### PR TITLE
 The 'expand students' button disappear after expanding panel #4352

### LINKED ISSUE #4352: The 'expand students' button disappear after expanding panel
image

### PR DESCRIPTION
**Pull request by yj-soh**
Fixes #4352

### CODE REVIEW

**Comment by LowWeiLin** [comment]
There are no tests for this?

**Comment by thyageshm** [comment]
@yj-soh could we complete this by today? this pr has been open for close to 2 weeks now

**Comment by yj-soh** [comment]
@LowWeiLin Unfortunately, to test this "feature", I believe we'll need a test to create over 500 responses which may not be very impractical for the reason below.

Like mentioned elsewhere, we will likely be removing this auto-collapse-on-many-responses behaviour, so if possible, let's run with this as a stopgap measure for the time being.
I'll make an issue for removing the `RESPONSE_LIMIT_FOR_COLLAPSING_PANEL` constant for further discussion later.

**Comment by LowWeiLin** [comment]
There is a parameter that can be used in the url to force the results to load via ajax. That way, you don't have to have 500 responses.

**Comment by yj-soh** [comment]
? The behaviour from loading via AJAX is different from what is caused from this issue.

It appears loading via AJAX resulting in a structure that is broken in a different way ("Expand Students" button on RQG view despite them already expanded), so that could be a new issue. As far as I can tell, though, using that functionality won't help in testing this issue.

**Comment by kanghj** [comment]
@yj-soh, do you think we can remove that constant <code>RESPONSE_LIMIT_FOR_COLLAPSING_PANEL</code> here? That will resolve this issue too, right? There will be no change to testing, because behaviour related to that constant has never been tested, as far as I know.

**Comment by yj-soh** [comment]
@damithc Should we remove the undocumented load-collapsed "feature" as @kanghj mentioned above? If it serves no feasible benefit, it may be better to remove it entirely rather than handling it as a sort of edge case.

**Comment by damithc** [comment]
Sure.

**Comment by thyageshm** [comment]
@LowWeiLin  @yj-soh, I am afraid this PR has been open for very long. Could we please try and complete it by this release?

**Comment by yj-soh** [comment]
@LowWeiLin @kanghj
I have removed the constant.
It's currently dev green after merging with master.

**Pull request merged**
