### PR TITLE
[#11215] Hide CollapseAll button when feedback session has no questions

### LINKED ISSUE #11215: Collapse All button visible when feedback session has no questions
- **Environment**: `master` branch at commit 744b69a.

**Steps to reproduce**
1. Create a new feedback session.
2. Delete all questions.

**Expected behaviour**
Collapse all button is hidden.

Screenshot 2021-06-21 at 9 49 04 PM

**Actual behaviour**
Collapse All button is not hidden. Clicking on the button does not do anything.

Screenshot 2021-06-21 at 9 47 34 PM

### PR DESCRIPTION
**Pull request by ChanwooJung1**
Fixes #11215

### CODE REVIEW

**Review by rrtheonlyone — APPROVED** [review]
@ChanwooJung1 Good to merge once you pull from master and fix the conflicts!

**Comment by madanalogy** [comment]
Looks like quite a lot of changes and the component tests are also not passing, let us know once it's resolved. Will switch PR to ongoing in the meantime

**Comment by halfwhole** [comment]
@ChanwooJung1 for your kind update on this PR as well! it should be a simple fix

**Comment by jianhandev** [comment]
@ChanwooJung1 Looks like it is a snapshot failure (see https://github.com/TEAMMATES/teammates/pull/11287/checks?check_run_id=3394182077#step:10:640), if you are not sure how to update snapshots this may help https://github.com/TEAMMATES/teammates/pull/11324#issuecomment-891662002.

**Comment by moziliar** [comment]
Closes due to inactivity since the last review 9 days ago. Please reopen it if you are still interested in continuing to this issue!

**Pull request closed without merging**
