### PR TITLE
Add side navigation for Help page #5616

### LINKED ISSUE #5616: Instructor help page: add side navigation
Currently, we are using the "back to top" method for users to navigate back to the contents listing, this can get quite tedious after a while.

Having a side navigation (something like the [bootstrap components page](http://getbootstrap.com/components/)) would make the help page more helpful.

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #5616

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Not reviewing this (unless arrowed), but I think you shouldn't change the indentation now because:
screen shot 2016-08-10 at 3 58 30 pm

**Comment by YongJieYongJie** [comment]
@wkurniawan07 The file is rather unwieldy without fixing the indentation (also because there are numerous stray opening or closing tags)

If I create another issue and PR to change the indentation, then the diff for this PR will be cleaner right?

**Comment by wkurniawan07** [comment]
@YongJieYongJie good idea :+1:

**Comment by wkurniawan07** [comment]
Closing as agreed.

**Pull request closed without merging**
