### PR TITLE
InstructorStudentListPageUiTest failing at dev server #6446

### LINKED ISSUE #6446: InstructorStudentListPageUiTest failing at dev server
As per title.

### PR DESCRIPTION
**Pull request by leeyimin**
Fixes #6446

Sorry about the trouble caused!

### CODE REVIEW

**Comment by wkurniawan07** [comment]
I expect this failure to occur (because I have encountered and fixed it locally 😛). To fix, add the following lines to `InstructorStudentListPage#verifyProfilePhoto`:
```java
JavascriptExecutor jsExecutor = (JavascriptExecutor) browser.driver;
jsExecutor.executeScript("arguments[0].scrollIntoView(true); window.scrollBy(0, -100);", photo);
```
between where `WebElement photo` is defined and `Actions action` is defined.

**Comment by leeyimin** [comment]
@wkurniawan07 I see :joy: Thanks and sorry!

**Comment by wkurniawan07** [comment]
Will merge immediately since many PRs are blocked by this.

@damithc apologies for this, but if there are any problems in this PR, we can work on it afterwards.

**Comment by damithc** [comment]
> Will merge immediately since many PRs are blocked by this.

Sure.

**Pull request merged**
