### PR TITLE
Hardcoded 1-2 Apr preventing dev green #5167

### LINKED ISSUE #5167: Hardcoded 1-2 Apr preventing dev green
Surprisingly this case is missed in #4857, perhaps because this one is in production code (instructor sample data). This is preventing Travis from getting a "passing" build.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5167

Travis should be able to reach green here.

### CODE REVIEW

**Comment by ashrayjain** [comment]
Thanks @wkurniawan07 !

**Comment by wkurniawan07** [comment]
Green as expected!

**Comment by damithc** [comment]
@ashrayjain for review

**Comment by ashrayjain** [comment]
The changes look fine to me.

**Pull request merged**
