### PR TITLE
Rich text boxes: make the toolbar appear over existing content #7063

### LINKED ISSUE #7063: Rich text boxes: make the toolbar appear over existing content
Currently, when the user clicks on a rich text form field, the formatting toolbar is inserted above the form field, shifting all elements below it. When the user clicks outside the form field after editing it, the toolbar disappears and elements below it shifts again. This jumping of page content gets in the way of a smooth user user experience. It can also result in 'mishit clicks' i.e. user tries to click a button but ends up clicking something else because content moves with the click.

Options:
1. make the toolbar stay fixed all the time
2. make the toolbar appear on top of the existing content above the form field (I believe this is the default mode but we changed it to the current behavior in a misguided attempt to improve user experience -- my bad 😢  )

Before clicking:
image

After clicking:
image

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7063 

~~Alternate Solution: PR #7421~~ 

**Outline of Solution:**

Removed `fixed_toolbar_container` to allow the tinyMCE editor to revert to its default behavior of hovering over existing content. Pull request created as per @damithc's request in PR #7421, to compare the outcomes of the two solutions proposed in the Issue Description.

Note: This solution will involve some clean-up work, as the `div` which was acting as the container no longer needs to be created. I will do this after it is decided which approach we are choosing.

### CODE REVIEW

**Comment by damithc** [comment]
The behavior feels acceptable. Shall we go ahead with it?

**Comment by HirdayGupta** [comment]
@damithc The issues with this behaviour brought up in #5775 would still be an annoyance to users, in my opinion. Is the amount of space taken by the behaviour in #7421 big enough a problem to supersede these issues? 

Not only does the hovering toolbar look unsightly, it also covers content that the user may want to refer to while typing in the rich text field.

**Comment by damithc** [comment]
> @damithc The issues with this behaviour brought up in #5775 would still be an annoyance to users, in my opinion. Is the amount of space taken by the behaviour in #7421 big enough a problem to supersede these issues?
> 
> Not only does the hovering toolbar look unsightly, it also covers content that the user may want to refer to while typing in the rich text field.

That was my initial feeling too and that's why I asked the original dev to change it. But over time I realized that may be the best option in the long run (probably that's why it is used as the default by the editor itself). For example, imagine if we decided to allow rich text for Rubric question options (i.e. every text box in the grid) or MCQ options. The whole 'edit session' page will be littered with so many toolbars while only one will be used at any time. :-p

**Comment by HirdayGupta** [comment]
@damithc Ahh okay. I hadn't thought about that. That makes sense. Will fully implement this behaviour and close the other PR! 😄

**Comment by HirdayGupta** [comment]
Ready for review

**Pull request merged**
