### PR TITLE
Tidy up email templates #5702

### LINKED ISSUE #5702: Tidy up email templates
Many rooms for tidying up such as:
- `<p/>` everywhere, but `<p>` is not a self-closing tag and even if it is, it is against our style guide to close it.
- HTML attributes not surrounded by quotes.
- No/extraneous EOL at the end of file.
- Missing punctuations/periods/space, weird line breaks, etc.

### PR DESCRIPTION
**Pull request by connorkendrick**
Fixes #5702 

In this branch, I've changed the p tags from self-closing `<p/>` to the correct format `<p></p>`. I've also corrected indentation issues, spacing issues, and placed quotes around HTML attribute values that didn't have any. Note: there may be other style issues that I've missed in these email templates.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Hi @connorkendrick, why is this PR closed?

**Comment by connorkendrick** [comment]
I couldn't get the Travis CI tests to work, even though I only changed a few minor things. I decided to close it until I figured out how to actually make contributions that pass the tests.

**Comment by connorkendrick** [comment]
@wkurniawan07 Alright, thank you. I'm really new to contributing to open source projects, and things going wrong on someone else's project is scarier to me than if it was my own project. I'll be working on this issue throughout this week, and figure out why the tests failed. Thanks again!

**Comment by wkurniawan07** [comment]
Hi @connorkendrick, any updates here?

**Comment by connorkendrick** [comment]
Hey @wkurniawan07, sorry that I'm taking awhile. I've read through the Travis CI log and have marked where the tests are failing. I've looked through the test files and couldn't find anything of use to tell me why they failed, so I have been setting up the project locally on my machine. I'll run the tests locally and see if I can find any solution. If I can't, my plan is to reset the HTML files to their original state, and change them one by one, testing as I go (as I probably should have done from the beginning).

**Comment by wkurniawan07** [comment]
Hi @connorkendrick, any updates here?

**Comment by wkurniawan07** [comment]
Closing due to inactivity.

**Pull request closed without merging**
