### PR TITLE
student feedback submit: Untick 'send confirmation email' option by default #6099

### LINKED ISSUE #6099: student feedback submit: Untick 'send confirmation email' option by default
This will help to reduce our email volume
image

### PR DESCRIPTION
**Pull request by stevesimpson4375**
Fixes #6099 

This change unticks the checkbox for the student feedback submit page. This will untick the boxes on the instructor pages as well; however, I think that is in the spirit of this issue.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Hi @stevesimpson4375, you are right that it includes the instructor page as well. However, the change introduced here causes some tests to fail (this is to be expected) which you have to fix.

**Comment by wkurniawan07** [comment]
@stevesimpson4375 another job well done :+1:

**Comment by wkurniawan07** [comment]
@damithc this one can be reviewed.

**Comment by damithc** [comment]
Can merge after fixing merge conflicts.

**Pull request merged**
