### PR TITLE
[#11205] Fix for Checkbox not aligned with text when choosing from template question

### LINKED ISSUE #11205: Checkbox not aligned with text when choosing from template question
- **Environment**: `master` branch at commit 476193c

**Steps to reproduce**
From the edit feedback session page, click Add New Question -> Choose from template questions.

**Expected behaviour**
Checkboxes are aligned with the text.

Screenshot 2021-06-18 at 8 24 03 PM

**Actual behaviour**
Checkboxes are not aligned with the text.
Screenshot 2021-06-18 at 8 19 16 PM

### PR DESCRIPTION
**Pull request by xyzhang00**
Fixes #11205 

Add margin around the checkboxes to align them with the text.

Screenshot 2021-06-21 at 8 34 59 PM

### CODE REVIEW

**Review by jianhandev — APPROVED** [review]
LGTM

**Review by rrtheonlyone — APPROVED** [review]

**Comment by damithc** [comment]
@xyzhang00 when there are multiple lines, would it look better if the check box appeared aligned to the first line rather than in the middle?

**Comment by xyzhang00** [comment]
@damithc Aligning by the top will look something like the following. Would this be better?

Screenshot 2021-07-11 at 10 55 41 PM

**Comment by damithc** [comment]
> @damithc Aligning by the top will look something like the following. Would this be better?

To me, this looks better. Others, any views to the contrary?

**Comment by rrtheonlyone** [comment]
I am okay with this look too!

**Comment by xyzhang00** [comment]
> > @damithc Aligning by the top will look something like the following. Would this be better?
> 
> To me, this looks better. Others, any views to the contrary?

In this case should I open another PR for the new look?

**Pull request merged**
