### PR TITLE
IDE REQUEST

### PR DESCRIPTION
**Pull request by dipzzzz**
Fixes #

**PR Checklist**

Ensure that you have: 
- [ ] Read and understood our PR guideline:  https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [ ] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ ] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

We can use ATOM for javascritp

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@dipzzzz, please learn how to use Git and GitHub first. If you keep doing this kind of actions blindly, I'm afraid I have no choice but to block you.

**Comment by dipzzzz** [comment]
No sir please don't block me. I want to contribute.

**Comment by dipzzzz** [comment]
I will refrain from doing this again.

**Comment by dipzzzz** [comment]
M sorry sir for doing that. I Learned but concepts but not getting how to
implement it, that's why I am getting wrong.

**Comment by dipzzzz** [comment]
I am* sorry sir for doing that.I learned the* concepts but not getting how
to implement it that's why I am going wrong.

**Comment by wkurniawan07** [comment]
@dipzzzz, I appreciate that you want to learn and contribute. There is nothing wrong with trying to apply what you learn, in fact it is natural. Your mistake was doing it in another person/organization's repository. You should have set up your own repository to figure things out. I'll give you an analogy: if an amateur gardener seeks to improve his/her skill, would you be happy if he/she practices in your garden?

**Comment by dipzzzz** [comment]
No sir I won't be happy. Thanks a lot sir for your apology.

**Comment by dipzzzz** [comment]
Sir I have cloned your repository into my account. So should I start
working on that cloned repository rather than original repository by
creating master and sub branches?

**Comment by dipzzzz** [comment]
Sir you blocked me?I didn't do anything purposefully sir. I wasn't knowing
that by doing changes in your repository directly I am harming our project.

**Comment by wkurniawan07** [comment]
@dipzzzz I didn't block you and I didn't think anyone else did. Where did you get that impression from?

**Comment by dipzzzz** [comment]
Nope sir. Just asking.I am learning and will contribute in right way to our
project.

**Pull request closed without merging**
