### PR TITLE
[#11784] instructor viewing the 'Students' page: sort chronologically by default

### LINKED ISSUE #11784: instructor viewing the 'Students' page: sort chronologically by default
v8.15.0

Steps: login as an instructor and go to the 'Students' page

Current: courses are sorted alphabetically

Suggestions
1. Sort chronologically by default, latest course on top
2. Optioanlly, provide a way to sort in other ways e.g., similar to how it is done in the Instructor home page
   image

### PR DESCRIPTION
**Pull request by fans2619**
Fixes #11784

### CODE REVIEW

**Comment by fans2619** [comment]
Almost the same as the sorting on the Home page.

**Comment by fans2619** [comment]
https://user-images.githubusercontent.com/68739475/170229209-c9d12b21-a70d-4281-bddd-232f263dc6c5.mp4

**Comment by damithc** [comment]
> Behaves almost the same as the sorting on the Home page.

The UX looks fine to me. 👍

**Review by ziqing26 — APPROVED** [review]
LGTM!

**Review by wkurniawan07 — APPROVED** [review]

**Pull request merged**
