### PR TITLE
Instructor: edit rubric question: allow moving columns #3910

### LINKED ISSUE #3910: Instructor: edit rubric question: allow moving columns
An instructor should be able to add a column and place it in between existing columns by dragging and dropping the column in the correct place. The new blank column is added to the right. Currently, the instructor has to cut and paste existing column contents to shift them to the right.

screen shot 2015-07-08 at 2 39 20 pm

### PR DESCRIPTION
**Pull request by VamsiSangam**
Fixes #3910 

**Outline of Solution**

- Two arrow buttons show up when question is in edit mode. Left arrow button click leads to column being swapped with the left column and vice-versa.
- Added tooltips.
- Modified `addRubricCol` to include buttons for the new column.
- Current state of UI -

tinytake30-05-2017-05-18-55

- When the left button for the left column is clicked nothing happens. Similarly for the right most column.

I created a `swapRubricCol(colIndex, questionNum, offset)` function in `questionRubric.es6`. It is a generic function which swaps contents of any 2 columns, identified by the column number provided by `colIndex` and `offset`. The column numbered `colIndex` and `colIndex + offset` are swapped. The left button has -

``` js
onclick="swapRubricCol(${col}, ${questionIndex}, -1)"
```
 and the right button has -

``` js
onclick="swapRubricCol(${col}, ${questionIndex}, 1)"
```

`swapRubricCol` first checks validity of the input and swaps the contents. By swapping we swap the values of input fields which is equivalent to manually copy pasting things in browser. The rubric choice and rubric weight fields are manually swapped. Then we iterate the rows swapping each `textarea` values.

If this UI and my implementation is acceptable, I will move to write testing code. Suggestions are much needed as this is my first big sized issue :sweat_smile:

### CODE REVIEW

**Comment by damithc** [comment]
Would it be better to add `move left` `delete` `move right` buttons at the bottom of the column?
image

**Comment by VamsiSangam** [comment]
I'll try to do that and come up with a demo @damithc sir :smile:

**Comment by VamsiSangam** [comment]
@damithc sir, this is a demo with buttons at the bottom -

demo

The last few seconds are due to #7409 .

This implementation is much more complicated than the one in this PR as it involved modifying a lot more files. So for the sake of preserving code, I wrote my above implementation in another local branch. If you feel that the above UI is better (I too think it is better :+1: ) , then I will close this PR and create a new one from my other branch. In which case, I will keep my old branch locally till a PR is merged.

**Comment by damithc** [comment]
Yes this UI is better. Can go ahead. I guess we need to fix #7409 before we merge this PR.

**Comment by VamsiSangam** [comment]
Ok sir, I'm closing this PR. I'll open a new one from the other local branch which has the implementation of the latter UI.

**Pull request closed without merging**
