### PR TITLE
[#8528] Instructor: view results: make the explanation of the view more informative

### LINKED ISSUE #8528: Instructor: view results: make the explanation of the view more informative
Current:
image

Suggestion:
1. Use an ascii arrow `→` rather than `>` (both in this view, and in the drop down menu)
2. Give a more precise tooltip based on the value e.g., `Group responses by giver, then by recipient, and then by question`

### PR DESCRIPTION
**Pull request by g-lilian**
Fixes #8528 

Changed '>' icon to ASCII arrow.

To clarify, does suggestion 2. mean dynamically changing the tooltip text based on the currently selected option in the dropdown list? The UI has changed quite a bit and differs from the SS in the issue.

*Ready for review

### CODE REVIEW

**Comment by ChooJeremy** [comment]
> To clarify, does suggestion 2. mean dynamically changing the tooltip text based on the currently selected option in the dropdown list? The UI has changed quite a bit and differs from the SS in the issue.

Yup, that would be the ideal case.

**Comment by g-lilian** [comment]
> Yup, that would be the ideal case.

Ok, will look into it.

**Comment by g-lilian** [comment]
Tooltip shows information about currently selected option. It initially defaults to 'View results in different formats'.
Screenshot_1

**Review by madanalogy — APPROVED** [review]
LGTM

**Review by t-cheepeng — APPROVED** [review]
LGTM 👍

**Pull request merged**
