### PR TITLE
Remove orphaned comment in FeedbackQuestionEditForm.java #5921

### LINKED ISSUE #5921: Remove orphaned comment in FeedbackQuestionEditForm.java
the header comments before the method `getQuestionIndex()` is obsolete and can be removed

```
    /**
     * @see {@link #getQuestionIndexIfNonZero}
     */
```

### PR DESCRIPTION
**Pull request by hiresh**
Fixes #5921

### CODE REVIEW

**Comment by chowyb** [comment]
Almost there, you just need to change the pull request name now.

**Comment by hiresh** [comment]
@chowyb Name of the pull request has been changed, let me know if there are some other issues, thanks for all the guidance :)

**Comment by chowyb** [comment]
@hiresh yep looks good now :+1:

**Comment by hiresh** [comment]
@chowyb thanks for all the guidance..looking forward to solve some serious bugs now :)

**Pull request merged**
