### PR TITLE
Test failing at InstructorFeedbackPageUiTest line 461 #4979

### LINKED ISSUE #4979: Test failing at InstructorFeedbackPageUiTest line 461
I did not take enough care when merging multiple PRs and got confused over which PR caused the test to fail and merged the wrong PR - I will fix this with a PR within the next few minutes

### PR DESCRIPTION
**Pull request by junhaoyap**
Fixes #4979

@wkurniawan07 could you help me take a quick look?

### CODE REVIEW

**Comment by wkurniawan07** [comment]
This doesn't look like "merging the wrong PR" to me, rather it's a case where the previously reached green was invalidated by changes in master branch. I trust that this is the only thing stopping us from dev green.

**Comment by junhaoyap** [comment]
Ah! You're right - I was trying to figure out what the problem is over ~15 mins and I couldn't figure out what was wrong so I assumed I must have made a huge mistake during the merging of PRs - thanks!

**Comment by junhaoyap** [comment]
And yes it's the thing stopping us from dev green

**Comment by junhaoyap** [comment]
Thanks @wkurniawan07 for the quick review I've merged this branch so we should be at dev green

**Pull request merged**
