### PR TITLE
Instructor: add new session: rename session template options #8563

### LINKED ISSUE #8563: Instructor: add new session: rename session template options
Current:
image

Suggested:
* `Session with my own questions` → `session with my own questions`. Reason: As this form is a way for the user to tell TEAMMATES what to do, `my` is more appropriate than `your`
* `Team peer evaluation session` → `session using template: team peer evaluation`

### PR DESCRIPTION
**Pull request by tanhengyeow**
Fixes #8563 

**Outline of Solution**

- Updated session template options as requested in `InstructorFeedbackSessionsPageData`.
- Updated relevant assertion tests in `InstructorFeedbackSessionsPageDataTest`.
- Updated the parameters of method `selectSessionType` in `InstructorFeedbackSessionsPageUiTest`.
- Updated relevant HTML pages using God Mode.
- Updated documentation in instruction help page.

**Changes in instructor's sessions page:**

image

**Changes in instructor's help page:**

> Getting Started > 4. Create a session
screenshot from 2018-03-09 23-23-26
screenshot from 2018-03-10 01-46-49

> screenshot from 2018-03-10 01-47-10
screenshot from 2018-03-10 02-44-07

### CODE REVIEW

**Comment by joanneong** [comment]
Your changes are in the right direction :) 

However, Travis is failing because you forgot to edit the expected HTML pages. Hint: you may find [God Mode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) useful here...

**Comment by tanhengyeow** [comment]
@joanneong 

Thank you! I'm actually on it now :smile:

**Comment by tanhengyeow** [comment]
Ready for review!

**Comment by tanhengyeow** [comment]
@joanneong 

Thanks for pointing out! I'll update the documentation 👍

**Comment by tanhengyeow** [comment]
These are the parts I changed in the instructor help page.

First change:
screenshot from 2018-03-09 23-23-26

Second change:
screenshot from 2018-03-09 23-23-47

Third change:
screenshot from 2018-03-09 23-24-13

I would like to check if starting the first letter with an uppercase in the second and third change is appropriate (because the sentence is a bullet point itself) since it appears as all lowercase in the template options.

**Comment by joanneong** [comment]
@tanhengyeow In this case, how about copying the session type ad verbatim, but wrapping in quotation marks instead? Like so:

"session with my own questions" and "session using template: team peer evaluation"

**Comment by tanhengyeow** [comment]
@joanneong Sounds great! I'll do that and update the changes!

**Comment by joanneong** [comment]
@tanhengyeow While Travis runs, I must tell you that you have still missed something out in the instructor help page. Just one last spot - can you find it?

**Comment by joanneong** [comment]
LGTM 👍

**Comment by damithc** [comment]
Need one more review by a @TEAMMATES/seniordevs .

**Pull request merged**
