### PR TITLE
Instructor: Results: Use separate result stats templates for MSQ questions instead of re-using MCQ templates #8894

### LINKED ISSUE #8894: Instructor: Results: Use separate result stats templates for MSQ questions instead of re-using MCQ templates
While working on #8860, I made changes to `feedbackQuestionMcqResultStatsTemplate.html` to add statistics for MCQ weight feature in the result page. But as MSQ questions also use MCQ result templates to create MSQ statistics, they also incorporated the changes, which is a problem as MSQ weight feature is not present yet. Which creates the following problem:
screenshot 516

So, as a work around to this problem, we should use separate templates for MSQ and MCQ question statistics until the weight feature is present in both of them.

**This is a temporary solution**

This will be reverted in #8895

### PR DESCRIPTION
**Pull request by sukanta-27**
Fixes #8894 

**Outline of Solution**

Added separate Result templates for MSQ questions so that it is not dependent on the design of MCQ template.

### CODE REVIEW

**Comment by sukanta-27** [comment]
@xpdavid @bqnguyen94 Ready for review. Please review it ASAP as it is blocking #8860

**Comment by sukanta-27** [comment]
>Do this in a separate PR instead of #8860 to make things easier.

@xpdavid I did not understand this. Are you talking about undoing this change in a separate PR or are you talking about doing the Calculation of statistics part in a separate PR?

**Comment by xpdavid** [comment]
@sukanta-27 You can actually do this change in #8860. But #8860 is messy enough :P

**Comment by xpdavid** [comment]
@sukanta-27 Note that the PR title is not as specified.

**Pull request merged**
