### PR TITLE
Instructor: edit session: add option to discard changes #7232

### LINKED ISSUE #7232: InstructorFeedbackEditPage: Add option to discard changes for session details
**Description of feature/enhancement**

We need to add a "Discard changes" option for the feedback session details too. Precisely speaking, when we try to edit a feedback question,

edit-feedback-3

we get these options -

edit-feedback-4

But when we edit the feedback session details, 

edit-feedback-1

we don't get a "Discard changes" option -

edit-feedback-2

(Icons appear because I tinkered with the code)

**Justification**

If the instructor wants to discard changes in the feedback details, he has no option but to reload the page, but by doing so, they will lose changes made to the feedback questions.

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7232 

**Outline of solution:**

- Add a `Discard Changes` button with the `glyphicon ban-circle` symbol to the feedbacksession forms header
- Button is visible only when FS is in edit mode and hidden otherwise
- On clicking, confirmation bootbox modal is shown and the callback function for the ok button in the modal resets the Feedback Session Edit form and disables edit mode.

**Todo:**
- Run godmode
- Add a test for visibility of modal
- Other possible tests? (Requesting assistance in deciding what tests would be needed for this)

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@damithc aside from the contents of this PR, just for my knowledge, is this what you meant by rebasing and did I do it correctly?

**Comment by damithc** [comment]
> is this what you meant by rebasing and did I do it correctly?

Looks like the branch is out-of-date. Do a rebase and force-push the branch to your fork.

**Comment by HirdayGupta** [comment]
Oops looks like I messed up the push (didn't force the push). Reverting the above commits and trying again.

**Comment by HirdayGupta** [comment]
@damithc Are the commits from 0e52fcc to 46130d7 (ignoring the reverted commits due to the mistake described in the previous comment) the expected result of the rebase and force push? It seems a little counter-intuitive that the previous commits reappear again, is there something I'm missing that avoids that?

Apologies for the messy PR. Will open a new one after figuring out the rebase workflow completely if you so recommend.

**Comment by damithc** [comment]
Make sure your master is exactly same as ours. It should not contain any extra merge commits.
After that, it is a matter of 
`git checkout your-branch`
`git rebase master`
`git push -f ...`

Anyway, git rebase is a general git thing and not specific to TEAMMATES or even GitHub. It takes some work to figure it out but there are plenty of resources on the Internet about it. Perhaps you should practice in a dummy repo first :-)

**Comment by HirdayGupta** [comment]
Hi @damithc, thanks for the help so far! I'm afraid I need to bother with you with this for just a little bit more 😅.

> Make sure your master is exactly same as ours. It should not contain any extra merge commits.

To do this, I tried to experiment on my own fork. 
- I created a branch of my master (the idea was for this new branch would serve as my "master" for all my experiments). I then ran `git reset --hard TEAMMATES/master` to make the "master" the exact same as TEAMMATES (without any extra merge commits). 
- I then made a branch off this branch and added a commit and PRed to my fork.
- Then, when the branch fell out of date I updated my "master" using the same `git reset` command and then, on the changed branch followed the steps you recommended.

However, on running `git push -f`, the commit was still pushed to the bottom of the conversation. You can see it [here](https://github.com/HirdayGupta/teammates/pull/3)

After reading some docs, I believe that pushing the commits to the bottom of the conversation is the intended behaviour of the rebase (since it is incorporating the changes and then reapplying my commits). So is there any special strategy I have to employ to ensure this doesn't happen? Would the git rebase's `--onto` tag come in handy here? Or `git pull --rebase`

**PS:** Would you suggest that I rebase only before starting my PR  and then use the merge commits to keep the PR up to date?

**Comment by damithc** [comment]
That is the intended behavior of rebase.  Yes, it does mess up the timeline of the conversation. To keep the timeline clean, you can use rebase only during the period before you create the PR.

**Comment by HirdayGupta** [comment]
Thank you so much @damithc! 😄 

Last question about this: Would it be okay to keep this PR open as it is and make the changes I need to make? Or would you recommending creating a new branch and PR because of the `revert commits`?

**Comment by damithc** [comment]
> Would it be okay to keep this PR open as it is and make the changes I need to make? Or would you recommending creating a new branch and PR because of the revert commits (71a1f07 --> 46130d7)?

Can continue with this PR. We squash everything into one commit at the point of merging anyway.

**Comment by whipermr5** [comment]
@HirdayGupta Looks like the test HTML files need updating.

**Comment by HirdayGupta** [comment]
**Ready for review.**

Requesting assistance with the following:

1. Suggestions for testing this feature
2. A close review of why the change in e6dce33 was necessary for the Travis build to pass. (Maybe @leeyimin can help here). It is a seemingly unrelated update to the `instructorHomeTestingSanitization.html` test resource by the `______TS("content: require sanitization");` test section in the `testContent()` method of the `instructorHomePageUiTest`.

**Comment by whipermr5** [comment]
> A close review of why the change in e6dce33 was necessary

Did you `npm run build` after updating the branch?

**Comment by wkurniawan07** [comment]
@HirdayGupta at least one of the following three commits 71a1f07, bd5e76c, 46130d7 are causing unnecessary changes here.

**Comment by HirdayGupta** [comment]
@wkurniawan07 would you suggest a new branch and new PR then?

**Comment by HirdayGupta** [comment]
@wkurniawan07 @whipermr5 @damithc closing in favour of #7626.

**Pull request closed without merging**
