### PR TITLE
HTML: Use `charset` attribute instead of `http-equiv` attribute to specify encoding #7878

### LINKED ISSUE #7878: HTML: Use `charset` attribute instead of `http-equiv` attribute to specify encoding
Let's replace all
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```
with
```html
<meta charset="utf-8">
```

---
While our [HTML style guide](https://oss-generic.github.io/process/codingStandards/CodingStandard-Html.html) did not specifically prefer either to specify encoding, the style guide should be updated to prefer `charset`.

Although the standard did not specify which is to preferred, their examples use the charset attribute as well.

```html
<!DOCTYPE HTML>
<HTML LANG="EN">
 <HEAD>
  <META CHARSET="UTF-8">
  <BASE HREF="https://www.example.com/">
  <TITLE>An application with a long head</TITLE>
  <LINK REL="STYLESHEET" HREF="default.css">
  <LINK REL="STYLESHEET ALTERNATE" HREF="big.css" TITLE="Big Text">
  <SCRIPT SRC="support.js"></SCRIPT>
  <META NAME="APPLICATION-NAME" CONTENT="Long headed application">
 </HEAD>
 <BODY>
 ...
```
https://html.spec.whatwg.org/multipage/semantics.html#the-head-element
https://www.w3.org/TR/html5/document-metadata.html#the-meta-element

Furthermore, in [Google's HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html#General_Meta_Rules):
> Specify the encoding in HTML templates and documents via \<meta charset="utf-8">. Do not specify the encoding of style sheets as these assume UTF-8.

The community is also in consensus that `charset` is preferred.
https://stackoverflow.com/questions/4696499/meta-charset-utf-8-vs-meta-http-equiv-content-type

MDN web docs also recommends using `charset`
> The <meta> element with a charset attribute is a synonym for the pre-HTML5 \<meta http-equiv="Content-Type" content="text/html; charset=IANAcharset">, where IANAcharset contains the value of the equivalent charset attribute. This syntax is still allowed, although no longer recommended.

https://developer.mozilla.org/en/docs/Web/HTML/Element/meta

### PR DESCRIPTION
**Pull request by stanislous**
Fixed #7878 

Replace all 'meta http-equiv="Content-Type" content="text/html; charset=UTF-8" ' to ' meta charset="utf-8" '.

### CODE REVIEW

**Comment by whipermr5** [comment]
@stanislous Please follow the PR naming conventions :) Also, the test HTML files need updating for the build to pass.

**Comment by stanislous** [comment]
@whipermr5 there are both .html and .jsp files exist in main. Is there a specific way to find their test files?

**Comment by whipermr5** [comment]
Run the failing tests listed in the build log locally with [GodMode enabled](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) to update the HTML files.

**Comment by stanislous** [comment]
@whipermr5 To try another issue, do I need to close this?

**Comment by whipermr5** [comment]
@stanislous No need! You can do both, as long as they're not first timer issues. Do change your PR title to follow the conventions.

**Comment by stanislous** [comment]
@whipermr5 Can you review this? :-)

**Comment by whipermr5** [comment]
@stanislous Please follow the PR naming conventions first :)

**Comment by stanislous** [comment]
@whipermr5 I think this is ok now :)

**Pull request merged**
