### PR TITLE
InstructorFeedbacksPageAction.java: change Feedbacks -> FeedbackSessions #7185

### LINKED ISSUE #7185: InstructorFeedbacksPageAction.java: change Feedbacks -> FeedbackSessions
Typo caught in the class /src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java. InstructorFeedbacksPageAction is not a word according to the provided dictionary. The 's' should be removed from Feedback, and the updated name should change across the project. 

CheckStyle did not catch. I believe it is the same as in #7155.

### PR DESCRIPTION
**Pull request by SELVAKUMAR-S**
Fixes #7185 
Ready for Review

**Outline of Solution**

Renamed required files and properties 
Named it in extended format InstructorFeedbackSessions(replaced 's' with 'Sessions')
Updated all references
Left JS and JSP (and tag files) pages as such instructorFeedbacks.js, nstructorFeedbacks.jsp(If required i can rename them too to make the codebase uniform)
Altered test files and their html resource files

### CODE REVIEW

**Comment by SELVAKUMAR-S** [comment]
Ready for Review

**Comment by SELVAKUMAR-S** [comment]
thanks @whipermr5 for the positive review feedback. Made required changes!!!

**Comment by whipermr5** [comment]
Are there any email templates that contain links to `/page/instructorFeedbacksPage`? If there are, existing emails already sent out would have broken links, and we should consider adding a redirect.

**Comment by SELVAKUMAR-S** [comment]
Hi John, i just did a text search for `instructorFeedbacksPage` on master branch and did not find any match  under  `src/main/resources`. Please correct me if i am wrong.

**Comment by SELVAKUMAR-S** [comment]
@wkurniawan07, did changes as requested!!. Ready for Review

**Pull request merged**
