### PR TITLE
wrong status message #4021

### PR DESCRIPTION
**Pull request by AnaghHegde**
updated Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE to Const.StatusMessages.STUDENT_DELETED

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@AnaghHegde do follow the workflow as lined out in [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md). Your PR title and PR description both do not satisfy what is required of each, and you should work on a new branch instead of `master`.
In addition there is a minor test failure that you need to fix.

**Comment by AnaghHegde** [comment]
@wkurniawan07 ok. I will work on it.

**Comment by wkurniawan07** [comment]
@AnaghHegde I just realized that you changed a test code without changing any part of the production code, not the other way around. You need to figure out where the constant in used in the production code (`src/main/*`) and change accordingly.

**Comment by AnaghHegde** [comment]
@wkurniawan07 i didn't notice that.Thanks for pointing it out.I will work on it.

**Comment by AnaghHegde** [comment]
@wkurniawan07  changes need to be applied to this file master/src/main/*/AdminAccountDeleteAction.java   .

**Comment by wkurniawan07** [comment]
Superseded by #6299.

**Pull request closed without merging**
