### PR TITLE
Instructor: existing feedback sessions with fixed offsets: reduce occurrence of confirmation modals #8748

### LINKED ISSUE #8748: Instructor: existing feedback sessions with fixed offsets: reduce occurrence of confirmation modals
- **Environment**: `master` branch at commit dc85dd0

**Steps to reproduce**

After TEAMMATES have switched to auto-detecting the geographical time-zone, instructors are reminded of this new feature when they start a new feedback session/ when they first edit a feedback session.

screen shot 2018-04-03 at 1 30 45 pm

1. In the Instructor Sessions page, pick an existing feedback session that was created before this new feature was implemented.
2. Edit the feedback session.
3. Add/delete a question.
4. Observe that the confirmation modal above appears every single time a question is added/deleted.

screen shot 2018-04-03 at 1 17 44 pm

**Justification**
Although the feature works well for new feedback sessions created after the feature was implemented, it is annoying for existing feedback sessions as the modal will appear after every single question edit. The behaviour of the modal should be consistent - the modal should only appear once when you first access a feedback session.

P/S Can someone check if this issue is reproducible on their copy of TEAMMATES?

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #8748

**Outline of Solution**
- Allow user to upgrade an existing session to the geographical time zone with a single click (clicking `Correct` automatically saves the session)
<br>screen shot 2018-04-04 at 12 28 48 am
<br>apr-04-2018 00-31-56
- ~~When copying from sessions using fixed offset time zones, use detected geographical time zone~~
  - ~~When creating a single new session, use the client-detected time zone~~
  - ~~When copying an existing session to multiple courses, use each destination course's time zone~~
- When copying sessions, use destination course time zone

### CODE REVIEW

**Comment by whipermr5** [comment]
Well, the course time zone might not be accurate for all courses, particularly those created before #5863. I realised that the [migration script](https://github.com/TEAMMATES/teammates/pull/5863/files#diff-bf893c7329d4722365232e36e8172be5) from that PR used an arbitrary mapping from offset to geographical zone.

**Comment by whipermr5** [comment]
My rationale for using the client detected time zone for a single copied session is that creating such a session is similar to creating a new session manually, and should behave the same way. The current behaviour for manual creation of sessions is that time zone is autodetected, as it is more reliable than using the course time zone. Course time zone is only reliable for courses created after August 2016.

**Comment by tran-tien-dat** [comment]
and the reason for not doing the same for multiple courses?

**Comment by whipermr5** [comment]
My rationale for multiple courses is that it's entirely possible for different courses to have different time zones. It is no longer a safe assumption that the desired time zone is the client time zone.

**Comment by tran-tien-dat** [comment]
Thanks @whipermr5 and sorry if I sounded like interrogating. I just wanted to see all your reasons first before continuing. 

I think for a new session, the timezone detection is more like a convenience feature. It's our guess (**not an assumption**) and we expect users to change it if our guess is wrong. Hence, it is different from the behaviour of **assuming** that our timezone detection is correct and **assuming** that the new duplicate feedback session should be in the instructor machine's timezone. Here we are turning what we guessed into assumptions that we based our actions on. That does not sound very good to me.

For multiple courses, your concern can also be applied for a geographical timezone, but we don't handle the problem then. I think we are not too worried about whether the duplicate timezone is the same as the real timezone of the course. We just want to make the copy operation simple - copying the exact details of the feedback session.

From what I have said above, it seems to me that maybe *automatically* choosing a geographical timezone, whether by browser-detection or deduced from course, is not a good behavour. How about we just don't do anything and allow the offset timezone to be duplicated? As I said before, most likely, the users will edit the session to set the time correctly, so he/she will be prompted to set a geographical time zone then. This would also avoid handling these cases in the code which increases the code's complexity.

**Comment by whipermr5** [comment]
Hey @tran-tien-dat, it's fine! I should have stated my rationale more clearly anyway haha.

> For multiple courses, your concern can also be applied for a geographical timezone, but we don't handle the problem then.

That's true; I missed that 😅

> I think we are not too worried about whether the duplicate timezone is the same as the real timezone of the course. We just want to make the copy operation simple - copying the exact details of the feedback session.

Good point.

> From what I have said above, it seems to me that maybe automatically choosing a geographical timezone, whether by browser-detection or deduced from course, is not a good behavour. How about we just don't do anything and allow the offset timezone to be duplicated? As I said before, most likely, the users will edit the session to set the time correctly, so he/she will be prompted to set a geographical time zone then. This would also avoid handling these cases in the code which increases the code's complexity.

This is good for correctness, but not good for usability. The second commit in this PR arose because @damithc asked me to take a look at the behaviour for copied sessions where the source session uses a fixed offset time zone. If the newly copied session follows the fixed offset time zone, the user will get the modal prompt for every single session newly copied from the source session, which can be very annoying to the user. He made the point that most users probably do not even think about time zones, and the process should be as seamless as possible without interrupting the user unless absolutely necessary.

Actually, the ideal solution would be to do the actual migration to course time zone (#5928) now. The user should get a modal confirmation per course created in/before August 2016 for them to set the correct time zone. After answering that prompt, the course, as well as all sessions within it, should be updated to the time zone that the user confirmed/selected. For courses created after August 2016, we can just update all sessions within it to use the course time zone. This will ensure correctness while minimising inconvenience to the user.

My concern is that I may not have time to implement the ideal solution 😅

**Comment by whipermr5** [comment]
> I think for a new session, the timezone detection is more like a convenience feature. It's our guess (not an assumption) and we expect users to change it if our guess is wrong. Hence, it is different from the behaviour of assuming that our timezone detection is correct and assuming that the new duplicate feedback session should be in the instructor machine's timezone. Here we are turning what we guessed into assumptions that we based our actions on. That does not sound very good to me.

Actually I just realised that setting the wrong time zone doesn't really have adverse consequences, now that we have migrated to UTC time fields. The time zone only affects the display of the session start/end/visible/publish time, not the interpretation of the time - they will still open/close/ become visible/published at the same instant in time.

Perhaps I should just write a migration script to change all sessions to course time zone, then disable editing of session time zone at the action level. The UI can show the session time zone as read-only, with a tooltip telling the user that it follows the course time zone. If the user changes the course time zone, we can cascade the change to all sessions within the course.

**Comment by tran-tien-dat** [comment]
> Perhaps I should just write a migration script to change all sessions to course time zone, then disable editing of session time zone at the action level. The UI can show the session time zone as read-only, with a tooltip telling the user that it follows the course time zone. If the user changes the course time zone, we can cascade the change to all sessions within the course.

I think that's a good idea. If that's implemented then the copy behaviour in this PR should be using the destination's timezone?

**Comment by whipermr5** [comment]
> If that's implemented then the copy behaviour in this PR should be using the destination's timezone?

Yes. In fact the whole confirmation modal thing can be removed. @damithc are you okay with the new approach of just following the course time zone for all sessions?

**Comment by tran-tien-dat** [comment]
> In fact the whole confirmation modal thing can be removed
I think this is a bit too radical. Even though changing the stored timezone field does not affect the actual open/close timings, it affects how these timings are displayed to users, both instructors and students. So I think all users should be informed, probably by a one-time modal. Instructors should be advised to confirm course timezones. Students should be informed of the timezone currently being used, and be advised to alert their instructors if it is not correct.

**Comment by damithc** [comment]
> Perhaps I should just write a migration script to change all sessions to course time zone, then disable editing of session time zone at the action level. The UI can show the session time zone as read-only, with a tooltip telling the user that it follows the course time zone. If the user changes the course time zone, we can cascade the change to all sessions within the course.

This was the original plan when we introduced time zone to the course. 

> I think this is a bit too radical. Even though changing the stored timezone field does not affect the actual open/close timings, it affects how these timings are displayed to users, both instructors and students. So not informing users about the change will likely cause confusion. I think all users should be informed, probably by a one-time modal. Instructors should be advised to double-check course timezones. Students should be informed of the timezone currently being used, and be advised to alert their instructors if it is not correct.

Students may not be in a position to do this checking as they can be in different time zones from the course. Besides, no point all students checking the time zone of the same course. A one-time modal per instructor may be acceptable but a modal for each course/session could be a bit too much. As far as users are concerned, time zone is not something they need to bother about (supposed to be auto-detected by the app). On the other hand, we can show this info in an existing status message or a modal that is already part of the current workflow?

**Comment by whipermr5** [comment]
> A one-time modal per instructor may be acceptable but a modal for each course/session could be a bit too much.

I'm thinking of a one-time modal that pops up the next time an instructor loads any instructor page. All courses that have unconfirmed time zones will be listed, with a time zone dropdown beside each course showing the current value of the course time zone. The instructor just needs to click confirm once, and the modal will never appear again for that instructor, or any of the other instructors of those courses (unless they also teach other courses that have not been updated). If the instructor dismisses the modal without confirming, it will pop up again on the next page load of any instructor page, encouraging the instructor to confirm it. Would this be acceptable?

**Comment by damithc** [comment]
> I'm thinking of a one-time modal that pops up the next time an instructor loads any instructor page. All courses that have unconfirmed time zones will be listed, with a time zone dropdown beside each course showing the current value of the course time zone. The instructor just needs to click confirm once, and the modal will never appear again for that instructor, or any of the other instructors of those courses (unless they also teach other courses that have not been updated). If the instructor dismisses the modal without confirming, it will pop up again on the next page load of any instructor page, encouraging the instructor to confirm it. Would this be acceptable?

Yes, but wouldn't this need adding a new entity type (to track if the instructor confirmed)?

**Comment by damithc** [comment]
> Not a new entity type, but a new flag on the course entity isTimeZoneVerified. With Objectify, it's painless to add and later remove.

Sounds good, but we are unlikely to be able to remove it because there can be instructors who are not using TEAMMATES anymore. Also, how will this affect UI tests?

An alternative is to do a one time force migration and email all instructors (at least the ones who were active in the last 2 years) asking them to double-check time zones of their courses. In the same email we can mention support for DST.

**Comment by whipermr5** [comment]
> An alternative is to do a one time force migration and email all instructors (at least the ones who were active in the last 2 years) asking them to double-check time zones of their courses. In the same email we can mention support for DST.

Yes; this sounds better. Will implement the migration script.

**Comment by tran-tien-dat** [comment]
Just to clarify,  we are removing feedback timezone totally and will query the course's timezone when timezone is needed, or are we just making the feedback timezone unchangeable by the user and update it every time the course timezone is changed? I would prefer the former as there's only one point of reference for the timezone. But the later approach is more convenient and we will need minimal change to implement.

**Comment by whipermr5** [comment]
> Just to clarify, we are removing feedback timezone totally and will query the course's timezone when timezone is needed, or are we just making the feedback timezone unchangeable by the user and update it every time the course timezone is changed? I would prefer the former as there's only one point of reference for the timezone. But the later approach is more convenient and we will need minimal change to implement.

For now it'll be the latter. Can consider switching to the former in future.

**Comment by whipermr5** [comment]
Closing as this is superseded by #8759.

**Pull request closed without merging**
