### PR TITLE
[#8465] Instructor: edit question: distribute question options vs recipients tooltip (UI)

### LINKED ISSUE #8465: Instructor: edit question: distribute question options vs recipients tooltip (UI).
**Description of feature/enhancement**

Currently, the tooltip for total points to distribute in 'Distribute points (among options)' should be describing options which is correct. On the other hand, the tooltip for total points to distribute in 'Distribute points (among options)' should be describing distributing points among recipients but it is now describing about distributing it among options.

Distribute in options:
image

Distribute in recipients:
Still mentioning about distributing it in options.
image

We can change the tooltip for the Distribute Question (for recipients) to talk about recipient instead of option.

**Justification**

Instructors will benefit when by having less confusion with the type of question they are actually selecting.

This can be a `d.FirstTimers` issue.

### PR DESCRIPTION
**Pull request by bezalelBU**
Fixes #8465 
Instructor: edit question: distribute question options vs recipients tooltip (UI)

**PR Checklist**
gradlew.bat and npm lints have passed.

Solution: Changed tooltip text

### CODE REVIEW

**Review by madanalogy — APPROVED** [review]
LGTM

**Comment by rrtheonlyone** [comment]
Nice work 💯 

Some additional things we can add onto this PR:

### Distribute Points Among Options Question

Screenshot 2020-12-13 at 3 07 50 PM

The above tooltip should be referring to **options** instead of **recipients**.


### Distribute Points Among Recipients Question

Screenshot 2020-12-13 at 3 09 57 PM

The bottom should be `X (number of recipients)` - it multiplies by the number of recipients.

**Comment by bezalelBU** [comment]
@rrtheonlyone, thank you, I will commit the additional changes.

**Comment by bezalelBU** [comment]
@madanalogy, thank you!

**Comment by bezalelBU** [comment]
@madanalogy, @rrtheonlyone 
Hello, I am sorry, I am still getting the hang of the workflow process. The changes were made, and the PR is ready for review again.

**Review by rrtheonlyone — APPROVED** [review]
LGTM 👍

**Pull request merged**
