### PR TITLE
removed raise edge from home page , feature page

### LINKED ISSUE #12186: raise-edge image should be removed
raise edge image should be removed from home page .

- **Environment**: 

**Steps to reproduce**
- open this page on any browser : https://teammatesv4.appspot.com/web/front/home
- take look at below the request a free instructer account  button 

**Expected behaviour**
Screenshot (86)

**Actual behaviour**
Screenshot (85)

**Additional info**

### PR DESCRIPTION
**Pull request by sumitshinde-84**
Fixes #12186 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Review by weiquu — CHANGES_REQUESTED** [review]
Hi @sumitshinde-84, seems that the changes to package-lock.json are still there. Do also remember to merge the latest changes from master into your branch.

**Comment by sumitshinde-84** [comment]
> Hi @sumitshinde-84, seems that the changes to package-lock.json are still there. Do also remember to merge the latest changes from master into your branch.

i am sorry @weiquu  can you please revert package.lock.json file or copy from main branch because i am facing issue if i push my current branch it has issue now because i have tried to revert changes  .

**Comment by sumitshinde-84** [comment]
> > Hi @sumitshinde-84, seems that the changes to package-lock.json are still there. Do also remember to merge the latest changes from master into your branch.
> 
> i am sorry @weiquu can you please revert package.lock.json file or copy from main branch because i am facing issue if i push my current branch it has issue now because i have tried to revert changes .

or can i copy and paste package.lock.json file

**Comment by sumitshinde-84** [comment]
@zhaojj2209 need help

**Comment by weiquu** [comment]
Hi @sumitshinde-84, I suggest you first merge the latest changes from `master` into your branch. You can find more information on how to do so via the GitHub docs, for instance [this page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

One part of becoming a good OSS contributor and even a good software engineer in general is the ability to find and test possible solutions on your own. If you could let me know what you've tried (other than just copying and pasting, which has been proven not to work), then it would be easier to help you.

**Comment by zhaojj2209** [comment]
@sumitshinde-84 Please do not treat Github like a chat application, we do not appreciate excessive spamming. We are also not expected to spoonfeed you or do your work for you.

If you would like to continue contributing to open source projects, it would serve you well to learn to troubleshoot basic technical issues (e.g. using Git, learning the tech stack for the project) independently (more often than not the solution can be found on Google), and approach the maintainers for technical help that is more project-specific. @weiquu has gone above and beyond to help you out despite your conduct thus far, please do not take it for granted, other open source projects may not be as kind.

Please do your best to resolve the rest of the issues on your own, we sincerely hope that the next time we review this PR, it will be ready to merge.

**Pull request closed without merging**
