### PR TITLE
[#11755] Session closing soon' email: highlight 'No action is required if you have already submitted

### LINKED ISSUE #11755: 'Session closing soon' email: highlight 'No action is required if you have already submitted'
v8.14.1, production

Suggestions: When sending the 'Session closing soon' emails for a session
* Tweak `The following feedback session is still open for submissions.` -> `Just a gentle reminder that the following feedback session is still open for submissions, in case you have not submitted yet or wish to update your submission.`
* Highlight the phrase (i.e., `<mark>...</mark>`)  'No action is required if you have already submitted.' and place it to follow the sentence mentioned above.

Reason: To reduce support requests such as these from students:
>I already submitted my feedback so I am not sure why I am still receiving the message below.
>Please advise

### PR DESCRIPTION
**Pull request by chenxu-wang**
Fixes #11755

**Outline of Solution** 

Tweak **The following feedback session is still open for submissions.** to **Just a gentle reminder that the following feedback session is still open for submissions, in case you have not submitted yet or wish to update your submission.** 

Change the FEEDBACK_STATUS_SESSION_OPEN in EmailGenerator and userEmailTemplate-feedbackSession.html.
 
Make same changes in **src/test/resources/emails/** for test cases: 

The affected email would be like the following screenshot.
Screen Shot 2022-05-10 at 11 28 23 PM

### CODE REVIEW

**Comment by damithc** [comment]
@chenxu-wang Let us know when ready for review. Remember to post screenshots of affected email samples.

**Comment by chenxu-wang** [comment]
> @chenxu-wang Let us know when ready for review. Remember to post screenshots of affected email samples.

It's ready for review. Thanks! :)

**Comment by damithc** [comment]
Suggestion: Move this phrase as follows, and use `<mark>` around them.
image

**Comment by zhaojj2209** [comment]
@chenxu-wang Any updates on the PR? Do let us know once the suggested change has been implemented.

**Comment by zhaojj2209** [comment]
Closing due to inactivity. @chenxu-wang feel free to reopen this PR if you would like to resume working on it and the issue is still open.

**Pull request closed without merging**
