### PR TITLE
[#11883] Admin/maintainer logs: Fix UI for small screen sizes

### LINKED ISSUE #11883: Partially hidden number in search period input
- **Environment**: live server at V8.17.0

**Steps to reproduce**
image

1. Go to https://teammatesv4.appspot.com/web/maintainer/stats
2. Observe time input for "Search period from" and "Search period until"

**Expected behaviour**
Whole number in the time input boxes should be seen

**Actual behaviour**
Part of the number is cut off.

**Additional info**
Found on a 12 inch Macbook. 

Reduce padding for input

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Fixes #11883 

**Outline of Solution**

Fixed the UI for screens of all sizes.

Desktop:

Screenshot 2022-07-06 at 7 24 40 PM

Tablet:

Screenshot 2022-07-06 at 7 25 01 PM

### CODE REVIEW

**Review by zhaojj2209 — APPROVED** [review]
LGTM

**Comment by sivayogasubramanian** [comment]
> On tablet, could there be a left margin for the pages? As there seems to be margin on the right hand side only

@ziqing26 I don't really get what you are saying 😅. What left margin and right margin are you talking about?

**Comment by ziqing26** [comment]
> > On tablet, could there be a left margin for the pages? As there seems to be margin on the right hand side only
> 
> @ziqing26 I don't really get what you are saying 😅. What left margin and right margin are you talking about?

From the screenshot, the left side text seems too close to the edge, compared to right side of screen.

**Comment by sivayogasubramanian** [comment]
@ziqing26 My earlier screenshot was zoomed in a bit. Sorry about that. This is the new zoomed out tablet view.

Screenshot 2022-07-08 at 8 24 39 PM

**Pull request merged**
