### PR TITLE
Replaced instances of Const.EOL with System.lineSeparator()#8299

### LINKED ISSUE #8299: Replace all instances of `Const#EOL` with `System#lineSeparator()`
It is preferable not to use a constant for a line separator and the standard library offers a much better alternative.

### PR DESCRIPTION
**Pull request by ManognaMutyala**
I would like to make changes in other modules too soon if these are the expected changes to be made.

Fixes #8299

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

### CODE REVIEW

**Comment by LiHaoTan** [comment]
@ManognaMutyala yes these are the changes to be made.

**Comment by wkurniawan07** [comment]
@ManognaMutyala it will be much faster if you do a workspace-wide search-and-replace with text editors/IDEs, rather than looking at every single file one by one on GitHub and doing manual search-and-replace.

**Comment by ManognaMutyala** [comment]
Thanks for the advice @wkurniawan07 ,I was very late in seeing in your comment! I would definitely try it out from next time as I finished replacing all files.

**Comment by wkurniawan07** [comment]
@ManognaMutyala are you really sure these are all the replacements needed? Hint: if it is the case, will removing the `EOL` variable from the `Const` class cause a compile error?
On a related note, have you checked that your changes will not cause any compile error and/or lint violations?

**Comment by ManognaMutyala** [comment]
@wkurniawan07  I think it wouldn't cause any error because System.lineSeparator() does the same function as Const.EOL.I haven't checked if it would cause compile time error.

**Comment by wkurniawan07** [comment]
> I haven't checked if it would cause compile time error.

@ManognaMutyala you should have checked before saying that you are "finished". Imagine if you are a project maintainer, will you be happy if you receive a patch that does not even compile?
I have unchecked the things in the PR checklist that you definitely did not do. Make sure all of them are done before requesting for review.

**Comment by ManognaMutyala** [comment]
I am really sorry for the mistake.I would assure you that I will never repeat the above mistake and will follow the guidelines properly.

**Comment by wkurniawan07** [comment]
Closing as the linked issue has been resolved.

**Pull request closed without merging**
