### PR TITLE
TEAMMATES logo displaced #6746

### LINKED ISSUE #6746: TEAMMATES logo displaced
This is the current view on the live server when logged in:

screen shot 2017-03-07 at 12 13 14 am

### PR DESCRIPTION
**Pull request by Dartteon**
Fixes #6746

**Outline of Solution**
Landing page (staticPage) uses the TEAMMATES logo for the home button in the navBar .tag file.
```
<a class="navbar-brand" href="/index.jsp">
    <img height="100%" src="/images/teammateslogo.jpg" alt="TEAMMATES[Logo] - Online Peer Feedback/Evaluation System for Student Team Projects">
</a>
```
The other .tag pages(/admin, /errorPage, /helpPage, /instructor, /student) are using a string literal for the same <a> component.
```
<a class="navbar-brand" href="/index.jsp">TEAMMATES</a>
```

**What I have done**
For each of the .tag files of the various pages, I changed the navBar component to use the image instead of string "TEAMMATES"

**Before**
image

**After**
image

### CODE REVIEW

**Comment by junhaoyap** [comment]
@Dartteon the test is failing, please refer to CI to find out the cause of failure

**Comment by Dartteon** [comment]
@junhaoyap I found out that the test is failing because it's checking against a hard-coded HTML file, which is hard-coded in the old style (string literal TEAMMATES instead of logo image).

What course of action should I take? Do I have to edit all of the test HTML files to make the test pass?

image

**Comment by chowyb** [comment]
@Dartteon you will need to use [GodMode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) to update the test HTML files.

**Comment by Dartteon** [comment]
Alright, I will try to use GodMode to update the test HTML files. Just to be sure, I will be pushing the updated test files too, right?

Also, thank you for the clarification. Will edit the PR title accordingly.

**Comment by whipermr5** [comment]
@Dartteon That's right! Also check that after GodMode updates the files, only the relevant parts have changed. If unrelated parts are changed, it might be due to problems in your config.

**Comment by whipermr5** [comment]
@Dartteon Also, referring to [my comment on your other PR](https://github.com/TEAMMATES/teammates/issues/6747#issuecomment-285265361), maybe you can look into the possibility of having the actual image path appear only in one file? I.e. make a `navBarBrand.tag` that references the image and use it in all the current `.tag` files.

**Comment by Dartteon** [comment]
@whipermr5 That seems to be a clean way to solve this. 

I will look into referencing the navBarBrand.tag from other .tag files!

**Comment by whipermr5** [comment]
@Dartteon Any updates on this? :)

**Comment by Dartteon** [comment]
@whipermr5 Hello! Sorry for the delay, I was really swamped with projects over the last week and have been trying to get the testing and GodMode to work.. 

I thought I could resolve the testing issues myself but I finally cave in and made a new issue.

I have actually figured out the way to make a separate navBarBrand tag and make all of them reference that for the brand, but with tests failing, I am unable to push the code.

I will try to resolve the issue ASAP (I'm just done with two presentations today) and will most probably make a new PR. Sorry for the trouble!

**Comment by whipermr5** [comment]
@Dartteon No worries at all; totally understand! Sorry if I made you feel pressured 😅

**Comment by Dartteon** [comment]
Made a new PR at https://github.com/TEAMMATES/teammates/pull/6836 - will be closing this

**Pull request closed without merging**
