### PR TITLE
Instructor view results, group by recipient: 'No specific recipient' shown wrongly #7044

### LINKED ISSUE #7044: Instructor: view results, group by recipient: fix 'No specific recipient' showing questions with specific recipients
v5.100

These questions have specific recipients but are shown as `No Specific Recipient`

image

### PR DESCRIPTION
**Pull request by basitsattar**
Fixes #7044 

Changed the code to add default section only if sections list is empty. Also changed javascript code which was removing the first section on click.

### CODE REVIEW

**Comment by basitsattar** [comment]
Some tests are failing because of change in UI. Can someone guide me about the changes that'll need to be done in browser tests? Am I supposed to copy new HTML to src/test/resources HTML files?

**Comment by chowyb** [comment]
@basitsattar you might want to have a look at [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md), which allows for easy updating of test HTML files.

**Comment by wkurniawan07** [comment]
@basitsattar you need to resolve the merge conflicts.

Also, how does what you did in this PR (add default section only if sections list is empty, removed the javascript code which was removing the first section on click) resolve the issue at hand?

**Comment by basitsattar** [comment]
@wkurniawan07 I have removed the java code which was adding a default section "No specific recipient" on the top of target groups and the javascript was removing that first section (default section) on click. But when I removed the code which was adding the default section in the first place, the javascript was still hiding the first panel which was not default. So I removed the code to hide the first panel. 
Also, computers power ic got damaged due to which I am currently unable to work on this. Is it possible that somebody can work on it or I can close this commit and someone else can work on this issue?

**Comment by basitsattar** [comment]
Due to some reasons, I'll be unable to work on this project for the next week. So I am closing this pull request.

**Pull request closed without merging**
