### PR TITLE
[#10594] Fixed instructor page course edit spinner

### LINKED ISSUE #10594: Instructor edit course details page: loading spinner for edit does not disappear
**Steps to reproduce**

Go to edit course details page, edit an instructor, click save changes. Then click edit again and choose cancel this time.

**Expected behaviour**

The spinner next to edit should not be shown.

**Actual behaviour**

The spinner next to edit appears and stays there. Also, the spinner is inconsistent with editing course details: when saving course details, spinner appears next to save changes button:
image

However, when saving instructor details, spinner appears next to edit button:
image

May be better to standardise the two.

### PR DESCRIPTION
**Pull request by brandedcow**
Fixes #10594 

Reset bool on cancel

### CODE REVIEW

**Review by t-cheepeng — COMMENTED** [review]
Thanks for contributing @brandedcow. Could you post a screenshot/gif on your fix so we can verify that the fix works.

**Comment by brandedcow** [comment]
gif

**Comment by t-cheepeng** [comment]
> image

@damithc Would it better for the `Save Changes` button for editing an instructor stay until the saving is done(like how it is for editing the course details). Right now, the button will disappear immediately once user clicks on the `Save Changes` button

**Comment by brandedcow** [comment]
I am having trouble syncing changes with the master branch, will make a new PR.

**Comment by brandedcow** [comment]
https://github.com/TEAMMATES/teammates/pull/10654

**Pull request closed without merging**
