### PR TITLE
Remove AdminSearchTaskServlet and all its references #5258

### LINKED ISSUE #5258: Remove AdminSearchTaskServlet and all its references
Its usage is deprecated in #2280. The removal involves:

- `AdminSearchTaskServlet.java`
- A few lines referring to that in `web.xml`.

### PR DESCRIPTION
**Pull request by HooDeLin**
Fixes #5258

### CODE REVIEW

**Comment by damithc** [comment]
Thanks for the PR @HooDeLin 
A few test cases are failing. Can you get them to pass on your own machine?

**Comment by HooDeLin** [comment]
Sorry, my bad. I forgot to remove the servlet mapping on web.xml

**Comment by wkurniawan07** [comment]
Thanks for the PR @HooDeLin! There are two more things you need to do:
- `web.xml` has one more `/searchTask` instance in line 266, you should remove that as well.
- I didn't mention this in the issue, but check the constants `Const.SystemParams.MAX_NUM_OF_INPUT_FOR_APP_ENGINE_BATCH` and `Const.SearchIndex.STUDENT`, and remove the ones that are now unused.

**Comment by HooDeLin** [comment]
The instances and the constant has been removed. `Const.SearchIndex.STUDENT` is still in use by the storage

**Comment by wkurniawan07** [comment]
Good work @HooDeLin! :+1:

**Pull request merged**
