### PR TITLE
[#10662] Fix masquerade mode not working for new tabs

### LINKED ISSUE #10662: Masquerade mode doesn't work when using right-click menues
Suppose the admin is masquerading as an instructor and is in the instructor home page.
Clicking on a menu item or a button (e.g., view students of a course) works as expected -- i.e., can masquerade
But accessing a page via right-clicking the same item seems to cause an access error

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #10662 

**Outline of Solution**

1. Implement custom `tmRouterLink` directive to add `user` query param to all hyperlinks if the current URL has the `user` param.
2. Remove code within `app.component.ts` previously used to sync masquerade mode. Now masquerade mode should be determined only by the URL `user` param
3. Modify `NavigationService` to preserve `user` param
4. Change `routerlink` to `tmRouterlink` for **all** usage.

### CODE REVIEW

**Comment by damithc** [comment]
@ccyccyccy can speed this up? A crippled masquerade mode is really hampering user support. Without a mode, I can't reproduce the errors as users see them, which means I can't troubleshoot their problems.

**Comment by wkurniawan07** [comment]
Masquerade mode is not crippled, though? Not working with tabs/right clicks = you just need to add the `user` param manually. Not convenient, but not crippled.

**Comment by damithc** [comment]
> Masquerade mode is not crippled, though? Not working with tabs/right clicks = you just need to add the `user` param manually. Not convenient, but not crippled.

In some cases the mode doesn't work either way. e.g., view/edit student details -> even normal click doesn't work
image

Another one: preview session as a student

**Comment by wkurniawan07** [comment]
It's the same: you just need to add the user param manually.

**Comment by damithc** [comment]
> It's the same: you just need to add the user param manually.

Oh? I didn't realize there is a manual workaround. Yes, that works. Thx.

**Comment by wkurniawan07** [comment]
Masquerade mode is not rocket science; presence/absence of `user` param is all that it needs. Unfortunately it is a lot of hard-coding if the `user` param is to be persisted across different pages visited via links, which is what this PR aims to resolve.

**Comment by ccyccyccy** [comment]
Sorry for the delay. This PR is now ready for review.

**Review by xpdavid — COMMENTED** [review]
> Remove code within app.component.ts previously used to sync masquerade mode. Now masquerade mode should be determined only by the URL user param

Did you do this or I have missed something?

Actually can we remove all old code original for the masquerade mode (e.g. `masqueradeModeService` and its usage)

**Comment by ccyccyccy** [comment]
> Did you do this or I have missed something?

Accidentally reverted that change in one of my later commit 😓. Just fixed it.

> Actually can we remove all old code original for the masquerade mode (e.g. `masqueradeModeService` and its usage)

I changed `masqueradeModeService` to be used for purely retrieving the information from the URL, and removed all the `set` commands for the masquerade mode. Also changed `NavigationService` to reuse the same logic. I think that should be all the old code used.

**Comment by wkurniawan07** [comment]
This PR is currently blocking #10827. I will expedite the process and push some necessary fixes. The groundwork laid here is very solid, so good job for that. 💯

**Review by xpdavid — APPROVED** [review]

**Review by madanalogy — APPROVED** [review]

**Pull request merged**
