### PR TITLE
Rename settingUp.md -> setting-up.md #7741

### LINKED ISSUE #7741: Rename settingUp.md -> setting-up.md
For consistency with the way the other documents are named. Also involves updating links to it in the other documentation files, if any.

### PR DESCRIPTION
**Pull request by yliang97**
Fixes #7741 

**PR Checklist**

**Outline of Solution**

Hopefully I was able to rename and update dependencies!

### CODE REVIEW

**Comment by whipermr5** [comment]
@yliang97 One thing to note though - I noticed you're committing directly to your `master` branch. While this is forgivable as this is your first contribution, do take note to read and follow our workflow (link: [process.md#step-2-start-clean-from-a-new-branch](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-2-start-clean-from-a-new-branch)) _exactly_ for future PRs :)

**Comment by yliang97** [comment]
@whipermr5  Gotcha. Thanks for the note and will do next time

**Comment by thenaesh** [comment]
@yliang97 May we have your full name for inclusion into the contributors' list?

**Comment by yliang97** [comment]
Hi @thenaesh, it's Yijia Liang. Cheers!

**Pull request merged**
