### PR TITLE
Rubric questions: show summary excluding self-evaluation #6887

### LINKED ISSUE #6887: Rubric questions: show summary excluding self-evaluation
**Feature**: Instructor/student viewing results of a rubric question

**Current state**: stats shown in summary table includes self ratings
Example (from instructor side):
image

**Suggestion**: provide a way to view stats excluding self ratings as well

**Justification**: some users have requested for this feature.

### PR DESCRIPTION
**Pull request by shubham49**
Fixes #6887 

I just did the changes on my local and haven't pushed the changes. Just want to show this particular approach if this looks nice.

excluding rubic

Please suggest whether to proceed with this approach.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@damithc for your input

**Comment by damithc** [comment]
@shubham49 nice work. May be use a check box instead? It can be placed inside the panel next to the `Response Summary` heading (because it applies to the summary table only)

**Comment by shubham49** [comment]
okay @damithc I will make these changes.

**Comment by shubham49** [comment]
Ready for review.
rubric_question

**Comment by LiHaoTan** [comment]
@shubham49 I apologize but I forgot to mention that the new interface you designed is not very intuitive. You should have a separate checkbox to the right of `Response Summary`, not a checkbox linked to the header `Response Summary`. Can you change that as well?

**Comment by shubham49** [comment]
No problem... I will make the changes.

**Comment by wkurniawan07** [comment]
@shubham49 closing due to inactivity for a long period. Feel free to request for reopen if you're ready to resume the work here.

**Pull request closed without merging**
