### PR TITLE
change the admin highlight functionality to use more general function of common.js #4822

### LINKED ISSUE #4822: change the admin highlight functionality to use more general function of common.js
highlightSearchResult() function has been introduced in common.js . admin highlight functionality should use this general function.  
One should work on this issue after #4800 merges.

### PR DESCRIPTION
**Pull request by tarun14110**
fixes #4822

### CODE REVIEW

**Comment by tarun14110** [comment]
@junhaoyap please review.

**Comment by damithc** [comment]
@tarun14110 the branch name should be based on 3-4 keywords of the issue title (rather than the entire issue title), to avoid very long branch names.

**Comment by tarun14110** [comment]
ok, I will keep this in mind from next time.

**Comment by junhaoyap** [comment]
Good to merge - @damithc please take a look and also see if we should add any HTML test considering it's for admin page

**Comment by bamboo3250** [comment]
I don't recommend to do so. An attempt to add HTML tests for admin pages was made in the past but we had to undo it. You can check it in #4314 and #4377

**Comment by junhaoyap** [comment]
@bamboo3250 alright! Thanks :+1:

**Comment by thyageshm** [comment]
hey @junhaoyap could you merge this one and #4830 in soon? thanks!

**Comment by junhaoyap** [comment]
@thyageshm will do

**Comment by junhaoyap** [comment]
@tarun14110 it's been merged - great work

**Pull request merged**
