### PR TITLE
usermap.jsp is not responsive #6567

### LINKED ISSUE #6567: usermap.jsp is not responsive
The map isn't responsive.

### PR DESCRIPTION
**Pull request by li-kai**
Made the map responsive. 

I also tried directly loading the topo json file through `dataJson` instead of `dataUrl` but it doesn't work. I couldn't debug it, even after scanning through the source code of datamaps.

Related to #6487 
Fixes #6567 

**Outline of Solution**
Read the docs of datamap, and read the source code.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@li-kai nothing looks suspicious, but can you host in a staging server just to confirm?

**Comment by li-kai** [comment]
> @li-kai nothing looks suspicious, but can you host in a staging server just to confirm?

http://4-18-dot-teammates-divided.appspot.com/usermap.jsp

**Comment by wkurniawan07** [comment]
Didn't seem to work for me :/ what's the expected behaviour?

**Comment by li-kai** [comment]
> Didn't seem to work for me :/ what's the expected behaviour?

My mistake, it needed some changes from the other PR. 

The map should always keep within view of the screen.

**Comment by wkurniawan07** [comment]
@li-kai correct me if I'm wrong, but that means this PR is dependent on #6488, right?
If that is the case, might need to put on hold for merging.

**Comment by damithc** [comment]
Probably something wrong in how this PR is created (too many commits in the branch!) -- may be your master branch is different from ours?

**Comment by li-kai** [comment]
> Probably something wrong in how this PR is created (too many commits in the branch!) -- may be your master branch is different from ours?

Somehow my origin/master got detached from HEAD. I fixed it now, sorry!

**Pull request merged**
