### PR TITLE
Instructor: home page: give menu option to edit a course #8541

### LINKED ISSUE #8541: Instructor: home page: give menu option to edit a course
Current:
image

Suggested: Give an `Edit` menu option. It can behave same as `Instructors` → `View/Edit` menu option (because the resulting page has a panel for editing course name).

### PR DESCRIPTION
**Pull request by jacoblipech**
Fixes #8541 

**Outline of Solution**
In the instructor homepage, I added the logic of "edit/view" button for instructors to courses as both edit courses and edit instructors are in the same page with the same URL. If in the future the edit instructors and edit courses are in different pages, then we can edit the button for courses.

screen shot 2018-03-28 at 12 23 47 am

### CODE REVIEW

**Comment by jacoblipech** [comment]
Hi anyone can help with the test cases? The fail test cases mainly come from StudentHomePageUiTest, StudentAdminPageUiTest, InstructorFeedbackQuestionCopyActionTest. But I only changed the instructor home page, any idea where the failing test case may be from so that I can make the changes?

**Comment by craaaa** [comment]
You'll have to run [God mode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) on the failing UI tests to ensure that the expected DOM structure is updated to match the changes you made.

`InstructorFeedbackQuestionCopyActionTest` should not fail; Travis shows that rerunning it allows it to pass.

**Comment by jacoblipech** [comment]
Thanks for your tip! I am trying to run with GodMode but the test cases causing the problem either failed or ignored and I cannot seem to make the necessary changes to UI. 
I rebased to the latest version, run npm build, and do the tests and it is still the same problem. I do not have firefox installed. Is this the issue? Or am I missing out on something? Hope you can help thanks!

**Comment by bqnguyen94** [comment]
@jacoblipech Can you give the stack trace of the failed tests? Also, do the test suites pass in `master` for you?

**Comment by jacoblipech** [comment]
hi @bqnguyen94 I am really sorry for the delay but after a few days of trying, I have finally figured out the problem. GodMode works after I download firefox v46.0 to run the test. And I realised that I should not run it multiple times as the values for time will keep changing. 

Now I have a much better idea on how Teammates work. Hopefully you can help me to review again? Thank you so much.

**Comment by wkurniawan07** [comment]
> GodMode works after I download firefox v46.0 to run the test.

@jacoblipech what browser did you use before (and fail)?

> And I realised that I should not run it multiple times as the values for time will keep changing.

Are you sure? Godmode is supposedly immune to this kind of change. Which tests are you running and where does it fail?

**Comment by jacoblipech** [comment]
@wkurniawan07 I ran GodMode using the latest version of Firefox which is v59.0. Basically the Firefox browser opens up and nothing changes after that. The UI tests are still ignored. After changing to Firefox v46.0, all the tests run and works well.

Actually, I ran the tests over all CI Tests using GodMode. Somehow, GodMode updated the UI to the actual time I ran the tests instead of being `data-original-title="${datetime.now}"`.

**Comment by craaaa** [comment]
Hi @jacoblipech, can you rebase your branch onto master and force push? There are unrelated commits being captured here.

**Comment by whipermr5** [comment]
> Actually, I ran the tests over all CI Tests using GodMode. Somehow, GodMode updated the UI to the actual time I ran the tests instead of being data-original-title="${datetime.now}".

Sounds like #8640

**Comment by wkurniawan07** [comment]
@jacoblipech how exactly do you keep your fork in sync? You're not supposed to cherry-pick the commits one by one...

**Comment by jacoblipech** [comment]
@wkurniawan07 I am so sorry. Actually I used my master to pull from the teammates repo, then I rebase my branch onto the master and push. Then it caused all the commits from other people shown as well. I will look into the issue and solve it. Thanks.

**Comment by jacoblipech** [comment]
Sorry for the delay. I think this PR is ready for review. Thank You.

**Comment by craaaa** [comment]
@jacoblipech I think you reverted your change in https://github.com/TEAMMATES/teammates/pull/8725/commits/9ed045a1b938a78f22b84597f8d4b1d407a40e2a.

I pulled your branch and the View/Edit button does not appear.
screen shot 2018-04-05 at 12 38 22 pm

At this point it might be best to start on a fresh branch since there are duplicate commits, commit hashes are no longer consistent and the original change can quite easily be replicated.

**Comment by craaaa** [comment]
Also, you may want to double-check your git config settings since your identity looks a little weird to git and GitHub. It shows up in the patch as

`Jacob Li Peng Cheng <JacobLI@229-41.priv23.nus.edu.sg>`
`Jacob Li Peng Cheng <JacobLI@Jacobs-MacBook-Pro-2.local>`

Need to run this inside Git Bash
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

**Comment by darrenwee** [comment]
Hi @jacoblipech, your git identity is not set up correctly and is messing with GitHub, so it looks like there are multiple authors touching your commits. You can run the following commands in your Terminal to set your identity correctly:

```
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
```

Replace the name and email parts with whatever you want to use. Otherwise, they'll show up with strange things in your commits like
```
From: Jacob Li Peng Cheng <JacobLI@229-41.priv23.nus.edu.sg>
...
From: Jacob Li Peng Cheng <JacobLI@Jacobs-MacBook-Pro-2.local>
```

**Comment by jacoblipech** [comment]
@craaaa and @darrenwee I see. Thanks a lot for the help. I will make the necessary changes.

**Comment by jacoblipech** [comment]
@craaaa I think this is ready for review. Thank you.

**Pull request merged**
