### PR TITLE
Removing Outdated Links

### PR DESCRIPTION
**Pull request by yasirunilan**
Removing outdated links on the about.html

### CODE REVIEW

**Comment by kanghj** [comment]
Hi @yasirunilan, thanks for the pull request! However, please follow the [development process](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md) for the PR name, first comment in a PR, and the branch name. Since the branch name is incorrect, I will be closing this for now, could you make a new pull request with the correct branch? Thanks again!

**Comment by yasirunilan** [comment]
Could you please help me with this issue?

**Comment by kanghj** [comment]
@yasirunilan What do you need help with?

**Comment by yasirunilan** [comment]
I'm a first timer,so I should follow  
capture

 this one right?
What is meant by 2287 and add sample course test??
Can you please clarify.

**Comment by damithc** [comment]
Looks like you've mixed up (or missed) a few things along the way. For example, you did not follow this step:
image
Perhaps you can go back to the beginning and start over?

**Comment by yasirunilan** [comment]
Just one thing.Do I have to work with my tinker branch or another branch?

**Comment by damithc** [comment]
tinker branch is no longer relevant. It was just an orientation task.

**Comment by yasirunilan** [comment]
Ok thanks

**Pull request closed without merging**
