### PR TITLE
Multiple problems in MashupPageUiTest #4538

### LINKED ISSUE #4538: Multiple problems in MashupPageUiTest
Some serious ones:
- A few pages (`instructorCourseStudentDetailsPage`, `instructorCourseStudentEditPage`, `instructorStudentRecordsPage`, `instructorFeedbackPreviewAsStudentPage`, `instructorFeedbackPreviewAsInstructorPage`, `studentCourseJoinConfirmationPage`) doesn't load correctly because the student email is wrong (ends with `.com` instead of `.tmt`).
- ~~`studentCourseJoinConfirmationPageNew` won't load except the `app.url` defined in `build.properties` matches `test.app.url` defined in `test.properties`.~~ No longer an issue.
- The error pages (`deadlineExceededErrorPage`, `entityNotFoundPage`, `errorPage`) now won't load because of their error 500 status.
- Many missing pages.

Some not-so-serious ones:
- The jquery script is taken from CDN. That means this page cannot be tested offline (on an unrelated note, `logout.jsp` and `instructorHelp.html` are also guilty of this).
- The `instructorHelp` iframe is not resized due to typo in line 459 (`instructorHelpt`).
- No red line boundaries (`<br><hr class="hr-bold"><br>`) between the static pages, making it harder for viewers to separate them.

And one that I'm not so sure:
We only load `teammatesCommon.css` and `mashup.css` on top of bootstrap. Does this mean some of the views are not 100% accurate?

### PR DESCRIPTION
**Pull request by Gisonrg**
Fixes #4538 

#### Issues fixed so far:
1. Fix student's email address (.com to .tmt) so `instructorCourseStudentDetailsPage`, `instructorCourseStudentEditPage`, `instructorStudentRecordsPage`, `instructorFeedbackPreviewAsStudentPage`, `instructorFeedbackPreviewAsInstructorPage` and `studentCourseJoinConfirmationPage` could be correctly loaded.
2. Use local jqeury library instead of taking from CDN
3. Fix a typo so `instructorHelp` iframe's height could be shown properly.
4. Add red line boundaries between static page
5. Load error pages regardless of 500 status.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
The 500 status was added some time back for some reason that I can't recall, so better not remove it.
If there's no straightforward way to solve it, we might as well remove those pages from the mashup page and add it some time in the future.

**Comment by Gisonrg** [comment]
@wkurniawan07 
I managed to manually load and render the error page in ba40088. 
Basically make a HTTP Get request first. It will fail because of the 500 status, but we could get the response html text, manually parse it and render it. However I don't feel this is an elegant way to do it...

**Comment by wkurniawan07** [comment]
I'd say it's acceptable :+1:
One thing, though: can you extract the following process to a method to reduce repetition:
```javascript
$.get(...).fail(function(data) {
    $(...).html($('<div>').html(data.responseText).find('#mainContent').html());
});
```

**Comment by Gisonrg** [comment]
Done, please help review :smile:

**Comment by wkurniawan07** [comment]
Looks good :ok_hand:

**Pull request merged**
