### PR TITLE
TEAMMATES logo not transparent #6747

### LINKED ISSUE #6747: TEAMMATES logo not transparent
The black background is obvious against the new responsive navbar which has a gradient fill. This is the current view of the front page:

screen shot 2017-03-07 at 12 20 12 am

### PR DESCRIPTION
**Pull request by Dartteon**
Fixes #6747

**Outline of Solution**
Old image was a JPG which cannot save transparency. 
Recreated a new logo (as previous logo was too low resolution) and saved it in PNG.

**OLD**
image

**NEW**
image

### CODE REVIEW

**Comment by whipermr5** [comment]
The new logo is slightly off centre vertically (4 pixels to be exact):
comparison

**Comment by samsontmr** [comment]
@whipermr5 the old logo looks a little high to me though. The new position looks better to me aesthetically.

**Comment by whipermr5** [comment]
@samsontmr The new one seems low to me, like there's not enough space between the bottom of the logo and the bottom of the bar 😅 The logo is mostly the text and not the gear on the top right, so usually our perception of the vertical centre is more with reference to the text part. The text part looks too low to me.

**Comment by samsontmr** [comment]
On the other hand, there's too little space between the gear and the top edge for the old one compared to the text and the bottom edge, which affects the centredness of the logo as a whole. We should be looking at the logo as a whole and not just the text. In this case, the old one definitely looks a little too high.

**Comment by Dartteon** [comment]
Both of you make valid points, and both your views actually crossed my mind when I was creating the new logo image.

However, I decided that centre-ing the image as a whole was a better direction than centre-ing the text. Maybe we should have more inputs on this before going forward.

**Comment by damithc** [comment]
No strong preference on either.  :-)
There is some sense in using the 'visual center' rather than the 'physical center' of the image.

**Comment by whipermr5** [comment]
Yup I feel the visual centre gives more weight to the text than to the image as a whole, and so it's further down the image. Therefore the image should be moved further up. Also, when it's moved further up, the TEAMMATES text aligns more with the other menu item labels:
f1930876-1030-11e7-9ae2-c16537d0ccbb copy

This is not so when it's further down:
e64ca2e2-1030-11e7-83bc-bf5745fb39e7 copy

**Comment by Dartteon** [comment]
How about this?

image

**Comment by whipermr5** [comment]
@Dartteon Yup to me that's perfect haha

**Comment by Dartteon** [comment]
@wkurniawan07 Will do.

By the way, for your last point, do you mean `teammates.jpg' instead of 'teammates.png'?

Also, do you want me to include an uncompressed, high-resolution version for future uses?

**Comment by wkurniawan07** [comment]
@Dartteon no, it's `teammates.png`. You should be able to find the image. There is no need to include any uncompressed, hi-res version.

**Comment by Dartteon** [comment]
@wkurniawan07 Oh okay, I missed it when I went through the images.

Also, the reason why I think a high-res version should be included, is for future uses when a high-res image might be needed for various purposes.
For example, the reason why a 'new' logo was remade this time, was because the old logo was too low resolution. If it were of a higher resolution, I could have easily made modifications on it.

**Comment by wkurniawan07** [comment]
@Dartteon the reason why I am not very fond of things "might be used in the future" is that it is (perhaps) the number one reason for dead legacy code.
But since this is not code, I guess exceptions can be made. You can add a hi-res version of it in the `mockups` folder.

**Comment by Dartteon** [comment]
@wkurniawan07 Alright, will do. I'll name it `teammatesLogo_highRes.png` and add it into the folder. It will be the black-text version.

**Comment by li-kai** [comment]
@wkurniawan07 There's a use for hi-res 😆, the teammates poster

**Comment by Dartteon** [comment]
@li-kai It will be done by tomorrow :)

**Comment by whipermr5** [comment]
@Dartteon Nearly there! But there's no need for `teammates.png` when it's a copy of `teammateslogo.png`; plus I think @wkurniawan07 wanted you to delete it.

**Comment by Dartteon** [comment]
Woops, forgot about that. Removing it now! :)

**Pull request merged**
