### PR TITLE
#7910. InstructorFeedbackEditPage.java : Added documentation for sele…

### LINKED ISSUE #7910: InstructorFeedbackEditPage: add documentation for selectConstSumPointsOptions method
The `selectConstSumPointsOptions()` method in `InstructorFeedbackEditPage` is used to switch between the points distribution scheme for const sum question. Though the method is understandable, the arguments to pass to the method is still a mystery even after looking at the code -

```java
public void selectConstSumPointsOptions(String pointsOption, int questionNumber) {
    markRadioButtonAsChecked(
           browser.driver.findElement(By.id("constSumPoints" + pointsOption + "-" + questionNumber)));
}
```

One would have to check the templates or inspect HTML to find out the ID of the radio buttons and deduce the value for the String parameter. It would be very helpful to devs if we added a small documentation string above this method -

```java
/**
 * Selects the points distribution scheme for a const sum question.
 * 
 * @param pointsOption Value of "Total" will select total number of points for all options points distribution scheme,
 *                     or "PerOption" will select number of points per option points distribution scheme.
 * @param questionNumber question number of the const sum question.
 */
```

### PR DESCRIPTION
**Pull request by sidntrivedi012**
…ctConstSumPointsOptions() method.

Fixes#7910 Added documentation to the method selectConstSumPointsOptions() with a suitable Documentation title and indentation.

Fixes #7910 

**PR Checklist**

Ensure that you have:
- [ ] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [ ] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ ] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

I added the documentation as asked by the authority by using forward slashes  astrisk syntax.

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
Sorry once again Sir,by mistake.

**Comment by sidntrivedi012** [comment]
Sir,the Travis CI is showing the error:

The command "./gradlew lint --continue" failed and exited with 1 during . 

What is that Sir?Please tell.I really aspire to learn alot from you and the whole open source community.

**Comment by wkurniawan07** [comment]
@sidntrivedi012, have a look at [our workflow for fixing issues](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) as well as the PR checklist above, and make sure you follow them. Once you do so, you should be able to figure out what that line means.

**Comment by wkurniawan07** [comment]
Closing due to inactivity. @sidntrivedi012 feel free to reopen if you wish to resume the work done here.

**Pull request closed without merging**
