### PR TITLE
[#11854] Refactor NavigationService to use Angular's dependency injection for services

### LINKED ISSUE #11854: Refactor NavigationService to use Angular's dependency injection for services
Issue: Currently the methods in the `NavigationService` take in `router` as a param. This is not required as we can inject these services into the constructor directly.

Solution: Refactor `NavigationService` to take in `private router: Router` in the constructor directly using Angular's dependency injection and remove `private router: Router` injection in the components that use affected methods of `NavigationService` and fix failing tests.

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Fixes #11854 

Note: This PR should be merged after #11850. (merged)

**Outline of Solution**

The inbuilt angular service `router` is now injected into the navigation service constructor instead of passing it in method params.

### CODE REVIEW

**Comment by sivayogasubramanian** [comment]
This PR is ready for review.

**Comment by fsgmhoward** [comment]
@samuelfangjw @NicolasCwy Reminded for this opened PR! If you cannot review it please request a review from someone else.

**Review by samuelfangjw — APPROVED** [review]

**Comment by NicolasCwy** [comment]
Will take a look at this tomorrow

**Review by NicolasCwy — APPROVED** [review]
LGTM

**Pull request merged**
