### PR TITLE
Error messages for each field should be shown on separate lines #5085

### LINKED ISSUE #5085: Error messages for each field should be shown on separate lines
image

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #5085 and #2352

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
Continuation of #5094

**Comment by YongJieYongJie** [comment]
@JosephineKwa This is in relation to the discarded PR.

I managed to get the tests to pass locally but they are not passing on Travis CI.
(I ran the tests both as full test suite and also by using the `./gradlew -Pgist=a6e68554bddd46f0ca075b41b6d95432 downloadFailedXml` as instructed in the Travis CI failed build)

Is it possible for you to help check if the tests are failing on your local machine too?
Specifically, `InstructorCourseEnrollSaveActionTest`, `InstructorCourseEnrollPageUiTest`, and `StudentProfilePageUiTest`

(by the way, I am also ramping up on exams revision and may not be as prompt in replying; so maybe if this cannot be solved, we can put it on hold first)

**Comment by YongJieYongJie** [comment]
The previous errors were caused by some hardcoded `\n` that resulted in different behaviours on Window vs Unix based machines: on my PC, the hardcoded `\n` weren't replaced to `<br>` because `Const.EOL` uses the system's EOL; however, the `\n` were replaced in Travis, thus the failing tests.

**Comment by JosephineKwa** [comment]
Good to merge!

**Comment by wkurniawan07** [comment]
@YongJieYongJie GitHub doesn't recognize `Fixes #... and #...` to close multiple issues, next time use `Fixes #... and fixes #...` :ok_hand:

**Comment by YongJieYongJie** [comment]
@wkurniawan07 noted!

**Pull request merged**
