### PR TITLE
request to update lines

### PR DESCRIPTION
**Pull request by dipzzzz**
can't we add a word "thank you"on 29th line to thank the vistors on this page?

Fixes #

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by damithc** [comment]
@dipzzzz as mentioned in my previous email, and now I'm more certain than at the time of writing that email, I'm afraid you are not yet ready to work in a project of this size and complexity. I think you need more basic software engineering training before you can start contributing to OSS projects of this size. Qualities such as asking a lot of questions, numerous trial-and-error attempts, and being brave enough to jump into hard tasks are an asset to any student and you seem to have those qualities in good supply. Hope you don't lose them as they will serve you well in your learning journey. However, without some level of basic competency, you are unlikely to be able to contribute to TEAMMATES. Hope to see you back in TEAMMATES sometime in future, but for now, I'm afraid we do not have resources to help/accommodate you.

**Comment by dipzzzz** [comment]
OK sir. I am learning but I don't know why am I not able to implement it:(

**Comment by dipzzzz** [comment]
I think I am facing issue with my machine. Will have to change machine and
try it.

**Comment by dipzzzz** [comment]
Sir please give me some more days. I told you sir I am still learning GIT
and github. I learnt basics and I am trying to be an expert. I apologise
sir.

**Comment by dipzzzz** [comment]
Hope you will understand me.I am again telling that I am still at basic
level. Just give me some time

**Pull request closed without merging**
