### PR TITLE
[#10029] Add "Enroll this student to my course" button in Student-Profile page

### LINKED ISSUE #10029: Add "Enroll this student to a course" button in Student-Profile page
- **Environment**: Student-Profile-Page, Instructor-Courses-Page & Instructor-Course-Enroll-Page

**Description of feature/enhancement**
I already made locally the pages in order to show you how it could look like:
So, I am thinking about adding here this button, which will appear whenever an instructor is searching for a student:

Whenever the instructor wants to enroll this student to a course, he/she will press this button and get to the courses page and will select "Enroll" in the course he wants the student to be enrolled:

Finally, after selecting the course the instructor will be directed to the "Enroll students to course" page and the student's name and email will automatically be saved there:

 **Justification**
I believe, since everything nowadays is getting even more and more operated automatically,  this enhancement can add value to the instructor's role and save him time and trouble, by enabling the instructor to enroll a student to a course without having to search in his files for the attributes of the student, or copy-paste an excel file, just by searching for this certain student and adding him to a course.

As you can see, I feel really motivated to implement this enhancement and add my mark to this project, so I would be extremely happy If you agree with it!

Thank you.

### PR DESCRIPTION
**Pull request by edwardkang0925**
Fixes #10029 

**Screen shots**
Student profile detail page 
Screen Shot 2020-06-21 at 14 16 38 PM

After clicking the "Enroll this student to my course", 
Screen Shot 2020-06-21 at 14 23 48 PM

After clicking the "Enroll" button for a specific course, 
Screen Shot 2020-06-21 at 14 24 47 PM

**Solution**
Created a button on the Student-Profile page which carries the student name and email and route to the instructor-courses-page. When the enroll button on the instructor-courses-page is clicked, the previously carried student name and email and the course-id will be carried as query parameters and route to the instructor-course-enroll-page. When the page is initialized, by using the query parameters, we put the new student's information to the spreadsheet.  

**Concern** 
In instructor-course-enroll-page.component.ts file, we created an array (newStudentInfo) to initialize the new students' hands-on-table data, but since the only cells to be filled for the table are name and email, the indexes of the array are hard-coded.

### CODE REVIEW

**Comment by madanalogy** [comment]
I would recommend creating a new branch from `master` when working on a new issue instead of continuing from previous work done as appears from your commit history. Also, the CI is failing the component tests, don't forget to run `npm run test` to confirm that they're passing locally.

**Comment by madanalogy** [comment]
Hi @edwardkang0925, the decision from the dev team regarding this issue is that we will not be proceeding with the enhancement. This is because the impact this feature would have does not justify the resource cost for maintaining this feature. 

However, since this decision was made only after you have started working on the issue, I am offering to help you work on your PR until it is merge-ready if you would like to do so for whatever reason. I will indicate with a PR approval when it is, but it will not be merged to the main repo.

If you would like to proceed with this option, you need to first address the comments given previously (i.e. cleaning up your git commits and passing the component tests) then reopen this PR. Do let me know if you have any other questions or concerns, thank you.

**Comment by edwardkang0925** [comment]
> Hi @edwardkang0925, the decision from the dev team regarding this issue is that we will not be proceeding with the enhancement. This is because the impact this feature would have does not justify the resource cost for maintaining this feature.
> 
> However, since this decision was made only after you have started working on the issue, I am offering to help you work on your PR until it is merge-ready if you would like to do so for whatever reason. I will indicate with a PR approval when it is, but it will not be merged to the main repo.
> 
> If you would like to proceed with this option, you need to first address the comments given previously (i.e. cleaning up your git commits and passing the component tests) then reopen this PR. Do let me know if you have any other questions or concerns, thank you.

Thank you for offering help! I would be glad to know how to fix this kind of issue in a proper way. 
I have created another fork to start from a clean git. Could you explain how to reopen this PR? It seems I don't have permission to do so. Should I open new PR regarding this issue?

**Comment by madanalogy** [comment]
> I have created another fork to start from a clean tree.

You shouldn't need to create another fork. It might be worth your while to learn how to use git to reset your branch to the state before your changes. [This article on stackoverflow](https://stackoverflow.com/questions/9301782/need-to-reset-git-branch-to-origin-version) is a good starting point. Subsequently, please read our [`development workflow`](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) on how you can use the branching model for your local repo.

> Also, about the local tests, it seems the upstream/master (TEAMMATES/teammates repo) is failing "npm run test". It returns "TypeError: fsevents is not a function at new FSEventsWatcher," and my modified code returns the same error.

Please read our development guide on [how to work with the front end](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#managing-the-dev-server-front-end). It seems you need to generate types first before running the tests locally on your machine.

> Could you explain how to reopen this PR? It seems I don't have permission to do so. Should I open new PR regarding this issue?

I will re-open this PR for you and close it again after approval has been given (i.e. the code quality is merge-ready). Until then, let me know if you need any help getting there :)

**Comment by madanalogy** [comment]
@edwardkang0925 I'm going to close this PR now, it is good to go and merge-ready but as mentioned we will not be adopting this feature. Do let me know if you have any other questions or concerns, thanks!

**Pull request closed without merging**
