### PR TITLE
[#8931] Instructor: Feedback Session: Mark mandatory fields for creating and editing session

### LINKED ISSUE #8931: Instructor: Feedback Session: Mark mandatory fields for creating and editing session
**Description of feature/enhancement**
Mark mandatory fields using `*` or some other mechanism when user creates a new feedback session or edits existing feedback session.

Currently, user is only notified of mandatory fields on form submission

image

It will be even better if these errors are attached to the fields rather being listed at one place.
Example:
image

### PR DESCRIPTION
**Pull request by Ting-TT**
Fixes #8931

**Mark "Session Name" as a mandatory field during new session creation in the following ways:**  
1. Append a `*` symbol after "Session Name" when creating a new session. (Note: When editing a session, the session name cannot be modified, so the "Session Name" label remains unchanged and does not display the `*` symbol.)  
2. Disable the "Create Feedback Session" button when the "Session Name" field is empty.
3. Display a red warning with an exclamation mark, stating "The field Session Name should not be empty," when the instructor clicks the field but leaves it empty.

(I modelled changes 2 and 3 based on the behaviour of the "Course Name" field during new course creation.)

<br>

**Screenshots**

_Before the changes:_  

teammates_session_name_before

_After the changes:_ 
Below is a screenshot illustrating the updates. The areas circled in red encompass all the modifications I introduced.

teammates_session_name_mandatory

### CODE REVIEW

**Comment by Ting-TT** [comment]
Ready for review :))

**Review by cedricongjh — CHANGES_REQUESTED** [review]
hey @Ting-TT thank you for the contribution!

looks fine to me, let's also add this to the copy from previous feedback sessions modal to keep the behaviour consistent:
image

**Comment by Ting-TT** [comment]
Thank you for pointing that out! 
I've implemented the following changes to ensure consistency between the two methods of creating a new feedback session:

**Mark the "Name for new session" field mandatory when creating by copying from a previous session:**
1. Append a `*` symbol after "Name for new session"
2. Display a red warning with an exclamation mark, stating "The field 'Name for new session' should not be empty," when the instructor clicks the field but leaves it empty.

**Screenshots** 

*Before the changes:*

Name_for_new_session_before. 

*After the changes:*

Name_for_new_session_after

**Comment by Ting-TT** [comment]
Ready for review :))

**Review by cedricongjh — APPROVED** [review]
LGTM, thank you for your contribution to TEAMMATES!

**Comment by Ting-TT** [comment]
No worries! Thank you for reviewing :))

**Review by weiquu — APPROVED** [review]
LGTM

**Pull request merged**
