### PR TITLE
[#11237] Feedback session table doesn't differentiate grace period and open status

### LINKED ISSUE #11237: Feedback session table doesn't differentiate grace period and open status
**Steps to reproduce**

I used these settings and to my understanding, this feedback session should be in the GRACE_PERIOD status (it's 5:14 pm at time of screenshot)
image

**Expected behaviour**

The sessions table should indicate to the instructor if a feedback session is in the grace period.

**Actual behaviour**

Seems like the submission in the feedback session table says that the feedback is open and there's no mention of grace period in the table and the tooltips

image

**Additional info**

It's a minor issue but could help clarify the status to instructors.

Fixing this might involve just two files 1) submission-status-name.pipe 2) submission-status-tooltip.pipe

### PR DESCRIPTION
**Pull request by xyzhang00**
Fixes #11237 

**Outline of Solution**

Added text descriptions for grace period and open status submission sessions at relevant switch case blocks.

Time of screenshot 6:03 pm.
Screenshot 2021-07-02 at 6 03 02 PM

Screenshot 2021-07-02 at 10 09 20 PM

### CODE REVIEW

**Comment by damithc** [comment]
@xyzhang00 see https://github.com/TEAMMATES/teammates/issues/11237#issuecomment-870527328 too.

**Comment by xyzhang00** [comment]
> @xyzhang00 see [#11237 (comment)](https://github.com/TEAMMATES/teammates/issues/11237#issuecomment-870527328) too.

Really sorry for missing that! I have updated the PR.

**Review by daongochieu2810 — APPROVED** [review]
lgtm

**Comment by damithc** [comment]
@xyzhang00 minor tweak to the tooltip: `The feedback session is visible to respondents, is open for submissions, and is in the grace period`

**Comment by xyzhang00** [comment]
> @xyzhang00 minor tweak to the tooltip: `The feedback session is visible to respondents, is open for submissions, and is in the grace period`

@damithc The tooltip has been tweaked!

**Comment by damithc** [comment]
> > @xyzhang00 minor tweak to the tooltip: `The feedback session is visible to respondents, is open for submissions, and is in the grace period`
> 
> @damithc The tooltip has been tweaked!

Looks good to me @xyzhang00 👍

**Comment by ccyccyccy** [comment]
Looks good to me!
Can you resolve the conflict before we merge?

**Review by ccyccyccy — APPROVED** [review]

**Comment by xyzhang00** [comment]
> Looks good to me!
> Can you resolve the conflict before we merge?

@ccyccyccy Resolved! I changed the tooltip to `The feedback session is open for submissions, is in the grace period, and is visible to respondents.` to better follow the format of other tooltips, hope that is alright!

**Comment by ccyccyccy** [comment]
Merged. Thank you for the PR!

**Pull request merged**
