### PR TITLE
Whitespace12679

### PR DESCRIPTION
**Pull request by ArunErram**
Fixes #12679 

**Outline of Solution**

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @ArunErram, do take a look at the failing tests, and let us know if you face any issues

**Comment by ArunErram** [comment]
@weiquu , I'll check the test cases, and as I informed previously wasn't able to login as student or instructor to check the modification done in code , so can you help me with these login

**Comment by weiquu** [comment]
> @weiquu , I'll check the test cases, these just a draft PR as you said to raise , and as I informed previously wasn't able to login as student or instructor to check the modification done in code , so can you help me with these login

Hi @ArunErram, I've replied to your discussion post [here](https://github.com/TEAMMATES/teammates/discussions/12729#discussioncomment-8377656). Let's continue the conversation there

**Comment by cedricongjh** [comment]
closing due to inactivity, do reopen the PR if you continue work on the issue

**Pull request closed without merging**
