### PR TITLE
Display comment time in the session's time zone #4488

### LINKED ISSUE #4488: Display comment time in the session's time zone
Currently, comment timestamp is in the format: Mon, 13 Jul 2015, 08:47:18 UTC
We need to do this using the session time zone.

### PR DESCRIPTION
**Pull request by Mynk96**
Fixes #4488 

- Used moment.js library to get user's time zone and update comment's time accordingly.

### CODE REVIEW

**Comment by whipermr5** [comment]
@Mynk96 Set the UTC flag and re-run tests with GodMode

**Comment by wkurniawan07** [comment]
Just a heads up, this solution was attempted some time back but was discarded. One of the reasons was that using `moment` will get the VM's locale, not the one used to start up the TEAMMATES instance, and this is not possible to control and will significantly affect testability.
A proper solution would be using the timezone dictated by the course in which the comment was made, but at that point of time it was not possible. It may be possible now.

**Comment by Mynk96** [comment]
@wkurniawan07 But moment is used to get timezone for the courses!

**Comment by wkurniawan07** [comment]
@whipermr5 setting the value for CI is one thing. The problem comes when different devs from different parts of the world are exposed to the same expected value. Imagine one of the HTML tests expecting some time in UTC+8, thus Travis is configured as such, but another dev who comes from e.g. UTC+7 encounters the same test. We wouldn't want to force the dev to set his/her PC's timezone just to comply with the test, right?

@Mynk96 you'd be right, but as it so happens, we chose to sweep this problem under the rug when we introduced this feature slightly more than one year ago ([sample](https://github.com/TEAMMATES/teammates/blob/master/src/test/resources/pages/instructorArchiveStatusNotAffected.html#L35)). We haven't found the opportunity to look at this again, so it's kind of our bad here. 🤕

@damithc since this topic is on the rise again, actually what's the _real_ reason for [not allowing the previous solution](https://github.com/TEAMMATES/teammates/pull/4688)? (I have forgotten)

**Comment by whipermr5** [comment]
@wkurniawan07 I was thinking the UTC timestamp can exist as a data attribute in the DOM; the user-specific timestamp added by JavaScript can be detected and replaced like how the existing unpredictable values are handled.

**Comment by damithc** [comment]
> @damithc since this topic is on the rise again, actually what's the real reason for not allowing the previous solution? (I have forgotten)

From what I remember, I objected because the comment time stamp (to be consistent with all other time info we show e.g. deadlines) should be based on the course/session timezone, not the browser timezone, and therefore should be determined on the server side. We just need to take the actual time stamp and adjust it to match the course/session time zone.

**Comment by Mynk96** [comment]
> From what I remember, I objected because the comment time stamp (to be consistent with all other time info we show e.g. deadlines) should be based on the course/session timezone, not the browser timezone, and therefore should be determined on the server side. We just need to take the actual time stamp and adjust it to match the course/session time zone.

@damithc that means if a student is enrolled in course with India's time zone then all the deadlines and time-related info should be shown in that timezone irrespective of student's time zone.Right?

**Comment by damithc** [comment]
> @damithc that means if a student is enrolled in course with India's time zone then all the deadlines and time-related info should be shown in that timezone irrespective of student's time zone.Right?

Yes. That's what we do already, except for the comments (which should follow the same).

**Comment by whipermr5** [comment]
@damithc Should I update the issue title and description since it has been decided that server-determined time is to be used? Currently the issue mentions using the browser time zone.

**Comment by damithc** [comment]
> @damithc Should I update the issue title and description since it has been decided that server-determined time is to be used? Currently the issue mentions using the browser time zone.

Sure. go ahead @whipermr5

**Comment by whipermr5** [comment]
@damithc Can I confirm that since all comments are now response comments (after #7334), the time zone should follow the session time zone (not course time zone)?

**Comment by damithc** [comment]
> @damithc Can I confirm that since all comments are now response comments (after #7334), the time zone should follow the session time zone (not course time zone)?

Yes

**Comment by whipermr5** [comment]
@Mynk96 Closing due to inactivity, and also because the issue has changed. Feel free to reopen and change the approach if you wish to continue work on this :)

**Comment by Mynk96** [comment]
@whipermr5 Was waiting for the PR #7551 to merged. As this had changes on the same file.Will reopen after #7551 is merged.

**Pull request closed without merging**
