### PR TITLE
Add new Eclipse compiler rule - no unused exception

### PR DESCRIPTION
**Pull request by wkurniawan07**
Now this might come as a surprise to many, but Eclipse has its own static analysis tools too:

screen shot 2016-05-20 at 12 25 31 pm

I activated only one additional rule and already it caught a lot of violations, in the form of so many unused Exceptions.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@junhaoyap been a while since I assigned any one of my PR to you, hope you don't mind!

**Comment by junhaoyap** [comment]
@wkurniawan07 sure thing

**Comment by junhaoyap** [comment]
It is indeed a surprise! Eyeing commit by commit, one moment

**Comment by junhaoyap** [comment]
@wkurniawan07 changes looks good, I'm curious as to how this static analyzer works though, it is able to suggest all these changes? does it look into the methods and determine whether or not a kind of exception can be thrown and then suggest these changes?

**Comment by junhaoyap** [comment]
@damithc please take a look

**Comment by wkurniawan07** [comment]
@junhaoyap my guess is it's taking a look into the method body and examine line by line which checked exceptions are not handled, then matching with the "throws" declaration. The details might have to be deferred to those learning programming languages or compilers though :p

**Comment by junhaoyap** [comment]
Oh I didn't know that, go ahead and merge in that case 💃

**Comment by junhaoyap** [comment]
@wkurniawan07 it's cool though, didn't know that Eclipse could do such static analysis and give such sophisticated suggestions!

**Comment by wkurniawan07** [comment]
@junhaoyap you can explore all other magics that Eclipse can do. Pity that this is not enforce-able, which is why we have to resort to proper tools like PMD.

**Comment by junhaoyap** [comment]
Well we could turn them up to higher levels, there are ignore, warning and if there is one that blocks compiling... gonna be quite irritating though :p

**Comment by wkurniawan07** [comment]
@junhaoyap it's enforce-able only within each Eclipse environment. When we moved to Gradle build environment, we have to resort to other tools. ✂️ 📏

**Pull request merged**
