### PR TITLE
Pull Request Template: Fix typo 'abovementioned' #7234

### LINKED ISSUE #7234: Pull Request Template: Fix typo 'abovementioned'
A minor typo in [PULL_REQUEST_TEMPLATE.md](https://github.com/TEAMMATES/teammates/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Change -

> Titled the PR as specified in the abovementioned document

to 

> Titled the PR as specified in the above-mentioned document

### PR DESCRIPTION
**Pull request by mahmoudhanoraa**
Update  PULL_REQUEST_TEMPLATE.md fixing typo, issue #7234

Fixes #7234

**Outline of Solution**

### CODE REVIEW

**Comment by thenaesh** [comment]
@mahmoudhanoraa Do note the comment by the bot, and fix accordingly. Other than that, LGTM.

**Comment by whipermr5** [comment]
It's actually one word, though hyphenated: https://en.oxforddictionaries.com/definition/us/above-mentioned

Some sources do accept `abovementioned` too:
https://www.merriam-webster.com/dictionary/abovementioned
http://www.dictionary.com/browse/abovementioned
Though it's not as common. I'd go with the hyphenated version `above-mentioned`.

**Comment by thenaesh** [comment]
@mahmoudhanoraa Reminder.

**Comment by thenaesh** [comment]
Closing due to inactivity. Feel free to reopen if you wish to continue working on this.

**Pull request closed without merging**
