### PR TITLE
[#12679] & [#12653] Copying feedback session: Name for copied session should not be whitespace & Copy course modal: Mandatory fields not highlighted

### LINKED ISSUE #12653: Copy course modal: Mandatory fields not highlighted
**Description of feature/enhancement**
When copying a course, user is not notified that the course ID and course name fields are mandatory:

image

Unlike when creating a course:
image

Let's make the behavior consistent between the 2, by displaying a red warning with an exclamation mark, stating "The field Course ID/Course Name should not be empty," when the instructor clicks the field but leaves it empty

### PR DESCRIPTION
**Pull request by Josephine0110**
Fixes #12679 
Fixes #12653 

**Outline of Solution**

 
For Issue#12679
Added a validator to copy session component, checking whether the feedback session name is whitespace or not. If the Name for feedback session is only composed of whitespace, the red warning of "The field "Name for copied session" should not be empty." would appear on the screen.

Before: (from the issues)
image

After:
Screenshot 2024-04-21 at 2 43 56 PM

For Issue#12653
Modified frontend to make the user input of Course ID and Course Name mandatory by adding a red warning sign down the input box

Before:
image

After:
image

### CODE REVIEW

**Comment by weiquu** [comment]
@Josephine0110 Do fix the failing tests. You can find out more about how to update tests in our documentation

**Comment by domoberzin** [comment]
Hi @Josephine0110  could you please fix the failing component tests? Do let us know if you need any help

**Comment by domoberzin** [comment]
Hi @Josephine0110, 

I've noticed there hasn't been any activity on this PR for awhile. Are you still working on this? If you need any help or have decided not to continue, please let us know so someone else may pick up this issue to keep things moving.

Thank you for your contribution!

**Comment by mingyuanc** [comment]
@Josephine0110 closing due to inactivity, please reopen when ready!

**Pull request closed without merging**
