### PR TITLE
[#9248] Removing keepUpdateTimestamp from FeedbackResponse

### LINKED ISSUE #9248: Remove keepUpdateTimestamp in FeedbackResponse
`keepUpdateTimestamp` is only set to `true` in test case and it is always `false` in production code.

For data migration script, we will use the Objectify API directly. Thus, this field also does not help in this case.

### PR DESCRIPTION
**Pull request by Alessandra-Rossaro**
Fixes #9248 

**PR Checklist**

I have checked each point requested.

**Outline of Solution**

I solved the issue removing the field "keepUpdateTimestamp" from FeedbackResponse and I updated the dependencies in the same class and in the classes where it was used (FeedbackResponsesDb, FeedbackResponseDbTest).

### CODE REVIEW

**Comment by xpdavid** [comment]
@Alessandra-Rossaro Hi, please don't introduce irrelevant changes.

**Comment by Alessandra-Rossaro** [comment]
Hi, 
What do you mean exactly with irrelevant changes? 
Sorry for the several commits, but I discovered that I included in my project also the commits of another contributor and this made tests fail, in addition I’m so sorry, because When I fixed the bugs I left some empty lines that gave problems with the code style rules.

**Comment by wkurniawan07** [comment]
@Alessandra-Rossaro, have a look at the [changes you introduced](https://github.com/TEAMMATES/teammates/pull/9265/files).

`README.md` should not be modified, and there should not be any new files like `src/main/webapp/js/*.js`, `src/main/webapp/test/*.js`, or `*.log`.

**Comment by Alessandra-Rossaro** [comment]
Good afternoon,
Sorry for the changes about the README.md, I had to update that file because this contribution is part of an exam at the university and the professor needs a report of my job.
Could I make a new pull request without the new version of the README.md? It will be a pull request from a new branch called “pullRequest”.

**Comment by wkurniawan07** [comment]
> Could I make a new pull request without the new version of the README.md? It will be a pull request from a new branch called “pullRequest”.

I'm afraid that is a must, otherwise we cannot take in your contribution. There is no requirement for branch name, although using the `master` branch (like what you did right now) is discouraged. Alternatively, you can undo the changes to README here and do it in another branch instead.

**Comment by Alessandra-Rossaro** [comment]
I decided to create a new branch called #9248PullRequest, I'll send right now another pull request and close this one.
Thanks for the attention.

**Pull request closed without merging**
