### PR TITLE
[#10243] Adjust site-wide font/padding settings and modal settings

### LINKED ISSUE #10440: Showing role permissions: use a bigger modal
Current: 
image

Suggestion: use a bigger modal to avoid this overflow (as done in V6)

### LINKED ISSUE #10468: Student home page: add gaps between course panels
image

### LINKED ISSUE #10469: Footer: standardize link color
Current: 
image

Suggestions: use blue for links

### PR DESCRIPTION
**Pull request by wkurniawan07**
Part of #10243 

What has been done:
- Adjusted site-wide font size to 0.875rem (14px in most browsers, i.e. same size as V6/Bootstrap 3's default)
  - As the regular font size is reduced to 87.5% of original, all heading font sizes are also reduced to 87.5% of original
- Adjusted site-wide padding such that the pages are not stretched too wide when the screen is large (>1024px)
- Adjusted sizing and padding for all modal dialogs, part of which resolves #10440 
- Standardized the way card headers are constructed. There have been perhaps 10 different ways of getting the buttons to be right-aligned; now they are all standardized. In addition, the card header text is now vertically aligned.
- Created a reusable component for chevron/caret/... (whichever way to call it)
- Added site-wide `margin-bottom` setting for all `card`s, which will resolve #10468
- Changed the footer link colour to blue (i.e. default colour), which will resolve #10469

### CODE REVIEW

**Comment by wkurniawan07** [comment]
> A lot of the collapsable panels do not change the cursor to pointers anymore (home page, courses page, etc)

This is not a pre-set design pattern. The ones you have seen having the cursor changing to pointers are all hard-coded.

**Comment by wkurniawan07** [comment]
> Intended button style changes? Original was `btn-primary`

- The original `btn-primary` works because the header color was `lighten`ed. Since we want to standardize the header colors, with the color being the same, the button is now indistinguishable with the background.
- This is literally the only place where the a non-light button color is used against a primary background. We can change this behavior, but the point is standardization.

**Comment by wkurniawan07** [comment]
> not sure what wrong with the initial padding in the first place

Nothing inherently wrong, just that when compared to V6 the page looks stretched wide. Maybe I will revert the site wide padding.

**Comment by ccyccyccy** [comment]
>     * The original `btn-primary` works because the header color was `lighten`ed. Since we want to standardize the header colors, with the color being the same, the button is now indistinguishable with the background.
> 
>     * This is literally the only place where the a non-light button color is used against a primary background. We can change this behavior, but the point is standardization.

Ok then we can standardize it here then. I was planning to change the button styling in https://github.com/TEAMMATES/teammates/pull/10399, but I can resolve the conflict after this is merged.

**Pull request merged**
