### PR TITLE
[#11837] Add support for multiples of 5 for team contribution question

### LINKED ISSUE #11837: Team contribution questions: also support 5%, 15%
Context: submitting answers to a 'team contribution' type question

Current: 
image

Suggestion: Also let students choose 5% and 15% (possibly 25% too), to give respondent more flexibility

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Fixes #11837

**Outline of Solution**

Added support for multiples of 5 to give respondents more flexibility.

### CODE REVIEW

**Comment by damithc** [comment]
> This PR is ready for review

@sivayogasubramanian thanks for the PR. As this involves a UI change, can you post a screenshot as well?

**Comment by sivayogasubramanian** [comment]
@damithc 

Before: 
image

After: 
image

**Comment by damithc** [comment]
> After:
> image

Looks good. The initial suggestion was to add up to +/- 25 only, but I'm OK to add +5 increments all the way too.

**Review by NicolasCwy — APPROVED** [review]
LGTM! Thanks for contributing to Teammates :+1:

**Review by ziqing26 — APPROVED** [review]
LGTM!

**Review by wkurniawan07 — APPROVED** [review]

**Pull request merged**
