### PR TITLE
Update about.jsp to match team make up at Oct 2016 #6125

### LINKED ISSUE #6125: Update about.jsp to match team make up at Oct 2016
As per title

### PR DESCRIPTION
**Pull request by damithc**
Fixes #6125

### CODE REVIEW

**Comment by wkurniawan07** [comment]
I looked at the new `about.jsp` and it looks fine except for the following issues:
- Nimantha is duplicated in past members as well as current member
- The names of the new members with photo should be removed from the "multiple contributors" section
- (minor issue) `src/main/webapp/mockups/processed photo sample.pptx` should not have any change?

Also, tangentially related, but should we have a section on (past) committers (e.g the FBOA people)? They certainly have contributed much more compared to the people in the "multiple contributors" section.

**Comment by damithc** [comment]
I did a small change to the pptx file (removed a shadow effect from the picture sample).
Yes, we can have a section for past 'major contributors' to include FBOA/GSoC members who don't stay long enough to become team members.
Thanks for catching the duplication. Can you fix the remaining issues and merge?

**Comment by wkurniawan07** [comment]
Nothing more from me here.

**Comment by damithc** [comment]
Go ahead and merge.

**Comment by wkurniawan07** [comment]
It would be nice if we can give proper credits to previous committers in the new section, however I do not know who they are especially if their involvement was (far) before I got in the team.

**Comment by damithc** [comment]
I don't think anybody else in the 'multiple contributions' list contributed to the same level as FBOA contributors.

**Pull request merged**
