### PR TITLE
[#7678] Instructor: edit question: do not warn about deleting responses if destructive changes are cancelled

### LINKED ISSUE #7678: Instructor: edit question: do not warn about deleting responses if destructive changes are cancelled
Steps to replicate the bug:
1. Click 'Edit' for a question with existing responses.
1. Change the visibility option to some other listed option.
1. Change the visibility option to the original option (or discard changes).
1. Attempt to save the question.

A modal warning the user that responses will be deleted is shown although the visibility is not changed.  

Edit: After #6124 is solved, the issue will not affect (most?) visibility changes, but is still present for team contribution question and when feedback path is edited and then reverted.

### PR DESCRIPTION
**Pull request by ellaella12**
Fixes #7678

Approach:
- In `question-edit-form`, all changes are immediately propagated to `component.model` and its parent components
- So even if a change is reverted, there is no original copy to compare with and signal that no change was made in the end

Solution:
- Have another `unsavedModel` that stores all unsaved changes first
- Before save button is clicked, compare `unsavedModel` with the original `model` to check for any changes 
- Warning modal will only be shown if the 2 models are different
(in terms of feedback path, visibility or question details)

Not sure if this is the right approach, or if there is a better approach? Also do E2E tests need to be added?

### CODE REVIEW

**Comment by zhaojj2209** [comment]
@ellaella12 Thank you for looking into this issue!

The general idea of comparing the new model against the old model to check for any changes before saving is fine, but I'm hesitant about introducing more complexity to the frontend in order to fix a relatively minor issue. The original issue is a few years old now, and while the issue is still present currently, we may need to re-assess whether it's worth fixing. @wkurniawan07 Any thoughts on this?

If we were to continue fixing this issue, though, one suggestion would be to simply disable the "Save Changes" button if there are no changes detected.

Also, regarding your last question, it does seem that modifications will be needed to the E2E tests following your changes. Do hold off on making the changes first while we discuss the merits of this PR though.

**Comment by wkurniawan07** [comment]
> The original issue is a few years old now, and while the issue is still present currently, we may need to re-assess whether it's worth fixing.

Need to confirm with @damithc for feature-related inclusion/exclusion.

**Comment by damithc** [comment]
@ellaella12 @zhaojj2209 

To confirm, the context is that the instructor goes into the edit mode of the question, does some changes, but the changes cancel each other and the question attributes are same as when the edit started.
Upon trying to save the question, a warning message about deleting data pops up, although the question attributes are same as before. Is that correct?

If the user chooses to proceed, are the responses actually deleted? I'm assuming that is not the case (based on the previous comments in the issue thread). 

If the data is not actually deleted, I don't think this issue is worth fixing, given instructors are likely to cancel the edit (because no real change was done) rather than try to save such an edit.

What do you all think?

**Comment by ellaella12** [comment]
Hi, to answer the questions above
1. Upon trying to save the question, a warning message about deleting data pops up, although the question attributes are same as before. Is that correct? Yes, so the unsaved changes are equal to the saved changes
2. If the user chooses to proceed, are the responses actually deleted? The responses will not be deleted

The implementation above emits an event on submit as compared to on key change of the form. Does it help performance?
(not sure about this). Noted on the discussion above, I will go ahead and close this pr. If there is a recommended approach that doesn't add as much complexity to the frontend, do let me know too. Thank you!

**Comment by zhaojj2209** [comment]
> If the data is not actually deleted, I don't think this issue is worth fixing, given instructors are likely to cancel the edit (because no real change was done) rather than try to save such an edit.

Agree with this as well. Will proceed to close the issue.

**Pull request closed without merging**
