### PR TITLE
[#10527] Student view responses: tweak spacing

### LINKED ISSUE #10527: Student view responses: tweak spacing
Use spacing to indicate relationships between elements. Elements should be closer to other related elements than to non-related elements. In this case, `Evaluee/recipient` label should be closer to the names below than the panel above.

image

Also present in V6 but less severe.

### PR DESCRIPTION
**Pull request by srdeotarse**
Fixes #10527 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Snapshot testing done and all passed
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

Added class 'margin-top-30px' to para tag of Evaluee/Recipient and result is shown below -

image

### CODE REVIEW

**Comment by srdeotarse** [comment]
I have added class 'margin-top-30px' to para tag of Evaluee/Recipient to add space above Evaluee/Recipient.
Please review my PR @ChooJeremy @madanalogy and suggest any changes.

**Review by Derek-Hardy — APPROVED** [review]
Good attempt. Original issue states that:
> Evaluee/recipient label should be closer to the names below than the panel above

Current screenshot seems to suggest that the `Evaluee/recipient` section sits in the middle. 
I would personally prefer to have its own class to fine-tune the `margin-top` and `margin-bottom`. 

Nonetheless, this solution is acceptable to me.

**Review by ChooJeremy — APPROVED** [review]
Change looks fine.
Please ensure your PR title follows the issue title next time.

**Comment by srdeotarse** [comment]
> Change looks fine.
> Please ensure your PR title follows the issue title next time.

Yes i will keep in mind next time.

**Review by madanalogy — CHANGES_REQUESTED** [review]
30px seems a bit excessive to me imo (based on your screenshot), maybe try 15px instead? Also, after making the changes could you please take a screenshot displaying a mobile width? What might seem like good spacing on desktop could change with a mobile screen, which is more relevant here since you're essentially hardcoding the spacing

**Comment by srdeotarse** [comment]
> 30px seems a bit excessive to me imo (based on your screenshot), maybe try 15px instead? Also, after making the changes could you please take a screenshot displaying a mobile width? What might seem like good spacing on desktop could change with a mobile screen, which is more relevant here since you're essentially hardcoding the spacing

Okay I will try with 15px and also take a screenshot in mobile width.

**Comment by srdeotarse** [comment]
> 30px seems a bit excessive to me imo (based on your screenshot), maybe try 15px instead? Also, after making the changes could you please take a screenshot displaying a mobile width? What might seem like good spacing on desktop could change with a mobile screen, which is more relevant here since you're essentially hardcoding the spacing

Instead of 30px I have tried with 15px by creating a new class 'margin-top-15px' and following are the screenshots of desktop and mobile width -

Desktop width -

image

Mobile width -

image

Suggest any changes @madanalogy .

**Comment by madanalogy** [comment]
Looks good! Push your changes into the PR and we'll get it merged. Thanks!

**Comment by srdeotarse** [comment]
> Looks good! Push your changes into the PR and we'll get it merged. Thanks!

Pushed the changes in PR. Please review it @madanalogy.

**Review by madanalogy — APPROVED** [review]

**Pull request merged**
