### PR TITLE
[#12467] Add Sort Functions to Admin Sessions Page

### LINKED ISSUE #12467: Add Sort Functions to Admin Sessions Page
**Description of feature/enhancement**
Add “Sort” features to AdminSessions-OngoingSessions:
- “Sort” features:
    - Sort by “Start Time”, “End Time”, “Session Name”, “University Name”, and “The Number of Open Sessions a University Has”

**Justification**

Keep the format consistent and let administer would have a more clear understanding of sessions

**Existing similar features and their shortcomings**

Screenshot 2023-06-06 at 10 47 26 AM
- Instructor Home has a similar format but with sort features

### PR DESCRIPTION
**Pull request by sxw022020**
Fixes #12467 

**Outline of Solution**
Modify admin-sessions-page.component.ts and the corresponding html file to add the feature

 
1. Sort by startDate and endDate
image (2)
2. Sort by institution name and institution sessions total
image (1)

### CODE REVIEW

**Comment by sxw022020** [comment]
> Hi @sxw022020, thank you for your interest in contributing to TEAMMATES! However, your PR does not appear to follow our [contribution guidelines](https://teammates.github.io/teammates/process.html#step-4-submit-a-pr):
> 
> * Description must reference the issue number the PR is fixing, e.g. `Fixes #<issue-number>` (or `Part of #<issue-number>` if the PR does not address the issue fully)
> 
> Please address the above before we proceed to review your PR.

fix

**Comment by weiquu** [comment]
Hi @sxw022020, did you try using the `sortable-table` component? I believe it can be used to implement sorting based on `startDate` and `endDate`, though I'm not too sure about the other 2 options.

Do let me know if you tried it, and if you did, what issues you faced. This info will have some bearing on issue #12329, since we should aim to form sortable tables use the same `sortable-table` component.

**Comment by weiquu** [comment]
Hi @sxw022020, do update us as to whether or not you're still working on the issue

**Comment by weiquu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
