### PR TITLE
Javascript: button event callback: use event.currentTarget #8335

### LINKED ISSUE #8335: Javascript: button event callback: use event.currentTarget
As suggested by @LiHaoTan (#8331), most if not all jQuery button event callback instances throughout the code should refer to their respective target as `event.currentTarget` instead of `event.target` to avoid erratic behaviours when the buttons are clicked (see #8148 and #8329).

The problem occurs with `button` elements that contains one or more child elements (e.g. glyphicons). When one such button is clicked while the mouse is pointing at a child element, the click event is propagated to the parent element, triggering its attached event handler. However, in event callback, if the target element is referred to using `event.target`, the target will be the child element (e.g. a glyphicon) and not the parent (i.e. the `button` element). This leads to the needed attributes of the target in the callback being `undefined` (e.g. `data` attribute). 

A proposed solution is to replace `event.target` with `event.currentTarget` (where appropriate), which is the parent element the event is propagated to (e.g. the `button` element).

### PR DESCRIPTION
**Pull request by bqnguyen94**
Fixes #8335

### CODE REVIEW

**Comment by bqnguyen94** [comment]
Ongoing

**Comment by bqnguyen94** [comment]
All `event.target` instances have been replaced with `event.currentTarget`, ready for review.

**Comment by wkurniawan07** [comment]
I assume this PR is confined to `instructorFeedbackEdit.js`? Otherwise there's quite possibly about 50 of such instances across all JS files.

**Comment by bqnguyen94** [comment]
My mistake. I forgot to pop the stash after merging from `master`. This PR is intended to replace `event.target` in all JS files.

**Comment by wkurniawan07** [comment]
@bqnguyen94 looks like you've caused some regressions (tests failing). I'm not sure if those are unintended regressions or you actually fix things that need fixing. Need to check case by case.

**Comment by bqnguyen94** [comment]
Yes, I realized `event.currentTarget` should not be used with panel toggling. I have removed those changes.

**Pull request merged**
