### PR TITLE
Student Records Page: fix id of visibility options button for student comments #5383 

### LINKED ISSUE #5383: Student Records Page: fix id of visibility options button for student comments
In the Student Records Page, the id of the visibility options button for new student comments is not unique if the instructor has given that particular student any student comments. While this does not affect the user, it causes a problem when running UI tests.

### PR DESCRIPTION
**Pull request by chowyb**
Fixes #5383

### CODE REVIEW

**Comment by chowyb** [comment]
Ready for review

**Comment by wkurniawan07** [comment]
The changes are fine, but what does this want to achieve?

**Comment by chowyb** [comment]
It's mainly for making it easier to find the HTML elements associated with adding a new comment for UI testing. Previously, the id of elements related to adding a comment would be the same as the id of elements related to the earliest comment posted, resulting in findElement(By.id()) not working correctly.

**Comment by wkurniawan07** [comment]
Ok, then it should be good to go.

**Comment by wkurniawan07** [comment]
@chowyb can you update this branch (and do any necessary fixes) so I can merge it in?

**Pull request merged**
