### PR TITLE
[#12290] Instructor view session results (course-wide): Improve display of no-response card header

### LINKED ISSUE #12290: Instructor view session results (course-wide): Improve display of no-response card header
The current display of the no-response card header doesn't work well on mobile:
photo_2023-03-28 14 00 24

Suggestion: switch to column format on mobile screen sizes, similar to the card headers for the instructor edit page (example below).
Screenshot 2023-03-28 at 15 07 46

The card header should also be changed to be a button semantically so that it can be picked up by screen readers. For the approach, do refer to the card headers in the instructor edit sessions page.

### PR DESCRIPTION
**Pull request by rhyses-pieces**
Fixes #12290 

**Outline of Solution**

I reformatted the `instructor-session-no-response-panel-component` to have the `.card` class, and nested old code accordingly. The changes added include:
- changing the `card-header` from a `<div>` into a `<button>`
- adding the `<tm-panel-chevron>` to be the first element under the `card-header` button
- nesting the text "Participants who have not responded to any question" and `card-header-btn-toolbar` under a flex container
- adding flex properties to the `card-header-btn-toolbar` so that it behaves smoothly in mobile view.

Screenshot of the no-response card header in mobile view: 
Mobile view of no-response card header

**Comments**

After reformatting the no-response card header to be consistent with the edit question card headers, I noticed that the no-response card header is inconsistent with the other card headers on the session results page:
Mobile view of session results page

Should the other card headers also be consistent with the edit question card headers and no-response card header too?

Please let me know if there's any questions or concerns. This is my first time contributing code to an open source project, so I'm open to feedback!

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @rhyses-pieces, the approach generally looks fine, but do fix the failing tests (snapshot, accessibility, E2E) before we do a complete review.

> After reformatting the no-response card header to be consistent with the edit question card headers, I noticed that the no-response card header is inconsistent with the other card headers on the session results page:

Can you help to check if the panel chevron is usually on the right or left in other pages? I think it would be good to standardise the chevron's location across the entire website. @zhaojj2209 do weigh in if you have any other opinions

**Comment by zhaojj2209** [comment]
@weiquu The positions are currently not standardised; the submit feedback and instructor session edit panels have the chevron on the left, the rest have it on the right. We can discuss whether to standardise the position in a separate issue; for this particular PR, let's keep it consistent with the previous design and have the chevron on the right.

**Comment by rhyses-pieces** [comment]
Hello! Thanks for the feedback.

I've updated the chevron's position in the no-response card header, but I wasn't sure how to resolve indicating that the card header is expandable without using `<button>` because there are other buttons within the card header. Should the card header stay a `<div>` in order for it to avoid the nested interactables issue?

Also, I'm running into problems with testing on my local system. My system keeps crashing even after following guidelines to set up E2E testing for the Edge browser. (For reference, I'm using Windows and WSL for my local dev environment.) Not sure how else to do testing on my end.

**Comment by zhaojj2209** [comment]
> I've updated the chevron's position in the no-response card header, but I wasn't sure how to resolve indicating that the card header is expandable without using `<button>` because there are other buttons within the card header. Should the card header stay a `<div>` in order for it to avoid the nested interactables issue?

In this case I think it's fine to have nested buttons. Let's go with an approach similar to the other card headers (e.g. instructor edit session card header).

> Also, I'm running into problems with testing on my local system. My system keeps crashing even after following guidelines to set up E2E testing for the Edge browser. (For reference, I'm using Windows and WSL for my local dev environment.) Not sure how else to do testing on my end.

Unfortunately E2E testing for TEAMMATES is known to be wonky on Edge, we recommend using other browsers such as Chrome or Firefox. If E2E tests still do not work on your local machine, you can use the E2E tests workflow on GitHub to debug as well, but we would not recommend doing it directly on this PR as repeated commits would spam maintainers with notifications. You can try using the following steps instead:

1. Enable GitHub actions on your own forked repo
1. Open a PR to the `master` branch of your own forked repo
1. Make changes until the E2E test workflow passes
1. Make the same fix to this PR after a fix has been found

**Comment by zhaojj2209** [comment]
@rhyses-pieces My bad, forgot that nested buttons will cause accessibility tests to fail. Let's revert the change, have checked and verified that the other card headers in the codebase still use divs.

**Comment by rhyses-pieces** [comment]
@zhaojj2209 Hello! Thanks for the feedback. I've fixed the nested buttons issue as suggested, and E2E testing is now passing.

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

**Review by weiquu — APPROVED** [review]
LGTM! Thanks for contributing

**Pull request merged**
