### PR TITLE
InstructorFeedbackResultsPage: avoid use of `.click()` #7886

### LINKED ISSUE #7886: InstructorFeedbackResultsPage: avoid use of `.click()`
This method does not work on Chrome (causing the AppVeyor build failures after merging #7586), and is sometimes unreliable on Firefox too. Use `AppPage`'s `click` method instead, which uses JavaScript and is reliable across both browsers.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7886

Build passing on both [AppVeyor](https://ci.appveyor.com/project/whipermr5/teammates/build/1.0.285) and [Travis](https://travis-ci.org/whipermr5/teammates/builds/259826407).

### CODE REVIEW

**Comment by whipermr5** [comment]
@wkurniawan07 The popover link clickers don't run on Chrome, and we actually want them to fail if the popover isn't clickable at that point. The photo link clicker fails when using the JavaScript click.

**Comment by wkurniawan07** [comment]
> The popover link clickers don't run on Chrome

I don't think this gives a ground for them to be different.

> and we actually want them to fail if the popover isn't clickable at that point (I believe moveToElement was written in the same spirit of making the test as realistic as possible)

Not sure if I get what this is about. Does `click(...)` not fail if something is not clickable? (I have not given this a try before)
Also, I think `moveToElement` and `focusViaClickAction` is a different kind of `.click()` as compared to `WebElement#click`, and I don't intend to touch on that topic.

> As for the photo link clicker, it fails when using the JavaScript click.

If this is confirmed to be the case, can add a comment before this line?

**Comment by whipermr5** [comment]
> Does click(...) not fail if something is not clickable? (I have not given this a try before)

Just tried using it on a non-clickable element. It does not fail, as it only executes JavaScript, which fails silently.

> Also, I think moveToElement and focusViaClickAction is a different kind of .click() as compared to WebElement#click, and I don't intend to touch on that topic.

I wasn't referring to the `click()` inside `moveToElement`, but to the fact that `moveToElement` is called (it scrolls the element into view and moves the mouse to the element). I believe this was the desired way (perhaps it was the only way) of making the popover appear, and using `WebElement#click` is in line with this spirit of very realistic checking.

**Comment by whipermr5** [comment]
@wkurniawan07 Managed to get everything working with the JavaScript click. Ready for review :)

**Pull request merged**
