### PR TITLE
[#11150] Search page: Remove unnecessary panel

### LINKED ISSUE #11150: Search page: Remove unnecessary panel
image

Suggested changes:
* Rephrase as `You can search for students (by name or email) from all your courses here.`
* Give an example at the end `e.g., "John Doe"`
* Remove this outer panel as all results are students anyway.

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #11150
Hi @damithc @moziliar, how does this look?
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Comment by moziliar** [comment]
Thank you for your contribution. 
For the ease of reviewing, especially for issue concerning UI changes, could you also attach the before-after screenshots in your PR description?

**Comment by moziliar** [comment]
Also, your tests seem to be failing.

**Comment by daongochieu2810** [comment]
@RhnSharma since you changed the UI, the snapshots should be updated accordingly to pass the test cases

**Comment by madanalogy** [comment]
Closing due to inactivity. Feel free to reopen this PR if you're picking it up again.

**Pull request closed without merging**
