### PR TITLE
Instructor add essay question: Typo in tooltip #5995

### LINKED ISSUE #5995: Instructor add essay question: Typo in tooltip
image

Should be `... shown to the ...`

### PR DESCRIPTION
**Pull request by dp80**
Fixes #5995  a typo in Instructor add essay question tool tip

### CODE REVIEW

**Comment by junhaoyap** [comment]
Hi @dp80 please look up our contributor guidelines for how to name pull requests and we need the test on Travis to pass in order for us to move this forward, in the mean time I'll set it to onGoing

**Comment by dp80** [comment]
Hi @junhaoyap will do.

How do i go about fixing and re-run the test on Travis?  Do i need to do another pull request or further commits will trigger the Travis build CI build?

**Comment by damithc** [comment]
New commits will trigger travis to rerun tests.

**Comment by junhaoyap** [comment]
@dp80 as commented by @damithc, new commits will automatically trigger the tests to run, wee need it to at the minimum pass the CI test before we can look at it again

**Comment by wkurniawan07** [comment]
Hi @dp80, any updates on this PR?

**Comment by dp80** [comment]
@wkurniawan07 yes, I should have it completed today.  Down to couple failed test cases.

**Comment by dp80** [comment]
ready for review  @wkurniawan07 @junhaoyap

**Comment by junhaoyap** [comment]
@dp80 excellent - just one minor thing, the branch name should be slightly better named (refer to the contributor guidelines) [understood that it can't be changed now so let's do better the next time around shall we?]

**Comment by junhaoyap** [comment]
@dp80 could you update this against the master branch and I can merge this for you?

**Comment by wkurniawan07** [comment]
Merging on behalf on @junhaoyap, I have tested this locally.

**Comment by wkurniawan07** [comment]
@dp80 can we get your full name so that we can add you to our contributors' list?

**Comment by dp80** [comment]
@wkurniawan07  my full name:  Dhiren Patil

**Pull request merged**
