### PR TITLE
Avoid throwing raw exception types in production code #7085

### LINKED ISSUE #7085: Replace raw exception throws in production code
> There is a rule in `PMD` named `AvoidThrowingRawExceptionTypes` and it indicates that throwing raw exception types is not a practice in software engineering. We may want to use `Assumption.assert*` rather than throwing raw exceptions in the production code. Therefore, we should change all RuntimeException to make use of `Assumption` class for production code.

image
For example, we should use `Assumption.assert*` here.

Three Tasks here.
1. Add `<rule ref="rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes"/>` to `teammates-pmdMain.xml`
2. Fix violations reported by PMD (Make use of `Assumption.assert` instead)
3. Remove `TODO` if it is necessary (Like the example above)

### PR DESCRIPTION
**Pull request by Jvsierra**
Fixes #7085 

**PR Checklist**

**Outline of Solution**

I removed the raw exception type in the file and replaced by a Assumption.assert* instead.

### CODE REVIEW

**Comment by xpdavid** [comment]
@Jvsierra Note that you need to changes every violation reported by PMD, not only `TeamEvalResult.java`

**Comment by Jvsierra** [comment]
@xpdavid I need help in this one.  I'm having trouble in finding all the files i need to change. The violations are reported in the file teammates-pmd.xml?

**Comment by xpdavid** [comment]
After you have run `./gradlew lint`, you shall find report in `teammates/build/report/pmd/main.html`

**Comment by Jvsierra** [comment]
@xpdavid What should i use instead of the try-catch? For example:

`static {
        Properties properties = new Properties();
        try {
            properties.load(FileHelper.getResourceAsStream("build.properties"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }`

How to replace that with an Assumption* method?

**Pull request closed without merging**
