### PR TITLE
[#12186] Remove raised-edge from home and features page

### LINKED ISSUE #12186: raise-edge image should be removed
raise edge image should be removed from home page .

- **Environment**: 

**Steps to reproduce**
- open this page on any browser : https://teammatesv4.appspot.com/web/front/home
- take look at below the request a free instructer account  button 

**Expected behaviour**
Screenshot (86)

**Actual behaviour**
Screenshot (85)

**Additional info**

### PR DESCRIPTION
**Pull request by sumitshinde-84**
Fixes #12186

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
@weiquu  i have make appropriate changes this time . please review it

**Review by domlimm — APPROVED** [review]
LGTM! Thanks for contributing!

You may remove the PR checklist once you've checked each task in it. Outline of Solution too, if the solution is trivial.

**Comment by weiquu** [comment]
Seems like the E2E checks are failing, @zhaojj2209 can help to rerun? While that's going, do merge the latest changes from master into your branch.

**Review by domlimm — APPROVED** [review]

**Review by samuelfangjw — APPROVED** [review]
Thank you for contributing to TEAMMATES!

**Comment by sumitshinde-84** [comment]
Is there any problem in that pr ?

**Comment by sumitshinde-84** [comment]
Thank you so much all of you for guiding me .
@weiquu @zhaojj2209 @domlimm @samuelfangjw

**Pull request merged**
