### PR TITLE
MCQ question: right align 'generate' option #5460

### LINKED ISSUE #5460: MCQ question: right align 'generate' option
Right aligning the test to be near the dropdown can make the option easier to understand
image

### PR DESCRIPTION
**Pull request by thyageshm**
Fixes #5460

### CODE REVIEW

**Comment by junhaoyap** [comment]
I'll assume this isn't done yet since it's set to ongoing and the build is still failing

**Comment by thyageshm** [comment]
Yes, I need to update the test cases. But if you have any comments on my suggested fix for the issue please provide them :-)

**Comment by wkurniawan07** [comment]
Hi @thyageshm, any updates on this PR?

**Comment by thyageshm** [comment]
sorry about that, will send an update tongiht. The fix is in, will need to update the tests

**Comment by junhaoyap** [comment]
Sure just let me know as and when and hopefully that won't be during the exam period!

**Comment by wkurniawan07** [comment]
Hi @thyageshm, any updates here?
If you're busy and all that needs to be done is fixing the HTML files, I can give some assistance here.

**Comment by thyageshm** [comment]
That would be greatly appreciated, thank you!

**Comment by junhaoyap** [comment]
Will do so tonight

**Comment by junhaoyap** [comment]
Can we use div instead of hr tag ->

screen shot 2016-10-28 at 10 29 18 pm

**Comment by junhaoyap** [comment]
Also, just so I got this right, the only non-html change is the template html right? Just to be sure I'm reviewing the right part

**Comment by wkurniawan07** [comment]
@thyageshm let's continue working on this?

**Comment by thyageshm** [comment]
@junhaoyap that is right. the only change is in template html.
@wkurniawan07 tmrw morning will upload the change

**Comment by thyageshm** [comment]
@junhaoyap ready for review

**Comment by thyageshm** [comment]
@junhaoyap ready for review

**Comment by wkurniawan07** [comment]
@junhaoyap let's review this?

**Comment by junhaoyap** [comment]
Sure - same as other PR that’s on me - just back from a holiday so give me a day (had to unwind after the exam)

**Comment by junhaoyap** [comment]
@thyageshm excellent let's get this in @wkurniawan07, thanks so much @thyageshm

**Comment by junhaoyap** [comment]
@wkurniawan07 any help with why eslint failed after merging master?

**Comment by wkurniawan07** [comment]
@junhaoyap it seems like we're a collateral damage of a tinker done by Travis. I've opened #6199.

**Comment by wkurniawan07** [comment]
@damithc this is ready for review.

**Pull request merged**
