### PR TITLE
[#12657] Fix Color of Students Dropdown Buttons on Instructor Home Page

### LINKED ISSUE #12657: Instructor Home Page: Students dropdown buttons of the wrong colour
The buttons in the Students dropdown of a course in the instructor home page are the wrong colour:

Screenshot 2023-12-12 at 8 36 41 PM

This seems to be an unintentional change cause by #12591, in particular the following addition to `styles.scss`:
```
  .btn-info {
    background-color: darken(#0DCAF0, 3%); // 3% darker than info
  }
```

The background colour is being used by another button in another page; moreover, it's unclear why the buttons in the students dropdown is of class `.btn-info` when no other dropdown button has that class (they have `.button-light` instead, but even that class seems to be redudant).

My suggestion is to simply remove that class from the affected buttons, as well as to ensure that no other buttons are affected. I've taken a quick look and this seems to be the only case, though I might have missed something.

### PR DESCRIPTION
**Pull request by akhil0903**
Fixes #12657 

**Outline of Solution**
- Have updated the button class from btn-info to btn-light, as the default btn class was a bit darker 
teammatesfix

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @akhil0903, looks good but please remove the `package-lock.json` file! These files shouldn't be committed unless you're updating dependencies

**Comment by akhil0903** [comment]
Hello @weiquu, This is my first time contributing to a open source and accidentally committed the `package-lock.json `. I have just quick question should I raise be raising a fix to previous PR correcting it or should I just raise new PR with just the changes in it?

**Comment by weiquu** [comment]
> Hello @weiquu, This is my first time contributing to a open source and accidentally committed the `package-lock.json `. I have a quick question should I be raising a PR to fix the previous PR or should I just raise new PR with just the changes in it?

The best approach would be to revert the `package-lock.json` to the previous commit (i.e. the one on the `master` branch). There are a couple of resources online of how to do so using git, for example [here](https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/) and [here](https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision). I would strongly suggest using this approach, since it will get you more familiar with git and will likely be useful in your future software development.

Of course, if you're unable to, you can always close this PR and open a new one with the same changes (without committing the `package-lock.json` file). However, please try the above approach first.

**Comment by weiquu** [comment]
Hi @akhil0903, just checking in to see if you are facing any issues

**Comment by akhil0903** [comment]
@weiquu  I tried reverting the commit but found a bit confusing, was thinking to close the pull request and raise a new one.

**Pull request closed without merging**
