### PR TITLE
Add new rules to PMD-UselessParentheses

### PR DESCRIPTION
**Pull request by kanghj**
Added PMD.UselessParentheses

### CODE REVIEW

**Comment by kanghj** [comment]
@wkurniawan07, are you going to review all the pull requests related to adding new static analysis rules? Or should I assign some to @JosephineKwa or @bamboo3250 (if he is free)?

**Comment by wkurniawan07** [comment]
@kanghj I'd be grateful if you can share the workload :joy:

**Comment by kanghj** [comment]
@wkurniawan07, just go ahead and assign me if you need me to review anything

**Comment by wkurniawan07** [comment]
This one's OK too :+1:

**Pull request merged**
