### PR TITLE
Instructor: remove unnecessary unboxing of Boolean value #7716

### LINKED ISSUE #7716: Instructor: remove unnecessary unboxing of Boolean value
In the `return` statement of `isDisplayedToStudents` in Instructor.java, the `Boolean` variable `isDisplayedToStudents` can be returned directly without unboxing it.

### PR DESCRIPTION
**Pull request by rajujha373**
Fixes #7716 

**PR Checklist**

Ensure that you have:
- [ ] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by rajujha373** [comment]
i don't know but i think i've messes something up... would be grateful if anyone helps

**Comment by amarlearning** [comment]
@rajujha373 you didn't mess up anything, your build failed because of issue #7808.
And Thanks for your contribution :smile: :+1:

**Comment by rajujha373** [comment]
@amarlearning thank you so much... feels good to contribute to opensource.. This is my first contribution. Thank you!! 💃

**Comment by thenaesh** [comment]
While the code changes in this PR are fine, you should take note of a few things when making contributions in the future:

1. Title your PR properly. We prefer if the PR and issue it fixes both have the same title, as it makes it easier to reference.
1. Create a proper branch to commit from, instead of from branches like `tinker`. This is mainly to make your life easier.
1. Make sure you actually *read* the contributor's guide before ticking it on the PR checklist.

**Comment by rajujha373** [comment]
@thenaesh This was my first time sir, I will definitely consider all these points from now on :) Thank You

**Comment by whipermr5** [comment]
> What branch naming should i use to commit from?

You'll know once you've read the documentation :)

**Pull request merged**
