### PR TITLE
[#11388] Remove numOf* fields from question details structure

### LINKED ISSUE #11388: Remove numOf* fields from question details structure
https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L33-L36

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java#L30-L31

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java#L35-L36

These question details have `numOf*` fields. They are unnecessary and all places where they are used can be replaced with `.size()` (or `.length`) of the list they are representing without any side effect. In fact, adding `numOf*` adds unnecessary risk of the two numbers getting out of sync.

### PR DESCRIPTION
**Pull request by Shubhojeetban**
Fixes #11388

**PR Checklist**

- Removed numOfRubricSubQuestions from FeedbackRubricQuestionDetails.java
- Removed numOfRubricChoices from FeedbackRubricQuestionDetails.java
- Removed numOfMcqChoices from FeedbackMcqQuestionDetails.java
- Removed numOfConstSumOptions from FeedbackConstantSumQuestionDetails.java

### CODE REVIEW

**Comment by Shubhojeetban** [comment]
Yeah sure @jianhandev

**Comment by jianhandev** [comment]
> @jianhandev Can you tell me why the checks got stuck?

@Shubhojeetban the checks are still running, it is normal for it to take some time.

**Comment by Shubhojeetban** [comment]
@jianhandev Can you review the PR

**Comment by jianhandev** [comment]
> @jianhandev can you mark my PR as ''hacktoberfest-accepted' label?

Sure I can label the issue associated with this PR.

**Comment by damithc** [comment]
> > @jianhandev can you mark my PR as ''hacktoberfest-accepted' label?
> 
> Sure I can label the issue associated with this PR.

@jianhandev @Shubhojeetban our project's policy is not to opt-in PRs with that label. Your PR will be counted for Hacktoberfest after it has been approved/merged (label not needed)

**Comment by jianhandev** [comment]
> @jianhandev @Shubhojeetban our project's policy is not to opt-in PRs with that label. Your PR will be counted for Hacktoberfest after it has been approved/merged (label not needed)

I see, thanks for clarifying!

**Comment by jianhandev** [comment]
@Shubhojeetban a few more to remove in following files:
* `session-result-page.component.spec.ts`
* `FeedbackRubricQuestionE2ETest.json`
* `StudentFeedbackResultsPageE2ETest.json`
* `feedbackSessionResultsRubricResults.json`
* ... (a couple of more files)

You can try to do a full search to see which files still contain those fields.

**Comment by jianhandev** [comment]
@Shubhojeetban Looks like there are still some files to look into:
Screenshot 2021-10-17 at 6 02 01 PM
Screenshot 2021-10-17 at 6 02 20 PM
Screenshot 2021-10-17 at 6 01 44 PM
Screenshot 2021-10-17 at 6 01 33 PM
Screenshot 2021-10-17 at 6 01 16 PM

**Comment by Shubhojeetban** [comment]
@jianhandev Can you help me, why the checks failed?

**Comment by daongochieu2810** [comment]
@Shubhojeetban let us know how the conflict resolving is going! Otherwise this PR looks good to merge

**Comment by Shubhojeetban** [comment]
@daongochieu2810  yes you can merge it.

**Comment by moziliar** [comment]
Hi @Shubhojeetban we are still waiting for you to resolve the conflicts such that it can be merged:)

**Comment by jianhandev** [comment]
Hi @Shubhojeetban please resolve the conflicts, thank you!

**Comment by jianhandev** [comment]
@Shubhojeetban gentle reminder on this PR.

**Comment by jianhandev** [comment]
Closing this PR for now, feel free to reopen if this issue has not been resolved in the future and when you have more time!

**Pull request closed without merging**
