### PR TITLE
[#11830] User documentation: don't use bold to refer to UI text

### LINKED ISSUE #11830: User documentation: don't use bold to refer to UI text
Current: the user documentation uses **bold text** to refer to text in the UI. e.g.,
image

Suggestion: Use a different style to differentiate UI text from the rest e.g., `this style`

Reason: Bold is normally used to make the text stand out by adding more visual weight e.g., to indicate more important parts of the text. By using it for the above purpose, we lose the opportunity to emphasize important parts of the user documentation using bold formatting.

What do others think?

### PR DESCRIPTION
**Pull request by John-Poulos**
Fixes #11830

**Outline of Solution**
First, I searched to find the affected files in codebase. I reviewed the website for each user doc to find where in the text the bold was used incorrectly and then searched the matching file for the bold tags. These were replaced with mark tags. This helps to preserve translation functionality vs the previously proposed solution of using code tags. 

Can you please review this sample to see how it should be handled? Where it made contextual sense, like a heading of a paragraph, I left the bolded text intact. Please let me know if you want that altered. 

Thank you!
Screenshot (896)

### CODE REVIEW

**Comment by damithc** [comment]
@John-Poulos `<mark>` is for highlighting text to draw attention to them. The purpose is different here i.e., we want to distinguish text that appears in the UI from other text. They need to appear _different_, not more or less important. So, I don't think this formatting is a good choice.
But yes, certain text may be currently formatted as bold to indicate their importance (e.g., headings) and they should remain bold.

**Comment by John-Poulos** [comment]
> @John-Poulos  - . But yes, certain text may be currently formatted as bold to indicate their importance (e.g., headings) and they should remain bold.

Aside from intuition on sections that I assume to remain, is there any rule you want me to use with respect to sections that should remain bolded?

Would you prefer those sections of the text be italicized instead?

**Comment by damithc** [comment]
> Would you prefer the remainder of the text be italicized instead?

Italics are used for emphasis. so that's not a good choice either.


> Aside from intuition on sections that I assume to remain, is there any rule you want me to use with respect to sections that should remain bolded?

The special formatting needs to be applied to any text that is citing text from the UI (e.g., an item in a drop-down menu, a label in a form etc. ). So, you need to familiar with the TEAMMATES UI to make those decisions.

**Comment by John-Poulos** [comment]
@damithc  Thank you for that information. I think I developed some insight on what to change as I worked on the code. 
Would a different color be suitable for this task? Do you have a preference?  Or is there some other method you have in mind?
Thank you.

**Comment by damithc** [comment]
> @damithc Thank you for that information. I think I developed some insight on what to change as I worked on the code.
> Would a different color be suitable for this task? Do you have a preference? Or is there some other method you have in mind?
> Thank you.

Perhaps something like `this`? i.e., different font and light background (but no change to the text color).

**Comment by John-Poulos** [comment]
@damithc  Can you clarify what you mean by  "light background"? The background of the existing document is white. Are you indicating that any lightly colored background with a different font would be an acceptable solution? Is it best practice to create a custom html tag in css to accomplish this instead of hardcoding the value at each location? Thank you.

**Comment by damithc** [comment]
> @damithc Can you clarify what you mean by "light background"? The background of the existing document is white. Are you indicating that any lightly colored background with a different font would be an acceptable solution?

image


> Is it best practice to create a custom html tag in css to accomplish this instead of hardcoding the value at each location? Thank you.

I'll leave this for someone from the dev team but hardcoding it everywhere is definitely a no-no.

**Comment by John-Poulos** [comment]
Ok, thank you for the experience. If no one is willing to continue this issue, please let me know, I would really like to complete it!

**Comment by John-Poulos** [comment]
@damithc Hello Professor, can I proceed with creating a custom html tag and styling it in the scss?

**Comment by damithc** [comment]
> @damithc Hello Professor, can I proceed with creating a custom html tag and styling it in the scss?

@John-Poulos Let me remind the dev team to give their inputs on this.

**Comment by damithc** [comment]
> @damithc Hello Professor, can I proceed with creating a custom html tag and styling it in the scss?

@John-Poulos While waiting for inputs from devs, you can go ahead with this approach.

**Comment by samuelfangjw** [comment]
> @John-Poulos @damithc Apologies for the late response, maybe the HTML `<code>` tag would be sufficient here?

Let's not do it this way, code tags should not be used for non-code content. HTML elements have semantics attached to them. Misusing elements hurts accessibility, which is something we are keen on improving in a future iteration.

A custom style or custom elements will probably be better here.

**Comment by zhaojj2209** [comment]
@John-Poulos Please go ahead with adding the custom tag!

**Comment by John-Poulos** [comment]
> @John-Poulos Please go ahead with adding the custom tag!

Ok, thank you! I will see what I can do :-)

**Comment by John-Poulos** [comment]
> 

Ok, thank you @zhaojj2209! I will see what I can do :-)

**Comment by John-Poulos** [comment]
@zhaojj2209 Hi Zhao, can you give me some context on the website's structure? I am interested in creating the custom tag for the given text, but the stylesheets referenced in the index.html (teammates->src->web) seemed to be passed in and not directly accessible. I tried creating a simple class inside of instructor-help-students-section.component.html as follows:
```
<script>
    class CustTag1 extends HTMLElement{
      constructor(){
        super();
      }
    }

    customElements.define('Cust-Tag1', CustTag1);

    var custTag1 = new CustTag1();
    custTag1.style.color = "red";
    document.body.appendChild(custTag1);

  </script>
```
But received an error message that if its a web component I would need to add a custom elements schema.

Screenshot (977)

**Comment by zhaojj2209** [comment]
@John-Poulos Apologies for the late response. TEAMMATES uses Angular for its frontend framework, please refer to the [Angular documentation](https://angular.io/guide/elements) for information on how to add custom components.

**Comment by zhaojj2209** [comment]
Closing as PR is superceded by #11975. Feel free to open the PR again if #11975 is ever closed without merging.

**Pull request closed without merging**
