### PR TITLE
[#11329] Release V8.0.0

### PR DESCRIPTION
**Pull request by wkurniawan07**
Part of #11329 

- Two minor backend updates: connection timeout values for Solr and slightly more secure `img-src` CSP rule
- Fixed L&P test failures introduced by upgrading to Java 11 (due to timestamp now being calculated in microsecond precision)
- Updated `developers.json`:
  - Updated committers/core team members after a long while
  - Added new contributors
  - Updated some outdated GH usernames; many past contributors unfortunately became @ghost and are subsequently removed
- Some documentation update
  - In particular, Python is no longer a requirement as we have decoupled from Cloud SDK
  - Python is needed if deployment is involved, but this is a separate requirement and will be reflected in the ops repository instead
- Added note for search feature brownout while we're indexing data (note that the date is changed to Aug 15 in code; can always be changed to any other date)
  Screenshot 2021-08-07 at 8 10 39 PM

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@damithc is the brownout message good enough?

**Comment by damithc** [comment]
> @damithc is the brownout message good enough?

@wkurniawan07 Can we make it more prominent, like in 'danger' style?  Let's make it 16th Aug.

**Comment by wkurniawan07** [comment]
Danger is too much though. It's not "you should not do this at all", but rather "you can do this, but be warned".

**Comment by damithc** [comment]
> Danger is too much though. It's not "you should not do this at all", but rather "you can do this, but be warned".

True

**Pull request merged**
