### PR TITLE
[#11941] Instructor creating courses: auto-trim text fields

### LINKED ISSUE #11941: Instructor creating courses: auto-trim text fields
v8.19.2, production

Current: When creating a course, there will be an error message if the course ID or the name has leading/trailing white spaces

image

Suggestion: Auto-trim those fields as such leading/trailing spaces are sure to be accidental rather than intended.

### PR DESCRIPTION
**Pull request by Haoting-Chen**
Fixes #11941

**Outline of Solution**

This pull request solves the issue by making the function `sanitizeForSaving()` in `CourseAttributes` to sanitize `name` so that untrimmed course names can be automatically trimmed.

**Demonstration**

image

image

**Reason**

As far as my understanding, the current process to create/update a course is to,

image
https://github.com/yengah/teammates/blob/henry_branch/src/main/java/teammates/storage/api/CoursesDb.java#L65-77

1) Store its temperory attributes in `CourseAttributes`
2) Sanitize the attributes using `sanitizeForSaving();`
3) Check validity using `getInvalidityInfo()`
4) Write into the database

The reason for editing the function `sanitizeForSaving()` is that the job of `sanitizeForSaving()` is to trim invalid names into valid ones. Since the `institute` name is trimmed by `sanitizeForSaving()`, it should be aligned with the original code structure to trim the course `name` using `sanitizeForSaving()` as well.

### CODE REVIEW

**Comment by Haoting-Chen** [comment]
I only make the program trim the course because the current toast for invalid course ID may be wrong. The toast mentions `Courses Name` instead of `Course ID`. I am not sure if it is necessary to open a new issue to solve it or just solve it here.

Current Toast
Screen Shot 2022-10-18 at 8 38 23 pm
Suggested Toast
Screen Shot 2022-10-18 at 8 43 22 pm

**Comment by Haoting-Chen** [comment]
Also, trimming the course ID may be risky. I have tried letting `sanitizeForSaving()` in `CourseAttributes`  to trim the course ID like the following
image

However, if I submit an untrimmed course ID. An error message occurs. And the message is from https://github.com/TEAMMATES/teammates/blob/master/src/main/java/teammates/ui/servlets/WebApiServlet.java#L99.
Even though, the course will still be added when refreshing the page.

Screen Shot 2022-10-18 at 9 22 36 pm

My suggestion is not to trim the course ID automatically. Unlike course names which can be edited at any time, the course ID is fixed once created. When a user enters a course ID, rather than implicitly fixing their invalid ID, it would be better to explicitly pop up a message to show what is wrong with the ID they entered.

**Comment by Haoting-Chen** [comment]
@zhaojj2209 Hi Zhao, regarding the small error in the toast I mentioned above, do you think it is necessary to fix it? Should we fix it here or in a new issue?

**Comment by zhaojj2209** [comment]
@Haoting-Chen It's a small enough change so you may add it to this PR. You're right that this error message will no longer show up, though; it'll still be good to change it for consistency nonetheless.

**Comment by Haoting-Chen** [comment]
@zhaojj2209 Cool. I have fixed it.

**Comment by Haoting-Chen** [comment]
@hhdqirui @ziqing26 are the changes made look fine?

**Review by ziqing26 — APPROVED** [review]
LGTM, thanks for the reminder!

**Comment by Haoting-Chen** [comment]
Thanks for reviewing the code!

**Pull request merged**
