### PR TITLE
Show "Participants who have not responded to any question" panel in grey #3328

### LINKED ISSUE #3328: Show "Participants who have not responded to any question" panel in grey
Currently shown in orange, which should be used for warnings. we can use grey instead.

### PR DESCRIPTION
**Pull request by tungnk1993**
Fixes #3328 

Preview
panel-grey

Though I'd like to also bold the panel (for consistency) and change panel color to red (better contrast)

### CODE REVIEW

**Comment by kanghj** [comment]
@tungnk1993, remember to update the tests (with godmode). If you have any suggestions, you can post screenshots of your suggested change for discussion here, or make a new issue (preferred).

**Comment by tungnk1993** [comment]
@kanghj, its a minor change so i will just post it here. If it is accepted, I can make new issue + PR, and also update the tests with godmode.

My suggestion
suggested

**Comment by damithc** [comment]
Let's use gray. Red is for errors.

**Comment by tungnk1993** [comment]
I used godmode to update pages, but for some pages (such as instructorFeedbackResultsSortSecondSessionFilteredBySectionA.html), I notice it causes some weird modification

weird

May I know what causes these problems and how to resolve them?

**Comment by kanghj** [comment]
@tungnk1993, what version of jdk are you running teammates on? Prior to this pr, did you manage to get dev green while setting up the project?

**Comment by tungnk1993** [comment]
@kanghj, sorry for late reply. I used jdk7 and I havent managed to get dev green. For testBackEndActions and testFrontEndActions, I am getting selenium web driver exception, "element is not clickable at point ....". I tried searching for solutions but it seems like a [bug](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2766)

May I know do I need to change anything else for this pull request?

**Comment by kanghj** [comment]
@tungnk1993, as far as I know, that test is passing for everyone else. You ran that test on master right? You can post the stack trace here if you want help to resolve those tests.

You need to sync your pull request as there are now merge conflicts that must be resolved.

**Comment by wkurniawan07** [comment]
@tungnk1993 yes that's expected for Chrome, sorry for not having updated the docs but Chrome is currently also not an option for testing (@kanghj this is precisely why) so you have to resort to Firefox. Any version between 38.0.5 and 42.0, would work well for this purpose.

**Comment by wkurniawan07** [comment]
Hi @tungnk1993 @kanghj, any progress on this PR? It'll be great if you can finish this soon. If you can't finish it by this milestone, let's push it to the next one.

**Comment by tungnk1993** [comment]
Some of the failed tests were due to the change i make after using godmode to generate pages (from panel-warning to panel-default). Should I revert those changes? If not, how should I resolve this?

Since I am pretty busy with other projects, I think its better to push to next one. Sorry about that

**Comment by kanghj** [comment]
The html comparison failing seems to be a file that you didn't modify in your commits, so you should run godmode on those files too.

**Comment by wkurniawan07** [comment]
@tungnk1993 no worries there, and the error seems like what @kanghj mentioned.

**Comment by wkurniawan07** [comment]
Hi @tungnk1993, any progress on this PR? It'll be great if you can finish this soon. If you can't finish it by this milestone, let's push it to the next one. However, if you abandon it for too long, I'm afraid I have to close it.

**Comment by wkurniawan07** [comment]
Closing due to inactivity.

**Pull request closed without merging**
