### PR TITLE
Make use of StringHelper.join() in ActivityLogEntry and AdminActivityLogPageData #6844

### LINKED ISSUE #6844: Make use of StringHelper.join() in ActivityLogEntry and AdminActivityLogPageData
In #6755, `StringHelper.join` is introduced, which is essentially the same as `String.join` method in Java 8.

`StringHelper.join` method can be used in `ActivityLogEntry.generateLogMessage()` and `AdminActivityLogPageData.getQueryKeywordsForInfo()`.

### PR DESCRIPTION
**Pull request by shrut1996**
Fixes #6844 

**Outline of Solution**

Used the `StringHelper.join()` method in `ActivityLogEntry.generateLogMessage()`  and `AdminActivityLogPageData.getQueryKeywordsForInfo()`

### CODE REVIEW

**Comment by shrut1996** [comment]
Not ready for review yet though

**Comment by xpdavid** [comment]
@shrut1996 Make comment when you are ready for review :)

**Comment by shrut1996** [comment]
@xpdavid Ready  for review :+1:

**Comment by shrut1996** [comment]
Sorry for the many commits but I'm getting an npm error while building. I can't figure out the problem. Could someone help me with this please?

**Comment by xpdavid** [comment]
@shrut1996 We have reported this issue to Travis Team. Don't worry. Should be fine in a while.

**Comment by shrut1996** [comment]
@xpdavid Thanks ! :)

**Comment by shrut1996** [comment]
@xpdavid Done :+1:

**Pull request merged**
