### PR TITLE
[#9346] [WIP] Use snackbar to show status message

### PR DESCRIPTION
**Pull request by monmanuela**
Part of #9346 

Currently, the page freezes when a snackbar appears.
image

### CODE REVIEW

**Comment by tanhengyeow** [comment]
@monmanuela Did you manage to find a workaround for the `~` issue that needs to be included manually for children files?

**Comment by monmanuela** [comment]
@tanhengyeow Not yet cause I'm still trying to get the snackbar working 😅 I'll look into it though. Right now, the page keeps freezing, as if it goes into an infinite loop. But I don't see any error message on the console. Do you happen to have an idea how I can fix this haha

**Comment by monmanuela** [comment]
@tanhengyeow Following suggestions [here](https://github.com/material-components/material-components-web/issues/981#issuecomment-362396837) and [here](https://github.com/angular/angular-cli/issues/2269#issuecomment-320050420), I added `stylePreprocessorOptions`. It seems to fix the import issue for me!

**Comment by monmanuela** [comment]
Closing this PR, replacing it with #9612

**Pull request closed without merging**
