### PR TITLE
Remove excess space in courseTable.tag #7961

### LINKED ISSUE #7961: Remove excess space in courseTable.tag
In [this line](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag#L17) of courseTable.tag, there are two spaces after the `<th`. Reduce this to one space and fix indentation of remaining attributes of that tag accordingly.

Possible tags: `d.FirstTimers`, `a-CodeQuality`.

### PR DESCRIPTION
**Pull request by varshav21**
Fixes #7961

### CODE REVIEW

**Comment by VamsiSangam** [comment]
@HirdayGupta , I think you should review this PR :smile:

**Comment by HirdayGupta** [comment]
@varshav21 A quick note: You might want to take a look at our [Orientation Task List](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list). By doing this `d.FirstTimers` issue successfully, you have already achieved quite a bit of what that task list set out to do, but I would recommend that you post an intorduction issue in our issue tracker, as outlined in [Phase D](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#phase-d-introduce-yourself-to-the-community) of the aforementioned task list. This serves the dual purpose of allowing the community to get to know you better and also so that we can have your full name to add to our contributors list.

**Comment by whipermr5** [comment]
@varshav21 May we have your full name for inclusion into the contributors' list? :)

**Comment by varshav21** [comment]
hi, sorry for the late reply.Full name is varsha venkatesh.

**Pull request merged**
