### PR TITLE
Instructor: search comments: fix 'Unparseable date' exception #7569

### LINKED ISSUE #7569: Instructor: search comments: fix 'Unparseable date' exception
v5.107
Received from the live server
```
Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet :
com.google.gson.JsonParseException: java.text.ParseException: Unparseable date: "Mar 1, 2016 11:59:00 PM"
at teammates.common.util.JsonUtils$TeammatesDateAdapter.deserialize(JsonUtils.java:107)
at teammates.common.util.JsonUtils$TeammatesDateAdapter.deserialize(JsonUtils.java:88)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
at com.google.gson.Gson.fromJson(Gson.java:887)
at com.google.gson.Gson.fromJson(Gson.java:852)
at com.google.gson.Gson.fromJson(Gson.java:801)
at teammates.common.util.JsonUtils.fromJson(JsonUtils.java:66)
at teammates.storage.search.FeedbackResponseCommentSearchDocument.fromResults(FeedbackResponseCommentSearchDocument.java:245)
at teammates.storage.api.FeedbackResponseCommentsDb.search(FeedbackResponseCommentsDb.java:400)
at teammates.logic.core.FeedbackResponseCommentsLogic.searchFeedbackResponseComments(FeedbackResponseCommentsLogic.java:160)
at teammates.logic.api.Logic.searchFeedbackResponseComments(Logic.java:2008)
at teammates.ui.controller.InstructorSearchPageAction.execute(InstructorSearchPageAction.java:57)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:50)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:661)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:621)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:591)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.text.ParseException: Unparseable date: "Mar 1, 2016 11:59:00 PM"
at java.text.DateFormat.parse(DateFormat.java:357)
at teammates.common.util.JsonUtils$TeammatesDateAdapter.deserialize(JsonUtils.java:105)
... 54 more
```
To reproduce:
Search for something while this check box is ticked
image

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7569

**Outline of Solution**

Make use of `JsonUtils`' existing [fallback code for legacy data](https://github.com/TEAMMATES/teammates/blob/935872235aae83981527f5861b79967b8b43144f/src/main/java/teammates/common/util/JsonUtils.java#L68-L69) by catching `ParseException` and rethrowing as `JsonSyntaxException` in `TeammatesDateAdapter`.

### CODE REVIEW

**Comment by damithc** [comment]
May be add a test case as well? Apparently, searching feedback comments is not covered in tests.

**Comment by wkurniawan07** [comment]
Searching for FRCs is currently being worked on in #7576. Even then, it will not be able to immediately catch the issue at hand because there is no concept of "legacy data" in CI; only live testing would catch this kind of problem.
I don't think writing a special code to test legacy data in CI justify the cost, and it will be outdated relatively quickly especially if migration is underway.

**Comment by damithc** [comment]
> I don't think writing a special code to test legacy data in CI justify the cost, and it will be outdated relatively quickly especially if migration is underway.

Yes, the preferred solution is to migrate the legacy data. No need to test for legacy data. However, it is a legit concern that data migration gets forgotten and subsequently the existence of legacy data gets forgotten leading to bugs like this. It's good if we have a mechanism to enforce data migration within a certain time frame. e.g. create an issue for data migration as soon as the data format changes and assign the issue it to a specific milestone right away.

**Comment by whipermr5** [comment]
Got it! I've created #7591 for the data migration.

**Pull request merged**
