### PR TITLE
[#11149] Students page: tweak text 

### LINKED ISSUE #11149: Students page: tweak text
image

Some minor cosmetic tweaks:
* Page title `Student List` -> `Students`
* Rephrase the explanation as follows:
  >Expand the panels below to view the details of students in each course. Use the ['Search' page]() if you need to locate the details of a specific student by name or email.

### PR DESCRIPTION
**Pull request by BoazWu**
Fixes #11149 

Ready for review.

### CODE REVIEW

**Comment by moziliar** [comment]
Hi @BoazWu, thanks for your contribution! However, your e2e test seems to be failing due to the UI change.
Do update the corresponding e2e changes. If you need help do ask here:)

**Comment by BoazWu** [comment]
Thanks for the response! Is there a way I can debug the e2e test to figure out what's causing the test failure and what I should change? Thanks

**Comment by rrtheonlyone** [comment]
@BoazWu Take a look at the logs here: https://github.com/TEAMMATES/teammates/pull/11209/checks?check_run_id=2867941698

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at teammates.e2e.pageobjects.AppPage.getNewPageInstance(AppPage.java:128)
	at teammates.e2e.pageobjects.AppPage.getNewPageInstance(AppPage.java:114)
	at teammates.e2e.cases.BaseE2ETestCase.getNewPageInstance(BaseE2ETestCase.java:189)
	at teammates.e2e.cases.BaseE2ETestCase.loginAdminToPage(BaseE2ETestCase.java:140)
	at teammates.e2e.cases.InstructorStudentListPageE2ETest.testAll(InstructorStudentListPageE2ETest.java:40)
	...

Failed suite [Failed suite [Failed suite [Failed suite [e2e-tests]]]] > e2e-tests(failed)(failed)(failed)(failed) > teammates.e2e.cases.InstructorStudentListPageE2ETest > testAll FAILED
    java.lang.RuntimeException at InstructorStudentListPageE2ETest.java:40
        Caused by: java.lang.reflect.InvocationTargetException at InstructorStudentListPageE2ETest.java:40
            Caused by: java.lang.IllegalStateException at InstructorStudentListPageE2ETest.java:40
````

We see that the trace from `InstructorStudentListPageE2ETest.java:40` is failing. Can you tell why and debug using the above? Let me know if you need help :)

**Comment by BoazWu** [comment]
I updated the failing E2E test

**Review by rrtheonlyone — APPROVED** [review]
LGTM 👍

**Pull request merged**
