### PR TITLE
email alerts sent to respondents: include session instructions #5768

### LINKED ISSUE #5768: email alerts sent to respondents: include session instructions
We can include session instructions in the email.

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #5768 

Includes Session Instructions in the Feedback Session Opening, Feedback Session Reminder, and Feedback Session Closing emails. It is also included in the email sent to instructors showing an example of the email sent to students.  

They are displayed in a box as per suggestion by @damithc 

As I have only been able to test on my Local Server (as my staging server ran out of quota), **please review and confirm whether session opening and session closing emails will indeed include the Session Instructions**. I can confirm from the logs of the local test that the reminder email will include it. 

**Screenshot** of new email design:

screen shot 2017-04-09 at 12 28 24 am

I used inline styling for cross-email-client compatibility.

Also, according to [this reference](https://templates.mailchimp.com/resources/email-client-css-support/) and [this reference](https://www.campaignmonitor.com/css/), All CSS styling I have used will be visible regardless of platform with the following exceptions:
- The `max-width` CSS property offers limited IE support and no Outlook 2007/10/13 support, which means older versions of IE and Outlook will not resize the Session Instructions Box to fit the window for a very small window.
- Outlook.com doesn't support any `margin` properties which means that the Session Instructions Box  will hug the left edge of the email-display window in Outlook.com.

### CODE REVIEW

**Comment by leeyimin** [comment]
@HirdayGupta The tests are failing as the expected html files of the generated emails are not updated. You can update the expected html files using [god mode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md).

**Comment by HirdayGupta** [comment]
@leeyimin can I get a little more guidance regarding God Mode? For example, in order to change the expected HTML of an email, which test suite would I have to run?

**Comment by thenaesh** [comment]
@HirdayGupta There's a godmode version of `All Tests` and `Failed Tests`. You should run all tests first without any godmode, then run the failing tests with godmode. Check the resulting HTML changes for anything suspicious after that.

What godmode does is essentially update the HTML tests such that they succeed. This is the opposite of what is normally done, which is to fix code until they pass tests. If carelessly used, it may render the HTML tests useless, so care must be taken.

**Comment by leeyimin** [comment]
@HirdayGupta To add on to what @thenaesh has said, it might also be good to only run god mode only on tests relevant to your changes to avoid unexpected changes in unrelated tests. In this case, you are changing the html templates of emails so you should run god mode on EmailGeneratorTest.

**Comment by HirdayGupta** [comment]
@leeyimin @thenaesh Thanks. Got it. New commit on the way.

**Comment by HirdayGupta** [comment]
@leeyimin should I then let the box resize according to parent viewport only? (i.e. remove max-width entirely?) Or just increase the max-width to something like 500px? 

In the meantime I will also start looking into the outlook problem.

**Comment by leeyimin** [comment]
@HirdayGupta 500-600px seems like a safe max-width. 

Regarding the outlook issue, one solution is to use table, instead of div. The max-width on table seems to work on outlook desktop as well.
image

This are the settings tested out.
```
<table style="max-width:600px;border:1px solid black;border-collapse:collapse">
  <tr>
    <th style="border:1px solid black;padding:10px;border-collapse:collapse">
      Instructions for this feedback session are:
    </th>
  </tr>
  <tr>
    <td style="border:1px solid black;padding:10px;border-collapse:collapse">
      <p>The instructions.</p>
    </td>
  </tr>
</table>
```

**Comment by HirdayGupta** [comment]
@leeyimin sincerest apologies. I have been having some dev trouble with this branch and have opened a new PR (#7138) continuing the discussion of the solution to this issue. I have implemented all requested changes in the new PR.

**Pull request closed without merging**
