### PR TITLE
[#11967] adding dark mode toggle

### LINKED ISSUE #11967: adding dark mode toggle
dark mode is like the most loved thing by users specially the student . I think I can help this website get a dark mode. 

- **Environment**: 

**Description of feature/enhancement**

**Justification**

**Existing similar features and their shortcomings**

### PR DESCRIPTION
**Pull request by U6729988**
Fixes #11967

Outline of Solution

We add the dark theme toggle in the top bar and define the colour and style of the button in the CSS file.

### CODE REVIEW

**Comment by zhaojj2209** [comment]
Lint tests are failing, please fix the tests.

**Comment by U6729988** [comment]
Hi Zhao,

I have tried to fix the tests. However, I am still stuck and do not have any idea what I need to do next. Can I have some help?

Best Regards,

Henry

On 3 Nov 2022, at 2:40 am, Zhao Jingjing ***@***.***> wrote:



Lint tests are failing, please fix the tests.

**Comment by zhaojj2209** [comment]
> Hi Zhao, I have tried to fix the tests. However, I am still stuck and do not have any idea what I need to do next. Can I have some help?

To fix the lint tests, please run `npm run lint` on your local machine and address the errors that are thrown. The errors provide information on what to change as well as the line that should be changed.

**Comment by U6729988** [comment]
I fix part of the tests, but still got problem.

[Screenshot 2022-11-03 at 8.26.33 pm.png]

On 3 Nov 2022, at 7:49 pm, Zhao Jingjing ***@***.***> wrote:



Hi Zhao, I have tried to fix the tests. However, I am still stuck and do not have any idea what I need to do next. Can I have some help?

To fix the lint tests, please run npm run lint on your local machine and address the errors that are thrown. The errors provide information on what to change as well as the line that should be changed.

**Comment by zhaojj2209** [comment]
> I fix part of the tests, but still got problem.

Then fix all of the errors. That's the entire point of linting: to ensure that all code changes are styled consistently with the rest of the codebase.

**Comment by zhaojj2209** [comment]
Closing due to inactivity. Feel free to reopen the PR if you would like to resume working on it.

**Pull request closed without merging**
