### PR TITLE
5891-remove-unused-method-finishRequest

### LINKED ISSUE #5891: Remove finishRequest in Datastore.java
It is unused

### PR DESCRIPTION
**Pull request by AbhiramU**
Fixes #5891  

Removed unused method finishRequest() from Datastore class

### CODE REVIEW

**Comment by chowyb** [comment]
@AbhiramU you will need to remove the following line (near the top of the file) as well:

`import javax.jdo.Transaction;`

**Comment by AbhiramU** [comment]
@chowyb  
Is it fine now?

**Comment by chowyb** [comment]
@AbhiramU yep, the build passes on our CI sever now; this pull request is good to go :+1:

**Comment by damithc** [comment]
PR title doesn't match with issue title

**Comment by chowyb** [comment]
Oh whoops, missed that :(

**Comment by AbhiramU** [comment]
Is it fine now






On Fri, Aug 19, 2016 at 8:13 PM +0530, "chowyb" <notifications@github.com> wrote:





Oh whoops, missed that :(

**Comment by chowyb** [comment]
@AbhiramU you should copy the issue name of the original issue along with its number, instead of the branch name.

**Comment by wkurniawan07** [comment]
Hi @AbhiramU, another PR which addresses this issue (#6026) has successfully been merged into the repository, so I have to close this one. You can take a look at that PR to see what is expected for the naming conventions etc.
Meanwhile, if you want to contribute more fixes, feel free to move on to `d.Contributors`-labelled issues.

**Pull request closed without merging**
