### PR TITLE
[#10243] Button style changes

### PR DESCRIPTION
**Pull request by ccyccyccy**
Part of #10243 
Fixes https://github.com/TEAMMATES/teammates/issues/10342

- Add border to `btn-light`
    - Style: `border 1px solid #DDD`
    - `#EEE` on hover
    - image
- Convert most `btn-secondary` to `btn-light`
    - image
- Add `btn-success` to appropriate buttons
- Standardize margins of buttons to `10px`
    - image
- Change button styles on panels
    - image

~Below are screenshots of two different shades of grey borders, `#DDD`, vs `#EEE`.~
~@damithc Need you to check which one you like better.~
~Going with `#DDD` on borders, with `#EEE` for disabled buttons.~

### CODE REVIEW

**Comment by damithc** [comment]
Can you mark which buttons to focus on? For example, not relevant to buttons in panel/table headings as those are not supposed to be _light_ in the first pace, right?

**Comment by ccyccyccy** [comment]
> Can you mark which buttons to focus on? For example, not relevant to buttons in panel/table headings as those are not supposed to be _light_ in the first pace, right?

@damithc Have updated the screenshots.

**Comment by damithc** [comment]
What about disabled buttons? The border should be added for them too, right?
w.r.t. the two colors, I can't see a big difference, so I'm OK with either.

**Comment by ccyccyccy** [comment]
> What about disabled buttons? The border should be added for them too, right?

I think it's better for them to not have borders? Gives them the more distinct disabled look
image
image

**Comment by damithc** [comment]
> I think it's better for them to not have borders? Gives them the more distinct disabled look

The problem is they blend into the background, which is the problem we are trying to solve with boarders. Let's go with borders for disabled buttons as well. Or at least add a lighter border for disabled buttons.

**Comment by madanalogy** [comment]
@ccyccyccy need your help resolving the merge conflicts, thanks!

**Pull request merged**
