### PR TITLE
[#9818] Natural sort for tables

### LINKED ISSUE #9819: Natural sort for tables
- **Environment**: 
`master` branch at commit e4700402dcc9a3ae6193d2501b069da096d6c47a

Currently, sorting is done alphabetically by default. However, if there are multi-digit numbers in the labels, the sorting is not intuitive e.g "Team 11" will come first before "Team 2".

But natural sorting can't be applied to all labels with numbers e.g course IDs where the first digit indicates the level and there's a variable number of digits. Say, CS1010 is before CS202.

Have to explore where to place natural sorting and how to implement it.

### PR DESCRIPTION
**Pull request by jtankw3**
Fixes #9819

**Outline of Solution**

- Extracted SortBy and SortOrder enums to sort-properties.ts to consolidate all possible properties that tables are sorted by.

- Added TableComparatorService to contain different comparison methods for different element types and ensure consistent sorting across tables. Currently have lexicographic and natural comparison.

- SessionName, SectionName and TeamName set to be sorted naturally while all other elements remain sorted lexicographically. This is because only these three elements are likely to contain content that should be sorted naturally such as "Week10-Feedback", "Section 10", "Team 10" etc.

- Applied TableComparatorService to student-list component.

- TODO: If PR is approved, apply TableComparatorService to:

- [x]  sessions-table-model
- [x] student-list-info-table
- [x] instructor-courses-page
- [x] copy-questions-from-other-sessions-modal

**Screenshot**
Team name sorted naturally:
natural-sort-teamname

Email sorted lexicographically:
lexicographical-sort-email

### CODE REVIEW

**Comment by jtankw3** [comment]
> Awesome! Are these all the places that need sorting?

Aside from the student-list component, sessions-table-model, student-list-info-table, instructor-courses-page, copy-questions-from-other-sessions-modal are the only other components I could find that involves sorting a table.

Should I start editing each component to use the new service?

**Comment by xpdavid** [comment]
Go ahead.

**Comment by xpdavid** [comment]
You can consider do a rebase of your changes to the current master and do force-push.

You have a lot of irrelevant changes in your PR right now.

**Comment by jtankw3** [comment]
Done updating all pages, screenshots below:

**student-list:**
Instructor Student Page
instructor-student-page

Instructor Search Page
instructor-search-page

**session-table**
Instructor Home Page
instructor-home-page

Instructor Sessions Page
instructor-sessions-page

**student-list-info-table**
resent-results-link-modal
resend-modal

**instructor-courses-page**
instructor-courses-page

**copy-questions-from-other-sessions-modal**
copy-questions

**Pull request merged**
