### PR TITLE
id="caption" in static pages should be class instead #6190

### LINKED ISSUE #6190: id="caption" in static pages should be class instead
~~Multiple instances of `<h2 id="caption">...</h2>` (... are some context-specific texts).
It is invalid for multiple HTML elements to have the same ID, but the ID is not meaningful anyway so it can be removed.~~

Edit (12/12/16): 
The said selector is used for styling purpose, however styling with ID is in general not preferred due to its fragility to changes. It also necessitates one of the static pages, `features.jsp`, to have duplicated IDs which is invalid.
Based on the purpose, it should be `class="caption"` instead.

### PR DESCRIPTION
**Pull request by xpdavid**
Fixes #6190

### CODE REVIEW

**Comment by damithc** [comment]
@xpdavid Let us know when ready for review.

**Comment by xpdavid** [comment]
@damithc Ready for review.

**Comment by damithc** [comment]
@wkurniawan07 for your review please.

**Comment by xpdavid** [comment]
@wkurniawan07 Ready for Review.
Travis CI went wrong accidentally because its server cannot download google sdk :(, can you restart it?
I have deployed the changed version in my server (can be viewed here http://4-18-1-1-dot-teammates-xiaopu.appspot.com/features.jsp)

**Pull request merged**
