### PR TITLE
[#10805] Browse by topic listing comes over the text

### LINKED ISSUE #10805: Browse by topic listing comes over the text
[Help for instructions page][small screen mode]Browse my topic listing comes over the text

LIVE TEAMMATES V7.3.1

Steps to reproduce
1. Go to this page: https://teammatesv4.appspot.com/web/front/help/instructor
2. Reduce the size of the browser

Expected results:
Browse by topics words should not overlap with the info text

Actual results:
Browse by topics words overlaps with the info text

SCREENSHOT attached!

Screenshot 2020-10-23 at 15 54 53

### PR DESCRIPTION
**Pull request by Suiiyush**
Fixes #10805 

**Outline of Solution**

- Gave an id "browse-by-topic" to the browse by topic listing.
- Added a media query that hides the browse by topic listing when the screen width goes below 500 px which is when it started to overlap the other elements on the webpage.

I gave it an id so that the media query does not affect any other element sharing the same class as browse by topic listing.

READY FOR REVIEW

### CODE REVIEW

**Comment by madanalogy** [comment]
@Suiiyush could you upload some screenshots for manual verification of the fix?

**Comment by Suiiyush** [comment]
**The Element appears as long as the screen width is above 500 px**
Screenshot (1344)

**The added media query hides the element once the screen width goes below 500px**
Screenshot (1345)

**Here you can see it working outside the responsive view**
Screenshot (1350)
Screenshot (1352)

**Also here's a screen recording to show it working better** -> [Screen Recording](https://drive.google.com/drive/folders/15zmJPS1XpLyTDrbrvcVPdqjzQ92WfSxE?usp=sharing)

**Review by madanalogy — APPROVED** [review]
LGTM!

**Review by wkurniawan07 — COMMENTED** [review]
It works in that the browse by topic is no longer displayed, but now there is a weird empty right-hand-side padding for smaller screens?

**Comment by jianhandev** [comment]
> It works in that the browse by topic is no longer displayed, but now there is a weird empty right-hand-side padding for smaller screens?

Hi! I have fixed this issue in my latest PR (#10864)

**Pull request closed without merging**
