### PR TITLE
Use enum instead of string for gender field in StudentProfileAttributes and related classes #7603

### LINKED ISSUE #7603: Use enum instead of string for gender field in StudentProfileAttributes and related classes
Replace 'gender' field with corresponding enum for StudentProfileAttributes and related classes.
Currently gender field is String that only accepts "male", "female" or "other" values, so It's better to use enum over String value in that case.

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #7603 

outline of the solution---
1)instead of using the string for gender variable i.e. male female and other I have used enum in StudentProfileAttributes
2)All the related class which use the variable gender has also been change to use enum

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
kimdly @whipermr5  confirm this PR . i will consider change as suggested by u

**Comment by wkurniawan07** [comment]
@shaharyar-shamshi before anyone reviews this, do take note of the following which you should fix:
- You're including changes from other issues (#8119).
- You're removing `.gitignore`, which has resulted in inclusion of more than 15,000 unnecessary files. In addition, it seems like you deleted `instructorFeedbackEdit.js` and `StudentProfilePage.java`, which should not be the case.

**Comment by shaharyar-shamshi** [comment]
I am sorry Sir @wkurniawan07   I need your help . Actually I searched lot on the internet but was not able to get the solution of this problems ( problem you mentioned in the last comment).I will be highly thankfull to you for this  .

**Comment by wkurniawan07** [comment]
@shaharyar-shamshi, rather than pushing small changes one by one and getting red "X"s, it would be better if you run `./gradlew lint` locally and make sure it passes.
In addition, even though you have restored `.gitignore`, the 15000+ unnecessary files are still there. You need to revert them.

**Comment by shaharyar-shamshi** [comment]
sorry sir @wkurniawan07  next time I will not commit same mistake sorry

**Comment by shaharyar-shamshi** [comment]
sir @wkurniawan07 I am extremely sorry 
1)But after lot of attempt I am still not able to figure out how remove those extra files
2)./gradlew lint pass on my local machine but it is failing here 
  can you please guide me for this I will be thankful to you

**Comment by damithc** [comment]
@shaharyar-shamshi if it is too hard to revert the git mistakes, you can close this PR and start over with a new branch and a new PR.

**Comment by wkurniawan07** [comment]
> after lot of attempt I am still not able to figure out how remove those extra files

@shaharyar-shamshi what exactly have you tried?

**Pull request closed without merging**
