### PR TITLE
[#9679] Instructor: Preview Sessions Submission Page's navbar covers some content on the page

### LINKED ISSUE #9679: Instructor: Preview Sessions Submission Page's navbar covers some content on the page
**Environment**: 
`master` branch

**Steps to reproduce**
1. Create an instructor with a lengthy name e.g. "dsadadasdsadadsadsadadasdsadadasdsadadsadsadadasdsadadasdsadadsadsadadasdsadadasdsadadsadsadadasdsad"
2. Edit a Feedback Session
3. Preview the session submission results with the instructor that has lengthy name e.g.
image

**Expected behaviour**
The content on the page shouldn't be covered e.g.
image

**Actual behaviour**
Some content on the page is covered e.g.
image

**Additional info**
This is because the current page is using `class="navbar fixed-top ...."`. We should explore something that is more responsive.

### PR DESCRIPTION
**Pull request by hcwong**
Fixes #9679 

**Outline of Solution**

Just does a check of navbar height using `ngDoCheck`, and changes the padding on the top if the navbar height is too large and covers content

EDIT: Changed navbar to no longer make it fixed

### CODE REVIEW

**Comment by hcwong** [comment]
> Looking at the issue this seems like it might be pretty hard for a first timer issue.
> 
> This resolves the problem but there are a few issues. If there is a notification:
> image
> then the notification is still blocked.
> 
> The 2nd issue is that this only works on page load. So, for example, if I create an instructor with the name "dsadadasdsad dsadsadadasd adadasdsadads dsadadasdsa adasdsadads dsadadasdsada asdsadadsadsad dasdsad " (containing spaces so that word wrap will be done) and re-size the page after page load, as I shrink the browser window the text starts being blocked again. Ideally we would prefer if this does not happen.
> 
> Finally I feel like this solution is not very elegant, because it kind of 'brute forces' a solution by setting the margin the value it needs to be. Ideally a solution would involve responsive css which would adapt the page no matter the height of the container. My suggestion would be to not make the "Previewing session as instructor ..." message fixed and just add it to the content window, so the rest of the content flows naturally below it. This would of course make the menu bar visible, but I think that should be fine.

Yea making it not `position fixed` will help. But for the feedback thing, the `z-index` of the navbar is very high, so we can consider making the feedback modal have a higher `z-index`, which it should.

Another alternative is to truncate the name if it gets too long and display it with some tooltip.

**Comment by ChooJeremy** [comment]
> Yea making it not `position fixed` will help. But for the feedback thing, the `z-index` of the navbar is very high, so we can consider making the feedback modal have a higher `z-index`, which it should.

That's a good solution for the first issue.

> 
> Another alternative is to truncate the name if it gets too long and display it with some tooltip.

I don't think we really want to solve it this way. While this solves the issue if the name is too long, the problem does still appear if the window width is too small, since the "Previewing session as instructor" can potentially be split into 2 lines.

**Comment by hcwong** [comment]
> > Yea making it not `position fixed` will help. But for the feedback thing, the `z-index` of the navbar is very high, so we can consider making the feedback modal have a higher `z-index`, which it should.
> 
> That's a good solution for the first issue.
> 
> > Another alternative is to truncate the name if it gets too long and display it with some tooltip.
> 
> I don't think we really want to solve it this way. While this solves the issue if the name is too long, the problem does still appear if the window width is too small, since the "Previewing session as instructor" can potentially be split into 2 lines.

Do we have a fixed set of z-index values that we used. I dont want to increase z-index arbitrarily and lead to some z-index arms race

**Comment by ChooJeremy** [comment]
> Do we have a fixed set of `z-index` values that we use. I dont want to increase `z-index` arbitrarily and lead to some `z-index` arms race

Not as far as I'm aware of. A brief search on IntelliJ just shows some hard-coded values: 2000, 2001, 1151, 10, 999, -1. @xpdavid is there any list?

If not it would be good to set up some z-index constants somewhere that is referenced within the css.

**Comment by hcwong** [comment]
> > Do we have a fixed set of `z-index` values that we use. I dont want to increase `z-index` arbitrarily and lead to some `z-index` arms race
> 
> Not as far as I'm aware of. A brief search on IntelliJ just shows some hard-coded values: 2000, 2001, 1151, 10, 999, -1. @xpdavid is there any list?
> 
> If not it would be good to set up some z-index constants somewhere that is referenced within the css.

Cool 👍scss should make this pretty convenient . In any case I've removed the class which caused the z-index to go up because it wasnt being used anymore. 

Also I have attached the photos of what it looks like. Let me know if it's alright. 

Screen Shot 2020-01-22 at 2 44 54 PM

Screen Shot 2020-01-22 at 2 45 01 PM

**Pull request merged**
