### PR TITLE
[#12230] Extension Confirm Modal: Misplaced submit buttons on mobile

### LINKED ISSUE #12230: Extension Confirm Modal: Misplaced submit buttons on mobile
problem

- **Environment**: On [production website](https://teammatesv4.appspot.com/web/front/home) 

**Steps to reproduce**

1. Access the production website on **mobile**.
2. Login as an instructor and go to `Home`.
3. For any sessions, click on `Edit`.
4. Scroll to section with link to `Individual Deadline Extensions`.
5. Click on `Individual Deadline Extensions`.
6. Extend the deadline for any student and click `Extend / Edit`. A modal will pop up to confirm the extension duration.
7. Click on any duration and click `Save changes`. A modal with the problematic buttons will pop up.

**Expected behaviour**

- Submit buttons should be inside the footer of the modal, similar to the behavior of other modals.

**Actual behaviour**

- Buttons are outside of the footer of the modal.

**Additional info**

- May be caused by use of `<fieldset>` element to wrap modal, which disrupts the `modal-footer`'s `flex` CSS
    - Relevant stackoverflow question: https://stackoverflow.com/questions/28078681/why-cant-fieldset-be-flex-containers

### PR DESCRIPTION
**Pull request by hollymvargas**
Fixes #12230

**Outline of Solution**
The problem had to do with padding styling that was attached to the modal-footer class. Instead of removing that styling, as I didn't know what other modals used it, I decided to use bootstrap5 padding classes to override it.

Screenshot before the fix:
image

Screenshot after the fix: 
image

### CODE REVIEW

**Review by jasonqiu212 — COMMENTED** [review]
Hi @hollymvargas, Thank you for your contribution!

Would it be possible to update the snapshot tests as well? I believe they are currently failing from the changes.

**Comment by hollymvargas** [comment]
Ready for review! I updated the test accordingly.

**Review by jasonqiu212 — APPROVED** [review]
LGTM! Thanks for the contribution

**Review by weiquu — APPROVED** [review]
LGTM!

**Pull request merged**
