### PR TITLE
[#9573]  Add student profile photo feature

### LINKED ISSUE #9573: Confusing user flow in Student Profile upload photo feature
- **Environment**: `master` branch, commit `ba5b2ef`

**Steps to reproduce**
- Go to Student Profile page
- Click `Upload/Edit Photo`
- Click `Browse` and choose a picture
- Click `Upload Picture`

**Expected behaviour**
The new picture should appear in the modal so that it can be cropped and edited, but the old photo should remain in the background

**Actual behaviour**
The old photo is already replaced by the new photo even before I click `Save Edited Photo`

**Additional info**

I think a better flow would be after choosing the new photo, the new photo should appear in the cropper immediately. Then, the `Upload Picture` button can be removed and saving the changes can be done by clicking `Save Edited Photo`.

### PR DESCRIPTION
**Pull request by ariendy**
Fixes #9573 

This is still work-in-progress.

**Outline of Solution**

So far I modified uploadPicture method to accept a boolean value that update the old photo only  when "Save edited photo" button is clicked and it doesn't if "Upload Picture" is clicked.

Making the photo available in the cropper right after being chosen is still pending.

### CODE REVIEW

**Comment by ariendy** [comment]
@monmanuela I think I need some help here. I delete "Upload Picture" button as suggested in the issue and made adjustments test accordingly so that they could pass. On my local it worked find but CI fails when testing saying that it can't find this button. Is there anything I should have done before pushing?

**Comment by monmanuela** [comment]
Hi @ariendy, good work so far! The failing test is an E2E test. However, I just noticed that the backend for this page is still under migration, and as a result, the user flow will change too (refer here https://github.com/TEAMMATES/teammates/pull/9575#issuecomment-478362656). I think it's best to put this PR on hold first, and after the backend is done being migrated, we'll see if we can incorporate some of the changes you proposed or work together to do additional improvements :) thank you for your understanding!

**Comment by ariendy** [comment]
Thank you for your quick answer. I appreciate it!

**Comment by xpdavid** [comment]
Closed due to investigation and #9575.

**Pull request closed without merging**
