### PR TITLE
[#12280] Improve display for create course card header

### LINKED ISSUE #12280: Instructor courses page: Improve display of create course card header
Currently, the display of the create course card header doesn't work well on mobile:
photo_2023-03-28 14 00 05

Suggestion: switch to column format on mobile screen sizes, similar to the card headers for the instructor edit page (example below).

Screenshot 2023-03-28 at 15 07 46

### PR DESCRIPTION
**Pull request by domoberzin**
Fixes #12280 

**Outline of Solution**

- Modified the CSS for screen widths  <= 768px for the card header elements to appear column-wise. Styling for larger screen sizes remains the same

 

## Original appearance on small screens
image

## Appearance after changes
image

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @domoberzin, just 2 comments:

1. The fix has also changed the buttons for the Edit Course Details page, rendering them inconsistent (see example below - they are on a new line now, rather than being on the same line like Instructor 1). I would suggest applying the styles only when the course edit form is in add mode.
Screenshot 2023-07-03 at 9 01 01 PM


2. Let's change the breakpoint to 576px, similar to how the buttons work in the Edit Feedback Session page. I think the current breakpoint leaves a bit too much space. You might want to take a look at the question-edit-form component.

**Comment by domoberzin** [comment]
Hey @weiquu , thanks for the feedback. I've updated the branch with the changes you've mentioned

**Review by weiquu — APPROVED** [review]
LGTM!

**Review by domlimm — APPROVED** [review]
LGTM! Great use of conditional and flex to tackle this issue. Thank you for your contribution!

**Pull request merged**
