### PR TITLE
[#12588] Improve test code coverage of core components - ToastComponent

### PR DESCRIPTION
**Pull request by techMedMau**
Part of #12588 

**Outline of Solution**
Add test cases in `src/web/app/components/toast/toast.component.spec.ts`

### CODE REVIEW

**Review by cedricongjh — APPROVED** [review]
LGTM, thank you for your contribution!

**Review by domlimm — COMMENTED** [review]
Let's add the case for:
```typescript
/**
   * Returns true if the argument passed is a TemplateRef.
   */
  isTemplate(): boolean {
    if (!this.toast) {
      return false; // done!
    }
    // a case for this too! please and thank you
    return this.toast.message instanceof TemplateRef;
  }
```

**Comment by techMedMau** [comment]
> Let's add a test for:
> 
> ```ts
> /**
>    * Returns true if the argument passed is a TemplateRef.
>    */
>   isTemplate(): boolean {
>     if (!this.toast) {
>       return false; // done!
>     }
>     // a test for this too! please and thank you
>     return this.toast.message instanceof TemplateRef;
>   }
> ```

Added

**Review by domlimm — APPROVED** [review]
LGTM!

**Pull request merged**
