### PR TITLE
[#11862] Instructor viewing results: make critical error message persist 

### LINKED ISSUE #11862: Instructor viewing results: critical error message does not persist
Context: An instructor is viewing results of a session. She clicks on a question panel to expand it, but the operation times out in the back end.

Current: The following message appears for a while and disappears. The spinner keeps going.
image
image

Problem: The user can miss this critical information if she was not watching the page continuously. There is a good chance she could be doing something else while the page is loading, given the loading is going to take considerable time.

Expected: The error message persists until the user dismisses it. Alternatively, the spinner can be replaced with an error message.

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Fixes #11862 

**Outline of Solution**

Make the error appear inside the question tab if a critical error occurs.

### CODE REVIEW

**Comment by sivayogasubramanian** [comment]
Before:


https://user-images.githubusercontent.com/53614454/173188245-2d88f73f-da79-4c05-a803-488a3759d766.mp4



After: 

https://user-images.githubusercontent.com/53614454/173188244-61bde1d0-5ea0-4618-8589-eba7a0ae3a3c.mp4

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]
Disagree with the solution direction. For this case it is definitely to display the error message within the panel itself (where the loading spinner is) because (1) the toasts could stack up if multiple questions face the same problem, and (2) the loading spinner stays in the panel indefinitely, not an accurate indicator because there is no more "loading" in motion.

**Comment by sivayogasubramanian** [comment]
https://user-images.githubusercontent.com/53614454/173618152-68f34e4c-bba8-4b82-b2a7-1ceb8ff49223.mp4

**Comment by damithc** [comment]
@sivayogasubramanian I have no objections to this version.

**Comment by samuelfangjw** [comment]
Would it be possible to use the existing `tm-loading-retry` component for this? While this implementation looks nice, it's not consistent with how we handle these types of errors in other pages.

**Comment by sivayogasubramanian** [comment]
@samuelfangjw Used `tm-loading-retry`. I also realized that I missed the other views in the earlier implementation. Added it now.

### Question View

https://user-images.githubusercontent.com/53614454/175961641-32fd09e0-545f-4b07-b259-aaf99ba81478.mp4

### GRQ View 

https://user-images.githubusercontent.com/53614454/175961669-55de3cb6-e519-4995-b92a-937975c19ca8.mp4

### RGQ View

https://user-images.githubusercontent.com/53614454/175961703-d30c3a46-efd3-47c3-9ab3-c63273194e6d.mp4

### GQR View

https://user-images.githubusercontent.com/53614454/175961730-df3eea41-b09f-4ec7-911e-86845531aac7.mp4

### RQG View

https://user-images.githubusercontent.com/53614454/175961768-854e4033-75fc-49f1-9eb0-ea3255ab4cd2.mp4

**Review by wkurniawan07 — APPROVED** [review]
LGTM, good work

**Review by ziqing26 — APPROVED** [review]
LGTM! 👍

**Comment by sivayogasubramanian** [comment]
> Just need to fix the failed tests

Help to re-run the test. It will fix itself.

**Pull request merged**
