### PR TITLE
AccountAttributes: remove HTML sanitization before saving for email #8775

### LINKED ISSUE #8775: AccountAttributes: remove HTML sanitization before saving for email
As per #8774, sanitization of email will be performed during rendering if required.

Currently, a valid email containing `<>"/'&` would become an invalid email after sanitization, leading to failure when trying to persist an account with such an email.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #8775

The only time these email addresses are displayed in the frontend are in admin pages. Hence, handling of double sanitisation (which happens when displaying existing accounts with already-sanitised emails) is not done.

### CODE REVIEW

**Comment by tran-tien-dat** [comment]
I don't think we need to sanitize `statusToAdmin`. It is not where the information is rendered. It is saved in the log and later rendered, where it is already sanitized.

**Comment by whipermr5** [comment]
@tran-tien-dat Oh! 😅 Thanks for letting me know

**Comment by tran-tien-dat** [comment]
Actually, I think for this kind of PR, it's more important to show evidence that you have sanitized everywhere where the field is rendered. But to be honest, I'm not sure how to show it in a PR, and how a reviewer can verify it 😅. What I'm doing now is looking at every read of the field in IntelliJ and see whether it will lead to some HTML file.

**Comment by whipermr5** [comment]
> What I'm doing now is looking at every read of the field in IntelliJ and see whether it will lead to some HTML file.

Yup that's what I did. Yea it's definitely tedious but I think it's best that the reviewer verify it independently? Thanks for the review!

On a separate note, the possibility of script injection via an email address is really quite low. The valid special characters (space and `"(),:;<>@[\]`) are only allowed with restrictions ([link](https://stackoverflow.com/a/2049510)), and our own email regex doesn't even allow them. Not sure how possible it is to do script injection with something that passes our email regex.
https://github.com/TEAMMATES/teammates/blob/b5ef1bc2913dbd199101aacafb7f572e4c3fc386/src/main/java/teammates/common/util/FieldValidator.java#L234-L243

**Pull request merged**
