### PR TITLE
[#11878] Add Admin E2E Tests

### PR DESCRIPTION
**Pull request by domoberzin**
Part of #11878 

**Outline of Solution**

### CODE REVIEW

**Comment by ziqing26** [comment]
@domoberzin pls resolve the conflict 🙏

**Review by dishenggg — COMMENTED** [review]
Looks good just 1 comment

**Comment by ziqing26** [comment]
@domoberzin let's address Di Sheng's comments in a commit
@EuniceSim142 pls review this soon

**Review by ziqing26 — APPROVED** [review]
LGTM!

**Pull request merged**
