### PR TITLE
[#12048] Migrate CreateInstructorAction

### PR DESCRIPTION
**Pull request by mingyuanc**
## Migrate CreateInstructorAction Summary

**Changes**
- Added private method `CreateInstructorAction::executeWithSql` which adds the instructor with default attributes
- Aforementioned default attribute is generated in the `CreateInstructorAction::createInstructorWithBasicAttributesSql`method
- Refactor `CreateInstructorAction::execute` method to reduce code duplication
- Perform a check to ensure email is unique within the course before persisting it
- Added testcases
  - I only tested success and constraints, I believe validating instructor input is done in UpdateInstructorActionIT

**TODO**
- [X] Add testcases

### CODE REVIEW

**Review by kevin9foong — COMMENTED** [review]
LGTM. 

Just need to write some tests and should be ready to merge.

**Review by NicolasCwy — APPROVED** [review]
LGTM, nice work!

**Comment by weiquu** [comment]
Sorry @mingyuanc do you mind looking at the failing checks before we merge in? Can ping us if you face any issues

**Comment by mingyuanc** [comment]
> [ ](/mingyuanc)



> Sorry @mingyuanc do you mind looking at the failing checks before we merge in? Can ping us if you face any issues
Hey i tried my best to fix all the issues but i cant seem to pass the last one, could you advise me on how i could do so

**Comment by mingyuanc** [comment]
@weiquu 
Hey i managed to fix most of the issues but is unable to fix the last one (E2E). Could you help me with that?

**Comment by weiquu** [comment]
> @weiquu Hey i managed to fix most of the issues but is unable to fix the last one (E2E). Could you help me with that?

Oops sorry the E2E test is expected to fail since it hasn't been changed to the new methods, so it's fine. Thanks for the speedy fix!

**Comment by NicolasCwy** [comment]
@mingyuanc Bump on this! Your PR is almost there :)

**Review by cedricongjh — APPROVED** [review]
LGTM, thanks!

**Comment by cedricongjh** [comment]
@mingyuanc do fix the linting checks before we merge this in, thank you

**Comment by NicolasCwy** [comment]
@mingyuanc,  I think cedric is talking about the changes to white space for lines which you have not done any changes to

**Pull request merged**
