### PR TITLE
[#10433] Instructor view results: Use fixed-width floating numbers

### LINKED ISSUE #10433: Instructor view results: Use fixed-width floating numbers
V7:
image

V6:
image

### PR DESCRIPTION
**Pull request by DanielMcBane**
Fixes #10433 

I added ().toFixed(2) to lines 65, 82, and 83. This causes the value returned to always go to two decimal places e.g. 1 -> 1.00, 2.1 -> 2.10, 3.222 -> 3.22, etc.
two_decimal_places

### CODE REVIEW

**Review by Derek-Hardy — APPROVED** [review]
LGTM

**Review by ccyccyccy — COMMENTED** [review]
Looks good. I think we don't need the paranthesis to call `toFixed()`?

**Comment by DanielMcBane** [comment]
parentheses_needed
After further testing, it appears to me that the parentheses are needed.

**Review by madanalogy — APPROVED** [review]
LGTM. Thanks for your contribution!

**Pull request merged**
