### PR TITLE
Add new rules to Checkstyle-Whitespace around operators 0

### PR DESCRIPTION
**Pull request by JosephineKwa**
Part 0 of add whitespace around rule to Checkstyle.
Added whitespace around rule for the following operators: 
assignment `=`
bitwise AND `&`
bitwise AND assignment `&=`
bitwise OR `|`
bitwise OR assignment `|=`
unsigned shift right `>>>`
unsigned shift right assignment `>>>=`
bitwise exclusive OR `^`
bitwise exclusive OR assignment `^=`
colon `:`
division `/`
division assignment `/=`
equal `==`
greater than or equal `>=`
greater than `>`
less than `<`
less than or equal `<=`
logical AND `&&`
left curly brace `{`
signed shift right `>>`

and the following keywords:

`while` in do while loop,
`assert`
`catch`
`do`
`else`
`finally`
`for`
`return`
`synchronized`
`try`

### CODE REVIEW

**Comment by JosephineKwa** [comment]
Is it ok if I branched off this branch to work on part 1 of Whitespace around operators

**Comment by wkurniawan07** [comment]
@JosephineKwa should be fine. There's a merge conflict right now, btw.

**Comment by JosephineKwa** [comment]
Ready for review!

**Comment by wkurniawan07** [comment]
Good to go! :+1:

**Pull request merged**
