### PR TITLE
Refactor FeebackResponsesLogic.java #6403

### PR DESCRIPTION
**Pull request by ablyx**
Refactor long method names for FeedbackResponsesLogic #6403

### CODE REVIEW

**Comment by ablyx** [comment]
@chowyb actually, can I just change the title and comment to reference a new issue?

**Comment by chowyb** [comment]
@ablyx those are possible, but my main concern would be the branch name, which still indicates `5780`. This contravenes the naming conventions that we use.

**Comment by ablyx** [comment]
@chowyb oh sorry, didn't notice that. I will create a new pull request then!

**Comment by chowyb** [comment]
@ablyx due to the presence of #6412, I will be closing this PR.

**Pull request closed without merging**
