### PR TITLE
Migrate all JS used by admin pages to strict mode #6649

### LINKED ISSUE #6649: Migrate all JS used by admin pages to strict mode
As part of the drive to move all JS to strict mode in preparation for ES6 migration (#3361), the JS used by all the admin pages (all the admin*.js) should be migrated to strict mode.

### PR DESCRIPTION
**Pull request by thenaesh**
Fixes #6649

### CODE REVIEW

**Comment by thenaesh** [comment]
Closing this first since I think the changes for the entire strict-mode migration may be smaller than I thought they would be (I expected a ton of problems to show up, but apparently not).

**Comment by thenaesh** [comment]
Reopening this since the migration turned out to be highly non-trivial. This isn't ready for review yet; I haven't checked all the code paths properly.

**Comment by thenaesh** [comment]
To assist reviewers once this is ready, here's the output of running JSHint on all the JS files for the admin pages (command: `for FILE in $(ls | grep ^admin); do jshint --show-non-errors $FILE; done`):

```
adminAccountManagement.js: line 1, col 1, Use the function form of "use strict".
adminAccountManagement.js: line 156, col 27, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminAccountManagement.js: line 157, col 27, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminAccountManagement.js: line 12, col 3, 'document' is not defined.
adminAccountManagement.js: line 118, col 3, 'document' is not defined.
adminAccountManagement.js: line 122, col 3, 'document' is not defined.
adminAccountManagement.js: line 129, col 3, 'document' is not defined.
adminAccountManagement.js: line 153, col 31, 'document' is not defined.
adminAccountManagement.js: line 168, col 3, 'document' is not defined.
adminAccountManagement.js: line 13, col 5, 'toggleSort' is not defined.
adminAccountManagement.js: line 20, col 5, 'AdminCommon' is not defined.
adminAccountManagement.js: line 160, col 13, 'window' is not defined.
adminAccountManagement.js: line 163, col 9, 'BootboxWrapper' is not defined.
adminAccountManagement.js: line 164, col 17, 'BootboxWrapper' is not defined.
adminAccountManagement.js: line 164, col 49, 'BootboxWrapper' is not defined.
adminAccountManagement.js: line 164, col 85, 'StatusType' is not defined.

16 errors

adminAccountManagement.js :
	Implied globals:
		document: 12,118,122,129,153,168
		toggleSort: 13
		AdminCommon: 20
		window: 160
		BootboxWrapper: 163,164,164
		StatusType: 164


adminActivityLog.js: line 1, col 1, Use the function form of "use strict".
adminActivityLog.js: line 24, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminActivityLog.js: line 25, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminActivityLog.js: line 3, col 3, 'document' is not defined.
adminActivityLog.js: line 5, col 5, 'AdminCommon' is not defined.
adminActivityLog.js: line 42, col 13, 'setTimeout' is not defined.
adminActivityLog.js: line 74, col 13, 'setTimeout' is not defined.
adminActivityLog.js: line 49, col 17, 'setStatusMessage' is not defined.
adminActivityLog.js: line 88, col 17, 'setStatusMessage' is not defined.
adminActivityLog.js: line 49, col 54, 'StatusType' is not defined.
adminActivityLog.js: line 88, col 54, 'StatusType' is not defined.
adminActivityLog.js: line 70, col 33, 'olderButton' is not defined.

12 errors

adminActivityLog.js :
	Implied globals:
		document: 3
		AdminCommon: 5
		setTimeout: 42,74
		setStatusMessage: 49,88
		StatusType: 49,88
		olderButton: 70
	Unused Variables:
		toggleReference(8), submitLocalTimeAjaxRequest(22), submitFormAjax(55), 

adminEmail.js: line 1, col 1, Use the function form of "use strict".
adminEmail.js: line 199, col 54, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminEmail.js: line 8, col 3, 'document' is not defined.
adminEmail.js: line 13, col 5, 'richTextEditorBuilder' is not defined.
adminEmail.js: line 49, col 5, 'toggleSort' is not defined.
adminEmail.js: line 64, col 13, 'setTimeout' is not defined.
adminEmail.js: line 98, col 13, 'setTimeout' is not defined.
adminEmail.js: line 128, col 13, 'setTimeout' is not defined.
adminEmail.js: line 164, col 13, 'setTimeout' is not defined.
adminEmail.js: line 69, col 21, 'setStatusMessage' is not defined.
adminEmail.js: line 102, col 21, 'setStatusMessage' is not defined.
adminEmail.js: line 133, col 21, 'setStatusMessage' is not defined.
adminEmail.js: line 170, col 21, 'setStatusMessage' is not defined.
adminEmail.js: line 183, col 5, 'setStatusMessage' is not defined.
adminEmail.js: line 187, col 5, 'setStatusMessage' is not defined.
adminEmail.js: line 78, col 24, 'FormData' is not defined.
adminEmail.js: line 144, col 24, 'FormData' is not defined.
adminEmail.js: line 102, col 55, 'StatusType' is not defined.
adminEmail.js: line 170, col 55, 'StatusType' is not defined.
adminEmail.js: line 183, col 31, 'StatusType' is not defined.
adminEmail.js: line 187, col 87, 'StatusType' is not defined.
adminEmail.js: line 168, col 21, 'url' is not defined.
adminEmail.js: line 169, col 38, 'url' is not defined.

23 errors

adminEmail.js :
	Implied globals:
		document: 8
		richTextEditorBuilder: 13
		toggleSort: 49
		setTimeout: 64,98,128,164
		setStatusMessage: 69,102,133,170,183,187
		FormData: 78,144
		StatusType: 102,170,183,187
		url: 168,169


adminEmailLog.js: line 1, col 1, Use the function form of "use strict".
adminEmailLog.js: line 6, col 3, 'document' is not defined.
adminEmailLog.js: line 68, col 13, 'setTimeout' is not defined.
adminEmailLog.js: line 82, col 17, 'setStatusMessage' is not defined.
adminEmailLog.js: line 82, col 54, 'StatusType' is not defined.

5 errors

adminEmailLog.js :
	Implied globals:
		document: 6
		setTimeout: 68
		setStatusMessage: 82
		StatusType: 82
	Unused Variables:
		toggleReference(12), submitFormAjax(50), 

adminHome.js: line 1, col 1, Use the function form of "use strict".
adminHome.js: line 81, col 46, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminHome.js: line 100, col 46, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminHome.js: line 149, col 29, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminHome.js: line 17, col 27, 'encodeHtmlString' is not defined.
adminHome.js: line 18, col 24, 'encodeHtmlString' is not defined.
adminHome.js: line 19, col 24, 'encodeHtmlString' is not defined.
adminHome.js: line 20, col 24, 'encodeHtmlString' is not defined.

8 errors

adminHome.js :
	Implied globals:
		encodeHtmlString: 17,18,19,20
	Unused Variables:
		addInstructorFromFirstFormByAjax(118), addInstructorFromSecondFormByAjax(144), 

adminSearch.js: line 1, col 1, Use the function form of "use strict".
adminSearch.js: line 66, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminSearch.js: line 67, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminSearch.js: line 3, col 3, 'document' is not defined.
adminSearch.js: line 7, col 5, 'highlightSearchResult' is not defined.
adminSearch.js: line 84, col 13, 'setTimeout' is not defined.
adminSearch.js: line 94, col 17, 'setStatusMessage' is not defined.
adminSearch.js: line 94, col 54, 'StatusType' is not defined.

8 errors

adminSearch.js :
	Implied globals:
		document: 3
		highlightSearchResult: 7
		setTimeout: 84
		setStatusMessage: 94
		StatusType: 94
	Unused Variables:
		submitResetGoogleIdAjaxRequest(64), adminSearchDiscloseAllStudents(100), adminSearchCollapseAllStudents(105), adminSearchDiscloseAllInstructors(110), adminSearchCollapseAllInstructors(115), 

adminSessions.js: line 1, col 1, Use the function form of "use strict".
adminSessions.js: line 3, col 3, 'document' is not defined.
adminSessions.js: line 5, col 5, 'AdminCommon' is not defined.

3 errors

adminSessions.js :
	Implied globals:
		document: 3
		AdminCommon: 5
	Unused Variables:
		openAllSections(26), closeAllSections(37), toggleFilter(48), 

administrator.js: line 1, col 1, Use the function form of "use strict".
administrator.js: line 16, col 11, 'window' is not defined.
administrator.js: line 24, col 11, 'document' is not defined.

3 errors

administrator.js :
	Implied globals:
		window: 16
		document: 24
	Unused Variables:
		AdminCommon(6), 

```

This is what I'm using to hunt down all the evil stuff.

**Comment by wkurniawan07** [comment]
@thenaesh it looks like your JSHint needs to be configured to accept browser global vars such as `setTimeout`, `window`, `document`.
Other than that, if you want ESLint to unleash the same power, go to our config file and set the `no-undef` rule to `error`. There's a reason I turned it off despite being recommended by everybody. 🌚

**Comment by thenaesh** [comment]
@wkurniawan07 I'll update that later on before I call for a review. xD

**Comment by thenaesh** [comment]
Update: I fixed a few problems with undeclared variables and now JSHint gives a nearly clean bill of health. There are a few other issues remaining (the misleading line break before '+' nonsense and the unused variables that are not actually unused), but I think they don't have anything to do with strict mode.

Here's the JSHint output:
```
adminAccountManagement.js: line 1, col 1, Use the function form of "use strict".
adminAccountManagement.js: line 156, col 27, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminAccountManagement.js: line 157, col 27, Misleading line break before '+'; readers may interpret this as an expression boundary.

3 errors

adminActivityLog.js: line 1, col 1, Use the function form of "use strict".
adminActivityLog.js: line 24, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminActivityLog.js: line 25, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.

3 errors

adminActivityLog.js :
	Unused Variables:
		toggleReference(8), submitLocalTimeAjaxRequest(22), submitFormAjax(55), 

adminEmail.js: line 1, col 1, Use the function form of "use strict".
adminEmail.js: line 199, col 54, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminEmail.js: line 78, col 24, 'FormData' is not defined.
adminEmail.js: line 144, col 24, 'FormData' is not defined.

4 errors

adminEmail.js :
	Implied globals:
		FormData: 78,144


adminEmailLog.js: line 1, col 1, Use the function form of "use strict".

1 error

adminEmailLog.js :
	Unused Variables:
		toggleReference(12), submitFormAjax(50), 

adminHome.js: line 1, col 1, Use the function form of "use strict".
adminHome.js: line 81, col 46, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminHome.js: line 100, col 46, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminHome.js: line 149, col 29, Misleading line break before '+'; readers may interpret this as an expression boundary.

4 errors

adminHome.js :
	Unused Variables:
		addInstructorFromFirstFormByAjax(118), addInstructorFromSecondFormByAjax(144), 

adminSearch.js: line 1, col 1, Use the function form of "use strict".
adminSearch.js: line 66, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.
adminSearch.js: line 67, col 18, Misleading line break before '+'; readers may interpret this as an expression boundary.

3 errors

adminSearch.js :
	Unused Variables:
		submitResetGoogleIdAjaxRequest(64), adminSearchDiscloseAllStudents(100), adminSearchCollapseAllStudents(105), adminSearchDiscloseAllInstructors(110), adminSearchCollapseAllInstructors(115), 

adminSessions.js: line 1, col 1, Use the function form of "use strict".

1 error

adminSessions.js :
	Unused Variables:
		openAllSections(26), closeAllSections(37), toggleFilter(48), 

administrator.js: line 1, col 1, Use the function form of "use strict".

1 error

administrator.js :
	Unused Variables:
		AdminCommon(6), 

```

I ignored the obvious globals and all the stuff in common.js (that's a battle for another day xD):
```
{
    "jquery": true,
    "globals": {
        "document": true,
        "window": true,
        "richTextEditorBuilder": true,
        "AdminCommon": true,
        "setStatusMessage": true,
        "StatusType": true,
        "toggleSort": true,
        "BootboxWrapper": true,
        "setTimeout": true,
        "encodeHtmlString": true,
        "highlightSearchResult": true
    }
}
```

There is one undeclared variable remaining, whose origins are uncertain. There is this variable called `FormData`, seen in the for `new FormData` in lines 78 and 144 of adminEmail.js. They seem to be from the library ajv, but I don't see any `require('ajv')` anywhere in the entire project.

Apart from that, this is ready for review. @li-kai @wkurniawan07

**Comment by junhaoyap** [comment]
There's a good reason for the error:

Use the function form of "use strict".

Read -

https://yuiblog.com/blog/2010/12/14/strict-mode-is-coming-to-town/

We could get it wrong just like anyone else and that is the reason why it is less non-trivial than we think, if we want to wrap our files in a function before using strict - some files were never written to be wrapped that way

**Comment by thenaesh** [comment]
@junhaoyap According to the article, the function form is preferred so that there won't be issues when concatenating a non-strict file with a strict file. But at this time there is no concatenation since all the files are served separately.

Of course, at some point in the very near future, we will want to start bundling up the JS files before serving them. But I don't think we will start doing that until we have everything in ES6 (at which point this whole issue is moot).

At the end of the day, the I think main reason why we're ensuring strictness is to keep Babel happy when we introduce a transpile step on the existing JS code.

**Comment by thenaesh** [comment]
@junhaoyap If you're free, do have a look. I know it's exam season now, so no pressure though. :)

**Comment by junhaoyap** [comment]
@li-kai @thenaesh great! Thanks for the explanation and plans on moving forward that will not cause us to have problems with the concatenation issue, otherwise I'm good with the changes and going to approve

**Pull request merged**
