### PR TITLE
Experimental upgrade to Java 8 #7609

### LINKED ISSUE #7609: Upgrade to Java 8
Recent versions of AppEngine SDK are fully compatible with JDK 8, as long as the compiler compliance level is set to Java 7.

**Reasons for Upgrading**

- First step in upgrading to Java 8 (second step is still dependent on Google though)
- Enables use of latest Travis images (can revert #7548)
- Enables use of Checkstyle 7
- Enables use of SonarQube

**Caveats**

- The iteration order of HashMaps and HashSets is affected ([link](https://docs.oracle.com/javase/8/docs/technotes/guides/collections/changes8.html)):
  > In rare situations, this change could introduce a change to the iteration order of HashMap and HashSet. A particular iteration order is not specified for HashMap objects - any code that depends on iteration order should be fixed.
  - Unfortunately, some of our tests do depend on a particular iteration order
    - These tests need to be updated - the dependence on iteration order must be removed
    - This is required to allow testing on both the dev server (running on Java 8) and the staging server (running on Java 7)
- Still requires a valid JRE 7 installation as the Java 7 libraries are needed for proper cross-compilation to Java 7-compatible bytecode required for the GAE runtime in deployed instances
- ~~Dependent on #7608 to be merged first, as older versions of AppEngine SDK won't work~~ Edit: merged

### PR DESCRIPTION
**Pull request by wkurniawan07**
**Outline of Solution**

Migrated entirely to Java 8 runtime, not just JDK 8 with Java 7 compliance.

What this PR is **NOT** about: Asking everyone to **immediately** migrate to Java 8. This branch will stay on the sidelines for as long as needed, until at least the Java 8 support in GAE is GA. All other Java 8 improvements (CheckStyle 7, Selenium 3) will follow suit here first, and when everything is ready, it will go back to `master` via rebase-and-merge style. This way, everyone will have access to a branch with a guaranteed Java 8 dev green, ready to be tested in staging server if necessary.

There will be no syntactic migration (lambdas, functional interfaces) in this PR either; they can be left for later on.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
I can give a CI-green and can-deploy guarantee now, but I can also guarantee any page visited after deployment will be a 500. Likely related to #7648, so I'll side track there for the next few days.

**Comment by wkurniawan07** [comment]
As it turns out, it has nothing to do with the older method of deployment. I'm adding a "things-seem-to-work-fine-on-staging" guarantee now.

**Comment by wkurniawan07** [comment]
@whipermr5 this is as far as I can do for now

**Comment by whipermr5** [comment]
From the way they phrased it, I'm not sure `Appstats` will ever be coming back. I guess we can always use the custom headers added by GAE to estimate costs: https://cloud.google.com/appengine/docs/standard/java/how-requests-are-handled#headers_added_or_replaced

**Comment by wkurniawan07** [comment]
@whipermr5 thanks for adding a staging green guarantee 😆

**Comment by damithc** [comment]
Are we going to merge this now? What's the impact?

**Comment by whipermr5** [comment]
@damithc Just into the long-lived `teammatesv6` branch, I think.

**Comment by wkurniawan07** [comment]
As I mentioned in the PR description: "stay on the sidelines for as long as needed, until at least the Java 8 support in GAE is GA". Everyone can very well pretend that nothing has happened.

**Pull request merged**
