### PR TITLE
[#9781] Upgraded footer to include sponsor information

### PR DESCRIPTION
**Pull request by rrtheonlyone**
Part of #9781

Updates sponsor information for v6

Before Login:
Screenshot 2019-06-20 at 5 22 42 PM

After Login:
Screenshot 2019-06-20 at 5 22 34 PM

Contact us Page:
Screenshot 2019-06-20 at 5 22 55 PM

### CODE REVIEW

**Comment by rrtheonlyone** [comment]
@damithc prof is the presentation okay? 

I will then proceed to run Godmode and fix the tests.

**Comment by damithc** [comment]
Thanks for taking this up @rrtheonlyone 

For the 'after login' case, perhaps like this, if not too much work?
```
                                             serving: ABC school
              TEAMMATES (v6.x.x) is sponsored by ... [Become a sponsor][send feedback]
```

I think we can remove `Hosted on Google App Engine` entirely.

**Comment by rrtheonlyone** [comment]
Sure no worries Prof. So just to clarify:

1. Remove `Hosted on Google App Engine` from all the footers

2. Improved Footer for `after login`:
Screenshot 2019-06-21 at 4 31 58 PM

**Comment by damithc** [comment]
Looks good @rrtheonlyone 👍

**Comment by damithc** [comment]
@rrtheonlyone how's this coming along?

**Comment by rrtheonlyone** [comment]
@damithc Apologies for the delay. I will settle this latest by end of the week! 

I am having a little bit of difficulty getting the CI to pass (mainly because the tests take over an hour to run on my computer).

**Comment by damithc** [comment]
Sure @rrtheonlyone 

> I am having a little bit of difficulty getting the CI to pass (mainly because the tests take over an hour to run on my computer).

Try with just one or two tests locally. Once they are passing, let Travis run the other tests.

**Comment by damithc** [comment]
@rrtheonlyone reminder

**Comment by rrtheonlyone** [comment]
Apologies for the delay @damithc 

I have fixed the tests and the PR is ready for review.

**Comment by damithc** [comment]
Thanks @rrtheonlyone

**Pull request merged**
