### PR TITLE
Images used in the project are not optimized #6552

### LINKED ISSUE #6552: Images used in the project are not optimized
All the images in [this page](https://teammatesv4.appspot.com/about.jsp) are not optimized, resulting in the user downloading nearly 3.5mb of images when visiting the page.

### PR DESCRIPTION
**Pull request by li-kai**
Fixes #6552. Original images are stored in `./original` folder. Compressed and resized images are now only 3.4mb, resulting in savings of 50% (was 6.8mb).

**Outline of Solution**

I used three image command line tools, [imagemagick](https://www.imagemagick.org/script/index.php), [optipng](http://optipng.sourceforge.net/) and [gifsicle](https://www.lcdf.org/gifsicle/) with the following commands.
```bash
mogrify -path optimized/ -resize 300 *.png
optipng *.png -o7 -quiet -strip all -dir optimized
gifsicle -O3 [filename].gif -o [filename].gif
```

Reason for 300px width: With #6488, 300px is the maximum size of the largest image, unless bootstrap updates version 3's max-width.

### CODE REVIEW

**Comment by boxin-yang** [comment]
Wow this is nice, and the resizing is legit as I look through the pix and realize they are of diff size. LGTM

**Comment by wkurniawan07** [comment]
@damithc I believe we do not need the original images?

**Comment by damithc** [comment]
> @damithc I believe we do not need the original images?

Yes, no need.

**Comment by damithc** [comment]
> @damithc I believe we do not need the original images?

Yes, no need.

**Comment by wkurniawan07** [comment]
@li-kai you can remove all the original uncompressed images

**Comment by li-kai** [comment]
@damithc @wkurniawan07 Removed the original as requested.

**Comment by li-kai** [comment]
> It looks like you accidentally removed teammateslogo.jpg, everything else is good.

Oh yep. Since it's a jpg file it wasn't compressed. It's fixed now.

**Comment by wkurniawan07** [comment]
@li-kai actually can you convert it to (optimized) png as well?

**Comment by li-kai** [comment]
> @li-kai actually can you convert it to (optimized) png as well?

That would involve changing links, tests, and causing more conflict with PRs like #6487.

**Comment by wkurniawan07** [comment]
@li-kai noted on that 👍

**Pull request merged**
