### PR TITLE
Refactor FeedbackSessionsLogic.java #5780

### PR DESCRIPTION
**Pull request by ablyx**
Made a few refactorings for #5780

### CODE REVIEW

**Comment by chowyb** [comment]
Leave a comment when ready for review

**Comment by ablyx** [comment]
Ready for review

**Comment by chowyb** [comment]
As a note, when I first opened this issue, it was intended to refactor the 4 files with that naming scheme, namely `FeedbackQuestionsLogic.java`, `FeedbackResponseCommentsLogic.java`, `FeedbackResponsesLogic.java`, and `FeedbackSessionsLogic.java`. As such, I would like to know if you intend on refactoring the other files in this PR as well.

Alternatively, you may instead open separate issues for each file and work on them one PR at a time.

In addition, I believe that more segments of the code in `FeedbackSessionsLogic.java` can be refactored, as some methods are presently far too long to be readable (eg. `getFeedbackSessionResultsForUserWithParams` is still a giant method with about 250 lines even after the current refactoring). It is fine to extract out a method that is only used by one other method if it helps to make the code more readable.

As such, I would like to know what your plans are regarding this issue (eg. are you planning to continue working on this/the other files, and how comprehensive you intend the refactorings to be).

**Comment by ablyx** [comment]
I will try to see if I can continue to refactor `getFeedbackSessionResultsForUserWithParams` but I think I'll choose to continue to work on these files on another PR.

I am not too sure how comprehensive I can be, it's still a lot for me to understand at this stage. 

In the future, should I submit a bunch of refactorings in 1 PR or should I separate them?

**Comment by chowyb** [comment]
@ablyx it depends on the size of the changes, if the total changes combined add up to more than 500 lines, it might be better to split them into several PRs (and several corresponding issues, to be in line with our workflow).

And yep no problems, it's a bit hard to just dive in to these files right at the beginning, although I believe your understanding of the system should increase significantly after trying out this issue 😄

**Comment by ablyx** [comment]
@chowyb actually, what were the major refactorings that you would like to do for these files?

**Comment by chowyb** [comment]
@ablyx Some of the stuff I had in mind can be found in my older PR for this issue (#5790), but the main goal was to make the code more readable where possible, so the guiding principles I had in mind are as follows:

1. Split large methods into several smaller methods to make the individual steps easier to understand.
2. If a particular logic is used across several methods (or used more than once in the same method), extract it into a single reusable method.
3. Add comments or rename methods where necessary to help better understand what each method is doing.

**Comment by chowyb** [comment]
@ablyx given the new PR (#6393) you have made for the same issue, I will be approving the changes for this PR.

However, please note that in general, one issue should be fixed by one PR. In this case, it should be possible to create additional issues in the issue tracker (eg. "Refactor FeedbackQuestionsLogic.Java") and create a separate PR for each of them, as such #6393 will need to be changed (or even closed, seeing as the issue number of the new issue will be different from the current one).

**Comment by ablyx** [comment]
@chowyb sorry about that. I'll make a new issue and submit a new PR for that. You can close #6393.

**Comment by wkurniawan07** [comment]
@chowyb, I'll leave you to merge this one since I'm not sure how you want to approach the possibly long-lived issue.

**Comment by chowyb** [comment]
@wkurniawan07 understood. My current plan is to split the issue into several smaller ones, one for each file involved (4 total), in which case it might be possible to retroactively change the issue name/description of #5780 (assuming this is allowable), and then create additional issues for the other files (such as #6403)

**Pull request merged**
