### PR TITLE
Instructor: download results: include only the selected section #7164

### LINKED ISSUE #7164: Instructor: download results: include only the selected section
Current:
An instructor can choose to show results of a specific section.
section
However, when the instructor downloads the results using the `Download Results` button, all responses of that session are in the downloaded csv file.

Suggestions:
Only responses for the selected section should be in the downloaded csv file.

Justification: 
This allows downloading responses one section at a time, which is useful when the course is big.

Other notes: This was supposed to be implemented long time ago ( #5628 ) but somehow doesn't seem to be working now.

### PR DESCRIPTION
**Pull request by LimeTheCoder**
Fixes #7164 

After an investigation was found a cause of the bug. Download for specified section action worked incorrectly because to the list of possible givers which haven't provided yet their responses were added givers from all section regardless selected one.

Before:
image
After:
image

### CODE REVIEW

**Comment by LimeTheCoder** [comment]
Need review here.

**Comment by chowyb** [comment]
@LimeTheCoder Behaviour seems okay from my point of view, but I believe some discussion may be required regarding the behaviour of the download, as compared to the behaviour of the web page itself. I noticed that no tests covering the case of downloading by section has been done yet, therefore I believe you plan to add the tests later after a review.

@damithc the changes suggested in this PR looks fine, however it seems to be different from the behaviour of the results page itself. As a summary:

CSV file: shows all responses where the giver is from the selected section
Results page: shows all responses where both the giver and the recipient are from the selected section (and is therefore a subset of responses found in the CSV file)

As such, I'd like to ask which of the display options would be more preferable, so that we can standardise the results shown (perhaps in a separate PR if the display of results in the results page has to be changed).

**Comment by chowyb** [comment]
@damithc when only a specific section is selected, these responses are not displayed.

**Comment by damithc** [comment]
> @damithc when only a specific section is selected, these responses are not displayed.

Probably we'll have to provide separate options for 'giver in section' 'recipient in section' and 'both in section', in a future version. The default can be 'both in section' which is how the results page works now and csv can follow the same? What do you guys think?

**Comment by LimeTheCoder** [comment]
Hi, guys. It seems that results page shows not only responses where giver and recipient within the selected section. Here 3 cases when a response will be displayed:
1) Already mentioned the case where both giver and recipient in the selected section.
2) Where giver in selected section and recipient section is 'None'
3) Where giver section is 'None' and recipient section is selected one.
So should we follow that behaviour or display only responses from the first case?

Method that retrieves responses: teammates.storage.api.FeedbackResponsesDb#getFeedbackResponseEntitiesForQuestionInSection

**Comment by damithc** [comment]
> @damithc. @chowyb So should we follow current behavior or display only responses from the first case?

I'm for following current behavior. @chowyb ?

**Comment by chowyb** [comment]
I'm for following current behaviour as well. If there are any changes that need to be made, we can do it in a future PR.

Setting to `s.ToMerge` as there are no other issues.

**Pull request merged**
