### PR TITLE
[#10427] Fix formatting for answer constraints

### LINKED ISSUE #10427: Submit responses: Show MSQ restrictions more prominently
Current:
image

V6:
image

V6 is slightly better in terms of layout. 
Suggestion: Also use different colors to draw attention to the restrictions.

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #10427 

### rank-recipient
image

### rank-options
image

### msq
image

### constsum-options
image

### constsum-recipients
image

### CODE REVIEW

**Comment by damithc** [comment]
MSQ can follow the same phrasing as others.

**Comment by ccyccyccy** [comment]
> MSQ can follow the same phrasing as others.

Screenshots updated.

**Comment by damithc** [comment]
> Screenshots updated.

Looks good. nit: give lower bound first, to be consistent with other places.

**Comment by damithc** [comment]
Also, the last two screenshots seem to use slightly different text color than the rest. Not sure if it is a real difference or something to do with how the screenshots were taken.

**Comment by ccyccyccy** [comment]
> Also, the last two screenshots seem to use slightly different text color than the rest. Not sure if it is a real difference or something to do with how the screenshots were taken.

It's just a screenshot difference. I think I was using different browsers. Screenshots updated to fix that and the ordering issue.

**Pull request merged**
