### PR TITLE
[#12292] Admin logs page: Fix display of logs table on mobile

### LINKED ISSUE #12292: Admin logs page: Fix display of logs table on mobile
Currently, the logs table fits within the window regardless of width, causing the table contents to be unreadable at small screen sizes:
photo_2023-03-28 14 00 50

One possible fix is to make the table scroll horizontally at smaller screen sizes.

### PR DESCRIPTION
**Pull request by yash29896**
Fixes #12292 

**Outline of Solution**
Added overflow-x: scroll below a minimum width.
Added a logs-table-container class to remove right padding and margin which were causing the table to overflow even when it was above minimum width.

### CODE REVIEW

**Comment by yash29896** [comment]
It seems like the existing snapshot is not updated, leading to failure in the UTs. How can I update the existing snapshot ?

**Comment by cedricongjh** [comment]
> It seems like the existing snapshot is not updated, leading to failure in the UTs. How can I update the existing snapshot ?

Hi @yash29896, to update the snapshots run `npm run test` and pressing `a` to run all test cases. After that, check through the snapshots to make sure the changes are as expected, then press `uto update them. You can find more details on snapshot testing [here](https://teammates.github.io/teammates/snapshot-testing.html).

Do try it out and let us know if there's any issues you ran into!

**Comment by yash29896** [comment]
@cedricongjh Thanks for the quick reply. I updated the snapshot.

However unrelated e2e-tests seem to be failing.

`176:        homePage.resendResultsLink(courseIndex, sessionIndex, studentToEmail);`

**Comment by jasonqiu212** [comment]
@yash29896 Thanks for fixing the snapshot tests! The TEAMMATES E2E test workflow occasionally need reruns. Maintainers will help to monitor the tests and rerun them if necessary. Currently, the E2E tests are passing.

**Review by cedricongjh — APPROVED** [review]
LGTM, thank you for your contribution to TEAMMATES!

**Pull request merged**
