### PR TITLE
Duplicate bold class in teammates.css #5060

### LINKED ISSUE #5060: Duplicate bold class in teammates.css
Two instances of the .bold class have been defined in teammates.css as shown in the two screenshots below:

bold1

bold2

While this presently does not seem to cause any issues, it would probably be better to only have one such declaration for the class.

### PR DESCRIPTION
**Pull request by pandilladivya**
Fixes #5060

### CODE REVIEW

**Comment by pandilladivya** [comment]
@damithc 

Kindly review this PR
Thank You :)

**Comment by thyageshm** [comment]
@JosephineKwa ready for review

**Comment by JosephineKwa** [comment]
Good to merge!

**Comment by JosephineKwa** [comment]
@pandilladivya , do edit the PR name to also include the issue number :) The PR name should contain the entire issue name.

**Comment by damithc** [comment]
I think branch name can have a few more keywords too. Perhaps we can redo this PR with a better branch name?

**Comment by pandilladivya** [comment]
Thanks for the review :)
I have changed the PR name!

**Pull request merged**
