### PR TITLE
Refactor InstructorFeedbackResultsDownloadActionTest #6924 

### LINKED ISSUE #6924: InstructorFeedbackResultsDownloadActionTest have unnecessary duplications
There seems to have unnecessary duplication among the `verifyFileContent` methods that can be refactored to make it clearer.

### PR DESCRIPTION
**Pull request by ZhaoDingfan**
Fixes #6924 

**Outline of Solution**
Add several methods to return the common components of the expected String array.
Replace the components with respective String methods.

### CODE REVIEW

**Comment by ZhaoDingfan** [comment]
Basically my TRAVIS-CI check fails due to two kinds of reasons. The first is unnamed function in es6 files. The second is due to checkstyle. I don't know how to deal with those mistakes but is it because I edited the file in Atom rather than Eclipse for the second?

**Comment by xpdavid** [comment]
@ZhaoDingfan You don't need to care ES6 things as they don't trigger the build error.
It is the CheckStyle thing:
```
/home/travis/build/TEAMMATES/teammates/src/test/java/teammates/test/cases/action/InstructorFeedbackResultsDownloadActionTest.java:224:29: '(' is preceded with whitespace. [MethodParamPad]
```

**Comment by ZhaoDingfan** [comment]
Actually I manually correct some errors of CheckStyle, but there are some weird errors like 
`ci-tests > parallel-ui-tests > teammates.test.cases.browsertests.InstructorFeedbackPageUiTest.testCopyActions PASSED`
I don't know how to fix them.

**Comment by boxin-yang** [comment]
Hi, @ZhaoDingfan , for the error on **teammates.test.cases.browsertests.AdminHomePageUiTest.testAll FAILED** , I highly believe it is caused by the code legacy to use 2nd April 2017 as the testing date. That date has passed and is causing some errors. However, the problem is fixed in this [commit](https://github.com/TEAMMATES/teammates/commit/52c2669aa4056794014ec14756aa092210e43e14) . What I suggest you to do is to sync your branch with the remote master branch and the instructions for that is found [here](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) . 

As for the nullPointerException, I think it is something in your new code that is causing the problem. Please trace the code to find the error and fix it. Also, please setup testing environment on your machine and only push code when your local tests run successfully. You do not need to push for every commit.

**Comment by wkurniawan07** [comment]
@ZhaoDingfan I apologize, but this PR needs to be closed since the issue at hand was not well-defined to begin with.

**Pull request closed without merging**
