### PR TITLE
Rename appPage0.html to appVerifyTablePatternTestPage.html #3870

### LINKED ISSUE #3870: Rename appPage0.html to appVerifyTablePatternTestPage.html
From a quick dig through, it seems that it is not used anywhere. @kanghj can confirm? Any ideas where this could be used?

### PR DESCRIPTION
**Pull request by allevy3**
Fixes #3870

### CODE REVIEW

**Comment by allevy3** [comment]
Could anyone shed some insight on how I can manually run the test via Eclipse to debug the error? As far as I can tell the change I made was as directed.

"Failed suite [travis-tests] > parallel-ui-tests(failed) > teammates.test.cases.ui.browsertests.AppPageUiTest.testVerifyTablePattern FAILED
    java.lang.IndexOutOfBoundsException at AppPageUiTest.java:27"

**Comment by chowyb** [comment]
@allevy3 it should be possible to right click on the file from the Project Explorer on the left containing that particular test and select Run as > TestNG Test. In the general case where you want to run all tests instead, it is covered in the [documentation](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#running-the-test-suite-with-eclipse).

**Comment by allevy3** [comment]
I am confused how there is a conflict now with AppVeyor. I found out what the issue was and its resolved after my latest two commits.  I tested it and the test ran successfully.

**Comment by chowyb** [comment]
@allevy3 you will need to update your branch by merging the committer repository's `master` branch into your branch, and resolving any merge conflicts.

**Comment by allevy3** [comment]
@chowyb Thank you so much for the help. GIT actually makes sense to me now. Ended up doing the merge via git bash. Was trying to use tortoise SVN because I already had it installed but was not having any luck.

**Comment by wkurniawan07** [comment]
@allevy3 for your next contributions, please work on a separate branch for any fix instead of `master`.

Also, Tortoise SVN should not work for this project because we are using Git instead of Subversion, and they are not made to be substitutable with each other. If you have Tortoise Git by any chance, you can give it a shot.

**Comment by allevy3** [comment]
@wkurniawan07 so do I make my own branch or pick an existing branch?

**Comment by wkurniawan07** [comment]
@allevy3 you should make a new branch in your own fork.

**Pull request merged**
