### PR TITLE
Remove unnecessary classes in common.datatransfer package #6640

### LINKED ISSUE #6640: Remove unnecessary classes in common.datatransfer package
- `FeedbackQuestionBundle`: not used at all.
- `SessionResultsBundle`: an empty interface with only one implementing class. Removing it has no side effect.
- `FeedbackSessionState`: only used in `AdminSearchPageData`; can be moved there as a private enum instead.

### PR DESCRIPTION
**Pull request by miguelarauj1o**
See:

* Remove **FeedbackQuestionBundle** class
* Remove **SessionResultsBundle** interface
* Move **FeedbackSessionState** class to **AdminSearchPageData** as private enum instead.

Fixes #6640

### CODE REVIEW

**Comment by samsontmr** [comment]
@miguelarauj1o You can click on the red 'x' to find out why your build is failing.

**Comment by miguelarauj1o** [comment]
I'll fix that ASAP.

**Comment by junhaoyap** [comment]
@miguelarauj1o great move on starting on your firstTimer issue, please fix the failure so that we can continue with the progress of the PR, remains as ongoing until then!

**Comment by miguelarauj1o** [comment]
Hello, I've been very busy the last few days. I tried setting the environment to run the tests yesterday, but I did not succeed. When I get home from work, I will do my best to finish this PR.

**Comment by wkurniawan07** [comment]
Hi @miguelarauj1o, any updates for this PR?

**Comment by miguelarauj1o** [comment]
Hey @samsontmr, I would to apologize for the delay in fixing this PR.
Follow new changes.

I referencing #6751 because is about the same problem.

**CC** @junhaoyap @wkurniawan07

**Comment by miguelarauj1o** [comment]
Failed because:

```
:checkstyleMain[ant:checkstyle] [ERROR] 
/home/travis/build/TEAMMATES/teammates/src/main/java/teammates/ui/controller/AdminSearchPageAction.java:24:9: Missing a Javadoc comment. [JavadocVariable]
```

**Comment by wkurniawan07** [comment]
@miguelarauj1o you are moving the enum to AdminSearchPage**Action**. It should be to AdminSearchPage**Data**, and should be `private`.

**Comment by miguelarauj1o** [comment]
# SHAME ON ME

**Pull request merged**
