### PR TITLE
[#10862] Student viewing results: Add more info to about the 'Team View'

### LINKED ISSUE #10862: Student viewing results: Add more info to about the 'Team View'
When a student is viewing the results of a 'Team contribution' question, she can click on the (i) icon to find more info about how to interpret the results.
image

Suggestion: Add the following information to the modal that pops up.

>Please note that the ‘Team view’ shown to you has been adjusted to match the total of your own view (i.e., the ‘My view’). In the example below, ‘My view’ adds up to 4E+10% and therefore, the ‘Team view’ has been scaled up to add up to 4E+10% as well (give or take minor differences due to rounding off errors).
>image
>The reason for such an adjustment is to allow you to make a direct comparison between your own view of work distribution against that of the team. In the example above, the ‘Team view’ is quite close to the ‘My view’ which means the respondent has an accurate view of how much each contributed (in other words, the team agrees with the respondent’s view).
Note that the above also means the ‘Team view’ seen by each team member could be different.

### PR DESCRIPTION
**Pull request by ZhangYiping126**
Fixes #10862

### CODE REVIEW

**Comment by damithc** [comment]
Quick comment: You may be able to reproduce the visual using code rather than use an image. We prefer to code to screenshots as the former is easier to maintain/update.

**Comment by ZhangYiping126** [comment]
replaced img with code,
screenshot of the current modal:Screenshot 2020-12-10 at 10 13 46 PM

**Comment by damithc** [comment]
Good progress. I think this should appear as one of the bullet points under 'How do I interpret these results' section?

**Review by madanalogy — APPROVED** [review]
Looks alright to me, thanks for your contribution!

**Review by hcwong — APPROVED** [review]
lgtm!

**Comment by madanalogy** [comment]
@rrtheonlyone @wkurniawan07 @tiuweehan Travis doesn't seem to be triggering for this PR, any idea why?

**Comment by tiuweehan** [comment]
I don't have access to the project settings, but could be because of branch protection settings.

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154/17

**Comment by wkurniawan07** [comment]
Screen Shot 2020-12-19 at 12 32 10 PM

https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191

I haven't encountered this before, so I'm not sure what to do myself.

**Comment by rrtheonlyone** [comment]
I am not too sure either, odd...

@ZhangYiping126 could we trouble you to reopen another PR from a different branch? That should re-trigger the Travis build again

**Comment by ZhangYiping126** [comment]
I've created another PR from a different branch, but Travis build seems not to be activated.  It might be that my Travis account is flagged for potential abuse, I've emailed Travis support and waiting for their reply.

**Comment by madanalogy** [comment]
We're probably gonna have to wait till we migrate to GitHub Actions then, will put this PR on hold till then

**Pull request merged**
