### PR TITLE
 An option should be included to avoid empty responses in results download. #5548 

### LINKED ISSUE #5548: An option should be included to avoid empty responses in the response panel view.
This feature will introduce a new checkbox to session feedback results page as 'Include empty responses'. If it is 'checked', the web panels of feedback responses would not contain the missing responses.  By default this would be checked.  ﻿

snip20160606_5

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #5548

### CODE REVIEW

**Comment by damithc** [comment]
Can post screenshots?

**Comment by rclakmal** [comment]
Attached some screenshot of the panel view.
Both CSV download and panel view get effected on the status of the new checkbox. 

snip20160608_10
snip20160608_9
snip20160608_8
snip20160608_7

There seem to be some style violations. Please avoid reviewing until I make it green :-)

**Comment by damithc** [comment]
Not sure if `empty responses` is the right term here :-p Any other suggestions?
It's also a bit odd to affect csv file because no other setting affects it right? eventually we want the csv file to follow the setting in the page, but we haven't started on that yet.

**Comment by rclakmal** [comment]
@damithc "Missing Responses" ? "Uncompleted Responses" ? :-)

True on the second fact. For now,  should we include a hint below saying "This will also effect the download" ?

**Comment by damithc** [comment]
`Indicate missing responses`?
Which one is extra work? keeping the csv intact or making it follow the setting?

**Comment by rclakmal** [comment]
@damithc Didn't follow what you meant by 'keeping the csv intact'. 

I guess once we update the CSV to follow the other settings (as planned), we should probably introduce a second download button (eg: `Download the filtered data`) and keep the existing download button to retrieve the full data set without any filtering.

**Comment by damithc** [comment]
What I meant was, 'to keep the csv file unaffected by this option'. In general, we prefer to limit a PR to the narrowest scope, which in this case is to change the web page behavior but not change the csv behavior. However, we can consider widening the scope to include an additional feature if sticking to the narrow scope in fact requires a lot more work. In this decision, we should ignore the fact that you've already implemented the extra feature ('already done' is generally not a valid reason).

**Comment by rclakmal** [comment]
@damithc Noted the content. 
For both view and download there are common data structure changes. However, the check to avoid empty responses for CSV and the panel views are in two different locations.

**Comment by rclakmal** [comment]
@damithc The Ajax loading of the table view uses the exact same method (`getFeedbackSessionResultsSummaryInSectionAsCsv`) as the CSV download. So, with the existing implementation, if we include this new option also for the ajax loading of the html table,  it also effects the CSV download. 

What would you advise ?

**Comment by damithc** [comment]
@wkurniawan07 @kanghj what do you think? Ideally, web view should be consistent whether it is using ajax or not. It is ok if the csv follows the same. Some internal changes are required? If so, how to do it in steps?

**Comment by kanghj** [comment]
> The Ajax loading of the table view uses the exact same method (getFeedbackSessionResultsSummaryInSectionAsCsv) as the CSV download.

Just to clarify, this ajax loading here refers to the `Non-English characters not displayed properly in the downloaded file? click here` link, right? This one should follow the csv method entirely, and like the csv download, it ignores the current page setting completely. 

I think a good first step is to work on hiding the 'missing' responses on the web view first, before trying to find a way to make the csv download consistent with the web view.

**Pull request closed without merging**
