### PR TITLE
[#10341] Set panel to expand on load

### LINKED ISSUE #10341: Instructor view all records page: expand all panels by default
Current: inner panels are collapsed

Suggested: all panels should be expanded by default to minimize work for users

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #10341 

- Set default expanded status to true

### CODE REVIEW

**Comment by niqiukun** [comment]
I think the original issue refers to the instructor view session results page instead. See https://github.com/TEAMMATES/teammates/issues/10344. On student list page it still makes more sense for the instructor to locate the course first and expand the list to view the students for that particular course.

**Comment by ccyccyccy** [comment]
> I think the original issue refers to the instructor view session results page instead. See #10344. On student list page it still makes more sense for the instructor to locate the course first and expand the list to view the students for that particular course.

Oh oops will change to that instead..

**Comment by damithc** [comment]
To clarify, the issue refers to the view opened by clicking on the <kbd>view all records</kbd> button.

**Comment by ccyccyccy** [comment]
> To clarify, the issue refers to the view opened by clicking on the view all records button.

Yep got it. This one

image

**Comment by ccyccyccy** [comment]
@damithc Do you want the inner panels to be collapsed or expanded after the user toggles the outer panel? Currently it is expanded.

output

**Comment by damithc** [comment]
> @damithc Do you want the inner panels to be collapsed or expanded after the user toggles the outer panel? Currently it is expanded.

Should be fine.  Saves work for the user.

**Pull request merged**
