### PR TITLE
Remove unused parameter in InstructorHomeAjaxCoursePageData.java #6638

### LINKED ISSUE #6638: Remove unused parameter in InstructorHomeAjaxCoursePageData.java
In `teammates.ui.pagedata.InstructorHomeAjaxCoursePageData#init`, the last parameter `sectionNames` is not used and thus can be removed.

### PR DESCRIPTION
**Pull request by JoshuaClark311**
Fixes #6638 

**Outline of Solution**

> Removed the unused parameter sectionNames from the method init and in the subsequent calls to the same method.

### CODE REVIEW

**Comment by JoshuaClark311** [comment]
For some reason my previous pull request for this issue was closed and I could not push to reopen the issue. I apologize for the second PR for this issue.

**Comment by JoshuaClark311** [comment]
Ready for Review!

**Comment by junhaoyap** [comment]
@wkurniawan07 are you still assigning people to review or can someone else do it too?

**Comment by JoshuaClark311** [comment]
@whipermr5 Thank you for all the help! :)

**Comment by whipermr5** [comment]
@JoshuaClark311 No problem :) Thanks for your contribution!

**Pull request merged**
