### PR TITLE
[#11196] Fix incorrect display of average value for rubric question stats

### LINKED ISSUE #11196: Instructor download results: total given where average is expected
v7.x (live version)

Reported by a user:
image

There is a problem in rounding off (too many decimal places) but that one is minor.

### PR DESCRIPTION
**Pull request by moziliar**
Fixes #11196 

Patches a bug from #10621

Added missing division by length.

Also decorate the numbers with `.toFixed(2)`.

### CODE REVIEW

**Comment by moziliar** [comment]
@damithc Regarding the "NA" fields, do you want it to be averaged as well? It is currently so.

**Comment by damithc** [comment]
> @damithc Regarding the "NA" fields, do you want it to be averaged as well? It is currently so.

@moziliar Do you mean if a respondent hasn't submitted a response? In that case those should be omitted from the average calculation.

**Comment by moziliar** [comment]
> Do you mean if a respondent hasn't submitted a response?
Yes. In the frontend it is translated from "0" to "NA"

> In that case those should be omitted from the average calculation.
Will do. This makes sense too.

**Comment by damithc** [comment]
> Yes. In the frontend it is translated from "0" to "NA"

Hmmm... 🤔 This doesn't sound right. Why use a legit value `0` to indicate a special value `NA`. What if the actual value is `0`? Or the actual value can never be `0`?

**Comment by moziliar** [comment]
@damithc from #10621, is it safe to say that there won't be a 0 weightage question (if there is, it is a bug)?
If so, then 0 implies no reply. We can safely remove it from the average.

**Comment by damithc** [comment]
> @damithc from #10621, is it safe to say that there won't be a 0 weightage question (if there is, it is a bug)?
> If so, then 0 implies no reply. We can safely remove it from the average.

As we allow both negative and positive value. There is no reason to disallow 0.  e.g., `bad: -1`, `neutral: 0`, `good:+1`
The UI doesn't seem to disallow it either.

**Comment by madanalogy** [comment]
@moziliar lmk me when this PR is done, I'll need to tag the release branch after this is merged

**Comment by moziliar** [comment]
@damithc I can't seem to be able to reason well behind this.
The problem lies in that if a question is not answered at all for a participant, and the following:
> Do you mean if a respondent hasn't submitted a response? In that case those should be omitted from the average calculation.

As a fix, can I just set it as assuming the weights are generally positive and do the above: omitting any 0 sub question weight from the average. Is that ok?

**Comment by damithc** [comment]
> The problem lies in that if a question is not answered at all for a participant, the sub question weight sum will be 0

This is problematic. The weight is fixed (defined by the question), and should not vary based on the answer. I think the root cause is the logic doesn't have a proper way to indicate 'not answered'. If a special value is used to indicate that case, the special value should be not also be a legit value. Furthermore, it is more appropriate for that special value to be assigned to the answer value rather than the weight. The current one might give the expected result in most cases but I'm not sure if it will cause problems if a user actually assigned '0' as a weight to a sub-question. 

That said, we can address that problem separately from this PR. The problem addressed by this PR is more urgent.

**Comment by moziliar** [comment]
@damithc I don't see a use case of weight = 0; however, I too am concerned if it emerges.
Will just push the changes about omitted "unanswered" as discussed and hand to @madanalogy for review!

**Comment by damithc** [comment]
> @damithc I don't see a use case of weight = 0; however, I too am concerned if it emerges.

Something like this?  bad: -1, neutral: 0, good:+1

**Comment by moziliar** [comment]
@damithc you are right...
Will create an issue to follow this up!

**Review by madanalogy — APPROVED** [review]
Outcomes based on the snapshot look good. For distinguishing between answered vs unanswered questions, we could probably do that in the data transformation for the `perRecipientStatsMap` after processing the API response. Suggest to tackle in another PR as mentioned. 

@rrtheonlyone need your help prioritising this PR for review. Sorry for the late notice, I forgot to hit "submit review" for this PR when I reviewed it earlier

**Comment by rrtheonlyone** [comment]
Made some minor changes. A summary below:

1. Made use of the `RubricQuestionStatisticsCalculation` class and avoided code duplication.

2. Fixed decimal place in output:
Screenshot 2021-06-20 at 9 18 32 PM

3. Fixed averaging in csv file:
```
Per Recipient Statistics (Overall)
Team,Recipient Name,Recipient's Email,Average,Breakdown
Team 4,David,d@d.com,0.9,"1.8,0"
Team 4,John,j@d.com,0.77,"1.2,0.33"
Team 4,Kenny,k@d.com,0.5,"0.2,0.8"
Team 4,Mary,m@d.com,0.7,"0.8,0.6"
Team 4,Sarah,s@d.com,0.3,"0.6,0"
Team 4,Tom,t@d.com,0.9,"1.4,0.4"
```

4. Removed "N/A" in the table and updated the formula to be: sum of averages of subquestions divided by subquestions. Created a new issue to discuss the potential pitfalls and a new proposal: https://github.com/TEAMMATES/teammates/issues/11210

**Review by rrtheonlyone — APPROVED** [review]

**Pull request merged**
