### PR TITLE
One-member teams cannot submit MCQ (multiple choice) questions #6154

### LINKED ISSUE #6154: One-member teams cannot submit MCQ (multiple choice) questions
There is an error upon submission for the student who is the only team member. In the session that surfaced this bug, there are multiple questions and only the response to the first question (which happens to be a self-evaluation question) is saved.

### PR DESCRIPTION
**Pull request by leelunn**
Fixes #6154

### CODE REVIEW

**Comment by leelunn** [comment]
Also fixes #5971

**Comment by kanghj** [comment]
Also, can you help investigate if the code on lines 73-75 are still relevant? Since questions without recipients are displayed now, I don't remember other cases where we are hiding questions. We should be able to remove those lines safely.

```
if (totalResponsesForQuestion == null) {
    continue; // question has been skipped (not displayed).
}
```

**Comment by leelunn** [comment]
@kanghj Yes. I will, but I do not know how to create a test; is there a resource available to review for this?

I will investigate relevancy of line 73-75.

**Comment by leelunn** [comment]
@kanghj  The check for null that you mentioned above seems to me to be almost pointless; the only situation I could see where this value is not a value is if the dom is manipulated manually.  My understanding of this value is that it is the number of responses possible for a specific question (such as a multiple select MCQ, or a distributive value question, and not the actual number of responses given, which, given the variable name, is a little misleading.

Since this attribute of the request parameters is provided during form creation, under normal circumstances it will always equate to an integer value.  I feel that the check could be removed and that section of code could be refactored a bit more.

However, it is theoretically possible for this value to be null if the request parameter map does not contain the entry.  Is this something that is typically error checked for and handled?  I have not noticed a lot of error handling in cases where a valid parameter is expected (such as the Integer.parseInt call on line 95)

```
if (totalResponsesForQuestion == null) {
                continue; // question has been skipped (not displayed).
}
```

**Comment by leelunn** [comment]
@kanghj I'm afraid I do not understand how to go about creating a test; I've taken a look a look at a lot of of the test code, but I don't understand  how it works.  I'm not even certain what the test is to accomplish. If the test is to verify valid question id, there appears to be a test for this in FeedbackSubmissionEditPageDataTest#testQuestionAttributes().

I have never worked with a test framework before, and this project is quite complex!  I am reviewing the design document to get a better understanding.

**Comment by kanghj** [comment]
@leelunn, thanks for investigating! We can remove that unnecessary check then. It was not entirely pointless when it was first introduced, but it became obsolete after another issue changed how questions would appear on the submission page. We were careless and did not notice this part of the code back then, resulting in the current bug.  

The test will be to verify that the student can still submit responses successfully, even if there is a question on the submission page that does not require a response. The UI test acts as an integration test in this case.

**Comment by leelunn** [comment]
@kanghj Still looking into this.  Removing the null check causes a a few tests to fail where the test data bundle has more questions than the page request parameters have.  

Will take some time for me to get an understanding how everything works.

**Comment by kanghj** [comment]
@leelunn, no worries. Actually, if removing that check causes changes in many places, it will be better to make a new issue to be resolved separately instead. We should focus on writing the test for this bug.

**Comment by leelunn** [comment]
Roger.  I am going step back and become more familiar with the process and building a test; it may be a bit before I attend to this. Also, I have four finals next week, so if I seem to disappear this is why.

**Comment by leelunn** [comment]
@kanghj With much pain and struggle to understand how these tests are built, the total 3 new lines of code is not representative of my efforts!  Over to you.

**Comment by kanghj** [comment]
I'll review this later today, sorry for the wait

**Comment by kanghj** [comment]
LGTM. Thanks, @leelunn!

**Comment by damithc** [comment]
Good effort @leelunn 👍

**Pull request merged**
