### PR TITLE
Admin: create instructor: fix bug that shows failure even when the operation succeeds #7481

### LINKED ISSUE #7481: Admin: create instructor: fix bug that shows failure even when the operation succeeds
v5.106, manual testing against dev server

image

Operation seems to succeed (the join link works and the sample course is in the datastore) but shown in red and the data is reinserted to the text box (should only happen when the operation fails)

### PR DESCRIPTION
**Pull request by LiHaoTan**
Fixes #7481 

WIP

### CODE REVIEW

**Comment by damithc** [comment]
It's better if we can update the relevant test to detect future regressions

**Comment by damithc** [comment]
@LiHaoTan any relation to #7441 ? I can't seem to find the sample comments that PR is supposed to add.

**Comment by LiHaoTan** [comment]
@damithc Hmm I don't think so, I went to check out the branch for that PR and could only get this result.

image

**Comment by LiHaoTan** [comment]
@wkurniawan07 sorry this isn't done yet I haven't added the tests

**Comment by whipermr5** [comment]
I guess this should wait till after #7522 (webpack) is merged.

**Comment by wkurniawan07** [comment]
@LiHaoTan let's not forget to resume this.

**Comment by whipermr5** [comment]
@LiHaoTan Reminder :)

**Comment by damithc** [comment]
If adding tests is taking longer, can merge this first and add tests as a separate PR

**Comment by whipermr5** [comment]
@LiHaoTan Do create an issue about adding the tests :)

**Pull request merged**
