### PR TITLE
[#10243] Change multi level panel color to match V6

### PR DESCRIPTION
**Pull request by ccyccyccy**
Part of #10243 

GQR / RQG
image

GRQ / RGQ
image

### CODE REVIEW

**Comment by damithc** [comment]
This horizontal line is not needed?
image

**Comment by wkurniawan07** [comment]
@damithc here is V6:

Screen Shot 2020-07-23 at 10 29 33 PM

The horizontal line is faint, but is there.

**Comment by damithc** [comment]
> The horizontal line is faint, but is there.

Not a big problem but both versions can benefit from removing that line. OK to keep too.

**Comment by ccyccyccy** [comment]
> Not a big problem but both versions can benefit from removing that line. OK to keep too.

Have removed the `<hr>`. Screenshot updated.

**Comment by damithc** [comment]
> Have removed the `<hr>`. Screenshot updated.

Nice 👍

**Pull request merged**
