### PR TITLE
Feedback session description: text color lost after saving #5774

### LINKED ISSUE #5774: Feedback session description: text color lost after saving
To try rich text support, I tried coloring some text. After saving, the text color turned to black. If this formatting is not supported, it should be removed from the formatting toolbar.
image

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #5774

### CODE REVIEW

**Comment by belyabl9** [comment]
Ready to review

**Comment by wkurniawan07** [comment]
@belyabl9 can you update the test to include span as a permissible tag?

**Comment by belyabl9** [comment]
Ready to review

**Comment by wkurniawan07** [comment]
Ok, looks good now :+1:

**Pull request merged**
