### PR TITLE
Rename settingUp.md -> setting-up.md #7741

### LINKED ISSUE #7741: Rename settingUp.md -> setting-up.md
For consistency with the way the other documents are named. Also involves updating links to it in the other documentation files, if any.

### PR DESCRIPTION
**Pull request by yliang97**
Fixes #7741 

**PR Checklist**

**Outline of Solution**

Trivial renaming fix - this is my first PR to an open source project!

### CODE REVIEW

**Comment by yliang97** [comment]
Hi there, I created a new pull request to reflect hopefully the correct changes. Cheers!

**Comment by whipermr5** [comment]
@yliang97 In future, do continue work on the existing PR instead of opening a new one. Refer to the docs: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#updating-the-pr

**Comment by yliang97** [comment]
Okay do you want me to reopen this one? And update it here? or use the other PR request

**Comment by whipermr5** [comment]
@yliang97 Since you've already created the other one, I'm okay with you continuing work there.

**Comment by yliang97** [comment]
Thanks @whipermr5 looking forward to your feedback with the other PR and appreciate your understanding

**Pull request closed without merging**
