### PR TITLE
[#11299] Remove previous results if search encounters error

### LINKED ISSUE #11299: Instructor searching: previous results are shown if search encounters an error
v8.0.0.rc.0

Problem: The previous results are shown the search encountered an error
image

### PR DESCRIPTION
**Pull request by tjtanjin**
Fixes #11299

**Outline of Solution**

Should a search result in an error, existing results are cleared to eliminate any potential confusion from mismatching search terms and results on the UI.

Here is the behaviour before the changes:
https://user-images.githubusercontent.com/43908963/128482662-ed96e16b-5542-45ba-8a1c-60d266900928.mov

Here is the behaviour after the changes:
https://user-images.githubusercontent.com/43908963/128482736-06ba99f4-c52c-410b-8d18-82960778abf2.mov

### CODE REVIEW

**Comment by jianhandev** [comment]
@tjtanjin do you mind attaching a short video to show how the problem has been solved?

**Comment by tjtanjin** [comment]
@jianhandev Hello! I have edited the post to include video examples for your reference :)

**Review by jianhandev — APPROVED** [review]
LGTM

**Review by wkurniawan07 — APPROVED** [review]
LGTM

**Pull request merged**
