### PR TITLE
 Feedback path options not enabled after cancel adding team contribution question #5716 

### LINKED ISSUE #5716: Feedback path options not enabled after cancel adding team contribution question
At feedback session edit page, if an instructor adds a new team contribution (which has only one available feedback path), cancels adding the question, and subsequently adds another question of a different type, the other feedback paths are still disabled.

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #5716

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
@chowyb Since you discovered this bug

**Comment by chowyb** [comment]
@YongJieYongJie wasn't me, it was @JosephineKwa, do you want to change reviewers? :stuck_out_tongue:

**Comment by YongJieYongJie** [comment]
@chowyb It's alright, since you're already assigned =)

**Comment by chowyb** [comment]
@YongJieYongJie looks good! There's some stuff I'd like to change but it's definitely outside the scope of this PR (eg. magic strings in tests)

**Pull request merged**
