### PR TITLE
[#11878] Modify CreateAccountRequestAction

### PR DESCRIPTION
**Pull request by jayasting98**
Part of #11878 

**Outline of Solution**

 

`AccountCreateRequest`
- added comments

`AccountRequestData`
- added id
- added status
- added comments

`CreateAccountRequestAction`
- removed check for registered `Instructor` to allow even them to create account requests
- removed sending of registration email (this should only occur when the instructor is approved, but in the new logic, creating account requests no longer implies approval)
- changed response to `AccountRequestData`

### CODE REVIEW

**Comment by ziqing26** [comment]
@EuniceSim142 need your help to check if this change affects the correctness of the current admin create account flow 🙏

**Comment by jayasting98** [comment]
@ziqing26 It does affect the old logic. This change removes the sending of the registration email.

In the old logic, when the account request is created by the admin, the account request is already approved (it is only pending when it is still in the Google form submissions), so we send the registration email. On the other hand, in the new logic, when the account request is created by an instructor, the account request is merely pending, so we do not send the registration email.

Still, I think this is the intended change, right?

**Comment by ziqing26** [comment]
> @ziqing26 It does affect the old logic. This change removes the sending of the registration email.
> 
> In the old logic, when the account request is created by the admin, the account request is already approved (it is only pending when it is still in the Google form responses), so we send the registration email. On the other hand, in the new logic, when the account request is created by an instructor, the account request is merely pending, so we do not send the registration email.
> 
> Still, I think this is the intended change, right?

Yes, that is intended change

**Comment by ziqing26** [comment]
@xenosf @EuniceSim142 reminder to review this PR 🙏

**Review by EuniceSim142 — APPROVED** [review]
LGTM!

**Review by xenosf — APPROVED** [review]
LGTM!

**Comment by jayasting98** [comment]
Thanks for the reviews!

**Pull request merged**
