### PR TITLE
BackDoorTest: Remove `@SuppressWarnings("deprecation")` #7901

### LINKED ISSUE #7901: BackDoorTest: Remove `@SuppressWarnings("deprecation")`
The deprecated constructor has already been removed in #7191 and replaced by the use of the builder.

```diff
         @SuppressWarnings("deprecation")
-        InstructorAttributes instructor = new InstructorAttributes(instructorId, courseId, name, email);
+        InstructorAttributes instructor = InstructorAttributes.builder(instructorId, courseId, name, email)
+                .build();
```

### PR DESCRIPTION
**Pull request by MelkyFB**
Fixes #7901 

```diff
-        @SuppressWarnings("deprecation")
         InstructorAttributes instructor = InstructorAttributes.builder(instructorId, courseId, name, email)         .build();
```

Just removed the informed line.

### CODE REVIEW

**Comment by LiHaoTan** [comment]
@MelkyFB I'm wondering why did you close this?

**Comment by MelkyFB** [comment]
Sorry, I have to follow the intro guidelines, I'll do that and reopen here.

**Comment by sujeet14108** [comment]
@MelkyFB PR title should be same as issue title

**Comment by sujeet14108** [comment]
It should be like this 
`BackDoorTest: Remove @SuppressWarnings("deprecation") #7901 #7907`

**Comment by MelkyFB** [comment]
Thank you @sujeet14108

**Comment by sujeet14108** [comment]
Remove extra `#7907` from title :sweat_smile:

**Comment by sujeet14108** [comment]
@MelkyFB Looks like you have made changes in your master. You should always create a new branch to push your commits.
Read this [https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues](url)  and follow proper guideline

**Pull request closed without merging**
