### PR TITLE
[#10819] Instructor edit session page: Add scroll to top button 

### LINKED ISSUE #10819: Instructor edit session page: Add scroll to top button
- **Environment**: V7.4.0

**Description of feature/enhancement**
In Instructor Edit Feedback Session in Figure 1.3.1 and Figure 1.3.2, there is no feature to scroll back up if the user is at the bottom of the page. In a Feedback Session with fewer questions, it is not a big issue to scroll back to the top when the user finished with the questions. However, if there are many questions in the session and the questions are expanded, it may take the user a long time to get back to the top of the page. The expand questions button is also located on the top of the page, it means the user only has one way to get back to the top which is by scrolling. 

**Justification**

By adding a scroll to the top button in this page, the user can quickly get back to the top if the user wants to quickly get to other questions at the top of the page. The scroll to top button is implemented to be in the bottom right of the page. It should only show if the user has scrolled a certain amount of the page’s length. The button should also change color if the user hovers on it.

**Existing similar features and their shortcomings**

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Fixes #10819 

**Outline of Solution**

Mostly followed #11619. Credits to @egorovak.

https://user-images.githubusercontent.com/53614454/175048824-76903c2c-825c-4341-a767-852196dfff7b.mp4

Note: My computer is slightly laggy in the video above.

### CODE REVIEW

**Comment by sivayogasubramanian** [comment]
This PR is ready for review.

**Review by zhaojj2209 — APPROVED** [review]
LGTM

**Review by samuelfangjw — APPROVED** [review]
LGTM, pending investigation into failing e2e test. 

Note that the `behavior: 'smooth'` option will not work on safari browsers, though this is not an issue in my view.

**Comment by sivayogasubramanian** [comment]
> pending investigation into failing e2e test.

Can help to re-run the test. Don't think these changes affect the e2e tests.

**Pull request merged**
