### PR TITLE
[#12900] Gradle task componentTests should not stop entirely when only one task fails

### LINKED ISSUE #12900: Gradle task componentTests should not stop entirely when only one task fails
The Gradle task `componentTests` now depends on the two Gradle tasks `unitTests`, and `integrationTests` since #12056. These can be independent from each other, so if one fails, we should continue to execute the other (except when it fails due to the failure of a common dependency, like compilation). However, when either of them fails due to a failing test, the other one is not completed because the execution of the whole `componentTests` task is aborted.

To prevent this, we can run `componentTests` with the option `--continue`, just like the Gradle task `lint`. This probably needs to be changed in the GitHub workflows and in the documentation.

### PR DESCRIPTION
**Pull request by emrekenar**
Fixes #12900

**Outline of Solution**

After the docker is started, running the code below stops if `integrationTests` task fails. 

`./gradlew componentTests`

However, running the following command prevents stopping before all `componentTests` tasks finish.

`./gradlew componentTests --continue`

Note that if `unitTests` task is completed before, to run it again, either the build folder should be cleaned with `./gradlew clean` or `--rerun-tasks` flag should be passed as well.

Also note that `./gradlew componentTests jacocoReport --continue` doesn't work. Instead, `./gradlew jacocoReport` command should be executed separately.

In this commit, the `--continue` flag is added in github workflows and the documentation is updated.

### CODE REVIEW

**Review by jayasting98 — CHANGES_REQUESTED** [review]
Here's just a bit of feedback.

**Review by jayasting98 — APPROVED** [review]
Thanks!

**Comment by emrekenar** [comment]
Thank you for the approval, let me know if I need to test or add anything else

**Comment by weiquu** [comment]
Hi @emrekenar, could you also help to make the change to the `/.github/workflows/jdk21.yml` file? Should be line 34. Thanks!

**Comment by emrekenar** [comment]
Hi @weiquu I made the change, it seems to be working fine. Let me know if there is anything else I can do.

**Comment by jayasting98** [comment]
@weiquu Just a reminder to review this. It looks fine to me now. I think your comment has been addressed.

**Review by weiquu — APPROVED** [review]
LGTM

**Pull request merged**
