### PR TITLE
[#11254] Instructor Feedback Session Results: Session Duration formatting

### LINKED ISSUE #11254: Instructor Feedback Session Results: Session Duration formatting
- **Environment**:  `master` branch at commit f4924bb3225d25c1e14a499cb563d1106b606949

**Steps to reproduce**
From the Instructor Home page, view the results of any course. (Results -> View Results)

**Expected behaviour**
The Session Duration dates are each on separate lines if there is not enough space.
image

**Actual behaviour**
The Session Duration date (usually the second one) is cut off depending on the window size.
image

**Additional info**

Very small visual bug, might not warrant fixing at all.

Could possibly be solved as seen above in expected outcome by changing regular spaces to non-breaking spaces for dates in instructor-session-result-page.component.ts, and adding minor tweaks in instructor-session-result-page.component.html

### PR DESCRIPTION
**Pull request by ericluoliu**
Fixes #11254

### CODE REVIEW

**Review by halfwhole — CHANGES_REQUESTED** [review]
Hi @ericluoliu, it looks like the issue still persists even with these changes! For example:

Screenshot 2021-07-17 at 11 50 06 PM

With your suggested change along with the existing line of code below, the entire session duration text will consist of non-breaking spaces, but because it's too long, it still has to break somewhere (leading to the situation in the image above):

https://github.com/TEAMMATES/teammates/blob/48b67bae03babf5a5e578aefce47f0285e8de8b4/src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html#L28

To resolve this, we could perhaps either: use all normal spaces everywhere, but make a line-break after the 'to' (by adding `<br/>` perhaps); or we could use normal spaces before and after the 'to', along with non-breaking spaces in the formatted opening/closing times. (I'd favour the first approach actually!)

**Comment by ericluoliu** [comment]
Hi @halfwhole , sorry for the very delayed response. I made the suggested changes and reverted my old changes.

**Review by halfwhole — COMMENTED** [review]
The session duration box now looks like this, as the whitespaces before the 'to' are collapsed into a single space, and the whitespaces after the `<br>` are simply ignored:

Screenshot 2021-08-03 at 1 59 57 PM

May I suggest changing the 3 whitespaces before the 'to' back to non-breaking spaces, and simply removing the 3 whitespaces after the linebreak? That should resolve the issue

**Comment by ericluoliu** [comment]
Done.

**Review by halfwhole — APPROVED** [review]
LGTM

**Comment by ericluoliu** [comment]
image

E2E Tests give me an error. I think it is because it expects just a tab rather than an entire line break in the spot we changed.

**Review by halfwhole — COMMENTED** [review]
In that case, could you update the relevant code used in the E2E tests too? The relevant lines should be here:

https://github.com/TEAMMATES/teammates/blob/8a97db611be37ae1975715723e1913de4fd675e8/src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java#L781-L784

**Review by halfwhole — APPROVED** [review]

**Review by rrtheonlyone — APPROVED** [review]
LGTM

**Pull request merged**
