### PR TITLE
[#11270] Fixed Alignment Issue with Checkboxes in Template Questions Modal

### LINKED ISSUE #11270: Checkboxes aligned via center instead of start when choosing from template questions
**Environment**: `master` branch at commit 6484257

**Steps to reproduce**
From edit feedback session page, click Add New Question -> Choose from template questions.

**Expected behaviour**
Checkboxes aligned to the first line when there are multiple lines.
Screenshot 2021-07-13 at 9 45 04 PM

**Actual behaviour**
Checkboxes are aligned in the center when there are multiple lines.
Screenshot 2021-06-21 at 8 34 59 PM

**Additional info**
Modifying files `template-question-modal.component.scss` and `template-question-modal.component.html` should be sufficient to fix this.

### PR DESCRIPTION
**Pull request by josflesan**
Fixes #11270

**Outline of Solution**

Aligned checkboxes to start of the parent flex container using align-self and reduced top margin to achieve the required alignment.

### CODE REVIEW

**Comment by abh1je3T** [comment]
Hi,

I would like to give it a try.

**Comment by damithc** [comment]
> I would like to give it a try.

@abh1je3T there is already a PR for it. In fact, you are commenting in that PR thread :-p

**Comment by damithc** [comment]
@josflesan let us know when the PR is ready for review.

**Comment by josflesan** [comment]
The PR should now be ready for review

**Review by halfwhole — APPROVED** [review]
LGTM, after screenshot for convenience:

Screenshot 2021-08-15 at 11 16 03 PM

**Review by jianhandev — APPROVED** [review]
LGTM

**Pull request merged**
