### PR TITLE
[#12045] Instructor copying sessions: preserve time when auto-changing dates

### LINKED ISSUE #12045: Instructor copying sessions: preserve time when auto-changing dates
v8.21

Current: When an instructor is copying a session to a new course, dates are auto-changed if they don't fall within the allowed time period for new sessions. e.g.,
image

Suggestion: Preserve the original time and change the date only, as it is most likely the instructor will want to keep the same times as before.

### PR DESCRIPTION
**Pull request by andremralves**
Fixes #12045 

**Outline of Solution**

When copying a feedback session, if the dates aren't in the allowed time period, the new date will use your local time to generate a valid date range. For the opening time, the new date is +2 days from now and for the closing time the new date is +7 days from now. I kept this logic and added an extra logic to set the time to the original one instead of your local time.

I also changed some variable names as the names were saying "roundedUp", but  what is really happening is a round down with the "startOf" method of moment.js. So I changed the last part to "roundedDown".

I didn't changed the logic to keep the time for dates that surpasses the upper bound limit because that could lead to some corner case problems if the original time is bigger than the local time (the date would be bigger than the limit).

image

### CODE REVIEW

**Review by zhaojj2209 — CHANGES_REQUESTED** [review]
`InstructorHomePageE2ETest` is failing due to the changes made in this PR, do look into it.

Also, before opening a PR, we would appreciate if you could indicate interest in fixing the issue in the issue thread itself first, and check that there are no other people working to fix the issue.

**Comment by zhaojj2209** [comment]
Closing due to inactivity. Feel free to reopen this PR if you would like to continue working on it.

**Comment by andremralves** [comment]
Hi, I would like to reopen this PR but I think I don't have the right to reopen it. Could you reopen it for me, please?

**Review by domlimm — APPROVED** [review]
LGTM! Thanks for solving this issue and catching the inconsistent rounding! 👍🏻

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
