### PR TITLE
Instructor: homepage: rephrase confirmation dialog text for the 'unpublish' button #3352

### LINKED ISSUE #3352: Instructor: homepage: rephrase confirmation dialog text for the 'unpublish' button
Similar to #3338, but for the 'unpublish' button

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #3352 

**Outline of Solution**

- Added additional text (similar to that added in PR https://github.com/TEAMMATES/teammates/pull/3351) to inform the Instructor that emails will be sent out to students and that the students will no longer be able to view responses.

Screenshot of new behavior:

screen shot 2017-06-08 at 2 48 47 am

**Note:** Apologies for taking a seemingly simple issue. The issue had the `d.Contributors` and `e.2` labels, which was why I decided to tackle it.

### CODE REVIEW

**Comment by whipermr5** [comment]
@HirdayGupta Pending trailing spaces removal (and perhaps GodMode run?)

**Comment by HirdayGupta** [comment]
@whipermr5 Need some help with removing the trailing spaces. This is the line of code in question:
```JavaScript 
const messageText = `Are you sure you want to unpublish the session "${$button.data('fsname')}" An email will be sent to students to inform them that the session has been unpublished and the session responses will no longer be viewable by students.`;
```

Since this line is longer than the number of characters permissible by the linter, I broke it up like this:
``` JavaScript
const messageText = `Are you sure you want to unpublish the session "${$button.data('fsname')}"?
                     An email will be sent to students to inform them that the session has been unpublished 
                     and the session responses will no longer be viewable by students.`;
```

I assumed that the convention was to split it up the long string by placing the content as above. However, since this is resulting in a trailing spaces error, any suggestions on how I should split this up?

**Comment by whipermr5** [comment]
@HirdayGupta The splitting up is fine; just drop the space after `unpublished` on the same line (the leading spaces on the next line will do the job of separating `unpublished` from `and`).

**Comment by HirdayGupta** [comment]
@whipermr5 my bad, mistook trailing spaces for leading spaces. 😅 

All checks seemed to have passed, so no need for a god mode. Ready for review.

**Pull request merged**
