### PR TITLE
[#11339] Update modal header to be more consistent

### LINKED ISSUE #11339: More Info Modal Header inconsistent
Page: `/web/front/help/instructor`

Modal Header looks off, not consistent

### PR DESCRIPTION
**Pull request by xinyee20**
Fixes #11339

(before) 

(after)

### CODE REVIEW

**Comment by damithc** [comment]
@TEAMMATES/active-mentors anyone up for reviewing this?

@xinyee20 looks like the `<strong>/<b>` tags are actually making the text non-bold?

**Comment by xinyee20** [comment]
> @xinyee20 looks like the `<strong>/<b>` tags are actually making the text non-bold?

Hi prof @damithc ,
Both make the header looks bold as compared to when its unbolded. The original very bolded visual appearance was due to an unexpected situation.

Originally `<strong><strong>` was used, since the second tag missed out a `/`, no closing tag was given, resulting in an unexpected effect that looks very bolded (I was unable to emulate by normal means)

else with `<strong></strong>` given, it will look like the following with just the name bolded

When the header is unbolded, it looks like the following:

I chose to use `<b></b>` in the end over `<strong></strong>` for the whole header as the latter is usually used for emphasis e.g. notes/warnings while the former is more for visual emphasis which seems more suitable in our case. 


Which do you prefer? I will change accordingly

**Comment by damithc** [comment]
Appearance-wise, probably no need for extra bolding but I'm OK to have it too. Consistency is important too -- which means we should consider how bolding is used in other similar Modals within TEAMMATES.

**Comment by xinyee20** [comment]
> Appearance-wise, probably no need for extra bolding but I'm OK to have it too. Consistency is important too -- which means we should consider how bolding is used in other similar Modals within TEAMMATES.

I went to look at the code of other modals, the present change with single bolding across the whole header is most similar/consistent with the other modals, so I will not make further amendments.

**Review by daongochieu2810 — APPROVED** [review]

**Comment by damithc** [comment]
A side question? Why `<b>` and not `<strong>` (or vice versa)? It's better if the choice of tag is consistent too.

**Comment by jianhandev** [comment]
> A side question? Why `<b>` and not `<strong>` (or vice versa)? It's better if the choice of tag is consistent too.

`<strong>` is used for emphasis (e.g. notes, warnings) whereas `<b>` is used merely for style. Although it can be subjective, in this case I would think `<b>` is more appropriate.

**Comment by damithc** [comment]
@ccyccyccy can do the final review (and merge) for this one too? TIA

**Review by ccyccyccy — APPROVED** [review]
LGTM

**Pull request merged**
