### PR TITLE
[#10645] [#10688] Fix bugs in instructor results page

### LINKED ISSUE #10795: Instructor GQR-RQG view cannot hide statistics
- **Environment**: `master` branch at commit 481c7a9786bb3408d7b73a925065b822349d4852

**Steps to reproduce**
- unmarking show statistics in GQR or RQG view does not hide statistics

**Additional info**
GQR view - show statistics is not marked but statistics is still shown
GQR

RQG view - same as above
RQG

### LINKED ISSUE #10798: Instructor result page filter by section not accurate
- **Environment**: `master` branch at commit 481c7a9786bb3408d7b73a925065b822349d4852

**Steps to reproduce**
- Use GRQ/RGQ/GQR/RQG view on instructor results page
- filter by section
- the filter will always only show the results for the chosen section

**Additional info**
Supposed to show results if either recipient or giver is in the section A but only shows responses with Section A as giver

### PR DESCRIPTION
**Pull request by jtankw3**
Fixes #10798
Fixes #10795

**Outline of Solution**
- Add `*ngIf = showStatistics` check to remove statistics element when statistics should not be shown
- Standardize naming for `No Specific Team` across views
    - Did not change naming for the titles as `No Specific Team Statistics` sounds weird to me.
- Add extra variable `sectionOfView` to differentiate filtering for the view and filtering because of the section.
    - It is not possible to filter the section headers as the data is only loaded when the headers are expanded. Thus, added a empty message for sections that are empty after filtering.

**Statistic not shown when show statistics is not selected**
statistics

**Renamed to `No Specific Team` but titles are not renamed.**
specific

**Filter by sections now shows other sections and has a message when the section is empty.**
filter

### CODE REVIEW

**Comment by wkurniawan07** [comment]
> Standardize naming for No Specific Team across views

While in theory a correct thing to do, is this necessary, though? Unlike section, team is a hard requirement for students. Even instructors should be assigned to a team named "Instructors" for this page.

**Comment by jtankw3** [comment]
> > Standardize naming for No Specific Team across views
> 
> While in theory a correct thing to do, is this necessary, though? Unlike section, team is a hard requirement for students. Even instructors should be assigned to a team named "Instructors" for this page.

The responses with no team are from questions with recipient type `NONE`. Actually they have team name `-`, so we can choose to standardize as `-` or `No Specific Team`

**Comment by wkurniawan07** [comment]
> The responses with no team are from questions with recipient type `NONE`

Right, I forgot about recipient type. Either should be fine.

**Review by madanalogy — APPROVED** [review]
LGTM

**Review by xpdavid — APPROVED** [review]

**Pull request merged**
