### PR TITLE
 [#12161] Instructor adding a new session: stray X in the form UI 

### LINKED ISSUE #12161: Instructor adding a new session: stray X in the form UI
v8.23.*, production

Context: instructor is adding a new session to a course

Problem: there is an `X` that should be on the top-right (not top-left) or not present at all.
image

### PR DESCRIPTION
**Pull request by SudarshanSirsi**
Fixes #12161 

**PR Checklist**
Ensure that you have:
- [x ] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x ] Added the issue number to the "Fixes" keyword above
  - [x ] Titled the PR as specified in the above mentioned document
- [x ] Made your changes on a branch other than `master` and `release`
- [ x] Gone through all the changes in this PR and ensured that:
  - [x ] They addressed one (and only one) issue
  - [x ] No unintended changes were made
- [x ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

Added display flex properties and used justify-contents:right ; to move stray-x from left-top to right-top.
image

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
Hello @SudarshanSirsi ,
Can you please tell how you pass E2test
Previously you haven't pass it.
Actually I am facing same issue in my PR #12189 
Can you please tell me how I can fix it.

**Review by cedricongjh — APPROVED** [review]
looks good to me!

**Review by kevin9foong — APPROVED** [review]
Tested on local and LGTM as well

**Review by samuelfangjw — APPROVED** [review]
Thanks for contributing to TEAMMATES!

**Comment by SudarshanSirsi** [comment]
You are welcome @kevin9foong @cedricongjh @samuelfangjw

**Pull request merged**
