### PR TITLE
[#10631] Unnecessary checks in InstructorPrivileges.java

### LINKED ISSUE #10631: Unnecessary checks in InstructorPrivileges.java
In InstructorPriviledges.java methods: removeSectionLevelPrivileges,removeSessionsPrivilegesForSection<br />
if (this.sessionLevel.containsKey(sectionName)) is Unnecessary since the map will remove the key only if it exists.

### PR DESCRIPTION
**Pull request by konkos**
Fixes #10631

### CODE REVIEW

**Comment by madanalogy** [comment]
Your PR is not passing the lint, you can try running lint locally to fix it

**Comment by konkos** [comment]
@madanalogy I have been trying to do that but i couldn't find information on how to do it. Could you please point me to the right resources so that I can resolve this issue?

**Comment by madanalogy** [comment]
> @madanalogy I have been trying to do that but i couldn't find information on how to do it. Could you please point me to the right resources so that I can resolve this issue?

You need to run static analysis on your files. See: https://github.com/TEAMMATES/teammates/blob/master/docs/static-analysis.md#running-static-analysis

**Review by ccyccyccy — APPROVED** [review]
LGTM 👍

**Review by t-cheepeng — APPROVED** [review]
LGTM

**Pull request merged**
