### PR TITLE
Rename HTML files in src/test/resources/pages that start with upper case #5103 

### LINKED ISSUE #5103: Rename HTML files in src/test/resources/pages that start with upper case
The files in `src/test/resources/pages` should all start with a lower case. There are some `Instructor*.html` that don't follow it.

### PR DESCRIPTION
**Pull request by GGfpc**
Fixes #5103 

Fixed the issue by running the following command: rename 's/\b(\w)/\l$1/g' *

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Hi @GGfpc, please do not commit directly to `master` branch as it will make it hard when you have to sync with our repo's `master` branch. As per lined out in our [process document](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#creating-a-branch), you need to start a separate branch in order to submit a pull request.
I will allow this one to pass, but if you wish to work on more issues, you have to adhere to the workflow. Thanks for your contribution :+1:

**Comment by wkurniawan07** [comment]
@GGfpc can we get your full name so that we can add you to our contributors' list?

**Comment by GGfpc** [comment]
@wkurniawan07 Sure, Gonçalo Garcia. Quick question, is there a label for easier issues other than first timers? I'd like to contribute, but the code base is really overwhelming

**Comment by wkurniawan07** [comment]
@GGfpc `d.Contributors` is what you are looking for.

**Pull request merged**
