### PR TITLE
[#11337] Home page header misaligned

### LINKED ISSUE #11337: Home page header misaligned
Page: `/web/front/home`

Headers are not aligned properly

### PR DESCRIPTION
**Pull request by xinyee20**
Fixes #11337

- Alignment of Headers

(before) 

(after)

### CODE REVIEW

**Comment by damithc** [comment]
@TEAMMATES/active-mentors anyone up for reviewing this PR?

**Review by halfwhole — COMMENTED** [review]
Perhaps we could shift the styles into the relevant `.scss` file? Otherwise it looks good to me

**Comment by xinyee20** [comment]
> Perhaps we could shift the styles into the relevant `.scss` file? Otherwise it looks good to me

yup sure, I have shifted the styles into the scss file

**Review by jianhandev — APPROVED** [review]
LGTM

**Comment by damithc** [comment]
@halfwhole you commented on this PR earlier. Do you approve of the current version?

**Review by halfwhole — APPROVED** [review]
Yep LGTM as well!

**Comment by damithc** [comment]
@halfwhole I think you can merge this, as it is a simple PR and has two approvals. Remember to follow our convention for commit message subject.

**Pull request merged**
