### PR TITLE
[#10532] Instructor view results: tweak icon-buttons

### LINKED ISSUE #10532: Instructor view results: tweak icon-buttons
V7: 
image

V6:
image

The style of icon-buttons in V6 seems cleaner? Plus, blue indicates they are active.

### PR DESCRIPTION
**Pull request by hhdqirui**
Fixes #10532

**Outline of Solution**

One of the classes for the buttons is changed from `btn-light` to `btn-outline-primary` to change the colour of the buttons to blue to indicate the buttons are active.

The result looks like this
image

### CODE REVIEW

**Review by niqiukun — APPROVED** [review]
LGTM!

**Comment by t-cheepeng** [comment]
@hhdqirui Why not just use the bootstrap classes? the primary ones in particular

**Comment by hhdqirui** [comment]
> @hhdqirui Why not just use the bootstrap classes? the primary ones in particular

Using primary button would look like this. The colour of the button would be a bit too blue and it does not match with the colour of rest of the component very well.
image

**Review by Derek-Hardy — CHANGES_REQUESTED** [review]
I think `btn-outline-primary` will do the work.

Screenshot 2021-01-15 at 20 08 02

**Comment by hhdqirui** [comment]
> I think `btn-outline-primary` will do the work.

OK sure.

**Review by t-cheepeng — APPROVED** [review]
LGTM. But do fix the lint error first

**Comment by Derek-Hardy** [comment]
And please update on the PR description for latest changes. @hhdqirui

**Review by Derek-Hardy — APPROVED** [review]
LGTM

**Pull request merged**
