### PR TITLE
[#10161] Extract data out to dedicated file from instructor help page componenets

### LINKED ISSUE #10161: Instructor help page components: extract data out to dedicated file
Some instructor help page components, such as `instructor-help-questions-section.component.ts`, `instructor-help-sessions-section.component.ts`, and `instructor-help-students-section.component.ts`, have a lot of data defined in it as field. It works but is not a good practice as it pollutes application code with too much data.

The data should be extracted out into a dedicated `.ts` or `.json` file and then used via import. This would also enable reuse across different help page sections.

### PR DESCRIPTION
**Pull request by edwardkang0925**
Fixes #10161 
**Solution**
For each component, I created a dedicated typescript file and used import/export to make sure the data will be assigned to each component as data properly. 

**Concerns**
For cleaner code, should I use "import * as 'data' from 'dedicated ts file' " instead of listing all the imports for the data which is extracted out? I didn't go with this method because it seems not the best practice for this project.

### CODE REVIEW

**Comment by madanalogy** [comment]
Please resolve the merge conflicts thank you. Also, what were the considerations in mind regarding your choice to use a `ts` file instead of `json`?

**Comment by yook0530** [comment]
@madanalogy Hi, I am working with @edwardkang0925 @manzurayusup as a team, and I resolved the merge conflicts. However, we ran into firefox e2e test error while passing the chrome e2e test. Would this be related to our choice of file type?
 
Regarding our choice to use `ts` instead of `JSON`, we originally thought the advantage of `JSON` is being language independent but in this issue, the data are mainly used for testing purposes, and the test runs in `ts` file. Therefore, we thought using `ts` would be more natural. Please let us know if using`JSON` in this case is a more desirable practice, we will modify our code into `JSON`. 

Again, thank you for your advice.

**Comment by madanalogy** [comment]
> @madanalogy Hi, I am working with @edwardkang0925 @manzurayusup as a team, and I resolved the merge conflicts. However, we ran into firefox e2e test error while passing the chrome e2e test. Would this be related to our choice of file type?

This is a common problem being faced right now with PRs and our CI, don't worry about it.

> Regarding our choice to use `ts` instead of `JSON`, we originally thought the advantage of `JSON` is being language independent but in this issue, the data are mainly used for testing purposes, and the test runs in `ts` file. Therefore, we thought using `ts` would be more natural. Please let us know if using`JSON` in this case is a more desirable practice, we will modify our code into `JSON`.

All good, was just curious on the justifications for your decision. I'm okay with `ts`, senior devs might disagree though so just wait out for their review.

> Again, thank you for your advice.

You're welcome :)

**Comment by yook0530** [comment]
@madanalogy About a month and a half, we've been learning and attempting to resolve open issues. While doing so, we found that the community has been welcoming, and with helpful feedback, we could resolve several entry-level issues. We are planning to contribute to this project for about two more months and expecting to resolve more challenging and meaningful issues (or add some additional features if possible). We are fully aware that this project is mainly discussed via GitHub issues channel but we think if there is a bit more direct communication channel such as Slack that would significantly improve our workflow and efficiency. Would you consider having such a channel with us? If this doesn't work for you, that is totally fine, we understand. Please let us know. Thanks!

**Comment by madanalogy** [comment]
> @madanalogy About a month and a half, we've been learning and attempting to resolve open issues. While doing so, we found that the community has been welcoming, and with helpful feedback, we could resolve several entry-level issues. We are planning to contribute to this project for about two more months and expecting to resolve more challenging and meaningful issues (or add some additional features if possible). We are fully aware that this project is mainly discussed via GitHub issues channel but we think if there is a bit more direct communication channel such as Slack that would significantly improve our workflow and efficiency. Would you consider having such a channel with us? If this doesn't work for you, that is totally fine, we understand. Please let us know. Thanks!

I've spoken with the core team and we'll try to work out something down the road. In the meantime, you can continue to use the issue tracker. You can create issues for dev help or advice, and tag any of us in issues if you have questions or need any clarification. If you'd like more direct communication with me personally feel free to drop me an email and we can work something out, my address is available on my profile. Thank you for all your contributions thus far!

**Pull request merged**
