### PR TITLE
Submit feedback: distribute points (among recipients) question: give a way to distinguish between recipients with the same name #6372 

### LINKED ISSUE #6372: Submit feedback: distribute points (among recipients) question: give a way to distinguish between recipients with the same name
In the feedback submission page, there is no way (except by inspecting the html) to distinguish between students with the same name. This affects the results page as well, where the user is only able to distinguish between students with the same name through their photograph.

### PR DESCRIPTION
**Pull request by eei34**
Fixes #6372 

feebacksession1

@damithc
I've added a View Email tooltip and although @AnaghHegde thought to show it only for the students with the same name, I thought it may be useful to have it available for all students.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@damithc we don't want to remove the view photo on hover/click, right?

**Comment by damithc** [comment]
> @damithc we don't want to remove the view photo on hover/click, right?

No, we want to keep it. Perhaps the pop-up can show both photo _and_ email for all students (if it is not a heavy performance burden) thereby giving a way to distinguish between people with the same name as well?

**Comment by eei34** [comment]
@damithc 
The photo is set up to download once after clicking so it seems the only option is to have the email address included in the contents along with the photo. Would that work? I originally had separate links for View Photo and View Email but couldn't find the functionality to restart the popover with the original view email/ view photo once the user clicked on one of them. In my opinion, View Email is more useful to an instructor than View Photo since there are places in the app to do so and it would likely be more handy to distinguish a students feedback through their email address. Any suggestions on what to do?

**Comment by damithc** [comment]
@eei34 Email can be shown as a tooltip rather than a popover because it is just text. Does that help to work around the problem of having two popovers?

**Comment by eei34** [comment]
@damithc Not sure if I understand you correctly. Are you saying have both a tooltip and popover over a name?

**Comment by damithc** [comment]
Guys, I've been thinking about this issue and realized perhaps tooltip/popover is not the best solution. For example, it will not appear in hardcopy of the results. How about we simply prevent users from enrolling multiple persons with the same name? While it is possible for two people to have the same name, for the purpose of TEAMMATES the instructor has to decorate duplicate names with some extra info to make them unique e.g. `John Doe [1]`. What do you think?

**Comment by LiHaoTan** [comment]
I agree as well. Actually, I did have some thoughts on the tooltip and popover solution not being ideal but have not yet formed a solid idea on how to proceed.

So some of my thoughts are as follows:

Generally speaking, if two persons have the same name we would want to be able to tell them apart instantly, not go through a tooltip/popover to differentiate them.

Furthermore, if we do differentiate them based on fields such as emails, depending on the email address it can be hard to tell at a glance who the person is even if we are able to differentiate them.

There is also a subtle but yet important problem on whether there is a need to have extra clutter (e.g. info box), or require extra clicks (e.g. tooltip/popover) for identifying two persons, when it is clear that we always want to be able to tell who those people are, and to do that quickly.

Hence, I think it might be better to differentiate people at the name level, e.g. there are two Johns (ignoring the full name situation because a similar argument applies). Then an instructor may call one John and the other Johnny, or one as J1 or J2, or sometimes use visual cues to identify them separately. However, all these require context and there seems to be no nice way for TEAMMATES to generate a unique name for each of them that includes the context.

If we don't make use of the context, identifying the persons with the same name may become troublesome and it seems that there is no need for that given that there is a  workaround of instructors disambiguating the names manually, which while manual allow them to add the context themselves.

I think the manual approach offers the most ideal experience that I can think of right now, and I think following that we should tackle this issue properly rather than an iterative solution that falls short of the manual workaround.

I'm not sure but perhaps the issue should switch focus onto how to make the user add context for users with the same names, e.g. detecting duplicates and informing them (not sure yet if we should disallow duplicate names altogether).

**Comment by eei34** [comment]
@damithc In regards to not allowing a instructor to enroll two students with the same name, in this scenario would it be better to then require a middle name or initial?

**Comment by damithc** [comment]
> @damithc In regards to not allowing a instructor to enroll two students with the same name, in this scenario would it be better to then require a middle name or initial?

I don't think we can be specific like that. It's quite possible for the entire name to be identical, especially Chinese names. It is up to the instructor to somehow make each name unique by using initials, middle names, a different order of names, etc.

**Pull request closed without merging**
