### PR TITLE
[#11341] Update example box spacing #11342

### PR DESCRIPTION
**Pull request by harshal43**
Hi,
Issue - [#11341] Update example box spacing #11342
I had added a margin on top.
This was my very first issue solved fixed #11342

### CODE REVIEW

**Comment by harshal43** [comment]
Hi,
Issue - [#11341] Update example box spacing #11342
I had added a margin on top.
This was my very first issue solved fixed #11342

**Comment by jianhandev** [comment]
Hi @harshal43 this issue is already worked on by @xinyee20 in another PR. If you are looking for new first-timer issues to work on, please head over to the Github Issues page. 

Screenshot 2021-08-09 at 7 05 12 PM

**Comment by harshal43** [comment]
> Hi @harshal43 this issue is already worked on by @xinyee20 in another PR. If you are looking for new first-timer issues to work on, please head over to the Github Issues page.
> 
> Screenshot 2021-08-09 at 7 05 12 PM

Thank you very much @jianhandev this is very helpful, I am new to this so facing little difficultes.

**Comment by moziliar** [comment]
Close due to existing duplicate fix. Should that fix become inactive, do feel free to open this up again:)

**Pull request closed without merging**
