### PR TITLE
Instructor edit questions: show spinner while loading visibility preview #5996

### LINKED ISSUE #5996: Instructor: edit question: show spinner while loading visibility preview
It's best if we show the spinner while loading the updated visibility preview.

### PR DESCRIPTION
**Pull request by SmokinClove**
Fixes #5996 

**Outline of Solution**

Added a spinner in visibilityOptions.js just before ajax call, by appending a child to the visibilityMessage div.
When the ajax is completed, the visibility preview is reloaded thus removing the spinner automatically.

### CODE REVIEW

**Comment by damithc** [comment]
@SmokinClove let us know when ready for review

**Comment by damithc** [comment]
Can you also post a screen shot or an animated gif showing how the feature works?

**Comment by SmokinClove** [comment]
Sorry for late reply, had a few interviews the last few days.
Hmm i see, thanks for pointing it out. I better understand how the methods use this now.
Not a very important point but I was not sure I'd be comfortable using hard coded values since if there are a few methods in the same file using the same gif and the gif were to change (which is unlikely), we will need to manually change all the functions.
But of course to maintain consistency, I might as well use this if the other files are doing similarly (I failed to check the file you mentioned before attempting this).

**Comment by li-kai** [comment]
@SmokinClove Yes your principles of engineering is solid. However, the spinner is an UI element, where consistency is valued over flexibility. Using the same gif is the whole intent 😄. 

Although we prob should move that string to a constant (see #3975), its ok to do this here and clean it up in one sweep.

**Comment by SmokinClove** [comment]
Oh I see there is already an issue to do it!
I will make the changes when I get home tonight. Sorry about all the delay.

**Comment by SmokinClove** [comment]
@li-kai I have made changes as you requested. Note that the spinner is aligned on the left, not center.

**Comment by li-kai** [comment]
The change looks fine, but it seems you may have roped in some other commits. I'd do this if I were you.
```
git checkout master
// modify the relevant js file
git branch -D 5996-instructor-edit-questions-show-spinner
git branch -b 5996-instructor-edit-questions-show-spinner
// add and commit
git push -f // rewrite history
```

**Comment by damithc** [comment]
Closing due to inactivity. @SmokinClove please reopen when ready to continue

**Pull request closed without merging**
