### PR TITLE
EmailGeneratorTest failing on dev server #5992

### LINKED ISSUE #5992: EmailGeneratorTest failing on dev server
Looks like an issue with Win/Unix line ending incompatibility.
image

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5992

### CODE REVIEW

**Comment by JosephineKwa** [comment]
Hm the test still fails on my Windows laptop, the line endings still seem to be LF only on specific lines of the html template
lineendings

lineendings2

**Comment by wkurniawan07** [comment]
@JosephineKwa I think you followed what I suggested in [here](https://github.com/TEAMMATES/teammates/pull/5934#issuecomment-237874834)? If so, you need to repeat it again. The expected HTML should have uniform line ending instead of what's currently observed.

**Comment by JosephineKwa** [comment]
Oh my bad, yup it works then!

**Comment by damithc** [comment]
Sorry for the delay. Ping me if I don't respond in a couple of days.

**Pull request merged**
