### PR TITLE
InstructorAttributes: remove HTML sanitization before saving for name #7787

### LINKED ISSUE #7787: InstructorAttributes: remove HTML sanitization before saving for name
As per #4699, sanitization of name will be performed during rendering if required.

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #7787
Removal of html sanitization before saving the name of instructor.

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
Status ongoing

**Comment by shaharyar-shamshi** [comment]
@xpdavid Sir I am continously getting the unhandled error (first time I am getting such type of error that to in 4 test case) Can you guide me how to solve such error I am continously trying but not able to get an idea to solve it . You can just guide me for 1 test case other I can do it myself I will be thankful to you for this

**Comment by xpdavid** [comment]
```
org.gradle.internal.serialize.PlaceholderException: Unexpected modal dialog (text: hi!): hi!
```
The instructor's name in test data is `xxx<script>alert('hi')</script>`. The error indicates that the page have unexpected alert `hi`, which means that the instructor's name is not correctly sanitized.

**Comment by xpdavid** [comment]
Closed due to inactivity. Fell free to re-open it if there any updates. @shaharyar-shamshi

**Pull request closed without merging**
