### PR TITLE
[#12588] Improve test code coverage of QuestionResponsePanelComponent

### PR DESCRIPTION
**Pull request by leyguan**
Part of #12588

**Outline of Solution**

 
I added a few tests to cover the uncovered code.
I tried to cover everything. It's ready for review. 
I only fix the test for one component, so I use the description "Part of #12588".

### CODE REVIEW

**Comment by leyguan** [comment]
It seems I mistakenly add an unexpected file `lint-output` I used to test locally. How should I fix this?

**Comment by Andy-W-Developer** [comment]
Make a copy of the entire folder first just in case.

Then give this command a try:
`git rm --cached`

Commit and push like a regular commit.

**Comment by leyguan** [comment]
I have removed the unnecessary file and it's ready for review.

**Review by cedricongjh — CHANGES_REQUESTED** [review]
test cases LGTM, could I trouble you to add the method that is being tested in the test string e.g. it('canUserSeeResponse: should allow instructors to see responses when intent is INSTRUCTOR_RESULT'), this is something we are doing for newly added test cases as it makes it easier for future developers to see exactly which method is being tested

**Comment by leyguan** [comment]
I only added tested methods for the newly created tests. Or do I need to add for all of them?

**Pull request merged**
