### PR TITLE
[#10805] Browse by topic listing comes over the text (fix padding)

### LINKED ISSUE #10805: Browse by topic listing comes over the text
[Help for instructions page][small screen mode]Browse my topic listing comes over the text

LIVE TEAMMATES V7.3.1

Steps to reproduce
1. Go to this page: https://teammatesv4.appspot.com/web/front/help/instructor
2. Reduce the size of the browser

Expected results:
Browse by topics words should not overlap with the info text

Actual results:
Browse by topics words overlaps with the info text

SCREENSHOT attached!

Screenshot 2020-10-23 at 15 54 53

### PR DESCRIPTION
**Pull request by jianhandev**
Fixes #10805 

Resolved 2 UI issues in the instructor help page, they are described below:

Issue 1 - Browse by topic listing side nav overlaps main body
Solution: Added a media query to hide the browse by topic listing side nav when browser width is below 480px.

Issue 2 - Empty right-hand-side padding (a by-product from fixing issue 1)
Solution: Added a media query to remove the extra padding in the flex container.

Screenshot of before (notice the big gap on the right hand side causing the the main body content to be compressed):

Screenshot 2020-12-10 at 4 
08 17 PM

After (the main content body stretches out to the full width of the browser window):

ezgif-3-ad02df607551

### CODE REVIEW

**Comment by rrtheonlyone** [comment]
Thanks for your contribution! Changes looks good

Any reason you created a new scss file instead of adding to `instructor-help-page.component.scss`?

**Comment by jianhandev** [comment]
> Thanks for your contribution! Changes looks good
> 
> Any reason you created a new scss file instead of adding to `instructor-help-page.component.scss`?

I could achieve the same result by forcefully overriding the `padding-right` property of the `flex-property` class using `!important`. In that case, no new file is needed. However, I learnt that the use of `!important` should be avoided whenever possible and is not the best way to deal with CSS specificity. My workaround is to create a new scss file that is loaded after the main scss file, so that it will override the `padding-right`property successfully in the media queries.

**Comment by rrtheonlyone** [comment]
>  However, I learnt that the use of !important should be avoided whenever possible

Yes you are correct in this.

However, in our case we can simply put the media query at the very end of the current scss file and there would be no need to use `!important`. This is because media queries do not change the specificity of your selectors. When you have two selectors with the same specificity, the one appearing later in your stylesheet will override the earlier one

**Comment by jianhandev** [comment]
> However, in our case we can simply put the media query at the very end of the current scss file

You are right, that works too! I have updated the PR.

**Review by madanalogy — APPROVED** [review]
LGTM

**Review by niqiukun — APPROVED** [review]
LGTM

**Review by t-cheepeng — APPROVED** [review]
LGTM

**Comment by ChooJeremy** [comment]
Hi @jianhandev,

This solves the issue, but up till the point in which a panel with images is opened. Once a panel with images is opened, then the browse by topic hiding no longer works as the width of the main panel is significantly larger.

You can view this by opening any panel under `Questions` - `Setting Up Questions`

Screenshot 2020-12-16 at 10 24 34 AM

Are you up to solve this issue? If not, perhaps we can create a new issue for it to be solved after this is merged.

**Comment by jianhandev** [comment]
> This solves the issue, but up till the point in which a panel with images is opened. Once a panel with images is opened, then the browse by topic hiding no longer works as the width of the main panel is significantly larger.

Thanks for raising up this issue, I will look into it. 

> perhaps we can create a new issue for it to be solved after this is merged
I feel we should create a new issue for this as it is related to image scaling. If we can allow the image to scale dynamically whenever the user resizes the window, it should solve the problem.

**Comment by ChooJeremy** [comment]
> Thanks for raising up this issue, I will look into it.
> 
Awesome, feel free to post if you end up finding it too difficult at the moment and we'll merge this and create a new issue.

> I feel we should create a new issue for this as it is related to content scaling. If we can allow the content within the panel to scale dynamically whenever the user resizes the window, it would solve the problem?

That's one way to solve it, yes. Another solution would be to hide the topic listing depending on the width of the main content, where if `screen width - main content width < some value`. Or, alternatively perhaps the browse by topic listing can have some opaque background and stay regardless, that way it doesn't look too out of place with text overlapping text.

**Comment by madanalogy** [comment]
I'm a little confused @jianhandev, do you want to try working on the issue @ChooJeremy raised in this PR or have it submitted as a separate issue in the tracker?

**Comment by jianhandev** [comment]
> I'm a little confused @jianhandev, do you want to try working on the issue @ChooJeremy raised in this PR or have it submitted as a separate issue in the tracker?

Hi @madanalogy I think this problem is related to another potential UI bug related to responsive web design, so I have created a new issue here (#10885)

**Pull request merged**
