### PR TITLE
instructorCourseEditInstructor: the feedback message can mention which instructor was edited #2523

### LINKED ISSUE #2523: instructorCourseEditInstructor: the feedback message can mention which instructor was edited
Currently, it says something generic like 'the instructor has been edited'. It is more useful if the message mentions which instructor was edited.

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #2523

### CODE REVIEW

**Comment by LowWeiLin** [comment]
@belyabl9  Thank you for the pull request! InstructorCourseInstructorEditSaveActionTest seems to be failing on line 63. Do run all tests to check that all tests are passing. You can also merge the current master branch into your branch to keep it updated.

**Comment by belyabl9** [comment]
Ready to review

**Comment by damithc** [comment]
@belyabl9 can you syn this branch with upstream? Seems it is outdated.

**Comment by belyabl9** [comment]
Rebased. Ready to review

**Comment by thyageshm** [comment]
@LowWeiLin ready for merge

**Pull request merged**
