### PR TITLE
Instructor: Home Page: Sort By Date does not work as expected #7919

### LINKED ISSUE #7919: Instructor: home page: fix sort by date
Noticed while working on #1297.

On the Instructor Home Page, in the table of Sessions displayed, the sorting by date buttons do not work as expected if any one session in the list has start date or end date with a `12 NOON`time. 

This error happens because JS fails to parse this as a date object (which is essential for sorting by date to work. See the [`sortDate` comparator in `sortBy.js`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/common/sortBy.js#L83))

Since 12 NOON is the ideal way to display the time to the user, we may have to include a separate data-attribute containing the time in a format that is always JS parsable (ideally the ISO8601 format). Perhaps something like what was done in #7715. (See: [this diff](https://github.com/TEAMMATES/teammates/pull/7715/files#diff-8ed3a79a64da103b6ee4bcaa7100f0abR37)).

I'll leave it up to the senior devs to decide if the scope of this issue includes adding this datetime data attribute in ISO8601 format to all HTML elements that display date. (This might make solving #1701 easier).

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7919 

In https://github.com/TEAMMATES/teammates/issues/7919#issuecomment-322027930, @whipermr5 agreed to my suggestion that we use this issue to add ISO8601 date stamps to all the date elements of TEAMMATES. In this PR I hope that I have managed to cover all the date elements.

**Outline of Solution:**

- Added ISO8601 datestamp to the start-time in `feedbackSessionDetailsPanel` tag which, as far as I know, adds the start time of the session formatted in ISO8601 as a `data-start-time` attribute to the `studentFeedbackSubmissionEditPage`. This adds on to the work done in #7715 where I added the end time as a datestamp data attribute to the same page.

- Added the end-time date-stamp to the studentHomePage, so that each cell of the table has the data-date-stamp attribute.

- Added the data-date-stamp to the tables on the instructorHomePage (the original focus of this issue). 

- Lastly, changed the extractor in the instructorHomePage date elements to `dateStampExtractor`. This is a new extractor I have added in #7920 and this PR will make everything work as expected once that is merged.

Let me know if I missed any date elements in the App.

### CODE REVIEW

**Comment by HirdayGupta** [comment]
Dropping a note that the build failure is only because the dateStampExtractor isn't yet implemented as it is awaiting the merge of #7920. I have checked on my local machine that god mode works as intended once the extractor is added.

**Comment by HirdayGupta** [comment]
Meanwhile, other than that, this PR is ready for review.

**Comment by HirdayGupta** [comment]
@thenaesh Please review soon.

**Comment by HirdayGupta** [comment]
@thenaesh Review reminder please.

**Comment by HirdayGupta** [comment]
@thenaesh Have cleaned up and resolved conflicts and incorporated #7920 now that it's been merged. Travis build has also passed. This feature now works exactly as intended. Please review.

**Comment by HirdayGupta** [comment]
@thenaesh, Apologies, I overlooked that the sort by date on the instructor home page wasn't working. Pushed the solution to this in 154657f. (Suspicious god mode changes led me to this). Now, feature works exactly as per plan. All god mode changes are as expected too.

Requesting a review on this PR soon, please and thank you. :)

**Comment by HirdayGupta** [comment]
@thenaesh Please review.

**Comment by thenaesh** [comment]
Apologies, I've been busy with school assignments the past couple of weeks. I'll try to review by the end of this week.

**Comment by wkurniawan07** [comment]
Closing due to an inactivity for a very long period. If anyone is interested to continue the work done here, feel free to reopen/request for reopen.

**Pull request closed without merging**
