### PR TITLE
[#8532] Sessions: instructor view results: stop showing a random identifier for anonymous responses

### LINKED ISSUE #8532: FeedbackSessionResultsBundle: remove anonymous participant's hash identifier
As per #6092, we need to stop displaying the random hash in anonymised participants' name, e.g. `Anonymous student 1234567890` to `Anonymous student`. #8443 addresses this by removing the hash before data is rendered, but only for `student` view; `instructor` users can still see the trailing hash and could trace the anonymised student. Ideally, we should remove the hash completely from `FeedbackSessionResultsBundle`.

### PR DESCRIPTION
**Pull request by halfwhole**
Part of #8532

**Outline of Solution**

The hash has been removed from the anonymised name, leaving only strings such as 'Anonymous student' for display.

Before:
anonymous-before

After:
anonymous-after

I've tried to be careful in removing all the remaining references, here's hoping that it works out well.

### CODE REVIEW

**Comment by damithc** [comment]
Guys, any update on this PR?

**Comment by rrtheonlyone** [comment]
Good attempt here! However, this is not quite enough. 

A simple way to break this is to switch the view.

Switch to view `Group by - Recipient → Giver → Question`, you should see something like this with the hashes:

Screenshot 2020-12-28 at 6 57 20 PM

As you can see, we use the hashes to differentiate between different responses on the frontend. Now without that, it will not be able to do that anymore and the frontend logic will break. In order to properly remove the hashes, we might have to rewrite the API to send grouped data instead for the different views.

**Comment by halfwhole** [comment]
I've managed to fix the previously mentioned issue without making any changes to the API, by changing only small parts of the frontend code. Would this approach work just as well?

The frontend logic should work just the same when the students' names are unique. However, when students of the same name (e.g. "Anonymous student") separately give different responses, their responses can now be distinguished.

teammates

For the above example with the `Group by - Recipient → Giver → Question` view, previously the frontend would wrongly show the "a->bc" response 3 times. Now it shows the correct responses. I've also tried it out with other views, and now they look correct also.

A drawback of this approach is that different anonymous students will still be grouped under the same single category of "Anonymous student" by the frontend, but this solution seems much more simple compared to changing the API entirely to allow for grouping.

**Comment by rrtheonlyone** [comment]
Right now this method looks to work - but it makes the result panel a lot harder to interpret. All responses for every question will now be grouped as one entity - 'Anonymous Student'. 

In fact, I am wondering if there is a real need for this much processing in the first place. 

Why don't we just retain existing functionality and just remove the hash when showing in the HTML? The number is encrypted so the instructor is unlikely to be able to trace the student who gave that response even if he gets hold of it from the HTML response. 

Even for the current solution above, even though the hash is removed from the name, there is a unique ID attached to each feedback response (that's why the comments feature still works for each response). 

Tagging: @damithc , @wkurniawan07 , @xpdavid for further opinion on this PR/issue.

**Comment by damithc** [comment]
> Why don't we just retain existing functionality and just remove the hash when showing in the HTML? The number is encrypted so the instructor is unlikely to be able to trace the student who gave that response even if he gets hold of it from the API response.

I'm OK with that.

**Comment by halfwhole** [comment]
Sure, I can work with this method.

**Comment by madanalogy** [comment]
Sorry I missed out on this PR, I don't agree with having this managed solely on the frontend actually. Might as well not remove the hash as it's still available in the API response. Even though the name is first encrypted, the hash can be used in cross validation with other sessions/responses to aid in de-anonymising data. Something I learnt in my computer security module haha

The original issue filed makes it clear what needs to be done:

>  Ideally, we should remove the hash completely from `FeedbackSessionResultsBundle`

Since the issue was filed, the data bundle has been renamed to `SessionResultsBundle`. Even in the worst case assuming that removing the hash completely is not feasible, we can just as easily remove the hash when crafting the response. There is already a removal of hash function in `SessionResultsData` for responses sent out to students, should be easy enough to replicate for instructors.

The issue then becomes how to display anonymised responses in the frontend, but I believe that's already resolved from what I'm seeing in the screenshots.

**Review by madanalogy — CHANGES_REQUESTED** [review]
Sorry I missed out on this PR, I don't agree with having this managed solely on the frontend actually. Might as well not remove the hash as it's still available in the API response. Even though the name is first encrypted, the hash can be used in cross validation with other sessions/responses to aid in de-anonymising data. Something I learnt in my computer security module haha

The original issue filed makes it clear what needs to be done:

>  Ideally, we should remove the hash completely from `FeedbackSessionResultsBundle`

Since the issue was filed, the data bundle has been renamed to `SessionResultsBundle`. Even in the worst case assuming that removing the hash completely is not feasible, we can just as easily remove the hash when crafting the response. There is already a removal of hash function in `SessionResultsData` for responses sent out to students, should be easy enough to replicate for instructors.

The issue then becomes how to display anonymised responses in the frontend, but I believe that's already resolved from what I'm seeing in the screenshots.

**Comment by madanalogy** [comment]
@halfwhole after further consideration, we can go ahead with the implementation you have here. Just that your solution will be counted as "Part of" the issue and it will remain open

**Review by madanalogy — APPROVED** [review]

**Comment by madanalogy** [comment]
@halfwhole I'll put this on hold actually until you've had the chance to take a look at my comments. Let me know if you are okay proceeding to resolve this PR or if you'd rather try again for a backend solution.

**Comment by halfwhole** [comment]
Yup agree that the current purely frontend solution can be helpful, but is incomplete because the hash is still accessible via API.

If we intend to fully go for a backend solution though, we would probably run into the same issue as before. The first solution I had was already a purely backend approach: it removed the anonymous hash from `SessionResultsBundle` entirely, which is feasible, so the API returned all student names as 'Anonymous student'. That led to some frontend errors on the `grq-rgq` views though because it bugs out when it receives multiple responses under the same name, so I added a bit of frontend code to solve that. But that doesn't resolve the issue of grouping, because the frontend still has no way of distinguishing between responses when all of them are called 'Anonymous student', so it groups them all together under the same name (as in the most recent screenshot).

Reviewing that solution now, personally I think that grouping all responses under 'Anonymous student' should be OK (?), because we probably don't intend to distinguish between the students anyway under the condition of anonymity, and it doesn't look too confusing, at least to me?

But if we do want to want to distinguish these responses, there might still be a way. Could the frontend not simply break up all the responses under 'Anonymous student' (as in the most recent screenshot) into multiple groups of 1? If each anonymous student is limited to 1 response per question per recipient in the `grq-rgq` views (correct me if I'm wrong!), then each grouping on the frontend must consist of 1 and only 1 response, so we can just separate them.

If we intend to go with that, then the current solution would be obsolete.

**Comment by madanalogy** [comment]
There might be a way to figure out the frontend issue. Either with what you suggested or by replacing the frontend UI logic entirely to use a different key maybe? I'm not exactly sure right now either. Regardless, there's a lot of work that will have to go into resolving this issue, which you might not have the capacity for right now considering that your focus is on the audit logs project. What I recommend is choosing between: 
1. Having this PR merged now as it is, but leave the issue open for further development by someone else (could be you) down the road eventually; or
2. Having this PR remain opened and on hold indefinitely until you find the time to develop the more comprehensive approach; or
3. Closing this PR, but still be able to claim credit for work done towards 3281 since it has been approved

Let me know which direction you want to take this PR, and I'll help accordingly.

**Comment by halfwhole** [comment]
Perhaps the first option is best? I'd like to still attempt figuring something out eventually, but for now the current solution can still be helpful in removing the hash, even if only on the frontend

**Pull request merged**
