### PR TITLE
Add new rules to Checkstyle-Empty line separator

### PR DESCRIPTION
**Pull request by JosephineKwa**
Added empty line separator rule

Checks that there is an empty line after header, package, all import declarations, constructors, methods, nested classes, static initializers and instance initializers. Excludes enum declaration and variable declaration. Also checks that there are no multiple (>1) consecutive empty lines.

### CODE REVIEW

**Comment by kanghj** [comment]
Personally, I find preventing multiple consecutive empty lines a bit unnecessary.

**Comment by damithc** [comment]
Yes, sometimes having two blank lines can be useful, but may be 3 is too many? Is there a way to specify the number of allowed blank lines?

**Comment by JosephineKwa** [comment]
I don't think its possible to configure the number of lines using the provided properties of this check in the checkstyle xml file, however it might be possible to extend the check and write a custom one.

**Comment by JosephineKwa** [comment]
@damithc do I allow multiple consecutive lines?

**Comment by damithc** [comment]
Let's disallow it and see how it goes. We should give the rule a try before deciding to break it.

**Pull request merged**
