### PR TITLE
[#12064] Add back per criterion averages to the stat table

### LINKED ISSUE #12064: Instructor viewing rubric question results: add back per criterion averages to the stat table
current version: v8.22

In v8.19, the rubric question results were shown like this:

image

Note how we show a list of averages for each criterion for each student.

In https://github.com/TEAMMATES/teammates/issues/11210 we tweaked the results display format which resulted in this column being removed.

A user wrote to us today to explain that she used this column. Specifically, she would look through these numbers and decide on a score for the student based on how the student scored for each criterion.

Suggestion: Add that column back to the relevant stats table. The values can be copied from the `Per criterion` table. We can name it `Per criterion averages`. In the csv file, each value can be put in a separate cell so that users can easily perform more analysis on them.

### PR DESCRIPTION
**Pull request by tjex**
Fixes #12064 

**PR Checklist**

Note:   
`gradle lint failed` as standard on a fresh clone. Not sure if it's because of my system or the build. 
Cannot trust a test therefore on my machine. Fixing the linting goes beyond the scope of this feature request.

`npm run lint` = "all files pass linting"

**Outline of Solution**

Added a column at the end the `Per Recipients Statistics (Overall)` table in the rubric results view.
Retrieved `subQuestionWeightAverage` and input parsed into string, to present in the respective cell in the table.

### CODE REVIEW

**Comment by tjex** [comment]
Hi guys. We've noticed the failing tests and are addressing them. Converting this PR to a draft then for now. Should be done in the coming days!

**Comment by tjex** [comment]
We're really not sure how to go about solving the E2E failing tests. This occurs for us in the updated master branch as well as our feature branch. 

I get this output:

```
> Task :e2eTestTry2 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':e2eTestTry2' (type 'Test').
  - Gradle detected a problem with the following location: '/Users/tillman/t-root/ctech/KTH/FSE/proj5/teammates/build/reports/e2e-test-try-1/testng-failed.xml'.

    Reason: Task ':e2eTestTry2' uses this output of task ':e2eTestTry1' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':e2eTestTry1' as an input of ':e2eTestTry2'.
      2. Declare an explicit dependency on ':e2eTestTry1' from ':e2eTestTry2' using Task#dependsOn.
      3. Declare an explicit dependency on ':e2eTestTry1' from ':e2eTestTry2' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
6 actionable tasks: 1 executed, 5 up-to-date
```

The suggestions in the error log are also a 'dead end', as in the `testng-failed.xml` I cannot find any task ':e2eTestTry2'. 
Will keep trying, but feel as though it's beyond our scope of capabilities unfortunately to solve it.

**Comment by wkurniawan07** [comment]
This is a known problem if you are using Gradle 8. You should not face this problem if you are running the command with `./gradlew` instead of, if I may presume, just `gradle` (the latter uses your locally installed Gradle instead of the wrapper within this repository).
Nevertheless, if the E2E tests pass in the GitHub Actions run (sometimes it takes a few retries, again this is a known problem #12035), there is no need to worry.

**Comment by weiquu** [comment]
Hi @tjex, thanks for the fix (: It looks good, just one small nit: in the CSV file downloaded, there seems to be a `Per Criterion Average` column in the `Per Recipient Statistics (Per Criterion)`, which I think is redundant? Since the average is the same as the per criterion average. Example below:
Screenshot 2023-03-06 at 3 15 48 PM

Would be good to remove this extra column if it's really not needed!

**Comment by tjex** [comment]
ups, nice catch. Thanks. The column is removed now 👍

**Comment by weiquu** [comment]
Looks good, thanks! Think the `angular.json` file shouldn't be merged though (: Pinging @zhaojj2209 / @samuelfangjw

**Comment by zhaojj2209** [comment]
> Looks good, thanks! Think the `angular.json` file shouldn't be merged though (:

Actually, now's a good time for us to just disable analytics altogether so that we won't have to keep removing changes like these for future PRs. @tjex No need to revert `angular.json`, do fix the failing snapshot tests though.

**Comment by damithc** [comment]
@tjex have you added back the missing column to the csv file as well? I don't remember the values in that table in concern also appears in the csv file, but if it does, then a similar change need to be done to the csv file as well.

**Comment by tjex** [comment]
Ahh sorry about the angular.json. My git shortcut adds all changes, and as it was a quick change I didn't `git status` first to check...

> @tjex have you added back the missing column to the csv file as well? I don't remember the values in that table in concern also appears in the csv file, but if it does, then a similar change need to be done to the csv file as well.

do you mean the file which you ask for in the issue? 
> In https://github.com/TEAMMATES/teammates/issues/11210 we tweaked the results display format which resulted in this column being removed.

That column is back in the csv as well. Here is the latest export.
[123_test2_result.csv](https://github.com/TEAMMATES/teammates/files/10897837/123_test2_result.csv)

**Review by weiquu — APPROVED** [review]
LGTM

**Review by samuelfangjw — APPROVED** [review]

**Pull request merged**
