### PR TITLE
 Instructor home page: Show year as a tooltip of start/end time #5742 

### LINKED ISSUE #5742: Instructor home page: Show year as a tooltip of start/end time
As the year is not shown at all, it's hard to see when the course was held.
I thought we had this feature already (may be we had it and lost it due to a regression?)
image

Or perhaps we can show the duration `[earliest start time - latest end time]` on the panel header center?

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #5742

### CODE REVIEW

**Comment by chowyb** [comment]
Current UI:

time

We might have to add a `<span>` element to this if the fix in #5761 remains unchanged, but as that PR is still pending review it's okay to leave this as it is for now, and update it once that PR is finalised.

**Comment by chowyb** [comment]
Edited typo in issue and PR title

**Comment by wkurniawan07** [comment]
@rclakmal is this ready for review?

**Comment by rclakmal** [comment]
@wkurniawan07 As @chowyb pointed out may be it's a good idea to wait until #5761 is finalized. There are few changes it requested for that PR, I will finalize it soon.

**Comment by rclakmal** [comment]
@chowyb Added the span element. Once #5761 is merged, this could be tested out.

**Comment by rclakmal** [comment]
Since 5696 is good to merge, this is now ready to review.

**Comment by rclakmal** [comment]
@wkurniawan07 @chowyb This needs status change toReview.

**Comment by chowyb** [comment]
@rclakmal good to go!

**Comment by damithc** [comment]
@wkurniawan07 this library needs to be added into dev docs right?

**Comment by wkurniawan07** [comment]
@rclakmal the fix for the HTML files are no longer compatible due to #5761 being merged first. Can you sync with the `master` branch and do the necessary fixes before this can be merged?

**Comment by rclakmal** [comment]
@wkurniawan07 Done :)

**Pull request merged**
