### PR TITLE
Cancelling edits for comments does not revert visibility checkboxes #5653

### LINKED ISSUE #5653: Instructor: view results: edit and add comment: revert visibility checkboxes and comment text when canceling edits
When cancelling an edit being made to a comment, or when adding a new comment, the visibility checkboxes and text are not reverted. Therefore, it is possible to cancel an edit on a comment, and edit the comment again, resulting in the form being filled in with data that has already been modified.

### PR DESCRIPTION
**Pull request by srikanthnt**
Fixes #5653

### CODE REVIEW

**Comment by damithc** [comment]
@srikanthnt let us know when this is ready for review.

**Comment by wkurniawan07** [comment]
Hi @srikanthnt, any updates on this PR?

**Comment by srikanthnt** [comment]
I am working on it

**Comment by junhaoyap** [comment]
Hmm there is something amiss here - there seems to be some of @chowyb's changes here?

**Comment by wkurniawan07** [comment]
Hi @srikanthnt, any updates on this PR?
Also, as @junhaoyap mentioned, it seems like you are cherry-picking @chowyb's previous work verbatim. May I ask if you understand what is being done in the changes, and if they are sufficient to resolve the issue being addressed?

**Comment by wkurniawan07** [comment]
Closing due to inactivity.

**Pull request closed without merging**
