### PR TITLE
Set up AppVeyor to run tests on Windows #6238

### LINKED ISSUE #6009: InstructorFeedbackEditPageUiTest failing on staging/live server
Originally #5993. Stack trace:

```
java.lang.AssertionError: Expected the receiving student to be able to see response, but was 
    at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
    at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
    at teammates.test.cases.BaseTestCase.assertTrue(BaseTestCase.java:160)
    at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.testEditQuestionAction(InstructorFeedbackEditPageUiTest.java:330)
    at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.testGeneralQuestionOperations(InstructorFeedbackEditPageUiTest.java:101)
    at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.allTests(InstructorFeedbackEditPageUiTest.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
```

### LINKED ISSUE #6179: Potential bug between AJAX call and waitForElementVisibility in test cases
Hello, I am a new contributor and I currently keep failing the test case 'teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest' for 'staging test' against my server 'https://teammates-xiaopu.appspot.com/'.
screen shot 2016-11-30 at 2 21 35 am
I find a possible reason for this.
In `teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest`, the test case clicks the visibility option by using `feedbackEditPage.enableOtherVisibilityOptions(2);` and checks whether the visibility message is updated or not. When the option is clicked, AJAX request is sent to the server. The test case tries to use `waitForElementVisibility` to wait  the AJAX call, but it doesn't actually wait (reason below) and `visibilityMessage2.getText()` gets empty message (or message not updated by AJAX) thus the test cases fail.
``` java
feedbackEditPage.enableOtherVisibilityOptions(2);
// ...
WebElement visibilityMessage2 = browser.driver.findElement(By.id("visibilityMessage-2"));
feedbackEditPage.waitForElementVisibility(visibilityMessage2);

assertTrue("Expected the receiving student to be able to see response, but was "
                   + visibilityMessage2.getText(), visibilityMessage2.getText()
                   .contains("The receiving student can see your response, and your name."));
// ...
```
I think `feedbackEditPage.waitForElementVisibility(visibilityMessage2);` will always return true **when the page is loaded, visibility option is clicked after the loading**. The server renders the `div` element when page is loaded.
``` html
// `src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionVisibilityOptions.tag`
// ...
    <!-- Fix for collapsing margin problem. Reference: http://stackoverflow.com/questions/6204670 -->
    <div class="col-sm-12 visibilityMessage overflow-hidden" id="visibilityMessage-${fqForm.questionIndex}"> // here
        This is the visibility hint as seen by the feedback giver:
        <ul class="text-muted background-color-warning">
        <c:forEach items="${fqForm.visibilitySettings.visibilityMessages}" var="msg">
            <li>${msg}</li>
        </c:forEach>
        </ul>
    </div>
// ...
```
When doing AJAX request, the script **finds the div** to update the message.
``` javascript
// `src/main/webapp/js/instructorFeedbackEdit.js`
/**
 * Updates the visibility message div according to configurations in the
 * visibility checkboxes div (using AJAX)
 * @param $containingForm
 */
function updateVisibilityMessageDiv($containingForm) {
    // ...
    var formData = $containingForm.serialize();
    var $visibilityMessageDiv = $containingForm.find('.visibilityMessage'); // here
    // ...    
    $.ajax({
        // ...
    });
}
```
Thus, no matter the AJAX call complete or not, the `feedbackEditPage.waitForElementVisibility(visibilityMessage2);` will always return true.

Whether the test case fails or not actually depends on the speed of the server. If the server gives quick response to AJAX request, then `visibilityMessage2.getText()` would get correct data.

But I would like to point out this is a existing potential "bug" for test case, and I believe this may not be the only test case that has this issue. So I think for better testing, a mechanism need to be provided to wait for AJAX request in test cases.

### LINKED ISSUE #6238: Set up AppVeyor to run tests on Windows
Travis can be our primary CI because the live server is a Unix box.
However, many of our devs are using Windows and running CI on AppVeyor (in parallel to Travis) can help detect Windows specific test failures.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6238. The third commit also fixes #6179 and fixes #6009.

I'm not sure from which branch the badge pulls the status from, although this is just a minor edit if needed.

Also, I do not include the static analysis tools here (let Travis do the job) but easy to include if needed.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Seems like there is another unstable test that I haven't remedied :/
But do feel free to review what's already here.

**Comment by wkurniawan07** [comment]
Looks reasonably stable now. @damithc can review again.

**Comment by wkurniawan07** [comment]
Seems like we're not ready for AV in PRs. There are still some unstable tests coming from time to time (more unstable than they are in Travis), and the velocity we sustain for the past weeks will make AV a bottleneck.
Perhaps it's best to keep AV for `master` and `release` only for the time being. That way we still have a certificate that "everything works in Windows".

**Comment by damithc** [comment]
> Perhaps it's best to keep AV for master and release only for the time being. That way we still have a certificate that "everything works in Windows".

Sure, let's do that.

**Pull request merged**
