### PR TITLE
instructor add session: closing time text box gives an NaaN error on Safari #4950

### LINKED ISSUE #4950: instructor add session: closing time text box gives an NaaN error on Safari
Reported by user
image

### PR DESCRIPTION
**Pull request by Gisonrg**
Fixes #4950 

Detail reason could be found at [here](https://github.com/TEAMMATES/teammates/issues/4950#issuecomment-194369745)

### CODE REVIEW

**Comment by Gisonrg** [comment]
screen shot 2016-03-10 at 12 47 31
Bug found. It is because of different behavior of handling invalid date. In the screenshot, above is Chrome and it can correctly tell an invalid date. The below is Safari, it will still parse the date, even if the date is invalid but it is still a Date object.

**Comment by junhaoyap** [comment]
Will take a look in ~8 hours after work

**Comment by junhaoyap** [comment]
@Gisonrg awesome job on finding the problem and explanation - you could also submit a bug report to Apple :+1:

**Comment by Gisonrg** [comment]
@junhaoyap Haha thanks. Yea, probably should file a bug report and let Apple know that :stuck_out_tongue:

**Comment by junhaoyap** [comment]
@Gisonrg I merged this for ya! Do remember to file a report to Apple if you can :p

**Comment by Gisonrg** [comment]
@junhaoyap I have submitted the bug report to Apple. Let's see how they reply :D

**Pull request merged**
