### PR TITLE
AboutUs page: make the list numbering continuous #6588

### LINKED ISSUE #6588: AboutUs page: make the list numbering continuous
See screenshot below. Instead of restarting the numbering from 1, make it continue from the previous list.

image

### PR DESCRIPTION
**Pull request by karthikaacharya**
Fixes #6588

### CODE REVIEW

**Comment by karthikaacharya** [comment]
@AnaghHegde 
screen

**Comment by karthikaacharya** [comment]
can I request for s.ToMerge?

**Comment by AnaghHegde** [comment]
@karthikaacharya Your PR has conflict. First resolve it. When the review is done(completely) it will be changed to `s.ToMerge`. Mos OSS projects are handled by people who will have other daily jobs/works or sometimes students. So please wait for sometime. At present what you can do is **resolve the conflicts**(it's not like an option you have to do it).

**Comment by karthikaacharya** [comment]
Ok.

**Comment by wkurniawan07** [comment]
@karthikaacharya, I apologize, but the team has decided against doing what the issue originally was about. Thanks for your contribution! If you'd like, we will include your name in our contributors' list.

**Comment by damithc** [comment]
> Thanks for your contribution! If you'd like, we will include your name in our contributors' list.

Yes, let's include @karthikaacharya in our contributors list as the work was done although we didn't merge it.

**Comment by karthikaacharya** [comment]
@wkurniawan07, yes I would love to include in your contributors list.Thank you.

**Pull request closed without merging**
