### PR TITLE
[#11993] Diagrams in the developer documentation are not being displayed

### LINKED ISSUE #11993: Diagrams in the developer documentation are not being displayed
Most diagrams [here](https://teammates.github.io/teammates/design.html) are not being displayed due to syntax errors.

Screenshot

### PR DESCRIPTION
**Pull request by tenebrius1**
Fixes #11993

**Outline of Solution**
Fixed the path issue of `style.puml`. Below is a screenshot of the local deployment of the fixed developer docs page. I have gone  through the a local deploytment of the development documentation and have not found any other pages with diagrams not showing up, but please do let me know if you find any!

Web capture_2-12-2022_1672_127 0 0 1

### CODE REVIEW

**Comment by damithc** [comment]
@tenebrius1 is this PR ready for review?
@TEAMMATES/active-mentors let's merge this PR soon as it is important to keep the dev docs unbroken.

**Comment by tenebrius1** [comment]
@damithc Yes prof, this PR is ready for review.

**Review by fans2619 — APPROVED** [review]
LGTM. I did a local deployment and the changes are effective.

**Review by zhaojj2209 — APPROVED** [review]
LGTM, tested locally.

**Pull request merged**
