### PR TITLE
[#10508] Instructor courses page: some items don't show spinners

### LINKED ISSUE #10508: Instructor courses page: some items don't show spinners
Current: The courses page has three tables that seem to load independently of each other. However, only one spinner is shown.
image

Suggestion: Add a spinner for each.

### PR DESCRIPTION
**Pull request by rexong**
Fixes #10508 

**Outline of Solution**
1. I added alerts for both Archive and Deleted Courses tables on Courses Page and displays them when there are no archive or deleted courses. 
image
2. I added spinners for Archive and Deleted Courses Tables when the page is still fetching the data. 
3. I also changed the layout of the Active Courses Table to show the table name `Active Courses` while displaying the spinner. 

image

https://github.com/TEAMMATES/teammates/assets/66376253/3ec984dd-3444-4b98-94f2-d50f150f02ac

### CODE REVIEW

**Review by weiquu — COMMENTED** [review]
Hi @rexong, looks great (: Only one small nit: could you change `isLoadingSoftDeleteCourses` to <code>isLoadingSoftDelete**d**Courses</code>? I think this is more consistent with the other `Loading` variables like `isLoadingArchivedCourses` as well as variables such as `softDeletedCourses` and `softDeletedCourse`

**Comment by rexong** [comment]
Can I check if there is any updates on the E2E Test? I cant seem to pass the E2E test but not sure why.

**Comment by weiquu** [comment]
> Can I check if there is any updates on the E2E Test? I cant seem to pass the E2E test but not sure why.

I've just merged in a PR that fixes this issue - once you update your branch (and the branch for your other PR), it should be fine

**Comment by rexong** [comment]
I have updated my branch and made the relevant changes. Ready for review.

**Review by weiquu — APPROVED** [review]
LGTM!

**Comment by rexong** [comment]
Hello, I think this PR still requires another review? Thank you!

**Review by jasonqiu212 — APPROVED** [review]
LGTM!

**Pull request merged**
