### PR TITLE
[#11853] Add stricter checks for potentially destructive question edits

### LINKED ISSUE #11853: Warning message for potentially destructive edits of questions not shown under specific conditions
- **Environment**: v8.16.1

**Steps to reproduce**
1) Open the edit session page of an open session as instructor. The session currently has no responses.
2) Student responds to feedback question and submits their response.
3) Instructor makes a destructive edit (without refreshing the edit page). For example, changing visibility, or changing options of mcq question.

**Expected behaviour**
Modal with warnings should still be shown

**Actual behaviour**
Responses are deleted without any warning

**Additional info**
Warnings are skipped because of an additional check for whether there are any existing responses.
https://github.com/TEAMMATES/teammates/blob/2fc791c1befbd1ed529556416c827171452ce593/src/web/app/components/question-edit-form/question-edit-form.component.ts#L284
However, `isQuestionHasResponses` is not updated between the time the instructor first loads the page and the time when the edited question is saved.

While this is unlikely, it is not implausible. For example, imagine an instructor who does not have the habit of closing tabs. He is informed of a minor typo in MCQ question at the start of the session, and proceeds to correct it resulting in the above situation (past responses being deleted silently).

**Suggestion**
Add stricter checks for whether a session is already opened (there might be potential responses). If not possible, I believe the benefit of removing this check (potential silent deletion of responses) outweighs any potential minor annoyance to instructors.

### PR DESCRIPTION
**Pull request by cedricongjh**
Fixes #11853 

**Outline of Solution**

Added a check to make sure that if the question is in a session that is published, we show the warning message when the user makes edits.

### CODE REVIEW

**Comment by zhaojj2209** [comment]
`InstructorFeedbackEditPageE2ETest` is failing consistently; seems that it might be failing not because of E2E test instability but because of changes made in this PR. Do investigate further and let me know if you run into any issues debugging E2E tests.

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

E2E tests now pass, so they probably failed previously due to stability issues.

**Review by hhdqirui — APPROVED** [review]
LGTM!

**Review by samuelfangjw — APPROVED** [review]
LGTM! Thanks for the contribution :)

**Pull request merged**
