### PR TITLE
Add transient keword to createdAt and updatedAt in Student #4936

### LINKED ISSUE #4936: Add transient keword to createdAt and updatedAt in Student
This prevents the fields from being converted to json during testing. Can remove code in equalizeIrrelevantData in BaseComponentTestCase.

### PR DESCRIPTION
**Pull request by kennho**
Fixes #4936

### CODE REVIEW

**Comment by LowWeiLin** [comment]
More code needs to be removed. Look at the comment in #4936.

**Comment by kennho** [comment]
Sorry I am not too sure which part do I still need to remove in equalizeIrrelevantData? Because anything else other that the 
```
expectedStudent.setCreated_NonProduction(actualStudent.getCreatedAt());
expectedStudent.setUpdatedAt_NonProduction(actualStudent.getUpdatedAt());
```
will create an error. @LowWeiLin

**Comment by LowWeiLin** [comment]
Oops. I see. Are the *_NonProduction methods used elsewhere? If not they can be removed too.

**Comment by kennho** [comment]
Removed another place with equalizeIrrelevantData and the same piece of code. But the *_NonProduction is still being used in StudentsDbTest to set null to createdAt and updatedAt to test for the default timestamp value when both are null. @LowWeiLin

**Comment by LowWeiLin** [comment]
Okay looks good.

**Pull request merged**
