### PR TITLE
[#11941] Instructor creating courses: auto-trim text fields

### LINKED ISSUE #11941: Instructor creating courses: auto-trim text fields
v8.19.2, production

Current: When creating a course, there will be an error message if the course ID or the name has leading/trailing white spaces

image

Suggestion: Auto-trim those fields as such leading/trailing spaces are sure to be accidental rather than intended.

### PR DESCRIPTION
**Pull request by LokeshSingh1102**
Fixes #11941

Outline of solution
first i searched for the file where course name course id were used then i added trim() method to course name course id

Thank you

### CODE REVIEW

**Comment by zhaojj2209** [comment]
@LokeshSingh1102 Tagging this PR as ongoing for now since linting checks have failed. Do let me know once linting errors have been fixed and the PR is ready for review.

**Comment by LokeshSingh1102** [comment]
@zhaojj2209 ok

**Comment by Velosoda** [comment]
I think this fix may not work considering the linter is not ecstatic about reassigning the values you changed. Instead you may be able to fix this problem in the frontend when the data is submitted

**Comment by damithc** [comment]
Closing due to inactivity. Feel free to re-open when resuming work.

**Pull request closed without merging**
