### PR TITLE
Add new rules to Checkstyle-No whitespace after operators

### PR DESCRIPTION
**Pull request by JosephineKwa**
Added no whitespace after rule for bitwise complement `~`, prefix decrement `--`, dot `.`, prefix increment `++`, logical complement `!`, unary minus `-`, unary plus operators `+`.

I'm not sure what the whitespace after policy for typecasts should be like though.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Typecasts should be followed by whitespace as well:
```java
(String) abc; // good
(String)abc; // bad
```

**Comment by wkurniawan07** [comment]
Since the current one has surprisingly little violations, you can include the typecast whitespace as well.

**Comment by JosephineKwa** [comment]
Hm, I don't mind doing it in this PR, but that would be enforcing the "whitespace after" rule rather than "no whitespace after" though

**Comment by wkurniawan07** [comment]
Oh right :p

**Pull request merged**
