### PR TITLE
[#11491] Update tzdb version to 2021e

### LINKED ISSUE #11491: Update tzdb version to 2021e
Our current tzdb version is `2021a` which is quite outdated. The latest at the point of writing is `2021e`.

Guide to update: <https://github.com/TEAMMATES/teammates-ops/blob/master/maintainer-guide.md#timezone-database-update>

### PR DESCRIPTION
**Pull request by NicolasCwy**
Fixes #11491 

**Outline of Solution**
Updated tzdb version following [teammates guide](https://github.com/TEAMMATES/teammates-ops/blob/master/maintainer-guide.md#timezone-database-update)

### CODE REVIEW

**Comment by NicolasCwy** [comment]
My component test `TimezoneSyncerTest` run using `./gradlew componentTests --tests TimezoneSyncerTest` seems to fail. It sounds like it could not connect to the datastore, although I am running it using docker

**Error**
```
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:-2)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.net.Socket.connect(Socket.java:609)
        at java.net.Socket.connect(Socket.java:558)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at com.google.cloud.testing.BaseEmulatorHelper.sendPostRequest(BaseEmulatorHelper.java:198)
        at com.google.cloud.datastore.testing.LocalDatastoreHelper.stop(LocalDatastoreHelper.java:300)
        at com.google.cloud.datastore.testing.LocalDatastoreHelper.stop(LocalDatastoreHelper.java:315)
        at teammates.test.BaseTestCaseWithLocalDatabaseAccess.tearDownLocalDatastoreHelper(BaseTestCaseWithLocalDatabaseAccess.java:85)
        ...

teammates.storage.api.FeedbackSessionsDbTest.tearDownLocalDatastoreHelper FAILED
    java.net.ConnectException at PlainSocketImpl.java:-2
```

**Steps to replicate**

1.  ./gradlew generateTypes
2. npm run build
3. ./gradlew serverRun
4. docker-compose up -d

**Comment by moziliar** [comment]
Did you also generate configs?

You may also want to check where your local tests are accessing.

**Comment by wkurniawan07** [comment]
> `./gradlew componentTests --tests TimezoneSyncerTest`

`TimezoneSyncerTest` is not a component test.

**Comment by NicolasCwy** [comment]
@moziliar @wkurniawan07 Thanks both, realised its an E2E test, assumed that java filed are usually backend component tests. Managed to get it to work on my system

**Review by wkurniawan07 — APPROVED** [review]

**Pull request merged**
