### PR TITLE
Towards a Proper request system for Requesting an Instructor's Account #7161

### LINKED ISSUE #7161: InstructorRequestAccount: Move from Google Forms to a "Proper Request System"
Dear All,

I have chosen to work (and I have already started to doing so) with the creation of a "proper request system" instead of the Google Form in the "request.jsp" page, as proposed in [that](https://docs.google.com/document/d/1hjQQHYM3YId0EUSrGnJWG5AeFpDD_G7xg_d--7jg3vU/pub?embedded=true) page. 

First of all, I would like to ask you where the data obtained from the form should be stored. I guess I should not immediately create a new instructor based on this data since a first approval should be given by the administrator, right? Or we can automate this process by saying, for example, if this instructor belongs to one of the following universities, we will accept him and we will provide him with details for creating his account? Based on that question, I was wondering if I should work with the same way as you have been worked in other forms that I found (e.g. form action="${data.instructorCourseEnrollSaveLink}) or whether I should follow another path in order to store the obtained data and make them available to the admin.

I have created a small prototype of how the form will look like in order to get your feedback:
instructorrequest

Thank you in advance for your time.

### PR DESCRIPTION
**Pull request by nikiforosbotis**
Fixes #7161 

**First remark**: I already now that this PR will not be accepted as it is.

Please help me in order to understand a bit more what I need to do in order to make the proper request system work (even locally).

In order to handle the request properly, I have passed hours in front of my computer's screen trying to understand the path that is followed by a request in the TEAMMATES project.

In particular, I understood in detail how the request of an instructor about enrolling new students works and I tried to make the necessary changes in the files that you can see in order to create the proper request system.

Please note that I have chosen to be only focused **on the process which returns to the new potential instructor the page showing: "we have received your details and we will get back to you soon"** and just show him the details that he just gave. I have not done anything related to the admin and how he acquires access to those details.

It would be very important for me to receive some help **in order to achieve making the proper request system run locally** and then it may be helpful for another contributor to extend it in the future.

Thank you.

### CODE REVIEW

**Comment by damithc** [comment]
Hi @nikiforosbotis 
I commend your persistence and your initiative in this. However, you need to realize that we have no incentive to guide you through a feature that we don't need at the moment. As the project manager, I cannot allow my employees to spend time on things that have no benefit to the project.
Even if this is a feature we need, the situation you are in is not something we expect to happen. New developers are supposed to start from small issues and work their way through progressively harder issues until they have enough knowledge to implement a major feature. In your case you are probably a still a few steps away from being ready to implement an end-to-end feature such as the one you are trying to do.

Having said that, a developer might be willing to answer a more pointed question such as 'Which class should I use to do X' as a help to a fellow developer.

**Comment by nikiforosbotis** [comment]
@damithc Thank you for your kind answer. I really get what you mean and I do not intend to utilize your resources for matters that are not in your priorities. However, the only thing I would like to know is how can I achieve only this functionality: enable the potential instructor (who does not have an account yet, of course) to populate the form (request.jsp) and then return him a page saying "Thank you for your request, we will review it and get back to you shortly", accompanied by the details he just wrote. I think it so not a big deal, at least for me in order to run it locally. **It is for a university's project and I would like to make it happen**. Can any of you guys who had helped me a lot with another question ( @VamsiSangam  and @AnaghHegde ) give me a hand on how to achieve that? My problem right now is that the path I have followed (through Actions and PageData) requires the user to be logged in in order to see the pages and in the case of the "request account", this is impossible.

Finally, @damithc  I would be grateful if you could propose one more d.Contributors (I hopefully finished [this](https://github.com/TEAMMATES/teammates/pull/7241)). I searched on the open ones and most of them are already referenced by PRs.

**Comment by damithc** [comment]
@nikiforosbotis let's wait and see if anyone can help you with getting the page go work. From what I remember, `web.xml` is the place where we configure which page needs what level of authentication. Based on that file `/page/*` URLs require authentication.
In the meantime I'll try to add more `d.Contributor` issues. Some of the existing ones may be referenced by PRs but those PRs may be closed without merging, which means the issue is available for someone to take.

**Comment by wkurniawan07** [comment]
Hi @nikiforosbotis, since this PR is not in line with the project's current roadmap, I will have to close it, perhaps temporarily, perhaps permanently. However, I'll try to assist in what you want to achieve.

`web.xml` is where the mapping between URLs and servlets happen. In case of TEAMMATES, if you wish to bypass authentication for any page, you cannot prepend the URL with `/page/`, `/admin/`, or `/auto/` since they require authentication.

**Pull request closed without merging**
