### PR TITLE
Unused @returns documentation tags in datepicker.js #6700

### LINKED ISSUE #6700: Unused @returns documentation tags in datepicker.js
A number of header comments in datepicker.js have unused `@returns` tags. 

**Task:**
Either use them to describe what the respective methods return, or remove them entirely.

### PR DESCRIPTION
**Pull request by a0129998**
2/3/2017

Fixes #6700 

added comments for `@return` statements

### CODE REVIEW

**Comment by a0129998** [comment]
Ready for review

**Comment by samsontmr** [comment]
@a0129998 Your PR title should be an exact copy of the issue title + issue number (your format is correct).

**Comment by a0129998** [comment]
updated issue title
Ready for review

**Comment by damithc** [comment]
@chowyb is the comment syntax compliant with our JS coding standard?

**Comment by chowyb** [comment]
@damithc based off the referenced [airbnb JS style guide](https://github.com/airbnb/javascript/tree/es5-deprecated/es5#comments) for multi-line comments (since it is not covered in our own docs), strictly speaking there are certain elements that are missing (description of method, specifying parameter types) from the current comments, but otherwise it is compliant with the coding standard.

For quicker reference, the positive example provided in the style guide is as follows:

```javascript
// good
/**
 * make() returns a new element
 * based on the passed in tag name
 *
 * @param {String} tag
 * @return {Element} element
 */
function make(tag) {

  // ...stuff...

  return element;
}
```

**Comment by a0129998** [comment]
@chowyb ok, I will.

**Comment by damithc** [comment]
Merging this PR broke build on Appveyor. I've restarted the build in case it was a temporary problem.

**Comment by damithc** [comment]
> Merging this PR broke build on Appveyor. I've restarted the build in case it was a temporary problem.

Passing now. Probably a temporary issue on Appveyor side

**Pull request merged**
