### PR TITLE
Custom Feedback Paths #5773

### LINKED ISSUE #5773: Custom Feedback Paths
The Custom Feedback Paths feature will allow for a finer customisation of feedback giver to feedback recipient feedback paths. Development will take place on the long-lived `custom-feedback-paths` branch. I will update this issue with references to the relevant PRs when the feature is completed.

Below lists the aspects involved in implementing the Custom Feedback Paths feature. Beside each aspect is a link to the relevant PR where applicable. Those that have a tick beside them have been merged into the `custom-feedback-paths` feature branch.

Main PR (#5850)
- [x] Frontend (#5777)
- [x] Storage and Retrieval (#5895)
- [x] Results (#5941)
- [ ] Sanitization and Validation (#6023)
- [x] Visibility (#6345)
- [x] Update and Delete Cascades (#6061)
- [ ] Testing (In progress)

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #5773

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@JosephineKwa perhaps you're already working on it, but there are merge conflicts here and Travis can't run until it's resolved.

**Comment by JosephineKwa** [comment]
How should I handle the html replacement of the dynamically calculated width and heights for the various handsontable components? Some of the components involved do not have unique names (e.g. `<th class="" style="height: 25px;">`) and are I'm not sure what's the best way to match them using regex

**Comment by wkurniawan07** [comment]
@JosephineKwa where do those originate from? The HTML templates I've seen are identifiable by either `wtHider` or `wtHolder` (but even these two are not so easy to handle).

**Comment by JosephineKwa** [comment]
The `<th class="" style="height: 25px;">` would be the empty rectangle at the top-left hand corner of the spreadsheet, although I'm not too sure if it is calculated dynamically. There is also a `<colgroup>` where the width of its `<col>` elements shows how wide the columns are, which seems to be based on screen size

**Comment by wkurniawan07** [comment]
It looks like we don't have enough resources to take this big feature any further. I'm really sorry about this. Alternatively, if anyone is interested to continue the work done here, feel free to reopen/request for reopen.

**Pull request closed without merging**
