### PR TITLE
[#10595] Instructor session results page: better label for questions without specific recipients

### LINKED ISSUE #10595: Instructor session results page: better label for questions without specific recipients
Currently recipients of questions that do not require specifc recipients are identified as "-". This may be a bit confusing especially when grouped by recipients. Can give it a better label (e.g. no specific recipients)
image

### PR DESCRIPTION
**Pull request by EmberCS15**
Fixes #10595 

#### Outline of Solution
The following things were done in this PR - 
* In case the question is posed to no specific recipient, in the Recipient-Giver-Question view, instead of rendering - (-) as user, team under `No Specific Section`, render user (team) as `No Specific User (No Specific Team)`
* In per question view, in case the recipient user, team is marked as `-` render `No Specific User (No Specific Team)`

#### Testing
Attaching Screen shot for use cases

1. Use case fixed - 

No_Specific_User

2. Both Users are present in DB -

Both_Users_Present

### CODE REVIEW

**Comment by EmberCS15** [comment]
Hi, any update on the review? Let me know if any improvements are required !!!

**Comment by madanalogy** [comment]
> Hi, any update on the review? Let me know if any improvements are required !!!

Please be patient and give our team some time to review the PR. You can check in again if no response is received after 2 days.

**Review by t-cheepeng — APPROVED** [review]
LGTM 👍

**Review by madanalogy — APPROVED** [review]

**Comment by madanalogy** [comment]
Thanks for your contribution!

**Pull request merged**
