### PR TITLE
Instructor: add options (Rank and Distribute Points) question: add more options inputs not appearing #8463

### LINKED ISSUE #8463: Instructor: add options (Rank and Distribute Points) question: add more options inputs not appearing
**Environment**

Ran in development environment.
Master branch

**Steps to reproduce**

1. Edit session
1. Click `new question` => `add rank options question`.
1. Cancel question
1. Add `new question` => `add rank recipients question`
1. Cancel question
1. Add `new question` => `add rank options question`

**Expected behaviour**

The UI appearing should be consistent on both attempts of adding rank options.

**Actual behaviour**

First attempt of adding rank options:

image

Second attempt of adding rank options (after adding rank recipient questions):

image

The options on the left does not appear.

Similar problem happens for Distribute Points (Options) question, more details shown in @sukanta-27 comment below.

### PR DESCRIPTION
**Pull request by bqnguyen94**
Fixes #8463

**Outline of Solution**

`rank-option-table` is hidden every time `rank recipients` is toggled. Call a function so that the element is shown every time `rank options` is selected.

### CODE REVIEW

**Comment by Crphang** [comment]
Can this PR also fix the same problem for distribute (options) question? I will change the issue title to make it more general.

**Comment by bqnguyen94** [comment]
@Crphang I will look into it

**Comment by bqnguyen94** [comment]
@Crphang it's the same problem, child element got hidden and later on stayed hidden. I added the same fix for it.

**Comment by wkurniawan07** [comment]
@bqnguyen94 ready for review?

**Comment by bqnguyen94** [comment]
@wkurniawan07 yes, ready for review.

**Comment by LiHaoTan** [comment]
@bqnguyen94 By the way, the constants `ParamsNames.FEEDBACK_QUESTION_CONSTSUMOPTIONTABLE` and `ParamsNames.FEEDBACK_QUESTION_RANKOPTIONTABLE` were just inlined.

**Comment by bqnguyen94** [comment]
@LiHaoTan noob question: what did you mean by "were just inlined"? :D

**Comment by LiHaoTan** [comment]
I meant that `ParamsNames.FEEDBACK_QUESTION_CONSTSUMOPTIONTABLE` was inlined to just `constSumOptionTable` because they are not parameter names.

**Comment by bqnguyen94** [comment]
@LiHaoTan thanks for the heads up 👍

**Comment by LuLechuan** [comment]
Hi, this look good to me

**Pull request merged**
