### PR TITLE
Change "Received Responses Statistics" to "Statistics for Received Responses" #3245

### LINKED ISSUE #3245: Change "Received Responses Statistics" to "Statistics for Received Responses"
In the instructor's results page, on the views where the statistics are shown, the text shown is "Received Responses Statistics". "Statistics for Received Responses" sounds better.

### PR DESCRIPTION
**Pull request by Mynk96**
Fixes #3245

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@Mynk96 similarly, there are a lot of unrelated whitespace-only changes in this PR, please revert them.

**Comment by Mynk96** [comment]
@wkurniawan07 i didn't changed much in this , and also i am not getting the unrelated whitespaces can you please guide me more on this?

**Comment by wkurniawan07** [comment]
@Mynk96 when you take a look at [this PR's changed files](https://github.com/TEAMMATES/teammates/pull/6281/files):
screen shot 2016-12-31 at 7 52 22 pm
You should notice this kind of diff, comprising of nothing but whitespace changes. This should not be committed because they make the changeset harder to manage, and can cause unnecessary conflicts when other developers work around those area.

**Comment by Mynk96** [comment]
is this fine?

**Comment by wkurniawan07** [comment]
@Mynk96 no, there are still a lot of such changes. Please try your best to revert them all. May I ask if you use other IDE/text editor than Eclipse?

**Comment by Mynk96** [comment]
Eclipse as well as atom

**Comment by wkurniawan07** [comment]
@Mynk96 I have suspected Atom as the culprit as well. Can you try your best to revert all the whitespace-only changes? You need to consult the [Files changed](https://github.com/TEAMMATES/teammates/pull/6281/files) on this PR and make sure no unrelated whitespace-only changes occur.

**Pull request closed without merging**
