### PR TITLE
[#9514] Changed message for edited course 

### LINKED ISSUE #9514: Instructor: Course Edit Page: Show better success message
**Environment**: 
`master` branch

**Steps to reproduce:**
1. Go to `/web/instructor/courses/edit?courseid=<valid course id>`
2. Edit the course details and click `Save changes`
3. Observe success message:
image

**Ideal result:**
The success message can be improved by showing a simple message instead, similar to what we have in v6:
image

### PR DESCRIPTION
**Pull request by ritisha2000**
[#9514] Instructor: Course Edit Page: Show better success message

Regarding this issue, I found the file SaveCourseEditDetailsAction.java in teammates\src\main\java\teammates\ui\webapi\action\SaveCourseEditDetailsAction.java
and edited the JsonResult to return a better and the more simple message found close to the end of the file. 

Fixes #9514

### CODE REVIEW

**Comment by RonakLakhotia** [comment]
@ritisha2000 thanks for your contribution! Don't forget to update the relevant test cases as well.

**Comment by monmanuela** [comment]
Hi @ritisha2000, thank you for your contribution, but you should make the code changes on your own fork. Seems that you may have unintentionally committed your changes on someone else's fork. Do follow the [development process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md).

**Comment by ritisha2000** [comment]
Thank you for your feedback. I will change the relevant test cases. Also, I am working on this project for a class group project which is why I have committed the changes on a group member's fork.

**Comment by monmanuela** [comment]
@ritisha2000 Please resolve the merge conflicts so this PR is ready for review :)

**Comment by AyushChatto** [comment]
Hi @ritisha2000 you still have some merge conflicts in your PR. You can refer to [this] (https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line) article if you need help resolving it. Cheers :)

**Comment by ritisha2000** [comment]
Thank you for your help so far. I am having a conflict with the file SaveCourseDetailsActionTest.java because the file SaveCourseEditDetailsAction.java doesn't exist anymore. Does this make the test file unnecessary?

**Comment by wkurniawan07** [comment]
@ritisha2000, that is not how to handle git merge conflict. Have a read on some online resources to find out what you should do in this case.

**Comment by ritisha2000** [comment]
Thank you for your help. I will keep working on figuring out how to resolve the conflict.

**Comment by amrut-prabhu** [comment]
@ritisha2000 You should only take up **one**  `d.FirstTimers` issue. You've made this PR for #9514 and another PR #9602) for #9508 as well. It would be best if you could close one of these PRs

**Comment by ritisha2000** [comment]
> @ritisha2000 You should only take up **one** `d.FirstTimers` issue. You've made this PR for #9514 and another PR #9602 for #9508 as well. It would be best if you could close one of these PRs
Okay, I understand. I will be closing this PR.

**Pull request closed without merging**
