### PR TITLE
Rename HTML files in src/test/resources/pages that start with upper case #5103

### LINKED ISSUE #5103: Rename HTML files in src/test/resources/pages that start with upper case
The files in `src/test/resources/pages` should all start with a lower case. There are some `Instructor*.html` that don't follow it.

### PR DESCRIPTION
**Pull request by m-nikhil**
fixes #5103.

### CODE REVIEW

**Comment by junhaoyap** [comment]
@m-nikhil tests aren't passing

**Comment by damithc** [comment]
Note that some OSes are sensitive to file name case (e.g. Unix). I believe travis is running a unix platform.

**Comment by m-nikhil** [comment]
@junhaoyap What should I do now? Where should I look for the error?...

**Comment by damithc** [comment]
Perhaps try to run the test locally and see if you can get all of them to pass?

**Comment by wkurniawan07** [comment]
Hi @m-nikhil, any progress on this PR? It'll be great if you can finish this soon. If you can't finish it by this milestone, let's push it to the next one. However, if you abandon it for too long, I'm afraid I have to close it.

**Comment by m-nikhil** [comment]
@wkurniawan07, ok. will do in next 2 days :) ... Caught up some other works.

**Comment by junhaoyap** [comment]
@m-nikhil as advised by @damithc you should run the tests and see what tests are failing - following which you should look at the stack trace to see where they should be fixed! :)

**Comment by wkurniawan07** [comment]
Closing due to inactivity.

**Pull request closed without merging**
