### PR TITLE
InstructorCommentsPageUiTest fails at line 167 #5204

### LINKED ISSUE #5204: InstructorCommentsPageUiTest fails at line 167
Fails often enough to deny Travis from a passing build.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5204

### CODE REVIEW

**Comment by ashrayjain** [comment]
@wkurniawan07 change looks good to me.

**Comment by wkurniawan07** [comment]
@ashrayjain the said test passed on the first run. Not that this indicates absence of more problems, but it's definitely a good news.

**Comment by ashrayjain** [comment]
@wkurniawan07 yea. i think that going forward, the only way for us to get a reasonable level of confidence for these fixes is to monitor the logs and see if these tests fail to pass in the first try for any build for some period of time (like maybe a week). what do you think?

**Comment by wkurniawan07** [comment]
@ashrayjain I believe so. This PR can be set as `toMerge` already right?

**Comment by ashrayjain** [comment]
yup, done

**Pull request merged**
