### PR TITLE
Instructor view results, grouped by recipient: show spinner while loading panels #7043

### LINKED ISSUE #7043: Instructor view results, grouped by recipient: show spinner while loading panels
v5.100

In the case such as below, clicking the panel causes it to load, which can take a significant time. During this time we should show the spinner gif to indicate that things are happening in the background. Otherwise the user might think it's stuck/broken.

image

### PR DESCRIPTION
**Pull request by basitsattar**
Fixes #7043 

The code for adding spinner was already there which was already working in Group by Question view. The issue was the absence of encapsulating div with class "display-icon" in the remaining panels. I have resolved this issue.

### CODE REVIEW

**Comment by whipermr5** [comment]
@basitsattar One more HTML file (`instructorFeedbackResultsAjaxByGQR.html`) to fix with GodMode.

**Comment by basitsattar** [comment]
ready for review.

**Comment by damithc** [comment]
@basitsattar I forgot to ask: is there other places where a similar spinner can be applied while expanding panels? In the results page itself there are different views (grouped by giver, receiver, etc.); all of them now have the spinner?

**Comment by whipermr5** [comment]
@damithc All 5 views use this same tag file, so all of them now have the spinner :)

**Pull request merged**
