### PR TITLE
[#11126] Expand empty search results for feedback session logs

### LINKED ISSUE #11126: Instructor checking logs: expand results if empty
Scenario: instructor searches for logs using the `/web/instructor/logs` page. 

Current: all results panels are collapsed by default.
Suggested: If there are no results for some sessions, we can expand them automatically so that the user doesn't have to click to find out. 

image

We can also consider expanding all results panels by default? Are there any downsides?

### PR DESCRIPTION
**Pull request by hoonti06**
Fixes #11126 

**Outline of Solution**
* Modified that tap expand status depends on whether feedback session log entry is empty or not

before
before

after
after

### CODE REVIEW

**Comment by moziliar** [comment]
Hi @hoonti06 can you also attach the before-after snapshot for the ease of review?

**Comment by hoonti06** [comment]
> Hi @hoonti06 can you also attach the before-after snapshot for the ease of review?

Sure, I added gif files to compare before and after

**Review by moziliar — APPROVED** [review]
To me the change solves the problem.

Need @t-cheepeng to verify if there's any pitfall around this change.

**Review by t-cheepeng — APPROVED** [review]
LGTM 👍

**Comment by moziliar** [comment]
@hoonti06 the e2e test case is bind to the old UI. Please update the e2e test case

**Comment by rrtheonlyone** [comment]
Thanks for the work here @hoonti06 💯 

Looks like E2E tests for Audit Logs are failing - could you take a look and see if you can fix? Let us know if you need any assistance on this.

**Comment by moziliar** [comment]
Do try to run e2e test locally before pushing. It will save the time on remote CI and also allow us to get back to you faster, granted that we now limit the CI run for first PR to manual approval:)

**Comment by hoonti06** [comment]
Sorry, I just succeeded in configuring my test environment locally.

**Review by rrtheonlyone — APPROVED** [review]
LGTM 👍

**Pull request merged**
