### PR TITLE
Add new rules to PMD - MethodArgumentCouldBeFinal

### PR DESCRIPTION
**Pull request by kanghj**
I'll just leave this here, to decide at a later time if we want this

### CODE REVIEW

**Comment by wkurniawan07** [comment]
GH shows "Some checks haven’t completed yet", which is strange because there are obvious merge conflicts.
I'll close and re-open to see if it will be gone afterwards.

**Comment by damithc** [comment]
Merge conflicts are separate from tests/checks right?

**Comment by wkurniawan07** [comment]
If there are merge conflicts, tests/checks wouldn't even run, but the strange thing is that this is appearing:
screen shot 2016-05-19 at 3 17 15 pm

**Comment by wkurniawan07** [comment]
Correct me if I'm wrong, but by disallowing parameter reassignment we have achieved the same right?

**Comment by kanghj** [comment]
Yes, that achieved the same thing as what this PR eventually would. Will close this then.

**Pull request closed without merging**
