### PR TITLE
InstructorStudentListAjaxPageAction: prevent access by instructors without view students privileges #8000

### LINKED ISSUE #8000: GetStudentsAction: prevent access by instructors without view students privileges
Instructors can still access the list of students of a course they do not have privilege to as InstructorStudentListAjaxPageAction does not perform the necessary privilege check.

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #8000 

**Description:**

- Added a check in InstructorStudentListAjaxPageAction using gatekeeper to verify that the instructor has the requisite privileges.
- Now, if an instructor without this privilege (has to be a custom instructor since all our pre-defined types have this privilege enabled) tries to access the list this is what he sees _[Screenshot]_

screen shot 2017-08-28 at 2 09 22 am

Was considering changing the UI so that it doesn't just display a generic "Failed to load" message, but then I thought that it would not be worth it as the number of "custom" instructors are probably quite low. Let me know if you see fit otherwise.

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@leeyimin Turns out that the instructor being used at line 102 of the `InstructorStudentListPageUiTest` did not have permission to view students in the course. (Can see test data [here](https://github.com/TEAMMATES/teammates/blob/master/src/test/resources/data/InstructorStudentListPageUiTest.json#L151)).

Have committed god mode changes as per this test data in be356a6. Let me know however, if you would like the test data changed or if the current state of this branch looks good.

**Comment by HirdayGupta** [comment]
@leeyimin Please review, its quite a small change :)

**Comment by HirdayGupta** [comment]
@leeyimin, possible to review soon?

**Comment by xpdavid** [comment]
Good work @HirdayGupta if you are still there :P Your PR is OK. However, it is quite weird to show a page that requests users to click to do AJAX action while the AJAX doesn't work (due to permission issue). It is not friendly to do this. Wait for your reply to discuss more about this.

**Comment by wkurniawan07** [comment]
Closing due to an inactivity for a very long period. If anyone is interested to continue the work done here, feel free to reopen/request for reopen.

**Pull request closed without merging**
