### PR TITLE
[#12081] User-friendliness: Add labels to rubric questions

### PR DESCRIPTION
**Pull request by jasonqiu212**
Part of #12081 
Sub-issue [Submit feedback page: rubric question](https://github.com/TEAMMATES/teammates/projects/16#card-88052378)

**Outline of Solution**

- Similar to #12149

### CODE REVIEW

**Comment by weiquu** [comment]
Tested and it works! Possible suggestions (but idk if they make things better tbh):
1. Label for each table row
2. Not sure if the labels for the radio buttons are too long, esp. since the text is repeated again after the screenreader goes to the next item

Also, some lint tests seem to be failing? Looks like caused by the trailing whitespace for the `<input>` lines in the rubric html

**Comment by zhaojj2209** [comment]
Accessibility for rubric questions turn out to be more complicated than I previously thought because the questions are formatted as tables with two headers. Here's the W3C WAI tutorial on [dealing with tables with two headers](https://www.w3.org/WAI/tutorials/tables/two-headers/), let's try if this approach works for our case.

**Comment by zhaojj2209** [comment]
Looks great!

Since we're working on this component, though, let's also take the time to make one more improvement: On mobile, for radio buttons that do not have an extra description, let's remove the extra "-" following the option text.
Screenshot 2023-03-06 at 13 17 48

**Comment by jasonqiu212** [comment]
@zhaojj2209 Fixed! 

Screen Shot 2023-03-06 at 1 29 10 PM

Solution: Abstracted out function to combine choice and description with dash, if description exists. If description does not exist, return choice only.

**Review by zhaojj2209 — APPROVED** [review]
LGTM!

**Review by weiquu — APPROVED** [review]

**Comment by zhaojj2209** [comment]
@jasonqiu212 `FeedbackRubricQuestionE2ETest.java` is failing, do look into it.

**Comment by jasonqiu212** [comment]
Upon investigating the failing `FeedbackRubricQuestionE2ETest`, I found that changing `<td>` tags to `<th>` triggered the failures, as the e2e tests verify the table cells using only `<td>`. 

Solution:
- I added methods to test for row and column headers. 
- Since it is likely that we will alter other tables with `<th>` for accessibility reasons, it is likely we will reuse the same e2e testing methods for row headers and columns.

**Comment by zhaojj2209** [comment]
Thanks for the work on the E2E tests!

**Pull request merged**
