### PR TITLE
Merge travis.gradle and build.gradle into one config file #5467

### LINKED ISSUE #5467: Merge travis.gradle and build.gradle into one config file
They were there before because of the split workflow between local and Travis. Now most of the Travis tasks are also run locally: static analysis, tests (due to #5380), and we can even extend it to building and deploying, thus it doesn't make sense anymore to have a split config file.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5467

Few advantages and fixes:
- Saving 17 chars typing for many of the tasks (having to type `-b travis.gradle` everytime becomes annoying).
- Added description to some of the important tasks so they can be displayed via `./gradlew tasks`.
- The task `clean` _overrides_ the existing `clean` task given by Gradle which is not good; this is fixed.
- The JVM args `-Xss2m` was wrongly attached to the property `-Duser.timezone` before (although this might've been fixed by the JVM itself); this is fixed.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@ashrayjain you're also welcome to chip in!

**Comment by ashrayjain** [comment]
@wkurniawan07 looks ok to me. One of the original reasons for separating the two files was that simple tasks like setup etc would trigger the dependencies download that were not necessary for the actual task. This seemed like a waste of developer time. To replicate what I'm describing, try running the setup task in a new environment (delete existing gradle stuff). Dependencies like appengine-endpoints etc get downloaded. This may or may not be a big problem but I felt this was annoying. :P

**Comment by wkurniawan07** [comment]
@ashrayjain you're going to need that when we eventually allow build/run via Gradle (instead of via Eclipse) anyway :p
Also, I'm currently looking on how we can ditch the zip library and rely on Gradle entirely for dependencies. Then we would virtually have no difference between Travis and local save for few tasks.

**Comment by ashrayjain** [comment]
@wkurniawan07 yup, ditching the zip library is the end goal! :) just my two cents to give some clarity on the original thinking.

**Comment by damithc** [comment]
It would be good to use gradle for all dependency management and automating set up tasks as much as we can. We can also use it for testing. But ditching Eclipse testing is not a goal. Gradle is good for running tests that *we know* will pass, but Eclipse is more suitable when we are writing new tests and debugging tests.

**Comment by wkurniawan07** [comment]
It was never my intention to ditch Eclipse testing to begin with. Running tests outside Eclipse is just an alternative, like the ones we provided via `runtests.bat` or `runtests.sh` before (going to be removed soon and replaced with Gradle tasks).

**Comment by wkurniawan07** [comment]
@ashrayjain our end goal is before our eyes now #5509

**Pull request merged**
