### PR TITLE
[#10976] Document frontend standardizations

### LINKED ISSUE #10976: Document frontend standardizations

### PR DESCRIPTION
**Pull request by Jenn26**
Fixes #10976

Added documentation for frontend development standardizations and best practices. Linked the page in the Introduction page and is included in the side bar under "Best Practices". Having this file to document site-wide standards for frontend development will help keep the site consistent. Document can be updated when necessary whenever new standards are set.

Notes taken from previous issues. Ready to review.

### CODE REVIEW

**Review by EuniceSim142 — APPROVED** [review]
LGTM, thanks for contributing to TEAMMATES!

**Comment by zhaojj2209** [comment]
Thank you for the effort to compile the standardisations! However, there are a few points of concern:
- Some points (e.g. footer link colour should be blue) are too specific and therefore unnecessary.
- Some points overlap with existing best practices pages (e.g. UI design, accessibility, mobile friendliness).

The change that I think is sufficient to address this issue would be to simply add "Use Bootstrap styles and colors as much as possible." to the UI design best practices page, under "Be consistent".

**Comment by Jenn26** [comment]
> 

Do you mean that adding that would fix the whole “Document frontend standardizations” issue? Or just removing the overlapping/specific points? I believe there should still be a page where documentation can happen on site-wide standardizations based off issues previously where these were unknown.

**Comment by zhaojj2209** [comment]
> Do you mean that adding that would fix the whole “Document frontend standardizations” issue? Or just removing the overlapping/specific points? I believe there should still be a page where documentation can happen on site-wide standardizations based off issues previously where these were unknown.

Perhaps my suggestion was too extreme, we can add more than one point. I still think the points belong in the UI design best practices page, though. The HTML/CSS/JS best practices can be removed, and the points can be added as follows:

- Use Bootstrap styles and colors as much as possible.
- Keep a neutral color scheme across the site, and use Bootstrap color schemes (e.g. primary, info, warning, danger) to give subtle hints only when necessary.

@damithc Thoughts on this suggested change?

**Comment by damithc** [comment]
> Perhaps my suggestion was too extreme, we can add more than one point. I still think the points belong in the UI design best practices page, though. The HTML/CSS/JS best practices can be removed, and the points can be added as follows:
> 
> * Use Bootstrap styles and colors as much as possible.
> * Keep a neutral color scheme across the site, and use Bootstrap color schemes (e.g. primary, info, warning, danger) to give subtle hints only when necessary.
> 
> @damithc Thoughts on this suggested change?

@zhaojj2209 I have no objections. I think consistency is important (i.e., when choosing a style decision, follow what other similar elements in the UI does). Also, choices should be meaningful (e.g., use the warning style when actually warning the user, not because it looks nice).

**Comment by zhaojj2209** [comment]
Closing due to inactivity, superseded by #12436.

**Pull request closed without merging**
