### PR TITLE
About page: Use data object to contain name of contributors #6731

### LINKED ISSUE #6731: About page: Use data object to contain name of contributors
**Description of feature/enhancement**

Use data object such as JSON or POJO to contain the name of contributors, committers (less likely), and core team members (highly unlikely due to the variations in formatting), and use JS or JSP processes to display them to the about page.

**Justification**

By decoupling data from view, we can more easily manage changes and do processing such as adding new names or counting.

Refer to the last few posts in #6588.

### LINKED ISSUE #8098: AboutUs page: add back numbering
v5.112
Numbering seems to have disappeared. 
Actual:
image
Expected:
image

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6731, fixes #8098 

[Demo here](http://teammates-wkurniawan07.appspot.com/about.jsp).

This is quite a major redesign of the about page so I'm open to discussions.

**Outline of Solution**

- Use JSON data structure to contain the names, usernames, and all other metadata of all contributors, committers, and team members. This allows easy post-processing if the need ever arises.
- Updated all GitHub usernames to the latest and added missing usernames/contributors (last commit). Methodology: I probed the GitHub API for contributors (`https://api.github.com/repos/TEAMMATES/teammates/contributors?per_page=100&page=*`), checked for discrepancies with existing entries, and spent some good 2 hours to match the usernames with names for cases of missing usernames.
- Changed the link to simply GitHub profile link instead of `involves` because `involves` is a rather inadequate way to measure someone's "contribution". (commenting _anything_ to an issue/PR = contributing???)
- Removed "bug reporting/fixing, enhancements" because unless we precisely quantify the contributions, these words lose their value-add.
- All committers and core team members (except for the earliest ones whose GitHub profiles can't be traced via contributions) are now linked to their GitHub profiles. (it's counter-intuitive when we add link to contributors but not more important members, right?)

Note that I have not yet added contributors from V6.0.0. That will be done later, likely together with #8008.

### CODE REVIEW

**Comment by damithc** [comment]
No major objections.
Acknowledgements title can be a bit smaller?
I would like to show the total number of contributors too i.e. developer community size, if that's not too hard to do.

**Comment by wkurniawan07** [comment]
> Acknowledgements title can be a bit smaller?

Is it the word "Acknowledgements" or the text after ("TEAMMATES team wishes to thank the following invaluable contributions")?

> I would like to show the total number of contributors too i.e. developer community size, if that's not too hard to do.

It becomes a trivial matter now that the data is a proper data object. How do you want it to be displayed?

**Comment by damithc** [comment]
> Is it the word "Acknowledgements" or the text after ("TEAMMATES team wishes to thank the following invaluable contributions")?

The sentence. Ideally, should be smaller than the title `Acknowledgements`.

> How do you want it to be displayed?

Something like this? Open to other suggestions too.

>TEAMMATES contains code contributions from 325 developers.

**Comment by wkurniawan07** [comment]
@damithc demo site updated.

@whipermr5 if you have any suggestion with the new way of updating the contributors' list, do voice it out.

**Pull request merged**
