### PR TITLE
[#12894] Per-recipient stats are calculated based on student name, not email

### LINKED ISSUE #12894: Per-recipient stats are calculated based on student name, not email
Reported by a user. V8.30

Example question:
image

Problem:
Per-recipient stats are calculated based on student name. When there are multiple students with the same name, their scores are added up. It should be based on student email instead, which is the only field guaranteed to be unique. 

A similar problem might be affecting other places too, but this is the one reported by the user. As a temporary workaround, I've asked the used to disambiguate names so that no students have the same name.

### PR DESCRIPTION
**Pull request by Hkovin**
Fixes #12894

**Outline of Solution**

 
This PR is ready for review. We solved the issue by modifying msq-question-statistics.calculation.ts. Instead of using "response.recipient" to index into perRecipientResponse we used "response.recipientEmail." We also created another variable to store the recipient names in order to populate the recipient property of the perRecipientResponses object.

### CODE REVIEW

**Comment by cedricongjh** [comment]
hi @Hkovin, thank you for the PR, do fix the failing tests before we proceed to review it, thank you!

**Review by mingyuanc — COMMENTED** [review]
Hey, the component testing is still failing, do look into it. Feel free to ping me if you encounter any difficulty.

**Comment by Hkovin** [comment]
Currently, the component test "MsqQuestionStatisticsComponent" in the file "src/web/app/components/question-types/question-statistics/msq-question-statistics.component.spec.ts" is failing. This is due to the code changes I made, which index the recipients based on email rather than name - which was needed in order to uniquely identify students. Unfortunately, with the logic needed to resolve this issue, I won't be able to pass this test.

**Comment by cedricongjh** [comment]
> Currently, the component test "MsqQuestionStatisticsComponent" in the file "src/web/app/components/question-types/question-statistics/msq-question-statistics.component.spec.ts" is failing. This is due to the code changes I made, which index the recipients based on email rather than name - which was needed in order to uniquely identify students. Unfortunately, with the logic needed to resolve this issue, I won't be able to pass this test.

hi @Hkovin, since you changed the logic, the tests have to change accordingly to reflect the change in logic as well, do go ahead and update the tests

**Comment by jckras** [comment]
> > Currently, the component test "MsqQuestionStatisticsComponent" in the file "src/web/app/components/question-types/question-statistics/msq-question-statistics.component.spec.ts" is failing. This is due to the code changes I made, which index the recipients based on email rather than name - which was needed in order to uniquely identify students. Unfortunately, with the logic needed to resolve this issue, I won't be able to pass this test.
> 
> hi @Hkovin, since you changed the logic, the tests have to change accordingly to reflect the change in logic as well, do go ahead and update the tests

Hi @cedricongjh, we did attempt to change the logic in the tests, however the CI build still runs on the old tests that use the old logic.

**Comment by cedricongjh** [comment]
the CI will run the latest version of the tests, including those in this PR, it appears that there are not any tests in the PR, do remember to push them, thank you

**Review by Andy-W-Developer — COMMENTED** [review]
regarding your test changes
the names in `expectedPerRecipientResponsesWithOther` are not changed to emails

but everything passes and works, tested locally and on CI
https://github.com/Andy-W-Developer/teammates/actions/runs/9248847879

**Comment by weiquu** [comment]
Closing due to inactivity

**Pull request closed without merging**
