### PR TITLE
InstructorFeedbackEditPageUiTest failing on dev server #5993

### LINKED ISSUE #5993: InstructorFeedbackEditPageUiTest failing on dev server
Fails at different places at different runs. Possibly due to delay in loading visibility preview message.

```
java.lang.AssertionError: Expected the receiving student to be able to see response, but was 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at teammates.test.cases.BaseTestCase.assertTrue(BaseTestCase.java:160)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.testEditQuestionAction(InstructorFeedbackEditPageUiTest.java:330)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.testGeneralQuestionOperations(InstructorFeedbackEditPageUiTest.java:101)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest.allTests(InstructorFeedbackEditPageUiTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
```

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5993 

Not sure how switching preview by instructor/preview by student smoothens the test run, but I managed to get 5 continuous passes that way (when preview by student goes first I got stopped at 2nd run or so).

### CODE REVIEW

**Comment by JosephineKwa** [comment]
The test still seems to fail for me at line 330 of `InstructorFeedbackEditPageUiTest` on staging. I think it is because the visibility message element is always visible. Perhaps we could use `waitForTextContainedInElementPresence` to wait for the specified text in the visibility message instead of `feedbackEditPage.waitForElementVisibility(visibilityMessage2);` then asserting.

**Comment by JosephineKwa** [comment]
The test fails again for me at line 623, where it checks for the visibility error without waiting for it

**Comment by wkurniawan07** [comment]
How about I hijack the issue a bit... there are 3 open, failing PRs at the moment waiting for this fix to be merged.

**Comment by JosephineKwa** [comment]
Good to merge!

**Pull request merged**
