### PR TITLE
[#9705] focus tiny mce

### LINKED ISSUE #9705: Rich text box: Unable to put text box in focus when clicked anywhere but the top-most line of the box
click

- **Environment**: 
`master` branch at commit 18040a23ac6a5db5c0a251a7a0d7bfb19db468fb

**Steps to reproduce**
1. Go to any rich text box e.g in an essay type question of a feedback session.
2. Click the bottom part of the box

**Expected behaviour**
The text box is in focus and user is able to input text. User should be able to click anywhere within the box.

**Actual behaviour**
Text box is not in focus. To put the text box in focus, the user has to click the top-most line of the box.

### PR DESCRIPTION
**Pull request by BeaFerreira19**
Fixes #9705 

**Solution**
To solve this issue you only need to use the selector attribute of the tinyMCE on the tinymce.init. And give it a value according to your HTML, after some research on the html elements I found out that you wanted to select the 'editor' element. If you don't do this the selection will be only the first line because it's the default of tinyMCE. 
This fix makes it possible to click anywhere on the editor and the rich text component will appear.

### CODE REVIEW

**Comment by BeaFerreira19** [comment]
Hello , can you assign someone to review this pull request ? I know it will resolve your issue ! Thanks

**Comment by BeaFerreira19** [comment]
Yes it was working perfeclty 
result
The docker files probably generated automatically , I didin't notice I pushed them too

**Comment by wkurniawan07** [comment]
@BeaFerreira19, those are not auto-generated. You started off from the wrong branch; you should have started from the `master` branch instead of the experimental `docker` branch. You need to fix such that those Docker-related files are not part of this PR.

**Comment by madanalogy** [comment]
Closing due to inactivity, feel free to reopen this PR after addressing the comments made.

**Pull request closed without merging**
