### PR TITLE
InstructorStudentListPageUiTest fails at line 172 #5017

### LINKED ISSUE #5017: InstructorStudentListPageUiTest fails at line 172
This happens regularly on Travis and sometimes on local environments as well.

The stack trace is:
```
java.lang.AssertionError: expected:<http://localhost:8888/page/studentProfilePic?studentemail=F702AF37C82846594241AA61DA9E8121513646F6B96E433CF5475D7A0DDC960D8A760297A033C316073F728DF8BAE432&courseid=C179779D673504E85F7ADD572ED9CD4D&user=instructorWith2Courses> but was:<http://localhost:8888/images/profile_picture_default.png>
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
        at teammates.test.pageobjects.InstructorStudentListPage.verifyProfilePhoto(InstructorStudentListPage.java:117)
        at teammates.test.cases.ui.browsertests.InstructorStudentListPageUiTest.testShowPhoto(InstructorStudentListPageUiTest.java:172)
        at teammates.test.cases.ui.browsertests.InstructorStudentListPageUiTest.testAll(InstructorStudentListPageUiTest.java:68)
```

### PR DESCRIPTION
**Pull request by ashrayjain**
Fixes #5017

### CODE REVIEW

**Comment by ashrayjain** [comment]
@thyageshm please look at this as soon as possible. will allow me to move forward with Travis.
The fix basically makes the popover selection more selective (which was already being done for the other  asserts in the same function)

**Comment by thyageshm** [comment]
Will review tonight

**Comment by damithc** [comment]
@ashrayjain does this fix the travis problem?

**Comment by ashrayjain** [comment]
yep :)

**Comment by thyageshm** [comment]
Looks fine, not sure why this works though...

**Comment by ashrayjain** [comment]
The issue was that there were multiple popups and we were using findElement (which would return the wrong popup). Since there are multiple rows on that page, each of which can have a popup, this fix basically checks and compares against the popup in the row which we are interested in only.

**Comment by thyageshm** [comment]
:+1:

**Pull request merged**
