### PR TITLE
[#12588] Added unit tests for ErrorReportComponent

### PR DESCRIPTION
**Pull request by u7488099**
Fixes [#12588]

Outline of Solution
Add unit tests for ErrorReportComponent

### CODE REVIEW

**Comment by u7488099** [comment]
Ready for review

**Review by cedricongjh — CHANGES_REQUESTED** [review]
a small change, otherwise lgtm!

**Comment by u7488099** [comment]
The test has been removed

**Comment by u7488099** [comment]
Ready for review

**Comment by u7488099** [comment]
Ready for review

**Review by cedricongjh — APPROVED** [review]
LGTM, thank you for your contribution!

**Review by weiquu — APPROVED** [review]
LGTM

**Pull request merged**
