### PR TITLE
[#10782] Add a configurable banner

### LINKED ISSUE #10782: Add a banner with configurable content
Add a banner to the index page as well as home pages for students and instructors that can have its contents easily configurable. Banner should be dismissible for the user and whether it is displayed at all or not should also be configurable. See discussion in #10780 for more information and https://github.com/TEAMMATES/teammates/pull/10869#issuecomment-748183065 for important discussion points.

### PR DESCRIPTION
**Pull request by daongochieu2810**
Fixes #10782 
**Outline of Solution**
image

Based on the implementation from  #10471
Banner content can be set in ```student.banner-content.ts``` and ```instructor.banner-content.ts```. To hide/show banners, set the ```studentBannerContent``` or ```instructorBannerContent``` in ```config.ts``` (1 to show, 0 to hide).
Banner content has the form:
 - Title
 - Content
 - Links: each link has a name and a clickable link

### CODE REVIEW

**Review by niqiukun — CHANGES_REQUESTED** [review]
Follows what is discussed in https://github.com/TEAMMATES/teammates/issues/10780, I think the idea is to have the banner details configurable in some configuration files, not to hardcode them inside components. You may refer to the discussion there for more details.

**Comment by daongochieu2810** [comment]
> Follows what is discussed in #10780, I think the idea is to have the banner details configurable in some configuration files, not to hardcode them inside components. You may refer to the discussion there for more details.

Hi does this mean that we need an UI to configure banners?

**Comment by damithc** [comment]
> Hi does this mean that we need an UI to configure banners?

Probably no need for a UI. Something like setting the banner location in a config file should be enough.

**Comment by wkurniawan07** [comment]
Pardon the interruption.

I feel that the issue is very much incomplete at this point of time. Lots of unanswered question like:
- What can be changed within the banner? Obviously the content, but more than that: the styling, the background color, the position within page, the pages in which the banner is displayed, etc.?
- Can the banner accept more than just text or rich text?
- Do we need multiple versions of banners depending on the user who sees it?
- Are the user's interaction with banners persisted across sessions, e.g. if they dismiss once, will they see it again?

Without having most/all of them unanswered this issue (or any issue) should not even be attempted.

**Comment by daongochieu2810** [comment]
I will close this PR for the moment then

**Pull request closed without merging**
