### PR TITLE
Remove redundant tooltip #5684

### LINKED ISSUE #5684: Remove redundant tooltip
redundant_tooltip

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #5684

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
@belyabl9 Pursuant to the discussion on Slack, I think we should rephrase the tooltip messages such that they are no longer redundant

- FEEDBACK_QUESTION_EDIT
  - from "Edit this question"
  - to "Enable controls for editing this question. Do remember to save the changes before moving on to editing another question."
- FEEDBACK_QUESTION_DISCARDCHANGES
 - from "Discard your changes"
 - to "Discard any unsaved edits and revert back to original question."
- FEEDBACK_QUESTION_CANCEL_NEW
  - from "Discard new question"
  - to "Cancel adding new question. No new question will be added to the feedback session."

We can also remove the delete button for newly added question because that is slightly misleading: the question hasn't been added and thus cannot be deleted.

Maybe you can make the edits and post screenshots of the modified tooltips for @damithc to vet on the phrasing.

**Comment by YongJieYongJie** [comment]
@belyabl9 When you are ready, do post screenshots of the tooltips in content

**Comment by belyabl9** [comment]
image

image

image

**Comment by damithc** [comment]
@YongJieYongJie Should we use 'Edits` `Discards` etc. instead? i.e. phrase it as a description rather than an action.

**Comment by YongJieYongJie** [comment]
@damithc I would prefer phrasing the tooltips as actions (i.e., `Edit` and `Discard') because it seems more neutral this way. I think of it as "Click this button to [content of tooltip]"

I checked several websites (github, stackoverflow, slack and sites an awwwards.com) and desktop applications (firefox and my file manager) and they all phrase tooltips as actions

**Comment by damithc** [comment]
Yes, it make sense with "Click this button to...". We should document this somewhere.

**Pull request merged**
