### PR TITLE
[#10860] Student submit responses: prompt the student to save a submission confirmation

### LINKED ISSUE #5721: Email sent to respondent after submission: include answers submitted
The current email does not include the responses submitted.
To be done after #5675

### LINKED ISSUE #10860: Student submit responses: prompt the student to save a submission confirmation
Suggestion: After a student submits responses, prompt the student to save a record of responses locally in some suitable format (rtf, pdf, text?).

Reason: In case the submission is found to be missing in the data base later or the submission doesn't go through for some reason, the student has proof of submission as well as a copy of the responses that can be used in a resubmission.

Some background: 
* There are cases of a student swearing he submitted but there is no trace of a submission in our logs or in the database.
* There are cases where a student says he typed in very long responses and now they have disappeared. Even if the deadline is not over or extended, the user still loses all the work spent typing the responses.
* Although we have confirmation emails, it takes time for the email to come and it's too late when the student realizes the email never came (or don't bother to check for the email anyway), plus the email doesn't contain the responses submitted.

PS:
* If we implement this feature, it should be framed as a 'submission confirmation' so that users don't feel like they are saving a local copy of the submission. It's just that the submission confirmation happen to include a copy of the responses. 
* In fact, we can remove the submission confirmation altogether, saving us about 20% o our email cost.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #10860, fixes #5721 

First commit simply removes all code related to submission confirmation email; second commit is where the new implementation is.

Screen Shot 2020-12-16 at 9 41 18 PM

[TEAMMATES Proof of Submission - 1608126086099.txt](https://github.com/TEAMMATES/teammates/files/5703049/TEAMMATES.Proof.of.Submission.-.1608126086099.txt)

The downside of this is the proof of submission file is very easy to be tinkered, so someone can submit "complaints" with a fraudulent proof of submission. The request IDs printed cannot be fabricated, but it will be troublesome if admin needs to keep cross-checking to filter out fraudulent behaviors.

### CODE REVIEW

**Comment by damithc** [comment]
Nice. 

Some suggestions to consider (it's fine to merge even without them):

```
TEAMMATES Session Submission Confirmation
==============================
Submitted by: Wilson Kurniawan [wkurniawan.92.gma-demo0}
Course: ABC123
Session: First team feedback session
Submitted at: 13:45:43 on 2021/12/20 
Confirmation ID: 1607528081476-20211220134543
```
Note how the second part of the confirmation ID maps to the submitted date/time so that we can spot badly fabricated ones just by eyeballing. Can disguise it further by putting a random digit in front and and at the end of it. 

How about this phrasing?
>You are encouraged to save this submission confirmation as a proof of submission. 

Should we give buttons `[ Download Submission Confirmation ] [ OK ]` to increase the chance of them actually doing it?

**Comment by wkurniawan07** [comment]
> Note how the second part of the confirmation ID maps to the submitted date/time so that we can spot badly fabricated ones just by eyeballing. Can disguise it further by putting a random digit in front and and at the end of it.

This is not going to work. If anyone is smart enough to deduce the pattern (and furthermore the generating code is out there for the world to see), no amount of obfuscation/disguise will help.

Also, the part that concerns me more is the printed answers. Someone can easily fabricate a report (by downloading a legitimate one and changing some items) and says "the system changes my answer intentionally!".

**Comment by damithc** [comment]
> This is not going to work. If anyone is smart enough to deduce the pattern (and furthermore the generating code is out there for the world to see), no amount of obfuscation/disguise will help.

Of course this is not fool proof, but it can weed out any dumb fabrications at not much extra cost. For example, recently I came across a confirmation email that a student faked and I was able to spot that it was fake because the link in it was for viewing results, not for submitting responses (he must have copy-pasted the link from the wrong email).  If the ID passes the eyeball test, we still have to check against the logs but such a deeper investigation can be avoided if the forgery is already obvious.

> Also, the part that concerns me more is the printed answers. Someone can easily fabricate a report (by downloading a legitimate one and changing some items) and says "the system changes my answer intentionally!".

Yes, for example, they can submit an empty response (if the deadline is very near) and fill in the responses in the text file later. Hash the contents to a short string and add that to the ID?  However, verifying the hash will require another script 🤔 , unless the hash is also logged on the server side.

**Comment by damithc** [comment]
Guys, shall we go ahead with a simpler/current solution first? I'm keen to control the email cost, at least temporarily because we have already exceeded the email quota for this month i.e., every email sent is costing extra

**Review by rrtheonlyone — APPROVED** [review]
LGTM! Just need to fix the linting to pass CI 

Minor Point: As @damithc pointed out, this might be better:

Screenshot 2020-12-15 at 10 37 17 PM

If not the download link is quite easy to miss for a student.

**Review by rrtheonlyone — APPROVED** [review]
LGTM 💯

**Review by madanalogy — APPROVED** [review]
LGTM

**Pull request merged**
