### PR TITLE
Misleading error messages from backend validation when adding course #5277

### LINKED ISSUE #5277: Misleading error messages from backend validation when adding course
The error message is misleading:
image

Specifically, it assumes any problem will be with the course ID, and does not inform user of invalidity in course name.

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #5277

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
Previous error messages:
image

Current (same format as elsewhere, e.g., adding instructor, adding session):
image

**Comment by damithc** [comment]
Add a comment when ready to review.

**Comment by YongJieYongJie** [comment]
Ready for review!

**Comment by JosephineKwa** [comment]
Currently the invalid course id status message is handled on the front end, while the invalid course name status message is handled on the back end. @damithc should it be standardised to be handled by just the backend/frontend or do we leave it as it is?

**Comment by damithc** [comment]
Yes, I prefer it to be handled in the backend. We can make the error detection more responsive using AJAX (or some other technique) at a later stage.

**Comment by YongJieYongJie** [comment]
@JosephineKwa Ready for review!
Now both Course ID and Course name are handled by backend validation:

image

**Comment by JosephineKwa** [comment]
Good to merge!

**Pull request merged**
