### PR TITLE
[#9419] Add Form Validation to Add New Course

### PR DESCRIPTION
**Pull request by madanalogy**
Part of #9419, Closes #9820 

May-13-2020 12-49-13

### CODE REVIEW

**Comment by damithc** [comment]
In V6 we have a policy that because back-end validation is unavoidable (because front-end validation can be bypassed), to avoid duplicating the same validation logic in JS and Java, we only do back-end validation. Has this changed in V7? For example, is it possible in V7 to reuse the validation logic for both front-end and back-end?

**Comment by madanalogy** [comment]
> In V6 we have a policy that because back-end validation is unavoidable (because front-end validation can be bypassed), to avoid duplicating the same validation logic in JS and Java, we only do back-end validation. Has this changed in V7? For example, is it possible in V7 to reuse the validation logic for both front-end and back-end?

I was under the impression that the intent was to improve the user experience, i.e. users wouldn't  need to wait for the back-end validation. Maybe @wkurniawan07 or @xpdavid could provide more insight.

This PR is a continuation from https://github.com/TEAMMATES/teammates/pull/9975 since https://github.com/TEAMMATES/teammates/pull/9820 has been unresponsive.

**Comment by xpdavid** [comment]
Currently it is not possible to share the validation code (as one is in `TypeScript` and one is in `Java`) (If the backend is `node`, we can do this :P). I think it worth to investigate whether we can do the sharing (maybe be using a common `json` rule file?).

Nevertheless, this is a good to have feature since the backend validation has been throughly tested.

**Comment by madanalogy** [comment]
This is actually no longer necessary as the page will display an error toast and return if the form fields are not valid, thus already implementing a form validation of sorts

**Pull request closed without merging**
