### PR TITLE
[#10245] Improve rich-text editors

### LINKED ISSUE #9665: Text box formatter in sessions edit page is stuck at the top of the page
**Environment**: `master` branch at commit e360fc0

**Steps to reproduce**
1. Go to instructor sessions page
2. Click `Edit` on one of the feedback session
3. Click the top `Edit` button
4. Click inside the `Instructions` box
5. Scroll down, and the text box formatter stays at the top of the page

image

**Expected behaviour**
Text box formatter should disappear as the user scrolls down

**Actual behaviour**
Text box formatter is stuck at the top of the page

**Additional Info**
The bug only occurs when the `Instructions` text box is on focus. Clicking anywhere outside of the text box will make the text box formatter disappear.

### LINKED ISSUE #9705: Rich text box: Unable to put text box in focus when clicked anywhere but the top-most line of the box
click

- **Environment**: 
`master` branch at commit 18040a23ac6a5db5c0a251a7a0d7bfb19db468fb

**Steps to reproduce**
1. Go to any rich text box e.g in an essay type question of a feedback session.
2. Click the bottom part of the box

**Expected behaviour**
The text box is in focus and user is able to input text. User should be able to click anywhere within the box.

**Actual behaviour**
Text box is not in focus. To put the text box in focus, the user has to click the top-most line of the box.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #9705, fixes #9665, part of #10245, closes #9829 

**Outline of Solution**

Screen Shot 2020-07-13 at 9 59 05 PM

- Forced rich text editors to be non-inline mode for when spaces are sufficient (session instructions, question description, text question answer, response comment) and to be inline mode for when spaces are limited (MCQ option)
  - This may be a contentious decision because it goes against "compacting space" target we are trying to achieve. However, this behaviour is more user-friendly (user always knows to expect rich-text editor, which also doesn't block the text above) and is also commonly used (just look at GitHub's text editor)
  - Additionally, in V6 we went for inline mode because God mode doesn't play well with the rich-text editor. We have now replaced it with snapshot testing which can handle it just fine (in fact the snapshots are almost unaffected).

Screen Shot 2020-07-13 at 10 00 38 PM

- Removed plugins that are not useful, such as print and full screen
- Removed our custom-built placeholder plugin since it is now natively supported
- Removed toolbar items that are not useful, such as font size, font style, undo/redo. Now the toolbar can fit in one line, in a sufficiently large screen width.
  - Added some useful toolbar items such as strikethrough, subscript, superscript
- Fixed a few other settings, can be seen via commit message

### CODE REVIEW

**Comment by wkurniawan07** [comment]
> The cursor doesn't change to a text pointer when hovered over selectable text areas.

There is no good way to achieve this right now without hacking too much into the inner working of tinymce.

> Also, the disabled version of the text editor doesn't really look disabled, with the text box not greyed out

Fixed.

> and still selectable.

Disabled texts are not meant to be unselectable.

**Comment by damithc** [comment]
> > The cursor doesn't change to a text pointer when hovered over selectable text areas.
> 
> There is no good way to achieve this right now without hacking too much into the inner working of tinymce.

As a workaround, may be set the height to just one line?

**Comment by wkurniawan07** [comment]
> As a workaround, maybe set the height to just one line?

Not a good idea because the textarea is resizable.

**Comment by damithc** [comment]
> > As a workaround, maybe set the height to just one line?
> 
> Not a good idea because the textarea is resizable.

Yes, but it could reduce the number of users clicking outside the first line and then emailing us that the text area is not working. 

On the other hand, I wonder why this is the default behavior of tinyMCE. Is everybody OK with that behavior?

**Comment by wkurniawan07** [comment]
> Yes, but it could reduce the number of users clicking outside the first line and then emailing us that the text area is not working.

It seems like the problem is misunderstood. The problem is not the area outside is not clickable. It is merely the cursor does not change to text, but the area is very much clickable.

**Pull request merged**
