### PR TITLE
instructorFeedbackResponseCommentsLoad empty div has empty style attribute #3982

### LINKED ISSUE #3982: instructorFeedbackResponseCommentsLoad empty div has empty style attribute
Self explanatory, just remove it and fix the test cases

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #3982

### CODE REVIEW

**Comment by kanghj** [comment]
@belyabl9, thanks for the pull request. Since this is a first timer's issue, we usually don't expect tests to be modified. But in this case, the change made here will result in the tests failing, do you want to try to fix them yourself here (you can look through the development process under the section "Fixing issues")? Alternatively, if you prefer, the reviewer can fix the tests for you.

**Comment by belyabl9** [comment]
@kanghj, oh, It's my fault, I should have checked it more carefully. I overlooked it because I can't achieve 100% of passed tests. I always have ~7 failed tests, usually because of timeout.
I'll try to fix tests here.

**Comment by belyabl9** [comment]
Ready to review

**Comment by kanghj** [comment]
@JosephineKwa, for your review

**Comment by JosephineKwa** [comment]
Hi @belyabl9, thanks for opening a PR for the issue.
However, the branch name does not follow our guidelines. Please refer to <a href="https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md">here</a> for more information on the branch naming format. Rather than using underscores, the branch should be delimited by dashes.

**Pull request closed without merging**
