### PR TITLE
 [#12460] Set character limit on question description

### LINKED ISSUE #12460: Set character limit on question description
Inside feedback editing functionality, in the editing question, it doesn't have character limit to the description question, as well as in the configuration, it can cause problems to the user. I haven't checked but I believe that this problem is not exclusive to the question and configuration editing session, I believe that in creation there is no limit either.

image

### PR DESCRIPTION
**Pull request by anguye68**
Fixes #12460 

**Outline of Solution**

Added the [hasCharacterLimit]="true" attribute to the question edit component.

image
image

### CODE REVIEW

**Comment by cedricongjh** [comment]
hi @anguye68, thank you for your PR, however it appears that component tests are failing.

To update to update the snapshot tests, run `npm run test` and press `a` to run all test cases. After that, check through the snapshots to make sure the changes are as expected, then press `u` to update them. You can find more details on snapshot testing [here](https://teammates.github.io/teammates/snapshot-testing.html).

Do try it out and let us know if there's any issues you ran into!

**Comment by anguye68** [comment]
> hi @anguye68, thank you for your PR, however it appears that component tests are failing.
> 
> To update to update the snapshot tests, run `npm run test` and press `a` to run all test cases. After that, check through the snapshots to make sure the changes are as expected, then press `u` to update them. You can find more details on snapshot testing [here](https://teammates.github.io/teammates/snapshot-testing.html).
> 
> Do try it out and let us know if there's any issues you ran into!

Hello. I ran `npm run test` and all test cases are passing. There is no `u` option, but I ran it with `npm run test -- -u` to update, but there are no failing test cases. Any advice on why it is failing on GitHub cehcks?

**Comment by cedricongjh** [comment]
> > hi @anguye68, thank you for your PR, however it appears that component tests are failing.
> > To update to update the snapshot tests, run `npm run test` and press `a` to run all test cases. After that, check through the snapshots to make sure the changes are as expected, then press `u` to update them. You can find more details on snapshot testing [here](https://teammates.github.io/teammates/snapshot-testing.html).
> > Do try it out and let us know if there's any issues you ran into!
> 
> Hello @cedricongjh. I ran `npm run test` and all test cases are passing. There is no `u` option, but I ran it with `npm run test -- -u` to update, but there are no failing test cases. Any advice on why it is failing on GitHub cehcks?

Hey @anguye68, running it on my local machine, it seems that the test cases are failing. There is a possibility that the test cases pass on your end as there could be unpushed commits from your local branch, or a chance that the tests were running on the master branch. 

Running `npm run test`, followed by `a`, and then pressing `u` (after all the tests have run) updates the following snapshots for me:
`instructor-session-edit-page.component.spec.ts.snap` and `question-edit-form.component.spec.ts.snap`.

Do try the steps again, and let me know if you run into any further issues!

**Comment by jasonqiu212** [comment]
Hi @anguye68, Are you able to run all of the test cases on your local machine?

> run `npm run test` and press `a` to run all test cases

On my local machine, the same 2 tests mentioned by @cedricongjh fail:
1. `instructor-session-edit-page.component.spec.ts`
2. `question-edit-form.component.spec.ts`

**Comment by jasonqiu212** [comment]
Closing due to inactivity.

@anguye68 We appreciate your PR and would love to have your fix merged into TEAMMATES. Feel free to reopen this PR if you decide to work on this again :)

**Pull request closed without merging**
