### PR TITLE
[#2673] Student: view responses: show response statistics of 'constant sum' questions

### LINKED ISSUE #2673: Student: view responses: show response statistics of 'constant sum' questions
Similar to #2564 and #2658, but for constant sum questions.

### PR DESCRIPTION
**Pull request by ypinhsuan**
Fixes #2673

**Outline of Solution**
Display statistics to students for constant sum recipient questions and constant sum options questions.
The responses will be filtered in `SingleStatisticsComponent.ts` and will only show statistics of responses from others to self.
No statistics are displayed if responses are not visible to students

Constant sum options question before
image
Constant sum options question after
constsum options

Constant sum recipients question before
image
Constant sum recipients question after
constsum recipients

### CODE REVIEW

**Review by moziliar — COMMENTED** [review]
Change looks good!

It'd be good to have a before-after snapshot to show the difference.

**Comment by ypinhsuan** [comment]
Thanks for the tip!
I have updated the original post to include the screenshot before the changes.

**Review by moziliar — APPROVED** [review]
It really looks good! Thanks for the contribution.

**Review by madanalogy — APPROVED** [review]
LGTM

**Pull request merged**
