### PR TITLE
Navbar showing contents behind it #6823

### LINKED ISSUE #6823: Navbar showing contents behind it
**Environment**
LocalHost
http://localhost:8888/admin/adminEmailComposePage
Master branch is up-to-date with upstream.

**Steps to reproduce**
Clicking on the collapsed navbar button on /admin/adminEmailComposePage .

**Expected behaviour**
bug1

**Actual behaviour**
bug

### PR DESCRIPTION
**Pull request by LIUJIAHAOCS**
Fixes #6823 

**Outline of Solution**

> Delete the line as xpdavid suggested.
`$('.navbar-fixed-top').css('zIndex', 0);`

### CODE REVIEW

**Comment by LIUJIAHAOCS** [comment]
Ready for review

**Comment by xpdavid** [comment]
@LIUJIAHAOCS Can you post some screenshots to show the changes. (You can just copy from the issue :) )

**Comment by LIUJIAHAOCS** [comment]
It should look like this:
00409030-099e-11e7-98ee-362da251629d

**Comment by xpdavid** [comment]
@LIUJIAHAOCS What does it look like before the changes :P

**Comment by LIUJIAHAOCS** [comment]
@xpdavid the screenshots have been updated :)

**Pull request merged**
