### PR TITLE
[#1501] Add tests for FeedbackRankRecipientsQuestionDetails

### PR DESCRIPTION
**Pull request by hhdqirui**
Part of #1501 

**Outline of Solution**
Add tests for some of the methods in `FeedbackRankRecipientsQuestionDetails`. There is another PR #10913 which adds tests for the same class but this PR is currently closed. Tests added in this PR cover the testing of methods that are not covered by PR #10913. The tests from PR #10913 will be added if PR #10913 will not be re-opened.

### CODE REVIEW

**Review by halfwhole — COMMENTED** [review]
Looks alright, but I'm wondering if this PR will intend to cover the tests from #10913 eventually especially since those are the more important ones? Seeing how #10913 is already closed by now, it looks ok to me to just carry them over, unless there are separate arrangements? @moziliar

**Comment by rrtheonlyone** [comment]
@hhdqirui Please carry over the tests from #10913 and let us know when this PR is ready for review.

**Review by halfwhole — COMMENTED** [review]
Looks good, the main cases and failure modes are there. We could still afford to test the case when there are multiple errors involved as well

**Comment by hhdqirui** [comment]
Hi! This PR is ready for review.

**Review by halfwhole — APPROVED** [review]
LGTM!

**Review by rrtheonlyone — APPROVED** [review]
LGTM

**Pull request merged**
