### PR TITLE
StudentsLogicTest fails due to wrong ordering #5442

### LINKED ISSUE #5442: StudentsLogicTest fails due to wrong ordering
In testGetStudentsForGoogleId(),
```
StudentAttributes firstStudentReceived = listReceivedUsingStudentInCourse1.get(0);
        // First student received turned out to be the one from course 2
        assertEquals(studentInTwoCoursesInCourse2.email,
                firstStudentReceived.email);
        assertEquals(studentInTwoCoursesInCourse2.name,
                firstStudentReceived.name);
        assertEquals(studentInTwoCoursesInCourse2.course,
                firstStudentReceived.course);
```
The order of students returned from studentsLogic.getStudentsForGoogleId is assumed to be constant, causing the test to fail.

### PR DESCRIPTION
**Pull request by LowWeiLin**
Fixes #5442

### CODE REVIEW

**Comment by junhaoyap** [comment]
Hmm curious, how did a failed test get pass CI?

**Comment by LowWeiLin** [comment]
It does not fail all the time.

**Comment by junhaoyap** [comment]
Oh, I was reading the title literally as it is, got it!

**Comment by junhaoyap** [comment]
@LowWeiLin looks good, @damithc please take a look

**Pull request merged**
