### PR TITLE
Shrink down the size of HTML test files #4692

### LINKED ISSUE #4692: Shrink down the size of HTML test files
1. All the HTML test files are pushed forward by 3 spaces (i.e starts at one level of indentation); that's really a huge waste.
2. `<br/>` is _not_ compliant to our style guide, not to mention that it's wasting space (one extra char needed per void HTML element).

In fact, those two have been in TODO in `HtmlHelper` for a while.
screen shot 2016-01-31 at 11 56 34 am
screen shot 2016-01-31 at 11 58 02 am

This will wreak havoc because _every single line of every single HTML test file in existence_ will be affected, but it needs to be done eventually.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4692 
Code-wise these are all the changes needed. But regenerating the HTML files will affect everyone who's involved in updating HTML test files, so putting this on hold until the number of such people is minimised.

### CODE REVIEW

**Comment by thyageshm** [comment]
@wkurniawan07 I think you can complete this one as soon as the current release is over, ie, Wednesday night. Lets complete reviewing @4734 and @4732 by this release and then finish this one

**Comment by wkurniawan07** [comment]
My plan was to wait until there's only few PRs changing HTML files (perhaps 3-4) then finish this. I could be evil and just wreak havoc by finishing this now, but let's not :p

**Comment by thyageshm** [comment]
Haha I dint mean to wreck havoc, but I think the most non-destructive time would be right after a release as most PRs would be in early stages at that time. I am not sure if we will reach a time when only 3-4 prs are open in the next few weeks. But I guess 4734 and 4732 are not going to be done by this release, so I guess we have to postpone this one....

**Comment by thyageshm** [comment]
I think @kanghj has been oversubscribed this release :-P

**Comment by wkurniawan07** [comment]
Currently the PRs touching HTML files are #4664, #4704, #4749, #4751. I'll wait until it's down to 2 and then I'll open the can of worms :p

Meanwhile, feel free to check the code changes. Aside from the two TODOs mentioned in the issue thread, these optimizations are done:
- Indentation is not added after html/head/body tags (those top-level ones); this also means we can seamlessly convert from full HTML check to partial and vice versa.
- Line breaks in text nodes are removed and the texts separated are joined by a single whitespace. As the result, this:
```html
<p>
  This is a text that               
  (no longer)      
  contains line break
</p>
```
and this:
```html
<p>
  This is a text that (no longer) contains line break
</p>
```
are no longer treated as different, rightly so because they are treated that way in HTML. This essentially fixes #678 (which is not outdated at all).

I also regenerated two files for demo. Feel free to check them to see the effects of the optimizations.

**Comment by thyageshm** [comment]
Thats great! removing the indentation of top level nodes is brilliant. The two html generated look fine. Lets wait for at least the larger ones of the those 4 PRs to be closed. (Unless they are okay with running the test suite one more time using GodMode).

**Comment by thyageshm** [comment]
Hey shall we finish this one this release? There seems to be few html updates in the other PRs right now.

**Comment by wkurniawan07** [comment]
We're left with #4813, #4751, and #4749. I'll proceed once #4751 is merged, which should be very soon.
@damithc I think you can review this already since all that's left to do afterwards is regenerating every single HTML file.

**Comment by wkurniawan07** [comment]
Done, at last! As a quantitative evidence of the reduction, the HTML language percentage shrinks from 76.6% to 72.5%.

**Pull request merged**
