### PR TITLE
Instructor: edit session: visible date: reject incorrect dates #8791

### LINKED ISSUE #8791: Instructor: edit session: visible date: reject incorrect dates
v6.5.1

Steps:
1. Login as instructor
2. Edit visible date of an existing session by modifying the text box (not the date picker)
3. Enter an incorrect date where the day doesn't match the date e.g., Take a valid date and change the date but not the day -- Apr 19th is not a Tuesday
image

4. Save

Expected: The date is rejected or auto-corrected upon save
Actual: The incorrect date is saved

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #8791 
Added method in Time helper to change day according to date if not correct

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
Status :: ongoing

**Comment by nidhi98gupta** [comment]
@shaharyar-shamshi Hi, working on this?

**Comment by shaharyar-shamshi** [comment]
@nidhi98gupta Yes I am working on this. Actually due to scheduled exam I was not able work on this but resume soon .

**Comment by nidhi98gupta** [comment]
@shaharyar-shamshi Any updates?

**Comment by shaharyar-shamshi** [comment]
@nidhi98gupta  I am sorry I am consumed somewhere else you can take this good luck

**Comment by tshradheya** [comment]
Closing this PR due to inactivity and because there is an current existing PR resolving the corresponding issue

**Pull request closed without merging**
