### PR TITLE
Rich text boxes: make the toolbar appear over existing content #7063

### LINKED ISSUE #7063: Rich text boxes: make the toolbar appear over existing content
Currently, when the user clicks on a rich text form field, the formatting toolbar is inserted above the form field, shifting all elements below it. When the user clicks outside the form field after editing it, the toolbar disappears and elements below it shifts again. This jumping of page content gets in the way of a smooth user user experience. It can also result in 'mishit clicks' i.e. user tries to click a button but ends up clicking something else because content moves with the click.

Options:
1. make the toolbar stay fixed all the time
2. make the toolbar appear on top of the existing content above the form field (I believe this is the default mode but we changed it to the current behavior in a misguided attempt to improve user experience -- my bad 😢  )

Before clicking:
image

After clicking:
image

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7063 

**Old PR:** #7117.

**Reason for new PR**: Too many merge conflicts in Expected HTML files for UI Tests.

**Outline of Solution:**

Remove `inline: true` from the necessary `.es6` files to allow the tineMCE editor to default to its original behaviour of staying fixed regardless of mouse-pointer focus. (Same as old PR).

The bugs resulting from the old PR were only present in the `Comments` feature which has been entirely removed in PR #7334

### CODE REVIEW

**Comment by damithc** [comment]
@HirdayGupta how hard is it to use the other option? i.e. make the toolbar appear only when the user clicks on the text box (i.e. not fixed) but the toolbar hovers _above_ the the existing form content (covers existing content instead of displacing them).
I'm asking because if we show the tool bar in every text box, it's going to take a lot of space.

**Comment by HirdayGupta** [comment]
@damithc looking into the implementation now. 
However, I'm not sure if the hover functionality is the best approach. The fixed toolbar does not hide any content thus preventing mistakes on the user's end. There is also the additional problem of the interface looking ugly if the Toolbar ends up overflowing out of the panel.

**Comment by damithc** [comment]
That's true. May be you create 2 PRs and we can see how the two compare.

**Comment by HirdayGupta** [comment]
@damithc will do. 

Meanwhile, I need some assistance with the failing tests on this PR. I'm not entirely sure how to deal with these errors: 

- **`NoSuchElementException`** on **`InstructorFeedbackResultsPageUiTest`** (error occurs at this line: `resultsPage.addFeedbackResponseComment("showResponseCommentAddForm-0-0-1-1", "");`)

- **`ElementNotVisibleException`** on **`InstructorEditStudentFeedbackPageUiTest`** (error occurs on this line: `submitPage.fillResponseTextBox(1, 0, "");`)

- **`AssertionError`** on **`InstructorFeedbackSubmitPageUiTest`** (error on line `assertTrue(submitPage.isNamedElementVisible(Const.ParamsNames.FEEDBACK_RESPONSE_TEXT + "-" + qnNumber + "-" + responseNumber));`)

**Comment by damithc** [comment]
> Meanwhile, I need some assistance with the failing tests on this PR. I'm not entirely sure how to deal with these errors:
> 
> NoSuchElementException on InstructorFeedbackResultsPageUiTest (error occurs at this line: resultsPage.addFeedbackResponseComment("showResponseCommentAddForm-0-0-1-1", "");)
> 
> ElementNotVisibleException on InstructorEditStudentFeedbackPageUiTest (error occurs on this line: submitPage.fillResponseTextBox(1, 0, "");)
> 
> AssertionError on InstructorFeedbackSubmitPageUiTest (error on line assertTrue(submitPage.isNamedElementVisible(Const.ParamsNames.FEEDBACK_RESPONSE_TEXT + "-" + qnNumber + "-" + responseNumber));)

@TEAMMATES/activedevs can help?

**Comment by HirdayGupta** [comment]
Closing because an alternate solution to the issue is being implemented in PR #7427.

**Pull request closed without merging**
