### PR TITLE
One-member teams cannot submit MCQ (multiple choice) questions #6154

### LINKED ISSUE #6154: One-member teams cannot submit MCQ (multiple choice) questions
There is an error upon submission for the student who is the only team member. In the session that surfaced this bug, there are multiple questions and only the response to the first question (which happens to be a self-evaluation question) is saved.

### PR DESCRIPTION
**Pull request by leelunn**
Fixes #6154

### CODE REVIEW

**Comment by leelunn** [comment]
I need some help with this.  I'm not sure why there are commits from other contributors listed here, and I'm not sure why travis ci is failing.  The static analysis passes on my system.

**Comment by wkurniawan07** [comment]
@leelunn looks like your starting branch is not `master`, but rather `5460-mcq-qn-right-align-generate-option`. You need to start all works fresh from the `master` branch. You can do a `git rebase` to remove all the unrelated commits.
As for the ESLint and stylelint failures, I've opened #6199 and it will be resolved soon.

**Comment by wkurniawan07** [comment]
@leelunn also, can you revert the second and third commits? I know those fixes are necessary for the later ESLint versions (if I'm not mistaken from 3.10.0 onwards) but we are not concerned with those right now.

**Comment by leelunn** [comment]
@wkurniawan07 Yes. It may take me a bit to figure it out.

**Pull request closed without merging**
