### PR TITLE
[#9367] Display hints/messages to users when they have no internet connection

### PR DESCRIPTION
**Pull request by RonakLakhotia**
Part of #9367 

**Outline of Solution**

I tried to display the message on the students profile page. Not quite sure of the implementation though. Would like to get a review on the way I approached to write the code.
Here is how the page looks when the user is disconnected.

screenshot 2019-01-28 at 12 06 49 am

### CODE REVIEW

**Comment by monmanuela** [comment]
Just a suggestion, maybe the message to the user can be made more obvious using "❗️" icon, a box with red borders, or a modal like this?
image
 The current small black text seems quite easy to miss

**Comment by wkurniawan07** [comment]
@RonakLakhotia One issue: Student profile page is the wrong way to place this.

**Comment by RonakLakhotia** [comment]
Yeah , working on it

**Comment by wkurniawan07** [comment]
Also, you don't have to be worried about display/aesthetics for now. There's another issue reserved for that in #9366.

**Pull request merged**
