### PR TITLE
[#11210] Feedback Rubric Question: Suggestion for Statistics Per Recipient

### LINKED ISSUE #11210: Feedback Rubric Question: Suggestion for Statistics Per Recipient
Right now in latest production branch we have the per recipient statistics feature. This looks like this:

Screenshot 2021-06-20 at 8 43 44 PM

The **Per Recipient Statistics (Overall)** feature is taking the sum of the average of sub questions divided by the number of sub questions. This opens up some ambiguity as to what value to use when there is no responses for the sub questions. The current implementation takes it as zero and uses that in the average calculations. **An alternative is to ignore sub questions with no responses completely. However, it just feels a little clunky to do it this way.**

I want to propose a slightly different format instead. Like this (for the same example above), in csv notation:

Screenshot 2021-06-20 at 9 56 41 PM

The new format uses a similar notation as **Response Summary** and **Per Recipient Statistics (Per Criterion)**. We take the weighted sum and divide by the number of responses. This will give an indication to where a certain recipient lies in the range of weights that currently exist. There also won't be any ambiguity of zero weight vs no responses. We can also remove the assumption that all questions are equally weighted.

For your kind review @damithc.

### PR DESCRIPTION
**Pull request by u6867511**
Fixes #11210 

**Outline of Solution**

Updated Rubric Question "Per Recipient Statistics (Overall)" table to reflect new proposed formatting. Changed column names and content, added new methods for calculating statistics, edited Session Result snapshot to reflect formatting changes.

### CODE REVIEW

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

**Review by NicolasCwy — APPROVED** [review]
LGTM

**Comment by NicolasCwy** [comment]
@zhaojj2209 Tried running the E2E tests 3-4 times but it still fails. The changes doesn't seem related to the failure though, any idea what might be the cause?

**Comment by fsgmhoward** [comment]
> @zhaojj2209 Tried running the E2E tests 3-4 times but it still fails. The changes doesn't seem related to the failure though, any idea what might be the cause?

It has been failing persistently for quite a number of PRs. I guess since it is not related this PR is good to be merged?

Person to merge: please do a double check on this.

**Pull request merged**
