### PR TITLE
InstructorFeedbackResultsPage: make span scrollable to fit the table to copy #8437

### LINKED ISSUE #8437: InstructorFeedbackResultsPage: make span scrollable to fit the table to copy
**Description of feature/enhancement**

In the instructor feedback results page, instructors can directly copy the data in the page to an excel spreadsheet if non-english characters are not displayed properly in the downloaded file:

image

However, if there are feedback and comments given by students/instructors, the resulting table protrudes from the given span:

image

The span can be made scrollable in order to fit the entire table within the span.

**Justification**

By allowing the table to fit within the span, it will improve the look of the table. Additionally, it will make the table more readable for instructors (particularly the alternating transparent rows) so that they can take a look at the data before copying to their excel spreadsheet.

### PR DESCRIPTION
**Pull request by Shashwat-Garg**
Fixes #8437
Added code to CSS stylesheet for the overflow manipulation.

### CODE REVIEW

**Comment by Shashwat-Garg** [comment]
@joanneong Please check if I did it the right way. :)

**Comment by Shashwat-Garg** [comment]
@joanneong Gentle review reminder. :)

**Comment by joanneong** [comment]
@Shashwat-Garg Give me some time, and I will review by this Friday night!

**Comment by sukanta-27** [comment]
@Shashwat-Garg  You made all the changes (in #8401) directly on your `master` branch instead of creating a new branch.

**Comment by Shashwat-Garg** [comment]
@sukanta-27 @joanneong Really sorry for this confusion. I did a terrible mistake by making changes directly to `master` branch. Can I do anything now so that the older commits don't show up ?
I deeply regret this inconvenience.

**Comment by joanneong** [comment]
@Shashwat-Garg Actually if you did not change the `8437-make-span-scrollable` branch, you can just [switch the master branch to that branch instead](https://stackoverflow.com/questions/2763006/make-the-current-git-branch-a-master-branch), and then create a new branch from there?

**Comment by whipermr5** [comment]
@Shashwat-Garg Hard reset your master branch to before your first commit, pull from upstream to sync, then force push to origin (your repo).

**Pull request closed without merging**
