### PR TITLE
[#10042] Improve mobile UI for course details and course edit pages

### PR DESCRIPTION
**Pull request by sandysingh11918**
Part of #10042 Improve UI for Mobile Compatibility

Put the buttons in single line and put spacing between both vertically and horizontally.
Replace block buttons in place of some links in edit course page.
Move some text to center.

### CODE REVIEW

**Comment by madanalogy** [comment]
Hello, thanks for contributing to TEAMMATES! Just a couple of pointers:
- You need to attach either a screenshot or short clip showing your changes.
- Please do not use Github auto-closing keywords.
- It might be worth your while to read the issue more closely, examples for the two pointers above are provided in the issue.
- Your PR is failing the CI check because you need to update your snapshot. You can check out https://github.com/TEAMMATES/teammates/pull/9997#issuecomment-605014375 for a guide on how to do just that.

Do let me know if any of the pointers are unclear or if you need more help with anything :)

**Comment by sandysingh11918** [comment]
Screenshot from 2020-05-15 11-43-07
Screenshot from 2020-05-15 11-43-16
Screenshot from 2020-05-15 11-44-28
Screenshot from 2020-05-15 11-44-47

**Comment by madanalogy** [comment]
> Put the screenshots as requested

Could you have a before vs after comparison? You can just edit your comment and let me know when it's done. You can refer to https://github.com/TEAMMATES/teammates/pull/10052 and https://github.com/TEAMMATES/teammates/pull/10048 thanks!

**Comment by sandysingh11918** [comment]
Old

Screenshot from 2020-05-15 18-07-52

new

Screenshot from 2020-05-15 11-43-07
Screenshot from 2020-05-15 11-43-16

old 

Screenshot from 2020-05-15 18-08-30

new 

Screenshot from 2020-05-15 18-25-45

old

Screenshot from 2020-05-15 18-08-36

new

Screenshot from 2020-05-15 11-44-47

**Comment by sandysingh11918** [comment]
its done. i have commented the before vs after comparison

**Pull request merged**
