### PR TITLE
Use enum instead of string for gender field in StudentProfileAttributes and related classes #7603

### LINKED ISSUE #7603: Use enum instead of string for gender field in StudentProfileAttributes and related classes
Replace 'gender' field with corresponding enum for StudentProfileAttributes and related classes.
Currently gender field is String that only accepts "male", "female" or "other" values, so It's better to use enum over String value in that case.

### PR DESCRIPTION
**Pull request by ParmaarK**
Fixes #7603 

Help needed : I tried to attempt this. However not sure if I did it correctly. Please guide.

### CODE REVIEW

**Comment by leeyimin** [comment]
@ParmaarK Putting this PR on hold for now as #7338 will likely affect this PR significantly. We will start reviewing this PR again after that!

**Comment by whipermr5** [comment]
@ParmaarK I suggest starting over as #7338 changed the `StudentProfileAttributes and related classes` quite significantly.

**Comment by LimeTheCoder** [comment]
Hi, @ParmaarK Please resolve conflicts and I'll guide you through this issue.

**Comment by whipermr5** [comment]
@ParmaarK Closing due to inactivity (we try to keep the PR list clean). Feel free to reopen when you have new changes to push :)

**Pull request closed without merging**
