### PR TITLE
[#11388] Remove numOf fields from question details structure

### LINKED ISSUE #11388: Remove numOf* fields from question details structure
https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L33-L36

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java#L30-L31

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java#L35-L36

These question details have `numOf*` fields. They are unnecessary and all places where they are used can be replaced with `.size()` (or `.length`) of the list they are representing without any side effect. In fact, adding `numOf*` adds unnecessary risk of the two numbers getting out of sync.

### PR DESCRIPTION
**Pull request by Emp923**
Fixes #11388 

removed numOfRubricChoices from FeebackRubricQuestionDetails.java and replaced with rubricChoices.size()
removed numOfRubricSubQuestions from FeebackRubricQuestionDetails.java and replaced with rubricSubQuestions.size()
removed numOfMcqChoices from FeedbackMcqQuestionDetails.java and replaced with mcqChoices.size()
removed numOfConstSumOptions from FeedbackConstantSumQuestionDetails.java and replaced with constSumOptions.size()

removed references to setters for above fields and removed setters from each class listed above

### CODE REVIEW

**Comment by halfwhole** [comment]
Hi @Emp923, is the PR ready for review?

**Comment by Emp923** [comment]
Hi @halfwhole yes this PR is ready for review. Thanks!

**Review by jianhandev — CHANGES_REQUESTED** [review]
@Emp923 looks like there are still traces of `numOf*` fields in files e.g. `feedbackSessionResultsRubricResults.json`. Try doing a full search on all the files to identify the occurrence of `numOf*` fields. Also remember to update the comments for the methods affected.

**Review by jianhandev — APPROVED** [review]
@Emp923 thanks for the work here, looks good!

**Review by madanalogy — APPROVED** [review]

**Pull request merged**
