### PR TITLE
[#9096] removed unused methods from Logic.java

### LINKED ISSUE #9096: Logic.java: Clean up unused methods.
There are several unused methods (or methods only used in test) in `Logic.java`. See if we can remove them as well as their correspoding methods `*Db`.

### PR DESCRIPTION
**Pull request by IAmPramod**
Fixes #9096

### CODE REVIEW

**Comment by IAmPramod** [comment]
@xpdavid Ready for review

**Comment by IAmPramod** [comment]
> Is this all unused methods?

Yes. All methods were unused.

**Comment by xpdavid** [comment]
> Yes. All methods were unused.

No, I am asking whether all unused methods in Logic.java have being removed in this PR?

**Comment by IAmPramod** [comment]
> > Yes. All methods were unused.
> 
> No, I am asking whether all unused methods in Logic.java have being removed in this PR?

Yes, all unused methods have been removed.

**Comment by IAmPramod** [comment]
@nidhi98gupta reminder for review!

**Comment by IAmPramod** [comment]
@xpdavid @nidhi98gupta Reminder for review.

**Comment by IAmPramod** [comment]
@xpdavid @nidhi98gupta Reminder to review!

**Pull request merged**
