### PR TITLE
Instructor: feedback edit page: align tooltip to fit label for rank (recipients) question #8509

### LINKED ISSUE #8509: Instructor: feedback edit page: align tooltip to fit label for rank (recipients) question
**Description of feature/enhancement**

As an instructor, creating a rank (recipients) question can produce the following:

image

Here, the tooltip is obviously not aligned with the label which it is referring to. This can be a `d.firstTimers` issue since it should be a relatively simple fix.

### PR DESCRIPTION
**Pull request by VirinchiSainath**
Fixes #8509 

Edited the bootstrap classes.

Now looking,
github

### CODE REVIEW

**Comment by sukanta-27** [comment]
Before any senior developer reviews it, here are some pointers.
- Do check our [guide](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr) for submitting PRs. your PR title is not accurate.
- Travis CI build needs to pass for you to get a review.
- As this is a UI related issue, it will be helpful if you give a screenshot of the change

**Comment by VirinchiSainath** [comment]
Hi @sukanta-27, I don't get, can you help me out.

1. On running the test suit in my IntelliJ is giving some some errors. Does that mean, I made a mistake in my installation?
2. My code changes are so futile. I just changed that bootstrap class. How is this change creating a failed Travis CI build ?

**Comment by VirinchiSainath** [comment]
>Insufficient informatioin. what kind of error?

baseautomatedactiontest
capture
studentfeedbackresultspageaction

These are the errors on running CI tests.

**Comment by sukanta-27** [comment]
@VirinchiSainath Go through the installation process documents again and see if you missed any step while installing or not.

- [ ] [setting up](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md)
- [ ] [IDE setup](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md)
- [ ] [development](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md)
- [ ] [Troubleshooting](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md)

The problem is most probably on your installation or something, as if it was caused by your changes, the same tests would have failed in Travis CI as well.

(Anyway if you cannot solve your problem even after all this, feel free to open a issue and state your problem)

**Comment by craaaa** [comment]
Hi @VirinchiSainath, any updates on your progress?

**Comment by wkurniawan07** [comment]
@VirinchiSainath Closing due to inactivity for a long period. Feel free to request for reopen if you're ready to resume the work here.

**Pull request closed without merging**
