### PR TITLE
Update instructions for running test outside of Eclipse #5380

### LINKED ISSUE #5380: Update instructions for running test outside of Eclipse
With Gradle up and running, the same configuration used for Travis can be used locally as well without the need for extra `runtests.*` files.
- We need to maintain only one config file instead of three.
- The test run result can be supplied to `jacocoTestReport` for coverage report generation.

Although it's not without drawback:
- We lose the ability to run only certain test segments.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5380 

The command pretty much simulates how the test is run in the Travis CI environment.

### CODE REVIEW

**Comment by JosephineKwa** [comment]
The changes should be fine if they have been tested and work fine on your windows and mac! The `enhancerRun` failure is probably specific to my laptop. @kanghj could you help run the tests using `gradlew.bat -b travis.gradle travisTests` and check that it works too?

**Comment by kanghj** [comment]
<code>enhancerRun</code> doesn't work for me too

**Comment by wkurniawan07** [comment]
Weird thing is, it works on my Windows (tested yesterday). @kanghj @JosephineKwa can you copy/paste what is shown on the console, and we'll try to troubleshoot together?

**Comment by JosephineKwa** [comment]
Here's the error message on my console
```
C:\Users\kwa\git\teammates>gradlew.bat -b travis.gradle travisTests
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:enhancerRun FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\kwa\git\teammates\travis.gradle' line: 136

* What went wrong:
Execution failed for task ':enhancerRun'.
> taskdef class com.google.appengine.tools.enhancer.EnhancerTask cannot be found
 using the classloader AntClassLoader[C:\Users\kwa\git\teammates\gradle\wrapper\gradle-wrapper.jar]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.049 secs
```

**Comment by wkurniawan07** [comment]
@JosephineKwa add these lines to `travis.gradle`:
```
task printPath {
    ant.echo(System.getProperty("java.class.path"))
    ant.echo("${project.gradle.gradleUserHomeDir}/appengine-sdk/appengine-java-sdk-${appengineVersion}/lib/appengine-tools-api.jar")
}
```
then run `gradlew.bat -b travis.gradle printPath`. Look at the two paths printed, do they exist in your directory?

**Comment by JosephineKwa** [comment]
Yup, I get this message
```
C:\Users\kwa\git\teammates>gradlew.bat -b travis.gradle printPath
[ant:echo] C:\Users\kwa\git\teammates\\gradle\wrapper\gradle-wrapper.jar
[ant:echo] C:\Users\kwa\.gradle/appengine-sdk/appengine-java-sdk-1.9.27/lib/appengine-tools-api.jar
:printPath UP-TO-DATE

BUILD SUCCESSFUL

Total time: 6.578 secs
```

**Comment by wkurniawan07** [comment]
@JosephineKwa I think I get what's wrong. Try and add this line right after `def path = ...`:
```
path = path.replaceAll("\\\\", "/")
```
then run `gradlew.bat -b travis.gradle enhancerRun` again.

**Comment by wkurniawan07** [comment]
@JosephineKwa I figured it out, you need to have `gradle.properties` file in the root folder. Make it using `gradle.properties.template`. Afterwards can you try running the `enhancerRun` command again? There's no need for the extra line I gave before.

**Comment by JosephineKwa** [comment]
Hm, I'm still getting the error though, here is a screenshot of my gradle.properties
screenshot 268

and the console output
```
C:\Users\kwa\git\teammates>gradlew.bat -b travis.gradle enhancerRun
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:enhancerRun FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\kwa\git\teammates\travis.gradle' line: 136

* What went wrong:
Execution failed for task ':enhancerRun'.
> taskdef class com.google.appengine.tools.enhancer.EnhancerTask cannot be found
 using the classloader AntClassLoader[C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-launcher-2.12.jar;C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-core-2.12.jar;C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-base-services-2.12.jar]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.828 secs
```

**Comment by wkurniawan07** [comment]
@JosephineKwa that's weird, can you run the `printPath` task I gave above again and tell me the output this time?

**Comment by wkurniawan07** [comment]
@kanghj can you try the same as well? Make `gradle.properties`, run the same command, and if it still fails copy and run the `printPath` command I gave above.

**Comment by JosephineKwa** [comment]
Hey, here's the console output after running `printPath` with `gradle.properties`
```
C:\Users\kwa\git\teammates>gradlew.bat -b travis.gradle printPath
[ant:echo] C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-launcher-2.12.jar
[ant:echo] C:\Users\kwa\.gradle/appengine-sdk/appengine-java-sdk-1.9.27/lib/appengine-tools-api.jar
:printPath UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2.107 secs
```

**Comment by wkurniawan07** [comment]
@JosephineKwa try and do the `path = path.replaceAll("\\\\", "/")` trick again.

**Comment by JosephineKwa** [comment]
For `printPath` I get 
```
C:\Users\kwa\git\teammates>gradlew.bat -b travis.gradle printPath
[ant:echo] C:/Users/kwa/.gradle/wrapper/dists/gradle-2.12-bin/avhnk0p45wmm16bas931at19r/gradle-2.12/lib/gradle-launcher-2.12.jar
[ant:echo] C:/Users/kwa/.gradle/appengine-sdk/appengine-java-sdk-1.9.27/lib/appengine-tools-api.jar
:printPath UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2.368 secs
```
when I add this to `travis.gradle`

```
task printPath {
    ant.echo(System.getProperty("java.class.path").replaceAll("\\\\", "/"))
    ant.echo(("${project.gradle.gradleUserHomeDir}/appengine-sdk/appengine-java-sdk-${appengineVersion}/lib/appengine-tools-api.jar").replaceAll("\\\\", "/"))
}
```

For `enhancerRun` I get
```
C:\Users\kwa\git\teammates>gradlew.bat -b travis.gradle enhancerRun
[ant:echo] C:/Users/kwa/.gradle/wrapper/dists/gradle-2.12-bin/avhnk0p45wmm16bas931at19r/gradle-2.12/lib/gradle-launcher-2.12.jar
[ant:echo] C:/Users/kwa/.gradle/appengine-sdk/appengine-java-sdk-1.9.27/lib/appengine-tools-api.jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:enhancerRun
[ant:echo] C:/Users/kwa/.gradle/wrapper/dists/gradle-2.12-bin/avhnk0p45wmm16bas931at19r/gradle-2.12/lib/gradle-launcher-2.12.jar:C:/Users/kwa/.gradle/appengine-sdk/appengine-java-sdk-1.9.27/lib/appengine-tools-api.jar
:enhancerRun FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\kwa\git\teammates\travis.gradle' line: 138

* What went wrong:
Execution failed for task ':enhancerRun'.
> taskdef class com.google.appengine.tools.enhancer.EnhancerTask cannot be found
 using the classloader AntClassLoader[C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-launcher-2.12.jar;C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-core-2.12.jar;C:\Users\kwa\.gradle\wrapper\dists\gradle-2.12-bin\avhnk0p45wmm16bas931at19r\gradle-2.12\lib\gradle-base-services-2.12.jar]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.5 secs
```

when I add
```
path = path.replaceAll("\\\\", "/")
    ant.echo(path)
```
after `def path = ...`

**Comment by wkurniawan07** [comment]
@ashrayjain can you try this one also? Just try and run `./gradlew -b travis.gradle travisTests` locally when the dev server is running.

**Comment by ashrayjain** [comment]
@wkurniawan07 getting the same error as above.

**Comment by ashrayjain** [comment]
I think the problem is due to the app engine sdk not being downloaded before the enhancer is run. I started working for me after i ran `grade appengineRun` first. can you guys verify? If that the cause then we need to enforce this dependency.

**Comment by JosephineKwa** [comment]
EnhancerRun works for me if I run appengineRun first as well

**Comment by wkurniawan07** [comment]
Makes sense, I've had the SDK downloaded way before opening the issue, that should be why it never failed for me :p
Then again the dependency could be to the SDK download instead of the `appengineRun`. @kanghj when you try it, can you run `appengineDownloadSdk` first before `enhancerRun`?

**Comment by wkurniawan07** [comment]
Let's continue this one?

**Comment by JosephineKwa** [comment]
Successfully built on my laptop :).

**Comment by JosephineKwa** [comment]
Just to be sure, maybe it might be good to get developers who have not downloaded the SDK to test it out too. @kanghj @YongJieYongJie @chowyb

**Comment by kanghj** [comment]
Works for me

**Comment by JosephineKwa** [comment]
Should be good to merge :+1:

**Comment by chowyb** [comment]
Works for me too

**Comment by wkurniawan07** [comment]
@YongJieYongJie @LowWeiLin I forgot to add to the docs that you need `gradle.properties` to be configured first (very simple). Just get it from `gradle.properties.template`.

**Comment by YongJieYongJie** [comment]
Ran out of disk space while downloading =(

**Pull request merged**
