### PR TITLE
[#10568] Admin bulk-adding instructors: allow separation by tabs

### LINKED ISSUE #10568: Admin bulk-adding instructors: allow separation by tabs
image

This button doesn't seem to do anything.

### PR DESCRIPTION
**Pull request by IndeedSi**
Fixes #10568

**Outline of Solution**
I changed the regex to also split the lines by tabs

### CODE REVIEW

**Comment by tiuweehan** [comment]
@IndeedSi Thanks for your PR, your solution seems correct to me. For completeness sake, could you add some test cases as well?

**Comment by IndeedSi** [comment]
@tiuweehan  Thanks for taking a look! I added the tests for the change.

**Review by tiuweehan — APPROVED** [review]
@IndeedSi LGTM!

@madanalogy anything to add?

**Review by madanalogy — APPROVED** [review]
LGTM! Thanks for your contribution.

**Pull request merged**
