### PR TITLE
Remove additionalQuestionInfo.js import in instructorComments.jsp #6212

### LINKED ISSUE #6212: Remove additionalQuestionInfo.js import in instructorComments.jsp
Accidentally re-added in #6187 after removed in #6137.

### PR DESCRIPTION
**Pull request by Mynk96**
Fixes #6212

### CODE REVIEW

**Comment by junhaoyap** [comment]
@Mynk96 hi, I'm happy to see your first contribution to TEAMMATES, it seems that the jenkins CI build is currently failing and that's because we have UI testing

Other than removing it from the JSP file, it is necessary to tell the test file that it's removed from the HTML too!

**Comment by junhaoyap** [comment]
@Mynk96 that's a fast change, thank you! I'll take a look tomorrow once the build has passed (I expect it to pass at this point but who knows if anything will go wrong)

Not a huge issue since this is a small task, do take note that identical commit messages on different hashes are not recommend and that they are not supposed to be a replica of the issue message, commit messages before the eventual merge and squash into TEAMMATES should be a short message on what is done in the commit, in your case

```
Removed additionalQuestionInfo.js import in instructorComments.jsp
```

for the first commit is good

```
Removed additionalQuestionInfo.js html fragment in html test
```

would be a better commit message

It's good practice as it helps reviewers to manage the review process, especially for big pull requests that spans a few hundred lines

**Comment by Mynk96** [comment]
thank you.
it won'happen again

**Comment by junhaoyap** [comment]
@Mynk96 thank you for the fix, it's working now! All good, the first few contributions to any project is when we get more comments, we all get better over time just as you are now 👍 

@wkurniawan07 @damithc please take a look!

**Comment by wkurniawan07** [comment]
I don't really need to take a look at all PRs, but this looks good :+1:

**Comment by damithc** [comment]
@junhaoyap if the code is acceptable, please 'approve' using GitHub review feature.

**Comment by damithc** [comment]
@Mynk96 The PR title and branch name does not follow our conventions.

**Comment by Mynk96** [comment]
can you please post the link of coding conventions. I am not able to find it?

**Comment by damithc** [comment]
@Mynk96 https://github.com/TEAMMATES/teammates/blob/master/docs/process.md

**Comment by Mynk96** [comment]
should i have to create a new pr if I change the branchname?

**Comment by damithc** [comment]
@Mynk96 we'll overlook this branch name problem because this is your first PR :-)

**Comment by Mynk96** [comment]
Thank you.
from next time i'll stick to the conventions.

**Comment by damithc** [comment]
@Mynk96 The PR name is still not correct. You should look at other PRs to see if yours is consistent with them.

**Comment by junhaoyap** [comment]
It looks correct to me now, going to approve via GitHub, take note of the comments from everyone for the next PRs!

**Comment by wkurniawan07** [comment]
@junhaoyap you can merge this later once it's all green :+1:
@Mynk96 thanks for your contribution! May we get your name to be added to our contributors list?

**Comment by Mynk96** [comment]
Mayank Harsani

**Pull request merged**
