### PR TITLE
Uncaught typo in FeedbackResponseCommentRow.java #7155

### LINKED ISSUE #7155: Uncaught typo in FeedbackResponseCommentRow.java
Typo caught in issue #6989 also found in src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java

Typo did not show up in CheckStyle Audit: 
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html#f-/Users/XP/Documents/teammates-git/src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java

responseVisiblities is not a word according to provided dictionary. Multiple occurences beginning with: 
```
Map<FeedbackParticipantType, Boolean> responseVisiblities)
```

### PR DESCRIPTION
**Pull request by thejosharcher**
Fixes #7155 

Fixed typo on line 53 and 56 of FeedbackResponseCommentRow.java. Changed "responseVisiblities" to "responseVisibilities" to correct the spelling error.

### CODE REVIEW

**Comment by thejosharcher** [comment]
s.ToReview

**Comment by whipermr5** [comment]
Hey @thejosharcher, there are still two more instances of the typo. Also, take note that our PR title convention doesn't have the `Fixes` keyword nor the periods. I've helped you rename it this time :)

The commits also don't need to mention the issue number, to avoid cluttering up the timeline shown in the issue.

**Comment by thejosharcher** [comment]
@whipermr5 Thank you so much! My first time contributing to an open source project, so I am learning. Thanks again for the help and patience. I will go back and fix!

**Comment by thejosharcher** [comment]
I apologize, used the Fix # in the commit message again. I mixed it up.

**Comment by whipermr5** [comment]
@thejosharcher It's fine :) Thanks for your contribution!

**Comment by thejosharcher** [comment]
Accidental commit 👎 . Rolled it back.

**Pull request merged**
