### PR TITLE
[#11586] Remove trailing `@gmail.com` when checking for user ID equality

### PR DESCRIPTION
**Pull request by wkurniawan07**
Part of #11586

### CODE REVIEW

**Comment by xyliew25** [comment]
@wkurniawan07 I think `isAllowedAccess = userInfo != null && googleId.equals(userInfo.id);` in `GetRegkeyValidityAction.java` should be modified such that registered student/instructor can access the session submission/result page when clicked on the corresponding link. 

Regarding profiles, I think `getStudentProfileEntityFromDb()` in `ProfileDb.java` should be modified such that `StudentProfile` of old `googleId` can be retrieved. As for profile pictures, since both `PostStudentProfilePictureAction` and `DeleteStudentProfilePictureAction` are w.r.t. to new `googleId` while `GetStudentProfilePictureAction` is w.r.t. to old `googleId`, I'm not sure yet (still trying out myself) but I think we need to change `GetStudentProfilePictureAction` such that it first retrieves profile picture of new `googleId`, if null, then retrieves the profile picture of old `googleId`, and change `DeleteStudentProfilePictureAction` such that it deletes profile pictures of both old and new `googleId` if any.

**Comment by wkurniawan07** [comment]
@xyliew25 I missed the first one, so good catch. Regarding profiles, given how rare it is used in recent times, I don't think it is worth it to fix. I even dare to say that it will not see any new usage by the time we migrated the old google IDs.

**Comment by xyliew25** [comment]
@wkurniawan07 noted on the profiles.

**Review by xyliew25 — APPROVED** [review]
LGTM

**Pull request merged**
