### PR TITLE
[#12544] Rubric Question Statistics: Handle empty weights

### LINKED ISSUE #12544: Cannot download results of session due to
V8.28.1
A user reported that downloading results fails silently.

Upon checking, I found that the download action causes this error to appear in the Browser console.

image

Seems to be related to a particular question. Trying to view the results of that question results in the above error as well. In addition, the results show up without some stats tables, as shown below:
image

The missing tables appear if I tick this checkbox.
image

The question itself is a follows:
image

The user has 6 courses with similar sessions. One can be downloaded without a problem but all other 5 has this problem.

Let me know if you need more information.

### PR DESCRIPTION
**Pull request by jasonqiu212**
Fixes #12544 

**Changes:**
- Assign null weight values to `NO_VALUE`
- Skip over null weight values when calculating average weight
- Add explanation on usage of empty weights

**Screenshots:**
- Empty weights are displayed as empty string, as shown in the screenshots below (i.e. `[]`)

Viewing statistics:
Response Summary

- In above screenshot, calculation of average skips over empty weights
    - (7 * 0 + 8 * 10) / 15 = 5.33

Per Recipient Stats (Per Criterion)

- In above screenshot, calculation of average skips over empty weights
    - (1 * 0 + 1 * 10) / 2 = 5

Per Recipient Stats (Overall)

- In above screenshot, calculation of average skips over empty weights
    - (2 * 0 + 2 * 10) / 4 = 5

Downloaded result:
Downloaded result

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @jasonqiu212, I tried to leave the weight input box blank when creating a Rubric question, but am encountering a server error. Can I check if you're facing the error as well? Here's the input (with the error):
Screenshot 2023-08-08 at 4 45 59 PM

Snippet of stack trace:
```
java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
```

**Comment by jasonqiu212** [comment]
@weiquu, Thanks for flagging the issue! I believe it's due to the conversion between `null` and `NO_VALUE`. I reverted the empty input to be represented by `null`, and now it works fine.

**Comment by weiquu** [comment]
Thanks @jasonqiu212 for the changes! Just one more thing:
Screenshot 2023-08-10 at 11 22 05 PM

For this question, I set all options to have empty weights. I noted two possible areas of improvement:
1. The "Average" (and "Total") columns for Response Summary and Per Recipient Statistics (Per Criterion) should probably indicate that the average is not calculable, given that the answers all have empty weights. I would suggest indicating something like `-`. What do you think?
2. For the Per Recipient Statistics (Overall), the "Total" and "Per Criterion Average" columns should follow the same indication as above. In addition, the "Average" column should also show the same thing, instead of the `NaN` it shows now

**Comment by jasonqiu212** [comment]
@weiquu Yep, I agree! I will work on adding this indication of non-calculable averages (`-`). Thanks for pointing out this edge case!

**Comment by jasonqiu212** [comment]
As suggested by @weiquu, I display `-` to indicate that the aggregate value cannot be calculated when all values are empty.

Screen Shot 2023-08-15 at 12 23 04 AM

**Review by weiquu — APPROVED** [review]
LGTM! Thanks for the fix

**Comment by domlimm** [comment]
@jasonqiu212 @weiquu will get to this today

**Review by domlimm — APPROVED** [review]
LGTM! Very nice job @jasonqiu212! Thank you for fixing this 💯

**Comment by damithc** [comment]
@samuelfangjw shall we do a new release with this fix?

**Comment by damithc** [comment]
Fix deployed. Thanks for the fix @jasonqiu212 and @samuelfangjw @domlimm @weiquu for inputs/reviews.

**Pull request merged**
