### PR TITLE
[#11456] Unable to upload Profile Pictures on Local Machine

### LINKED ISSUE #11456: Unable to upload Profile Pictures on Local Machine
- **Commit SHA:** 065c199f74db0de7281f02232df54bc34b417ac9
- **Operating System:** Windows 10
- **JDK Version:**  openjdk 11
- **Node.js Version:** v14.18.0
- **Chrome Version (if applicable):** 95.0.4638.54

**What I was trying to do / What I need help with:**

The student's profile picture could not be uploaded when I tried to reproduce #11147:

image

**Attempts to resolve the problem**
I tried changing the below relative path into an absolute path and was able to upload profile pictures successfully with the LocalFileStorageService.java file found in the main/java/teammates/logic/core directory.:

`private static final String BASE_DIRECTORY = "../../filestorage-dev";`

to

`private static final String BASE_DIRECTORY = System.getProperty("user.dir") + "/filestorage-dev";`

### PR DESCRIPTION
**Pull request by itishrishikesh**
Fixes #11456

**Outline of Solution**
Changed value of `BASE_DIRECTORY` variable from `LocalFileStorageService.java` to absolute path from a relative path.

### CODE REVIEW

**Comment by jianhandev** [comment]
@itishrishikesh would you be able to provide some kind of proof that the issue is now fixed? Perhaps a short video recording or screenshots (of the before and after) would be good.

**Comment by itishrishikesh** [comment]
Hi @jianhandev here's a video of the before and after behavior of the application.

In the first (before changes were done) video, I wasn't able to view the uploaded profile picture and observed that in the console I was getting a `NoSuchFileException`:

https://user-images.githubusercontent.com/24785679/141644776-f297ddfe-a70c-4a82-be07-123baa58ce99.mp4


In the second (after changes were done) video, I was able to view the uploaded profile picture and delete upload the image:


https://user-images.githubusercontent.com/24785679/141644808-c36ab8c3-57dd-4843-8ee5-6203787be448.mp4

**Comment by itishrishikesh** [comment]
> @itishrishikesh would you be able to provide some kind of proof that the issue is now fixed? Perhaps a short video recording or screenshots (of the before and after) would be good.

Hi @jianhandev Just a reminder - let me know if something is wrong.

**Review by jianhandev — APPROVED** [review]
@itishrishikesh Thanks for the fix 👍

**Pull request merged**
