### PR TITLE
[#10331] Instructor course page: add sorting to archived/deleted courses

### LINKED ISSUE #10331: Instructor courses page: archived courses are not sorted
Current:
image

Expected: The list should be sorted by name (to match V6)

Suggested: Also make the table sortable.

### PR DESCRIPTION
**Pull request by niqiukun**
Fixes #10331

**Outline of Solution**

- Add sorting to archived/deleted courses tables
- Adjust the header size to match active courses

Should consider refactoring out the sortable header component in future as the current code is quite repetitive.

image

### CODE REVIEW

**Comment by ccyccyccy** [comment]
> Should consider refactoring out the sortable header component in future as the current code is quite repetitive.

I think you can reuse `SortableTableComponent` by modifying it a little to allow for different background colors.

**Comment by niqiukun** [comment]
> I think you can reuse SortableTableComponent by modifying it a little to allow for different background colors.

Shall we leave that to another PR? Because currently there are some other places where the SortableTableComponent is not used. We can do the refactoring altogether in one separate PR instead.

**Comment by ccyccyccy** [comment]
> Shall we leave that to another PR? Because currently there are some other places where the SortableTableComponent is not used. We can do the refactoring altogether in one separate PR instead.

Sounds good

**Comment by xpdavid** [comment]
> I think you can reuse SortableTableComponent by modifying it a little to allow for different background colors.

I don't think it is easy to do so in the case where the child component needs to fire events.

**Pull request merged**
