### PR TITLE
[#11124] Instructor downloading session results: course/session details are repeated for each question

### LINKED ISSUE #11124: Instructor downloading session results: course/session details are repeated for each question
When the instructor downloads the session results, the course ID and the session name seem to be repeated for each question. They should only appear once at the top.

image

### PR DESCRIPTION
**Pull request by ypinhsuan**
Fixes #11124

Before
image

After
image

The Course and Session Name will only appear once at the top after the change.

### CODE REVIEW

**Comment by moziliar** [comment]
Hi, thank you for your contribution. Could you also attach some snapshots before and after the change for ease of review?

**Comment by daongochieu2810** [comment]
Changes seem fine to me. The e2e check seems to fail at `teammates.e2e.cases.InstructorFeedbackResultsPageE2ETest`, probably because of the new changes in format. Please help look into it

**Comment by ypinhsuan** [comment]
Added screenshots and made changes to pass the test

**Review by daongochieu2810 — APPROVED** [review]

**Review by madanalogy — APPROVED** [review]
LGTM

**Pull request merged**
