### PR TITLE
[#11388] Remove numOf* fields from question details structure

### LINKED ISSUE #11388: Remove numOf* fields from question details structure
https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L33-L36

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java#L30-L31

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java#L35-L36

These question details have `numOf*` fields. They are unnecessary and all places where they are used can be replaced with `.size()` (or `.length`) of the list they are representing without any side effect. In fact, adding `numOf*` adds unnecessary risk of the two numbers getting out of sync.

### PR DESCRIPTION
**Pull request by thefreakingmind**
Fixes #11388 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

Solved Issue  #11388

### CODE REVIEW

**Comment by halfwhole** [comment]
Hey @thefreakingmind, it looks like there are still some remaining issues with component and E2E tests! In particular, it looks like the frontend still depends on the numOf* fields which were removed. Please tell us when it's ready for review after amending the relevant tests, thanks!

**Comment by thefreakingmind** [comment]
Sure. I am actually a Backend Java Developer, So Little less comfortable with frontend. I ll change these files.

**Comment by jianhandev** [comment]
@thefreakingmind let us know once this is ready for review, thank you :)

**Comment by damithc** [comment]
Guys, This PR seems to be stalling (no activities for the past 7 days). :snail: :cry:
Hope someone can get it to move forward again soon...

**Comment by thefreakingmind** [comment]
> Guys, This PR seems to be stalling (no activities for the past 7 days). 🐌 😢
> Hope someone can get it to move forward again soon...

Hi @damithc I am working on this one. There are certain frontend changes I am working on. Was busy with some work. will complete this on this weekend

**Comment by thefreakingmind** [comment]
All the Java files changes are done. I am not experienced with frontend so it's taking me some time to make changes here.

**Comment by moziliar** [comment]
@thefreakingmind No worries.

At the same time, I would recommend fixing the tests in the meantime. Let us know if you need any help!

**Comment by moziliar** [comment]
@thefreakingmind Hi, any update from you? There are many developers who want to work on the same issue.

Will follow the protocol and offer the issue up for grab if it remains inactive in another 3 days.

**Comment by jianhandev** [comment]
@thefreakingmind do give us an update on the status of this PR. On top of running `npm run lint`, you should also run `npm run test` to check if front-end component tests pass locally.

**Comment by thefreakingmind** [comment]
Sorry Guys. I am really busy at work so couldn't get time to complete this. I made all the changes to backend Java files but didn't get time to change the frontend and hence the Test are failing. I'll be busy this week also so if anyone else is looking to pick this issue up let them have it.. If it is left incomplete. I'll make front end changes and give pr on weekend.

**Pull request closed without merging**
