### PR TITLE
Ensure responses are valid before showing them #4486

### LINKED ISSUE #4486: Ensure responses are valid before showing them
In results, submit pages.
Related to #4482

### PR DESCRIPTION
**Pull request by Sumei1009**
fixes #4486

### CODE REVIEW

**Comment by Sumei1009** [comment]
Previous pull request and discussion #4835

**Comment by Sumei1009** [comment]
There is one test keeping failing: InstructorFeedbackResultsPageUiTest. Not sure if it is affected by the code I changed.

**Comment by wkurniawan07** [comment]
@Sumei1009 can you post the stack trace of the test failure?

**Comment by Sumei1009** [comment]
At testExceptionalCases: 
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class,'panel')][.//input[@name='questionid'][@value='ag90ZWFtbWF0ZXMtc3VtZWlyHQsSEEZlZWRiYWNrUXVlc3Rpb24YgICAgKDemAsM']]//div[contains(@class, 'table-responsive')]"}
Command duration or timeout: 9 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'r-72-98-25-172.comp.nus.edu.sg', ip: '172.25.98.72', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.7.0_75'
*** Element info: {Using=xpath, value=//div[contains(@class,'panel')][.//input[@name='questionid'][@value='ag90ZWFtbWF0ZXMtc3VtZWlyHQsSEEZlZWRiYWNrUXVlc3Rpb24YgICAgKDemAsM']]//div[contains(@class, 'table-responsive')]}
Session ID: 608d02e2-cab4-ef48-8f95-3f4bf2c429b7
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=38.0.5}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:455)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at teammates.test.pageobjects.AppPage.getPageSource(AppPage.java:847)
	at teammates.test.pageobjects.AppPage.verifyHtml(AppPage.java:814)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:882)
	at teammates.test.cases.ui.browsertests.InstructorFeedbackResultsPageUiTest.testExceptionalCases(InstructorFeedbackResultsPageUiTest.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class,'panel')][.//input[@name='questionid'][@value='ag90ZWFtbWF0ZXMtc3VtZWlyHQsSEEZlZWRiYWNrUXVlc3Rpb24YgICAgKDemAsM']]//div[contains(@class, 'table-responsive')]"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'r-72-98-25-172.comp.nus.edu.sg', ip: '172.25.98.72', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.7.0_75'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///var/folders/8v/sq5_5s5n4m91hz7t47hr9xx80000gn/T/anonymous1824802620500030883webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10299)
	at <anonymous class>.FirefoxDriver.prototype.findElement(file:///var/folders/8v/sq5_5s5n4m91hz7t47hr9xx80000gn/T/anonymous1824802620500030883webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10308)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///var/folders/8v/sq5_5s5n4m91hz7t47hr9xx80000gn/T/anonymous1824802620500030883webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12282)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///var/folders/8v/sq5_5s5n4m91hz7t47hr9xx80000gn/T/anonymous1824802620500030883webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12287)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///var/folders/8v/sq5_5s5n4m91hz7t47hr9xx80000gn/T/anonymous1824802620500030883webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12229)

**Comment by wkurniawan07** [comment]
@Sumei1009 yes it's caused by changes in this PR. I know why it happened and how to circumvent it, but I'll give you some time to try and debug it yourself. Hint: take a look at one of the modifications you made in `InstructorFeedbackResultsPageUiTest.json`
Also, the branch name is missing the issue number, so I have to be fair and close this PR. Feel free to reopen a new one with the correct branch name.

**Pull request closed without merging**
