### PR TITLE
 Fix typo on README.md #4833 

### LINKED ISSUE #4833: Fix typo on README.md
There is a typo for "use" in <code> (yes, we ues the issue tracker as a discussion forum too).</code>

### PR DESCRIPTION
**Pull request by sujeet14108**
Fixes #4833

### CODE REVIEW

**Comment by thyageshm** [comment]
Hi Sujeet! thank you for sending in your fix for the issue. Next time, if the pr is ready for reviewing, add the `s.ToReview` label to the pr.

**Comment by damithc** [comment]
I don't think @sujeet14108 has permissions to change labels :-)

**Comment by sujeet14108** [comment]
@damithc  Yes, i don't have permissions to change labels .

**Comment by thyageshm** [comment]
Oooops... sorry. 

@sujeet14108, thank you for your contribution and great job on completing your first issue! Please go ahead try other issues without  the label `d.FirstTimers`.

**Pull request merged**
