### PR TITLE
Review the contents of outdated folders #6114

### LINKED ISSUE #6114: Review the contents of outdated folders
The following folders (all located in root project folder) contain files that by now are outdated and either should be removed or should be documented if still used:
- `.hubturboconfig/`
- `BackupFiles/`
- `scripts/`

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6114

### CODE REVIEW

**Comment by wkurniawan07** [comment]
I'm not sure where any of them are used, so the decision is to remove all. If any of them turns out to be used somewhere, then as mentioned in the issue thread, a proper documentation is called for instead.

@damithc I think you have to review this directly since no one else in the current team is likely to know about these files.

**Comment by damithc** [comment]
Scripts in concern haven't been used in recent times. May not even work any more. But they are described [here](https://docs.google.com/document/d/1ECDOy2JUXKLz8t44lXj2t0nvqDtJCjyHM7_HA8DV1fA/pub?embedded=true)

**Comment by wkurniawan07** [comment]
@damithc noted, should we keep them or discard them? While they may still be usable, no one in the current team understands the implementation. If the decision is to keep, I'll try to make some form of documentation for it.

**Comment by damithc** [comment]
Let's keep them for now. Backup is a problem we haven't solved yet and we don't want to lose the work done by Shawn.

**Comment by wkurniawan07** [comment]
@damithc I added something so that anyone visiting the `BackupFiles/` folder will not be so confused:
screen shot 2016-10-25 at 4 55 17 pm

**Comment by damithc** [comment]
Can merge.

**Pull request merged**
