### PR TITLE
[#13054] Make substrings of the name in dropdown selections of recipient to be searchable

### LINKED ISSUE #13054: Make substrings of the name in dropdown selections of recipient to be searchable
**Description of feature/enhancement**
image

**Context**
When selecting students from a drop-down, there may be many students. If I know the recipient in advance, I would like to quickly type the name from the options and get the selection.

**Problem**
Currently, the code-base supports for searching only if I type the start of the name. 
The problem is when I'm trying to search for a surname, or for example in the screenshot, their first names are prefixed with the section / team names. This makes the search essentially useless.

Being able to search with some sort of substring of the name (all possible substrings, or substrings separated by spaces) will help improve the submission user experience.

### PR DESCRIPTION
**Pull request by juanchiflo17**
Fixes #13054

**Outline of Solution**
Introduces a real-time substring search filter to the recipient dropdown in the question submission form.

### CODE REVIEW

**Comment by FergusMok** [comment]
@juanchiflo17 Thank you for contributing, could you add some video snippets of the changes too inside the PR description? It'll make it easier for other reviewers to approve.

**Comment by domoberzin** [comment]
Hi @juanchiflo17 thank you for the PR, just a question, is it intentional that the search input is shared across all the dropdowns? I've attached a video for reference

https://github.com/TEAMMATES/teammates/assets/74132255/6f07133e-5a69-46f5-b338-96735cd1373e

**Comment by mingyuanc** [comment]
@juanchiflo17 Any updates on the question that my friend posted?

**Comment by domoberzin** [comment]
hi @juanchiflo17 , any updates?

**Comment by weiquu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
