### PR TITLE
Test failures due to line endings in HTML attribute value #6174

### LINKED ISSUE #6174: Test failures due to line endings in HTML attribute value
A whole bunch of tests failing on live server with a diff like this. e.g. `InstructorFeedbackPageUiTest::testCopyActions()`

image

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6174 

Line breaks and indentations _inside_ HTML attribute value is not really a good practice anyway since it is _not_ trimmed (by this I mean string inside quotes are generally not trimmed coding-wise, rendering-wise it _is_ trimmed like all other breaking whitespaces).

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@damithc this branch built on top of the latest `release` should be passing all the failures mentioned in the issue.

**Comment by damithc** [comment]
Let's do a new release in the next couple of days and include this in that release. I'll abort the current deployment in the meantime as it doesn't contain any critical features.

**Comment by JosephineKwa** [comment]
Good to merge!

**Comment by leelunn** [comment]
Hello.  I'm in the process of completing the orientation guide; I am at the step of confirming Travis tests.

I am getting one failed test, which appears to be related to this issue.  I am *almost* certain that I have the most current version of the code, but perhaps I do not; github is still quite confusing for me. On test: testInstructorCourseEnrollPage

image

**Comment by damithc** [comment]
@wkurniawan07 any help on this?

**Comment by wkurniawan07** [comment]
@leelunn you're absolutely right; I wasn't paying attention to this one when fixing the related issue. I shall open a new issue for this.

**Pull request merged**
