### PR TITLE
[#10527] Student view responses: tweak spacing

### LINKED ISSUE #10527: Student view responses: tweak spacing
Use spacing to indicate relationships between elements. Elements should be closer to other related elements than to non-related elements. In this case, `Evaluee/recipient` label should be closer to the names below than the panel above.

image

Also present in V6 but less severe.

### PR DESCRIPTION
**Pull request by clare0901**
Fixes #10527

### CODE REVIEW

**Comment by ChooJeremy** [comment]
Hi @clare0901, please fix your PR title: 
https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr

**Comment by clare0901** [comment]
> Hi @clare0901, please fix your PR title:
> https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr


1)Student view responses: tweak spacing [#10722 ]
- Issue Reference #10722
2)Added spaces wherever required.
- fixed

I have written this !! I am not getting what more is required !! Please help @ChooJeremy

**Comment by ChooJeremy** [comment]
> > Hi @clare0901, please fix your PR title:
> > https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
> 
> I am not getting what more is required !! Please help @ChooJeremy

You should use the entire issue title in your title and reference the number of the issue instead of the number of the PR. 
In your case, that would be issue #10527 and the title would be `Student view responses: tweak spacing `

**Comment by clare0901** [comment]
> > > Hi @clare0901, please fix your PR title:
> > > https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
> > 
> > 
> > I am not getting what more is required !! Please help @ChooJeremy
> 
> You should use the entire issue title in your title and reference the number of the issue instead of the number of the PR.
> In your case, that would be issue #10527 and the title would be `Student view responses: tweak spacing `

> 
[#10527]Student view responses: tweak spacing
Like this right !?

**Comment by damithc** [comment]
> [#10527]Student view responses: tweak spacing
> Like this right !? @ChooJeremy

Tip: look at existing PRs to see the title format they follow :-)

**Comment by ChooJeremy** [comment]
@clare0901 can you provide a screenshot of before/after your changes? There doesn't seem to be much of a change on my end.

**Comment by clare0901** [comment]
> @clare0901 can you provide a screenshot of before/after your changes? There doesn't seem to be much of a change on my end.

`before`
image


`after`
image

**Comment by ChooJeremy** [comment]
Hi @clare0901, while those changes are visible when viewing the .html file directly, we do not use those directly and our users certainly won't be viewing them in that way. Consider a website that looks like the screenshot you provided - it looks like a website that's very outdated and in which likely no one would use at all!

Please read and follow our setting up guide https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md to run the project properly.

**Comment by clare0901** [comment]
> Hi @clare0901, while those changes are visible when viewing the .html file directly, we do not use those directly and our users certainly won't be viewing them in that way. Consider a website that looks like the screenshot you provided - it looks like a website that's very outdated and in which likely no one would use at all!
> 
> Please read and follow our setting up guide https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md to run the project properly.

#10728

**Comment by ChooJeremy** [comment]
Closing due to inactivity. If you do end up finding a solution to your problem and making the required changes, please feel free to reopen or submit another PR.

**Pull request closed without merging**
