### PR TITLE
instructorFeedbackSessionCopy: session name should be trimmed automatically #2589

### LINKED ISSUE #2589: instructorFeedbackSessionCopy: session name should be trimmed automatically
The new session name supplied should be trimmed automatically. Currently, the copy operation fails if there is a trailing space.

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #2589

### CODE REVIEW

**Comment by damithc** [comment]
It's better if this can be covered in a test, to prevent future regressions.

**Comment by belyabl9** [comment]
Ready to review

**Comment by junhaoyap** [comment]
Let's keep a basic successful test for ```"New Session (Copied)"``` too rather than modifying the basic test into one that tests for trimmed strings only

**Comment by belyabl9** [comment]
Ok, but I think it'll only increase testing time. " New Session (Copied) " is valid input, so succesful result and trimmed input may be tested simultaneously.

**Comment by junhaoyap** [comment]
Indeed you're right, perhaps let's look at it this way - having both trimmed and untrimmed will help us to pinpoint the problem when the trimmed one fails (regression i.e. someone removed the trim when migrating code) or when both fails (signifies a bigger problem)

**Comment by belyabl9** [comment]
Ready to review

**Comment by junhaoyap** [comment]
@belyabl9 I have merged this for you - good job!

**Pull request merged**
