### PR TITLE
[#11176] Use grey panel when there are no results in student activity logs search

### LINKED ISSUE #11176: Instructor checking student activity: use grey panel if no results
Steps:
1. Instructor goes to `/web/instructor/logs`
2. Search for activities of some student/session
3. No results returned for some sessions:
   image

Suggestion: Empty panels are shown in green (i.e., success) style. Perhaps we can use a different style for empty panels e.g., grey?

### PR DESCRIPTION
**Pull request by ChanwooJung1**
Fixes #11176 

If there are no results in the search result for student activity logs, use `alert-failure` class instead to grey out the card header.

### CODE REVIEW

**Comment by ccyccyccy** [comment]
Hi @ChanwooJung1. Thank you for the contributions ;)
The e2e test is failing due to the UI changes. Do make the necessary changes.
You can refer to our documentations regarding how to make the appropriate changes.

**Comment by ChanwooJung1** [comment]
@ccyccyccy Thank you! I have updated the tests to match expected results. Could you please take another look?

**Review by t-cheepeng — APPROVED** [review]

**Comment by t-cheepeng** [comment]
@ChanwooJung1 
Could you post a quick screenshot of the changes made for verification? Thanks!

**Comment by ChanwooJung1** [comment]
changes made

**Comment by t-cheepeng** [comment]
> 
> 
> changes made
> 
> @t-cheepeng I posted the screenshot of the changes made for verification. Can you please take a look?

Looks good. thanks!

**Comment by damithc** [comment]
> changes made
> 

Looks OK to me @ChanwooJung1 
Perhaps you can post a screenshot showing both type of panels at the same time? i.e., empty panels and non-empty panels

**Comment by ChanwooJung1** [comment]
@damithc 
image
image

**Comment by damithc** [comment]
Looks good @ChanwooJung1 👍

**Review by ccyccyccy — APPROVED** [review]
LGTM!

**Pull request merged**
