### PR TITLE
[#10623] Change design diagrams from Powerpoint to PlantUML

### PR DESCRIPTION
**Pull request by tenebrius1**
Part of #10623 

**Outline of Solution**
The diagrams that I have converted are very heavily customized (different colors and line styles were used) and as such there were a lot of inline styling that were done. I am still quite new to PlantUML so I'm not too sure whether these customizations can be done in a better way, but I have represented the original images as best as I can in puml.

For the remaining 2 pptx files (`RolesAndTechnologies` and `workflow`), I stand with the previous committer that puml is not sufficient to represent the information presented

### CODE REVIEW

**Comment by damithc** [comment]
General comment: It is OK to keep some diagrams in the current format if the PlantUML version can't be as visually expressive as the current version, especially if the diagram is not expected to change often e.g., Architecture-level diagrams

**Review by zhaojj2209 — COMMENTED** [review]
Good effort!
Some suggestions for the high level architecture diagram:

- Would be good if these 2 arrows can be separated more! Currently looks a bit confusing since the bottom arrow is pointing too close to the top arrow
image

- The PlantUML diagram makes it seem like GAE is entirely separate from the rest of the architecture, would be good to shift it directly below Datastore or add an arrow/line to link the two together
image

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

**Review by ziqing26 — APPROVED** [review]
LGTM, kindly update the branches to be ready for merging

**Pull request merged**
