### PR TITLE
[#11487] Disable mouse wheel events for number inputs

### LINKED ISSUE #11487: Numerical scale questions replacing user ratings with random values
Received from a user:

>I've started to notice that when I type in a 5 or whatever number into the questions to rank my teammates that it would actually change the ranking from a 5 or a random number. Most of the time it changes to a 4 but I have found it has changed to a 3 on occasions. I don't believe it has anything to do with the specific computer I am using or any error on my end so I wanted to let you know so you are aware and maybe others have had the same issue.

Although the student says 'ranking' it is actually a numerical scale question.

image

image

The worrying thing is, another instructor from a different university reported that her students are complaining about this same thing.

The question in concern:
image

In both cases, the session has many similar questions (10-24) but the team size is normal (4-8).

Apparently, they can get TEAMMATES to save the correct values after a few tries.

I couldn't reproduce it at my end though. I'm waiting for more info. Will post here as I receive them.

### PR DESCRIPTION
**Pull request by fsgmhoward**
- Prevent mouse wheel scroll from changing students' number inputs

Fixes #11487

**Outline of Solution**

This PR adds event handler to disable mouse wheel events for three types of questions: distribute points (options), distribute points (recipients) and numerical scale question.

A lifecycle hook `ngAfterViewInit` is added to the base class `QuestionEditAnswerFormComponent`. It will try to check whether property `elementRef` is set. When it is set, it will try to query and select all number inputs and add event listener to disable the wheel actions. This property is set using dependency injection for the three classes affected by the issue.

Note: This only fixes for the student-side answer form. For the instructor-side question edit form, it is not changed.

### CODE REVIEW

**Review by moziliar — APPROVED** [review]
LGTM, although I am not exactly sure about the use of elementRef in this case. Is this encouraged? @t-cheepeng

**Comment by t-cheepeng** [comment]
> LGTM, although I am not exactly sure about the use of elementRef in this case. Is this encouraged? @t-cheepeng

elementRef is generally not encouraged due to it being not "Angular"

@fsgmhoward Is it possible to use selector `@Directive` with `@HostListener` and doing the same thing? If not, this approach is fine too

**Comment by fsgmhoward** [comment]
@t-cheepeng I have tried to use @Directive with @ViewChildren and/or @ContentChildren but unsure of reason, the input boxes are not being captured and the querylist always return an empty list. I did not attempt to combine it with HostListener though. I will try again and check whether it works or not. Thanks for the comment.

**Comment by fsgmhoward** [comment]
@t-cheepeng I have updated this PR to disable the mouse events using @Directive.

**Review by t-cheepeng — APPROVED** [review]
LGTM 👍

**Pull request merged**
