### PR TITLE
[#11556] Infinite loading upon clearing text in a date picker 

### LINKED ISSUE #11556: Infinite loading upon clearing text in a date picker
**Environment**
Live server at `V8.6.0`

**Steps to reproduce**
1. Choose a feedback session to edit (go to Edit Feedback Session Page)
2. Delete the date for any date picker (for example, Submission opening time or Make session visible)
3. Click 'Save Changes" button.
ezgif-2-a56aae2095

**Expected behaviour**
Report an error for invalid date time and stop loading to save data.

**Actual behaviour**
No error is reported and the loading sign is shown to prevent further editing (does not stop trying to save).

**Additional info**
Might need to catch this error before it attempts to save the data in the front end.

### PR DESCRIPTION
**Pull request by FergusMok**
Fixes #11556 

image

The problem was occurring due to the null-value time being parsed in the frontend, preventing the request from reaching the  backend for validation. However, I realized the fastest way would just be to limit the user's ability to use the datepicker only, and make the text portion readonly. 

However, I am also slightly worried that the readonly text UI may lead to users thinking that the entire date is disabled and cannot be edited.

### CODE REVIEW

**Comment by samuelfangjw** [comment]
> However, I am also slightly worried that the readonly text UI may lead to users thinking that the entire date is disabled and cannot be edited.

Screen Shot 2022-02-10 at 1 28 33 AM

Agreed, especially since that shade is already used for disabled input.

What do you think of overriding the styles on the readonly input instead? 

```css
.form-control {
  &[readonly] {
    background-color: transparent;
  }

  &:disabled {
    background-color: #e9ecef;
  }
}
```

**Review by samuelfangjw — CHANGES_REQUESTED** [review]
Screen Shot 2022-02-19 at 1 19 33 PM

Need to ensure disabled input retains their color.

**Review by samuelfangjw — APPROVED** [review]
Looks good :)

**Comment by samuelfangjw** [comment]
> Changes appear to be failing the e2e tests. Not sure if it's related to #11591 since that's supposed to be temporarily resolved. Could you take a look please? Thanks

Not related to #11591, sorry I missed this in my review. @FergusMok, since the fields are now readonly, need to use the date picker to select the dates in e2e tests.

**Comment by FergusMok** [comment]
@samuelfangjw Thanks for the headsup. I went to investigate it, and implementing the E2E tests for datepicker might take a while. I'll put this on hold first to meet the high priority milestone

**Comment by FergusMok** [comment]
Hi everyone, thanks for the help in reviewing this PR. I'm closing this PR as @ziqing26's PR will be solving this issue too, and she has merged this PR into hers.

**Pull request closed without merging**
