### PR TITLE
[#12399] Instructor editing feedback path of a question: unnecessary scrollbars

### LINKED ISSUE #12399: Instructor editing feedback path of a question: unnecessary scrollbars
v8.27, production, Windows, Chrome

Context: an instructor is editing questions of an existing session

image

image

Let me know if more info needed to reproduce

### PR DESCRIPTION
**Pull request by athakaras**
Fixes #12399 

**Outline of Solution**

Fix the issue by removing "overflow-scroll" which was the reason for the unnecessary scrollbars when an instructor is editing a question of an existing session (feedback path)

Here is the updated UI

issue1
issue2

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @athakaras, fix looks fine but do merge the latest changes from `master` into your branch and update the failing snapshot tests

**Comment by athakaras** [comment]
Hello! Fixed all issues.
Please review and merge :)

**Review by zhaojj2209 — APPROVED** [review]
LGTM, tested on Linux (since this issue seems to be not present on Mac).

**Review by domlimm — APPROVED** [review]
LGTM! Thank you for your contribution!

**Pull request merged**
