### PR TITLE
Typo in enableJS.jsp: conformation #5832

### LINKED ISSUE #5832: Typo in enableJS.jsp: conformation
In `src/main/webapp/enableJS.jsp`, there is the following line under the section to enable JavaScript in Internet Explorer:

`<li>Answer yes to the following conformation box.</li>`

"conformation" should be "confirmation" instead.

### PR DESCRIPTION
**Pull request by Naruto8**
Fixes #5832
Fixed the typo

Changed 'conformation' to 'confirmation'

### CODE REVIEW

**Comment by chowyb** [comment]
Hi @Naruto8,

The branch name for this PR is now correct, however you will still need to change the PR name and description. The PR should follow the conventions [here](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md#creating-a-pull-request).

**Comment by Naruto8** [comment]
The issue number is automatically shown 5878 and the one I changed has number 5832

**Comment by chowyb** [comment]
@Naruto8, yes the number #5878 is the number of the pull request. We require that the issue number which the pull request is trying to fix (#5832 in this case) be placed at the end of the pull request name as well.

**Comment by damithc** [comment]
@Naruto8 you can look at existing pull requests for examples on how to name PRs. When working in OSS projects, being consistent with the existing practices is very important.

**Comment by wkurniawan07** [comment]
@Naruto8 may we know your name so we can list you as our contributor?

**Comment by Naruto8** [comment]
Real name? - Rohith Mukku

**Pull request merged**
