### PR TITLE
Unused parameters in toggleSendRegistrationKey() for instructorCourseDetails #3895

### LINKED ISSUE #3895: Unused parameters in toggleSendRegistrationKey() for instructorCourseDetails
```
function toggleSendRegistrationKey(courseID, email) {
    return confirm("Usually, there is no need to use this feature because TEAMMATES " 
                   + "sends an automatic invite to students at the opening time of each" 
                   + " session. Send a join request anyway?");
}
```
Is it supposed to use the course id and email somehow?
Or should the parameters be removed?
At the moment, it is being called without passing any parameters in.

sendinvite
It corresponds to the "Send Invite" button on the course details page.

### PR DESCRIPTION
**Pull request by samatdav**
Fixed #3895

### CODE REVIEW

**Comment by thyageshm** [comment]
@yj-soh for your review :-)

**Comment by yj-soh** [comment]
Hello @samatdav, welcome to TEAMMATES.
The changes look fine, but when submitting PRs, please follow the workflow [here](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md) and take a look at other PRs, especially on how to name the branch. You need to make a PR from a correctly named branch, so I'll be closing this one.

**Comment by samatdav** [comment]
@yj-soh I am sorry I am confused now. I did follow the instructions which you linked. Specifically for the branch naming:
_Start a new branch named {IssueNumber}-{some-keywords}. If you are already working in a branch, 
remember to switch to the master before creating the new branch. e.g.,_

Is it that the keywords are not correct? Could you please help me understand? 
Would name _#3895-Unused-parameters_ be appropriate?

**Comment by yj-soh** [comment]
The keywords are more or less fine, it's the issue number that's the problem.
Take a look at other approved issues and check the difference.

**Comment by samatdav** [comment]
@yj-soh oh, is the number sign (#) the problem here? Just did not recognize that only numbers were needed. If so, I will be glad to fix the name of the branch and make a new PR :-)

**Pull request closed without merging**
