### PR TITLE
[#11242] Fix duplicate copied sessions shown in instructor homepage

### LINKED ISSUE #11242: Copying sessions from the home page results in temporary duplicate sessions being shown
Steps that I took:
1. Go to instructor home page
2. Click on the copy button of a session
3. Select to copy to multiple courses (some of which are inside collapsed panels)
4. Finish the copy operation.
5. When I expand the course panel of one of the destination courses, I see an extra duplicate of the copied session.

image

The duplicate goes away upon refreshing the page. So I guess this is a front-end glitch.

After refreshing:
image

### PR DESCRIPTION
**Pull request by tjtanjin**
Fixes #11242

**Outline of Solution**

Add an extra condition to check if the course that a session is being copied to is currently expanded. For courses that are unexpanded, do not push the model. This will be instead be done when the click event for expanding the course is triggered.

### CODE REVIEW

**Comment by ccyccyccy** [comment]
I don't think this is the right fix.
The duplicate session bug only appears when the tab is initially collapsed. 
If the course tab is initially opened and you manually collapse it, the bug will not appear. 
This PR will cause the duplicate to appear in these initially opened tab.

**Comment by tjtanjin** [comment]
> The duplicate session bug only appears when the tab is initially collapsed.
> If the course tab is initially opened and you manually collapse it, the bug will not appear.

Thank you for the response! I can confirm these observations. To clarify, the additional condition added serves as a guard against pushing the model into the courseTabModel for courses that are yet to be expanded. This is because for the unexpanded tabs, said model will still be pushed when the user eventually clicks to expand it (hence the observed duplication). This does not modify the behaviour of the initially opened tabs since the new check for them (`courseModel.isTabExpanded`) will always be true.

Here is a video for verification of expected behaviour:
https://user-images.githubusercontent.com/43908963/124498118-72a06000-ddee-11eb-83ca-d4a61ecc6f00.mov

**Comment by ccyccyccy** [comment]
> (`courseModel.isTabExpanded`) will always be true.

Don't think this is true. The `handleClick` function will toggle the `isTabExpanded` boolean.

> This is because for the unexpanded tabs, said model will still be pushed when the user eventually clicks to expand it

This is only true for the first expansion. On subsequent expansion, we would use the cached data which doesn't include the new copied session.

This would result in this bug with your PR, where it will not show the session until the page refreshes

https://user-images.githubusercontent.com/32454748/124541233-96e25800-de53-11eb-97fe-68594b89b47f.mov

**Comment by tjtanjin** [comment]
> More accurate to say that we will fetch data from the backend for the first expansion, which includes the new model. On subsequent expansion, we would use the cached data which might not include the newly copied session if we had toggled the tab expansion previously.

Thank you for the clarification! Based on what you've just highlighted, I've since changed the condition to check for whether the model is populated:

https://user-images.githubusercontent.com/43908963/124589381-84384500-de8c-11eb-9bd9-3a75d54d439e.mov

**Review by ccyccyccy — APPROVED** [review]
LGTM!

**Review by halfwhole — APPROVED** [review]
Sorry for the delay. Yep, the fix looks right!

**Pull request merged**
