### PR TITLE
[#13122] Create cancel button for instructor request form

### LINKED ISSUE #13122: Account Request Form: Adding Cancel button
- **Environment**:  V9-0-0-b6a

**Description of feature/enhancement**
Current: There is a Submit button for user to finish up and submit the form. User can use the browser's Back button to exit the form and go back to the homepage. 
Suggestion: Adding a Cancel button next to the Submit button so user can undo their form request and go back to homepage.

**Justification**
Instructors who do not want to complete their form right away or users who are testing out the feature can have a visible option to cancel their action and go back to homepage.

**Existing similar features and their shortcomings**
Although users can go back using the browser's Back button, the option may not be too obvious for some users, so having the choice to undo clearly visible may be beneficial for them.

### PR DESCRIPTION
**Pull request by NeoHW**
Fixes #13122 

**Outline of Solution**

* Add a Cancel button next to the Submit button so users can undo their form request and return to the homepage.
* Added accessibility features to both cancel and submit button

**UI changes**

Screenshot 2024-07-29 at 11 18 46 PM

### CODE REVIEW

**Review by itstrueitstrueitsrealitsreal — APPROVED** [review]
LGTM, good that accessibility features for screen readers are also added.

**Review by domoberzin — APPROVED** [review]
LGTM

**Comment by mingyuanc** [comment]
@NeoHW same thing pls fix failing tests

**Comment by itstrueitstrueitsrealitsreal** [comment]
Hi @mingyuanc, noticed that tests have been failing for recent PRs due to docker-compose being upgraded, should we prioritise the merging of https://github.com/TEAMMATES/teammates/pull/13159 before other PRs?

**Review by dishenggg — APPROVED** [review]
LGTM!

**Pull request merged**
