### PR TITLE
[#11588] Fix incorrect loading for student result page

### LINKED ISSUE #11588: Student viewing results: incorrect state shown while loading
Steps:
1. Login as a student
2. View results of a session
3. Problem: This message is shown for a brief instance while results are still loading
image

Session detail also appear blank but that is less of a problem compared to the above.

### PR DESCRIPTION
**Pull request by fsgmhoward**
Fixes #11588 

**Outline of Solution**

For the "nothing to show" message:

It is shown when nothing to show and it is not loading. Since the default value for loading state is `false`, it will be shown until document finish initialization and executes the loading method. So the solution for this is, loading state is set to `true` at initialization.

For the session information card:

An additional attribute is added to check whether session information has been loaded. The box is shown after information is fetched.

Recording after fix applied:

### CODE REVIEW

**Review by FergusMok — APPROVED** [review]
LGTM! :)

**Review by samuelfangjw — COMMENTED** [review]
Looking at the test snapshots, the parts that were previously the feedback session details have been replaced with the loading spinner. Every snapshot test now has almost the same output, which kind of defeats the purpose of the tests.

I think we should add the one or both of the following lines as necessary to the relevant snapshot tests so they give the intended output.
```
    component.isFeedbackSessionDetailsLoading = false;
    component.isFeedbackSessionResultsLoading = false;
```

**Comment by fsgmhoward** [comment]
@samuelfangjw Thanks for pointing that out. I have made the changes to it. The two flags will be set to false before each run to keep the original snapshots compatible. New rule is also added for details loaded but results not loaded.

**Review by samuelfangjw — APPROVED** [review]

**Comment by fsgmhoward** [comment]
Looks like there are failed tests after merging with master which is weird. I will check it out later.

**Review by moziliar — APPROVED** [review]
LGTM!

**Pull request merged**
