### PR TITLE
Instructor: Feedback: View Results: fix the disappearing 'No specific recipient' panel bug #7633

### LINKED ISSUE #7633: Instructor: Feedback: View Results: fix the disappearing 'No specific recipient' panel bug
Noticed while investigating #4282 

**Steps to replicate:**
1. Login as instructor
2. View results for an FS in which there are no questions that do not have a specific recipient. 
3. Load any view EXCEPT for `Group by - Question`

**The problem:**
You will see a panel header with `No specific recipients` (even though there are no such responses). This panel then disappears on clicking.

GIF of isssue:
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by LimeTheCoder**
Fixes #7633 

After fix panel is not disappearing anymore:

image

### CODE REVIEW

**Comment by damithc** [comment]
Should the style be `warning` instead of `success`?

**Comment by VamsiSangam** [comment]
Hey @LimeTheCoder ! For some reason, I'm very interested in this PR :stuck_out_tongue_closed_eyes: .

I agree with your approach of removing the panel hiding code :+1:  . This seems to be the [intention when `removeSection()` was written](https://github.com/TEAMMATES/teammates/pull/5549#issuecomment-228101201). Also, you may want to go through #5549 . I think we should do a little research on why a line of code was written before removing it.

> Should the style be warning instead of success?

I feel the `panel-default` maybe a better choice, the one used for the last panel -

capture

**Comment by LimeTheCoder** [comment]
Hi, guys. As @VamsiSangam mentioned it was an intentional behaviour to hide this section if no responses for it.

> So, let's clarify the expected behaviour. Is the following correct:
> 1. If section is 'Not in a section' without responses we hide it
> 2. If any other section doesn't have responses we build it with missing participant panels?

But seems It was implemented in such way that 'No specific recipient panel' hides only after user clicks on that panel. 
@damithc In case when no responses for that panel should we don't display it at all during page loading or should we display that panel but with 'No responses' message in body as currently implemented for that and other panels.

**Comment by damithc** [comment]
> @damithc In case when no responses for that panel should we don't display it at all during page loading or should we display that panel but with 'No responses' message in body as currently implemented for that and other panels?

That panel should not show up at all if there are no responses to show inside it.

**Comment by wkurniawan07** [comment]
@LimeTheCoder some tests (possibly newly added) need to be updated to get a passing build here.

**Comment by LimeTheCoder** [comment]
Hi, @VamsiSangam. I investigated your case and It seems that your response contains null value as giverSection in the database. As you saw to decide to show 'No specific section' panel or not I iterate over responses from all sections and check if the primary participant in 'None' section. During loading these responses from the database, all null values in giver or recipient sections replaced with 'None' as a default value. That's why the panel is displaying.
But after click on that panel, loading responses for specific section occurs and the following filter applied:
`.filter("giverSection =", section)`. So from the database will be fetched only responses with 'None' section without responses with null value in the section as in the previous case. That's why panel exists but no responses for it.
So since we treat null values as 'None' section, we should fix responses loading for this section to fetch also responses with null values in giver or recipient section. 
@wkurniawan07 what do you think about it?

**Comment by VamsiSangam** [comment]
> we should fix responses loading for this section to fetch also responses with null values in giver or recipient section.

Yes I think we should fetch responses with null values in **giver section**. If I remember correctly, the `No specific section` panel displayed the responses perfectly for  `Group by - Recipient > Giver > Question` and `Group by - Recipient > Question > Giver`. Which means the behavior is fine for null values in recipient section.

**Comment by wkurniawan07** [comment]
> So since we treat null values as 'None' section, we should fix responses loading for this section to fetch also responses with null values in giver or recipient section.

@LimeTheCoder I feel that this is the correct approach as well, but I could be wrong. You can give it a shot.

**Comment by VamsiSangam** [comment]
Leaving a note. I pulled your code and the empty panel for ` Group by - Giver > Recipient > Question` still exists.

**Comment by LimeTheCoder** [comment]
Hi, Vamsi, I cannot reproduce your case. Did you run npm build after pulling? I looked into the code and don't see a place where such behavior possible. Could you please, in some way, provide how looks your feedback response after retrieving from the database?

**Comment by VamsiSangam** [comment]
Steps to create the scenario -

1. Create a FS.
2. Create an essay question with feedback path `Instructors in this course will give feedback on -> Giver (self feedback).
3. Return to instructor home page, click `Submit` corresponding to the new feedback session.
4. Give some response and save.
5. Go to results page.
6. Click `Edit View` -> `Group by - Giver > Recipient > Question` (leave all checkboxes ticked).'
7. Click `Change view`.
8. Click on `No specific section` panel.

I don't know how to print the contents when retrieved from the database, but this is what I got when I put `System.out.println(response.getJsonString());` in `isSectionHavingResponses()` -

``` json
{
  "feedbackSessionName": "Instructor self response",
  "courseId": "teammates.instructor.uni-demo",
  "feedbackQuestionId": "ag90ZWFtbWF0ZXMtdmFtc2lyHQsSEEZlZWRiYWNrUXVlc3Rpb24YgICAgMDJ5QsM",
  "feedbackQuestionType": "TEXT",
  "giver": "teammates.instructor@university.edu",
  "recipient": "teammates.instructor@university.edu",
  "responseMetaData": {
    "value": "<p>Vlola</p>"
  },
  "giverSection": "None",
  "recipientSection": "None",
  "feedbackResponseId": "ag90ZWFtbWF0ZXMtdmFtc2lyHQsSEEZlZWRiYWNrUXVlc3Rpb24YgICAgMDJ5QsM%teammates.instructor@university.edu%teammates.instructor@university.edu"
}
```

**Comment by wkurniawan07** [comment]
@LimeTheCoder I encountered the same problem as @VamsiSangam in all non-question view types, i.e. GRQ, GQR, RGQ, RQG. It looks like your logic in deciding whether a "No specific section" panel should be displayed is correct, but the logic to actually put the responses inside it is still incorrect.

**Comment by wkurniawan07** [comment]
@LimeTheCoder let's continue working on this?

**Comment by wkurniawan07** [comment]
Hi @LimeTheCoder, any updates here?

**Comment by wkurniawan07** [comment]
Hi @LimeTheCoder, any updates here? If this PR has no updates for the next week, I'm afraid I have to close it due to inactivity.

**Comment by LimeTheCoder** [comment]
Hi, all, sorry for the delay. Reproduced this case for instructor which also student at the course.

**Comment by wkurniawan07** [comment]
Closing due to an inactivity for a very long period. If anyone is interested to continue the work done here, feel free to reopen/request for reopen.

**Pull request closed without merging**
