### PR TITLE
Shubham singh

### PR DESCRIPTION
**Pull request by shubham-singh-748**
Fixes #

**PR Checklist**

Ensure that you have:
- [ ] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [ ] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ ] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by moziliar** [comment]
Hi, thank you for your interest in contributing to the project!

Please update your PR title and description to indicate the purpose of this PR. It can only be inferred that this PR is trying to fix issue #11388 which has already been taken up by other contributor in an active PR at the moment. Please look for other issues to work on and indicate your interest in the issue before opening a PR on it.

In the meantime, we will put this on hold first.

**Comment by shubham-singh-748** [comment]
How would i know if someone already taken an issue who i am thinking about to work..

**Comment by hhdqirui** [comment]
> How would i know if someone already taken an issue who i am thinking about to work..

@shubham-singh-748 hi, to answer your question, in the page of the issue that you want to work on, you can see the comments about who has taken that issue. You can also see whether there are already pull requests linked to that issue.

**Comment by moziliar** [comment]
@shubham-singh-748 to start with, your PR is not properly made. You should first of all amend it to be review ready.

I could only infer what issue you are attempting to work on. But regardless, the review process cannot begin without a proper context for review to start with.

**Comment by moziliar** [comment]
Closed due to inactivity and wrong format of PR.

**Pull request closed without merging**
