### PR TITLE
Rename 'Instructors' in courseEditAddInstructorPanel.tag to 'Instructor' #5496

### LINKED ISSUE #5496: Rename 'Instructors' in courseEditAddInstructorPanel.tag to 'Instructor'
In courseEditAddInstructorPanel.tag, the `div` with class `panel-heading`, `Instructors` should be changed to `Instructor`.

This is to make it consistent with the headings of the Edit Instructor panels, which are in courseEditInstructorListPanelHeading.tag.

### PR DESCRIPTION
**Pull request by ablyx**
Fixes #5496 

Also did the change to instructorHelp.jsp, renaming 'Instructors' to 'Instructor' in second example under Add/Edit instructors

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@ablyx there are failing tests that you need to fix. You may want to consult the Travis CI build log to find out which ones. The failing `TaskQueuesLogicTest` should be ignored.

**Comment by ablyx** [comment]
@wkurniawan07 sorry about that, I have already edited the failing test cases.

**Comment by wkurniawan07** [comment]
@ablyx there's nothing to worry, and it's great that you managed to resolve it quickly!

**Comment by junhaoyap** [comment]
@damithc will have to do a merge approval right?

**Pull request merged**
