### PR TITLE
[#12442] Massive string is not correctly treated

### LINKED ISSUE #12442: [Search Students]: Massive string is not correctly treated
- **Environment**: 
- Dev server
- Master at commit `4b2333d36f76e172bb9e15fd18b70d02e4587d9a`

**Steps to reproduce**

- Log in as a `instructor`
- Access the Search feature via the menu bar
- Make a search with a massive String ( more than 6000 characters, counting the whitespaces)

**Expected behaviour**
If we have a limit accepted on the backend we should have one of two in our frontend: 
- Define this limit at the frontend and don't send this request to the backend
- Send this request to the backend. Backend spit out an error. Frontend treat the spitted error.

### The expected behaviour would be:

- Error message shown to user before sending a search with more characters than the limit.

**SUGGESTED BEHAVIOR**

- Addition of a char counter at the search field
- When char counter reaches its limit block anymore typing
- Enhance error treatment at search student methods

**Actual behaviour**
-  User can type as much as it wants
- The More the user types the slower the navigator gets due to memory allocation
- After sending the request, a red banner without any message pops up

**Additional info**

## Photos

The photos have been cutted out only for the relevant information. My monitor specs are: 1920x1080

SCR-20230522-o8q
SCR-20230522-o8u

### PR DESCRIPTION
**Pull request by LarsGielen**
Fixes #12442

**Outline of Solution**

 
Changes Made:
- Added `maxLength` attribute to the search bar to enforce the character limit
- Modified `triggerSearchParamsChangeEvent()` function to check if the character limit has been reached
  - The search button disables when the limit is reached
  - A warning message is shown to inform users about the character limit

Tests:
- Added a new test case to ensure that the search button becomes unclickable and the warning message is displayed when the character limit is reached.
- Updated failed snapshots

Screenshot of warning message:
image

### CODE REVIEW

**Comment by LarsGielen** [comment]
Currently, I have hardcoded the character limit. Is there a way to avoid hardcoding it? Or is it not an issue?

**Comment by weiquu** [comment]
Hi @LarsGielen, thanks for the fix! Looks good so far (: Don't think there'll be any issue with the hardcoded character limit as well.

Could you help to make the change to the admin search as well?

**Comment by LarsGielen** [comment]
Hi @weiquu, do I need to open a separate pull request for the changes to the admin search?

**Comment by weiquu** [comment]
> Hi @weiquu, do I need to open a separate pull request for the changes to the admin search?

Nope, I think using the same PR/branch is fine since it's the exact same issue for both

**Comment by weiquu** [comment]
Thanks @LarsGielen for the changes! Upon further reflection, I've 2 points that I think are worth discussing:

1. I'm not sure if the warning message is needed. Perhaps a simple "Note:" under "Tips:" would suffice, or we can also follow how the course copy modal does it, which is to put the number of characters left below the input field:
Screenshot 2023-06-01 at 3 42 40 PM

2. I think a limit of 6000 characters might be too long. For example, names of students are restricted to 100 characters and team/section names are restricted to 60 characters, so it makes sense to have a limit around that range. I would suggest just setting it at 100 characters.

Do let me know what you think, and other contributors feel free to weigh in as well (:

**Comment by LarsGielen** [comment]
Hi @weiquu, I agree that putting the number of remaining characters under the input field would be better. It gives more and immediate feedback to the user and is more in line with other sections. 

Regarding the size of the limit. I do not think the limit should necessarily be set lower because a higher limit does not give any disadvantages. For a name, a lower limit makes sense so that, for example, it can be displayed correctly without being cut off. In contrast, this problem does not really apply to searching. On the other hand, as you pointed out, it does make sense to have the same limit everywhere since this provides more consistency.

I will put the number of remaining characters under the input field and remove the warning. For now I will also set the character limit to 100. Changing the limit is not much work so it can be easily changed if needed.

**Comment by LarsGielen** [comment]
image
image

**Comment by weiquu** [comment]
Thanks @LarsGielen for the quick changes. Just one last comment on a corner case:

When the user enters 100 characters, they are technically still within the limit (0 characters left), but the search button is disabled. I would suggest either:
- Setting the search button to be disabled when the character count is above the limit (i.e. > 100 characters)
- Removing the disabling of the search button, and introducing an additional check that results in an error message if the character limit is breached

The first option feels cleaner to me since we are, in a sense, "intercepting" input that we know is invalid. The second option is similar to how course copying handles inputs above the character limit.

**Comment by LarsGielen** [comment]
Hi @weiquu , since no more characters can be put in the search field than the character limit the button will never be disabled, so I took out the disabling of the button altogether.

**Comment by weiquu** [comment]
> Hi @weiquu , since no more characters can be put in the search field than the character limit the button will never be disabled, so I took out the disabling of the button altogether.

Note that technically it's still possible (I think) to trigger the error if the user intentionally uses developer tools to remove the max length of the input field. Quick example of what I mean:
Screenshot 2023-06-04 at 3 25 00 AM

Having said that, I think there's no need to address this issue since:
- The user has to intentionally go out of their way to replicate it
- Doing the above doesn't pose a threat to system stability or security, doesn't inconvenience (normal) users, and doesn't affect our DB

Just for you to take note of in the future (: I'll review the changes tmr

**Comment by LarsGielen** [comment]
>Note that technically it's still possible (I think) to trigger the error if the user intentionally uses developer tools to remove the max length of the input field.

Thanks for pointing that out, I didn't think of that. That's definitely something I need to keep in mind going forward.

**Review by weiquu — APPROVED** [review]
LGTM! Thanks for your contribution

**Review by domlimm — APPROVED** [review]
LGTM! Thank you for your contribution!

@weiquu Thank you for proactively answering @LarsGielen queries/doubts!

😃👍🏻

**Pull request merged**
