### PR TITLE
Rephrase the link to user map in index.html #5020

### LINKED ISSUE #5020: Rephrase the link to user map in index.html
image

Rephrase as:
~~See who is using TEAMMATES in our [user map]()~~
[See who is using TEAMMATES ...]()

### PR DESCRIPTION
**Pull request by pandilladivya**
Fixes #5020

### CODE REVIEW

**Comment by damithc** [comment]
Hmm... the branch name is still not quite right :-p

**Comment by pandilladivya** [comment]
According to the developer guider I was sure it should have been {issue number}-{branch name}

Can you please tell me where am I going wrong?

Thank You

**Comment by damithc** [comment]
The convention is to use `few-keywords` not `few_keywords`

**Comment by pandilladivya** [comment]
Aw Thankyou :)

**Pull request closed without merging**
