### PR TITLE
Update admin email signature to 'Associate Professor' #6865

### LINKED ISSUE #6865: Update admin email signature to 'Associate Professor'
v 5.99

Current signature of emails sent by TEAMMATES:
`Damith C. Rajapakse (Dr) ; Senior Lecturer, School of Computing,...`

Update to:
`Damith C. Rajapakse (Dr) ; Associate Professor, School of Computing,...`

### PR DESCRIPTION
**Pull request by shrut1996**
Fixes #6865

### CODE REVIEW

**Comment by shrut1996** [comment]
@damithc  Ready for review :+1: and Congratulations !

**Comment by shrut1996** [comment]
@whipermr5 Sorry, Delay the review as I have found an issue.

**Comment by whipermr5** [comment]
@shrut1996 By the way, commit messages should be imperative, i.e. it should sound like you're giving instructions rather than describing what you did (so it should be `Update` not `Updated`). More guidelines for commit messages [here](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#commit-message).

**Comment by shrut1996** [comment]
@whipermr5 Could you have a look at the changes please?

**Pull request merged**
