### PR TITLE
[#11950] Fix bug with overflow of members count in error message

### LINKED ISSUE #11950: Student submitting zero-sum contribution question: the error message is misleading
v8.19.2 live server

Scenario: A student is submitting responses for a contribution question. The zero-sum constraint is in force. The team has five members. The student enters `Equal share + 20%` for all five members.

Error message shown:
image

It should read `Current total 5 x Equal share + 100% ...` as the team has only 5 members.

### PR DESCRIPTION
**Pull request by domlimm**
Fixes #11950.

**Outline of Solution**

Previously, the zero-sum contribution question overflows when it exceeds the total required contribution percentage i.e. `Number of members in the team * 100%`, as it is not captured in the logic flow for the error message.

image

Now, we have introduced another way of checking for this overflow and reducing the number of `Equal Share` with a cap based on the number of members in a team by `Total required contribution percentage / 100`. The excess will then be calculated separately.

And now, it should read `Current total 5 x Equal share + 100% ...` when the total required contribution percentage exceeds `n * 100`, where `n` is the number of members.

image

### CODE REVIEW

**Review by zhaojj2209 — COMMENTED** [review]
Just one nit

**Comment by domlimm** [comment]
Hello @zhaojj2209, thank you for your review and catching that! Have rolled out the change 👍🏻

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the change!

**Review by NicolasCwy — APPROVED** [review]
LGTM!

**Pull request merged**
