### PR TITLE
[#12344] Instructor courses page: fix margin of copy instructors from other courses modal on mobile

### LINKED ISSUE #12344: Instructor courses page: fix margin of copy instructors from other courses modal on mobile
Path: Instructor pages -> Courses tab -> Edit course details -> Copy instructors from other courses

The modal that appears has a large margin on the right, which is different from the behaviour of other modals on mobile:
copy instructors modal closed

This makes it difficult to read the text in the table:
copy instructors modal open

### PR DESCRIPTION
**Pull request by b-walton**
Fixes #12344

**Outline of Solution**

 

Fixes mobile margin by only applying width constraint on media 768 pixels or wider.
(ready for review)

Desktop View:
image

Mobile View:
image

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @b-walton, solution looks fine at a glance, but do fix the lint issues before we do a complete review.

**Review by weiquu — CHANGES_REQUESTED** [review]
Hi @b-walton, while this solution works, I think we should implement it in a way that is consistent with the rest of the modals. In particular, you can take a look at the `copy-questions-from-other-sessions-modal` component to see what I mean (involves setting `min-width` instead). Do let me know if you require any clarification.

**Comment by b-walton** [comment]
Are there any likely reasons for why the E2E tests fail?

**Comment by weiquu** [comment]
> Are there any likely reasons for why the E2E tests fail?

Hmm E2E tests can fail (for frontend changes) if there are changes to page structure / behaviour / element identifiers. However, they might occasionally fail due to the tests being unstable, in which case we will run them again (: Your PR passes all checks, so no worries there.

**Review by weiquu — APPROVED** [review]
LGTM! Thanks for contributing

**Review by zhaojj2209 — APPROVED** [review]
LGTM

**Pull request merged**
