### PR TITLE
CSV download of the feedback responses should take the show stats checkbox in to consideration #5631

### LINKED ISSUE #5631: CSV download of the feedback responses should take the show stats checkbox in to consideration
showstats

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #5631

### CODE REVIEW

**Comment by chowyb** [comment]
Behaviour looks good, but I'll put this as ongoing for now since there'll definitely be merge conflicts with #5740.

After that PR has been merged into master, update this branch and clear the merge conflicts and I'll have a look again after that :)

**Comment by rclakmal** [comment]
@chowyb Merged master branch.

**Comment by chowyb** [comment]
@rclakmal Alright the combined behaviour of text filter, statistics and missing responses works fine, good to go :)

On another note, I just realised that the downloaded results for rubrics questions doesn't look too good as the sub-questions cannot be seen when statistics are not shown. It would be good to fix this in another issue if possible, since fixing this would likely affect the display of responses in the HTML page as well.

With statistics:
rubrics1
exrubrics1

Without statistics:
rubrics2
exrubrics2

On the HTML page it'll still look okay since the sub-questions can be viewed by clicking "More", but there is no way to view this on the downloaded .csv file.

**Comment by damithc** [comment]
Yes, if useful information is missing from the csv file, we should consider adding it it in another PR.

**Pull request merged**
