### PR TITLE
[#12481] Fix running of component tests using Windows Powershell

### LINKED ISSUE #12481: Fix running of component tests using Windows Powershell
I followed the developer guide provided in the project documentation, but when I run the command to check the code line coverage of the tests, I get the following error: 
I try to run: ./gradlew componentTests
and: ./gradlew componentTests jacocoReport 

image
Guide link I followed: https://teammates.github.io/teammates/development.html

### PR DESCRIPTION
**Pull request by guilherme-puida**
The previous strategy of choosing the command for deleting temporary files relied on the Windows CMD command `del`. This command does not exist in PowerShell, so the task fails.

Thankfully, there is a `delete` method we can use. This method takes care of platform differences for us.

Fixes #12481 

**Outline of Solution**

Using gradle's [`delete`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#delete-java.lang.Object...-) method fixes the problem and takes care of all other platform issues (I hope).

### CODE REVIEW

**Comment by zhaojj2209** [comment]
Thanks for the fix!

Unfortunately I am unable to test this because I don't develop on Windows, any other maintainers using Windows please help to review this PR.

**Review by domlimm — APPROVED** [review]
LGTM! Thank you for your contribution!

**Comment by domlimm** [comment]
Things to note:
- `afterTestClosure` definition is used in `architectureTest`, `lnpTests`, `componentTests`, `e2eTests`, `axeTests`
- Works on Bash in Windows, Powershell

**Review by weiquu — APPROVED** [review]
LGTM! Works on Powershell, doesn't seem to cause any issues for mac (: Thanks for contributing

**Pull request merged**
