### PR TITLE
[#11571] Selective Deadline Extensions - Add collapsible tables to extension page

### LINKED ISSUE #11571: Selective Deadline Extensions
This issue keeps track of PRs relating to the selective deadline extensions feature. More info can be found on the wiki at https://github.com/TEAMMATES/teammates/wiki/Selective-Deadline-Extensions

We'll be working on a feature branch called [`selective-deadline-extension`](https://github.com/TEAMMATES/teammates/tree/selective-deadline-extension), and this issue will be resolved when the branch is merged into master. More details on maintaining a feature branch can be found in the [maintainer guide](https://github.com/TEAMMATES/teammates-ops/blob/master/maintainer-guide.md#using-a-long-lived-feature-branch).

### PR DESCRIPTION
**Pull request by FergusMok**
Part of #11571. Requires #11603 to be merged first 

image

Adds toggleable tables (no lazy loading)

In hindsight, the lazy loading of tables is not as useful as I thought. The almost negligible reads saved vs making the user wait for 1-2 more seconds is not worth implementing it.

### CODE REVIEW

**Comment by moziliar** [comment]
Wrong target branch? We will still want to merge it into the feature branch before merging all FE and E2E into master.

**Comment by moziliar** [comment]
Rebase this too.

**Comment by samuelfangjw** [comment]
Implementation seems fine! I would like to discuss UX of this dropdown though.

Now that we there's no lazy loading, what is the benefit of having this dropdown here and does it outweigh the disadvantages (one extra click before the user can extend deadline, information about who has deadline extensions hidden from user until dropdown opened)? Was wondering if having these open by default would be better.

**Comment by moziliar** [comment]
Just to weigh in my 2 cents: we probably can lazy load instructor panel upon toggling it open as it is less common a use case.
I agree that students panel should probably be loaded by default.

**Comment by samuelfangjw** [comment]
> Just to weigh in my 2 cents: we probably can lazy load instructor panel upon toggling it open as it is less common a use case.
> I agree that students panel should probably be loaded by default.

Actually according to the PR description, there's no lazy loading, so it's purely a UX enhancement. In this case, I don't really see the benefits of hiding the tables on first load. Was thinking it's better to show all and give the option to minimize than to show some and hide some, which seems a little confusing to me.

**Comment by FergusMok** [comment]
I was originally thinking that it should be closed on default, so that the instructor can easily see the 2 buttons at the bottom and understand the workflow more easily. Also, if the instructor would want to extend an instructor, it would be easier too (instead of having to scroll past the entire student list).

However, I realize these 2 cases probably don't make up the majority of use case. I also see value in leaving both tables open to extend students more easily. What do you think about this @moziliar ?

I'm thinking lazy loading instructors would have value, but as Samuel said, it'll be slightly strange to have 1 table open and the other closed by default.

**Comment by moziliar** [comment]
Let's not over optimize first and learn about the user behaviours before proceeding shall we? I guess we don't really know what the users like yet.

**Comment by samuelfangjw** [comment]
Closing as not required anymore.

Performance wise, minimal performance benefits even if lazy loading is implemented. On the UX side, it's an extra click for the user.

There's two problems with this page that occur when there are a large number of users that are partially addressed by collapsible tables, but I believe there are better solutions for these.

Firstly, if there are too many students/instructors, collapsing tables can help keep the screen organised. However, there are better solutions to this problem, such as pagination or filters/search for example.

Secondly, the buttons to extend/delete as well as the table for instructors are hidden at the bottom and may not be immediately visible to a user. In the case of extend/delete, this also means the instructor has to scroll to the bottom, even if they knew where to look. In this case, the better approach would be to increase the visibility of these buttons/options (e.g. sticky footer, tabs at the top, etc.) instead of collapsible tables.

**Pull request closed without merging**
