### PR TITLE
Unsupported pseudo: hover #4925

### LINKED ISSUE #4925: Unsupported pseudo: hover
Hi,

I've found some kind of bug while using 'Session Results' page. It is observed using Chrome and Firefox.
How to reproduce: move mouse pointer between different values of 'Giver' column

Actual result:
Quite frequently the following exception is observed in browser console:
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: hover
ga.error @ jquery.min.js:2ga.selectors.filter.PSEUDO @ jquery.min.js:2xa @ jquery.min.js:2ga.compile @ jquery.min.js:2ga.select @ jquery.min.js:2ga @ jquery.min.js:2ga.matches @ jquery.min.js:2m.filter @ jquery.min.js:2w @ jquery.min.js:2m.fn.extend.is @ jquery.min.js:2(anonymous function) @ instructor.js:247

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #4925

### CODE REVIEW

**Comment by belyabl9** [comment]
Please, review

**Comment by damithc** [comment]
@yj-soh for your review

**Comment by yj-soh** [comment]
`.siblings('.popover:hover')` appears to be usable as an alternate for `.siblings('.popover').find(':hover')`.
Looks fine aside from that, though.

On a side note, did the behavior change? I tried, but the popover hiding appears to work just as well despite the error in the console.

**Comment by belyabl9** [comment]
@yj-soh, I've got the same result. Behavior wasn't affected, so provided changes just remove the exception in the console.

**Comment by thyageshm** [comment]
@yj-soh could you please merge this soon?

**Comment by thyageshm** [comment]
@yj-soh reminder to merge this pr

**Comment by kanghj** [comment]
@yj-soh merge this soon

**Pull request merged**
