### PR TITLE
Fix typos in FieldValidatorTest #7315

### LINKED ISSUE #7315: Fix typos in FieldValidatorTest
'string' is misspelled in the message of `assertEquals` in `invalidityInfoFor_invalidGender_returnErrorString` and 'specific' is misspelled in the message of `assertEquals` in `testGetInvalidityInfoForEmailSubject_invalid_returnSpecificErrorString`.

### PR DESCRIPTION
**Pull request by andydaehn**
Fixes #7315 

The typos were fixed in FieldValidatorTest. Method testGetInvalidityInfoForEmailSubject_invalid_returnSpecificErrorString The word 'string' was changed to be spelled correctly. In method testGetInvalidityInfoForFeedbackSessionName_invalid_returnSpecificErrorString the word 'specific' was changed to be spelled correctly.

### CODE REVIEW

**Comment by andydaehn** [comment]
Thank you so much for the help, and giving me a chance at fixing this. I will fix line 352, and I will be sure to re-read all the documentation for contributing. I should be able to fix this soon.

**Comment by andydaehn** [comment]
I believe I have made the proper changes, but I do not know where #7343 comes from in the title. I must have mistyped something. Should I close this PR, and start a new one with the changes? Thanks much for the help! ;)

**Comment by VamsiSangam** [comment]
Hi @andydaehn ! The `+` on line 352, should come on the next line, i.e. on 353. This is a convention we follow.

capture

If you see, line 355 and 356 follow this convention. You can refer to these lines to make the required changes. :blush:

**Comment by chowyb** [comment]
@andydaehn #7343 refers to this exact PR, and is expected behaviour. Your current title of `Fix typos in FieldValidatorTest #7315` is correct.

Note that even if the title is not correct, it is possible to edit the PR title without having to open a new one.

**Comment by andydaehn** [comment]
Wow! You guys are an awesome team! I think I made the proper corrections. Thanks much for the help.

**Pull request merged**
