### PR TITLE
studentList.tag: prevent 'Add Comment' button causing a 'page not found' error #7203

### LINKED ISSUE #7203: studentList.tag: prevent 'Add Comment' button causing a 'page not found' error
**Description of feature/enhancement**

In `instructorStudentListPage` and `instructorCourseDetailsPage` (both of which rely on `studentList.tag`), the "Add Comment" button click leads to `pageNotFound.jsp`. We could instead trigger the dropdown to display upon clicking the "Add Comment" button or the down caret button beside it.

**Justification**

"Add Comment" which is mainly used to display the tooltip is still clickable nonetheless and redirects user to `pageNotFound.jsp`. User might not like to see a **Page not found** warning all of a sudden when the tooltip nicely said "Give a comment to student...".

This issue is to eliminate the exposed possibility of user getting a warning. My suggestion is to trigger the dropdown on any of the buttons. Other suggestions are most welcome.

### PR DESCRIPTION
**Pull request by VamsiSangam**
Fixes #7203 

**Outline of Solution**

- Removed `href="javascript:;"` on `Add Comment` button which was causing redirection to `pageNotFound.jsp`.
- Added `data-toggle="tooltip" data-placement="top"` to the `.btn-group` instead so that hovering over either of the buttons gives the tooltip.
- Shifted tooltip title logic to `.btn-group` which was formerly on the `Add comment` button.
- Added `href="javascript:;" data-toggle="dropdown"` to 'Add Comment` button so that it triggers the dropdown.
- Shifted `ul .dropdown-menu` upward. Placed it in between `Add Comment` button and the down caret button, because making it the last child in `div .btn-group` will make the down caret button's shape squared. Bootstrap uses first-child last child logic to determine `border-radius` of buttons in a button group. Eg. Bootstrap applies this for the `Add comment` button -

``` javascript
.btn-group > .btn:first-child:not(:last-child):not(.dropdown-toggle) {
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
}
```

this goes for the down caret button -

``` javascript
.btn-group > .btn:last-child:not(:first-child), .btn-group > .dropdown-toggle:not(:first-child) {
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
}
```

Used godmode. Status - ongoing.

### CODE REVIEW

**Comment by damithc** [comment]
Also consider updating some of the existing UI tests to click on the offending button and confirm it behaves as expected.

**Comment by VamsiSangam** [comment]
Sure! Working on it!

**Comment by VamsiSangam** [comment]
Ready for review.

**Comment by VamsiSangam** [comment]
**Outline of changes made**

- added `getAddCommentButton()` in `InstructorCourseDetailsPage.java` which selects the `Add Comment` button and returns the associated `WebElement` object.
- added `clickAddCommentStudentViaAddCommentButton()` in `InstructorCourseDetailsPage.java` which clicks on `Add Comment` button for a given student and then clicks on `add comment to student` option, returns the redirected page.
- added code in `testLinks()` of `InstructorCourseDetailsPageUiTest.java` which calls `clickAddCommentStudentViaAddCommentButton()` and verifies it.

**Comment by damithc** [comment]
@VamsiSangam I've renamed issue/pr, FYI

**Comment by VamsiSangam** [comment]
Ok sir 👍

**Pull request merged**
