### PR TITLE
[#8866] Submit feedback: optimize layout of questions

### LINKED ISSUE #8866: Student: submit feedback: optimize layout of questions
This is how we show a question in the submission page:
image

Suggested: improve/redesign the layout/formatting to save space e.g., remove unnecessary line breaks, borders, lines, etc.

### PR DESCRIPTION
**Pull request by darrenlmd**
**PR Checklist**
Fixes #8866 

**Outline of Solution**
Go with solution 1 (simply removing `<br>` and `<hr>`) as discussed [here](https://github.com/TEAMMATES/teammates/issues/8866)

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@darrenlmd, can you post a screenshot of the result of your changes?

**Comment by darrenlmd** [comment]
sol

**Comment by wkurniawan07** [comment]
@damithc ok with the new layout?

**Comment by damithc** [comment]
> @damithc ok with the new layout?

Yup 👍

**Comment by darrenlmd** [comment]
Great! I'll start on a new issue when the time permits.

**Pull request merged**
