### PR TITLE
[#9302] Support rich text for MCQ option text

### LINKED ISSUE #9302: Support rich text for MCQ option text
Current: MCQ and MSQ question answer options allow plain text only. 

image

Suggestion: allow rich-text so that options can provide more rich details 

This can also be done as a separate optional field `description` for each answer option.

### PR DESCRIPTION
**Pull request by niqiukun**
Fixes #9302

Current progress:
- [x] Edit question details page
- [x] Edit question answer page
- [x] Session results page
- [ ] CSV files download

Before:
image
image

After:
image
image
image

### CODE REVIEW

**Comment by niqiukun** [comment]
Drag and drop is currently interfering with the text editor (for example, it is unable to position the text cursor using mouse), hence I had to make some UI changes to separate the drag handle from the mcq-field component. Note that the the width of the text editor adjusts as the weight option is selected.

Preview:
image
image

Please let me know if this change is acceptable, so that I can continue with other components (multiple selection questions, other questions based on options). Thanks!

**Comment by niqiukun** [comment]
Somehow the `cdkDropListDisabled` input for `cdkDropList` cannot pass the test but the functionality is working fine (to disable dragging while the fields are not editable). The documentation can be found [here](https://material.angular.io/cdk/drag-drop/api#CdkDropList). Any idea why that happens?

**Comment by xpdavid** [comment]
You should import module (i,e. `DragDropModule`) for `cdkDropListDisabled` in the test file.

**Comment by niqiukun** [comment]
> You should import module (i,e. `DragDropModule`) for `cdkDropListDisabled` in the test file.

Yup it works. But I don't quite get it though because `cdkDropListDropped` does not require the import.

**Comment by xpdavid** [comment]
`cdkDropListDropped` is a derivative in the `DragDropModule` module.

**Comment by rrtheonlyone** [comment]
Nice work with this PR!

Some preliminary comments:

Shall we focus only on MCQ question types here? This way it is easier for me to review and look at the code. Once that is merged, we can easily update the other types. 

You can also rebase to remove commits like "fix failing tests" and only include relevant changes.

For MCQ Questions:

Screenshot 2020-02-09 at 10 04 37 AM

This is the panel that pops up to allow me to have bold text / tables. However, there are unnecessary stuff here like print / open file? Is there any way we can remove this? The panel is also way bigger than the actual text field and it looks a little odd.

Code-wise I had a glance through - it seems to be mainly UI changes (css and adding of a new component `<tm-rich-text-editor>`  to the html). It looks okay; I can take a closer look once tests are passing.

**Comment by niqiukun** [comment]
@rrtheonlyone 

Thanks for the review! I will look into the issue regarding the text editor panel. I have also removed the commits for MSQ and ranking options for now.

**Comment by damithc** [comment]
> Code looks fine. Pass @damithc for UI review

UI looks OK. I hope having rich text for options doesn't mess up the results page or the csv files that users download.

**Comment by niqiukun** [comment]
Will look into the results page and csv files. Sorry but may have to change the label back to ongoing.

**Comment by niqiukun** [comment]
Proposed change for results page:
image
Note that the responses in the table are kept in their original format while options expandable additional details are with HTML tags stripped off. Would like to know if this UI change is ok. @damithc

**Comment by damithc** [comment]
> Note that the responses in the table are kept in their original format while options expandable additional details are with HTML tags stripped off. Would like to know if this UI change is ok. @damithc

hmm... what if the option is just an image? We might have to use option numbering (e.g., `a`, `b`, etc.), not just bullet points.

Also, if the option text is long, it is wasteful to repeat it many times in the table? Perhaps clip the text at some length?

General note: in UI prototyping, use more realistic data e.g., realistic person names

**Comment by niqiukun** [comment]
> hmm... what if the option is just an image? We might have to use option numbering (e.g., `a`, `b`, etc.), not just bullet points.

Because responses are kept in their original format as displayed in the table, viewer of the results can see the images being selected. The only issue is with the additional information since HTML tags will be stripped. However, this shouldn't affect much since the information is collapsed by default. Certainly,  option numbering can be implemented in future to improve this.

> Also, if the option text is long, it is wasteful to repeat it many times in the table? Perhaps clip the text at some length?

My concern would be that after clipping, some long option text with variation at the end maybe clipped off, hence viewer of the results may not be able to differencitate two options. It is okay to clip the text inside the addtional information instead, but I think the table should display the options in their original way.

> General note: in UI prototyping, use more realistic data e.g., realistic person names

I will take note of this.

**Comment by damithc** [comment]
> Because responses are kept in their original format as displayed in the table, viewer of the results can see the images being selected. The only issue is with the additional information since HTML tags will be stripped. However, this shouldn't affect much since the information is collapsed by default. Certainly, option numbering can be implemented in future to improve this.

I was referring to the bullet list in the panel header.

**Comment by niqiukun** [comment]
> I was referring to the bullet list in the panel header.

Ah I see. My understanding of the bullet list is just a list for reference. So stripping off the html tags can save space. There is no need to differentiate between different options so should be fine.

**Comment by damithc** [comment]
> Ah I see. My understanding of the bullet list is just a list for reference. So stripping off the html tags can save space. There is no need to differentiate between options so I suppose it should be fine. Please do let me know your concern so I can adjust accordingly. Thank you very much!

Sorry, let me clarify: If an option is just an image with no text, wouldn't that result in an empty bullet point?

**Comment by niqiukun** [comment]
> Sorry, let me clarify: If an option is just an image with no text, wouldn't that result in an empty bullet point?

Ok now I get it. I have done the following change to text strip rules:
image
Specifically, `` tag will be replaced by `[Image]` while `<table>` will be replaced by `[Table]`. Let me know if this addresses your concern. Thanks!

**Comment by damithc** [comment]
> Specifically, `` tag will be replaced by `[Image]` while `<table>` will be replaced by `[Table]`. Let me know if this addresses your concern. Thanks!

Should be fine.

**Comment by niqiukun** [comment]
I tried the download results button in the session page and nothing seems to happen after clicking. Inspection of code suggests that the button does not has any click event. Is the feature yet to be implemented or am I missing something? @rrtheonlyone

**Comment by xpdavid** [comment]
Feature to be implemented. You can leave it there first.

**Comment by niqiukun** [comment]
> Feature to be implemented. You can leave it there first.

Okay. Anyone working on this feature right now? If not I can try working on it.

**Comment by xpdavid** [comment]
Go ahead :P

**Pull request merged**
