### PR TITLE
[#2719] Student: view results: do not show anonymous results if there is only response per team

### LINKED ISSUE #2719: Student: view results: do not show anonymous results if there is only response per team
If only one student submitted responses and there are anonymous and non-anonymous questions, the recipient can guess the sole responder via the non-anonymous questions.

Suggested: If a session has both anonymous and non-anonymous questions, hide responses to an anonymous question if there is only one response for that question.

### PR DESCRIPTION
**Pull request by lyeyixian**
Fixes #2719

**Outline of Solution**
Adds 2 new boolean fields `hasAnonymousResponse` and `hasNonAnonymousResponse` to be checked at the `*ngIf` attribute.

The anonymous responses are identified by checking if `question.feedbackQuestion.showGiverNameTo` array has `"RECIPIENT"` in it.

**Anonymous response not shown**
image

**Shown after getting more than 1 response**
image

**Also shown when there is only anonymous response**
image

### CODE REVIEW

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]
This is not the right approach. It's merely hiding from view, but the response is very much still there within the API response.

**Comment by lyeyixian** [comment]
> This is not the right approach. It's merely hiding from view, but the response is very much still there within the API response.

Ah okok, I will look into it again and make changes to the backend.

**Comment by lyeyixian** [comment]
Hi, I have already updated the backend, the overall logic is still the same.

**Comment by wkurniawan07** [comment]
Closing as the linked issue has been made invalid.

**Pull request closed without merging**
