### PR TITLE
Improve StudentAttributes.java doc comments  #6606 solved 

### PR DESCRIPTION
**Pull request by shivanshsoni**
Improve StudentAttributes.java doc comments 
only check my last commit [5acab5d](https://github.com/shivanshsoni/teammates/commit/5acab5d719bc62ca4da464d1c8622a417ae04e52)

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@shivanshsoni When you are creating a PR you will get something kind of template which has guidelines related to submitting a new PR. Please follow that.

**Comment by shivanshsoni** [comment]
ok  Sir, I will take care of that in future

**Comment by shivanshsoni** [comment]
thanks :-)

**Comment by AnaghHegde** [comment]
@shivanshsoni Why you have changed so many files?. Issue says only about `StudentAttributes.java` ?

>Improve StudentAttributes.java doc comments
 only check my last commit 5acab5d

This one has to be changed else it would be difficult to keep track of the issue which you are solving.

Fixes #issuenumber 
 **Outline of Solution**
 Breif description of what you have done.

Unsless you resolve the merge conflicts CI tests will not run.

**Comment by samsontmr** [comment]
@shivanshsoni Your PR title should be simply`Improve StudentAttributes.java doc comments #6606`. Don't add anything else or the bot will complain.

**Comment by wkurniawan07** [comment]
@shivanshsoni, unfortunately "only check my last commit" is not an acceptable practice. Your `master` branch is polluted with many unnecessary changes and it causes the merge conflicts as shown. You need to clean your `master` branch, and commit the necessary changes on a new branch started from the clean `master` branch. This is not a matter of "take care of that in future"; unless you can follow it, I'm afraid that this PR is not to be accepted.
On top of that, do take note that one PR should only fix one issue, unless multiple issues are tightly related.

**Pull request closed without merging**
