### PR TITLE
Rubrics: don't show numerical values of options in students' view #5015

### LINKED ISSUE #5015: Rubrics: don't show numerical values of options in students' view
The numerical values for computing the average can be hidden for the student's submit page for now, until we allow instructors to specify the numerical value for each option in #4746.

Edit: need to hide in student results page too

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #5015

### CODE REVIEW

**Comment by kanghj** [comment]
Made the pull request against the wrong branch, but will merge to release as V5.72.01

**Comment by kanghj** [comment]
@damithc, merged to release

**Comment by damithc** [comment]
Noted @kanghj. I'll release a hot fix.

**Comment by damithc** [comment]
image

**Comment by kanghj** [comment]
Oops, didn't notice that column was wrong, will make a new issue.

**Pull request merged**
