### PR TITLE
[#9996] Typo in the pop-up message of the button "Send Invite"

### LINKED ISSUE #9996: Typo in the pop-up message of the button "Send Invite"
typo-issue-teammates

- **Environment**:  The screenshot is from an instructor's account in the Student List page.

- **Expected behaviour**: I think that the right message should be "...using his/her Google Account..."
and "...without joining, but a..."

I would like to work on this issue!

### PR DESCRIPTION
**Pull request by AdamPanag**
Fixes #9996

### CODE REVIEW

**Comment by madanalogy** [comment]
Hello, thanks for contributing to TEAMMATES! The CI is failing because the snapshots affected by your change needs to be updated. You will need to execute `npm run test` and follow on-screen instructions to update the snapshots. You can refer to the testing guide [here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#testing) and more information about snapshot testing [here](https://github.com/TEAMMATES/teammates/blob/master/docs/snapshot-testing.md).

If the instructions above didn't resolve the issue or if you have any questions in general, let us know and we'll be happy to help :)

**Comment by AdamPanag** [comment]
Hello @madanalogy ! I tried to update the snapshots with these 3 commands:

jest --updateSnapshot
npm test -- --updateSnapshot
./node_modules/.bin/jest --updateSnapshot

but the snapsot testing (npm run coverage) still don't succeed. Is there any other way?

**Comment by madanalogy** [comment]
> Hello @madanalogy ! I tried to update the snapshots with these 3 commands:
> 
> jest --updateSnapshot
> npm test -- --updateSnapshot
> ./node_modules/.bin/jest --updateSnapshot
> 
> but the snapsot testing (npm run coverage) still don't succeed. Is there any other way?

Could you commit and push your changes to the snapshot? Or did you mean that you couldn't update the snapshot with those commands?

**Comment by AdamPanag** [comment]
> > Hello @madanalogy ! I tried to update the snapshots with these 3 commands:
> > jest --updateSnapshot
> > npm test -- --updateSnapshot
> > ./node_modules/.bin/jest --updateSnapshot
> > but the snapsot testing (npm run coverage) still don't succeed. Is there any other way?
> 
> Could you commit and push your changes to the snapshot? Or did you mean that you couldn't update the snapshot with those commands?

These are the outputs that I get running the commands below:

./node_modules/.bin/jest --updateSnapshot

Screenshot_3

npm test -- --updateSnapshot

Screenshot_4

I don't think that the snapshots are updated!

**Comment by madanalogy** [comment]
Try running the command `npm run test` instead, and press `a` to run all the tests. I checked out your PR locally and doing so gives me the option to update the failing snapshot:

Screenshot 2020-04-01 at 10 22 23 PM

**Comment by AdamPanag** [comment]
> Try running the command `npm run test` instead, and press `a` to run all the tests. I checked out your PR locally and doing so gives me the option to update the failing snapshot:
> 
> Screenshot 2020-04-01 at 10 22 23 PM

How exactly should I press 'a'? Sorry if the question is very basic

**Comment by madanalogy** [comment]
> How exactly should I press 'a'? Sorry if the question is very basic

Don't worry about it, we're here to help. What you want to do is to execute `npm run test` from your teammates working directory. This will run the angular test suite which will then give you the option to rerun all tests (with `a`) and update failing snapshots afterwards (with `u`). I've included a short clip below demonstrating the sequence:

Apr-02-2020 12-45-53

Another tip, since you've merge the latest updates from master into your branch, you might want to run the gradle task `generateTypes` since the updates include some refactoring of endpoints. This should help clear all your tests locally (i.e. those not related to the snapshot) in case you are concerned about those :)

**Comment by AdamPanag** [comment]
> > How exactly should I press 'a'? Sorry if the question is very basic
> 
> Don't worry about it, we're here to help. What you want to do is to execute `npm run test` from your teammates working directory. This will run the angular test suite which will then give you the option to rerun all tests (with `a`) and update failing snapshots afterwards (with `u`). I've included a short clip below demonstrating the sequence:
> 
> Apr-02-2020 12-45-53
> 
> Another tip, since you've merge the latest updates from master into your branch, you might want to run the gradle task `generateTypes` since the updates include some refactoring of endpoints. This should help clear all your tests locally (i.e. those not related to the snapshot) in case you are concerned about those :)

Thank you very much for the help! However, after executing `npm run test` this happens:

Screenshot_6

I waited for more than 30 minutes and it stays as it is! It doesn't give me the option to rerun all tests (with a).

**Comment by madanalogy** [comment]
> I waited for more than 30 minutes and it stays as it is! It doesn't give me the option to rerun all tests (with a).

Could you try running `ng test --watchAll` instead? If the problem persists I'll try and get someone who uses Windows to help.

**Comment by AdamPanag** [comment]
> Could you try running `ng test --watchAll` instead? If the problem persists I'll try and get someone who uses Windows to help.

I tried the default command line of my computer instead of git bash and it worked. Thank you very much!

**Comment by damithc** [comment]
Glad to hear that @AdamPanag 
Thanks for the guidance @madanalogy 👍

**Comment by madanalogy** [comment]
@AdamPanag could you take a screenshot of the new tooltip (after your fix)? Thanks! :)

**Comment by AdamPanag** [comment]
> @AdamPanag could you take a screenshot of the new tooltip (after your fix)? Thanks! :)

solved

**Pull request merged**
