### PR TITLE
Show loading gif picture while the profile picture is being loaded #2312

### LINKED ISSUE #2312: Show loading gif picture while the profile picture is being loaded
instructor.js is to be edited for both hover-triggered and click-triggered ViewPhoto events.

### PR DESCRIPTION
**Pull request by xpdavid**
Fixes #2312 

**How do I fix:**
I insert a `` element (i.e. The git loading spinner) when the profile picture is loading. When loading finished (set by `.load(function() {...})`), I remove the `` element.

The CSS selector in the `teammatesCommon.css`, force `img` to be 40x40px. But that is ugly for loading gif. 
``` css
.profile-pic-icon-hover > img,
.profile-pic-icon-click > img {
    width: 40px;
    height: 40px;
}
```
I can't find any similar style both in bootstrap css and `teammatesCommon.css`, so I create a new css style `profile-pic-icon-click-ajax-loading-img`, not sure wether it is necessary.
(Note that we need `!important` to override the style)
``` css
.profile-pic-icon-click-ajax-loading-img {
    height: auto !important;
}
```
**UI demo:**
demo

### CODE REVIEW

**Comment by damithc** [comment]
@xpdavid A general question: is your approach different from how we do it in other places of the app? If yes, does it have to be different?

**Comment by xpdavid** [comment]
@damithc I examine `ajaxResponseRate.js`, it also use similar approach.
``` javascript
parentOfHyperlinkObject.html('<img src="/images/ajax-loader.gif"/>');
```
Actually, my question is wthether it is necessary to create a new style `.profile-pic-icon-click-ajax-loading-img`. We can use add the css attribute `width: auto !important` to the element in `js` script instead (rather than create a new style `.profile-pic-icon-click-ajax-loading-img`) but I don't think this is recommended approach as it is not the `js` script's responsibility to control the css style.

**Comment by damithc** [comment]
> my question is wthether it is necessary to create a new style .profile-pic-icon-click-ajax-loading-img

I don't have the expertise to answer that question, so we'll have to wait for someone else from the team to respond to that. However, [this](https://oss-generic.github.io/process/codingStandards/CodingStandard-Css.html) says the use of `important!` is disallowed. We can make an exception if there is a justification.

**Comment by xpdavid** [comment]
Pls delay the review, I miss out sth. :P

**Comment by xpdavid** [comment]
@damithc Ready for review.
The use of `!important` has been removed :)
Add support for showing loading gif picture in popover.
demo3
It's too fast :P

**Pull request merged**
