### PR TITLE
[#11719] student submitting responses: inform that submitting individual responses is optional

### LINKED ISSUE #11719: student submitting responses: inform that submitting individual responses is optional
version: v8.13.1, production

In recent times, we have added a feature for respondents to submit one question at a time. We also have a button at the bottom of the page to submit the whole page, as before.

Some users seem to think that they _have_ to submit each question individually and then submit the whole page one more time at the end.

Suggestion: We can tweak the UI to inform the respondent that submitting individual responses is optional.

### PR DESCRIPTION
**Pull request by zhengtaoJ**
Fixes #11719 

**Outline of Solution**

- Added a notice within the alert in the session submission page, to inform user that submitting individual responses for each question is optional.

**Questions**

- Should we break the notes into a few list items? I chose to add a sentence to the end of previous note for consistency, as the two notes were in the same line previously.

**Before:** 
image

**After:** 
image

This PR is ready for review.

### CODE REVIEW

**Review by ziqing26 — CHANGES_REQUESTED** [review]
Hi, thanks for contributing! It is a good suggestion to break the notes into a few listed items to make the UI look more organized, maybe you could submit a screenshot for that so that we could compare?

**Comment by zhengtaoJ** [comment]
Sorry for the delayed update on this. Here's the preview :

**Notes as (unordered) list items**
image

**Notes as (ordered) list items**:
image

**Comment by damithc** [comment]
I think the phrasing needs to be clearer or else they might think some questions are optional. Something like the below?
> * You can use the `Submit Response for Question _` buttons to submit one-response-at-a-time.
  Alternatively, you can submit all responses in one go using the `Submit Responses for All Questions` button at the bottom of this page.

'Unordered list' is better as these are not steps but independent points?

**Comment by zhengtaoJ** [comment]
I agree with you. I've changed the phrasing. I'm thinking about whether the second point ("`Alternatively...`") should go into a nested list or not, as it's like a follow-up for the first point. However, this can make the UI more complex.

**Second point in nested list**
image

**Second point combined with first point**
image

**Second point as a separate point**
image

**Comment by zhengtaoJ** [comment]
I've updated the PR such that the note matches the format advised by Prof Damith.

**Review by hhdqirui — APPROVED** [review]
Looks good to me. Hi Prof @damithc, would like to ask for your final confirmation.

**Comment by damithc** [comment]
> Looks good to me. Hi Prof @damithc, would like to ask for your final confirmation.

I'm OK with this. Don' we currently use bold text when referring to text in the UI (e.g., button names etc.)? Perhaps follow the same for the sake of consistency? If using quotes instead (e.g., `"Submit"`, I think it should be single quotes rather than double quotes.

**Comment by zhengtaoJ** [comment]
Hi Prof, before this change, there's no formatting on the text in the UI (for the note appearing here). I saw another issue #11830 stating that we shouldn't use bold for text in the UI. The assignee of that issue proposes to use `<mark>` instead. Should I follow the previous practice (using bold), or follow the proposed use of `<mark>` instead?

**Comment by damithc** [comment]
> Hi Prof, before this change, there's no formatting on the text in the UI (for the note appearing here). I saw another issue #11830 stating that we shouldn't use bold for text in the UI. The assignee of that issue proposes to use `<mark>` instead. Should I follow the previous practice (using bold), or follow the proposed use of `<mark>` instead?

@zhengtaoJ That PR is not done yet and there is no decision on what format to use exactly. In that case best to follow the existing convention. If this PR merges first, you can put a note in that issue to remind that this needs to be updated to the new formatting as well.

**Comment by zhengtaoJ** [comment]
Hi Prof, I've changed the text referring to UI to bold form and the related tests, here's the preview:
image

**Comment by damithc** [comment]
> Hi Prof, I've changed the text referring to UI to bold form and the related tests, here's the preview:
> image

I'm OK with this version @zhengtaoJ Thanks for the quick update.

**Comment by zhaojj2209** [comment]
@ziqing26 Reminder for this review, thanks!

**Review by ziqing26 — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request merged**
