### PR TITLE
[#12375] Update phrasing of contact page

### LINKED ISSUE #12375: Incorrect Developer Website link in Contact page
**Environment**: 
V8.26.0

**Steps to reproduce**

https://teammatesv4.appspot.com/web/front/contact

image

**Expected behaviour**

Should link to https://teammates.github.io/teammates/index.html.

**Actual behaviour**

Links to back to [TEAMMATES repository](https://github.com/TEAMMATES/teammates).

### PR DESCRIPTION
**Pull request by itstrueitstrueitsrealitsreal**
Fixes #12375

**Outline of Solution**

Changed the text hyperlinked to the TEAMMATES GitHub on the contact page to be Project Website to be consistent with the phrasing used on the [NUS-OSS](https://nus-oss.github.io/index.html#projects) projects page.

### CODE REVIEW

**Comment by dishenggg** [comment]
One thing to note is that our repository readme has it as `TEAMMATES Developer Web Site` so this could possibly generate more confusion? I am leaning towards just calling it Teammates Github, maybe others can pitch in as well.

**Comment by itstrueitstrueitsrealitsreal** [comment]
@dishenggg oh, I failed to consider that. How would this look instead? I also added an icon to reduce confusion.
image

**Review by dishenggg — APPROVED** [review]
LGTM!

**Review by mingyuanc — APPROVED** [review]
LGTM

**Pull request merged**
