### PR TITLE
Outdated links in the about page #4771

### PR DESCRIPTION
**Pull request by yash14123**

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Thanks for your pull request, @yash14123.
When fixing issues and creating PRs, please follow the workflow specified [here](https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md), in particular on how to name the branch, the PR, and what to write on the PR description. You need to make a PR from a correctly named branch so I'll close this.
In addition, you cannot do more than one `d.FirstTimers`-labelled issues. Since I presume this will be your `d.FirstTimers` issue, please refrain from working on another one. You are welcome to contribute to other issues, in particular the ones labelled `d.Contributors`.

**Comment by yash14123** [comment]
Shall I issue another PR with the right format?

**Comment by wkurniawan07** [comment]
Feel free to if you wish.

**Comment by yash14123** [comment]
Were the files evaluated? I hope the commits seem fine. Just a proper formatted PR required?

**Comment by wkurniawan07** [comment]
Actually, no. You also removed the links to GitHub. Only the links to Google Code need removal.

**Pull request closed without merging**
