### PR TITLE
Student: view session results: do not show self responses #6290

### LINKED ISSUE #6290: Student: view session results: do not show self responses
Current:
When students view session results, they can see responses they gave to others. 

Suggestion:
Don't show responses the user gave to others. Instead, give a link to show the corresponding submission page. 

Justification:
Self-responses clutter the page. Some students get confused by self-responses.

### PR DESCRIPTION
**Pull request by dalessr**
Fixes #6290 

**Outline of Solution**

- Add a new section with title `Your own response`
- Move all the self-responses to the new section below. This is done by separating `FeedbackResponseTables` into two groups, one group with feedback giver as `You` and the other with giver as `Others`
- Change the panels color to be gray, as Prof @damithc suggested

**Current:**
6290-current-1

6290-current-2

See whether this looks clearer and less confusing to students!

### CODE REVIEW

**Comment by dalessr** [comment]
Status: ongoing

**Comment by dalessr** [comment]
Status: Ready for review

**Comment by dalessr** [comment]
Actually I don't think the original display of feedback result looks confusing to students... And if we separate others responses and self responses, then there is a higher chance that some questions are displayed without any response below. In this case, only showing the question is not suitable, but skipping the question is also not suitable.

The color of the panels actually does not matter since we separate them into two parts, which is clear enough.
 
The mockup proposed by @joanneong looks nice. It emphasizes the own responses for each question, which is clear enough for students. But is it a bit redundant to have "Your own response" for every question?

Would like to hear the others' suggestions @damithc @xpdavid

**Comment by xpdavid** [comment]
@dalessr I prefer @joanneong 's suggestion actually (A side note: @dalessr, to save ur time and also not to waste your effort, next time please discuss your solution (if the solution is not straight forward) under the issue before u are sending PR). Even we can collapse the tab.

BTW, if we are talking about `Your own response`, I belive the issue should be `Student: view session results: do not show student's own responses`.

**Comment by damithc** [comment]
> Would like to hear the others' suggestions @damithc @xpdavid

I'm OK with the approach proposed by @joanneong

**Comment by dalessr** [comment]
Okay noted. Will work on it. Thanks for the suggestions! @xpdavid @damithc

**Pull request closed without merging**
