### PR TITLE
Avoid throwing raw exception types in production code #7085

### LINKED ISSUE #7085: Replace raw exception throws in production code
> There is a rule in `PMD` named `AvoidThrowingRawExceptionTypes` and it indicates that throwing raw exception types is not a practice in software engineering. We may want to use `Assumption.assert*` rather than throwing raw exceptions in the production code. Therefore, we should change all RuntimeException to make use of `Assumption` class for production code.

image
For example, we should use `Assumption.assert*` here.

Three Tasks here.
1. Add `<rule ref="rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes"/>` to `teammates-pmdMain.xml`
2. Fix violations reported by PMD (Make use of `Assumption.assert` instead)
3. Remove `TODO` if it is necessary (Like the example above)

### PR DESCRIPTION
**Pull request by AnaghHegde**
Fixes #7085 

**Outline of Solution**
- I have created two methods in Assumption class to handle the below two types of exceptions
     - RunTimeExcepetion(String)

     - RunTimeExcepetion(String, Throwable)

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@xpdavid In AssertionError class 

```
 private AssertionError(String detailMessage) {
        super(detailMessage);
    }
```

it should be made public. If it's private there is no point in having it as none of the other class can make use of this. And when we want use the `Assumption.assert*` methods there are two types of RunTimeExcepetion needs to be handled : 

- RunTimeExcepetion(String)

- RunTimeExcepetion(String, Throwable)

In order to handle the 1st one in Assert method call stack goes like this 
 
 `RunTimeException(String) -- > Exception(String) --> Throwable(String)`. So in order to call the Throwable(String) from Assert method the only possible way i found is by calling the above mentioned method which calls `Error(String) -->Throwable(String)` .

Also the second issue is there are return statements inside the try block. So if i remove the throw statements in catch block i have to add return statement in catch block. 

Can you guide me a little.

**Comment by xpdavid** [comment]
> And when we want use the Assumption.assert* methods there are two types of RunTimeExcepetion needs to be handled

I am not sure what you are trying to say here.

> Also the second issue is there are return statements inside the try block.

I don't see any issue here. 

The task is rather simple, don't make it complicated. You may just replace all `throw new RuntimeException` with `Assumption.fail()`. Also, if `Assumption.assert*` can be used, make use of them.

**Comment by AnaghHegde** [comment]
>I don't see any issue here.

ok let me take an example and explain.

```
int calc() {
   try {  
      return 1;
   } catch (Exception e) {
       throw new RunTImeException(); //it won't result in error.
     // call to Assumption.assert*() will result in compilation error - missing return statement 
  }
}
```

>The task is rather simple, don't make it complicated. You may just replace all throw new RuntimeException with Assumption.fail().

I know but i am trying to say `Assumption.fail()` will call a different a method in `Throwable.class` where as RunTimeException() will call different method. So is it really a good idea to replace all the Exception statement with `Assumption.fail()` method ?. I have given detailed explanation of which methods are called by `fail()`, `RunTimeException()` .

`RunTimeException(e)` will call `Throwable(Throwable cause)`  

`RunTimeException(String)` will call `Throwable(String message)`

where as `fail(String)` will call `synchronized Throwable initCause(Throwable cause)`. 

This is the reason i have created two separate methods in Assumption class - commit  491235.

Correct me if i am wrong.

**Comment by xpdavid** [comment]
@AnaghHegde I get what you mean. Then it turns out the issue is not well-defined. Let me close the PR and investigate more.

Thanks for your contribution.

**Comment by AnaghHegde** [comment]
@xpdavid Ok but i want to work on this.

**Pull request closed without merging**
