### PR TITLE
[#12335] fix copy questions modal checkbox

### LINKED ISSUE #12335: Instructor sessions page: fix copy questions modal checkbox
Path: Instructor pages -> Sessions tab -> Edit feedback session -> Copy question

The modal that appears has a checkbox to select questions to copy over. However, there's no indication that it has been checked (e.g. in the screenshot below, rows 2 and 4 have been checked):
Screenshot 2023-04-03 at 1 07 23 PM

### PR DESCRIPTION
**Pull request by quantavoid11**
Fixes #12335 

**PR Checklist**

Ensure that you have:
- [ ] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [ ] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ ] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Review by weiquu — CHANGES_REQUESTED** [review]
Hi @quantavoid11, thanks for taking the time to look into this issue.

The checkbox for the modal looks different from the checkboxes used throughout the website. See the comparison below (current modal checkbox is the first, 2 other checkboxes below):
checkbox
checkbox 1
checkbox 2

I suspect the difference is being caused by the height and width set in the `.scss` file. For the sake of consistency, let's try to have the checkboxes look the same.

You could simply re-calculate the height and width, but I would like to suggest another solution.

Checkboxes within tables are used in other places, so I think it would be a good idea to implement these modal checkboxes in the same way. One such example is the last screenshot above, which is the visibility panel component (Instructor pages -> Edit feedback session -> Visibility). You can find the code for it in the `visibility-panel.component.html` file, which I strongly recommend you replicate in fixing the modal checkboxes.

Do let me know if you agree/disagree (:

**Comment by quantavoid11** [comment]
I do agree with you, I will do the changes soon and will submit a PR.

**Comment by weiquu** [comment]
> I do agree with you, I will do the changes soon and will submit a PR.

Thanks! (Note that you can push the changes onto this same branch (`12335-fix-copy-questions-modal-checkbox`), no need to close and submit a new PR)

**Comment by quantavoid11** [comment]
Yeah, got that. I am a beginner, so did a little mistake.

**Comment by quantavoid11** [comment]
Sorry, I deleted the branch by mistake. I will do the required changes and will submit the PR finally.

**Comment by cedricongjh** [comment]
hi @quantavoid11, no worries! 

If you've deleted your branch locally, you can still get it back by fetching it from your fork, by running `git fetch`. It would be ideal if can fetch the branch and update it, and continue using this PR, instead of opening a new one. We understand that you're new at this, so do reach out if you're facing difficulty doing this

**Comment by quantavoid11** [comment]
I have made the change, does it look promising?
image

**Comment by cedricongjh** [comment]
looks good! 

the discussion has been continued in #12348

**Pull request closed without merging**
