### PR TITLE
[#11826] Add unit tests for SubmitFeedbackResponsesAction

### LINKED ISSUE #11826: Add unit tests for `SubmitFeedbackResponsesAction`
`SubmitFeedbackResponsesAction` is by far the most important and the most used state-changing API of the system, and yet there are no unit tests for it.

### PR DESCRIPTION
**Pull request by u6358194**
Fixes #11826

**Outline of Solution**

 I created two test cases for SubmitFeedbackResponsesAction, I reviewed the two test cases which are already created by others and had a good understanding of related codes. Then I created test case for student and instuctor, if they submit feedback, then the status of feedback should be published, thus they can't edit this feedback anymore.

### CODE REVIEW

**Comment by hhdqirui** [comment]
Hi @u6358194 please remove the `package-lock.json` from this PR as it is irrelevant.

**Comment by u6358194** [comment]
> Hi @u6358194 please remove the `package-lock.json` from this PR as it is irrelevant.

how do I remove this file, I'm new to OSS project.

**Comment by u6358194** [comment]
@hhdqirui how do I remove this file, I'm new to OSS project.

**Comment by zhaojj2209** [comment]
> > Hi @u6358194 please remove the `package-lock.json` from this PR as it is irrelevant.
> 
> how do I remove this file, I'm new to OSS project.

In case it's not clear, the request was to revert the changes to `package-lock.json` so that it does not show up under "files changed" in this PR, not to remove the actual file. There are many ways for you to do that, hopefully you can figure out one of them.

**Comment by u6358194** [comment]
@zhaojj2209 sorry I have tried to revert but still  changed that json file, what should I do

**Comment by u6358194** [comment]
> @zhaojj2209 sorry I have tried to revert but still changed that json file, what should I do

I didn't commit this file after I revert but this file still changed

**Comment by zhaojj2209** [comment]
From your commit history it seems like the change to `package-lock.json` was done on the very first commit, so you may have to revert changes made to the entire branch.

Reverting your changes is not the only way to uncommit/revert `package-lock.json`. For your own learning, I would suggest doing your own exploration on how to solve this issue.

**Comment by zhaojj2209** [comment]
Closing due to inactivity. Feel free to reopen the PR if you would like to resume working on it.

**Pull request closed without merging**
