### PR TITLE
Remove additionalQuestionInfo.js import in instructorComments.jsp #6212

### LINKED ISSUE #6212: Remove additionalQuestionInfo.js import in instructorComments.jsp
Accidentally re-added in #6187 after removed in #6137.

### PR DESCRIPTION
**Pull request by swxsw**
Fixes #6212
Removed the import of additionalQuestionInfo.js from instructorComments.jsp

### CODE REVIEW

**Comment by swxsw** [comment]
Don't know why there are the merge commits because by right I updated from the teammates master branch before working on this fix, so the difference should not be there?

**Comment by damithc** [comment]
@swxsw don't do more than one `FirstTimer` issues.
To avoid merge commits in your branch, you can update master, rebase your branch on master (instead of merging master to your branch) and force-push the rebased branch to your fork

**Comment by swxsw** [comment]
Alright prof, noted with thanks. I am still figuring out the dependencies
and how the overall structure of the code works, I thought I should start
doing the small bits first, in this case those that is easy and urgent.
Will work on other non first timer tasks:) Thank you for the advice
regarding git, will try that out

**Comment by damithc** [comment]
@swxsw `d.Contributors` issues should be suitable for relatively new contributors.

**Comment by swxsw** [comment]
Noted, will try to work on those

**Comment by wkurniawan07** [comment]
@swxsw I apologize, but since you have done another `d.FirstTimers` issue this one has to be closed.

**Pull request closed without merging**
