### PR TITLE
[#9480] Add frontend tests to session result component

### PR DESCRIPTION
**Pull request by t-cheepeng**
Part of #9480, #10920

Added snapshot test for session result
Added unit test for reg key control flows
Added unit test for join course link

### CODE REVIEW

**Comment by rrtheonlyone** [comment]
Since we are already down this path, let's also take the time to add some unit tests for the page. 

We can test that the right data structures are initialised based on the results of API calls e.g. this page will fetch student/feedback session based on the result of authentication.

**Comment by rrtheonlyone** [comment]
Please fix the CI and request a review from me for this @t-cheepeng

**Comment by t-cheepeng** [comment]
@rrtheonlyone Fixed CI

**Review by rrtheonlyone — CHANGES_REQUESTED** [review]
Really good start here 💯 

Please add some extra tests for:
- checking snapshot when the feedback sessions have questions (consider a few different statistics)
- check right data structure initialised when we call `/result` - we don't just do `getFeedbackSession`, we also follow up with `getFeedbackSessionResults`

**Comment by t-cheepeng** [comment]
@rrtheonlyone 
Have added in the requested test

> (consider a few different statistics)

For the statistics snaps, I think it would be better to localize it to the specific `statistics-component` to test? Would get very unwiedly to test for the statistics in the `session-result-page`

**Review by rrtheonlyone — APPROVED** [review]
I still think there is much more we can test in this page :P However, that involves more discussion. 

Some tests are better than no tests... thanks for kickstarting this 👍 Let's get this in

**Review by madanalogy — APPROVED** [review]
LGTM

**Pull request merged**
