### PR TITLE
Update CheckStyle to 8.0 #7873

### LINKED ISSUE #7873: Update CheckStyle to 8.0
CheckStyle 8.0 (not the latest) is already supported in [Eclipse plugin 8.0.0](http://eclipse-cs.sourceforge.net/#!/) and [IntelliJ plugin 5.7.0](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) so we are ready to provide full support for it, contingent to our provision for Java 8 support.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #7873 

I need someone to supply me with information on what needs to be done on IntelliJ, in case changing the version number to `8.0` is not sufficient.

### CODE REVIEW

**Comment by damithc** [comment]
> I need someone to supply me with information on what needs to be done on IntelliJ, in case changing the version number to 8.0 is not sufficient.

@LiHaoTan is the intellij nija :-)

**Comment by LiHaoTan** [comment]
Yea you are right changing the version number is sufficient.

Though I was thinking of keep the version of CheckStyle in sync with the one used in the build script (that wasn't done previously because the CheckStyle used in IntelliJ required Java 8).

How about something like this?

https://github.com/TEAMMATES/teammates/compare/master...LiHaoTan:c9fc428c042549ca1fe27a984406788e9252e357

**Comment by wkurniawan07** [comment]
@LiHaoTan I am somewhat reluctant to implement that idea actually.
If I understand it correctly, there is no way to _sync_ the version number between `build.gradle` and the IDEA plugin, right? While your implementation will be useful for setting up, it seems to me that it adds too much code for such a little use case, and the version number of CheckStyle is not subjected to that often of a change. (background: since its introduction in May/June 2016 there has only been one upgrade #5640, and this is the second)

**Comment by whipermr5** [comment]
> If I understand it correctly, there is no way to sync the version number between build.gradle and the IDEA plugin, right?

@LiHaoTan Can confirm this?

**Comment by LiHaoTan** [comment]
Well, there are two ways to sync the version number between `build.gradle` and the CheckStyle-IDEA plugin.

The cleaner approach is to add `setCheckStyleVersion` to `Execute After Sync`, but for whatever  reason IntelliJ IDEA decided to make that a user specific setting only, so in order to add that for all users, we have to add some long XML manipulation code, like in [JDO enhancement](https://github.com/TEAMMATES/teammates/pull/7354/files#diff-c197962302397baf3a4cc36463dce5eaR420).

The other one requires lesser code, which is to manipulate the `checkstyle-idea.xml` at configuration phase for Gradle,  maybe something like

```Gradle
task configureProject {
    if (file('.idea/checkstyle-idea.xml').exists()) {
        String filePath = '.idea/checkstyle-idea.xml'
        Node xml = new XmlParser().parse(filePath)
        Node checkStyleComponent = (Node) (xml.component.find { it.@name == 'CheckStyle-IDEA' })
        Node checkStyleConfigurationMap = (Node) (checkStyleComponent.option.find { it.@name == 'configuration' })
        Node checkStyleVersionEntry = (Node) (checkStyleConfigurationMap.map.entry.find { it.@key == 'checkstyle-version' })

        checkStyleVersionEntry.@value = checkstyleVersion

        writeXml(xml, filePath)
    }
}
```
Can't seem to find a problem with the latter approach, but something feels wrong to me.

**Comment by whipermr5** [comment]
So it seems like syncing is possible. Either fully sync or don't sync at all. @wkurniawan07 seems to prefer the latter; is @LiHaoTan strongly opposed to it? I'm okay with either.

**Comment by LiHaoTan** [comment]
I somewhat prefer fully syncing, but then again I am not opposed to not syncing as well.

So I guess @wkurniawan07 will make the decision haha, though it would be nice to know why a choice is preferred.

**Comment by whipermr5** [comment]
I guess I'm slightly leaning towards syncing too haha.

**Comment by wkurniawan07** [comment]
If there is a way to sync, then it should be fine. But I still won't do it here. I don't have enough IntelliJ expertise to be held accountable for the syncing code should I add them here.

**Comment by whipermr5** [comment]
@wkurniawan07 You're right; @LiHaoTan can do it in a separate PR.

**Comment by wkurniawan07** [comment]
@whipermr5 can review, and also @LiHaoTan if you're also interested

**Pull request merged**
