### PR TITLE
Extract sort types for feedback session results into constants #5332

### LINKED ISSUE #5332: Extract sort types for feedback session results into constants
Sort types for feedback session results may be extracted into constants
- question
- recipient-giver-question
- giver-recipient-question
- recipient-question-giver
- giver-question-recipient

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #5332

### CODE REVIEW

**Comment by junhaoyap** [comment]
@belyabl9 good job 👍

**Comment by junhaoyap** [comment]
@damithc please take a look!

**Comment by YongJieYongJie** [comment]
maybe instead of
- `Const.FeedbackSessionResults.QUESTION_SORT_TYPE`,
- `Const.FeedbackSessionResults.GRQ_SORT_TYPE`, etc.

we can use something like
- `Const.FeedbackSessionResults.SortType.QUESTION`,
- `Const.FeedbackSessionResults.SortType.GRP_RECP_QNS`, etc

**Comment by damithc** [comment]
Along the lines of what @YongJieYongJie said, I prefer `SORT_TYPE_` to be prefix. Our convention is to put the category as the prefix so that same category appears together when ordered alphabetically.

**Comment by junhaoyap** [comment]
Didn't know about that convention! My bad :)

**Comment by damithc** [comment]
It's an 'unwritten' convention :-p

**Comment by belyabl9** [comment]
@damithc 
Ok, so, result constants will be like: "Const.FeedbackSessionResults.SORT_TYPE_QUESTION"

**Comment by damithc** [comment]
Yes that's right.

-- 
Sent from a mobile device.

**Comment by belyabl9** [comment]
Ready to review

**Comment by junhaoyap** [comment]
@belyabl9 looking good now :) @damithc @YongJieYongJie please take a look!

**Comment by wkurniawan07** [comment]
@belyabl9 can you sync with the current `master` branch and resolve the conflicts here so that I can merge this PR?

**Comment by belyabl9** [comment]
@wkurniawan07 , rebased

**Comment by wkurniawan07** [comment]
@belyabl9 noted, merging this now :+1:

**Pull request merged**
