### PR TITLE
[#9191] FeedbackResponsesLogicTest.java: Make use of `assertEquals` consistent

### LINKED ISSUE #9191: FeedbackResponsesLogicTest.java: Make use of `assertEquals` consistent
- **Environment**: `master` branch of commit 70cdecc8f578d9687b7254046441370d674228f7

**Expected behaviour**

In JUnit, the `assertEquals` statement takes in two parameters: expected and actual output. This means that the first argument should be the value that we hope to see versus the second argument which is what the program actually outputs.

**Actual behaviour**

However, in this test you can see instances like:

image

**Additional info**

It would be good to make the usage consistent, because the corresponding error message produced can be quite misleading. For example, if we are expecting to see `2` as an output, but the program produces `3` instead, the error message should tell us clearly so. However, since the `assertEquals` statement is written in a different format, you can get something like:

image

which can potentially mislead and confuse developers.

### PR DESCRIPTION
**Pull request by cbb692**
Fixes #9191 

As discussed in the above issue, some of the assertEquals calls in FeedbackResponsesLogicTest had their arguments switched (i.e. the expected value was last, when it should be first and vice-versa). These have been fixed by going through each test call and confirming their order.

### CODE REVIEW

**Comment by cbb692** [comment]
So I guess my attempt to fix #8814 caused some problems in my master branch when I broke off to fix this issue. I've done everything I can to remedy the problems, including reverting everything back to upstream/master then starting again but for some reason I can't remove the MapData file from my PR. If I need to close this and go about it in a different way to follow procedure, please let me know. 

Not trying to rock the boat, especially since I'm so new. Thanks.

**Comment by xpdavid** [comment]
@cbb692 Note that your PR should only solve one problem. You need to remove change in `userMapData.json`

**Comment by cbb692** [comment]
@xpdavid Should be good now. Sorry for the confusion and thanks for the help!

**Comment by cbb692** [comment]
Bumping, this should be good to go assuming everyone else is ok with it

**Comment by cbb692** [comment]
No biggie. Thanks for giving it a look over. As for the 'CB' thing, that's my bad. Just a habit I developed, but I'll keep them out of commits in the future.

**Comment by joanneong** [comment]
Sure. So can you update this branch?

**Comment by joanneong** [comment]
@wkurniawan07 Can I merge this after updating, or should I seek another review from Prof?

**Comment by wkurniawan07** [comment]
@joanneong can go ahead and merge, I have given the `s.ToMerge` label.

**Pull request merged**
