### PR TITLE
[#12081] User-friendliness: Fix feedback path dropdown

### PR DESCRIPTION
**Pull request by weiquu**
Part of #12081 
Sub-issue: [Fix feedback path dropdown](https://github.com/TEAMMATES/teammates/projects/16#card-88348663)

**Outline of Solution**
Changed second dropdown to be below instead of to the side. Keeps track of which submenus are open via a map. Also added buttons for accessibility and added the `text-wrap` class to resolve overflow issues.

For E2E tests, changed the options to click on the button.

### CODE REVIEW

**Comment by weiquu** [comment]
I didn't put `aria-label`s on the feedback path dropdown options since the screen reader already picks up the text inside each button. I did, however, put one on the overall feedback path dropdown button. The issue is that the `aria-label` is currently set to just "Feedback Path Dropdown", and does not indicate what feedback path is currently selected.

Given this situation, should I remove the `aria-label` so that the screen reader just mentions what is selected + that it is a button, or should I edit the `aria-label` to also take into account the currently selected path?

**Comment by zhaojj2209** [comment]
> Given this situation, should I remove the `aria-label` so that the screen reader just mentions what is selected + that it is a button, or should I edit the `aria-label` to also take into account the currently selected path?

I think in this case it would be alright to remove the aria label.

Also, do fix the E2E tests, this PR seems to have broken a few.

**Comment by samuelfangjw** [comment]
Snyk is currently down which explains the failing test.

**Comment by weiquu** [comment]
> I think in this case it would be alright to remove the aria label.
> 
> Also, do fix the E2E tests, this PR seems to have broken a few.

Thanks, updated!

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
