### PR TITLE
[#9165] Added Docker support (#9165)

### LINKED ISSUE #9165: Add Docker Support
Add Docker Support to Teammates

- **Environment**:  `master` branch at commit ad120e6

**Description of feature/enhancement**
Containerizing Teammates with Docker allows anyone to start a local server without setting up a dev environment

**Justification**
Makes it much more likely for prospect users to try out Teammates locally

**Existing similar features and their shortcomings**
Server can be set up by following the documentation, but that takes several installations and configuration steps

### PR DESCRIPTION
**Pull request by acheaito**
Fixes #9165 

**Outline of Solution**
Dockerized Teammates server. Note that build.gradle had to be updated with the "host" attribute. This is set to "localhost", which is the default. However, when started with Docker, the bootstrap script will swap localhost out for the container hostname. This allows app engine to bind to the proper host and expose the app on the Docker host.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Hi @acheaito, thanks for the PR! Indeed this is something that will be very helpful to us. However we will need some time to thoroughly review and test the Docker routine, so we'll appreciate if you can give us a few days to review before we can get back to you!

**Comment by acheaito** [comment]
@wkurniawan07 Absolutely. Please let me know if there are any questions in regards to the changes.

**Comment by wkurniawan07** [comment]
Hi @acheaito, thanks again for taking the initiative! I have tried the Docker routine and it works, albeit some minor improvements are needed.

However, after discussion with the team, we have decided not to move forward with this in the near future because we do not see that much benefit in introducing Docker support at this point of time. Allow me to explain:
1. We do not sell an on-premise solution (or even "sell" any solution, for that matter), thus there is little motivation for "prospect users to try out TEAMMATES locally". In fact, our target user is not even developers. A prospective user can instead request for a free account in the actual product (<https://teammatesv4.appspot.com>) to try it out.
1. The infrastructure we run on is Google App Engine standard environment, which is not managed by orchestrating Docker containers.
1. Docker is not superior to (or even inferior to) a fully set up dev environment for development purpose, and additionally comes with a steep learning curve. Given that the project is managed by mainly students (although I am no longer one) and our target contributor is also mainly students, it gives little motivation for any prospective contributor to use the Docker method.

Of course, any one of those reasons can change in the future, and thus we will keep your PR for reference. If anyone reading this wants to actually try out running TEAMMATES locally with Docker, you can have assurance that this PR has done what is necessary.

If we ever add Docker support in the future, we will be sure to give you proper credit.

**Comment by wkurniawan07** [comment]
@acheaito, we will be merging this to a separate branch instead. Thanks again for your contribution!

**Pull request merged**
