### PR TITLE
User map: move 'last updated date' to userMapData.json #6317

### LINKED ISSUE #6317: User map: move 'last updated date' to userMapData.json
Currently the last updated date of the user map is in `src/main/webapp/usermap.jsp` while the user data is actually updated in `src/main/webapp/js/userMapData.json`.

Explore the possibility of moving the date into the json file so that only one file needs to be updated.

### PR DESCRIPTION
**Pull request by AnaghHegde**
Fixes #6317

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@damithc i don't understand why tests are failing even though i did code format in eclipse.Can you please help me.

**Comment by wkurniawan07** [comment]
@AnaghHegde, do consult the Travis CI build log. The failure is caused by multitude of coding style violations, the most dominant of which is you are using tabs instead of spaces for indentation. You have to fix them before the CI will proceed to testing.
Also, your `master` branch is unclean. This causes unnecessary commits to be introduced in this PR (and any subsequent PR if you branch from this unclean `master`). You have to do [this](http://stackoverflow.com/questions/19864934/git-your-branch-and-origin-master-have-diverged-how-to-throw-away-local-com) to clean it up.

**Comment by AnaghHegde** [comment]
@wkurniawan07 I did what they have said here 7th point  **Source → Format** (https://github.com/TEAMMATES/teammates/blob/master/docs/process.md). So why its still failing and i am not using tabs (in the sense tabs are removed in the developer env set up time only  in the 2nd step ).

**Comment by chowyb** [comment]
@AnaghHegde when changing the settings for indentation, you will need to hit "Apply" after every change (eg. after changing the settings for Java, hit "Apply", then change the settings for JavaScript, hit "Apply" again etc.)

**Comment by AnaghHegde** [comment]
@wkurniawan07 why the build is taking such a long time?. I committed the change almost 4 hours back, but its still pending. What is appVeyor ?Why can't i see the build logs ?.

**Comment by damithc** [comment]
Seeing how your branch contains lot of unrelated commits, looks like the master branch of your fork is messed up, probably due to not syncing properly with upstream repo. Try resetting the fork and doing everything from scratch. 

> What is appVeyor ?

Google is your friend.

**Comment by AnaghHegde** [comment]
@damithc So is it ok if i delete the fork in my repo and start from the scratch?

**Comment by damithc** [comment]
@AnaghHegde 

> So is it ok if i delete the fork in my repo and start from the scratch?

Yes that's one of the simpler approaches.


> The link to airbnb JavaScript Style Guide in the docs is not correct.

Thanks for the catch. Can you post an issue for it. In the same issue, you can suggest where that page went, if you can find its new location online.

**Comment by wkurniawan07** [comment]
> why the build is taking such a long time?. I committed the change almost 4 hours back, but its still pending. ~~What is appVeyor ?~~ Why can't i see it's build logs ?

@AnaghHegde, I presume you have not encountered Git merge conflicts before. Do find articles about it online to learn what it is about and how to resolve it. Travis CI (or any CI) cannot run builds that have merge conflicts, thus it is not "taking such a long time": it does not ever happen in the first place.

**Pull request closed without merging**
