### PR TITLE
Use `Strings.isNullOrEmpty` instead of rolling our own `StringHelper.isEmpty` #7765

### LINKED ISSUE #7765: Use `Strings.isNullOrEmpty` instead of rolling our own `StringHelper.isEmpty`
~We should use Guava's `Strings.isNullOrEmpty` instead of creating our own `StringHelper.isEmpty`.~

~While the implementation is simple and unlikely to cause any problems, the overhead incurred in writing the tests was wasted. Furthermore, `isNullOrEmpty` is a better name than `isEmpty`.~

~EDIT:
As an example, in `StudentProfileAttributes#generateUpdateMessageForStudent`:~

~Change `StringHelper.isEmpty(shortName)` to `Strings.isNullOrEmpty(shortName)`~

---
This issue is currently being re-considered and will be updated when a conclusion has been reached.

The discussion of the issue begins here: https://github.com/TEAMMATES/teammates/pull/8013#issuecomment-326744059

Some possible reasons why this issue is to be rendered invalid so a related new issue is to be created:
https://github.com/TEAMMATES/teammates/pull/8013#issuecomment-335065025

### PR DESCRIPTION
**Pull request by eei34**
Fixes #7765 

**Outline of Solution**

Replaced StringHelper.isEmpty with Guava's Strings.IsNullorEmpty.

### CODE REVIEW

**Comment by sujeet14108** [comment]
@eei34 As per [contributing guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-1-pick-an-issue-to-fix) PR tittle should be same as issue name 
i.e `Use Strings.isNullOrEmpty instead of rolling our own StringHelper.isEmpty #7765
`

**Comment by eei34** [comment]
@sujeet14108 This is ready for review.

**Comment by whipermr5** [comment]
#8013 is more complete as it removes the method and corresponding test. @eei34 would you like to try another issue?

**Comment by whipermr5** [comment]
Closing in favour of #8013, where the issue is still being discussed.

**Pull request closed without merging**
