### PR TITLE
[#12517] Instructors creating sessions: response visible time should be 'not now' by default

### LINKED ISSUE #12517: Instructors creating sessions: response visible time should be 'not now' by default
When an instructors is creating a new session, 

Current:

image

The default `Make response visible` time is empty.

Expected:

Should be set to `Not now`.

Otherwise, there will be an error message upon saving.

Seems like a regression caused by V8.28

### PR DESCRIPTION
**Pull request by Zxun2**
Fixes #12517 

**Outline of Solution**

Overwrite default attributes inherited from base class.

### CODE REVIEW

**Review by domlimm — APPROVED** [review]
LGTM! Thanks for the hotfix ZX!

**Review by weiquu — APPROVED** [review]
LGTM!

**Comment by samuelfangjw** [comment]
Thanks @Zxun2, @domlimm, @weiquu for the quick fix!

**Comment by damithc** [comment]
> Thanks @Zxun2, @domlimm, @weiquu for the quick fix!

Yup 💯

**Pull request merged**
