### PR TITLE
Change the variable names in InstructorCourseDetailsPageUiTest #4643

### LINKED ISSUE #4643: Change the variable names in InstructorCourseDetailsPageUiTest
Currently it might not be that obvious that Alice is student one and Charlie is student two.
Also, consider making the variables global as they are used in multiple test segments.

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #4643

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
### Renaming
All references to `student1` etc. is renamed to `alice`, except when loading from test properties.
I decided against writing a comment because I thought that was sufficiently clear that `student1` is loaded into `alice` etc.

### Moving variable initialization location
As mentioned in the issue, I tried moving `StudentAttributes` that are used in multiple tests to global (i.e. class) scope.
However, I reversed that change because I found that the trade-off is not worth it: the reduction of duplication results in too much pollution of the class scope.
In the end, I moved the `StudentAttributes` and `courseId` to the start of each test method, so it is immediately clear what is tested.

**Comment by thyageshm** [comment]
@JosephineKwa ready for your review

**Comment by JosephineKwa** [comment]
Looks good to merge!

**Comment by damithc** [comment]
@wkurniawan07 have a look as you are the one who created this issue.

**Comment by damithc** [comment]
@wkurniawan07 reminder

**Comment by wkurniawan07** [comment]
Actually I was thinking the other way round, i.e `alice*` -> `student1*`, `charlie*` -> `student2*`, ... when I created the issue. `benny` and `danny` are fine because they are not tied to any of the test properties.

**Comment by YongJieYongJie** [comment]
@wkurniawan07
I just changed Alice to student1 and Charlie to student2.
(I originally did it the other way around to preserve the A B C D pattern.)

**Comment by wkurniawan07** [comment]
It's fine to keep them as Alice and Charlie in the JSON file, as long as the Java file makes it clear enough at the beginning (during account injection) that Alice is student1 etc.

**Comment by YongJieYongJie** [comment]
@wkurniawan07
I just changed Alice to student1 and Charlie to student2 (without changing the JSON data).

I originally did it the other way around to preserve the A B C D pattern. But I think it makes sense for the student1 and student2 to be different because, as you mentioned, they rely on test properties.

**Comment by wkurniawan07** [comment]
Good job, this is exactly what I'm looking for :+1:
@damithc ready for your review.

**Comment by thyageshm** [comment]
@JosephineKwa please merge this pr soon

**Pull request merged**
