### PR TITLE
[#9832] Inconsistent labelling of recycle bin 

### LINKED ISSUE #9832: Inconsistent labelling of recycle bin
- **Environment**: 
`master` branch at commit 4fb70a93119b887e4c6ccb7a70894994060d309c

See below:

**Instructor courses page**
image

**Instructor sessions page**
image

### PR DESCRIPTION
**Pull request by Vaironl**
Fixes #9832 

**Outline of Solution**
Made deleted sessions title consistent with deleted courses.

On my local dev server npm run lint seems to be throwing a warning stating: 
> File: C:\Users\Vairon\Documents\Programming\TEAMMATES\src\main\webapp\ngsw.json
Line: 328 Expected a newline at the end of the file. [warning]

I believe this most likely is due to improper setup on my part and should not affect the project. However, if someone more experienced minds pointing me in the right direction I would be glad to correct the issue.

### CODE REVIEW

**Comment by xpdavid** [comment]
Hi @Vaironl , it is known that `npm run lint` will fail after running `npm build`

**Comment by Vaironl** [comment]
@xpdavid thank you for letting me know about this issue. What is the general recommendation to fix this issue? Also, what are the next steps I should take considering I did not pass the Chrome E2E?

Thanks!

**Comment by xpdavid** [comment]
It's not your fault. #9847 will fix the build.

**Comment by Vaironl** [comment]
Sounds great, will grab another issue to work on

**Pull request merged**
