### PR TITLE
instructorViewStudentRecord: format 'no comments' differently #2772

### LINKED ISSUE #2772: instructorViewStudentRecord: format 'no comments' differently
Currently, the 'You don't have any comments on this student.' phrase is formatted in the same way we show comments. That could be confusing. Let's format it differently.

### PR DESCRIPTION
**Pull request by jkt001**
Fixes #2772 

Previously it was like this:
screen shot 2016-01-31 at 16 59 20

This is the updated one:
screen shot 2016-01-31 at 16 59 06

If this is OK, I shall change the tests to reflect the change.

### CODE REVIEW

**Comment by JosephineKwa** [comment]
@jkt001 it would be good to italicise the greyed-out text as well, to differentiate it further :)

**Comment by jkt001** [comment]
@JosephineKwa I have added the italics style using the \<em\> tag.

I don't know if this is preferred, though. To add the italic effect, I can either:

<ol>
<li>use the current method
<li>add an italic class to teammatesCommon.css since it is not there yet </li>
<li>use the italic class styling from teammates.css (it is defined there, if I'm not wrong) </li>
</ol>

Let me know which one is ok, if the current one is not preferable.

If it is already OK, I shall modify the test cases.

**Comment by thyageshm** [comment]
@JosephineKwa could we try and complete this by this release?

**Comment by JosephineKwa** [comment]
@jkt001 sorry for the delay, I think it might be better to use `<i>` in this case in order to maintain consistency in the code. Do proceed with changing the html files after you have made the amendment :)

**Comment by jkt001** [comment]
@JosephineKwa I have changed it to \<i\> and changed the tests as well. For your review, please.

**Comment by JosephineKwa** [comment]
Good to merge :+1: , @damithc pending your approval

**Pull request merged**
