### PR TITLE
Removed development log

### LINKED ISSUE #5595: Remove erroneously committed development log message
in `FeedbackResponsesLogic.java`, the `log.warning(feedbackQuestionId);` seems to be used for development purposes and then accidentally committed.

Full context:
~~~
    public FeedbackResponseAttributes getFeedbackResponse(
            String feedbackQuestionId, String giverEmail, String recipient) {
        // TODO: check what is this line doing here!!!
==>     log.warning(feedbackQuestionId);
        return frDb.getFeedbackResponse(feedbackQuestionId, giverEmail, recipient);
    }
~~~

The actual commit involved fixing test:
~~~
commit a5d1de4557c623de2034d6adbf4841e84823c817
Author: imouto1994 <imouto1994@gmail.com>
Date:   Thu Jun 12 17:12:46 2014 +0800

    Fix test cases
~~~

### PR DESCRIPTION
**Pull request by angiejones**
Fixes #5595

### CODE REVIEW

**Comment by junhaoyap** [comment]
Looks good - @damithc please confirm :)

**Comment by chowyb** [comment]
@junhaoyap branch name and PR title seem to be off though, normally we'd reject a PR like this since we can't change the branch name here.

@wkurniawan07 any thoughts?

**Comment by junhaoyap** [comment]
That is true @chowyb - PR title can be easily changed, I'm not sure if branch name is that big of a concern anymore considering our merge squash can change the commit message, @wkurniawan07 refer this to you for your consideration

**Comment by damithc** [comment]
Yup, we'll have to reject this PR.

**Comment by junhaoyap** [comment]
@damithc got it, @angiejones the fix is good, however we have to reject this PR because it doesn't conform to our contribution guidelines, please refer to our contributions guidelines and open a new PR with the right branching and PR naming and I'll be glad to look at it again

**Pull request closed without merging**
