### PR TITLE
[#8779] AccountAttributes: remove HTML sanitization before saving for googleId

### LINKED ISSUE #8779: AccountAttributes: Remove HTML sanitization before saving for googleId, name, institute
As per #8774, sanitization of Google ID will be performed during rendering if required.

Currently, a valid Google ID containing `<>"/'&` (possible for a Google account with a non-Gmail email) would become an invalid Google ID after sanitization, leading to failure when trying to persist an account with such a Google ID.

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #8779 

Removed googleId sanitization before saving from AccountAttributes.java and made corresponding change

### CODE REVIEW

**Comment by whipermr5** [comment]
Is that tag file really the only place the Google ID is displayed in HTML (just checking)?

**Comment by shaharyar-shamshi** [comment]
No @whipermr5 sir there may be also i have just made an initial Change

**Comment by shaharyar-shamshi** [comment]
@whipermr5 sir I have made a changes kindly review it .

**Comment by shaharyar-shamshi** [comment]
@whipermr5 sir have a look

**Comment by shaharyar-shamshi** [comment]
@whipermr5 sir have a look

**Comment by shaharyar-shamshi** [comment]
@whipermr5 Kindly have a look

**Comment by xpdavid** [comment]
@shaharyar-shamshi Sorry for the delay of review.

Are you still interested in doing this PR? I'll assign someone to review if you wish to continue doing it.

**Comment by shaharyar-shamshi** [comment]
@xpdavid yes I am interested in it

**Comment by xpdavid** [comment]
Close due to V7 migration and #9368

**Pull request closed without merging**
