### PR TITLE
[#12530] Allow header dropdown to be opened with enter key

### LINKED ISSUE #12530: Header: unable to expand dropdown with keyboard commands
I'm able to tab over the dropdown buttons in the header, but pressing spacebar or enter/return doesn't expand the dropdown. This issue is present both for the "Help" dropdown as well as the user email dropdown (on the far right).

Other dropdowns are able to be expanded with either the spacebar or enter/return or both.

### LINKED ISSUE #12531: Header: "Log Out" button cannot be tabbed over
In the header, I'm able to tab over all buttons except the "Log Out" button. After pressing tab, the button is skipped over and the browser focuses on the next button:

https://github.com/TEAMMATES/teammates/assets/48304907/b3636b74-7554-481e-977e-121ea830aaa2

### PR DESCRIPTION
**Pull request by domoberzin**
Fixes #12530

**Outline of Solution**
The current dropdown toggle on the header is created using `<a>` tags, so currently, the dropdown can actually be toggled  using the arrow down key. 

This PR changes those `<a>` tags to use `<button>`tags also with added classes to reduce any change in the visual appearance. This change will now allow the dropdown to be toggled with the Enter key instead of the arrow key.

This PR also allows tabbing to the Log Out button and fixes #12531 by adding `tabindex=0` to the element

### CODE REVIEW

**Review by weiquu — APPROVED** [review]
LGTM!

**Review by jasonqiu212 — COMMENTED** [review]
Thanks for the changes! Just one small nit pick - The buttons seem to flash blue when clicking on it, which I think is different from the original behavior. Is it possible to disable this behavior as well?

https://github.com/TEAMMATES/teammates/assets/25262042/1c1af857-f479-469b-bb10-018881a3257a

**Comment by domoberzin** [comment]
> Thanks for the changes! Just one small nit pick - The buttons seem to flash blue when clicking on it, which I think is different from the original behavior. Is it possible to disable this behavior as well?
> 
>  Screen.Recording.2023-08-02.at.8.00.03.PM.mov

@jasonqiu212 Updated with the behaviour in the video below, which i believe should be similar to the original behaviour, do let me know if any other changes are needed

https://github.com/TEAMMATES/teammates/assets/74132255/40565d8b-8806-4997-ae1b-71fade6c8f50

**Review by jasonqiu212 — APPROVED** [review]
LGTM!

**Pull request merged**
