### PR TITLE
build.gradle:  Upgrade to latest Selenium 3.8.1 #8150

### LINKED ISSUE #8150: Upgrade Selenium to 3.x
With Java 8 not being a blocking issue anymore, we are ready to migrate to Selenium 3.

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8150 

**Outline of Solution**

Upgraded Selenium version from 2.53.1 -> 3.8.1

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@tshradheya I will caution you that this is not an easy task even for maintainers. If you're up for the challenge, go ahead.

**Comment by tshradheya** [comment]
@wkurniawan07 Thanks for the heads up. I will try my best to see if I am able to do it.

If I see myself going no where with it, I will close this PR

**Comment by tshradheya** [comment]
@wkurniawan07 I updated travis to run tests with latest Firefox version and Geckodriver. 

Travis now fails around 43 tests all of which are browser tests. Is this the reason why you were telling its not an easy task? Any idea on what could be the reasons these tests are failing?

**Comment by wkurniawan07** [comment]
> Any idea on what could be the reasons these tests are failing?

That's your duty to find out.

**Comment by damithc** [comment]
> Travis now fails around 43 tests all of which are browser tests.

Do all tests pass locally? First get them to pass locally.

**Comment by tshradheya** [comment]
I have realized that this isnt an easy task and it involves fixing a lot of tests.
I am going to close this PR as I am not ver familiar with Testing and will resume my work later when it I have a much better knowledge of it.

**Pull request closed without merging**
