### PR TITLE
Add missing encoding page directive to several JSP files #7396

### LINKED ISSUE #7396: Add missing encoding page directive to several JSP files
Add this line -

``` jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
```

to all `.jsp` files in `src/main/webapp/partials` folder.

EDIT: Also to `invalidOrigin.jsp`

### PR DESCRIPTION
**Pull request by VamsiSangam**
Fixes #7396 

Screenshot -

capture

### CODE REVIEW

**Comment by VamsiSangam** [comment]
Ready for review.

**Comment by whipermr5** [comment]
Looks good! Could you do a quick search to check if there are any remaining `jsp` files in the project without the directive?

**Comment by VamsiSangam** [comment]
Checked all the `.jsp` files manually. Just one file `src/main/webapp/invalidOrigin.jsp` was missing the directive. Added it.

**Comment by whipermr5** [comment]
Good job! Oops that was my mistake again; I authored that file 😅

**Comment by damithc** [comment]
On a related note, is there any way to prevent this kind of omission happening again?

**Comment by VamsiSangam** [comment]
We must check if all `.jsp` files begin with this line -

``` jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
```

Although I don't know how to accomplish that :sweat_smile:

**Comment by whipermr5** [comment]
@damithc I'll look into implementing a test.

**Comment by wkurniawan07** [comment]
If we ever go down this way: PMD has some support for JSP linting, one of which is enforcing the UTF-8 encoding.

**Comment by whipermr5** [comment]
I might have found a way to restore the default jsp encoding directive removed from `web.xml` in #7221 while still avoiding issue #6889 - remove the `welcome-file-list` directive instead. I found out we don't even use it.

**Pull request merged**
