### PR TITLE
[#10705] [#10718] Improve user flow for unregistered student and invalid registration key

### LINKED ISSUE #10705: Invalid links redirecting the user to the Google login page
Current: In some cases, when the link used by a student is no longer valid, the user is redirected to the Google login page. 
Example: When the student is no longer in the course
Expected: show error message

### LINKED ISSUE #10718: Tweak flow when a student clicks a submission link while logged into a Google account
Situation: A student clicks on a submission link while logged into a Google account. The Google account is not linked to the TEAMMATES account.

Current: shows not-authorized message

Suggested (also V6):
* Ask student if she would like to use the current logged-in Google account to join TEAMMATES
  * If user agrees, 'join' the student into the course using the Google account and go to the submission page. The dialog should inform the user that joining is optional and what happens if she choose not to.
  * If user chooses not to, logout from the Google account and go the submission page

Marking as priority medium because this is generating user support requests
The dialog text can be copied over from V6. IIRC, it had some detailed instructions to the user.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #10705 
Fixes #10718 

Dealing with two issues at once since both deal with regkey check.

The root cause for both is the check for regkey's validity only stops at whether the regkey was usable by the current user or not. It did not specify further the different kinds of validity there can be, e.g. valid because the logged in user match, valid because it has not been used, etc.

### CODE REVIEW

**Review by xpdavid — APPROVED** [review]

**Comment by damithc** [comment]
@t-cheepeng can review this? I would like to deploy this soon.

**Comment by wkurniawan07** [comment]
@damithc if you want to deploy soon, I should move this to `release` branch. We have been doing hot-fixing from `master` branch for the entirety of `7.0.x` which is not the right practice.

**Comment by damithc** [comment]
> @damithc if you want to deploy soon, I should move this to `release` branch. We have been doing hot-fixing from `master` branch for the entirety of `7.0.x` which is not the right practice.

Sure.
Note that there is no real difference at the moment though i.e., there are no additional checks that happens in the release branch e.g., no additional manual testing before a release

**Comment by wkurniawan07** [comment]
> Note that there is no real difference at the moment though i.e., there are no additional checks that happens in the release branch e.g., no additional manual testing before a release

There were never additional checks on release branch. Manual testing, if it refers to the UI tests that have been decommissioned, happens regardless of hotfix or normal release, so none of the above holds. The entire reason for hotfixing (or not) is to keep the scope of release clean.

**Comment by damithc** [comment]
> There were never additional checks on release branch.

There used to be. I used to run E2E tests against the live server before a release. That means a hot fix is a change that builds on a version that has been proven to work on the live server. If the hot fix is minor and urgent, can be deployed without a live test.
But I have not run a live test for the recent releases. Relying on normal CI tests instead (plus a quick manual smoke test on the deployed version before I direct traffic to it). I assume if the code passes CI, it works on live server as well. Not a 100% safe assumption though.

**Review by t-cheepeng — APPROVED** [review]

**Pull request merged**
