### PR TITLE
[#11426] Index instructor who created course for searching

### LINKED ISSUE #11426: Instructor who created course is not searchable
- **Environment**: live server at V8.1.1, but issue existed since V8.0.0

**Steps to reproduce**

1. As an existing instructor, create a new course
1. As the admin, search for the newly created instructor in the newly created course

**Expected behaviour**

The instructor is searchable.

**Actual behaviour**

The instructor is not searchable.

**Additional info**

Cause: the newly created instructor is not indexed. Minor regression introduced by #11315.

### PR DESCRIPTION
**Pull request by jianhandev**
Fixes #11426 

**Before**

https://user-images.githubusercontent.com/59337195/134032166-894a5e0e-08b4-4677-8f7f-68bd391a18a1.mov

**After**

https://user-images.githubusercontent.com/59337195/134032471-2ea883d8-0f69-4075-ba31-4c22b9c41750.mov

### CODE REVIEW

**Review by wkurniawan07 — APPROVED** [review]
Quick and clean solution 💯

**Comment by damithc** [comment]
Thanks for the quick fix @jianhandev 
We need a script to recreate the search index entries missed due to this bug too, right?

**Comment by damithc** [comment]
> Thanks for the quick fix @jianhandev
> We need a script to recreate the search index entries missed due to this bug too, right?

@wkurniawan07 perhaps I can reuse the initial search data migration script for this? I suppose it has been removed from the code base but I can can dig it up from the history.

**Comment by jianhandev** [comment]
> Thanks for the quick fix @jianhandev We need a script to recreate the search index entries missed due to this bug too, right?

Sorry completely missed out on this. I think we can use the `PopulateCourseSearchDocuments` and modify the `createdAtUpperBound` and `createdAtLowerBound`. Just checked the repo the script is still inside the scripts folder.

**Comment by damithc** [comment]
> Sorry completely missed out on this. I think we can use the `PopulateCourseSearchDocuments` script and modify the `createdAtUpperBound` and `createdAtLowerBound`. Just checked the repo the script is still inside the scripts folder.

Will do so. Thanks @jianhandev

**Pull request merged**
