### PR TITLE
[#12307] Modified session timing modal does not use updated session name

### LINKED ISSUE #12307: Modified session timing modal does not use updated session name
- **Environment**: V8.25.0

**Steps to reproduce**

Copy a feedback session and rename it. In this case, "Project Presentation Week 10" has been renamed to "Project Presentation Week 11". Ensure the opening date of the session is sometime in the past (> 2hrs).

Screenshot 2023-03-30 at 8 28 04 PM

**Expected behaviour**

Session name is the updated session name.

**Actual behaviour**

Screenshot 2023-03-30 at 8 22 18 PM

Session name is the old session name. This makes it seem as if the older session was modified and not the newer one.

### PR DESCRIPTION
**Pull request by meet0806**
Fixes #12307 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by meet0806** [comment]
Hey @samuelfangjw @domlimm Please Review the changes

**Comment by zhaojj2209** [comment]
@meet0806 TEAMMATES maintainers are mostly student volunteers who also have other commitments both within and outside of this project. It has not even been 24 hours since this PR was last opened, please be patient and allow us time to review your PR.

**Review by cedricongjh — APPROVED** [review]
lgtm! When copying the session, the modal now displays the new session name, thank you for the work

**Comment by meet0806** [comment]
> lgtm! When copying the session, the modal now displays the new session name, thank you for the work

Thank you @cedricongjh for reviewing changes.

**Review by samuelfangjw — APPROVED** [review]

**Pull request merged**
