### PR TITLE
Instructor: Courses Page: Recycle Bin feature for courses #9002

### LINKED ISSUE #8852: Instructor: recycle bin feature: allow restore and delete courses in recovery page
**Environment:**
`recycling-bin` branch

**Description of feature/enhancement:**
- Create an instructor recovery page for instructors
- Display all deleted courses on this page
- Allow users to restore selected/all courses from Recycle Bin
- Allow users to delete selected/all courses permanently from Recycle Bin

**Justification:**
Users might deleted a course accidentally (even with the protection of the JavaScript confirmation prompt). This will give users a chance to restore deleted courses instead of directly deleted from database.

### LINKED ISSUE #8927: Instructor: recycle bin feature: add instructions for managing deleted courses in instructor help page
**Environment:**
`recycling-bin` branch

### LINKED ISSUE #8952: Instructor: recycle bin feature: add tests for deleting & restoring of courses
**Environment:**
`recycling-bin` branch

### LINKED ISSUE #8971: InstructorHomePageUiTest & InstructorCoursesPageUiTest failing on 'recycling-bin' branch
**Environment**
`recycling-bin` branch

### LINKED ISSUE #9002: Instructor: Courses Page: Recycle Bin feature for courses
**Environment:**
`master` branch at commit https://github.com/TEAMMATES/teammates/commit/4ed2bed6b6cedf8a17a7a16222355cd6e20e0f17

### PR DESCRIPTION
**Pull request by dalessr**
Fixes #9002 
Fixes #8852 
Fixes #8927 
Fixes #8952 
Fixes #8971 

**Content:**
- Allow instructors to restore/permanently delete single/all courses in Recycle Bin panel of the 'Courses' page
- Add instructions for managing deleted courses in `InstructorHelpPage`
- Add tests for deleting & restoring of courses in Recycle Bin

### CODE REVIEW

**Comment by dalessr** [comment]
@darrenwee @joanneong Ready for review :)

**Comment by joanneong** [comment]
@wkurniawan07 This is also my first time merging a long-lived branch to master. Just to check, is everything here fine? It seems fine to me other than needing a branch update...

**Comment by darrenwee** [comment]
This looks roughly correct 😄 @dalessr Just perform a `git rebase upstream/master` while on `recycling-bin-epic` to update the branch and we should be good. Do you want to wait for the remaining PRs to be approved first before merging this branch?

**Comment by wkurniawan07** [comment]
@dalessr to provide a background, long-lived branches are not usually squashed-and-merged, but rebased-and-merged instead. The commit 9f14116 should be squashed to one of the proper commits (possibly f815c76). If I may suggest, 83a1d14 and ad64346 as well because they are not really meaningful when viewing the full history of the commits.

**Comment by dalessr** [comment]
@wkurniawan07 Okay done. Is it suitable now?

**Comment by damithc** [comment]
Generally OK. I'm not so keen on using a magic term 'Recovery' in method/variable names because it is not self-explanatory. It's not even a noun. Let's try to minimize the terms too.

How about this set of terms?
`Bin`: recycle bin
`SoftDelete`:  normal delete
`HardDelete`: delete from the bin
`SoftDeleted`: in the bin
`Restore`, `RestoreAll`: as the name suggests

**Comment by damithc** [comment]
> @damithc Currently this PR cannot support massive changes like this according to @wkurniawan07 's comments. Changing the terms here may also cause a lot of conflicts with the other PRs. Do you mind if I create a new PR for this later?

Yes, a separate PR is fine.

**Comment by wkurniawan07** [comment]
@dalessr Can you rebase this on top of the latest `master`? I will merge it afterwards.

**Comment by dalessr** [comment]
@wkurniawan07 Done :)

**Comment by wkurniawan07** [comment]
@dalessr can squash 2cbea50? Otherwise it should be ok.

**Comment by dalessr** [comment]
@wkurniawan07 Ready to merge

**Pull request merged**
