### PR TITLE
 [#12909] :Dev docs (E2E testing):  update Chromedriver link 

### LINKED ISSUE #12909: Dev docs (E2E testing): Chromedriver link broken
Link to Chromedriver download broken in e2e testing dev docs

- **Environment**: https://teammates.github.io/teammates/e2e-testing.html#using-chrome

Link to chromedriver download in the docs is `https://sites.google.com/a/chromium.org/chromedriver/downloads`, which leads to a "not found" page:
image

Link should be `https://chromedriver.chromium.org/downloads`

### PR DESCRIPTION
**Pull request by nadasuhailAyesh12**
Fixes #12909 

**Outline of Solution**
update chromedriver download link to the correct page.

### CODE REVIEW

**Review by jayasting98 — APPROVED** [review]
Thanks!

**Comment by nadasuhailAyesh12** [comment]
> Thanks!

Thank you ,could you please merge it

**Comment by jayasting98** [comment]
> Thank you ,could you please merge it

@nadasuhailAyesh12 Typically, we do at least two rounds of reviews. However, since this is a simple change with minimal impact, if nobody else comments on this PR in a few days, I can consider merging it without the second review.

**Review by NicolasCwy — APPROVED** [review]
LGTM! Thanks for helping us change this

**Pull request merged**
