### PR TITLE
Fix typo in InstructorHomePage #7364

### LINKED ISSUE #7364: Fix typo in InstructorHomePage
"Enroll" is misspelled in `clickCourseErollLink` of InstructorHomePage.java.

### PR DESCRIPTION
**Pull request by umangborad123**
Fixes #7364

### CODE REVIEW

**Comment by chowyb** [comment]
@umangborad123 please note that you should only fix at most one `d.FirstTimers` issue. As such, you should choose if you want your work for this PR to be counted, or your work on #7350.

**Comment by umangborad123** [comment]
@chowyb I wanted to do #7350 but I am not able to solve that error. So, if you can help me with that, I can do #7350 otherwise you can merge #7364.

**Comment by chowyb** [comment]
@umangborad123 okay, I've already replied on your PR for #7350. If you wish, you may continue work on both, but note that if you do so I can only merge one of them (likely the first PR that gets approved).

**Comment by umangborad123** [comment]
@chowyb ok! Thanks! So now you can close my pull request for #7350.

**Pull request merged**
