### PR TITLE
Security vulnerability: target="_blank" #6367

### LINKED ISSUE #6366: Homepage links open to same new tab
Steps to reproduce: 
1) Click on any of the links under `Well Received by the Academic Community` section of the [homepage](https://teammatesv4.appspot.com/), which opens a new tab. 
2) Again, go back to the homepage and click on another link.

You will notice that the link opens to the same tab in step 1. The reason is that instead of `target="_blank"`, it is `target="blank"`.

### LINKED ISSUE #6367: Security vulnerability: target="_blank"
As [explain in depth here](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/), `target="_blank"` is a vulnerability if any of the external sites gets compromised. The fix is simple, attach `rel="noopener noreferrer"` to the `a` links.

### PR DESCRIPTION
**Pull request by li-kai**
Fixes #6366 and fixes #6367

**Changes in code**:
The HTML layouts are changed to add `rel="noopener noreferrer"`. Server's logic remains unchanged.

### CODE REVIEW

**Comment by li-kai** [comment]
@chowyb Done!

**Comment by damithc** [comment]
@li-kai perhaps update https://github.com/oss-generic/process/blob/master/codingStandards/CodingStandard-Html.md ?

**Comment by li-kai** [comment]
> @li-kai perhaps update https://github.com/oss-generic/process/blob/master/codingStandards/CodingStandard-Html.md ?

In this same PR? Or issue a new one?

**Comment by damithc** [comment]
> In this same PR? Or issue a new one?

Different PR (it's a different repo).

**Pull request merged**
