### PR TITLE
Remove orphaned comment in FeedbackQuestionEditForm.java #5921

### LINKED ISSUE #5921: Remove orphaned comment in FeedbackQuestionEditForm.java
the header comments before the method `getQuestionIndex()` is obsolete and can be removed

```
    /**
     * @see {@link #getQuestionIndexIfNonZero}
     */
```

### PR DESCRIPTION
**Pull request by hiresh**
Fixes #5921

### CODE REVIEW

**Comment by hiresh** [comment]
Base branch set to "master"

**Comment by wkurniawan07** [comment]
Hi @hiresh,
As per comment in #5951, we have a rule on the branch name of each PR. Although the convention is followed, it has to match the issue number and what the issue is about; reading the branch name `759-use-spreadsheet-for-enrollment` would give the impression that this PR is for issue #759 while it is in fact for issue #5921, so the branch name should be `5921-some-keywords` where `some-keywords` should be representative of what the issue is about.
Everything else looks good so once you open another PR from a correctly named branch it should be ready for merging :+1:

**Comment by hiresh** [comment]
@wkurniawan07  Got it ...I am on it

**Comment by hiresh** [comment]
@wkurniawan07 changes in branch name are done as they were instructed.

**Pull request closed without merging**
