### PR TITLE
[#11869] Student: Enhance UX when submitting response for a feedback question

### LINKED ISSUE #11869: Submitting responses: some users are not sure if the submission went through
v8.17

Context: After a user submits responses to a session, we show a success message (with an option to download a proof-of-submission) file. Despite this, based on user queries received, some are still not sure if their submission went through 'properly'. It seems their doubt is because the page stays in edit mode, exactly the same way it was before they clicked the submit button.

image

The reason we stay in the same page in edit mode is because it makes further edits to the submission easier. 

Is there anything we can tweak the UX to eliminate this doubt, without losing the ease of further edits? Ideas welcome.

### PR DESCRIPTION
**Pull request by domlimm**
Fixes #11869.

**Outline of Solution**
Introduced a new local variable, `isSaved`, in `question-submission-form.component`.

This variable acts as a state to provide users with a stronger indication upon saving their responses for a single feedback question, or saving responses for all the questions for that session.

If this variable has a value of `true`, the question's header will be green i.e.`bg-success`, and a check icon is displayed beside the question. Else, the question's header colour will be blue i.e. `bg-primary` and the check icon is hidden.

We will make use of each question's response (from the `model` object, mainly `model.recipientSubmissionForms`) and check the `responseId`'s length in each object of the array of responses, if it is more than 0, it means that previously, the user has saved his/her response for the particular question.

Also, when students click on Submit Response for a question, they will see this (the question's header)

image

### CODE REVIEW

**Comment by domlimm** [comment]
Sorry caught up with school, will work on this in the coming weeks!

**Comment by domlimm** [comment]
Hello, understand this has been idling for a long while. Will work on it after mid terms! 🙏🏻

**Comment by domlimm** [comment]
Will get to this soon.

**Comment by domlimm** [comment]
Hello, I was wondering if I could please get some help, been digging for quite awhile. I believe that the codes that have been written already will solve this issue. However, I'm not sure why it's affecting all the `question-submission-form.component` (HTML) or `tm-question-submission-form` (selector/component name) components.

Each of this component should be independently and individually used/processed. Meaning to say that the code change at this [line](https://github.com/TEAMMATES/teammates/blob/08ee500a6762e5302f5b286f12966aad8b6b0066/src/web/app/components/question-submission-form/question-submission-form.component.html#L3) should be independent for each render of the component.

For example, previously Q1 has some responses saved and not the rest of the questions. But the green header toggle is applied to every single component. We can see in the image that only Q1 has been previously filled but not Q2 onwards. The green header is oddly applied to all the other 'unsaved or untouched' questions.

image

I'm not sure if it's due to how each component is rendered by the parent component `session-submission-page.component` (HTML) or `tm-session-submission-page` (selector/component name).

In the meantime, will keep digging why! Thank you!

**Comment by domlimm** [comment]
Just an update to follow up with the latest comment. I have found a fix for the issue im facing! Ready to go for a PR review. Thank you in advance!

**Review by zhaojj2209 — CHANGES_REQUESTED** [review]
Code looks alright so far, but I believe this is only half of the solution. We should also ensure that `isSaved` is set back to `false` the moment any changes are made to the question's response, so as to indicate to the user the response needs to be saved again. The current implementation does not take this into account, which is not ideal as users may mistakenly believe that their response has been saved.

**Comment by domlimm** [comment]
Hello @zhaojj2209! Thanks for reviewing! Yes good point. Let me look into implementing that. Thank you!

**Comment by domlimm** [comment]
Hello @zhaojj2209! So sorry for the delays, had a busy week..

I have added the other half of the solution. Additionally, I realised that clicking on `Submit all Responses` wasn't taken into account and have added the checks for that too.

I have also updated the PR's description on how this solution is implemented for your reference please.

Thank you in advance for reviewing! 😬

**Comment by zhaojj2209** [comment]
Good catch on the `Submit all Responses` case!

The question header now changes from green back to blue whenever any changes are made, and changes back to green if the response is saved again. However, from my testing, this happens exactly once; any further changes will result in the header remaining green, unless the page is reloaded. Do help to investigate this further and make the necessary fixes!

**Comment by domlimm** [comment]
Thanks for reviewing again Jingjing! I will look into it!

**Comment by domlimm** [comment]
Hello @zhaojj2209! I have made the necessary changes for your review please. Thank you!

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

**Review by wkurniawan07 — APPROVED** [review]

**Pull request merged**
