### PR TITLE
Move logic.publicresource classes to ui.controller #6354

### LINKED ISSUE #6354: Move logic.publicresource classes to ui.controller
The said package contains just two classes (or to put it even more blatantly: _one_ abstract class and _one_ implementing class, essentially just _one_ class) extending `HttpServlet`.
This class does not connect to any core `*Logic` or even the API `Logic` so `teammates.logic.*` is the wrong place for it. As it is a Servlet class (i.e. next to most directly accessible by users), it should be placed in `ui.controller`.

### PR DESCRIPTION
**Pull request by hackosinn**
Fixes #6354

### CODE REVIEW

**Comment by hackosinn** [comment]
@wkurniawan07 - build failed because of timeout. how can i start the build again?

**Comment by samsontmr** [comment]
> build failed because of timeout. how can i start the build again?

You can run travis on your forked repo to check if it passes. If it fails there you can restart it

**Comment by damithc** [comment]
Pushing an empty commit might trick travis to restart the build.

**Comment by samsontmr** [comment]
Oh right. @hackosinn you could squash your commits and push. That would definitely make travis start a new build.

**Comment by junhaoyap** [comment]
Setting to ongoing until passing

**Comment by wkurniawan07** [comment]
@hackosinn, the issue is not as simple as moving the classes (even though the issue title suggests so).

**Comment by samsontmr** [comment]
@hackosinn are you still working on this? I've managed to fix the issue. I'll open a PR if you're not working on this anymore.

**Comment by hackosinn** [comment]
@samsontmr - my exams were going on.  i should have informed about it.apologies for that. yup i'm working on this.

**Comment by samsontmr** [comment]
@hackosinn did you manage to figure out what went wrong?

**Comment by hackosinn** [comment]
@samsontmr - last time build failed due to timeout. i'll run the build again.if this time it fails again then i'll close this PR.

**Comment by samsontmr** [comment]
New PR has been opened at #6407.

**Comment by chowyb** [comment]
Closing this PR due to presence of new PR, although there's no need to create a new PR if any changes need to be made.

**Pull request closed without merging**
