### PR TITLE
[#10986] Show loading message below response loading spinner

### LINKED ISSUE #10986: Show loading message below response loading spinner
From PR #10960 

**Description of feature/enhancement**

If a course has many students (or in general many responses per question), add extra loading text below the spinner to inform the user that the students are being loaded (after perhaps 5s).

image

**Justification**

From @damithc 
> Provided the load operation will not time out, perhaps simply show a message below the spinner cautioning the user that this particular question will take a long time to load?

This would give user more assurance that there is progress in the loading.

**Existing similar features and their shortcomings**

Experimented with using `forkJoin` in the frontend to fetch questions in parallel in #10960: the parallel calls create too much instantaneous load at the backend and causes new instances to be spun up. The cost here is not justified.

### PR DESCRIPTION
**Pull request by dastansultanov**
Fixes #10986 
Added a dynamic message below the spinner as a secondary-text that appears after 10 seconds stating: "Please wait, it is loading"
Screenshot from 2021-03-17 12-18-36

### CODE REVIEW

**Comment by t-cheepeng** [comment]
Not so sure about the message
@damithc Is the extra loading message okay? Maybe something more descriptive would be better?

**Comment by damithc** [comment]
> Not so sure about the message
> @damithc Is the extra loading message okay? Maybe something more descriptive would be better?

I have a prelim question. Is this merely a cosmetic thing or is there some front-end batching going on behind the scene? If there is no batching, the loading is going to fail if it doesn't complete within one minute, right?

**Comment by moziliar** [comment]
The context of this issue is that we want to inform the user that their browser didn't hang on a long loading session. Batching is going to be added for this in the PR. Do you think it should just be a progress circle ish thing instead of this message?

**Comment by damithc** [comment]
> The context of this issue is that we want to inform the user that their browser didn't hang on a long loading session. Batching is going to be added for this in the PR. Do you think it should just be a progress circle ish thing instead of this message?

If no batching, the benefit is marginal because the operation is going to fail in less than 60 seconds anyway. If the course is large, users will not think the page has hanged just because the spinner is going on for `< 60s` period. But yes, it can reduce the user anxiety a bit. But some type of progress bar is better because adding some extra static text is not much of a progress indicator. e.g., something like  `fetching data . . .` and keep adding a `.` after every 5 seconds? Would that require lot of code or cause unnecessary strain on the page?

**Comment by dastansultanov** [comment]
> > The context of this issue is that we want to inform the user that their browser didn't hang on a long loading session. Batching is going to be added for this in the PR. Do you think it should just be a progress circle ish thing instead of this message?
> 
> If no batching, the benefit is marginal because the operation is going to fail in less than 60 seconds anyway. If the course is large, users will not think the page has hanged just because the spinner is going on for `< 60s` period. But yes, it can reduce the user anxiety a bit. But some type of progress bar is better because adding some extra static text is not much of a progress indicator. e.g., something like `fetching data . . .` and keep adding a `.` after every 5 seconds? Would that require lot of code or cause unnecessary strain on the page?

The purpose of that message is to reduce the anxiety of users. I will try to change it to a progress bar as you suggested, which I think will not cause unnecessary strain on the page

**Comment by moziliar** [comment]
@dastansultanov let's put this on hold first maybe? Situation has changed where we are trying to break down the fetch by section, whereby a single question could potentially generate more api calls from one now. Thanks again for the work so far!

@damithc an oversight from me that this issue might have been obsolete as the requirement and need for a progress bar have arise in recent weeks. Do you think moving to progress bar after #11017 is done will be more beneficial?

**Comment by dastansultanov** [comment]
> @dastansultanov let's put this on hold first maybe? Situation has changed where we are trying to break down the fetch by section, whereby a single question could potentially generate more api calls from one now. Thanks again for the work so far!
> 
> @damithc an oversight from me that this issue might have been obsolete as the requirement and need for a progress bar have arise in recent weeks. Do you think moving to progress bar after #11017 is done will be more beneficial?
Sure! I will look at other issues on which I could work on.

**Comment by damithc** [comment]
> @damithc an oversight from me that this issue might have been obsolete as the requirement and need for a progress bar have arise in recent weeks. Do you think moving to progress bar after #11017 is done will be more beneficial? Or this change still holds some value in some cases?

Sure, can wait till #11017 is done.

**Comment by madanalogy** [comment]
@dastansultanov due to a lack of progress on #11017 we have decided to put that PR on hold instead and you're welcome to continue working on this PR if you're still inclined to do so. Apologies for the long delay.

You'll need to update your branch and fix the failing component tests. Ideally we'd like for this PR to progress within the next few weeks if at all possible. Do let us know if you need any help or would like more time. Thank you for your patience thus far.

**Comment by ypinhsuan** [comment]
Hi @dastansultanov, any progress on this PR? It's fine if you need more time, do let us know if you are facing any problems. Thanks!

**Comment by madanalogy** [comment]
Almost three weeks has passed since last notice with no response from PR author. Closing due to inactivity. @dastansultanov feel free to reopen this PR if you intend to continue working on it, though it'll be subject to prevailing conflicts with any other PRs addressing the issue / related issues

**Comment by P-Fabian** [comment]
I'm confused. There is also this older issue, which seems to be open, but not answered to: https://github.com/TEAMMATES/teammates/issues/10986
Is the issue still there or can it be closed?
I'd love to work on that issue.

**Comment by t-cheepeng** [comment]
@P-Fabian The issue is still open

**Pull request closed without merging**
