### PR TITLE
[#12312] Instructor giving individual deadline extensions: give an easy way to select all those who have not submitted yet

### LINKED ISSUE #12312: Instructor giving individual deadline extensions: give an easy way to select all those who have not submitted yet
v8.25, production

Suggestion: When an instructor is giving individual deadline extensions, provide a way to easily select all who have not submitted responses yet.
image

This can be similar to how we do the same when sending individual submission reminders.
image

### PR DESCRIPTION
**Pull request by ellaella12**
Fixes #12312

**Outline of Solution**
- queries feedback service to get submitted giver set
- updates submit status in Feedback model
I was also wondering, why is isLoadingAllStudents set to false, right when the feedback session is loaded and before getAllStudentsOfCourse()?

New deadline extension is applied to all instructors and users that have not submitted.
image
image
image

### CODE REVIEW

**Comment by zhaojj2209** [comment]
Thank you for working on this!

Some suggestions:
- Use the `form-check` class for the styling of the checkbox, do check the discussion in #12366 for more details.
- The new checkboxes work, but the "Select All" checkboxes are not updated accordingly (see below screenshot where clicking the "Select all instructors not yet submitted" checkbox causes all instructors to be selected, but the "Select All" checkbox is not ticked). Can we add in logic to update these checkboxes as well when interacting with the new checkboxes?
Screenshot 2023-05-12 at 19 38 01

**Comment by ellaella12** [comment]
Thank you for the review, I have updated the code to include form-check bootstrap class, and added logic to update 'Select All' checkbox, Thank you!
image

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

**Review by weiquu — APPROVED** [review]
LGTM!

**Pull request merged**
