### PR TITLE
Instructor: edit question visibility: do not delete existing responses when visibility is changed #6124

### LINKED ISSUE #6124: Instructor: edit question visibility: do not delete existing responses when visibility is changed
Occasionally, instructors delete responses accidentally while editing visibility. 
Let's not delete existing responses when changing visibility. Instead, let's simply warn the instructors that the existing responses were submitted under the promise of different visibility options and they should exercise care when changing visibility after submissions.

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #6124 

**Outline of solution:**

**Backend:**
- Remove condition in the `areResponseDeletionsRequiredForChanges` method in the `FeedbackQuestionAttributes` class that checked for visibility changes. Now, responses are no longer deleted if only visibility settings are changed.

**Frontend:**
- Change the warning added in #7453 to read `Changing visibility after collecting responses is not recommended.`

**DEV INPUT REQUESTED:**
- I need help to figure out which inputs in the `questionVisibilityOptions.tag` need the `.nonDestructive` class to be added to prevent the following JS code (present in `instructorFeedbackEdit.es6`) from assigning a `mustDeleteResponses` `editStatus ` to the form because of visibility changes

```Javascript
$('form[id|=form_editquestion]').find(':input').not('.nonDestructive').change(function () {
        const editStatus = $(this).parents('form').attr('editStatus');
        if (editStatus === 'hasResponses') {
            $(this).parents('form').attr('editStatus', 'mustDeleteResponses');
        }
    });
```

This will then prevent the warning modal that says "Warning: Existing responses will be deleted by your action" from popping up when visibility options are changed.

Note: As of now, changes to the feedback path WILL delete existing responses. I have not changed that in this PR. Is that okay?

### CODE REVIEW

**Comment by leeyimin** [comment]
@HirdayGupta It's okay that changing feedback path will delete existing responses. I believe that is not under the scope of the issue/PR.

**Comment by HirdayGupta** [comment]
@leeyimin, filtering out the  `.visibilityCheckbox` in the es6 code works to prevent the "warning: deletion" modal for all changes when the `Custom` mode is enabled. However changing between any of the pre-defined `COMMON_VISIBILITY_OPTIONS` still prompts this dialog to be shown. Any suggestions?

**Comment by leeyimin** [comment]
@HirdayGupta Check out visibilityOptions.es6, `checkAndMarkDestructiveChange`.

**Comment by HirdayGupta** [comment]
@leeyimin Awesome catch. So filtering out the `.visibilityCheckbox` and removing the `checkAndMarkDestructiveChange` method gets rid of the "Warning: this will delete all responses" modal together. Would you instead recommend a replacement modal (in addition to the warning color and message of the visibility options div) of color warning and respectively changed message? (Like: Caution: Changing visibility options is not recommended....) ?

**Comment by leeyimin** [comment]
I would think an additional modal is not necessary. 

@damithc What is your opinion on this?

**Comment by damithc** [comment]
> I would think an additional modal is not necessary.
> 
> @damithc What is your opinion on this?

Yes, as we are not deleting responses, no need to show the modal.

**Comment by HirdayGupta** [comment]
@leeyimin Ready for review! 

**Changes made:**
- Added `not('. visibilityCheckbox') ` filter when marking destructive changes to prevent custom changes to visibility resulting in "Warning: responses will be deleted..." modal.
- Removed `checkAndMarkDestructiveChange` from `visibilityOptions.es6` which prevents ANY changes to visibility resulting in the "Warning: responses will be deleted..." modal.
- Changed class from `alert-danger` to `alert-warning`

**Note:** This is what the `visibility options` div looks like with the `alert-warning` class as suggested by @leeyimin.

screen shot 2017-07-04 at 5 22 06 pm

**Comment by damithc** [comment]
> This is what the visibility options div looks like with the alert-warning class as suggested by @leeyimin.

Usually, this style is the appropriate choice for warnings. But this one is not a usual level warning. I'm wondering if we should use `danger/error` here, as before.

**Comment by HirdayGupta** [comment]
@damithc I was actually thinking the same. The `alert-warning` does not seem, for lack of better phrasing, "dramatic" enough :p, to discourage the instructor. May I revert https://github.com/TEAMMATES/teammates/pull/7642/commits/37afc339bab523f6cf2258e163571ebcbaee69a9 ?

**Comment by damithc** [comment]
> May I revert 37afc33 ?

@leeyimin what do you think?

**Comment by leeyimin** [comment]
@HirdayGupta Hmm I see.. I agree with your opinion, do revert 37afc33.

**Comment by HirdayGupta** [comment]
@leeyimin Revert done. Ready for review.

**Pull request merged**
