### PR TITLE
 instructorFeedbacks: start time isn't given a default value at 11pm #3926 

### LINKED ISSUE #3926: instructorFeedbacks: start time isn't given a default value at 11pm
starttimeuninitialised

Can be reproduced at 11pm. The start time is supposed to be set to 1 hour after the current hour.

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #3926

### CODE REVIEW

**Comment by rclakmal** [comment]
The mod operator doesn't seem to be serve any purpose here. It simply restrict `currenTime` between 0 and 23, where we need to be between 1 and 24 according to our select options.

**Comment by damithc** [comment]
@junhaoyap is it possible to change an existing test to cover this? If it is too much work, we can create a separate issue for that.

**Comment by junhaoyap** [comment]
@damithc this will require that we have a specific test for 11PM which might seem like an odd number to test against but yes it's definitely do-able - although it might be a tad hard for a new contributor as we will need to create a specific test and add an assertion to prevent this regression

@rclakmal are you up to doing that or should we open a separate issue to tackle this, I'll let you have the call here

**Comment by damithc** [comment]
@junhaoyap in that case, please open a separate issue.

**Comment by junhaoyap** [comment]
Will merge this soon - opened a issue https://github.com/TEAMMATES/teammates/issues/4921 as requested, @rclakmal feel free to take it up if you're up to it!

**Comment by junhaoyap** [comment]
@rclakmal I've merged this, good job on completing this task, now that you have two contributions, it'd be great if you can try your hands on more fulfilling tasks :+1:

**Pull request merged**
