### PR TITLE
InstructorFeedbackResultsDownloadActionTest have unnecessary duplications #6924

### LINKED ISSUE #6924: InstructorFeedbackResultsDownloadActionTest have unnecessary duplications
There seems to have unnecessary duplication among the `verifyFileContent` methods that can be refactored to make it clearer.

### PR DESCRIPTION
**Pull request by Malkone**
#InstructorFeedbackResultsDownloadActionTest have unnecessary duplications #6924
Fixes #6924

**PR Checklist**
Added additional private methods which return Strings to fill array in updated of methods
Removed unnecessary duplications of string creation in verifyFileContent methods, except blank strings "", because writing method name is longer and does not make the code cleaner

### CODE REVIEW

**Comment by Malkone** [comment]
Hi, I'm trying to change this but got confused, when I make new commits my pull request changes automatixally without providing ability to change PR text... Should I create new pull request for this change? Thank you!

**Comment by Neurrone** [comment]
@Malkone welcome to Teammates!

What do you mean your PR changes automatically without providing ability to change PR text?

Please avoid having multiple PRs on the same issue when possible. 

Finally, please note our convention on PR titles; have changed it for you for this PR.

**Comment by Malkone** [comment]
Thank you! Now I understand, what I did wrong, will be more carefull in the future!

**Comment by Malkone** [comment]
Could someone please advise, why Travis CI doesn't start the checking?

**Comment by wkurniawan07** [comment]
@Malkone I apologize, but this PR needs to be closed since the issue at hand was not well-defined to begin with.

**Comment by Malkone** [comment]
Hi, sure no problems, 
Thanks!

**Pull request closed without merging**
