### PR TITLE
CourseTable.tag

### PR DESCRIPTION
**Pull request by sidntrivedi012**
Fixed Indentation of all the tags.

Fixes #

**PR Checklist**

Ensure that you have:
- [ ] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [ ] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ ] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
Sir,Can i do it now?
Is the indentation alright?

**Comment by VamsiSangam** [comment]
Hi @sidntrivedi012 ! Welcome to TEAMMATES! We follow some naming conventions here. The pull request is named the same as that of its corresponding issue (along with issue number), so in your case the ideal PR name would be `Remove excess space in courseTable.tag #7961`, and in the PR description, you need to mention which issue is this PR fixing, so in the description, you need to write something like `Fixes #7961`. Please go through our [contributor orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) so that you can seamlessly contribute to TEAMMATES.

Also, I request you to close this PR as there is already another ongoing PR for the same issue. Please pick any other [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) issue of your choice. :smile:

**Comment by sidntrivedi012** [comment]
Ok Sir. Thanks for guiding.

**Comment by wkurniawan07** [comment]
The related issue has been resolved by #7975 which is pending merging.

**Pull request closed without merging**
