### PR TITLE
Integrate Codecov to the CI build #5317

### LINKED ISSUE #5317: Integrate Codecov to the CI build
As promised in #5268. With JaCoCo up and running, the next step is to make good use of the report generated.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #5317 

Let's hope I get this configured correctly.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Presenting our [first coverage report](https://coveralls.io/jobs/14392807)! :tada: :tada:

**Comment by kanghj** [comment]
Let's merge this soon?

**Comment by wkurniawan07** [comment]
@damithc do we want to include the test classes in the coverage report, or just the main classes? Including just the main classes will drop the coverage down to just about 60% though, and that's already excluding the un-coverable classes like Servlets and Filters.

**Comment by damithc** [comment]
@kanghj sorry for the spam if you received a review request from this issue. I was playing around with the new 'request review' feature.

**Comment by wkurniawan07** [comment]
This issue is sadly blocked by travis-ci/travis-ci#7094 :thinking: 
If they don't manage to resolve it anytime soon, I'll be switching to [codecov](https://codecov.io/).

**Comment by damithc** [comment]
[se-edu](https://github.com/se-edu/addressbook-level4) uses coveralls. Is this problem specific to TEAMMATES?

**Comment by wkurniawan07** [comment]
I suspect Java 7. Need to see how things develop on their side.

**Comment by wkurniawan07** [comment]
Actually codecov looks like the better choice ([reference](https://www.slant.co/topics/2188/versus/~codecov_vs_coveralls_vs_code-climate), [reference](https://stackshare.io/stackups/codecov-vs-coveralls-vs-uberalls), [reference](https://tilify.com/galvin/coveralls-vs-codecov/), [reference](https://github.com/brettcannon/cpython-ci-test/issues/27)). They did lose out in popularity but that's hardly a minus point.

One thing for sure, [their bot beats coveralls' hands-down](https://github.com/brettcannon/cpython-ci-test/pull/32#issuecomment-263410916).

**Comment by damithc** [comment]
We can try codecove. It's ok for different projects to use different tools.

**Comment by wkurniawan07** [comment]
@damithc should I integrate Codecov now? Doing this means we're sort of enforcing code coverage which I'm not sure we're ready for.

**Comment by damithc** [comment]
> Doing this means we're sort of enforcing code coverage which I'm not sure we're ready for.

I guess we can override the CI failure on coverage drop?

**Comment by wkurniawan07** [comment]
Codecov doesn't inherently enforce any coverage (Coveralls also, I believe); the thing I am more concerned with is now all contributors must live with Codecov reporting their code status and if we do not make good use of them it will be quite a nuisance.
If we want to enforce coverage, then we have to make it a rule and communicate it to everyone.

**Comment by damithc** [comment]
Coveralls an be configured not to post coverage updates as comments. Instead, they show up as a CI check (similar to travis status), which is less intrusive (see below). May be Codecov has the same feature?
image

**Comment by wkurniawan07** [comment]
I need to explore Codecov a bit more for that.

**Comment by wkurniawan07** [comment]
@damithc we should be ready to try this.

**Comment by damithc** [comment]
> @damithc we should be ready to try this.

Can go ahead.

**Comment by wkurniawan07** [comment]
Post-mortem:
image
I have configured three different status badges:
- `codecov/patch`: coverage of all the lines introduced in the PR
- `codecov/project`: default setting, i.e. production code coverage; this is also what is shown in the README.
- `codecov/project/all`: coverage of ALL codes (production + test - client script)

Coveralls allows no such configuration, and this is only a fraction of what Codecov allows, so choosing Codecov is a correct decision.

**Comment by damithc** [comment]
Looks nice 👍

**Pull request merged**
