### PR TITLE
[#12313] Instructor sending submission reminders: missing space between checkbox and label

### LINKED ISSUE #12313: Instructor sending submission reminders: missing space between checkbox and label
v8.15, production

image

Perhaps already fixed in the current master. Posting here just in case.

### PR DESCRIPTION
**Pull request by sgadkar2**
Fixes #12313

**Outline of Solution**

 

Used form-check and form-check-inline class from bootstrap for proper formatting of checkbox and label.

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @sgadkar2, do fix the failing lint tests before we proceed to review your PR. Thanks!

**Comment by sgadkar2** [comment]
Hi, Can anyone please review this PR. Thanks!

**Review by cedricongjh — APPROVED** [review]
LGTM! Thank you for your contribution to TEAMMATES

**Review by jasonqiu212 — APPROVED** [review]
LGTM!

**Pull request merged**
