### PR TITLE
Tinker

### PR DESCRIPTION
**Pull request by gupta-ujjwal**
I updated the UI of the contact page of the teammate project. Although its not much of a change but it did made the UI look a little better then the previous. Bootstrap icons are used in so there was no additional files added just some little changes did it all.

Before
screenshot from 2018-02-22 23-50-42

After 
screenshot from 2018-02-25 13-10-17

### CODE REVIEW

**Comment by bqnguyen94** [comment]
This looks good 👍 I believe you are doing this as per the [Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md)? Then perhaps you should create a new issue showing these changes to UI and introduce yourself to everyone. :)

**Comment by gupta-ujjwal** [comment]
Thanks @bqnguyen94 . I am new to open source so i am not fully aware of the process. Please check me if i am right.

First i should create a  new issue stating the UI changes. Then in this pull request i should right the issue number , title and the changes made ?

**Comment by wkurniawan07** [comment]
@gupta-ujjwal I presume this is done as part of the task in the contributor's orientation guide. This should not be made into a PR, so I am going to close this.

> I am new to open source so i am not fully aware of the process.

There is no "*the* process"; it depends from organization to organization (even from project to project). Do consult our documentations to find out the practices being done here.

**Comment by gupta-ujjwal** [comment]
@wkurniawan07  You are right . I did this as a part of the task in contributor's orientation guide. But i think that this can be an improvement in the UI as meaning no offense the UI of some pages is not very good as compared to the scale of the project .For example the photos in the About us page can be rearranged in a tabular form and changes can be made to the UI of contact page as i mentioned earlier. I can work on the UI of the website.Then again this is just a suggestion.

 So should i create an issue regarding this and work on it or just work on the other issues.

**Comment by damithc** [comment]
> So should i create an issue regarding this and work on it or just work on the other issues.

I suggest you work on existing issues for now. Once you are well acquainted with the project you can start suggesting UI improvements.

**Pull request closed without merging**
