### PR TITLE
 Wrong Status Message in AdminAccountDetailsPage #4021 

### LINKED ISSUE #4021: Wrong Status Message in AdminAccountDetailsPage
When deleting a student in Admin Account Details, `Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE` is used instead of `Const.StatusMessages.STUDENT_DELETED`

### PR DESCRIPTION
**Pull request by manishvishnoi2**
Fixes #4021

### CODE REVIEW

**Comment by manishvishnoi2** [comment]
hello,
This patch fixes the issue for Adminaccountdetails page but i found out that similar problem is present in Adminaccountdelete function.Even if we remove a instructor it is sending a status message for instructor removed.Should i include that in patch too.

**Comment by junhaoyap** [comment]
@manishvishnoi2 try to keep patches atomic, open a new issue and if you're up to completing the issue, do open a pull request for it as well - in the case that we need to revert patches we won't have to revert things that we still want

**Comment by junhaoyap** [comment]
@manishvishnoi2 apologies I was of the assumption that this was not tested in the HTML tests as it was an admin page but turns out that it does and there are tests failing due to this change - could you run the tests and make sure all tests are green and get back to me regarding this? :)

**Comment by thyageshm** [comment]
@manishvishnoi2, a gentle reminder to complete this task by V5.72 release

**Comment by thyageshm** [comment]
@manishvishnoi2 Please try to complete this PR by tomorrow, or I am afraid this PR would be closed tomorrow due to long inactivity.

**Comment by junhaoyap** [comment]
Closing this due to inactivity

**Pull request closed without merging**
