### PR TITLE
instructorHelp.jsp: Reorder entries in Table of Contents #6328

### LINKED ISSUE #6328: instructorHelp.jsp: Reorder entries in Table of Contents
Currently, this entry ("What to do if a student says he cannot submit responses due to some technical glitch?") in the table of contents for instructorHelp.jsp (highlighted in red in the screenshot attached) does not agree with the ordering of the actual contents. It should be placed in the position marked by the green arrow instead (just under "How do I interpret/use contribution values in the results of ‘Team contribution’ type questions?").
isp

### PR DESCRIPTION
**Pull request by leeyimin**
Fixes #6328

### CODE REVIEW

**Comment by damithc** [comment]
@wkurniawan07 Looks like this file uses 4-space indenting (should be 2-space right?) and probably needs line wrapping too. Create firstTimer issue? If have more such files, may be use as a source of firstTimer issues?

**Comment by wkurniawan07** [comment]
@damithc we are nowhere near using 2-space for HTML/JSP/tag files (which is why I remove that rule from the setting up guide). If we want to enforce that rule, then every single HTML/JSP/tag file (save for very few) is a source of refactoring.

**Comment by wkurniawan07** [comment]
https://github.com/TEAMMATES/teammates/pull/5744#issuecomment-236167871

> Better switch to 2 spaces for html-like files to avoid wasting space.

I agree with this.

> May be do it opportunistically, starting with the files where it is in fact a problem?

How do we define "a problem"?

**Comment by damithc** [comment]
@wkurniawan07 I forgot that we don't have that rule in TEAMMATES. I'll leave it you to decide when to and how to introduce it.

**Pull request merged**
