### PR TITLE
Issue 3147 sort constant sum statistics recipient name

### LINKED ISSUE #3147: Display constant sum statistics sorted by recipient name or option
For both the statistics on the website and in the csv file downloadable by instructors, the statistics table can be displayed in a sorted order

Edit (18 December 2016):
Screenshot (of the table to change sorting for ): 
constantsumstats

### PR DESCRIPTION
**Pull request by swxsw**
Fixes #3147
Added relevant comparator to constant sum question

### CODE REVIEW

**Comment by swxsw** [comment]
In progress, tests to come

**Comment by swxsw** [comment]
@kanghj I have updated the default display order for constant sum question results/statistics, now I am in process of updating tests but seem to be running into a bit of trouble, hope to seek your help on this.

I have read the document about god mode and tried using it, but somehow testNG is giving me the following message: "java.lang.AssertionError: Student MOTD URL defined in app.student.motd.url in build.properties must not be empty. It is advised to use test-student-motd.html to test it.".

Did I configure the build.properties wrong? Because I am not testing the message of the day feature so I suppose there is no need to fill it in? Somehow god mode requires it, will it affect the html generated during god mode in ui tests if I use  test-student-motd.html, or will it not affect the html generated using god mode?

**Comment by damithc** [comment]
@swxsw Why not give it a try and see what happens?

**Comment by swxsw** [comment]
On hold, because I could have potentially misinterpreted the issue again

**Comment by swxsw** [comment]
Going to close this PR because indeed I misinterpreted again, thoroughly clarified and will make another PR

**Pull request closed without merging**
