### PR TITLE
instructor home page: overflow in table cells #4539

### LINKED ISSUE #4539: instructor home page: overflow in table cells
image

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #4539

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
Wrapping now only allowed for session name

image

**Comment by thyageshm** [comment]
@JosephineKwa for your review :-)

**Comment by JosephineKwa** [comment]
@YongJieYongJie , changes look ok :). I just have a minor suggestion. Currently, when the screen size is reduced, the table looks like this.

overflow

Perhaps you could also make the table scrollable upon overflow to further improve the responsiveness of the table.

**Comment by YongJieYongJie** [comment]
@JosephineKwa 

Would it be okay if the wrapping defaults to "yes-wrap" when screen width becomes smaller?

Doing overflow scrolling on <td> requires quite some CSS gymnastics. There needs to be fixed table width, cell widths etc. and may be counter to the design principle behind bootstrap.

image

**Comment by JosephineKwa** [comment]
@YongJieYongJie , allowing the buttons to wrap when the screen width becomes smaller is ok as well :+1:

**Comment by YongJieYongJie** [comment]
@JosephineKwa All done!

**Comment by JosephineKwa** [comment]
Good to merge! Sorry, I wasn't able to review this earlier as I was busy this past week!

**Comment by thyageshm** [comment]
@JosephineKwa please merge this in

**Comment by JosephineKwa** [comment]
@YongJieYongJie , I was able to get dev green with your changes earlier, but when running the tests again, I'm currently getting test failures on line 247 and 252 of AdminHomePageUiTest. Could you resolve these as well?

**Comment by damithc** [comment]
Closed and opened to force a Travis build. Don't merge unless travis passes.

**Comment by thyageshm** [comment]
One of the failures is being fixed in #5178, the rest need to be fixed

**Comment by YongJieYongJie** [comment]
@JosephineKwa Tests are now passing again.

**Comment by JosephineKwa** [comment]
Good to merge!

**Comment by thyageshm** [comment]
@JosephineKwa please try to merge this in today

**Pull request merged**
