### PR TITLE
 InstructorFeedbackResultsPage: make span scrollable to fit the table to copy #8437

### LINKED ISSUE #8437: InstructorFeedbackResultsPage: make span scrollable to fit the table to copy
**Description of feature/enhancement**

In the instructor feedback results page, instructors can directly copy the data in the page to an excel spreadsheet if non-english characters are not displayed properly in the downloaded file:

image

However, if there are feedback and comments given by students/instructors, the resulting table protrudes from the given span:

image

The span can be made scrollable in order to fit the entire table within the span.

**Justification**

By allowing the table to fit within the span, it will improve the look of the table. Additionally, it will make the table more readable for instructors (particularly the alternating transparent rows) so that they can take a look at the data before copying to their excel spreadsheet.

### PR DESCRIPTION
**Pull request by Shashwat-Garg**
Fixes #8437 
Sorry, I don't know how I stupidly closed my older PR #8479 
Added code to CSS stylesheet for the overflow manipulation.

### CODE REVIEW

**Comment by Shashwat-Garg** [comment]
@joanneong Please check this. Extremely sorry for the confusion.

**Comment by Shashwat-Garg** [comment]
I am attaching a GIF, which show that the table is now scrollable.

team

I hope this explains the changes. :)

**Comment by LiHaoTan** [comment]
Adding a note note here that this bug is already fixed by Bootstrap.

**Comment by Shashwat-Garg** [comment]
@LiHaoTan Sorry, I didn't notice it. Should I close the PR ?

**Comment by LiHaoTan** [comment]
Of course not, TEAMMATES is still on an older version of Bootstrap 3.

**Comment by Shashwat-Garg** [comment]
@joanneong All the tests have passed, but I guess we need to look over what @LiHaoTan  said.

**Comment by joanneong** [comment]
I went to [read up a little on it](https://stackoverflow.com/questions/26394072/bootstrap-3-table-table-responsive-not-working/26424135), and as @LiHaoTan mentioned it does seem like sometimes Bootstrap 3's `.table-responsive` class does not seem to be working very well. 

In this case I think the changes that you made are okay. Awaiting an additional review from a senior developer...

**Comment by Shashwat-Garg** [comment]
@LiHaoTan will look into it ASAP. :)

**Comment by Shashwat-Garg** [comment]
@LiHaoTan Sorry got busy with exams. I need to change just this page to bootstrap 3.3.7 right ?

**Comment by LiHaoTan** [comment]
@Shashwat-Garg you should upgrade the version everywhere.

Note that this might require quite some work so given that this issue is not very important (as of now) so that is why we are not going ahead with your temporary solution.

**Comment by wkurniawan07** [comment]
@Shashwat-Garg Closing as the solution will not be adopted. If you wish to work on the alternatives suggested by @LiHaoTan, feel free to raise a new PR.

**Pull request closed without merging**
