### PR TITLE
 Instructor result download: xlsx file taking longer than csv file #6030 

### LINKED ISSUE #6030: Instructor result download: xlsx file taking longer than csv file
I have a case where csv file is downloaded almost immediately but the xlsx file time out.

### PR DESCRIPTION
**Pull request by rclakmal**
Reverting xlsx download feature until we figure out a solution to performance issue mentioned in the (fixes #6030)

### CODE REVIEW

**Comment by rclakmal** [comment]
@damithc Here's the PR to revert xlsx changes

**Comment by wkurniawan07** [comment]
Reverting the entire thing might be an overkill. We can just remove it from the UI (thereby restricting any end-user access to it) and keep the feature internally for future development, until we're ready to release it.

**Comment by damithc** [comment]
Let's revert it fully for now. It's best not to have dead code. In the meantime, @rclakmal can recover the code in a separate branch, fix the problem and merge it back again.

**Comment by wkurniawan07** [comment]
Confirmed that the code base after this PR is identical to what it would be without #5826 :+1:

**Pull request merged**
