### PR TITLE
[#9551] Instructor: Correct wrong colors and ensure consistency between modal boxes

### LINKED ISSUE #9551: Instructor: Correct wrong colors and ensure consistency between modal boxes
**Environment**:
`master` branch

**Steps to reproduce/Expected behavior**
The modal boxes present in the instructor pages are inconsistent and some have wrong colors. Below are a few examples. There might be more.
1. `/web/instructor/home`
- `Course` -> `Archive` 
image
- `Course` -> Header's `Delete` & Row's `Delete`
image
image
2. `/web/instructor/courses`
- `Course`'s row -> `Delete`
image
3. `/web/instructor/courses/details?courseid=inst.exa-demo`
- Row's `delete (`student-list-component`)
image

Also, some modal boxes have excess padding and should be removed. Example below:
image

**Expected behavior**
1. Warning modal boxes should be using the same yellow hex code
2. Delete modal boxes should be using the same red hex code
3. Archive/normal message modal boxes should be using the same blue hex code

### PR DESCRIPTION
**Pull request by ritisha2000**
Fixes #9551 

The modal boxes were located in multiple places.

Archive_Course_Edited
Delete_Student_Edited
Recycle_Course_Edited
Recycle_Session_Edited

In addition to these, I corrected the "Send Join Request" modal box 

Send_JoinRequest_Edited

Also, there were some inconsistent modal boxes in the student pages. Below are the unedited and edited ones. I can reverse these changes if you would like.

(Student)Delete_Picture
(Student)Delete_Picture_Edited
(Student)Save_Profile
(Student)Save_Profile_Edited

### CODE REVIEW

**Comment by tanhengyeow** [comment]
Hi @ritisha2000 

Thanks for working on this! It looks like you're pushing commits from a different user's branch. Can you change that to push it from your own branch instead?

**Comment by ritisha2000** [comment]
I am working on this issue as a group project for a class so I'm submitting a PR from a member's fork.

**Comment by tanhengyeow** [comment]
@ritisha2000 I see, please take a look at the Travis build to see why it was failing before this PR will be reviewed :)

**Comment by ritisha2000** [comment]
Thank you for your feedback, I corrected my mistake to make it pass the Travis build.

**Comment by xpdavid** [comment]
Closed due to inactivity.

**Pull request closed without merging**
