### PR TITLE
Instructor: view results: make the explanation of the view more informative #8528

### LINKED ISSUE #8528: Instructor: view results: make the explanation of the view more informative
Current:
image

Suggestion:
1. Use an ascii arrow `→` rather than `>` (both in this view, and in the drop down menu)
2. Give a more precise tooltip based on the value e.g., `Group responses by giver, then by recipient, and then by question`

### PR DESCRIPTION
**Pull request by J-Eisen**
Fixes #8528 

**Outline of Solution**
 - Used regex with find and replace to incorporate new text.
 - Decided that in the context of the filterEditModal window, the tooltip should reflect the more general state. Rolled back those changes but kept the others.

### CODE REVIEW

**Comment by joanneong** [comment]
Hi @J-Eisen , great to see your contribution to TEAMMATES! :)

Before I review them, can you make sure that the tests are passing first? You might want to take a look at [GodMode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) if it helps.

**Comment by J-Eisen** [comment]
Thanks, @joanneong! I knew I missed something when I saw the failing ci test.

**Comment by J-Eisen** [comment]
Hmm... tried using Godmode and still didn't pass. I'll take a closer look at my dev setup and make sure I didn't miss anything else.

**Comment by joanneong** [comment]
@J-Eisen On a side (but important) note, please remember to make your changes in a new branch. I see that your changes have been made on your master branch; please follow the [development guide](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-2-start-clean-from-a-new-branch) and start clean from a new branch each time!

**Comment by J-Eisen** [comment]
Ah! I totally misread the development guide and merged my fix branch with my main before the PR. As I write it out, I realize that that makes no sense. -_-

Do you think I should just start fresh from a clean branch and submit a new PR? Or try to get this working then create a fresh branch for everything going forward?

**Comment by J-Eisen** [comment]
Sorry! I accidentally hit comment and close.

Updated the PR. I'm still failing a few tests consistently, but they appear to be unrelated to the fix. I'll see if there's anything more I can figure out.

**Comment by joanneong** [comment]
@J-Eisen I would help you to figure out the problem, but unfortunately I can't pull your branch down to test locally from TEAMMATES since it's your master branch. Can you try to create a new branch from where you are now, and then hard reset the master branch to the state before this PR?

**Comment by J-Eisen** [comment]
Sure!

**Pull request closed without merging**
