### PR TITLE
InstructorSessionEdit: Duplicate question easily with a duplicate button #8876

### LINKED ISSUE #8876: Instructor: edit session: give a way to duplicate a question
Suggestion: give a way to create a duplicate of a question in the same session
image

Justification: it is possible for a session to have several variation of the same question

### PR DESCRIPTION
**Pull request by jacoblipech**
Fixes #8876 

**Outline of Solution**

Added a copy button for instructor to easily copy a question. Upon clicking of the question, the copied question will be added below the session edit.

The current UI is shown below. 
copy question

Is this acceptable? @damithc

### CODE REVIEW

**Comment by damithc** [comment]
Use `duplicate` instead of `copy`, similar to Google forms (see below)?
image

**Comment by jacoblipech** [comment]
@TEAMMATES/seniordevs Ready for review! Thank You :)

**Comment by jacoblipech** [comment]
@tshradheya Made the necessary changes. Ready for Review.

**Comment by jacoblipech** [comment]
On a side note, I just want to share a problem I experienced when using `GodMode` on this PR. As I performed `GodMode` on a branch which is not up to date to `master` branch, it does pass on my local computer but failed on Travis due to additional `verifyHtml` checks merged from other PRs. 

The error appears as the local code base does not have the newly added tests to perform `GodMode` on. In this case, it is caused by the merged PR #8860 hence it is important to always update your branch before performing `GodMode` to ensure that it passes on Travis as well 👍

**Comment by jacoblipech** [comment]
screen shot 2018-07-02 at 4 48 31 pm
This is how it looks after adding two icon side-by-side. I feel a bit weird looking at this but I am not too sure also...

**Comment by damithc** [comment]
> This is how it looks after adding two icon side-by-side. I feel a bit weird looking at this but I am not too sure also...

I'm OK with it. It's a bit weird, but effective :-p But I'm not opposed to the previous icon if other reviewers prefer that.

**Comment by tshradheya** [comment]
I am OK with this design too. 
@jacoblipech Go ahead and update the PR with the multiple copy icons

**Comment by jacoblipech** [comment]
@tshradheya Made the necessary changes, I think it is ready to be merged! Thanks.

**Comment by tshradheya** [comment]
@damithc Now that the icon has changed is this ready to merge?

**Comment by damithc** [comment]
> @damithc Now that the icon has changed is this ready to merge?

Yes, I think so.

**Comment by tanhengyeow** [comment]
@jacoblipech You might want to follow up with [this](https://github.com/TEAMMATES/teammates/pull/8756#issuecomment-404145902) 😄

**Pull request merged**
