### PR TITLE
[#11878] Add snapshot tests for instructor request form UI

### PR DESCRIPTION
**Pull request by xenosf**
Part of #11878

Depends on #12929

**Outline of Solution**
* Add snapshot tests for `RequestPageComponent` and `InstructorRequestFormComponent`

### CODE REVIEW

**Review by jayasting98 — APPROVED** [review]
Regardless of the commit history, I don't really have any problems with this.

**Comment by ziqing26** [comment]
On the issue of commit history, if you find rebase too confusing, you can look into the command `git cherry-pick` where you can create a new branch and cherry pick the relevant commits onto that branch.

**Comment by ziqing26** [comment]
@xenosf Would you like to clean up the git history before we merge this in:)

**Comment by xenosf** [comment]
Thanks for the detailed advice @jayasting98 and apologies for the delay! I've cleaned up the git history.

**Pull request merged**
