### PR TITLE
[#11843] Fix front end bugs

### PR DESCRIPTION
**Pull request by dishenggg**
Part of #11843 

**Outline of Solution**

- Fix not viewed since message
- Updated disclaimer message
  image

### CODE REVIEW

**Review by cedricongjh — APPROVED** [review]
LGTM!

**Comment by FergusMok** [comment]
@dishenggg @cedricongjh I realized there's also this edge case that might be misleading (probably not as common)

1. Person submitted the responses on 12th April 
2. Query logs from 1st April to 11th April
The message will be "Not submitted responses since Mon, 01 Apr 2024 ... "

I'd rather we display something true, i.e "Not submitted responses in the query range", or some alternatives that I can think of:

1. Have another action to query the latest logs for each student and display to show either "no submission / access", or the latest submission / access. But I also understand that it's quite close to the release and the action might take a significant amount of work.
2. Make the end query time to current time permanently, and the current statement will always be true.
3. Change the message to "Not submitted responses in the query range".

What do you guys think

**Comment by dishenggg** [comment]
> 3. Change the message to "No access / submitted responses in the query range".

I think this would work best for now, since there might be uses for the instructors to query up to a certain date/time e.g., a deadline

**Review by FergusMok — APPROVED** [review]
Great work, thanks for working on these fixes! 👍

**Pull request merged**
