### PR TITLE
Typos in StudentProfilePictureEditAction, AdminSearchPageData #6988

### LINKED ISSUE #6988: Typos in StudentProfilePictureEditAction, AdminSearchPageData
Detail CheckStyle Report:
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html

StudentProfilePictureEditAction.java
``` java
readAllPostParamterValuesToFields();
```

AdminSearchPageData.java
Seesion is not a word according to provided dictionary
``` java
public HashMap<String, String> feedbackSeesionLinkToNameMap = new HashMap<String, String>();
```

AdminSearchPageData.java
Homa is not a word according to provided dictionary
``` java
public HashMap<String, String> instructorHomaPageLinkMap = new HashMap<String, String>();
```

### PR DESCRIPTION
**Pull request by theitrain**
Fixes #6988 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [ ] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by chowyb** [comment]
Hi @theitrain,

Thanks for your contribution! However, the PR description is still a little off (as mentioned by the bot).

Additionally, merging from the `master` branch is generally not a good idea, as you will need additional work to reset it once this PR is merged. For your first PR however, this may not be too much of an issue, but do try to use a separate branch for future PRs :smile:

**Comment by theitrain** [comment]
I added the fix # to the PR. Should I close this and open a new PR from a branch? Not sure what's left to do.

**Comment by chowyb** [comment]
@theitrain it should not be necessary to close this PR (since it is your first PR), however after this PR is merged in, you will likely need to reset your master to be in sync with the master branch in this repository. For future PRs, it would be best to start from a different branch instead of master.

**Comment by whipermr5** [comment]
@theitrain there are PMD violations after merging in changes in #7122. The fix should be pretty simple - change `HashMap` to `Map`.

**Comment by theitrain** [comment]
Sorry for the confusion everyone. I fixed the conflicts.

**Comment by whipermr5** [comment]
@theitrain No worries; not your fault! Good job and thanks for your contribution!

**Pull request merged**
