### PR TITLE
Add PMD plugin setup instructions #5327

### LINKED ISSUE #5327: Add PMD plugin setup instructions
Add setup instructions for the eclipse PMD plugin

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #5327.

Cancelled the travis build since this doesn't touch any code

### CODE REVIEW

**Comment by wkurniawan07** [comment]
PMD is actually somewhat trickier, because we need the `.project` to include the PMD builder as well (otherwise PMD will use most of the rules provided, i.e the ~350 rules they have), but `.project` is not git-ignored.

**Comment by wkurniawan07** [comment]
Might need to put this on hold for #5365, it should be done in no time.

**Comment by wkurniawan07** [comment]
Actually why did I even put this on hold, you can continue on the instructions, just that until #5367 is merged people will need to take care not to commit the changes to `.project` file.

**Comment by JosephineKwa** [comment]
Add a short section on how to run PMD on the the project folder from Eclipse :D?

**Pull request merged**
