### PR TITLE
Fix typo in AdminHomeJsTest.js #6735

### LINKED ISSUE #6735: Fix typo in AdminHomeJsTest.js
On line 1, we have "QUnit.module('common.js');" - it should be "AdminHome.js" instead.

### PR DESCRIPTION
**Pull request by shubhamnishad97**
Fixes #6735

On line 1 changed "QUnit.module('common.js');" to "QUnit.module('AdminHome.js');" as guided by @Neurrone.

### CODE REVIEW

**Comment by Neurrone** [comment]
@shubhamnishad97 good job. In future, please note the following:

* The PR title should be the issue's title followed by its number, in this case "Fix typo in AdminHomeJsTest.js #6735"
* The PR description should also reference the issue, not this PR.

Will fixed it for you this time :)

**Comment by Neurrone** [comment]
Fixes #6735

**Comment by shubhamnishad97** [comment]
thanks @Neurrone for your help. will remember the note in future PRs.

**Comment by Neurrone** [comment]
@shubhamnishad97 NP, thanks for your contribution.

**Pull request merged**
