### PR TITLE
Student: submit responses: mention that partial answers can be saved #7993

### LINKED ISSUE #7993: Student: submit responses: mention that partial answers can be saved
In the submission page, we can mention that partially responses can be 'saved' using the submit button.

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7993 

**Outline of solution**

- Added a status message of color info to the feedbackSubmissionEdit page that displays the sentence recommended by @damithc sir to inform users that partial answers can be saved.
- The status message is added using the `statusMessageToUser` funcitonality in the `*Action` classes.

_[New UI Screenshot]_

screen shot 2017-08-27 at 11 07 11 am

(Note that the misaligned div will go away after #7999 is merged)

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@leeyimin @whipermr5 @chowyb  requesting your advice on this since I have worked with you on testing code decisions in the past:

Currently, the `StudentFeedbackSubmitPageUiTest` is failing at [line 236](https://github.com/TEAMMATES/teammates/blob/765dac3d570bdef94ec8ad9a4e518b4a3f73cda6/src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java#L236)
as the `verifyStatus` checks for equality against ALL status messages being displayed (and due to the problem brought up in https://github.com/TEAMMATES/teammates/issues/7993#issuecomment-325179420, there are two statuses displayed after submission of responses). 

Would it be okay for me to add a method called `verifyStatusContains` which would read like this: (noticiable differences from original method highlighted using diff). Note that I will be adding this in as an addiitonal method, not replacing the existing one. The diff notation is just to make the functionality evident to you.

``` diff
-    public void verifyStatus(final String expectedStatus) {
+    public void verifyStatusContains(final String expectedStatus) {
        try {
            uiRetryManager.runUntilNoRecognizedException(new RetryableTask("Verify status to user") {
                @Override
                public void run() {
                    waitForElementVisibility(statusMessage);
-                    assertEquals(expectedStatus, getStatus());
+                    assertTrue(getStatus().contains(expectedStatus));
                }
            }, WebDriverException.class, AssertionError.class);
        } catch (MaximumRetriesExceededException e) {
-            assertEquals(expectedStatus, getStatus());
+            assertTrue(getStatus().contains(expectedStatus));
        }
    }
```

This method will verify that the FEEDBACK_RESPONSES_SAVED status message does indeed get displayed, without it having to be the ONLY status message present for me to do so.

**Comment by HirdayGupta** [comment]
@whipermr5 @chowyb @leeyimin Requesting for advice on this. Would be extremely grateful if one of you could assist. Thank you :)

**Comment by wkurniawan07** [comment]
@HirdayGupta is it unnecessarily complicated to do a `verifyStatus` against _both_ the present statuses?

**Comment by HirdayGupta** [comment]
@wkurniawan07 I agree. In our current checking mechanism, the contents of ALL status messages on the page is concatenated into one string and checked for EQUALITY with the string passed. The method I'm proposing will allow us to check as many as status messages (one or all) as we please, because it uses `.contains()` instead of `.equals()`.

**Comment by wkurniawan07** [comment]
@HirdayGupta I am not giving a stand; I am asking. Current checking mechanism (checking the contents of all status messages, concatenated) does not sound bad to me; in fact it sounds like a necessity to me. Are there use cases of having to check just part of the status messages?

**Comment by HirdayGupta** [comment]
> I am not giving a stand; I am asking. 

Whoops :sweat_smile:. My apologies @wkurniawan07. 

I was thinking to check just part of the message because I felt checking both was unnecessary.  The use case would be when there are two or more status messages present.

 If you suggest however, I can instead pass the two concatenated status messages to the current existing method.

**Comment by wkurniawan07** [comment]
> The use case would be when there are two or more status messages present.

And are there cases where at least some of them are irrelevant?

**Comment by HirdayGupta** [comment]
@wkurniawan07 the case being the changes in my current PR. So I didn't want to check the new status message I had added, but just only check the success status message (which is how the current test works). Since I only wanted to test one message I proposed that method.

**Comment by wkurniawan07** [comment]
@HirdayGupta, you still did not answer the question. It is not the issue whether you _want_ to test it or not. The issue is whether testing just part of the message will affect the quality of test in the future or not, and whether it is a worthy trade off with the reduced complexity (if any).

**Comment by HirdayGupta** [comment]
@wkurniawan07 Apologies for being unclear with the phrase "want". The following message should clarify what I meant to say. I have even committed some changes to further explain what I mean.

**Affecting the quality of the test:**
Testing part of the message _might_ affect the quality of the test in the future only because if someone adds a status message to the page, the test won't fail and therefore will not remind the dev to update it. That being said, the dev is free to add in the status message he wishes to check in the new method as well (it is the dev's purview to update relevant tests). In fact, it will be easier to check two status messages with this method. (Explained how below).

**Case for the worthy trade off:**
The new method I proposed would allow me to just use that instead of adding in a hard coded `\n` and oddly concatenating the strings (as seen in the changes in https://github.com/TEAMMATES/teammates/pull/8004/commits/ca00240844f4d003494fcec5c91327dc464b827f - an example to show you what the test needs to pass without my proposed method). This complexity of the odd concatenation and the `\n` is what this method will reduce. 

Also, I do not believe it will be necessary for me to verify the new status from this PR at every stage as it is just a static status message that does not depend on any logic, so, I did not "want" to check the new status at each step.

In the future, if any dev _does_ indeed wish to check two or more status messages, then my proposed method will make it easier because instead of doing the odd concatenation as shown in my commit above, he can simply do `verifyStatusContains(string1);` followed by `verifyStatusContains(string2);`.

A couple of things to note:

- I am not proposing replacing the `verifyStatus` method entirely in the codebase, just adding in the new `verifyStatusContains` method I proposed for the double status message.
- I will have to make similar changes as I made in https://github.com/TEAMMATES/teammates/pull/8004/commits/ca00240844f4d003494fcec5c91327dc464b827f across all the tests failing in the [Travis log](https://travis-ci.org/TEAMMATES/teammates/builds/268969397?utm_source=github_status&utm_medium=notification) associated withhttps://github.com/TEAMMATES/teammates/pull/8004/commits/191a2d6df6feb1e87171348b16a64f3189384790. That is why, in my opinion, my new method would allow the tests to be cleaner.

I hope I have been able to answer your question @wkurniawan07. Let me know if you need any more details. Please advise regarding the same.

**Comment by wkurniawan07** [comment]
@HirdayGupta

> Also, I do not believe it will be necessary for me to verify the new status from this PR at every stage as it is just a static status message that does not depend on any logic

> can simply do verifyStatusContains(string1); followed by verifyStatusContains(string2);

Sadly, not all status messages are static. Additionally, using `.contains` is quite shaky as `.contains` lets substring keywords pass, which sometimes may not be what we want. Imagine this (unlikely to happen, but to illustrate how `.contains` can be misused):
```java
assertTrue("You can submit this session later, but your marks will be deducted".contains("You can submit this session later"));
```
i.e. your proposed method opens up possible misuses, and that is what I am against.

Why don't you just do this:
``` diff
-    public void verifyStatus(final String expectedStatus) {
+    public void verifyStatus(final String... expectedStatuses) {
        try {
            uiRetryManager.runUntilNoRecognizedException(new RetryableTask("Verify status to user") {
                @Override
                public void run() {
                    waitForElementVisibility(statusMessage);
-                    assertEquals(expectedStatus, getStatus());
+                    assertAllContained(expectedStatuses, getStatus().split(Const.EOL)); // implement assertAllContained accordingly
                }
            }, WebDriverException.class, AssertionError.class);
        } catch (MaximumRetriesExceededException e) {
-            assertEquals(expectedStatus, getStatus());
+            assertAllContained(expectedStatuses, getStatus().split(Const.EOL));
        }
    }
```
I'm quite sure you can get what I wanted to achieve with `assertAllContained`.

**Comment by wkurniawan07** [comment]
Hi @HirdayGupta, any updates here?

**Comment by HirdayGupta** [comment]
Hi @wkurniawan07, thanks a lot for the suggestion, it looks like it will work! My apologies for the delay in getting back as I am busy with moving in to my new college. I should be able to update this PR in about a week's time with the changes you suggested. Is that okay?

**Comment by wkurniawan07** [comment]
@HirdayGupta of course it is fine, I just need to make sure that the PR is not abandoned.

**Comment by wkurniawan07** [comment]
Hi @HirdayGupta, have you found the time to continue this PR?

**Comment by wkurniawan07** [comment]
Closing due to inactivity for a long period. @HirdayGupta feel free to reopen when you are ready to resume the work here.

**Pull request closed without merging**
