### PR TITLE
Wrong Status Message in AdminAccountDetailsPage #4021

### LINKED ISSUE #4021: Wrong Status Message in AdminAccountDetailsPage
When deleting a student in Admin Account Details, `Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE` is used instead of `Const.StatusMessages.STUDENT_DELETED`

### PR DESCRIPTION
**Pull request by AnaghHegde**
Fixes #4021

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@AnaghHegde there are failing tests that you need to fix. You may want to consult the Travis CI build log to find out which ones.

**Comment by AnaghHegde** [comment]
@wkurniawan07 I am getting dev green . So can i submit the pull requests now?

**Comment by wkurniawan07** [comment]
@AnaghHegde you have submitted a pull request (i.e. this one). There is no need to submit another one; just push the fixes you have made here.

**Comment by AnaghHegde** [comment]
@wkurniawan07 Why the build is failing even though i am getting dev green. Can you please help me out.

**Comment by AnaghHegde** [comment]
@wkurniawan07 according to the build its failing in AdminAccountDetailsPageUiTest.java at line 71. When i trace the call back i got like this the first call  detailspage.verifyHtmlMainContent("/adminAccountDetailsRemoveStudent.html") which in turn call the  AppPage.verifyHtmlMainContent( ) which will call AppPage.verifyHtmlPart() which in turn will call the HtmlHelper.areSameHtml() this will call the HtmlHelper.assertSameHtml(with 3 parameters) -->HtmlHelper.assertSameHtml(4 parameters)   which compare the html file (adminAccountDetailsRemoveStudent.html) with the results generated during the test and the problem in the test after the removal of student the status message will be Student removed from the course but the adminAccountDetailsRemoveStudent.html has only Instructor removed from course in line 57 and there is no information about Student. So  the <expected> and the <actual> are different .So build is failing .

Can you please guide me what do i have to do further.

**Comment by wkurniawan07** [comment]
> but the adminAccountDetailsRemoveStudent.html has only Instructor removed from course in line 57 and there is no information about Student

@AnaghHegde from where do you get this information? If only from the status message in that HTML file, that is precisely what you need to fix.

**Comment by AnaghHegde** [comment]
and @wkurniawan07 i got this from the error log ( after running test) in eclipse ( local environment ) and travis build log ( lines 1945 and 1947  and after the line 1951- which says about the verification ) and i traced all those calls which lead me to the **adminAccountDetailsRemoveStudent.html** . 

But the problem is i can't add both the status message in that html file, if i add again it will fail because test generates once only message at a time but the html file will have two messages( both the student and instructor ). So again **expectd** and **actual** will be different. Is it ok if i remove the calling of that function ?

**Comment by wkurniawan07** [comment]
> i can't add both the status message in that html file, if i add again it will fail because test generates once only message at a time but the html file will have two messages( both the student and instructor )

@AnaghHegde may I know what stops you from removing the message for the instructor and replacing it entirely with the message for the student? If you take a look at the build log, only that line causes the difference in the expected and actual cases.

**Comment by AnaghHegde** [comment]
@wkurniawan07  the problem is if i remove the message for instructor and replace it with the student the test will fail because the test checks for both student and instructor - meaning when the instructor is removed during the test the test will fail as there wont anything that says about the instructor.Did u get what i am trying to say?

**Comment by wkurniawan07** [comment]
@AnaghHegde honestly, I don't. Have you tried changing the message in that specific line of that specific HTML file and see how it goes?

**Comment by AnaghHegde** [comment]
@wkurniawan07  I know if i do that it will work for sure. But what i am trying to say is different.

**Comment by wkurniawan07** [comment]
@AnaghHegde does that have anything to do with the issue at hand? If it is not, please do not bring it in. It only adds unnecessary complexity, as you have clearly experienced now. If you believe that something is not right, feel free to open an issue for discussion.

**Comment by AnaghHegde** [comment]
@wkurniawan07 i am not able to create pull request.Is something wrong with my permission to this repo?

**Comment by AnaghHegde** [comment]
@wkurniawan07 I tried to commit to the same branch but i don't know what went wrong so i created a new pull request #6314 .

**Comment by wkurniawan07** [comment]
Superseded by #6314.

**Pull request closed without merging**
