### PR TITLE
[#11772] team contribution questions: force submissions to be zero-sum

### LINKED ISSUE #11772: team contribution questions: force submissions to be zero-sum
Current: A 'team contribution' questions allow respondents to use any scale. e.g., a respondent can give E, E, E or E, E, E+50%

Problem: While this flexibility is expected to increase the sincerity of submissions (the hypothesis is that a respondent will be more willing to say "I did an equal share, but others did more" than to say "I did less than an equal share") it can cause confusion when students compare their ratings with each other or when marks are given based on the absolute values of ratings received.

Suggestion: When creating this type of question, give the instructor an option to force the submission ratings to add up to `team size x E` (similar to point distribution questions) e.g., if the team size is 4, the ratings should add up to `4 x E` such as `E-10, E+10, E, E`. This option can be selected by default. The instructor can be cautioned not to unselect it if marks are intended to be given based on ratings received.

### PR DESCRIPTION
**Pull request by xyliew25**
Fixes #11772

**Outline of Solution**

Step 3 of the data migration process:
1. Modify the default constructor for `FeedbackContributionQuestionDetails`, which is used in deserialization, such that `isZeroSum` is set to `false` by default if absent, as in old feedback contribution questions.
2. Write and run a data migration script to set `isZeroSum` of old questions to `false`.
3. Revert the logic for the default constructor such that both constructors, i.e. `FeedbackContributionQuestionDetails()` and `FeedbackContributionQuestionDetails(String questionText)`, have the same set of default values.

### CODE REVIEW

**Review by wkurniawan07 — APPROVED** [review]

**Comment by fsgmhoward** [comment]
@NicolasCwy @ziqing26 Would appreciate if a final review can be done on this PR.

**Review by ziqing26 — APPROVED** [review]
LGTM!

**Comment by xyliew25** [comment]
Hi @ziqing26 sorry for the delay! I've updated the branch. May I know if you or me is going to merge the branch?

**Comment by ziqing26** [comment]
> Hi @ziqing26 sorry for the delay! I've updated the branch. May I know if you or me is going to merge the branch?

I can help with that, thank you!

**Pull request merged**
