### PR TITLE
[#2515] Instructor: edit instructors: ensure at least one instructor is visible to students

### LINKED ISSUE #2515: Instructor: edit instructors: ensure at least one instructor is visible to students
This is related to #2512

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #2515 
changed made in such a way that if only one Instructor is visible we can't make it invisible

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
ongoing

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07  Sir As asked by you in #8201 I had implemented the test case at action level .As the logic of not allowing only visible instructor to be invisible was approved by everyone so I have not change the logic

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07 sir ready for review

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07  Sir a reminder kindly have a look

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07  Sir kindly review it

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07  sir ready for review

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07 sir it is ready for review kindly have a look

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07  sir kindly have a look

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07 sir kindly have a look

**Comment by shaharyar-shamshi** [comment]
@tshradheya sir it seems that wkurniawan sir is busy can you review my pr . I will be thankful to you

**Comment by tshradheya** [comment]
Even if I review your PR, you will still require some senior developer to review it so I will leave it to them to review it.
@TEAMMATES/seniordevs anyone able to review this?

**Comment by shaharyar-shamshi** [comment]
Thanks @tshradheya  Sir

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07 sir this is ready for review

**Comment by shaharyar-shamshi** [comment]
@xpdavid sir can you review this I will be thankful to you

**Comment by shaharyar-shamshi** [comment]
@xpdavid sir kindly review it

**Comment by shaharyar-shamshi** [comment]
@xpdavid sir kindly review it . As only one extra file is changed( other are reviewed in pull request #8201) it will not take lot of your time to review

**Comment by shaharyar-shamshi** [comment]
@xpdavid sir a reminder

**Comment by shaharyar-shamshi** [comment]
@xpdavid sir a reminder . kindly have a look

**Comment by shaharyar-shamshi** [comment]
@xpdavid have a look

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07 kindly Have a look on this as well it is also ready for review

**Comment by shaharyar-shamshi** [comment]
@xpdavid  kindly have a look

**Comment by xpdavid** [comment]
You need to get your CI passed @shaharyar-shamshi

**Comment by damithc** [comment]
Closing due to inactivity

**Pull request closed without merging**
