### PR TITLE
[#8755] Update usermap to match data for March 2018

### LINKED ISSUE #8755: Update usermap to match data for March 2018
Similar to #8489

Entries to consider adding:

Australia | Curtin University
-- | --
Australia | Monash College
Australia | St Joseph's School Northam
Australia | The University of Western Australia
Australia | University of South Australia
Australia | University Of Technology, Sydney
Australia | University of the Sunshine Coast
Belgium | AP Hogeschool
Belgium | Erasmushogeschool Brussel
Belgium | Provinciaal Instituut voor Biotechnisch Onderwijs
Belgium | Universiteit Gent
Brazil | Faculdade de Tecnologia de Ourinhos
Canada | British Columbia Institute of Technology
Canada | Carleton University
Canada | Champlain St. Lawrence
Canada | Concordia University
Canada | Durham College
Canada | École de technologie supérieure
Canada | McMaster University
Canada | Nova Scotia Community College
Canada | Ryerson University
Canada | Ryerson University
Canada | St. Michael Catholic Secondary School
Canada | UNBC
Canada | University of British Columbia
China | Qingdao Number 1 International School of Shandong
China | Tianjin University of Technology
Colombia | Universidad de los Andes
Denmark | Aalborg University
El Salvador | OneLink Getcom
Estonia | Estonian Business School
Finland | Kurun yhtenäiskoulu
France | Burgundy School of Business
France | Ecole des ponts ParisTEch
France | ESSEC Business School
France | Grenoble Ecole de Management
France | Grenoble Ecole de Management
France | IESEG School of Management
Germany | European Business School
Germany | Kaiserslautern High School
India | NCR
India | Thapar Institute of Engineering & Technology
Japan | Kyushu University
Kazakhstan | NIS Almaty Ph.M
Lithuania | Affecto Lietuva
Malaysia | KDU University College
Malaysia | Universiti Malaysia Sarawak
Malaysia | Universiti Tenaga Nasional
Malaysia | University Tenaga Nasional
Mexico | ITESO
Netherlands | Eindhoven University of Technology
Netherlands | Eindhoven University of Technology
Netherlands | Hogeschool Rotterdam
Netherlands | ICT Institute
Netherlands | Johannes Fontanus College
Netherlands | Saxion University of Applied Sciences
Netherlands | Universiteit van Amsterdam
Netherlands | University of Applied Sciences Leiden
New Zealand | Goodnest School of Awesomeness
New Zealand | Massey University
New Zealand | University of Auckland
New Zealand | University of Otago
Pakistan | QUEST
Peru | Universidad San Ignacio de Loyola
Philippines | Ateneo School of Medicine and Public Health
Philippines | MSU-Iligan Institute of Technology
Philippines | UERMMMC
Philippines | University of Santo Tomas
Portugal | Escola Alemã de Lisboa
Singapore | Massey University
Singapore | National University of Singapore
Singapore | Ngee Ann Polytechnic
Singapore | Singapore Institute of Technology
Singapore | Singapre Polytechnic
Singapore | Victoria Junior College
Singapore | Ngee Ann polytechnic
South Africa | University of Johannesburg
South Africa | University of Johannessburg
South Africa | University of Pretoria
South Korea | Brigham Young University-Hawaii
South Korea | Chungnam National University
Spain | IES EL FOIX - Santa Margarida i els Monjos
Spain | IESE
Switzerland | Medtronic
UAE | IMT Dubai
UAE | Institute of Management Technology Dubai
UAE | University of Wollongong in Dubai
UK | Brighton And Sussex University Hospitals
UK | Buckinghamshire New University
UK | Hult International School of Business
UK | London School of Economics and Political Science
UK | Nottingham Trent University
UK | Queen Mary University of London
UK | University of Greenwich
UK | University of Greenwich
UK | University of Portsmouth
UK | University of Salford
UK | University of Sussex
UK | University of the West of Scotland
UK | Universtiy of Salford
UK | uri.lee@kcl.ac.uk
USA | Belmont University
USA | Brigham Young University - Idaho
USA | Brigham Young University - Idaho
USA | Butler University
USA | California Health Sciences University
USA | California State University
USA | Carleton College
USA | College of William & Mary
USA | Cornell University
USA | Dominican University
USA | Duke University
USA | Duke University
USA | Duke University
USA | Edison High School
USA | El-Abbadi Charter Academy
USA | Florida Southern College
USA | Fort Lewis College
USA | Garinger high School
USA | Georgia Southern University
USA | Harvard Division of Continuing Education
USA | Hult International Business School
USA | Hunter College CUNY
USA | Indiana State University
USA | Iowa State University
USA | Ithaca College
USA | Johnson County Community College
USA | Kennesaw State University
USA | Lakewood Middle
USA | Lee University
USA | Long Island University
USA | Merrimack College
USA | Michigan State University
USA | Michigan State University
USA | Mississippi State University
USA | Mount Saint Mary's University
USA | New Mexico State University
USA | Northeastern University
USA | Ohio University
USA | Oklahoma State University
USA | Pearson Education
USA | Point Park University
USA | Radford University
USA | Rensselaer Polytechnic Institute
USA | Riverview Elementary School
USA | Rochester Institute of Technology
USA | Saginaw Valley State University
USA | Saint Stephen's & Saint Agnes School
USA | Sonoma State University
USA | South College
USA | Southern Illinois University Edwardsvile
USA | Southern Oregon University
USA | Spring Hill College
USA | St. Joseph St. Thomas School
USA | Syracuse University
USA | Texas A&M University - Corpus Christi
USA | Texas Tech University
USA | The University of Texas at Austin
USA | Tree City Family Dental
USA | U.S. Army Engineer School
USA | University at Albany
USA | University of Arizona
USA | University of Colorado Boulder
USA | University of Dallas
USA | University of Florida
USA | University of Georgia
USA | University of Kansas
USA | University of Massachusetta Boston
USA | University of Massachusetts Amherst
USA | University of Miami
USA | University of Michigan
USA | University of Missouri
USA | University of Missouri - St. Louis
USA | University of North Carolina at Greensboro
USA | University of Oregon
USA | University of Oregon
USA | University of South Alabama
USA | University of South Dakota
USA | University of Southern California
USA | Washington State University
USA | Wellesley College
USA | Whitworth University
USA | William Carey University
USA | Xavier University of Louisiana

### PR DESCRIPTION
**Pull request by vsmasster**
Fixes #8755 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by Haozhe321** [comment]
@vsmasster Thanks for the PR 👍

Is this ready for review? I think there are some entries missing

**Comment by Haozhe321** [comment]
@vsmasster Are you working on this?

**Comment by vsmasster** [comment]
Sorry for delay. I think it's ready, actually some of the schools where already on the list, but with different name.

**Comment by dalessr** [comment]
Closing this PR as the issue has been solved in #9086

**Pull request closed without merging**
