### PR TITLE
[#11295] Distribute points among options question: negative points allowed on frontend

### LINKED ISSUE #11295: Distribute points among options question: negative points allowed on frontend
Very minor issue that's unlikely to be encountered in practice, but the frontend allows for points to be negative without showing any error:

Screenshot 2021-07-22 at 5 29 46 PM

The question submission will still fail as the backend does not allow for negative points

### PR DESCRIPTION
**Pull request by brandonfoong**
Fixes #11295

**Outline of Solution**

Added an error message if the user types in a negative value as a response to a `constsum-options` or `constsum-recipients` question.

Capture1
Capture2

As noted on the original issue, any form submissions with negative values will be rejected by the backend, so this is just a cosmetic fix prompting the user not to enter negative values.

### CODE REVIEW

**Comment by brandonfoong** [comment]
On a related note, I noticed that some of the constraints for the various responses are in the `/src/web/app/components/question-types/question-constraint/` folder, and some are still in the `/src/web/app/components/question-types/question-edit-answer-form/` folder. Would it be a good idea to refactor the code such that all the checks and error messages are in `question-constraint`?

**Comment by damithc** [comment]
How about the error message `Points cannot be negative`?

**Comment by brandonfoong** [comment]
Thanks for the feedback! Personally, I think either message is fine, and my intention was to keep it consistent with the error message produced by the backend.

err

**Comment by damithc** [comment]
> Thanks for the feedback! Personally, I think either message is fine, and my intention was to keep it consistent with the error message produced by the backend.

I see. Sure @brandonfoong , can keep it consistent with backend, or revise both.

**Comment by halfwhole** [comment]
@brandonfoong Just to follow up, would you like to stick with the current message, or revise both to say `Points cannot be negative`? Please tell us when it's ready to review too!

**Comment by brandonfoong** [comment]
Sorry for the delay, I've been rather busy recently and this completely slipped my mind. 
I'll be updating the error messages following @damithc's suggestion, will try to have it done in the next 2 days

**Comment by brandonfoong** [comment]
@halfwhole PR ready for review, thanks!

**Comment by daongochieu2810** [comment]
@brandonfoong hi please let us know if you have any update on this PR!

**Comment by brandonfoong** [comment]
Yup, I had this issue on my end too. However, I just tested with the master branch of the main repo and the same issue is there, so I don't think that it's related to my PR.

**Comment by halfwhole** [comment]
@brandonfoong I believe that the issue is what this PR is meant to fix! Looking through the code, it looks like it's probably related to the `isValid` method

**Comment by brandonfoong** [comment]
@halfwhole Got it! I'll have a look to see what's causing this issue.

**Comment by moziliar** [comment]
@brandonfoong any update on this PR?

**Comment by ypinhsuan** [comment]
Closing this PR for now due to inactivity. @brandonfoong Feel free to open it up again if you want to continue working on it.

**Pull request closed without merging**
