### PR TITLE
[#11571] Selective deadline extensions: resolve backend issues

### PR DESCRIPTION
**Pull request by samuelfangjw**
Part of #11571

**Outline of Solution**

Resolve comments in #11705

Edit: ~Temporarily changing target branch to master to trigger CI.~ This doesn't seem to work :/

### CODE REVIEW

**Review by moziliar — APPROVED** [review]
LGTM

**Comment by samuelfangjw** [comment]
@moziliar, I will run the CI checks [here](https://github.com/samuelfangjw/teammates/pull/10) (my own branch). CI will run again (on the main PR) when we merge to `selective-deadline-extensions` branch.

**Review by jayasting98 — APPROVED** [review]
LGTM

**Comment by moziliar** [comment]
CI seems fine. Let me merge this

**Pull request merged**
