### PR TITLE
feedbackResponseComments.js: use better parameter names #5707

### LINKED ISSUE #5707: feedbackResponseComments.js: use better parameter names
In `feedbackResponseComments.js`, there are two different set of parameter names:

`function toggleVisibilityEditForm(sessionIdx, questionIdx, responseIdx, commentIndex) {` and
`function hideResponseCommentEditForm(recipientIndex, giverIndex, qnIndex, commentIndex) {`

The first set of parameter names is accurate based off the context of `instructorCommentsPage`, while the second set of parameter names is accurate based off the context of `instructorStudentRecordsPage`. However, both pages reuse the same methods, and this becomes confusing to the developer as a result.

The solution I have in mind currently is to rename them to `firstIndex, secondIndex, thirdIndex, frcIndex` similarly to the current `feedbackResponseCommentRow.tag`, however this loses the meaning of the numbers. Adding comments as a header for every method would help keep the meaning, but causes the methods to be unnecessarily(?) verbose.

As such, I am leaving this issue up for discussion for now.

### PR DESCRIPTION
**Pull request by Mynk96**
Fixes #5707 
As the instructorComments page is no longer there, so used param names according to FeedbackResultsPage.

### CODE REVIEW

**Comment by Mynk96** [comment]
Ready for Review!

**Comment by chowyb** [comment]
Using comment box instead of review due to convenience - review box is narrow and doesn't offer preview capabilities.

Changes seem okay except that from my testing (by inspecting the resulting DOM in the browser, for the numbers on the "show visibility options" button), the behaviour for `InstructorStudentRecordsPage` is slightly different from the others.

From my testing, the numbering conventions seem to be as follows:

InstructorStudentRecordsPage:
-A-B-C-D
1. A: Giver index. Probably 1-indexed. If a particular giver has not responded, they will not add to the count (eg. if only Alice, Benny and Francis give a response, Francis will have giver index 3, skipping over Charles, Danny and Emma).
2. B: Recipient index. Probably 1-indexed.
3. C: Question index. Always 1-indexed.
4. D: FRC index. Always 1-indexed.

InstructorFeedbackResultsPage:
-A-B-C-D-E
1. A: Section index. Refers to Giver Section if grouped by GRQ, or Recipient Index if grouped by RGQ. Always 0-indexed.
2. B: Recipient index. Probably 1-indexed if grouped by GRQ, and 0-indexed if grouped by RGQ.
3. C: Giver index. Probably 0-indexed if grouped by GRQ, and 1-indexed if grouped by RGQ.
4. D: Question index. Always 1-indexed. Different giver types have their own set of indices (eg. there can be a question 1 where students are the givers, and a question 1 where teams are the givers in the same session).
5. E: FRC index. Always 1-indexed.

While the other information (0 or 1-indexed, whether numbers are skipped over, or duplicated) may not be relevant to this PR, it could suggest a need to make the numbering consistent (which could be done as a separate issue). However, its relevance to this PR is as such: the giver and the recipient index for `InstructorStudentRecordsPage` seems to be swapped. Everything else looks alright however 👍

**Comment by Mynk96** [comment]
@chowyb yes, numbering were slightly inconsistent. I have created an issue to resolve that after merging that this will get automatically resolved. #7544

**Comment by Mynk96** [comment]
@chowyb I've created a PR #7544 for the issue #7544.

**Comment by Mynk96** [comment]
@chowyb Ready for Review!

**Pull request merged**
