### PR TITLE
[#12186] removed raise edge image

### LINKED ISSUE #12186: raise-edge image should be removed
raise edge image should be removed from home page .

- **Environment**: 

**Steps to reproduce**
- open this page on any browser : https://teammatesv4.appspot.com/web/front/home
- take look at below the request a free instructer account  button 

**Expected behaviour**
Screenshot (86)

**Actual behaviour**
Screenshot (85)

**Additional info**

### PR DESCRIPTION
**Pull request by sumitshinde-84**
Fixes #12186 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**
i have removed raise edge image and added apropriate margin  from home page , feture page

i have also passed all the test 
Screenshot_2023-03-10_12-15-24

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
@samuelfangjw  request for review .

**Comment by weiquu** [comment]
Hi @sumitshinde-84, thanks for the PR. 2 issues first:
1. I noted that you ticked the checkbox corresponding to the "Added the issue number to the "Fixes" keyword above" item, yet it doesn't seem to be done. I think it would be better to shift your tagging of the issue from the bottom of your comment to the top, so that reviewers can immediately refer to it (rather than wondering about what issue this PR fixes). This is also to maintain consistency across PRs.
2. One of the lint checks is failing. To see what is causing the failure, you can click on the `Details` button next to the failing test, and the output will show what line is causing the error.
I've also left a comment under the issue you've raised, please go check it out.

**Review by weiquu — CHANGES_REQUESTED** [review]
Let's try to move towards the use of Bootstrap styles rather than defining our own custom styles (e.g. your `margin-bottom-40px`). You can refer to the [Bootstrap docs](https://getbootstrap.com/docs/5.0/utilities/spacing/) for more information.

**Comment by sumitshinde-84** [comment]
> Let's try to move towards the use of Bootstrap styles rather than defining our own custom styles (e.g. your `margin-bottom-40px`). You can refer to the [Bootstrap docs](https://getbootstrap.com/docs/5.0/utilities/spacing/) for more information.

Ok sir I will update it

**Comment by sumitshinde-84** [comment]
> Let's try to move towards the use of Bootstrap styles rather than defining our own custom styles (e.g. your `margin-bottom-40px`). You can refer to the [Bootstrap docs](https://getbootstrap.com/docs/5.0/utilities/spacing/) for more information.

but sir  i am confused  what changes should i made to update margin can you please tell me . because in our project there is an sass file . so where should i made changes . actually i havent used boostrap before .

**Comment by sumitshinde-84** [comment]
> Let's try to move towards the use of Bootstrap styles rather than defining our own custom styles (e.g. your `margin-bottom-40px`). You can refer to the [Bootstrap docs](https://getbootstrap.com/docs/5.0/utilities/spacing/) for more information.

ok wait i am gonna learn boostrap today .

**Comment by weiquu** [comment]
Thanks @sumitshinde-84, do check out the docs that I linked above as well. 

Also please note what @zhaojj2209 mentioned in your issue (ie image should be removed from all pages and the codebase)

**Comment by zhaojj2209** [comment]
> ok wait i am gonna learn boostrap today .

That's great to hear! In fact, according to our [Contributor Orientation Guide](https://teammates.github.io/teammates/contributing-doc.html#knowledge-required), Bootstrap is one of the required technologies that you need to learn before contributing to the TEAMMATES frontend.

Also, do remove the image from the features page as well, see https://github.com/TEAMMATES/teammates/issues/12186#issuecomment-1464830867.

**Comment by sumitshinde-84** [comment]
@weiquu  i have removed raise edge from home and feture page .

**Review by zhaojj2209 — CHANGES_REQUESTED** [review]
@sumitshinde-84 Please remove your changes in `package.json` and `package-lock.json`, and update your branch with the latest changes from `master`.

E2E tests may occasionally fail due to unstable tests. Please direct any questions to the maintainers of the repository instead of other first-time contributors.

**Comment by sumitshinde-84** [comment]
> @sumitshinde-84 Please remove your changes in `package.json` and `package-lock.json`, and update your branch with the latest changes from `master`.
> 
> E2E tests may occasionally fail due to unstable tests. Please direct any questions to the maintainers of the repository instead of other first-time contributors.

ok mam

**Review by weiquu — CHANGES_REQUESTED** [review]
Please remember to remove your `package-lock.json` changes as per @zhaojj2209's review... not sure why it's showing there's 73,874 changed lines.

Also, since we're no longer using the `raised-edge` image, feel free to remove it from the assets.

**Comment by sumitshinde-84** [comment]
> Please remember to remove your `package-lock.json` changes as per @zhaojj2209's review... not sure why it's showing there's 73,874 changed lines.
> 
> Also, since we're no longer using the `raised-edge` image, feel free to remove it from the assets.

@weiquu  i have  pasted orignal content from  package.lock.json because of its showing that much changes.

**Comment by weiquu** [comment]
> @weiquu i have pasted orignal content from package.lock.json because of its showing that much changes.

Noted, but we cannot possibly check through so many lines to ensure that that's indeed the case. You can look into using `git fetch` and `git checkout` to get back the original file. At the same time, do also merge in the latest changes from `master`.

**Comment by zhaojj2209** [comment]
> i have pasted orignal content from package.lock.json because of its showing that much changes.

My guess is you copy-pasted `package-lock.json` from your local `master` branch, which may not be up-to-date (we recently upgraded `package-lock.json` from v1 to v2). If you have indeed reverted your changes, then `package-lock.json` should not show up as one of the changed files in this PR.

I'd recommend learning to revert changes using Git so that such issues do not occur in the future.

**Comment by sumitshinde-84** [comment]
@weiquu  i have make another branch and another PR #12192 please check it

**Pull request closed without merging**
