### PR TITLE
Use builder instead of telescoping constructor antipattern in AccountAttributes class #7190

### PR DESCRIPTION
**Pull request by BrianCoveney**
Part of #7190

### CODE REVIEW

**Comment by BrianCoveney** [comment]
Ready for review

**Comment by BrianCoveney** [comment]
Added Javadoc to AccountAttributes and updated tests, to be inline with #7191

**Comment by BrianCoveney** [comment]
Ready for review

**Comment by BrianCoveney** [comment]
Changes made

**Comment by whipermr5** [comment]
@wkurniawan07 Reminder :)

**Comment by BrianCoveney** [comment]
Ready for review

**Comment by wkurniawan07** [comment]
Closing due to inactivity for a prolonged period. @BrianCoveney feel free to reopen if you wish to resume the work here.

**Pull request closed without merging**
