### PR TITLE
[#12275] Instructor edit sessions page: Fix preview sessions button overflow

### LINKED ISSUE #12275: Instructor edit sessions page: Fix preview sessions button overflow
At screen widths of less than 378px, the "Preview for Instructor" button overflows to the next line.
Screenshot 2023-03-27 at 16 14 34

The same issue exists on the instructor help page, where the "Preview for Instructor" button overflows at screen widths smaller than 410px, and both buttons overflow at widths smaller than 388px.
Screenshot 2023-03-27 at 16 17 09

One way to fix the issue is to align the buttons and dropdowns in column instead of row for small screen sizes.

### PR DESCRIPTION
**Pull request by Zxun2**
Fixes #12275

## Outline of solution
Purely cosmetic change on both Feedback Sessions Results and Feedback Sessions Edit page. Updated CSS where needed.

## Screenshots

- lg

image

- md

image

- sm 

image

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @Zxun2, will get to your PRs tmr! In the meantime, could you merge in the latest changes from `master`? Seems that there was an incident with GitHub Actions, so the checks weren't completed

**Comment by weiquu** [comment]
Looks good so far! 2 quick points:

Screenshot 2023-06-28 at 2 36 32 AM

Do you think it'll be possible to have the buttons be the same number of lines for all screen sizes? Seems to be present in a few different screen sizes (above is feedback sessions edit at 579px, below is instructor help page at 1225px). Off the top of my head, could set width for both to be the same / slightly bigger than what it currently is? But no worries if the solution is too complicated, looks to be a small issue
Screenshot 2023-06-28 at 2 39 47 AM

Second is that the button size doesn't work if there are no students that the session can be previewed as... seems to be because the styling is on the `<a>` tag, but that is only present if there are students to preview. Example below:
Screenshot 2023-06-28 at 2 41 29 AM

**Comment by Zxun2** [comment]
Thanks for the catch! I will fix it in a bit.

**Comment by weiquu** [comment]
Hi @Zxun2, instructor feedback sessions results and edit sessions page looks good now! For the instructor help page I noticed 2 issues:

From screen widths 576px to 584px, the "Preview as student" button takes up 2 lines (vs 1 line for "Preview as instructor"). Again, this is a small issue so no worries if the fix is too complicated - just thought I'd point it out.

From screen widths 992px to 1278px, the "Preview as instructor" button overflows to the next line... probably because the preview session panel is placed inside the example box for the instructor help page, meaning the width it has to use is smaller.
Screenshot 2023-06-29 at 4 13 51 PM

Would be great if you could look into these (:

**Comment by Zxun2** [comment]
Hey @weiquu, thanks for the review. Totally missed out the help page x.x 

This was quite a hacky fix. Essentially, what I did was to apply some custom styles when the component is used as an example. Do let me know if that's alright!

**Review by weiquu — APPROVED** [review]
LGTM! Thanks for contributing

**Review by cedricongjh — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
