### PR TITLE
Enhanced email interface for join links #8312

### LINKED ISSUE #8312: Enhancement: Improve Email Layout by using buttons for links
**Description of feature/enhancement**

When sending emails to student/instructor, instead of sending the raw link, we could send a button which redirects to the link when the button is clicked.
Something similar to the below: 
---
image
---

**Justification**

Through using buttons, we don't explicitly show the link and moreover, it improves the interface of email.

Hoping to get some feedback on this enhancement and would like to take it up if the enhancement is accepted to be implemented by the senior developers

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8312

Work still in progress. Will add screenshots soon after making minor tweaks

**Outline of Solution**

Used `<input type="button">` over the `<a href="">` to show clickable button which redirects to joining link.

**Screenshot**

image

### CODE REVIEW

**Comment by tshradheya** [comment]
Ready for Review

**Comment by damithc** [comment]
The first bullet point needs rephrasing.
Do you plan to do a similar enhancement for other kind of links e.g. submission links?

There are some downsides I didn't think of earlier.
1. Sometimes I resend submission links manually. Those links are now going to look odd to the user because TEAMMATES usually send buttons instead of links.
2. Although buttons look nicer, would the users feel safer to click plain text links because they can see the link is going back to teammates?

**Comment by tshradheya** [comment]
I can do the same for the submission links as well, I made the change only join links right now, so that the design and other things can be checked before I proceed further.

1. In that case, will it be better to only revamp `join links` since they need to be sent only once per user ?  Although I feel we should do for all to maintain consistency.

1. Agree with that point. The main reason why I thought of this was because some apps for e.g. `Slack` does it. But then with TEAMMATES the point may make sense cause most students are sent submission links for the first time by instructors which might make them apprehensive of clicking

**Comment by damithc** [comment]
So, may be put this on hold then? Given that the benefits are not significant and there could be downsides.

**Comment by tshradheya** [comment]
We can put this on hold then as the downsides are quite justified

**Comment by damithc** [comment]
Closing now. Can reopen later if needed.

**Pull request closed without merging**
