### PR TITLE
EmailTemplates contains ${joinFragment} placeholders that are unused #4967

### LINKED ISSUE #4967: EmailTemplates contains ${joinFragment} placeholders that are unused
There might be some **redundancy** in the email templates in `EmailTemplates.java` because the `${joinFragment}` placeholder seems to be always replaced with empty string for the following:
* `USER_FEEDBACK_SESSION_PUBLISHED`
* `USER_FEEDBACK_SESSION_CLOSING`
* `USER_FEEDBACK_SESSION`

I checked this by:
1. tracing the call hierarchy for each of the email template constants in `EmailTemplates.java`, then
2. from every assignment of the constant, I follow through to see how the placeholders are replaced

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #4967

### CODE REVIEW

**Comment by thyageshm** [comment]
@YongJieYongJie please edit your first comment to follow our format specified in the [process document](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md)

**Comment by thyageshm** [comment]
@taniach ready for review

**Comment by YongJieYongJie** [comment]
@thyageshm Thanks for the reminder, I've changed the comment accordingly.

**Comment by damithc** [comment]
@taniach does this mean we don't include the join link in emails at all, unless it is an email specifically for joining?

**Comment by taniach** [comment]
@damithc Yes

**Comment by thyageshm** [comment]
@taniach please merge this

**Pull request merged**
