### PR TITLE
SettingUp.md: recommend Source Tree instead of GitHub for Windows #5131

### PR DESCRIPTION
**Pull request by manparvesh**
Resolves [Issue #5131](https://github.com/TEAMMATES/teammates/issues/5131)

### CODE REVIEW

**Comment by YongJieYongJie** [comment]
@manparvesh do following the naming conventions for pull requests in [TEAMMATES Development Process][link]

The title for this pull request should be `SettingUp.md: recommend Source Tree instead of GitHub for Windows #5131` and the description should be `Fixes #5131`

[link]: https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md

**Comment by manparvesh** [comment]
@YongJieYongJie updated. Please check

**Comment by YongJieYongJie** [comment]
@manparvesh !'m a fellow contributor, do wait for the PR to be assigned to a reviewer!

**Comment by kanghj** [comment]
Hi @manparvesh , thanks for the pull request! However, please follow the [development process](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md) for the branch name. Since the branch name is incorrect, I will be closing this for now, could you make a new pull request with the correct branch? Thanks again!

**Pull request closed without merging**
