### PR TITLE
[#10243] Loading spinners for show buttons 

### PR DESCRIPTION
**Pull request by t-cheepeng**
Part of #10243

**Outline of Solution**
c
asd

- Added in spinner for instructor course page
- Change white spinner in instructor home/session to blue

### CODE REVIEW

**Comment by damithc** [comment]
The spinner itself looks good. 

On a separate note, I wonder if it was  mistake to left-align by default. Perhaps we should center align these columns i.e., columns containing a number. The reason is, a number is likely to be a lot smaller than the cell width and therefore looks odd when left aligned. Might apply for dates too. In fact, if the length of the content is fixed (e.g., dates), it's better to center-aligned. So, the design pattern can be _center align if length is fixed or very short (e.g., number, status)_

**Comment by damithc** [comment]
> On a separate note, I wonder if it was mistake to left-align by default. Perhaps we should center align these columns i.e., columns containing a number. The reason is, a number is likely to be a lot smaller than the cell width and therefore looks odd when left aligned. Might apply for dates too. In fact, if the length of the content is fixed (e.g., dates), it's better to center-aligned. So, the design pattern can be _center align if length is fixed or very short (e.g., number, status)_

In fact, there are some guidelines on the Web about this aspect.
* https://www.conetrees.com/articles/data-tables-cell-content-alignment-usability-guidelines/
* https://alistapart.com/article/web-typography-tables/

We can pick/adapt one to follow.

**Comment by t-cheepeng** [comment]
@damithc Following the bottom link. Here's some screenshots of how it would like for our tables. Don't think right align for numbers would fit well for us since we have the sorting icons

### All column left-aligned, except response rate
image
image

### All column left-aligned, except response rate and dates
image
image

### All column center-aligned, except session ID/course name
home
image

**Comment by damithc** [comment]
I like the last one.
Don't forget to update our document with the selected policies and a reference to the external document.
BTW, I just posted the top two search results as examples. Didn't mean to recommend them. The point being there's no need to make up UI design patterns ourselves as others have done it already. But we still need to explore them and pick one that works for us.

**Pull request merged**
