### PR TITLE
Remove unused parameter in InstructorHomeAjaxCoursePageData.java #6638

### LINKED ISSUE #6638: Remove unused parameter in InstructorHomeAjaxCoursePageData.java
In `teammates.ui.pagedata.InstructorHomeAjaxCoursePageData#init`, the last parameter `sectionNames` is not used and thus can be removed.

### PR DESCRIPTION
**Pull request by JoshuaClark311**
Fixes #6638 

**Outline of Solution**

> Removed the unused parameter _sectionNames_ from the method _init_

### CODE REVIEW

**Comment by JoshuaClark311** [comment]
Unfortunately I am not sure the issue with my title naming convention. I copied and pasted the title as required by the contributing guidelines. I also have looked to see the issue with be build failing as well. Could this be due to the branch being out of date?

**Comment by whipermr5** [comment]
Hi @JoshuaClark311, you need to update all calls to the method too so that the code can compile :)

**Comment by JoshuaClark311** [comment]
Oh wow, I can't believe I forgot that! I will make sure to find all of the calls and push again. :)

**Comment by whipermr5** [comment]
@JoshuaClark311 There are code style violations; you can open up the Travis log to see the violating lines. We adhere to [this](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html) Java coding standard.

**Comment by JoshuaClark311** [comment]
Ahhh thank you. It seems there were a few places I may have not fully removed spaces. I am going to try and fix the violating lines. I'm not sure about the pmdMain violation that is occurring though.

**Comment by whipermr5** [comment]
Yup! You can configure your IDE to automatically remove trailing spaces. The pmdMain violation is due to an unused import (take a look at [this](https://travis-ci.org/TEAMMATES/teammates/builds/210974786#L733) part of the log).

**Comment by JoshuaClark311** [comment]
I think I have fixed the issues with style and I configured Eclipse to remove trailing spaces. I also went ahead and removed the unused import as well. I will be updating my branch!

**Comment by whipermr5** [comment]
You need to configure Eclipse to remove trailing spaces from all lines (don't ignore empty lines).

**Comment by JoshuaClark311** [comment]
I do have that option selected. I will have to see what is happening.

**Comment by JoshuaClark311** [comment]
So it looks like that line was not caught during save. Not too sure why though. I went ahead and manually removed that white space

**Comment by whipermr5** [comment]
I think it wasn't run on that file after you selected the option (even if you press save, it does nothing if no changes were detected). Nice work; your code is now past the static analysis stage. Now to wait 25 minutes for the rest of the build to complete haha

**Comment by whipermr5** [comment]
Oh yes, you need to sync your branch with master again. The latest commit was 22 minutes ago.

**Comment by JoshuaClark311** [comment]
That's great to hear! You need me to merge my branch and master?

**Comment by whipermr5** [comment]
Yup!

**Comment by JoshuaClark311** [comment]
I'm not sure if I've done it correctly or not. I've synced my branch with my master but it does not show up in the commit tab here

**Comment by whipermr5** [comment]
You're doing it wrongly - you should not commit to master at all. Instead, master should be pulled into this branch.

**Comment by JoshuaClark311** [comment]
Okay, for some reason I manage to repush this to test by mistake. I will follow those steps exactly

**Comment by boxin-yang** [comment]
Hi @JoshuaClark311  , just looked at your changes and LGTM. However, you might want to read up on this [link](https://chris.beams.io/posts/git-commit/) on how to write better commit message.(commit message should start with present tense. "update" not "updated").    Also do read up on the expected workflow [here](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) . We have put down very detailed walk through on how you should go about syncing your branch with the upstream master branch.  Also, when you are done with merging, comment on your PR with **Ready for Review @your_reviewer** to notify your reviewer.

**Comment by JoshuaClark311** [comment]
Ready for Review @whipermr5 
Hope I've done it right! Followed your advice as well as @boxin-yang advice as well

**Comment by whipermr5** [comment]
@JoshuaClark311 Good job! Yup every push will trigger a build :) Remember to force push your master branch too

**Comment by JoshuaClark311** [comment]
I will make sure to do that! And to do that I will be replacing the branch name with just master? 
I.E: git push -f origin master

**Comment by whipermr5** [comment]
Yup! If done correctly, the [web UI](https://github.com/JoshuaClark311/teammates) should show `This branch is even with TEAMMATES:master.`

**Comment by whipermr5** [comment]
@JoshuaClark311 Just realised your commits are still on your master branch - you'll need to stash your changes, hard reset to before the first time you committed to master then force push to get your master clean (it should never be ahead of upstream). Do the same for this PR branch. Then update both branches, apply the stashed changes on this PR branch and push. Will continue the review process after you have completed this task.

**Comment by whipermr5** [comment]
@JoshuaClark311 Any updates? You might find it easier to use a Git GUI client like SourceTree to follow the instructions (I was thinking in terms of SourceTree when I wrote them).

**Comment by JoshuaClark311** [comment]
Currently working on repushing everything now!

**Comment by whipermr5** [comment]
@JoshuaClark311 Hmm it might be because the two branches became identical; sorry I didn't think of that 😅 Yup go ahead to open the new PR! Just follow the [process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) next time :)

**Pull request closed without merging**
