### PR TITLE
Fix infinite redirects when serving unknown URLs #6889

### LINKED ISSUE #6889: Fix infinite redirects when serving unknown URLs
**Environment**

Live server at `V5.98`

**Steps to reproduce**

Visit http://teammatesv4.appspot.com/abc

**Expected behaviour**

Fail gracefully with a 404 status code and error page

**Actual behaviour**

screen shot 2017-03-20 at 10 42 45 pm

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #6889

**Outline of solution:**

As per a [StackOverflow answer](http://stackoverflow.com/questions/12293934/google-app-engine-endless-redirect-with-a-filter-mapped-to), removed `<jsp config>` tag entirely from `web.xml`. This seems to solve the issue as can be seen by visiting a page that does not exist on my [staging server(v31)](https://4-31-dot-teammates-hirday.appspot.com).

**Example:**
eg: https://4-31-dot-teammates-hirday.appspot.com/abc will exit with a graceful 404.

Implemented as per @whipermr5's suggestion that the fix proposed by the aforementioned StackOverflow answer was a viable one.

### CODE REVIEW

**Comment by whipermr5** [comment]
Could you also add this line to all `src/main/webapp/*.jsp`? It's already present in all `src/main/webapp/jsp/*.jsp`:

`<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>`

**Comment by HirdayGupta** [comment]
@whipermr5 updated the .jsp files as required.

**Comment by HirdayGupta** [comment]
@whipermr5 apologies for the oversight. However, the unrelated changes seem to occur as soon as I paste `<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>` into the `.jsp` file and save. 

Any suggestions on how to prevent this? Should I just manually undo these automatic changes? Or is there a better way? 

Note: My eclipse text encoding is set to `Other: UTF-8` as mentioned in the setup guide.

**Comment by whipermr5** [comment]
@HirdayGupta Try following the link in #7274?

**Comment by HirdayGupta** [comment]
@whipermr5 all the settings matched to those on the link, but the automatic changes still happen. 

I just used a differrent text editor to make these changes, but that might be something we should look into.

**Pull request merged**
