### PR TITLE
[#11341] Update example box spacing

### LINKED ISSUE #11341: Spacing of contents within Example box can be improved
Page: `/web/front/help/instructor`

Looks relatively squashed

### PR DESCRIPTION
**Pull request by xinyee20**
Fixes #11341

- Make searching example box look less squashed

(before) 

(after)

### CODE REVIEW

**Comment by harshal43** [comment]
Hey @xinyee20,
I would like to work on this.

**Comment by xinyee20** [comment]
> Hey @xinyee20,
> I would like to work on this.

Hi, it's done already in the PR unless you have more things to add on?

**Comment by damithc** [comment]
@TEAMMATES/active-mentors anyone up for reviewing this PR?

**Review by jianhandev — APPROVED** [review]
Thanks for contributing, the margin added looks good to me 👍

**Comment by damithc** [comment]
@ccyccyccy can help to do the final review for this one and merge if everything is OK?

**Review by ccyccyccy — APPROVED** [review]
LGTM

**Pull request merged**
