### PR TITLE
Add new rules to Checkstyle - Modifiers

### PR DESCRIPTION
**Pull request by JosephineKwa**
Added modifier order and redundant modifier rules.

I'm not too sure if I should add this rule as the modifier order in checkstyle differs a little from the one specified in the teammates java standards doc. Specifically, checkstyle specifies that `transient` should be after `final` while the teammates standards specifies that `final` should be after `transient`

### CODE REVIEW

**Comment by kanghj** [comment]
@damithc, should we go with checkstyle's specifications for <code>final</code> and <code>transient</code>, or omit this rule?

**Comment by damithc** [comment]
Let's decide which one is better and apply it consistently.

**Comment by wkurniawan07** [comment]
Checkstyle follows JLS (Java Language Specification) so the chances of things going wrong on their side is slim.

**Comment by kanghj** [comment]
Let's go with checkstyle, since it can be enforced easily anyway. @JosephineKwa, then I think you have to change the teammates' standard to follow checkstyle's specifications.

**Pull request merged**
