### PR TITLE
Duplicate "the" in jsp files #6460

### LINKED ISSUE #6460: Duplicate "the" in jsp files
Remove the 3 extra `the`s from
1. Comment in `<form id="ajaxLoaderDataForm">` in `adminEmailLog.jsp`
2. The second `<li>` under `Enroll students by doing one of the following options` in `instructorHelp.jsp`
3. The first `<span>` after `Tolerate unequal contributions` in `instructorHelp.jsp`

### PR DESCRIPTION
**Pull request by iamhunter**
Fixes #6460

### CODE REVIEW

**Comment by iamhunter** [comment]
@samsontmr is it pretty?

**Comment by khanstark** [comment]
hello folks!
just wanted to know why this PR has not been merged if its fine?

**Comment by iamhunter** [comment]
@khanstark I assumed that was something that someone with more authority than I had to do.  Am I supposed to do something at this point to make the merge happen?

**Comment by khanstark** [comment]
@iamhunter  Maybe u can ping them for this issue, becoz many PR's are still open which should get closed.

**Comment by iamhunter** [comment]
@damithc Ready for review.

**Comment by samsontmr** [comment]
@khanstark @iamhunter just hang on guys, it's Chinese New Year over here and most of us are busy visiting relatives.

**Comment by khanstark** [comment]
@samsontmr In that case Happy New Year to all chinese friends. I was only suggesting that close the PR's which have been looked upon and checked, newcomers can get confused.

Have a look when u r free.
Cheers!

**Comment by wkurniawan07** [comment]
@khanstark, thanks for your concern for the PR.

For a PR to be merged, approval has to be obtained from one core team member (I am one of them) and the project manager. External contributors may chip in their opinions and give approvals themselves, but unfortunately they do not replace the two approvals I mentioned earlier. You would expect a similar workflow in many other open-source projects.

**Pull request merged**
