### PR TITLE
Remove method createAndReturnEntities from EntitiesDb.java #6668

### LINKED ISSUE #6668: Remove method EntitiesDb#createAndReturnEntities
The said method is not used anywhere.

### PR DESCRIPTION
**Pull request by kwehrheim**
Fixes #6668

Removed the method createAndReturnEntities as requested.

### CODE REVIEW

**Comment by samsontmr** [comment]
@kwehrheim there should not be a space between the hashtag and issue number.

**Comment by kwehrheim** [comment]
@samsontmr Thank you for your feedback!

**Comment by wkurniawan07** [comment]
@kwehrheim thanks for your contribution! Can we get your real name to be listed in our contributors' list?

**Comment by kwehrheim** [comment]
@wkurniawan07 Sure, my real name is Kaitlyn Wehrheim.

**Pull request merged**
