### PR TITLE
[#9419] Explore form validation in Angular - Add New Course

### PR DESCRIPTION
**Pull request by erjillsison**
Part of #9419

form validation

**Outline of Solution**
- Make use of FormGroup and FormControls to get input and perform validation.
- Perform basic validation for input i.e Input not empty and not exceeding max char limit.
- Upon clicking of submit form, display the appropriate error message next to the input fields instead of showing a status message.

### CODE REVIEW

**Comment by erjillsison** [comment]
Ready for review

**Comment by xpdavid** [comment]
Please discuss possible implementations before sending PR next time. 

Is it necessary to introduce `Reactive Form` to do validation? To me, `Template-driven forms` is more intuitive and enough for the simple form.

**Comment by erjillsison** [comment]
@xpdavid Understood. I'll explore validation using template-driven forms

**Comment by erjillsison** [comment]
@xpdavid Updated. Simplified the implementation by making it template driven.

**Comment by madanalogy** [comment]
Hi @erjillsison, you could consider standardising the display of invalid form warnings with those implemented in #9975 & #9633. Keen on helping to move this forward!

**Comment by wkurniawan07** [comment]
Superseded by #9820

**Pull request closed without merging**
