### PR TITLE
Fix #5103 'Rename HTML files in src/test/resources/pages that start w…

### LINKED ISSUE #5103: Rename HTML files in src/test/resources/pages that start with upper case
The files in `src/test/resources/pages` should all start with a lower case. There are some `Instructor*.html` that don't follow it.

### PR DESCRIPTION
**Pull request by afparsons**
Fixes #5103
Renamed Instructor*.html files in src/test/resources/pages to start with lowercase _i_.

Example: 
`src/test/resources/pages/{InstructorCourseDetailsEmptyCourse.html => instructorCourseDetailsEmptyCourse.html}`

### CODE REVIEW

**Comment by afparsons** [comment]
My PR seems to fail teammates.test.cases.ui.browsertests.Instructor* tests. 
I'm assuming this is because the browser tests look for Instructor*.html files instead of instructor*.html files. 

Do I modify the tests and submit them as a separate pull request? Or am I missing something else here? What is my next step?

**Comment by damithc** [comment]
Changes to the tests should be done in the same PR.

**Comment by afparsons** [comment]
@damithc Ok, I'll make the test changes as well. 
Which practice is preferred: modify this PR or close and reopen a new one?

**Comment by damithc** [comment]
@afparsons normally you just push to the same branch. The PR will update automatically. 
However, you'll have to close this PR and start a new one because you are not following our workflow. The PR should be on a separate branch. You can refer our developer docs to find the exact procedure.

**Comment by afparsons** [comment]
@damithc Ach, you're right. I surmise you mean the [process doc](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md). 
I'll close, open a new branch and start another PR. Thanks for being patient.

**Pull request closed without merging**
