### PR TITLE
[#11586] Remove trimming of gmail.com for user accounts

### LINKED ISSUE #11586: Remove trimming of gmail.com for user accounts
https://github.com/TEAMMATES/teammates/blob/f70ae535d0d0586d48530704227b67f169f49bfb/src/main/java/teammates/common/util/SanitizationHelper.java#L53-L55

https://github.com/TEAMMATES/teammates/blob/f70ae535d0d0586d48530704227b67f169f49bfb/src/main/java/teammates/ui/servlets/DevServerLoginServlet.java#L63

https://github.com/TEAMMATES/teammates/blob/f70ae535d0d0586d48530704227b67f169f49bfb/src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java#L85

Removing the trailing `@gmail.com` is a practice forced to us by the old and deprecated GAE Users API. We do not have any reason to do that anymore, so this practice needs to cease.

Need to also migrate entities who are scarred by this practice: accounts, students, instructors. Namely, if the `googleId` does not contain any `@`, it should be appended with `@gmail.com`.

### PR DESCRIPTION
**Pull request by xyliew25**
Fixes #11586

**Outline of Solution**

Step 3 of the data migration process:
1. Remove trimming of `@gmail.com` when saving `googleId` in the `Account`, `Instructor`, `CourseStudent` and `StudentProfile` entities and query for both `googleId` and `gmail`, i.e. `googleId` appended with `@gmail.com`, when searching/checking for users in the database.
2. Write and run a data migration script to append `googleId` that does not contain `@` with `@gmail.com`
3. Remove querying of `gmail` when searching/checking for users in the database.

### CODE REVIEW

**Review by wkurniawan07 — APPROVED** [review]

**Review by zhaojj2209 — APPROVED** [review]

**Review by ziqing26 — APPROVED** [review]

**Comment by ziqing26** [comment]
@xyliew25 Hi thanks for your contribution! Could you kindly update this branch so that it could be merged?

**Comment by xyliew25** [comment]
Hi @ziqing26 I've updated this branch as well.

**Comment by ziqing26** [comment]
> Hi @ziqing26 I've updated this branch as well.

@xyliew25 Could we trouble you to update the branch again? Thanks!

**Comment by xyliew25** [comment]
@ziqing26 ah yes, will do.

**Pull request merged**
