### PR TITLE
instructor session add: failed attempt results in <p> tags in the description #5994

### LINKED ISSUE #5994: instructor session add: failed attempt results in <p> tags in the description
Steps: Add a session with end time before the start time.
Result:
image

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #5994

### CODE REVIEW

**Comment by belyabl9** [comment]
Ready to review

**Comment by belyabl9** [comment]
Ready to review

**Comment by chowyb** [comment]
Looks good, maybe you can edit the current "end time earlier than start time" test case in `InstructorFeedbackEditPageUiTest` to test for this as well

**Comment by belyabl9** [comment]
@chowyb , the issue appears while adding session, not editing. I've added requested test check.
Ready to review

**Comment by belyabl9** [comment]
@chowyb , ready to review

**Comment by chowyb** [comment]
@belyabl9 looks good now :+1: 

In addition, I have manually tested this for bold, underline, italics text, links and images as well. The information for those are preserved correctly.

**Pull request merged**
