### PR TITLE
[#11865] Add to instructor help: 'Can I use a different team structure for different sessions?'

### LINKED ISSUE #11865: Add to instructor help: 'Can I use a different team structure for different sessions?'
Suggestion: Add the following to the instructor help page

Question: Can I use a different team structure for different sessions in the same course?
Answer:
Currently it is not possible. If you change the team structure midway, the new team structure will apply to all current/past sessions as well, and will cause any 'incompatible' responses (e.g., responses submitted in relation to a team that no longer exists) to be deleted automatically.
Workarounds (neither is optimal, unfortunately):
Alternative 1: Create a different course for each team structure you want to support.
Alternative 2: Keep changing the team structure as necessary but download the existing responses before changing it -- this works only if it is not important for students to be able to view responses to past sessions.

Probably fits this section:

image

### PR DESCRIPTION
**Pull request by Mcheung7272**
Fixes #11865 

Followed the other dropdowns to include this one. 
Added a new enum and moved the last qn class to my dropdown.

### CODE REVIEW

**Comment by damithc** [comment]
@Mcheung7272 Thanks for this PR. Can you also provide a screenshot of how it looks, for easier reviewing?

**Comment by Mcheung7272** [comment]
yeah, heres a ss 
image

**Comment by damithc** [comment]
@Mcheung7272 I suggest we retain the `Alternative N` wording suggested in the issue, to emphasize that the two suggested are alternatives (not steps).

**Comment by Mcheung7272** [comment]
sounds good. I'll add it in

**Comment by Mcheung7272** [comment]
Hows this?

image

**Comment by damithc** [comment]
@Mcheung7272 I'm fine with this version. Although I'm not sure if `... responses of past sessions.` or `... responses to past sessions` is more appropriate.

**Review by ziqing26 — APPROVED** [review]
LGTM, thanks for the PR! Just kindly update the branch

**Pull request merged**
