### PR TITLE
[#12048] Add database unique constraints and length changes

### PR DESCRIPTION
**Pull request by FergusMok**
Part of https://github.com/TEAMMATES/teammates/issues/12048

Added some unique constraints to SQL, and increase the length of some fields as part of data migration

### CODE REVIEW

**Comment by NicolasCwy** [comment]
We might need to generate a liquibase changelog for this let me check

**Review by cedricongjh — APPROVED** [review]
LGTM!

should we add in the deadline extensions unique constraint as well in the PR?

**Comment by FergusMok** [comment]
@cedricongjh Added the deadline extension

Awaiting confirmation about the field length, and will be adding changelog for beta 7 to the PR once confirmed

**Review by cedricongjh — APPROVED** [review]
LGTM!

**Comment by mingyuanc** [comment]
Not required anymore

**Pull request closed without merging**
