### PR TITLE
[#10711] Link to Feature Overview in CONTRIBUTING.md do not lead to the correct webpage

### LINKED ISSUE #10711: Link to Feature Overview in CONTRIBUTING.md do not lead to the correct webpage
Link to Feature Overview in CONTRIBUTING.md do not lead to the correct webpage

- **Environment**: Github LIVE

**Steps to reproduce**

1. Go to https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md#know-the-productproject
2. Click on _Feature Overview_

**Expected behaviour**
Get directed to [Feature Overview](https://teammatesv4.appspot.com/web/front/features) page

**Actual behaviour**
Gets **Error: Not Found**

### PR DESCRIPTION
**Pull request by Wimpzer**
Fixes #10711

### CODE REVIEW

**Comment by jtankw3** [comment]
LGTM

**Review by jtankw3 — APPROVED** [review]
LGTM

**Review by wkurniawan07 — COMMENTED** [review]
@Wimpzer thanks for reporting and fixing the issue!

There are a few more outdated links in this document as well as in `.github/SUPPORT.md`, can you take some time to fix them all? All of the outdated links end with `.jsp`.

**Comment by Wimpzer** [comment]
> @Wimpzer thanks for reporting and fixing the issue!
> 
> There are a few more outdated links in this document as well as in `.github/SUPPORT.md`, can you take some time to fix them all? All of the outdated links end with `.jsp`.

Hi wkurniawan07,

Let me create a new issue and look through the documents as to keep the branch focused on the mention in issue.

**Comment by Wimpzer** [comment]
> > @Wimpzer thanks for reporting and fixing the issue!
> > There are a few more outdated links in this document as well as in `.github/SUPPORT.md`, can you take some time to fix them all? All of the outdated links end with `.jsp`.
> 
> Hi wkurniawan07,
> 
> Let me create a new issue and look through the documents as to keep the branch focused on the mention in issue.

@wkurniawan07 As to avoid creating changes in this PR and issue I created a new Issue #10714 and created new PR for this one covering the other three instances of .jsp pages.

**Review by wkurniawan07 — APPROVED** [review]
LGTM

**Pull request merged**
