### PR TITLE
Instructor: view course: change Delete button color to red #7841

### LINKED ISSUE #7841: Instructor: view course: change Delete button color to red
Changing the colour of the delete button in Instructor: edit course page. And it would be attractive and readable. 

screenshot 810

### PR DESCRIPTION
**Pull request by stanislous**
Fixes #7841

Changed the colour of the delete button only in course details page.

### CODE REVIEW

**Comment by stanislous** [comment]
@damithc can I edit the feedback session page also or open a new issue?

**Comment by damithc** [comment]
> can I edit the feedback session page also or open a new issue?

Let's finish this one first. :-) When this is merged, we can create a new issue for the sessions page.

**Comment by damithc** [comment]
BTW, why do you have two PRs open fort his issue?

**Comment by stanislous** [comment]
@damithc, Because they are two branches. I couldn't assign new branch to the old branch's pull request.

**Comment by whipermr5** [comment]
@stanislous Do close the one linked to the old branch that you do not want.

**Comment by stanislous** [comment]
@damithc, Can you review this?

**Comment by VamsiSangam** [comment]
Hi @stanislous , could you post a screenshot of your UI enhancement?

**Comment by stanislous** [comment]
screenshot 794

**Comment by VamsiSangam** [comment]
Let us clarify the scope of the issue first. According to the issue, the proposed change is to make only this button red, right?



Or do you have something else in mind @stanislous ? What were all the buttons which you were going to change?

**Comment by stanislous** [comment]
@VamsiSangam, I mentioned above is all the delete delete buttons turn to red. But then @damithc asked me to change other delete buttons to red in a seperate issue.

**Comment by whipermr5** [comment]
@stanislous You can edit your issue to widen its scope so as to prevent confusion :)

**Comment by stanislous** [comment]
@whipermr5 it was already done by @damithc.

**Comment by whipermr5** [comment]
@stanislous Oops I misread; you should edit #7841 to narrow its scope. While @damithc has helped you edit the issue title, your issue description is still misleading - it still talks about changing the colour of "all delete buttons" and refers to the screenshot as an "example".

**Comment by stanislous** [comment]
@whipermr5 it is done. :-)

**Comment by whipermr5** [comment]
@stanislous Looks good now! I'll wait for @VamsiSangam to give an initial review first.

**Pull request merged**
