### PR TITLE
[#11779] Fixes hide deadline link

### LINKED ISSUE #11779: Hide the "Individual Deadline Extension" link when creating a new session
- Production environment 
- Right now when the instructor clicks the button to add a new session, they can still click on the link to make individual deadline extension before actually clicking "create feedback session". However, because the session is not created yet, when they click on the link, they will get an error message. 
Screen Shot 2022-05-10 at 12 54 14 AM
Screen Shot 2022-05-10 at 12 54 24 AM
- Solution: hide the link so that they cannot click on it until they have created the session.

### PR DESCRIPTION
**Pull request by hoanglan21**
Fixes #11779 

Changed the html file so that the link does not show up while creating a new session

### CODE REVIEW

**Review by fsgmhoward — CHANGES_REQUESTED** [review]
See comments in the original issue.

**Comment by hhdqirui** [comment]
@hoanglan21 reminder on this PR. Please fix the CI before we proceed to review. Thanks.

**Comment by fsgmhoward** [comment]
@hoanglan21 Hi is there anything blocking your progress? Please be reminded for this open PR. Tell us if any help is necessary for you to continue.

**Comment by wkurniawan07** [comment]
Closing due to inactivity for a long period. Feel free to reopen/request for reopen when ready to resume the work here.

**Pull request closed without merging**
