### PR TITLE
Instructor: home page: combine 'view results' and 'publish results' buttons #7294

### LINKED ISSUE #7294: Instructor: home page: combine 'view results' and 'publish results' buttons
Current:
image

Suggested:
Combine the two buttons like this (similar to the `Remind` button):
`Results`
  -`View`
  -`Publish`
Furthermore, clicking the `Results` button directly can be considered as `View Results`

Justification:
Saves space (especially because we might add more results-related buttons in future such as 'resend results link').

### PR DESCRIPTION
**Pull request by amarlearning**
Fixes #7294
 
Combined the two buttons as suggested by @damithc  (similar to the Remind button):
`Results`
`-View`
`-Publish`
Image

screenshot of the updated UI
screenshot from 2017-05-13 22-54-18

### CODE REVIEW

**Comment by damithc** [comment]
Should be `View Results`?

**Comment by amarlearning** [comment]
@damithc corrected.

**Comment by thenaesh** [comment]
@amarlearning Remember to run Godmode on the failing tests.

**Comment by amarlearning** [comment]
@thenaesh did the same still, some tests are failing.
I change the `isGodModeEnabled = true` in this file [BaseUiTestCase.java](https://github.com/TEAMMATES/teammates/blob/e587b4300bf06afe8c4eb322381f3eb29636683c/src/test/java/teammates/test/cases/browsertests/BaseUiTestCase.java) and then ran this command via CLI `./gradlew ciTests -Pgodmode=true`

Please correct me if i did anything wrong

**Comment by amarlearning** [comment]
Opened new [PR](https://github.com/TEAMMATES/teammates/pull/7312)!

**Pull request closed without merging**
