### PR TITLE
InstructorFeedbackEditPage: include question type help in lightbox #8431

### LINKED ISSUE #8431: InstructorFeedbackEditPage: include question type help in lightbox
**Description of feature/enhancement**
image
At the moment, clicking the info button (shown above) when trying to add a new question in the Edit Feedback Session screen opens `instructorHelp.jsp#fbQuestionTypes` in a new tab. While this is workable, it might be more beneficial to instructors' workflow to have information on question types available on the same page, for example in a lightbox as shown below:
peek 2018-02-10 15-45

**Justification**
Instructors will benefit from not having to navigate away from the page to learn more about question types. The current info button opens a new tab in the background. This impedes workflow as the user must navigate away from the page, read the information, then navigate back to the page to continue. Users may also get distracted by the (vey comprehensive) information available on `instructorHelp.jsp`.

Moreover, we are already using lightboxes in other parts of the site when displaying additional information; we should standardize what behaviour is expected when the user clicks on the information icon (i.e. lightbox vs. new tab).

To be fair, the question type help is quite long and elaborate, and may not fit well in a lightbox -- we may want to look into including a condensed version instead.

### PR DESCRIPTION
**Pull request by wenmogu**
Fixes #8431 

**Outline of Solution**

By extracting the info for each question type into tags, and use those tags in the question-type-help-modal tags in the `newQuestionForm.tag`.
Illustrations are given in the [comments](https://github.com/TEAMMATES/teammates/issues/8431#issuecomment-367429998).

One big trouble I encountered is the duplication of id, class and names of the elements inside the question help tags (fig 1) and the question frames in the `instructorFeedbackEditPage` (fig 2). My solution appends the question-type-help-modal tags at the end of `newQuestionForm.tag` which the `instructorFeedbackEdit.js` works on. This leads to the problem of the js code selects elements in the help tags (which should not happen).

fig 1
capture1

fig 2
capture2

One way of solving this problem is to add/delete identifiers of those elements in the help tags to distinguish them from the question frame elements (that is why i added `questionhelp-` in front of some element identifiers). However, to me this doesn't seem sustainable as in the future when other contributors trying to edit the UI of the edit page/the help page, they have to take extra care to avoid the error above (which is not easy to spot...). Moreover, (i hope i m not overthinking) I think the solution above would hinder the implementation of what @whipermr5 envisioned [here](https://github.com/TEAMMATES/teammates/issues/7604#issuecomment-311557171). So currently I am in need of guidance on how to get out of this dilemma. **HELP orz**

PS: i havnt changed the expected results for the UI tests yet as I think it would be better for me to solve this problem before I turn on GodMode

### CODE REVIEW

**Comment by wenmogu** [comment]
@joanneong please review. thxx!

**Comment by joanneong** [comment]
@wenmogu Thanks for the ping. In the meantime, do make sure that you are passing Travis first. On a side note the +6189, -5751 looks quite intimidating... :o

**Comment by whipermr5** [comment]
> His idea seems to simply be about the ability to extract the elements so that we do not have to keep updating the help page itself, which I feel is something that you have done here in this PR. But perhaps @whipermr5 may have differing opinions?

Actually, I meant that both the dummy question frame in the help page/modal and the actual question frame in the edit page should use the same tag, so that if the question frame UI is edited, the help page/modal is automatically updated. This was the context: https://github.com/TEAMMATES/teammates/pull/7275#issuecomment-307577692

**Comment by wenmogu** [comment]
This pr is currently not a feasible solution due to the complications behind the structure of TEAMMATES UI : the mixing of HTML template specific to question types with JSP.

**Pull request closed without merging**
