### PR TITLE
[#10480] Highlight text on search in Admin Search Page

### LINKED ISSUE #10480: Instructor/admin search/help page: Search text is highlighted yellow in V6 but not in V7

### PR DESCRIPTION
**Pull request by tau-bar**
Fixes #10480. This PR also extends #11952.

**Outline of Solution**
This solution uses the `SearchTermsHighlighterPipe` I created in PR #11952. 

Partial matches:
image

Exact phrase match:
image

Mixture of search terms and exact phrases:
image

### CODE REVIEW

**Comment by tau-bar** [comment]
I'm not sure why `AdminSearchPageE2ETest` is faliing. The test has passed multiple times on my local device, with `test.search.active` attribute in `src/e2e/resources/test.properties` set to true.

image

**Comment by ypinhsuan** [comment]
It might be due to the different testing environments. Just to check, what OS and browser are you using? The e2e workflow on github uses Firefox and Ubuntu.

**Comment by tau-bar** [comment]
@ypinhsuan I'm using Firefox on Windows. How should I proceed to debug this in that case?

**Comment by ypinhsuan** [comment]
Unfortunately I am developing windows as well so I can't help to test this. Let's see if other developers can help with this.

I took a brief look at your PR and I am guessing that this [function](https://github.com/TEAMMATES/teammates/blob/a1a7678b3f9e113c86f6cc360543a96a3518a09b/src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java#L141) is returning `null` because the highlighter pipe is transforming parts of the innerHtml content inside a `<span>` tag. But it is weird that the test is passing on your machine as I don't think this is an OS issue.

**Comment by zhaojj2209** [comment]
Here's a more detailed error message for the failed test:
image

When tracing the code execution, the reason behind the NPE is because `getStudentRow` in `verifyStudentRowContent` is unable to identify the row, because the text that is being used to search for the row is now wrapped in the `highlighted-text` span. As an example:

String used to look for the row: `tm.e2e.ASearch.course1 [Section 1] (Team 1.1)`
Actual string returned by getting the innerHTML: `tm.e2e.ASearch.<span class="highlighted-text">course1</span> [Section 1] (Team 1.1)`

Looks like changes will need to be made to the `getStudentRow` function in `AdminSearchPage.java` in order to fix this.

**Comment by zhaojj2209** [comment]
@tau-bar Any updates on this PR? Let me know if you need more help with debugging the E2E tests.

**Comment by tau-bar** [comment]
@zhaojj2209 Thanks for the help! Apologies I was occupied and was unable to work on this PR. Will try to fix the E2E tests now!

**Comment by tau-bar** [comment]
@zhaojj2209 Currently the failing E2E test is here:


```
Failed suite [Failed suite [Failed suite [Failed suite [e2e-tests]]]] > e2e-tests(failed)(failed)(failed)(failed) > teammates.e2e.cases.FeedbackSubmitPageE2ETest > testAll FAILED
    org.openqa.selenium.TimeoutException at FeedbackSubmitPageE2ETest.java:104
        Caused by: org.openqa.selenium.NoSuchElementException at FeedbackSubmitPageE2ETest.java:104
```

Could you provide me with some guidance on how to debug this type of error? Thank you!

**Comment by zhaojj2209** [comment]
> @zhaojj2209 Currently the failing E2E test is here:
> 
> ```
> Failed suite [Failed suite [Failed suite [Failed suite [e2e-tests]]]] > e2e-tests(failed)(failed)(failed)(failed) > teammates.e2e.cases.FeedbackSubmitPageE2ETest > testAll FAILED
>     org.openqa.selenium.TimeoutException at FeedbackSubmitPageE2ETest.java:104
>         Caused by: org.openqa.selenium.NoSuchElementException at FeedbackSubmitPageE2ETest.java:104
> ```
> 
> Could you provide me with some guidance on how to debug this type of error (`selenium.NoSuchElementException`)? Thank you!

This is one of the E2E tests that occasionally need multiple runs to pass. I will help to monitor the E2E test runs and will proceed to review once all of the tests pass.

**Review by zhaojj2209 — APPROVED** [review]
LGTM!

**Comment by tau-bar** [comment]
@zhaojj2209 Thank you!

**Review by ypinhsuan — APPROVED** [review]
LGTM

**Pull request merged**
