### PR TITLE
[#11947] Improve UI of Error Toasts

### LINKED ISSUE #11947: Improve UI of Error Toasts
- **Environment**:  `master` branch at commit 39192f4

**Description of feature/enhancement**
Propose to update the front-end to facilitate error messages to be represented as multiple toasts rather than a single one.

**Justification**
Currently if there are multiple error messages, it appears in a single toast in certain cases (e.g. where the back-end returns an array of error messages). Since the messages are displayed as an array it reduces the legibility/understanding of errors. Furthermore, the users may also view it as a bug since it seems like the array of messages is returned without being processed. 

Image below shows an instance where there are three error messages:
image

### PR DESCRIPTION
**Pull request by thikhinab**
Fixes #11947 

**Outline of Solution**
The back-end:
- Created `ErrorMessageFormatter` to format list of error messages that could be parsed from the front-end.
- Updated three classes (`CreateFeedbackQuestionAction`, `SubmitFeedbackResponseAction`, `UpdateFeedbackResponseAction`) where the Lists of messages are used to create error responses.

The front-end:
- Updated the `Toast` interface to facilitate `string` arrays.
- Updated the `StatusMessageService` to clean and parse the back-end error response.
- Updated the `Toast` component to render multiple error messages as bullet points.

**UI**
image

**Shortcomings & Alternatives** 
Future developers must be aware to use `ErrorMessageFormatter` instead of calling `List::toString()`. An alternative is to ensure that there is  a class such as `ErrorMessageList` embedded at points where error messages outputted. This would ensure that all error messages will follow the desired format. However this alternative will require to refactor the entire validation process and exception handling.

### CODE REVIEW

**Comment by damithc** [comment]
I'm OK with the proposed UI. 👍

**Comment by samuelfangjw** [comment]
> Future developers must be aware to use ErrorMessageFormatter instead of calling List::toString()

If I may ask, what is the behaviour if this is not followed? (Using List::toString() instead)

**Comment by thikhinab** [comment]
@samuelfangjw `List::toString` will output the error message as follows: `[ error_msg1, error_msg2, ... ]` since the delimiter is a `,` it makes it harder to parse in the front end (as error messages itself can contain the delimiter.). Moreover, the the back-end is currently inconsistent on whether it sends the error with brackets `[...]` or without. Instances where there is only a single error message, simply the string passed as param to the `Error` thrown. 

A solution to deal with it (where the developer is not responsible  for using`ErrorMessageFormatter`)  would need to refactor the back-end such that Error messages are abstracted out into a different class as suggested under alternatives.

**Comment by samuelfangjw** [comment]
I'm not comfortable with the proposed solution at the moment.

I'll preface this by saying that you are right when you say that the current error messages could be improved. The backend should be providing reasonable error messages, i.e. not array::toString().

However, the backend really should not be specifically formatting error messages for a specific consumer, the frontend in this case. Think about it this way, there shouldn't be a way for an error message sent on the backend to break/affect the formatting on the frontend, however improbable. If we do it this way, the developers working on the backend also have to be conscious of how any changes will affect the frontend as well. I'm not saying this cannot be done or there's no examples of strong coupling in the current codebase, I'm saying this is something we should try to avoid unless absolutely necessary.

There's also an issue of consistency. The fact that the format of the error message in the response and the way it should be parsed differs depending on the endpoint doesn't sit well with me. In my opinion, this is a short sighted workaround to this issue and the tech debt from this will cause more issues in the future.

The alternative suggested is definitely a cleaner solution, and one that I have been considering for awhile now. However, I'm not keen on rushing this out at the moment. Any solution that affects error handling has to be well thought out and designed in a way that is consistent yet extensible enough to handle all the different use cases in our application.

A simple compromise I would like to explore: We can try formatting the error messages by joining the array using newlines instead. This is more reasonable than the current toString implementation and should display nicely enough on the frontend within the toast. It's not as pretty as a bulleted list, but i suspect it might be enough for our use case.

Thoughts?

**Comment by thikhinab** [comment]
@samuelfangjw I understand your concerns. I agree with you. My intentions were to avoid large scale refactor of the Error Messaging in the back-end, which should preferably be solved under a different issue since it is more general and have direct impact on multiple points of the back-end. Thank you for pointing this out. I am interested in working on you idea for the compromise. I think it is an elegant way to solve the issue without major refactoring.  Furthermore, this would also solve the issue of inconsistency on the manner which the front-end deals with error messages.

**Comment by thikhinab** [comment]
Updated UI:
image

**Comment by fsgmhoward** [comment]
@thikhinab Any updates for this PR?

**Comment by thikhinab** [comment]
@fsgmhoward I believe that the proposed solution is completed and is pending review. However, I need to examine why the E2E tests are failing

**Comment by fsgmhoward** [comment]
@thikhinab It can fail randomly for many reasons. You can check whether it is due to your modification. I have updated this PR as to be reviewed.

**Comment by thikhinab** [comment]
I will try to take a look at this again this week

**Comment by fsgmhoward** [comment]
@thikhinab Could you run a local check and see if it fails or not?

**Comment by thikhinab** [comment]
@fsgmhoward I tried running again locally, this time the test worked:
image

**Comment by zhaojj2209** [comment]
E2E tests are passing on my local machine as well, which makes this difficult to debug. One way to debug this without spamming the PR itself would be to enable GH actions on your own forked repo, duplicating this branch, and making a PR to your own repo's master branch. Once the PR is up, you can make edits to your branch (e.g. removing changes incrementally to see which change caused the E2E tests to fail) and wait for the E2E test results on GH actions to see if they pass.

Maybe you can start by removing the change to `toast.component.scss` and checking if the E2E tests pass on GH actions after removing the change.

**Comment by thikhinab** [comment]
@zhaojj2209 Thank you for the verifying this! I will set up GH actions on the fork and tryout the workflow you mentioned.

**Comment by zhaojj2209** [comment]
@thikhinab Any updates on this PR? Let me know if you need help debugging the E2E tests.

**Comment by thikhinab** [comment]
@zhaojj2209 It would be great if I could get your assistance.

**Comment by zhaojj2209** [comment]
> After removing the CSS styling, E2E tests have passed several times

Then I guess my suspicions were correct; it seems that `white-space: pre-line` causes the E2E tests to fail for reasons that are beyond me. Can you try changing the CSS `white-space: pre-wrap` instead? If `pre-wrap` also causes E2E tests to fail, then I think removing the `white-space` property can also be an acceptable compromise.

**Comment by thikhinab** [comment]
@zhaojj2209 Understood, will update.

**Comment by thikhinab** [comment]
Since PR failing E2E tests even with the new changes, I would close the issue until the issue is resolved or alternative is found.

**Pull request closed without merging**
