### PR TITLE
Instructor: view results: 'expand' button collides with the status message #7485

### LINKED ISSUE #7485: Instructor: view results: separate 'expand' button from status message
v5.106
image

Can use `InstructorFeedbackResultsPageUiTest#testViewPhotoAndAjaxForLargeScaledSession()` to observe this problem

### PR DESCRIPTION
**Pull request by adityavhegde**
Fixes #7485 

Edits to `instructorFeedbackResultsTop.jsp:`
* added a `<div>` tag around the status message tag
* added inline style, to align as expected 
* extra `<br>`'s were removed. There was gap between Expand all button and the questions (Question panel). 

Edits to `filterPanel.tag`
* the form element that encloses the entire tag file, had a bottom margin, which has been removed
* the Expand/Collapse element (line 97) has been given extra top margins for formatting purposes

`byQuestionResults.tag` and `bySectionPanels.tag` had some `<br>` which were removed for formatting purposes.

expand-collapse-changes

This is how, the page would appear normally: 
image

### CODE REVIEW

**Comment by HirdayGupta** [comment]
Hi @adityavhegde, just an initial comment. Will take a closer look and let you know of more suggestions soon.

- Seeing the changes you have made to the test HTML files in commit 2960504, it seems you have copied the changes to the test files from your ongoing PR #7612 into the test files in this PR (although, I am not sure of exactly what you did to get the changes in 2960504, so if my assumption is wrong please correct me). As is standard practice, one PR only deals with one issue, and no matter which of your PRs gets merged first, the required changes to the test files will be committed to `TEAMMATES/master` and then you will merge those updates into the other PR's branch. I think maybe it would be best if you reverted changes made in 2960504 and fixed the build error shown in [this Travis error log](https://travis-ci.org/TEAMMATES/teammates/builds/248014840?utm_source=github_status&utm_medium=notification) (at commit c30d0a7) by running god mode on the failing tests.

**Comment by adityavhegde** [comment]
@HirdayGupta Yes, I was surprised, how those changes crept in. Nonetheless, there are some problems apart from this, that need inspection.

**Comment by HirdayGupta** [comment]
@adityavhegde perhaps you made some errors in your git commands? Can you remember the exact steps you took before you committed 2960504? This might give us an idea of steps to take to prevent such unwanted changes in the future. 

Either way, the faulty changes only seem to be there in 2960504.Revert it for now and then try and identify the steps you took before you committed it, which should help to prevent such unexpected changes in the future. You will also need to inspect `FeedbackRankQuestionUiTest` and find out what changes you have made that are causing the `assertionError` and then update the test accordingly.

**Comment by adityavhegde** [comment]
@HirdayGupta I have no clue. Judging my terminal history, after pushing changes to PR #7612, I checked out to the branch working on current PR, ran the CI tests, and found some new files. The CI tests, seem to have changed files from PR#7612. I don't suppose there can be such absurd changes. In absence of other history, I can't really comment, what's gone wrong.

Here is what the changes looked like after CI test. I wonder, how I pushed them in the first place. 
image

**Comment by HirdayGupta** [comment]
@adityavhegde are you running the CI tests using eclipse or using terminal?

**Comment by adityavhegde** [comment]
@HirdayGupta terminal.

**Comment by HirdayGupta** [comment]
Alright. Seeing your steps, there are a couple of possibilities as to how this crept in. 
- First, you should note that UI tests get HTML from the browser running the test, so you need to ensure that caching is switched off on the browser you use for the tests. 
- Second, if you only ran `./gradlew ciTests` after switching your branch, you essentially ran the tests on the local dev server instance of your previous branch which would also explain the unexpected changes. You should stop your dev server and restart it after switching branches. And for a large project like TEAMMATES, give some time for the directories to refresh.

**Comment by adityavhegde** [comment]
> Second, if you only ran ./gradlew ciTests after switching your branch, you essentially ran the tests on the local dev server instance of your previous branch which would also explain the unexpected changes. You should stop your dev server and restart it after switching branches. And for a large project like TEAMMATES, give some time for the directories to refresh after switching branches.

Ahh. Missed that in a hurry ( *blames multitasking*)

**Comment by HirdayGupta** [comment]
@adityavhegde Ah, the perils of parallel open PRs. 😝
Now that we've figured out how the unexpected changes came in, you can go ahead and revert 2960504, and proceed to fix the build error from https://github.com/TEAMMATES/teammates/commit/c30d0a77ba6e60ad2b298315a824ee9e52dc6e38. (Fixing that seems like a simple god mode re-run from the surface. I may be wrong though).

**Comment by adityavhegde** [comment]
@HirdayGupta yes, reverted back to the commit.

**Comment by damithc** [comment]
The button should be below the status message rather than above it? It's odd to insert the status message between the button and the panels. :thinking:

**Comment by adityavhegde** [comment]
@damithc coming to think of it, I agree with you. Should I close this pull request ?

**Comment by HirdayGupta** [comment]
@adityavhegde you don't need to close a PR when changes are requested. Just make the changes requested by @damithc and commit them :)

**Comment by adityavhegde** [comment]
@HirdayGupta For the functionality that is requested, I'd have to rollback to a state before this PR, and make fresh changes, which logically branches into a different set of changes. Are you sure, I should stick to this PR ?

**Comment by HirdayGupta** [comment]
@adityavhegde I guess then it's fine either way. Up to you. Unless @damithc has would recommend one approach over the other?

**Comment by damithc** [comment]
@adityavhegde you can rollback to an earlier state, add new commits, and force push to the same branch/PR. But it's ok if you want to close this and start a new PR too.

**Comment by adityavhegde** [comment]
Some of my files after CI test end up showing like this. The god mode is enabled.
The process I generally follow is > re-start dev server -> run build -> run lint -> ciTests
I also double checked that I am on the same branch. 

Can anyone explain, what I am missing ?

image

**Comment by HirdayGupta** [comment]
@adityavhegde I experienced the same issue a while ago because I had forgotten to set my `-Duser.timezone=UTC` VM argument. However, I don't see why this should be an issue after #7520 was closed by @whipermr5 in #7521. 

First, just update your branch and try rerunning godmode to see if it goes away. If that does not work then perhaps you can try setting this argument and running the tests in god mode from Eclipse/IntelliJ as explained  [here](https://github.com/TEAMMATES/teammates/commit/42aecbaf7ccd7c5d5ae221b58fd8b1e56b0e61b6#diff-1bf07101845de6da98f1c948b82c5ce0) (You'll have to read the red (omitted) part of the diff of the file `development.md`). Let's also ask @whipermr5 for his input.

**Comment by adityavhegde** [comment]
Closing this pull request, since I am opening a new one.

**Pull request closed without merging**
