### PR TITLE
feedbackSubmissionsEdit.es6: remove unnecessary if condition #8035

### LINKED ISSUE #8035: feedbackSubmissionsEdit.es6: remove unnecessary if condition
In the `validateMsqQuestions()` method of `feedbackSubmissionsEdit.es6`, an `if` statement has been put near [this line](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/feedbackSubmissionsEdit.es6#L656) -

```js
if (numOfSelectedChoices === 1
        && $(`input[name="responsetext-${qNum}-${recipientIndex}"][value=""]`).prop('checked')) {
    // Selecting "None of the above" as the only option is a valid response
    recipientIndex += 1;
    continue;
}
```

This `if` condition was meant for selecting `None of the above` options when min/max options for MSQ questions were enabled.

According to the current implementation, we are not even displaying `None of the above` option when min select-able options is enabled, this `if` condition can be removed safely.

### PR DESCRIPTION
**Pull request by jnisky**
Fixes #8035 
*This is my first attempt at an open source contribution*

### CODE REVIEW

**Comment by VamsiSangam** [comment]
Hi @jnisky ! I believe the Travis Build failed due to an unrelated issue, could you please close this PR and re-open it immediately? This will cause the Travis build to restart itself.

**Comment by jnisky** [comment]
Ok VamsiSangam, I've closed and reopened this PR.

**Comment by VamsiSangam** [comment]
@jnisky please have a look at our [conventions while contributing](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr).

@whipermr5 ready for review by a senior dev.

**Comment by jnisky** [comment]
Is the title change what you were looking for in referencing the contribution conventions? I appreciate your patience as this is my first ever contribution.

**Comment by VamsiSangam** [comment]
Yes the title of this PR should ideally be `feedbackSubmissionsEdit.es6 : remove unnecessary if condition #8035`. Refer to that document for more conventions. Take your time, no hurry :wink:

**Comment by VamsiSangam** [comment]
Just noticed, you did all your changes in your fork's master branch. Ideally you should create a separate branch and make changes there, then open a PR from the new branch.

**Comment by whipermr5** [comment]
@jnisky Do take note of what @VamsiSangam said for your future PRs. I've helped you fix the title for now since it's your first contribution.

Also, may we have your full name for inclusion into the contributors' list? :)

**Comment by jnisky** [comment]
You're welcome! My name is Jordan Niskanen.

**Pull request merged**
