### PR TITLE
Rename HTML files in src/test/resources/pages that start with upper case #5103

### LINKED ISSUE #5103: Rename HTML files in src/test/resources/pages that start with upper case
The files in `src/test/resources/pages` should all start with a lower case. There are some `Instructor*.html` that don't follow it.

### PR DESCRIPTION
**Pull request by rajivjhaimin**
Fixes #5103

### CODE REVIEW

**Comment by kanghj** [comment]
@rajivjhaimin, can you sync and fix the merge conflicts from master?

**Comment by bamboo3250** [comment]
@kanghj I think we have already had another PR about this issue #5106

**Comment by kanghj** [comment]
Let's put this on hold then, we can proceed on with this pr if that doesn't get fixed after a while. If that's completed then we can close this. @rajivjhaimin, in future avoid issues that are already in the middle of getting xied

**Comment by wkurniawan07** [comment]
@rajivjhaimin you have done another `d.firstTimers` issue which is #5117. Since one contributor is limited to one such issue, I'm going to close this one. You are free to contribute more, in particular issues marked `d.Contributors`.

**Comment by rajivjhaimin** [comment]
@wkurniawan07 @kanghj  Sure Sir. I am working on d.contributor labelled issue. I will keep in mind , to avoid issues which have been labelled s.ongoing or in review.

**Pull request closed without merging**
