### PR TITLE
[#10368] Instructor home page: Fix changing sort by results in duplicate tables

### LINKED ISSUE #10368: Instructor home page: changing sort by results in duplicate tables
**Steps to reproduce**

1. Go to instructor home page
2. With the tabs expanded, change sort by of the courses
3. Try to collapse the tab for any course (the tab does not get collapsed)
4. Expanding the tab creates a duplicate table

image

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #10368 

`ngIf` seems to be detached from the correct element after reordering.

**Outline of Solution**

 Deepcopy model before sort

### CODE REVIEW

**Comment by niqiukun** [comment]
While this is not directly related to this issue, I noticed that after changing the sorting of courses, the first three tabs will be opened together with previously opened tabs. So after opening the page and changing the sorting method there are actually more than three tabs expanded. Just want to check if this is the intended behaviour. @xpdavid @wkurniawan07

**Comment by damithc** [comment]
> While this is not directly related to this issue, I noticed that after changing the sorting of courses, the first three tabs will be opened together with previously opened tabs. So after opening the page and changing the sorting method there are actually more than three tabs expanded. Just want to check if this is the intended behaviour. @xpdavid @wkurniawan07

I think it's best if we don't auto-expand the top three panels after sorting. It saves cost (?) plus we don't know if the user is interested in seeing the top 3 panels (maybe she is interested in the panels at the bottom instead). But OK to leave as it is if this requires lot of extra work.

**Comment by wkurniawan07** [comment]
> I think it's best if we don't auto-expand the top three panels after sorting

No, this is the actual behaviour in V6.

> we don't know if the user is interested in seeing the top 3 panels

If we follow this logic, we wouldn't have to auto-expand any panel to begin with.

**Comment by damithc** [comment]
> If we follow this logic, we wouldn't have to auto-expand any panel to begin with.

The logic of the initial auto-expansion is that the user is likely to be interested in the most recent courses. That doesn't apply to other sorting orders.

**Comment by damithc** [comment]
> > I think it's best if we don't auto-expand the top three panels after sorting
> 
> No, this is the actual behaviour in V6.

It's fine to leave as it is. Certainly not something to worry about at this time.

**Pull request merged**
