### PR TITLE
Separate common.datatransfer package into sub-packages #6355

### LINKED ISSUE #6355: Separate common.datatransfer package into sub-packages
`teammates.common.datatransfer` is presently too cluttered and could be tidied up by breaking into sub-packages based on these categories:
- `.attributes`: the entity attributes, essentially those which can connect to the persistable entities.
- `.questiontypes`: the classes related to feedback questions and responses for different question
- `.bundles`: everything else (for the lack of more fine-tuned categories). Hopefully, everything in this sub-package is pure data structures: just classes containing public class variables without any methods (and thus naturally exempted from testing).

Other plausible categorisations are acceptable for consideration.

### PR DESCRIPTION
**Pull request by samsontmr**
Fixes #6355 

**Problem**
`teammates.common.datatransfer` is presently too cluttered.

**Solution**
Move files ending with Attributes into .attributes sub package, files related to Questions, Responses into .questions sub package.

### CODE REVIEW

**Comment by whipermr5** [comment]
You need to update the class references in the tag files ([example](https://github.com/samsontmr/teammates/blob/c42a761fbba7c0913ec740d8b7e31e433d7b6f32/src/main/webapp/WEB-INF/tags/student/feedbackResults/feedbackSessionDetailsPanel.tag#L4))

**Comment by samsontmr** [comment]
@junhaoyap ready for review

**Comment by junhaoyap** [comment]
@wkurniawan07 I believe you self assigned this

**Comment by samsontmr** [comment]
Something went really wrong after I updated the branch. Closing this and creating a new pr at #6453

**Pull request closed without merging**
