### PR TITLE
Instructor: home page: remind particular students: update all sorting icons when a column is sorted #7448

### LINKED ISSUE #7448: Instructor: home page: remind particular students: update all sorting icons when a column is sorted
When we select 'remind particular students' on instructor home page, a list of students gets populated through ajax request. When we try to sort the columns by selecting on headers, then previously sorted column icon doesn't reset.

issue

### PR DESCRIPTION
**Pull request by shubham49**
Fixes #7448 

This problem was for 'remind particular students', 'instructor home' and 'instructor sessions'.
Removed unnecessary classes on the headers.

Is this right approach or should I modify sorting method accordingly?

### CODE REVIEW

**Comment by shubham49** [comment]
Ready for review.

**Comment by thenaesh** [comment]
@shubham49 Remember to fix the merge conflicts. The HTML ones can be fixed easily by running godmode again.

**Comment by shubham49** [comment]
I just wanted to confirm if this is correct approach (i.e. to remove unnecessary classes) or I should modify sorting function.

**Comment by thenaesh** [comment]
I think this approach is fine. :)

**Comment by shubham49** [comment]
I just found one thing in `feedbackSessionsTable.tag`
On removing the class `course-id-table-width` page doesn't remain responsive.
image

**Comment by thenaesh** [comment]
@shubham49 Let's put this on hold for now. I'm in the process of modifying the `toggleSort` function significantly as part of another issue, and I think this problem will be solved in the process too.

**Comment by shubham49** [comment]
No problem :smile:

**Comment by thenaesh** [comment]
This issue has been fixed by #7476.

**Pull request closed without merging**
