### PR TITLE
Student Profile: add a 'Upload/Edit Photo' tooltip #8589

### LINKED ISSUE #8589: Student Profile: add a 'Upload/Edit Photo' tooltip
This tooltip will show size and formats of a photo. It would be easier for a student to look for available photos to submit.

There is a similar tooltip (shown in the screenshot below), but it also can be changed. For example, the new tooltip will look like this 'Upload a profile picture. Max size: 5MB .png .jpg'.
profile picture

### PR DESCRIPTION
**Pull request by jimmy51997**
Fixes #8589 

**Outline of Solution**

The issue was solved by updating the Const.java file in the path "E:\Git Projects\teammates\src\main\java\teammates\common\util". In the file the value of the constant STUDENT_PROFILE_PICTURE in line 415 was changed to the required string showing the required specs of the image.

### CODE REVIEW

**Comment by jimmy51997** [comment]
Why did this happen @sukanta-27  @damithc  @Crphang ??

**Comment by bqnguyen94** [comment]
@jimmy51997 You can take a look at the Travis log and see what went wrong, which in this case is a UI test. I suggest you follow our [dev guide](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#testing) for the testing process. For this issue [this guide](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) will be handy as well.

Also, please strictly follow our PR naming convention as detailed [here](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr). I have fixed it for you this time.

**Comment by bqnguyen94** [comment]
You can click on `Details` below to see the Travis log.

**Comment by tanhengyeow** [comment]
@jimmy51997 As mentioned by @bqnguyen94, please follow the resources that are linked to have a better idea on how to fix the issue you are currently facing.

To provide you with a little assistance, since you are making a UI change, HTML pages that are produced with your updated code would **not** match with the previous HTML pages used for testing, thus the errors shown in the Travis error log. 

To save the trouble of manually updating every HTML pages affected by your UI change, GodMode is an efficient way provided to help you. I'll leave setting up GodMode and how to run it for you to figure out as they are all in the resources linked in https://github.com/TEAMMATES/teammates/pull/8820#issuecomment-389539397.

**Comment by tshradheya** [comment]
Closing PR due to lack of activity. Feel free to reopen when you wish to resume work @jimmy51997

**Pull request closed without merging**
