### PR TITLE
Release V6.0.0 #8111

### LINKED ISSUE #8008: Update aboutUs page to reflect Aug 2017 team structure
@HirdayGupta @VamsiSangam @sujeet14108 @LimeTheCoder @Mynk96 @amarlearning can you post here suitable photos to be used in the [About Us](http://teammatesv4.appspot.com/about.jsp) page?

Requirements: clean background (no need to remove background), shoulders visible, 
Preferred: informally dressed, smiling :-)

### LINKED ISSUE #8111: Release V6.0.0
Scheduled for ~~October 29~~ ~~November 5~~ November 12, 2017, 11.59pm SGT.

This release will officially bring about the usages of Java 8 and Google Cloud SDK for development.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #8111 

I'll be doing something new: instead of using a separate issue to update the list of contributors, use the release issue to do the pre-release housekeeping which may encompass more items than just updating the list of contributors.

**Outline of Solution**

Since I'm releasing a rather new version (a bump in major version number!), I'm using this opportunity to update many stuffs that has not been updated for quite a long time:
- [x] List of contributors (as per usual)
- [x] Core team members (fixes #8008)
- [x] Remove unnecessary badges in README.md
  - Displaying LoC count is not a common practice; in fact I never see it done anywhere else. This is easily replaceable by the project stats in OpenHub.
  - Displaying number of users (or more precisely number of downloads) is quite a common practice, but this process is usually automated. When not automated this becomes a maintenance burden.
- [x] References to version numbers
- [x] Add [`CODE_OF_CONDUCT.md`](https://github.com/wkurniawan07/repo/blob/e188fc0efb2f0133b636de402e82ecb63de93d99/.github/CODE_OF_CONDUCT.md) as per [GitHub's community guideline](https://github.com/TEAMMATES/teammates/community)
- [x] Submissions count

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@damithc 
The new about page can be seen [here](http://teammates-wkurniawan07.appspot.com/about.jsp); a particular thing to look at is how core team members without picture is displayed.
Also this is a good time to update the submissions count. Do you happen to have the numbers?

**Comment by damithc** [comment]
Looks good:

Minor:
Perhaps the name can be bold (or bigger) so that it appears as important (or more important) than the role?
image

Also, if there are multiple devs without photos, there should be a  clear separation between each person.

> John
> Role
>
>Jane
>Role

instead of 

> John
> Role
>Jane
>Role

Entry count is 7 900 000. Can update with this PR or leave it as a first timer issue if we are short of those. I expect to get a wave of new contributors during December.

**Comment by wkurniawan07** [comment]
@damithc updated including the demo website with the suggested changes. As for when there are multiple devs without photos (currently hypothetical):
screen shot 2017-11-12 at 9 05 42 pm

**Comment by wkurniawan07** [comment]
> leave it as a first timer issue if we are short of those

@damithc we are never going to be short of these in the foreseeable future. I can come up with 10+ first-timer issues at any time if needed.

**Pull request merged**
