### PR TITLE
Show "Participants who have not responded to any question" panel in grey #3328

### LINKED ISSUE #3328: Show "Participants who have not responded to any question" panel in grey
Currently shown in orange, which should be used for warnings. we can use grey instead.

### PR DESCRIPTION
**Pull request by xpdavid**
Fixes #3328

Instead of writing new css, I change the panel class from "panel-warning" to "panel-default".

### CODE REVIEW

**Comment by xpdavid** [comment]
Ready for review

**Comment by damithc** [comment]
@xpdavid can post before-and-after screenshots?

**Comment by xpdavid** [comment]
Before:
screen shot 2017-01-11 at 8 31 31 pm
After:
screen shot 2017-01-11 at 8 32 15 pm

@damithc

**Comment by damithc** [comment]
UI change looks fine @xpdavid 
Let's wait for someone to review this PR.

**Comment by chowyb** [comment]
Looks good :+1:

**Pull request merged**
