### PR TITLE
Refactor instructorFeedbackResults<...>.js #5329

### LINKED ISSUE #5329: Refactor instructorFeedbackResults<...>.js
The content of these source files is almost identical. Only 'question' sort type has significant differences, but there are also common parts.
I propose to extract such common logic into one or some functions in instructorFeedbackResults.js

### PR DESCRIPTION
**Pull request by avocadomaster**
Fixes #5329 

Moved seeMoreRequest to commons lib instructorFeedbackResults.js

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@avocadomaster I recognize that this is done as part of a group project; can I get the names and GitHub handles of those involved to be duly credited?

**Comment by avocadomaster** [comment]
@gkrantz @matteushast @johnsv

**Comment by whipermr5** [comment]
@avocadomaster May we have @gkrantz and @johnsv's full names for inclusion into the contributors' list? :)

**Comment by johnsv** [comment]
Our full names are John Svanberg, Gustav Krantz and Matteus Hast.

**Pull request merged**
