### PR TITLE
InstructorHomePageUiTest: remove redundant reloading of previous page #7165 

### LINKED ISSUE #7165: InstructorHomePageUiTest: remove redundant reloading of previous page
Non Needed redirection in UInstructorHomePageUiTest 

 No need of redirection ( `homePage.goToPreviousPage(InstructorHomePage.class);` ) while testing remind button as the browser remains in the home page after sending a reminder

### PR DESCRIPTION
**Pull request by orinn248**
Fixes #7165 Remove redundant previous page reload on InstructorHomePageUiTest

I reviewed InstructorHomePageUITest to see the flow of the test. The previous page does not need to be navigated to after clicking the reminder link. Three previous page lines were removed that followed a reminder link click.  Afterwards, I ran the test again after the changes were made. The test functioned properly and regression checks passed.

### CODE REVIEW

**Comment by chowyb** [comment]
The changes in this PR seem fine, but please note that the PR title should have the issue number after the issue title, instead of before.

On a side note, it would also be better to submit a PR from a branch other than `master` on your fork, but as this is your first PR it should be fine to leave it as it is.

**Comment by orinn248** [comment]
Updated to place issue number after title

**Comment by whipermr5** [comment]
@orinn248 Please follow our [naming conventions](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr) _exactly_ :)

**Comment by chowyb** [comment]
Apologies for requesting another change, but I just realised that the PR title does not match the issue title; the PR title should contain the exact issue title with no modifications.

**Comment by orinn248** [comment]
Updated; I apologize for the multiple mix-ups.

**Pull request merged**
