### PR TITLE
In MobileView, text inside the menu is aligned on right side. #6864

### LINKED ISSUE #6864: In MobileView, text inside the menu is aligned on right side.
Text inside the menu in mobile view is aligned to `right side`. Not sure whether it's a feature or a bug?

screenshot from 2017-03-19 07-19-40

### PR DESCRIPTION
**Pull request by amarlearning**
Fixes #6864 

**Outline of Solution**

> removed the class `.text-right` from the menu items

### CODE REVIEW

**Comment by li-kai** [comment]
@amarlearning Using `important` is not a good practice. Please try an alternative.

**Comment by amarlearning** [comment]
@li-kai Getting build error, need help!

**Comment by li-kai** [comment]
@amarlearning Take a look at the build log in the build error. You will find `602:23  ✖  Unexpected unit   length-zero-no-unit`.

You should be able to fix this error easily.

**Comment by amarlearning** [comment]
@li-kai Please review

**Pull request merged**
