### PR TITLE
[#9559] Add a installation and overview guide on JMeter tool specifically to Teammates

### LINKED ISSUE #9559: Add guide for Continuous Profiling and Jmeter
**Description of feature/enhancement**
Add documentation for the Continuous Profiling process and set up of the tools used.

Guide can include list of conventions and best practices (like [this](https://www.blazemeter.com/blog/4-things-you-should-never-do-your-jmeter-script))

**Justification**

This will make it easier for other contributors to get started with running and creating new test plans, and improving the process.

### PR DESCRIPTION
**Pull request by jacoblipech**
Fixes #9559

- [x] Installation guide to JMeter for different users
- [ ] process of creating a JMeter
- [x] Processes involved in adding a test for Teammates (JSON generation, JMeter data config generation, jmx test plan) (completed in another PR)
- [ ] Overview of how JMeter works specifically in TEAMMATES's case
- [ ] List of conventions (naming, structure?)
    - eg. Don't specify `variableNames` in `CSVDataSet` config
- [ ] Selective list of best practices (refer to [project page](https://github.com/TEAMMATES/teammates/projects/7#card-18162975))
- [ ] Understanding necessary stages of TEAMMATES test plan (logging in, cookies, endpoint, response assertions)
- [ ] Brief explanation to understand how to interpret results (write scripts)

### CODE REVIEW

**Comment by wkurniawan07** [comment]
I have nothing against standalone tools, but see if you can use this instead: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin

**Comment by wkurniawan07** [comment]
Actually @jacoblipech how is this PR different from #9561?

**Comment by amrut-prabhu** [comment]
@wkurniawan07 This docs PR would be informational (vs instructional) and cover more high level details. Do you think this is too specific and should be left for contributors to figure out for themselves instead?

- [ ] Overview of how JMeter works specifically in TEAMMATES's case
- [ ] List of conventions (naming, structure?)
- [ ] Selective list of best practices (refer to [project page](https://github.com/TEAMMATES/teammates/projects/7#card-18162975))
- [ ] Processes involved in adding a test for Teammates (JSON generation, JMeter data config generation, jmx test plan)
  - [ ] Understanding necessary stages of TEAMMATES test plan (logging in, cookies, endpoint, response assertions)
- [ ] Brief explanation to understand how to interpret results?

**Comment by wkurniawan07** [comment]
@amrut-prabhu I am not concerned about the degree of specificity (at least not right now). I am just wondering why the need for separate PR between this and #9561.

**Comment by jacoblipech** [comment]
@wkurniawan07 Yes, it is possible to all work in PR. The reason we decided to separate this PR from #9561 as we hope to have a working sample test in JMeter first. After that, all 3 of us can refer to the PR and then we work on the enhancement

**Comment by wkurniawan07** [comment]
Closing as there is not a need for more L&P test documentation right now.

**Pull request closed without merging**
