### PR TITLE
UI tests against live server: update automated login to match new Google login page #7247

### LINKED ISSUE #7247: UI tests against live server: update automated login to match new Google login page
Google has introduced a new login page that doesn't match with our current login script used by UI tests.

image

Tests cannot be run against the live server until this is fixed.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7247

### CODE REVIEW

**Comment by damithc** [comment]
I tried running AdminHomePageUiTest using this code. It was able to handle the initial login page but failed at a later login page (confirmed after several tries).
```
[TestNG] Running:
  C:\Users\dcsdcr\.IntelliJIdea2016.3\system\temp-testng-customsuite.xml
[=============================teammates.test.cases.browsertests.AdminHomePageUiTest=============================]
Initializing Selenium: Using Firefox.
Custom path: C:\Program Files (x86)\Mozilla Firefox 38\firefox.exe
 * content: typical page
No 'sign into chrome' option
 * action fail & success: add multiple instructors
 * action success: displayed instructor details are properly HTML-encoded
 * action success : create instructor account and the account is created successfully after user's verification

org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"identifierId"}
Command duration or timeout: 6 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'damithch-d9010', ip: '172.26.184.136', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
*** Element info: {Using=id, value=identifierId}
Session ID: 74f91d56-6612-46a8-b295-af0077a6d41e
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=38.0.5}]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy10.getWrappedElement(Unknown Source)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:49)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators.addAll(Iterators.java:367)
	at com.google.common.collect.Lists.newArrayList(Lists.java:163)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:572)
	at teammates.test.pageobjects.AppPage.executeScript(AppPage.java:348)
	at teammates.test.pageobjects.AppPage.click(AppPage.java:475)
	at teammates.test.pageobjects.AppPage.fillTextBox(AppPage.java:483)
	at teammates.test.pageobjects.GoogleLoginPage.submitCredentials(GoogleLoginPage.java:93)
	at teammates.test.pageobjects.GoogleLoginPage.completeGoogleLoginSteps(GoogleLoginPage.java:68)
	at teammates.test.pageobjects.GoogleLoginPage.loginAsJoiningInstructor(GoogleLoginPage.java:114)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:160)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"identifierId"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'damithch-d9010', ip: '172.26.184.136', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/dcsdcr/AppData/Local/Temp/anonymous8615455584914881944webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
	at <anonymous class>.FirefoxDriver.prototype.findElement(file:///C:/Users/dcsdcr/AppData/Local/Temp/anonymous8615455584914881944webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10779)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/dcsdcr/AppData/Local/Temp/anonymous8615455584914881944webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/dcsdcr/AppData/Local/Temp/anonymous8615455584914881944webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/dcsdcr/AppData/Local/Temp/anonymous8615455584914881944webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12608)

teammates.test.cases.browsertests.AdminHomePageUiTest completed
```

**Comment by whipermr5** [comment]
@damithc 😅 Will look into it!

**Comment by whipermr5** [comment]
@damithc I was unable to reproduce that error on my staging server, Firefox 46, macOS (it runs until the original error of BACKDOOR_STATUS_FAILURE in the expected link). I've tried adding a wait step in the latest commit - does this work?

**Comment by whipermr5** [comment]
@damithc Oh I was able to reproduce - it happens when the username is remembered and only the password field is presented. Fixing

**Comment by damithc** [comment]
Oops, I should have noticed it myself when I was watching the tests. :-p

**Comment by whipermr5** [comment]
@damithc It should work now :)

**Comment by damithc** [comment]
The login page is working now 👍

**Comment by whipermr5** [comment]
@damithc Can I merge this to make developing #7255 easier?

**Comment by damithc** [comment]
> Can I merge this to make developing #7255 easier?

Sure

**Pull request merged**
