### PR TITLE
 Unable to add new questions on Chrome #5894 

### LINKED ISSUE #5894: Unable to add new questions on Chrome
On submitting the form for creating a new question, the button displays 'Saving' and gets disabled, but the form is not submitted.

Edit: Chrome 51.0.2704.103 m (64-bit)

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #5894

Tested on chrome/firefox

### CODE REVIEW

**Comment by rclakmal** [comment]
@kanghj @wkurniawan07 @damithc Can someone test this in IE too ?

**Comment by chowyb** [comment]
Running Windows 8, can confirm the form submission works for the following:

1. **Firefox 46**.0.1
2. **Chrome 51**.0.2704.106 m
3. **IE 11**.0.9600.18378

**Comment by wkurniawan07** [comment]
@rclakmal can you update this branch to be merged next? Sorry about the VersionEye thing, it's still in experimental stage, after your next push it should be gone.

**Comment by rclakmal** [comment]
@wkurniawan07 done.

**Pull request merged**
