### PR TITLE
[#12289] Usage statistics and logs page: Improve date/time input on mobile

### LINKED ISSUE #12289: Usage statistics and logs page: Improve date/time input on mobile
The display of the admin/maintainer usage statistics/logs pages on mobile are currently as follows:
photo_2023-03-28 14 00 34

photo_2023-03-28 14 00 37

The date/time inputs for both pages can be improved to be similar to the admin sessions page (shown below):
Screenshot 2023-03-28 at 15 19 15

### PR DESCRIPTION
**Pull request by aorlandou**
Fixes #12289

**Outline of Solution**

 
I made changes to the following files so that the hour selection is besides the date picker instead of below on mobiles:
- [logs-page.component.html](https://github.com/TEAMMATES/teammates/compare/master...aorlandou:teammates:team-mast?expand=1#diff-ee2477d2f4c61cebb26a8abf3bb8fb690a22ddff913400dfd322f51a01db0a80)
- [usage-statistics-page.component.html](https://github.com/TEAMMATES/teammates/compare/master...aorlandou:teammates:team-mast?expand=1#diff-7f560ba4f7dc66e249b704cb1f6a492222d8dac0fb4fa026a836241c18cff07c)

**Logs page after the changes**
logs after

**Usage Statistics page after the changes**
usage statistics after

### CODE REVIEW

**Review by cedricongjh — CHANGES_REQUESTED** [review]
hi @aorlandou, thank you for opening this PR.

Do fix the failing tests before we proceed to review this PR. Thank you!

**Comment by aorlandou** [comment]
Hey @cedricongjh, sorry for the late response I got caught up with work, but I will fix the failing tests today.

**Review by weiquu — APPROVED** [review]
LGTM!

**Review by cedricongjh — APPROVED** [review]
LGTM! thank you for your contribution to TEAMMATES

**Pull request merged**
