### PR TITLE
Use `Strings.isNullOrEmpty` instead of rolling our own `StringHelper.isEmpty` #7765

### LINKED ISSUE #7765: Use `Strings.isNullOrEmpty` instead of rolling our own `StringHelper.isEmpty`
~We should use Guava's `Strings.isNullOrEmpty` instead of creating our own `StringHelper.isEmpty`.~

~While the implementation is simple and unlikely to cause any problems, the overhead incurred in writing the tests was wasted. Furthermore, `isNullOrEmpty` is a better name than `isEmpty`.~

~EDIT:
As an example, in `StudentProfileAttributes#generateUpdateMessageForStudent`:~

~Change `StringHelper.isEmpty(shortName)` to `Strings.isNullOrEmpty(shortName)`~

---
This issue is currently being re-considered and will be updated when a conclusion has been reached.

The discussion of the issue begins here: https://github.com/TEAMMATES/teammates/pull/8013#issuecomment-326744059

Some possible reasons why this issue is to be rendered invalid so a related new issue is to be created:
https://github.com/TEAMMATES/teammates/pull/8013#issuecomment-335065025

### PR DESCRIPTION
**Pull request by kwilsonO**
Fixes #7765

**Outline of Solution**

I replaced all the calls of StringHelper.isEmpty with Strings.isNullOrEmpty.

I then, removed the StringHelper.isEmpty method and the corresponding test and replaced the calls from within StringHelper that were using it with Strings.isNullOrEmpty.

Question: Should I have tossed all the changes into a single commit, with one commit message?

### CODE REVIEW

**Comment by kwilsonO** [comment]
Whoops, looks like I failed the CI tests because I attempt to merge master into my change branch before the tests were finished running. My apologies if that causes issues!

**Comment by kwilsonO** [comment]
Awesome thanks @LimeTheCoder! When/how often should I merge the latest changes from master into my branch while it's waiting on review? I don't want to be wasting cycles on the CI server but I also know letting the branches get too far apart can be bad as well. Thanks for your help.

**Comment by wkurniawan07** [comment]
While this works, I'm wondering if `Strings.isNullOrEmpty` should be the method body of `StringHelper.isEmpty` instead. Doing it will decrease the number of components dependent to `com.google.common.base.Strings`. While `com.google.common.base.Strings` is a utility class whose import should not be restricted, it may be good if `StringHelper` can be a facade layer to that class (and many more) instead.
@LiHaoTan your opinions on this?

**Comment by LiHaoTan** [comment]
@wkurniawan07 I am thinking that instead of making lesser components depend on `com.google.common.base.Strings`, we should make more components depend on it? My rationale is to use Guava to fill in the gaps where the standard library fails to.

In this project at least, I do not really see any reason to have our own `StringHelper` class, since using a battle-tested open source library that already implements many features we need so we don't needlessly re-invent the wheel. Furthermore, as can be seen in our `StringHelper` class, we designed many things poorly.

Some examples:
`isWhiteSpace` is really `isBlank`, but what about the different types of whitespaces that Java defines? And the two instances where we use them could have been designed better and not depend on this altogether.
`getIndent` is very specific to `TEAMMATES`, not sure if there is any point in its existence but it does not really belong in a general `StringHelper` class.
`truncateHead` is also very specific to `TEAMMATES`, and I would argue that method should not exist in the first place.
`generateStringOfLength` could have a better name `repeat`

In my opinion, `StringHelper` should thus be renamed as either `StringExtras` (if there's somehow some things that Guava fail to implement but is general enough), or it should be renamed as a specific type of string helper, like `UIStringHelper` (though I'm not sure if it should be a string helper then).

I'm not sure if I missed something as to making `StringHelper` the canonical source for string utilities.

**Comment by wkurniawan07** [comment]
@LiHaoTan you seem to miss my point of contention. It is not the usage of `com.google.common.base.Strings` that I am concerned with; it is making more components (unnecessarily) dependent on it.

> we can use a battle-tested open source library that already implements many features required so we don't needlessly re-invent the wheel

I am against re-inventing the wheel (it is in fact a common anti-pattern many people fall for), but nowhere does making a `StringHelper` method a [facade](https://en.wikipedia.org/wiki/Facade_pattern) to `Strings` method making it "re-inventing the wheel".

> Furthermore, as can be seen in our StringHelper class, we designed many things poorly.

This I agree, along with your examples, but again not relevant to the point of contention.

Let me give you an example: if for some reason you find that `Strings#...` method is no longer compatible for us, would you like it better if you have to change it everywhere (your solution), or just change it in the facade class (`StringHelper` solution)? While you may be able to apply the same argument to `StringHelper#...`, this is more within our control since `StringHelper` is a self-authored class.

Take a look at our [Logger class](https://github.com/TEAMMATES/teammates/blob/master/src/main/java/teammates/common/util/Logger.java) and [JSON helper class](https://github.com/TEAMMATES/teammates/blob/master/src/main/java/teammates/common/util/JsonUtils.java). We could just as easily use `java.util.logging.Logger` and `com.google.gson.Gson`, but writing adapters to the actual implementation helps manage dependency and complexity.

**Comment by LiHaoTan** [comment]
@wkurniawan07 ah I see. The thing is, I feel controlling `StringHelper` is adding additional complexity. For instance in this case even if we use a facade, we would only need to skip the implementation but we still need to define the API, which also means writing tests.

That is why I rather depend on libraries. If we look at `Logger` and `JSONUtils` though I might see where `StringHelper` can be modified to behave similarly. But generally speaking `Logger` and `JSONUtils` is a higher level of abstraction than `java.util.logging.Logger` and `Gson`, so one of the benefits allow us to swap out the implementations.

Whereas methods such as `isNullOrEmpty` are what I would argue at the highest level of abstraction, and if possible I think should exist in a library, and only if it does not exist only do we create our own.

In some sense, since a good library would likely design such things better than us, I am not sure retaining control to the API or anything would benefit us. However, if the point is we somehow cannot find an appropriate library design philosophy that we agree with, then maybe we can implement our own.

For instance, Guava does keep the library as small and general as possible, and if we really believe that is not the right decision but yet we want to build top of the work they have already done, then I think we should have our own `StringHelper`.

However, what I think is that if we spend enough time to refactor our `StringHelper`, a large portion if not all of it can be removed. Though it would be at an awkward stage of mixing two string utility classes, so if we want to keep the state consistent at all time then I think a facade would make sense?

**Comment by whipermr5** [comment]
@LiHaoTan Is your conclusion that we should follow @wkurniawan07's suggestion of using `StringHelper` as a facade?

**Comment by wkurniawan07** [comment]
@LiHaoTan ping

**Comment by whipermr5** [comment]
@kwilsonO You might want to pick another first timer issue instead since this issue is still under discussion :)

**Comment by LiHaoTan** [comment]
@kwilsonO I am so sorry for the long wait and taking up your time, as @whipermr mentioned you might want to pick another `d.FirstTimers` issue.

@whipermr5 @wkurniawan07 

Sorry for the delay but I haven't got around to thinking about this but I am leaning towards keeping the status quo. Here are some of the thoughts I have currently and will update when I make time to think about this.

Some of the reasons are:

- If this PR is to be merged it means that we need to continue towards refactoring `StringHelper` and if there is no comment to indicate that it might not be ideal.
- Adding a comment may not distract developers if we have confidence that someone will take a look and help refactor `StringHelper` but it does not seem like we have sufficient resources to do so right now.
- Hence, the `StringHelper` has to be refactored completely otherwise things will be left in an inconsistent state for a long time.
- Yet adding a comment might unnecessarily distract the developers so it might be better to refactor `StringHelper` on a long-lived branch.
- Given the priority of the issue, there are other more important things TEAMMATES need work on than to focus on this right now.

**Comment by whipermr5** [comment]
I guess this PR should be closed then. Apologies @kwilsonO! You followed our contribution guidelines well 👍 If you open another PR to another first timer issue, we'd be happy to merge it.

@LiHaoTan Thanks for the inputs! Can you help edit the issue to reflect the above discussion and remove the `d.FirstTimers` label?

**Comment by LiHaoTan** [comment]
@whipermr5 updated the issue. Further discussion will continue on the issue.

**Pull request closed without merging**
