### PR TITLE
[#12020] Set generated app.admins field in build.properties to app_admin@gmail.com instead of app_admin

### LINKED ISSUE #12020: Set generated app.admins field in build.properties to app_admin@gmail.com instead of app_admin
**Background**: 
When starting the project for the first time, the admin account by default is 'app_admin'. However, when logging in to the platform, the field is labelled 'email'. This may cause confusion for first-time developers of TEAMMATEs. 
app.admins login

**Motivations for fixing**: 
Improve TEAMMATEs onboarding experience for new developers.  

**Environment**: 
Release [V8.20.0](https://github.com/TEAMMATES/teammates/releases/tag/V8.20.0) dev setup 

**Steps to reproduce**
Follow the developer setup guide in the [TEAMMATEs documentation](https://teammates.github.io/teammates/development.html) under the 'As administrator' section. 

**Expected behaviour**
Expected login info

**Actual behaviour**
Actual login info which may cause confusion

**Additional info**

This issue seems to be linked to Remove trimming of gmail.com for user accounts #11586.

### PR DESCRIPTION
**Pull request by NaveenJoyGit**
Updated build.template.properties fille value for app_admins from 'app_admin' to 'app_admin@gmail.com' Changed default value of input field for admin login from 'test@example.com' to 'app_admin@gmail.com' for a smoother experience.

Fixes #12020 

* Ready For Review

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

### CODE REVIEW

**Comment by NaveenJoyGit** [comment]
Please refer below images for review : 
login_page
landing_page

**Review by samuelfangjw — CHANGES_REQUESTED** [review]
Thanks for the PR!

Since you are already working on this, could you update the default value of app.maintainers (in build.properties) as well. It's the same issue as app_admin. You can test this out using the same method to log in to the dev server.

Thanks!

**Comment by NaveenJoyGit** [comment]
@samuelfangjw Sure. I can make those changes and update the PR

**Review by samuelfangjw — APPROVED** [review]
Thanks for contributing!

**Review by zhaojj2209 — APPROVED** [review]
LGTM, thanks for the changes!

**Pull request merged**
