### PR TITLE
Fixed Remove unused email html template for cleared pending comments #7564

### PR DESCRIPTION
**Pull request by stanislous**
Fixed that Remove userEmailTemplate-pendingCommentsCleared.html file from TEAMMATES in #7564 issue.

### CODE REVIEW

**Comment by whipermr5** [comment]
Hey @stanislous, each person is only allowed to do one first timer issue. Please choose between this and #7624, and close the other one :)

**Comment by whipermr5** [comment]
@stanislous Did you push to the wrong branch? The changes here look like they're for #7624.

**Comment by stanislous** [comment]
I fixed the #7257. Shall I need to open new pull request?

**Comment by whipermr5** [comment]
@stanislous You should fix #7257 in your #7624 PR, since this PR is about fixing #7564. Also, please close one of #7624 or #7625 (this PR), as [mentioned previously](https://github.com/TEAMMATES/teammates/pull/7625#issuecomment-311548385).

**Pull request closed without merging**
