### PR TITLE
Separate JavaScript constants into a Const object #3975

### LINKED ISSUE #3975: Separate JavaScript constants into a Const object
var const = {
    // so on and so forth
}
1. Reduces the pollution of the global namespace
2. Faster too because there will be less scope resolutions
3. More maintainable, we should have a const.js file instead of dumping them into common.js, common.js contains too much things at the moment

### PR DESCRIPTION
**Pull request by AnaghHegde**
Fixes #3975

I have created conts.js file and moved all the constants into constant object.

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@junhaoyap I didn't get why do we have to use `self-invoking` function on this as this object contains only contants.

**Comment by AnaghHegde** [comment]
Please delay the review.

**Comment by junhaoyap** [comment]
@AnaghHegde thank you for putting effort into this, the reason is to enable strict mode

I have also updated the issue in preparation for the ES6 migration where constants are allowed, cc @li-kai

**Comment by AnaghHegde** [comment]
@junhaoyap So do i need to wait for the migration thing to complete ?

>
ES6 migration where constants are allowed

What do you mean by constants are allowed ?

**Comment by wkurniawan07** [comment]
@AnaghHegde may I ask if you have experience in developing JavaScript?

**Comment by AnaghHegde** [comment]
@wkurniawan07 
> may I ask if you have experience in developing JavaScript?

When you say experience i don't know what all you expect me to know. But i do have experience in javascript(and other web techs).

**Comment by junhaoyap** [comment]
@AnaghHegde it is something new in ES6, refer to https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/const

cc @li-kai I believe we have some ES6 ready, could you kindly guide @AnaghHegde what you have done to allow ES6 and how he could start using consts in what you have set up? It will be a great test to starting to use ES6 in TEAMMATES as well

**Comment by wkurniawan07** [comment]
@AnaghHegde we have plans underway to migrate our JavaScript code base to a more modern standard and this issue happens to be on that roadmap, so I'd suggest you leave this issue for now. Thanks for your hard work!

Other than that, the reason I asked for your experience in JavaScript is because you are expected to know how to modify all the usages of those constants in all the affected JavaScript files. Lacking that knowledge, you will most likely try to make all tests pass by trial-and-error, which is not ideal. JavaScript and Java are only common as far as "Java" is part of their names; they are two entirely different programming languages.

**Pull request closed without merging**
