### PR TITLE
Student: submit responses: tick email confirmation option if the form is empty #8606

### LINKED ISSUE #8606: Student: submit responses: tick email confirmation option if the form is empty
Current: the email confirmation tick box is unticked by default.
image

Suggested: if the form is empty at loading, we can assume it is a first time submission, and tick the tickbox by default. 

Reason: it is ok to send the confirmation by default to first-time submission. That email will serve as proof of submission for students who claimed they submitted.

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #8606 

email confirmation box ticked by default 
in feedbackSubmissionForm.tag

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
ongoing test cases to be added

**Comment by damithc** [comment]
> Should we also do a check for an empty form (e.g. no responses at all in questions) before marking the checkbox as checked?

Tick by default only if the form is empty. Otherwise it should not be ticked by default.

**Comment by shaharyar-shamshi** [comment]
@tanhengyeow sir no problem You can work on your approach . Actually I thought you are not interested any more .

**Comment by tshradheya** [comment]
Closing this PR as @tanhengyeow has opened a PR for the issue and since this one isn't going to be worked upon https://github.com/TEAMMATES/teammates/pull/8692#issuecomment-375219052

**Pull request closed without merging**
