### PR TITLE
Instructor: remove unnecessary unboxing of Boolean value #7716

### LINKED ISSUE #7716: Instructor: remove unnecessary unboxing of Boolean value
In the `return` statement of `isDisplayedToStudents` in Instructor.java, the `Boolean` variable `isDisplayedToStudents` can be returned directly without unboxing it.

### PR DESCRIPTION
**Pull request by Surya-06**
Fixes #7716 

Removed the function call to booleanValue to avoid unnecessary unboxing of the boolean value.

Fixes #7716

### CODE REVIEW

**Comment by leeyimin** [comment]
@Surya-06 Sorry, I'm afraid I have to close this PR as you have already completed a first timer issue. I should noticed that earlier. You can take a look at d.Contributors issues 😄

**Comment by Surya-06** [comment]
@leeyimin Could you help me find some other issues I could help . I haven't seen much issues related to java in the issues tab under d.contributors tag

**Comment by leeyimin** [comment]
@Surya-06 Not many java related issues are labeled with t-Java so you have probably have to click into them to find out what they are about. One issue I found was #7060.

**Comment by Surya-06** [comment]
Thanks. I am a beginner and would like to contribute to issues requiring
Java. What else are required to tackle other issues ??

**Comment by leeyimin** [comment]
@Surya-06 You can learn about the different technologies we use through our [orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) and other related documentations which you can find [here](https://github.com/TEAMMATES/teammates/blob/master/docs/README.md).

**Pull request closed without merging**
