### PR TITLE
[#12313] Instructor sending submission reminders: missing space between checkbox and label

### LINKED ISSUE #12313: Instructor sending submission reminders: missing space between checkbox and label
v8.15, production

image

Perhaps already fixed in the current master. Posting here just in case.

### PR DESCRIPTION
**Pull request by hansen454**
Fixes #12313

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [ ] Added the issue number to the "Fixes" keyword above
  - [ ] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ ] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [x] Added/updated tests, if changes in functionality were involved
- [x] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**
I solved the missing space issue by adding an HTML non breaking space (&nbsp;) before the label text for each label.

### CODE REVIEW

**Comment by hansen454** [comment]
Hi @weiquu, sorry about that! I didn’t quite understand what the process was as this is my first time committing to an open source project and I didn’t realize someone else was working on it. I will make sure to double check in the future!

**Review by weiquu — CHANGES_REQUESTED** [review]
Hi @hansen454, the current fix works but let's try to standardise it for consistency. If you refer to [this comment](https://github.com/TEAMMATES/teammates/pull/12151#issuecomment-1454297677), most cases of 'checkbox followed by text' are resolved by using the `form-check` class on the surrounding `div`. You can refer to the [Bootstrap documentation](https://getbootstrap.com/docs/5.0/forms/checks-radios/) for more information. (Note that you might need to introduce additional `div`s in this particular scenario.)

Since `.form-check` automatically improves the layout and helps with consistency, I think using that would be a better option. Do let me know if you agree.

**Comment by hansen454** [comment]
Hi @weiquu, I agree that it would be better to follow a more consistent approach. I will try to make my solution fit that instead.

**Review by weiquu — CHANGES_REQUESTED** [review]
Hi @hansen454, note the following issues with the current changes (screenshot provided below):
- Checkboxes not present for the second option on the line
- Extra space between checkbox and text
Screenshot 2023-04-14 at 11 42 37 PM

Do make the necessary adjustments and request another review when you're ready. Thanks!

**Comment by hansen454** [comment]
Hello, that is strange because when I view the changes on my local host, each label has its own checkbox but I will try to fix that this morning

**Comment by weiquu** [comment]
Hi @hansen454, I'm not sure if your PR is ready for another review, but just note that the 2 issues pointed out above haven't been resolved with the latest changes. Do re-request a review / let us know when you're ready!

**Comment by zhaojj2209** [comment]
> Hi @hansen454, note the following issues with the current changes (screenshot provided below):
> 
> * Checkboxes not present for the second option on the line
> * Extra space between checkbox and text

The checkboxes not being present for the second column is because each `form-check` div contains two sets of inputs and labels instead of one. Also, `form-check` automatically adds space between the checkbox and the label, so the extra `&nbsp;` is longer necessary. This is what is causing the extra space.

In addition to the above changes, please also fix the indentation of the tags. Each indentation should be two spaces, not one space.

**Comment by zhaojj2209** [comment]
@hansen454 Please ensure your PR works and fix all tests before requesting for review.

**Comment by zhaojj2209** [comment]
Closing due to inactivity.

**Pull request closed without merging**
