### PR TITLE
InstructorFeedbackEditPage: correct variable name #7941

### LINKED ISSUE #7941: InstructorFeedbackEditPage: correct variable name
In `fillRubricDescriptionBox()` method of `InstructorFeedbackEditPage.java`, we find the rubric description box by ID and fill it. But the variable has been named as `subQnBox`, which is confusing. Change the variable name. `descBox` might be a good name.

**Scope of issue**

Change these lines -

``` java
WebElement subQnBox = browser.driver.findElement(By.id(elemId));
fillTextBox(subQnBox, description);
```

to

``` java
WebElement descBox = browser.driver.findElement(By.id(elemId));
fillTextBox(descBox, description);
```

### PR DESCRIPTION
**Pull request by lehighjcut**
Fixes #7941

### CODE REVIEW

**Comment by VamsiSangam** [comment]
@whipermr5 this PR is ready to be reviewed by a senior dev.

**Comment by HirdayGupta** [comment]
@lehighjcut As per our [contributing guidelines for submitting a PR](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr), please rename your PR title to exactly match the title of the issue it is fixing. In this case, you should rename it to `InstructorFeedbackEditPage.java : correct variable name #7941`.

**Comment by whipermr5** [comment]
@lehighjcut Thanks for your contribution! Do take note of what @HirdayGupta said [above](https://github.com/TEAMMATES/teammates/pull/7944#issuecomment-322535206) for future PRs - I've helped you correct it this time.

**Comment by lehighjcut** [comment]
@whipermr5 Thanks for doing the merge for me haha was super busy day at work these past two days and was finally about to get to it now but glad it's already done :)

**Pull request merged**
