### PR TITLE
[#9773] Student course detail page: Standardize picture size and title length

### LINKED ISSUE #9773: Student course detail page: Standardize picture size and title length
- **Environment**:  `master` branch at commit ad2d071317e2b1c70139daf43148219cf859f0db

**Steps to reproduce**
1. login as a student who has teammates, some teammates have their profile photo whose size is large
2. click the `View team` button in home page

**Actual behaviour**
Captureccccccc

**Expected behaviour**
the picture and title length should be standardized so that the details of students are aligned.

### PR DESCRIPTION
**Pull request by hcwong**
Fixes #9773 

**PR Checklist**

**Outline of Solution**

Make image size not exceed bounds by setting a max-width. This preserves aspect ratio but images which are more landscape will now not occupy the whole height, as expected. Screenshot below for reference

Screen Shot 2020-02-01 at 12 20 33 PM

### CODE REVIEW

**Comment by hcwong** [comment]
> Hi @hcwong , again, sorry for the delay. You might want to think a bit more about this, because although your fix solves the problem for horizontally long pictures, it will be a bit strange for vertically long pictures. I have attached a screenshot here as an example:
> 
> image
> 
> whereas the current `master` branch does not have this problem but a problem with horizontally long pictures. Can you have a fix which handles both cases?

Hey Joanne, I don't think theres a way (did some research, but may be wrong), to control both responsively. I've opted to keep the max width approach, and for the outliers like vertically long pictures, it will be cropped by the `max-height: 240px` line. Hopefully this should preserve the aspect ratio

**Comment by hcwong** [comment]
Hey @wkurniawan07, is the above approach fine? thanks!

**Comment by joanneong** [comment]
Hi @xpdavid , maybe you can take a quick look at this?

**Comment by xpdavid** [comment]
Looks good :)

**Pull request merged**
