### PR TITLE
Instructor: response comments: fix misalignment of edit/delete buttons #7719

### LINKED ISSUE #7719: Instructor: response comments: fix misalignment of edit/delete buttons
For comments on InstructorFeedbackResultsPage and InstructorStudentRecordsPage, the edit and delete buttons can be out of line if the comment details are long enough.

push

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7719 

**Outline of solution**

- Used bootstrap to achieve the desired changes.
- Added `row` class to `commentBar` parent div
- Surrounded the comment details and `eye icon` with a `col-xs-10`
- Surrounded the edit and delete buttons with `col-xs-2`

**Screenshot of change:**
(Old behaviour can be seen in issue description)

New behaviour:

**Option 1:** (`10-2`)
screen shot 2017-07-22 at 4 45 08 am

Note: we can also change the distribution of bootstrap columns to 11-1. This would make the comment bar look like this:

**Option 2:** (`11-1`)
screen shot 2017-07-22 at 4 43 56 am

Depending on whatever looks better according to everyone, we can finalise between `10-2` and `11-1` and then I will go ahead with god mode.

### CODE REVIEW

**Comment by HirdayGupta** [comment]
Forgot to add, the changes here have the benefit of the comment bar looking exactly as expected on all screen sizes.

**Comment by thenaesh** [comment]
@HirdayGupta Is this ready for review?

**Comment by HirdayGupta** [comment]
@thenaesh yep, just let me know which of the two UI options you like from the screenshots I've posted in the PR description.

**Comment by HirdayGupta** [comment]
@thenaesh the PR isn't ongoing, I'm waiting for input from a senior dev to choose between the two UI options I've posted in the PR description.

**Comment by chowyb** [comment]
It would probably be best for @damithc to decide on this, but my own opinion of this would be to use `10-2`, since this does not change the positions of the buttons, causing a need for users to "relearn" the buttons. However, if there is a compelling advantage for `11-1` over `10-2` such that relearning is a small price to pay, then using `11-1` should be done.

**Comment by damithc** [comment]
> It would probably be best for @damithc to decide on this, but my own opinion of this would be to use 10-2, since this does not change the positions of the buttons, causing a need for users to "relearn" the buttons.

I prefer 10-2 too.

**Comment by HirdayGupta** [comment]
Thanks for the input @chowyb @damithc! :)

If nothing else is to be changed about the code, may I go ahead with god mode?

**Comment by chowyb** [comment]
@HirdayGupta yep, looks good 👍

**Comment by HirdayGupta** [comment]
@chowyb Dropping a note that I rebased my branch and force pushed instead of merging as there was only one (now two) of my own commits.

**Comment by HirdayGupta** [comment]
@chowyb Ready for review :)

**Pull request merged**
