### PR TITLE
[#10655] Fix getRecipientsOfQuestion in FeedbackQuestionsLogic

### LINKED ISSUE #10665: Instructors cannot give feedback to teams
Question setting:
image

When previewed as an instructor:
image

In V6:
image

### PR DESCRIPTION
**Pull request by madanalogy**
Fixes #10665

### CODE REVIEW

**Review by wkurniawan07 — APPROVED** [review]
LGTM

**Comment by damithc** [comment]
@madanalogy commit message format deviation?
image

**Comment by damithc** [comment]
Fix deployed as v7.0.4

**Comment by madanalogy** [comment]
> @madanalogy commit message format deviation?

Yes sorry I merged this from the GitHub mobile app and it didn't give me the option to edit the commit message. I'll only merge PRs from my desktop from now on.

**Pull request merged**
